; global data symbols, MUST directly follow function_pointers

; class GameWorld ou; // RVA = 0x2131020 Global
?ou@@3PEAVGameWorld@@EA proc EXPORT
QWORD 0
?ou@@3PEAVGameWorld@@EA endp

; class GlobalConstants con; // RVA = 0x2130CE0 Global
?con@@3PEAVGlobalConstants@@EA proc EXPORT
QWORD 0
?con@@3PEAVGlobalConstants@@EA endp

; class InputHandler key; // RVA = 0x2130290 Global
?key@@3PEAVInputHandler@@EA proc EXPORT
QWORD 0
?key@@3PEAVInputHandler@@EA endp

; class OptionsHolder options; // RVA = 0x21303B0 Global
?options@@3PEAVOptionsHolder@@EA proc EXPORT
QWORD 0
?options@@3PEAVOptionsHolder@@EA endp