
?_CONSTRUCTOR@AABB2D@@QEAAPEAV1@AEBVVector4@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@AABB2D@@QEAAPEAV1@AEBVVector4@Ogre@@@Z endp

; AABB2D::AABB2D(const class Ogre::Vector4 &);
??0AABB2D@@QEAA@AEBVVector4@Ogre@@@Z proc EXPORT
jmp function_pointers[_AABB2D_base+0*8]
??0AABB2D@@QEAA@AEBVVector4@Ogre@@@Z endp

?_CONSTRUCTOR@AABB2D@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AABB2D@@QEAAPEAV1@XZ endp

; AABB2D::AABB2D();
??0AABB2D@@QEAA@XZ proc EXPORT
jmp function_pointers[_AABB2D_base+1*8]
??0AABB2D@@QEAA@XZ endp

; AABB2D::setNull();
?setNull@AABB2D@@QEAAXXZ proc EXPORT
jmp function_pointers[_AABB2D_base+2*8]
?setNull@AABB2D@@QEAAXXZ endp

; AABB2D::pointWithin(const class Ogre::Vector3 &);
?pointWithin@AABB2D@@QEBA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AABB2D_base+3*8]
?pointWithin@AABB2D@@QEBA_NAEBVVector3@Ogre@@@Z endp

; AABB2D::inflate(float);
?inflate@AABB2D@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AABB2D_base+4*8]
?inflate@AABB2D@@QEAAXM@Z endp

; AABB2D::sizeX();
?sizeX@AABB2D@@QEBAMXZ proc EXPORT
jmp function_pointers[_AABB2D_base+5*8]
?sizeX@AABB2D@@QEBAMXZ endp

; AABB2D::sizeY();
?sizeY@AABB2D@@QEBAMXZ proc EXPORT
jmp function_pointers[_AABB2D_base+6*8]
?sizeY@AABB2D@@QEBAMXZ endp

; AABB2D::intersects(const class Ogre::Vector3 &, float);
?intersects@AABB2D@@QEBA_NAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_AABB2D_base+7*8]
?intersects@AABB2D@@QEBA_NAEBVVector3@Ogre@@M@Z endp

; AABB2D::intersects(const class AABB2D &);
?intersects@AABB2D@@QEBA_NAEBV1@@Z proc EXPORT
jmp function_pointers[_AABB2D_base+8*8]
?intersects@AABB2D@@QEBA_NAEBV1@@Z endp

; AABB2D::intersects(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?intersects@AABB2D@@QEBA_NAEBVVector3@Ogre@@0@Z proc EXPORT
jmp function_pointers[_AABB2D_base+9*8]
?intersects@AABB2D@@QEBA_NAEBVVector3@Ogre@@0@Z endp

; AABB2D::intersects2(const class Ogre::Vector2 &, const class Ogre::Vector2 &);
?intersects2@AABB2D@@QEBA?AVVector2@Ogre@@AEBV23@0@Z proc EXPORT
jmp function_pointers[_AABB2D_base+10*8]
?intersects2@AABB2D@@QEBA?AVVector2@Ogre@@AEBV23@0@Z endp
