
?_CONSTRUCTOR@AbstractMovementBase@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AbstractMovementBase@@QEAAPEAV1@XZ endp

; AbstractMovementBase::AbstractMovementBase();
??0AbstractMovementBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+0*8]
??0AbstractMovementBase@@QEAA@XZ endp

?_DESTRUCTOR@AbstractMovementBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AbstractMovementBase@@QEAAXXZ endp

; AbstractMovementBase::~AbstractMovementBase();
??1AbstractMovementBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+1*8]
??1AbstractMovementBase@@UEAA@XZ endp

; AbstractMovementBase::create(class Ogre::Vector3);
?create@AbstractMovementBase@@QEAAXVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+2*8]
?create@AbstractMovementBase@@QEAAXVVector3@Ogre@@@Z endp

?_NV_getHandle@AbstractMovementBase@@QEAA?AVhand@@XZ proc EXPORT
?_NV_getHandle@AbstractMovementBase@@QEAA?AVhand@@XZ endp

; AbstractMovementBase::getHandle();
?getHandle@AbstractMovementBase@@UEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+3*8]
?getHandle@AbstractMovementBase@@UEAA?AVhand@@XZ endp

?_NV__setPositionAndTeleport@AbstractMovementBase@@QEAAXVVector3@Ogre@@H@Z proc EXPORT
?_NV__setPositionAndTeleport@AbstractMovementBase@@QEAAXVVector3@Ogre@@H@Z endp

; AbstractMovementBase::_setPositionAndTeleport(class Ogre::Vector3, int);
?_setPositionAndTeleport@AbstractMovementBase@@UEAAXVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+4*8]
?_setPositionAndTeleport@AbstractMovementBase@@UEAAXVVector3@Ogre@@H@Z endp

?_NV__setPositionSimple@AbstractMovementBase@@QEAAXVVector3@Ogre@@@Z proc EXPORT
?_NV__setPositionSimple@AbstractMovementBase@@QEAAXVVector3@Ogre@@@Z endp

; AbstractMovementBase::_setPositionSimple(class Ogre::Vector3);
?_setPositionSimple@AbstractMovementBase@@UEAAXVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+5*8]
?_setPositionSimple@AbstractMovementBase@@UEAAXVVector3@Ogre@@@Z endp

?_NV_faceDirection@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_faceDirection@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@@Z endp

; AbstractMovementBase::faceDirection(const class Ogre::Vector3 &);
?faceDirection@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+6*8]
?faceDirection@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_lookatPosition@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_lookatPosition@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@@Z endp

; AbstractMovementBase::lookatPosition(const class Ogre::Vector3 &);
?lookatPosition@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+7*8]
?lookatPosition@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_getPosition@AbstractMovementBase@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@AbstractMovementBase@@QEBAAEBVVector3@Ogre@@XZ endp

; AbstractMovementBase::getPosition();
?getPosition@AbstractMovementBase@@UEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+8*8]
?getPosition@AbstractMovementBase@@UEBAAEBVVector3@Ogre@@XZ endp

; AbstractMovementBase::getFacingDirection();
?getFacingDirection@AbstractMovementBase@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+9*8]
?getFacingDirection@AbstractMovementBase@@QEBAAEBVVector3@Ogre@@XZ endp

; AbstractMovementBase::getDestination();
?getDestination@AbstractMovementBase@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+10*8]
?getDestination@AbstractMovementBase@@QEBA?AVVector3@Ogre@@XZ endp

; AbstractMovementBase::isProbablyStuck();
?isProbablyStuck@AbstractMovementBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+11*8]
?isProbablyStuck@AbstractMovementBase@@QEBA_NXZ endp

?_NV_pathOk@AbstractMovementBase@@QEBA_NXZ proc EXPORT
?_NV_pathOk@AbstractMovementBase@@QEBA_NXZ endp

; AbstractMovementBase::pathOk();
?pathOk@AbstractMovementBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+12*8]
?pathOk@AbstractMovementBase@@UEBA_NXZ endp

?_NV_pathFailed@AbstractMovementBase@@QEBA_NXZ proc EXPORT
?_NV_pathFailed@AbstractMovementBase@@QEBA_NXZ endp

; AbstractMovementBase::pathFailed();
?pathFailed@AbstractMovementBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+13*8]
?pathFailed@AbstractMovementBase@@UEBA_NXZ endp

?_NV_update@AbstractMovementBase@@QEAAXM@Z proc EXPORT
?_NV_update@AbstractMovementBase@@QEAAXM@Z endp

; AbstractMovementBase::update(float);
?update@AbstractMovementBase@@UEAAXM@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+14*8]
?update@AbstractMovementBase@@UEAAXM@Z endp

?_NV_isDestinationReached@AbstractMovementBase@@QEBA_NXZ proc EXPORT
?_NV_isDestinationReached@AbstractMovementBase@@QEBA_NXZ endp

; AbstractMovementBase::isDestinationReached();
?isDestinationReached@AbstractMovementBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+15*8]
?isDestinationReached@AbstractMovementBase@@UEBA_NXZ endp

?_NV_amInsideTownWalls@AbstractMovementBase@@QEAAHXZ proc EXPORT
?_NV_amInsideTownWalls@AbstractMovementBase@@QEAAHXZ endp

; AbstractMovementBase::amInsideTownWalls();
?amInsideTownWalls@AbstractMovementBase@@UEAAHXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+16*8]
?amInsideTownWalls@AbstractMovementBase@@UEAAHXZ endp

?_NV_manualMovement@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_manualMovement@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@@Z endp

; AbstractMovementBase::manualMovement(const class Ogre::Vector3 &);
?manualMovement@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+17*8]
?manualMovement@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_setDestination@AbstractMovementBase@@QEAAXPEAVBuilding@@W4UpdatePriority@@@Z proc EXPORT
?_NV_setDestination@AbstractMovementBase@@QEAAXPEAVBuilding@@W4UpdatePriority@@@Z endp

; AbstractMovementBase::setDestination(class Building *, enum UpdatePriority);
?setDestination@AbstractMovementBase@@UEAAXPEAVBuilding@@W4UpdatePriority@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+18*8]
?setDestination@AbstractMovementBase@@UEAAXPEAVBuilding@@W4UpdatePriority@@@Z endp

?_NV_setDestination@AbstractMovementBase@@QEAAXPEAVCharacter@@W4UpdatePriority@@@Z proc EXPORT
?_NV_setDestination@AbstractMovementBase@@QEAAXPEAVCharacter@@W4UpdatePriority@@@Z endp

; AbstractMovementBase::setDestination(class Character *, enum UpdatePriority);
?setDestination@AbstractMovementBase@@UEAAXPEAVCharacter@@W4UpdatePriority@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+19*8]
?setDestination@AbstractMovementBase@@UEAAXPEAVCharacter@@W4UpdatePriority@@@Z endp

?_NV_setDestination@AbstractMovementBase@@QEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z proc EXPORT
?_NV_setDestination@AbstractMovementBase@@QEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z endp

; AbstractMovementBase::setDestination(class RootObjectBase *, enum UpdatePriority);
?setDestination@AbstractMovementBase@@UEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+20*8]
?setDestination@AbstractMovementBase@@UEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z endp

?_NV_setDestination@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z proc EXPORT
?_NV_setDestination@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z endp

; AbstractMovementBase::setDestination(const class Ogre::Vector3 &, enum UpdatePriority, bool);
?setDestination@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+21*8]
?setDestination@AbstractMovementBase@@UEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z endp

?_NV_halt@AbstractMovementBase@@QEAAXXZ proc EXPORT
?_NV_halt@AbstractMovementBase@@QEAAXXZ endp

; AbstractMovementBase::halt();
?halt@AbstractMovementBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+22*8]
?halt@AbstractMovementBase@@UEAAXXZ endp

; AbstractMovementBase::setRoadDestination(const class Ogre::Vector3 &);
?setRoadDestination@AbstractMovementBase@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+23*8]
?setRoadDestination@AbstractMovementBase@@QEAA_NAEBVVector3@Ogre@@@Z endp

; AbstractMovementBase::setRoadPreference(float);
?setRoadPreference@AbstractMovementBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+24*8]
?setRoadPreference@AbstractMovementBase@@QEAAXM@Z endp

; AbstractMovementBase::extractRoadFollower();
?extractRoadFollower@AbstractMovementBase@@QEAAPEAVRoadFollower@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+25*8]
?extractRoadFollower@AbstractMovementBase@@QEAAPEAVRoadFollower@@XZ endp

; AbstractMovementBase::setCurrentRoadFollower(const class Ogre::Vector3 &, class RoadFollower *);
?setCurrentRoadFollower@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@PEAVRoadFollower@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+26*8]
?setCurrentRoadFollower@AbstractMovementBase@@QEAAXAEBVVector3@Ogre@@PEAVRoadFollower@@@Z endp

?_NV_setPatrolInput@AbstractMovementBase@@QEAAXAEAVPatrolInfo@@@Z proc EXPORT
?_NV_setPatrolInput@AbstractMovementBase@@QEAAXAEAVPatrolInfo@@@Z endp

; AbstractMovementBase::setPatrolInput(class PatrolInfo &);
?setPatrolInput@AbstractMovementBase@@UEAAXAEAVPatrolInfo@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+27*8]
?setPatrolInput@AbstractMovementBase@@UEAAXAEAVPatrolInfo@@@Z endp

?_NV_setDesiredSpeed@AbstractMovementBase@@QEAAXW4MoveSpeed@@@Z proc EXPORT
?_NV_setDesiredSpeed@AbstractMovementBase@@QEAAXW4MoveSpeed@@@Z endp

; AbstractMovementBase::setDesiredSpeed(enum MoveSpeed);
?setDesiredSpeed@AbstractMovementBase@@UEAAXW4MoveSpeed@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+28*8]
?setDesiredSpeed@AbstractMovementBase@@UEAAXW4MoveSpeed@@@Z endp

; AbstractMovementBase::setDesiredSpeed(float);
?setDesiredSpeed@AbstractMovementBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+29*8]
?setDesiredSpeed@AbstractMovementBase@@QEAAXM@Z endp

; AbstractMovementBase::setDesiredSpeedOrders(enum MoveSpeed);
?setDesiredSpeedOrders@AbstractMovementBase@@QEAAXW4MoveSpeed@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+30*8]
?setDesiredSpeedOrders@AbstractMovementBase@@QEAAXW4MoveSpeed@@@Z endp

; AbstractMovementBase::setDesiredSpeedOrders(float);
?setDesiredSpeedOrders@AbstractMovementBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+31*8]
?setDesiredSpeedOrders@AbstractMovementBase@@QEAAXM@Z endp

; AbstractMovementBase::setStandardWalkSpeed(float);
?setStandardWalkSpeed@AbstractMovementBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+32*8]
?setStandardWalkSpeed@AbstractMovementBase@@QEAAXM@Z endp

; AbstractMovementBase::getStandardWalkSpeed();
?getStandardWalkSpeed@AbstractMovementBase@@QEAAMXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+33*8]
?getStandardWalkSpeed@AbstractMovementBase@@QEAAMXZ endp

; AbstractMovementBase::restoreDesiredSpeed();
?restoreDesiredSpeed@AbstractMovementBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+34*8]
?restoreDesiredSpeed@AbstractMovementBase@@QEAAXXZ endp

; AbstractMovementBase::setMaxSpeed(float);
?setMaxSpeed@AbstractMovementBase@@QEAAXM@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+35*8]
?setMaxSpeed@AbstractMovementBase@@QEAAXM@Z endp

; AbstractMovementBase::getMaxSpeed();
?getMaxSpeed@AbstractMovementBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+36*8]
?getMaxSpeed@AbstractMovementBase@@QEBAMXZ endp

; AbstractMovementBase::isCurrentlyMoving();
?isCurrentlyMoving@AbstractMovementBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+37*8]
?isCurrentlyMoving@AbstractMovementBase@@QEBA_NXZ endp

; AbstractMovementBase::getCurrentSpeed();
?getCurrentSpeed@AbstractMovementBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+38*8]
?getCurrentSpeed@AbstractMovementBase@@QEBAMXZ endp

; AbstractMovementBase::getCurrentMotion();
?getCurrentMotion@AbstractMovementBase@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+39*8]
?getCurrentMotion@AbstractMovementBase@@QEBA?AVVector3@Ogre@@XZ endp

; AbstractMovementBase::getCurrentSpeedRelativeToMax01();
?getCurrentSpeedRelativeToMax01@AbstractMovementBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+40*8]
?getCurrentSpeedRelativeToMax01@AbstractMovementBase@@QEBAMXZ endp

; AbstractMovementBase::getSpeedOrders();
?getSpeedOrders@AbstractMovementBase@@QEBA?AW4MoveSpeed@@XZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+41*8]
?getSpeedOrders@AbstractMovementBase@@QEBA?AW4MoveSpeed@@XZ endp

; AbstractMovementBase::leaveSpeedGroup();
?leaveSpeedGroup@AbstractMovementBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+42*8]
?leaveSpeedGroup@AbstractMovementBase@@QEAAXXZ endp

?_NV_onShapeHit@AbstractMovementBase@@QEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z proc EXPORT
?_NV_onShapeHit@AbstractMovementBase@@QEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z endp

; AbstractMovementBase::onShapeHit(const struct NxControllerShapeHit &);
?onShapeHit@AbstractMovementBase@@UEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+43*8]
?onShapeHit@AbstractMovementBase@@UEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z endp

?_NV_onControllerHit@AbstractMovementBase@@QEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z proc EXPORT
?_NV_onControllerHit@AbstractMovementBase@@QEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z endp

; AbstractMovementBase::onControllerHit(const struct NxControllersHit &);
?onControllerHit@AbstractMovementBase@@UEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z proc EXPORT
jmp function_pointers[_AbstractMovementBase_base+44*8]
?onControllerHit@AbstractMovementBase@@UEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z endp
