
?_NV_loadFromDisk@ActivePlatoon@@QEAA_N_NPEAVSerialisable@@@Z proc EXPORT
?_NV_loadFromDisk@ActivePlatoon@@QEAA_N_NPEAVSerialisable@@@Z endp

; ActivePlatoon::loadFromDisk(bool, class Serialisable *);
?loadFromDisk@ActivePlatoon@@UEAA_N_NPEAVSerialisable@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+0*8]
?loadFromDisk@ActivePlatoon@@UEAA_N_NPEAVSerialisable@@@Z endp

; ActivePlatoon::_recalculateIsIntact();
?_recalculateIsIntact@ActivePlatoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+1*8]
?_recalculateIsIntact@ActivePlatoon@@QEAA_NXZ endp

; ActivePlatoon::isAnyoneCaptured();
?isAnyoneCaptured@ActivePlatoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+2*8]
?isAnyoneCaptured@ActivePlatoon@@QEAA_NXZ endp

?_DESTRUCTOR@ActivePlatoon@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::~ActivePlatoon();
??1ActivePlatoon@@UEAA@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+3*8]
??1ActivePlatoon@@UEAA@XZ endp

; ActivePlatoon::getGroupSense();
?getGroupSense@ActivePlatoon@@QEAAPEAVGroupSense@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+4*8]
?getGroupSense@ActivePlatoon@@QEAAPEAVGroupSense@@XZ endp

; ActivePlatoon::getMemory();
?getMemory@ActivePlatoon@@QEAAPEAVCharacterMemory@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+5*8]
?getMemory@ActivePlatoon@@QEAAPEAVCharacterMemory@@XZ endp

?_NV_removeObject@ActivePlatoon@@QEAA_NPEAVRootObject@@@Z proc EXPORT
?_NV_removeObject@ActivePlatoon@@QEAA_NPEAVRootObject@@@Z endp

; ActivePlatoon::removeObject(class RootObject *);
?removeObject@ActivePlatoon@@UEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+6*8]
?removeObject@ActivePlatoon@@UEAA_NPEAVRootObject@@@Z endp

?_NV_addActiveObject@ActivePlatoon@@QEAA_NPEAVRootObject@@@Z proc EXPORT
?_NV_addActiveObject@ActivePlatoon@@QEAA_NPEAVRootObject@@@Z endp

; ActivePlatoon::addActiveObject(class RootObject *);
?addActiveObject@ActivePlatoon@@UEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+7*8]
?addActiveObject@ActivePlatoon@@UEAA_NPEAVRootObject@@@Z endp

; ActivePlatoon::addCharacterAt(class RootObject *, int);
?addCharacterAt@ActivePlatoon@@QEAAXPEAVRootObject@@H@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+8*8]
?addCharacterAt@ActivePlatoon@@QEAAXPEAVRootObject@@H@Z endp

; ActivePlatoon::swapCharacters(int, int);
?swapCharacters@ActivePlatoon@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+9*8]
?swapCharacters@ActivePlatoon@@QEAAXHH@Z endp

; ActivePlatoon::emptySquadCheck();
?emptySquadCheck@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+10*8]
?emptySquadCheck@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::clearAllTheUniqueNPCStates();
?clearAllTheUniqueNPCStates@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+11*8]
?clearAllTheUniqueNPCStates@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::isIntact();
?isIntact@ActivePlatoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+12*8]
?isIntact@ActivePlatoon@@QEAA_NXZ endp

; ActivePlatoon::getCharactersInArea(class lektor<RootObject *> &, const class Ogre::Vector3 &, float, bool);
?getCharactersInArea@ActivePlatoon@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@M_N@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+13*8]
?getCharactersInArea@ActivePlatoon@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@M_N@Z endp

; ActivePlatoon::getSquadLeader_theRealOne();
?getSquadLeader_theRealOne@ActivePlatoon@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+14*8]
?getSquadLeader_theRealOne@ActivePlatoon@@QEAAPEAVCharacter@@XZ endp

; ActivePlatoon::getNearestActiveCharacter(const class Ogre::Vector3 &, int);
?getNearestActiveCharacter@ActivePlatoon@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+15*8]
?getNearestActiveCharacter@ActivePlatoon@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@H@Z endp

; ActivePlatoon::getSquadLeader();
?getSquadLeader@ActivePlatoon@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+16*8]
?getSquadLeader@ActivePlatoon@@QEAAPEAVCharacter@@XZ endp

; ActivePlatoon::getSquadSize();
?getSquadSize@ActivePlatoon@@QEBAHXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+17*8]
?getSquadSize@ActivePlatoon@@QEBAHXZ endp

; ActivePlatoon::setSquadLeader(class Character *);
?setSquadLeader@ActivePlatoon@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+18*8]
?setSquadLeader@ActivePlatoon@@QEAAXPEAVCharacter@@@Z endp

?_NV_update@ActivePlatoon@@QEAA_NXZ proc EXPORT
?_NV_update@ActivePlatoon@@QEAA_NXZ endp

; ActivePlatoon::update();
?update@ActivePlatoon@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+19*8]
?update@ActivePlatoon@@UEAA_NXZ endp

; ActivePlatoon::refreshInventory(bool);
?refreshInventory@ActivePlatoon@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+20*8]
?refreshInventory@ActivePlatoon@@QEAAX_N@Z endp

; ActivePlatoon::_forceRefreshInventory();
?_forceRefreshInventory@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+21*8]
?_forceRefreshInventory@ActivePlatoon@@QEAAXXZ endp

?_NV_periodicUpdate@ActivePlatoon@@QEAA_NXZ proc EXPORT
?_NV_periodicUpdate@ActivePlatoon@@QEAA_NXZ endp

; ActivePlatoon::periodicUpdate();
?periodicUpdate@ActivePlatoon@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+22*8]
?periodicUpdate@ActivePlatoon@@UEAA_NXZ endp

; ActivePlatoon::serialiseEverythingToDisk(bool);
?serialiseEverythingToDisk@ActivePlatoon@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+23*8]
?serialiseEverythingToDisk@ActivePlatoon@@QEAAX_N@Z endp

; ActivePlatoon::isWholeSquadDown(int);
?isWholeSquadDown@ActivePlatoon@@QEAA_NH@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+24*8]
?isWholeSquadDown@ActivePlatoon@@QEAA_NH@Z endp

; ActivePlatoon::setDataFilename(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setDataFilename@ActivePlatoon@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+25*8]
?setDataFilename@ActivePlatoon@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ActivePlatoon::setupLeaderDialogues();
?setupLeaderDialogues@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+26*8]
?setupLeaderDialogues@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::isLoaded();
?isLoaded@ActivePlatoon@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+27*8]
?isLoaded@ActivePlatoon@@QEBA_NXZ endp

; ActivePlatoon::teleport(const class Ogre::Vector3 &);
?teleport@ActivePlatoon@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+28*8]
?teleport@ActivePlatoon@@QEAAXAEBVVector3@Ogre@@@Z endp

; ActivePlatoon::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@ActivePlatoon@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+29*8]
?setName@ActivePlatoon@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ActivePlatoon::getName();
?getName@ActivePlatoon@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+30*8]
?getName@ActivePlatoon@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; ActivePlatoon::getIsTrader();
?getIsTrader@ActivePlatoon@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+31*8]
?getIsTrader@ActivePlatoon@@QEBA_NXZ endp

; ActivePlatoon::getHasVendorList();
?getHasVendorList@ActivePlatoon@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+32*8]
?getHasVendorList@ActivePlatoon@@QEBA_NXZ endp

; ActivePlatoon::getHasSpecialItemsList();
?getHasSpecialItemsList@ActivePlatoon@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+33*8]
?getHasSpecialItemsList@ActivePlatoon@@QEBA_NXZ endp

; ActivePlatoon::setupTraderBuildings();
?setupTraderBuildings@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+34*8]
?setupTraderBuildings@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::putTheSpecialCharactersInNewSquads_captured();
?putTheSpecialCharactersInNewSquads_captured@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+35*8]
?putTheSpecialCharactersInNewSquads_captured@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::checkForCharactersBeingCarried();
?checkForCharactersBeingCarried@ActivePlatoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+36*8]
?checkForCharactersBeingCarried@ActivePlatoon@@QEAA_NXZ endp

; ActivePlatoon::restoreSquad();
?restoreSquad@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+37*8]
?restoreSquad@ActivePlatoon@@QEAAXXZ endp

?_CONSTRUCTOR@ActivePlatoon@@QEAAPEAV1@PEAVPlatoon@@PEAVDataObjectContainer@@PEAVFaction@@PEAVGameData@@PEAVTasker@@AEBVVector3@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@ActivePlatoon@@QEAAPEAV1@PEAVPlatoon@@PEAVDataObjectContainer@@PEAVFaction@@PEAVGameData@@PEAVTasker@@AEBVVector3@Ogre@@@Z endp

; ActivePlatoon::ActivePlatoon(class Platoon *, class DataObjectContainer *, class Faction *, class GameData *, class Tasker *, const class Ogre::Vector3 &);
??0ActivePlatoon@@QEAA@PEAVPlatoon@@PEAVDataObjectContainer@@PEAVFaction@@PEAVGameData@@PEAVTasker@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+38*8]
??0ActivePlatoon@@QEAA@PEAVPlatoon@@PEAVDataObjectContainer@@PEAVFaction@@PEAVGameData@@PEAVTasker@@AEBVVector3@Ogre@@@Z endp

; ActivePlatoon::unloadCheck();
?unloadCheck@ActivePlatoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+39*8]
?unloadCheck@ActivePlatoon@@QEAA_NXZ endp

; ActivePlatoon::setupCheck();
?setupCheck@ActivePlatoon@@QEAA?AVYesNoMaybe@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+40*8]
?setupCheck@ActivePlatoon@@QEAA?AVYesNoMaybe@@XZ endp

; ActivePlatoon::destroyCharacters(bool);
?destroyCharacters@ActivePlatoon@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+41*8]
?destroyCharacters@ActivePlatoon@@QEAAX_N@Z endp

; ActivePlatoon::serialiseCharacterData();
?serialiseCharacterData@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+42*8]
?serialiseCharacterData@ActivePlatoon@@QEAAXXZ endp

; ActivePlatoon::saveToDisk(bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveToDisk@ActivePlatoon@@QEAAX_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+43*8]
?saveToDisk@ActivePlatoon@@QEAAX_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_loadCharacters@ActivePlatoon@@QEAAXVVector3@Ogre@@PEAVFactoryCallbackInterface@@@Z proc EXPORT
?_NV_loadCharacters@ActivePlatoon@@QEAAXVVector3@Ogre@@PEAVFactoryCallbackInterface@@@Z endp

; ActivePlatoon::loadCharacters(class Ogre::Vector3, class FactoryCallbackInterface *);
?loadCharacters@ActivePlatoon@@UEAAXVVector3@Ogre@@PEAVFactoryCallbackInterface@@@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+44*8]
?loadCharacters@ActivePlatoon@@UEAAXVVector3@Ogre@@PEAVFactoryCallbackInterface@@@Z endp

?_NV_loadInstance@ActivePlatoon@@QEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z proc EXPORT
?_NV_loadInstance@ActivePlatoon@@QEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z endp

; ActivePlatoon::loadInstance(class GameSaveState &, bool, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class FactoryCallbackInterface *, const class Ogre::Vector3 &);
?loadInstance@ActivePlatoon@@UEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z proc EXPORT
jmp function_pointers[_ActivePlatoon_base+45*8]
?loadInstance@ActivePlatoon@@UEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z endp

; ActivePlatoon::calculateCurrentPos();
?calculateCurrentPos@ActivePlatoon@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+46*8]
?calculateCurrentPos@ActivePlatoon@@QEAA?AVVector3@Ogre@@XZ endp

; ActivePlatoon::_checkForUniqueCharactersOnUnload();
?_checkForUniqueCharactersOnUnload@ActivePlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_ActivePlatoon_base+47*8]
?_checkForUniqueCharactersOnUnload@ActivePlatoon@@QEAAXXZ endp
