
?_CONSTRUCTOR@AnimalInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AnimalInventoryLayout@@QEAAPEAV1@XZ endp

; AnimalInventoryLayout::AnimalInventoryLayout();
??0AnimalInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_AnimalInventoryLayout_base+0*8]
??0AnimalInventoryLayout@@QEAA@XZ endp

; symbol is too long
; ?setupSections@AnimalInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; AnimalInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
AnimalInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_AnimalInventoryLayout_base+1*8]
AnimalInventoryLayout_setupSections_PLACEHOLDER endp

?_DESTRUCTOR@AnimalInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AnimalInventoryLayout@@QEAAXXZ endp

; AnimalInventoryLayout::~AnimalInventoryLayout();
??1AnimalInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_AnimalInventoryLayout_base+2*8]
??1AnimalInventoryLayout@@UEAA@XZ endp
