
?_CONSTRUCTOR@DataCategory@AppearanceManager@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@DataCategory@AppearanceManager@@QEAAPEAV12@AEBV12@@Z endp

; AppearanceManager::DataCategory::DataCategory(const class AppearanceManager::DataCategory &);
??0DataCategory@AppearanceManager@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+0*8]
??0DataCategory@AppearanceManager@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@DataCategory@AppearanceManager@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@DataCategory@AppearanceManager@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceManager::DataCategory::DataCategory(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0DataCategory@AppearanceManager@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+1*8]
??0DataCategory@AppearanceManager@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@DataCategory@AppearanceManager@@QEAAPEAV12@W4Enum@12@@Z proc EXPORT
?_CONSTRUCTOR@DataCategory@AppearanceManager@@QEAAPEAV12@W4Enum@12@@Z endp

; AppearanceManager::DataCategory::DataCategory(enum AppearanceManager::DataCategory::Enum);
??0DataCategory@AppearanceManager@@QEAA@W4Enum@01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+2*8]
??0DataCategory@AppearanceManager@@QEAA@W4Enum@01@@Z endp

; AppearanceManager::DataCategory::setValue(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setValue@DataCategory@AppearanceManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+3*8]
?setValue@DataCategory@AppearanceManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceManager::DataCategory::getValue();
?getValue@DataCategory@AppearanceManager@@QEBA?AW4Enum@12@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+4*8]
?getValue@DataCategory@AppearanceManager@@QEBA?AW4Enum@12@XZ endp

?_DESTRUCTOR@DataCategory@AppearanceManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataCategory@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::DataCategory::~DataCategory();
??1DataCategory@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+5*8]
??1DataCategory@AppearanceManager@@QEAA@XZ endp

; AppearanceManager::DataCategory::operator=(const class AppearanceManager::DataCategory &);
??4DataCategory@AppearanceManager@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataCategory_base+6*8]
??4DataCategory@AppearanceManager@@QEAAAEAV01@AEBV01@@Z endp
