
; AppearanceManager::DataRangeVector::addValue(const class Ogre::Vector3 &);
?addValue@DataRangeVector@AppearanceManager@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+0*8]
?addValue@DataRangeVector@AppearanceManager@@QEAAXAEBVVector3@Ogre@@@Z endp

; AppearanceManager::DataRangeVector::getValue(int);
?getValue@DataRangeVector@AppearanceManager@@QEBA?AVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+1*8]
?getValue@DataRangeVector@AppearanceManager@@QEBA?AVVector3@Ogre@@H@Z endp

; AppearanceManager::DataRangeVector::getValueIndex(const class Ogre::Vector3 &);
?getValueIndex@DataRangeVector@AppearanceManager@@QEBAHAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+2*8]
?getValueIndex@DataRangeVector@AppearanceManager@@QEBAHAEBVVector3@Ogre@@@Z endp

; AppearanceManager::DataRangeVector::size();
?size@DataRangeVector@AppearanceManager@@QEBAHXZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+3*8]
?size@DataRangeVector@AppearanceManager@@QEBAHXZ endp

?_NV_clamp@DataRangeVector@AppearanceManager@@QEBAXPEAVGameData@@@Z proc EXPORT
?_NV_clamp@DataRangeVector@AppearanceManager@@QEBAXPEAVGameData@@@Z endp

; AppearanceManager::DataRangeVector::clamp(class GameData *);
?clamp@DataRangeVector@AppearanceManager@@UEBAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+4*8]
?clamp@DataRangeVector@AppearanceManager@@UEBAXPEAVGameData@@@Z endp

?_CONSTRUCTOR@DataRangeVector@AppearanceManager@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@DataRangeVector@AppearanceManager@@QEAAPEAV12@AEBV12@@Z endp

; AppearanceManager::DataRangeVector::DataRangeVector(const class AppearanceManager::DataRangeVector &);
??0DataRangeVector@AppearanceManager@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+5*8]
??0DataRangeVector@AppearanceManager@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@DataRangeVector@AppearanceManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@DataRangeVector@AppearanceManager@@QEAAPEAV12@XZ endp

; AppearanceManager::DataRangeVector::DataRangeVector();
??0DataRangeVector@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+6*8]
??0DataRangeVector@AppearanceManager@@QEAA@XZ endp

?_DESTRUCTOR@DataRangeVector@AppearanceManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataRangeVector@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::DataRangeVector::~DataRangeVector();
??1DataRangeVector@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+7*8]
??1DataRangeVector@AppearanceManager@@QEAA@XZ endp

; AppearanceManager::DataRangeVector::operator=(const class AppearanceManager::DataRangeVector &);
??4DataRangeVector@AppearanceManager@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangeVector_base+8*8]
??4DataRangeVector@AppearanceManager@@QEAAAEAV01@AEBV01@@Z endp
