
?_NV_clamp@DataRange@AppearanceManager@@QEBAXPEAVGameData@@@Z proc EXPORT
?_NV_clamp@DataRange@AppearanceManager@@QEBAXPEAVGameData@@@Z endp

; AppearanceManager::DataRange::clamp(class GameData *);
?clamp@DataRange@AppearanceManager@@UEBAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRange_base+0*8]
?clamp@DataRange@AppearanceManager@@UEBAXPEAVGameData@@@Z endp

?_CONSTRUCTOR@DataRange@AppearanceManager@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@DataRange@AppearanceManager@@QEAAPEAV12@AEBV12@@Z endp

; AppearanceManager::DataRange::DataRange(const class AppearanceManager::DataRange &);
??0DataRange@AppearanceManager@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRange_base+1*8]
??0DataRange@AppearanceManager@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@DataRange@AppearanceManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@DataRange@AppearanceManager@@QEAAPEAV12@XZ endp

; AppearanceManager::DataRange::DataRange();
??0DataRange@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRange_base+2*8]
??0DataRange@AppearanceManager@@QEAA@XZ endp

?_DESTRUCTOR@DataRange@AppearanceManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataRange@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::DataRange::~DataRange();
??1DataRange@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRange_base+3*8]
??1DataRange@AppearanceManager@@QEAA@XZ endp

; AppearanceManager::DataRange::operator=(const class AppearanceManager::DataRange &);
??4DataRange@AppearanceManager@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRange_base+4*8]
??4DataRange@AppearanceManager@@QEAAAEAV01@AEBV01@@Z endp
