
?_CONSTRUCTOR@AppearanceBase@@QEAAPEAV1@PEAVAnimationClass@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@AppearanceBase@@QEAAPEAV1@PEAVAnimationClass@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z endp

; AppearanceBase::AppearanceBase(class AnimationClass *, class GameDataCopyStandalone *, class Character *, class GameData *);
??0AppearanceBase@@QEAA@PEAVAnimationClass@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+0*8]
??0AppearanceBase@@QEAA@PEAVAnimationClass@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z endp

?_DESTRUCTOR@AppearanceBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::~AppearanceBase();
??1AppearanceBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+1*8]
??1AppearanceBase@@UEAA@XZ endp

; AppearanceBase::updateAnimationTransforms();
?updateAnimationTransforms@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+2*8]
?updateAnimationTransforms@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::forceUpdateAnimationTransforms();
?forceUpdateAnimationTransforms@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+3*8]
?forceUpdateAnimationTransforms@AppearanceBase@@QEAAXXZ endp

?_NV_update@AppearanceBase@@QEAAXXZ proc EXPORT
?_NV_update@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::update();
?update@AppearanceBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+4*8]
?update@AppearanceBase@@UEAAXXZ endp

?_NV_periodicUpdate@AppearanceBase@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::periodicUpdate();
?periodicUpdate@AppearanceBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+5*8]
?periodicUpdate@AppearanceBase@@UEAAXXZ endp

; AppearanceBase::setAppearanceData(class GameDataCopyStandalone *);
?setAppearanceData@AppearanceBase@@QEAAXPEAVGameDataCopyStandalone@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+6*8]
?setAppearanceData@AppearanceBase@@QEAAXPEAVGameDataCopyStandalone@@@Z endp

; AppearanceBase::getAppearanceData();
?getAppearanceData@AppearanceBase@@QEBAPEAVGameDataCopyStandalone@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+7*8]
?getAppearanceData@AppearanceBase@@QEBAPEAVGameDataCopyStandalone@@XZ endp

?_NV_activate@AppearanceBase@@QEAAXXZ proc EXPORT
?_NV_activate@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::activate();
?activate@AppearanceBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+8*8]
?activate@AppearanceBase@@UEAAXXZ endp

?_NV_deactivate@AppearanceBase@@QEAAXXZ proc EXPORT
?_NV_deactivate@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::deactivate();
?deactivate@AppearanceBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+9*8]
?deactivate@AppearanceBase@@UEAAXXZ endp

; AppearanceBase::isFemale();
?isFemale@AppearanceBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+10*8]
?isFemale@AppearanceBase@@QEBA_NXZ endp

?_NV_setGender@AppearanceBase@@QEAAX_N@Z proc EXPORT
?_NV_setGender@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::setGender(bool);
?setGender@AppearanceBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+11*8]
?setGender@AppearanceBase@@UEAAX_N@Z endp

; AppearanceBase::getRace();
?getRace@AppearanceBase@@QEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+12*8]
?getRace@AppearanceBase@@QEBAPEAVGameData@@XZ endp

; AppearanceBase::chooseBodyMesh();
?chooseBodyMesh@AppearanceBase@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+13*8]
?chooseBodyMesh@AppearanceBase@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; AppearanceBase::addWound(class Wound *);
?addWound@AppearanceBase@@QEAAXPEAVWound@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+14*8]
?addWound@AppearanceBase@@QEAAXPEAVWound@@@Z endp

; AppearanceBase::removeWound(class Wound *);
?removeWound@AppearanceBase@@QEAAXPEAVWound@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+15*8]
?removeWound@AppearanceBase@@QEAAXPEAVWound@@@Z endp

; AppearanceBase::attachItem(class Item *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?attachItem@AppearanceBase@@QEAA_NPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+16*8]
?attachItem@AppearanceBase@@QEAA_NPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; AppearanceBase::attachItem(class Item *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?attachItem@AppearanceBase@@QEAA_NPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+17*8]
?attachItem@AppearanceBase@@QEAA_NPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::attachHarpoon(class Harpoon *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?attachHarpoon@AppearanceBase@@QEAA_NPEAVHarpoon@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVVector3@Ogre@@AEBVQuaternion@6@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+18*8]
?attachHarpoon@AppearanceBase@@QEAA_NPEAVHarpoon@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVVector3@Ogre@@AEBVQuaternion@6@@Z endp

; AppearanceBase::attachEffect(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class Ogre::Vector3 &, const class Ogre::Quaternion &, bool, float);
?attachEffect@AppearanceBase@@QEAAPEAVAttachedEffect@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVVector3@Ogre@@AEBVQuaternion@7@_NM@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+19*8]
?attachEffect@AppearanceBase@@QEAAPEAVAttachedEffect@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVVector3@Ogre@@AEBVQuaternion@7@_NM@Z endp

; AppearanceBase::getAttachedEntity(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getAttachedEntity@AppearanceBase@@QEBAPEAVAttachedEntity@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+20*8]
?getAttachedEntity@AppearanceBase@@QEBAPEAVAttachedEntity@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::detachItem(class Item *);
?detachItem@AppearanceBase@@QEAA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+21*8]
?detachItem@AppearanceBase@@QEAA_NPEAVItem@@@Z endp

; AppearanceBase::detachItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?detachItem@AppearanceBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+22*8]
?detachItem@AppearanceBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::detachHarpoon(class Harpoon *);
?detachHarpoon@AppearanceBase@@QEAA_NPEAVHarpoon@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+23*8]
?detachHarpoon@AppearanceBase@@QEAA_NPEAVHarpoon@@@Z endp

; AppearanceBase::detachAllHarpoonsT();
?detachAllHarpoonsT@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+24*8]
?detachAllHarpoonsT@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::_detachAllHarpoons();
?_detachAllHarpoons@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+25*8]
?_detachAllHarpoons@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::removeEffect(class AttachedEffect *);
?removeEffect@AppearanceBase@@QEAAXPEAVAttachedEffect@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+26*8]
?removeEffect@AppearanceBase@@QEAAXPEAVAttachedEffect@@@Z endp

; AppearanceBase::updateWetness(bool);
?updateWetness@AppearanceBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+27*8]
?updateWetness@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::updateBloodyness();
?updateBloodyness@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+28*8]
?updateBloodyness@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::getAttachmentPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Ogre::Vector3 &, class Ogre::Quaternion &);
?getAttachmentPosition@AppearanceBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVVector3@Ogre@@AEAVQuaternion@5@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+29*8]
?getAttachmentPosition@AppearanceBase@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVVector3@Ogre@@AEAVQuaternion@5@@Z endp

; AppearanceBase::hasSlot(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?hasSlot@AppearanceBase@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+30*8]
?hasSlot@AppearanceBase@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::getNormalisedCharacterHeight();
?getNormalisedCharacterHeight@AppearanceBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+31*8]
?getNormalisedCharacterHeight@AppearanceBase@@QEBAMXZ endp

; AppearanceBase::getCharacterHeight();
?getCharacterHeight@AppearanceBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+32*8]
?getCharacterHeight@AppearanceBase@@QEBAMXZ endp

; AppearanceBase::getAnimationSystem();
?getAnimationSystem@AppearanceBase@@QEBAPEAVAnimationClass@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+33*8]
?getAnimationSystem@AppearanceBase@@QEBAPEAVAnimationClass@@XZ endp

; AppearanceBase::getSceneNode();
?getSceneNode@AppearanceBase@@QEBAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+34*8]
?getSceneNode@AppearanceBase@@QEBAPEAVSceneNode@Ogre@@XZ endp

; AppearanceBase::getSkeleton();
?getSkeleton@AppearanceBase@@QEBAPEAVOldSkeletonInstance@Ogre@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+35*8]
?getSkeleton@AppearanceBase@@QEBAPEAVOldSkeletonInstance@Ogre@@XZ endp

; AppearanceBase::getBody();
?getBody@AppearanceBase@@QEBAPEAVEntity@Ogre@@XZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+36*8]
?getBody@AppearanceBase@@QEBAPEAVEntity@Ogre@@XZ endp

; AppearanceBase::getBodyRadius();
?getBodyRadius@AppearanceBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+37*8]
?getBodyRadius@AppearanceBase@@QEBAMXZ endp

; AppearanceBase::failedToLoad();
?failedToLoad@AppearanceBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+38*8]
?failedToLoad@AppearanceBase@@QEBA_NXZ endp

; AppearanceBase::getBonePosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBonePosition@AppearanceBase@@QEAA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+39*8]
?getBonePosition@AppearanceBase@@QEAA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::getBoneOrientation(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneOrientation@AppearanceBase@@QEAA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+40*8]
?getBoneOrientation@AppearanceBase@@QEAA?AVQuaternion@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::getVertexPosition(const int);
?getVertexPosition@AppearanceBase@@QEBAAEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+41*8]
?getVertexPosition@AppearanceBase@@QEBAAEBVVector3@Ogre@@H@Z endp

; AppearanceBase::getVertexWorldPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const int);
?getVertexWorldPosition@AppearanceBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+42*8]
?getVertexWorldPosition@AppearanceBase@@QEBA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; AppearanceBase::getRandomVertex(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum MeshDataLookup::Dir);
?getRandomVertex@AppearanceBase@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Dir@MeshDataLookup@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+43*8]
?getRandomVertex@AppearanceBase@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Dir@MeshDataLookup@@@Z endp

; AppearanceBase::getRandomVertexPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum MeshDataLookup::Dir);
?getRandomVertexPosition@AppearanceBase@@QEBAAEBVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Dir@MeshDataLookup@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+44*8]
?getRandomVertexPosition@AppearanceBase@@QEBAAEBVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Dir@MeshDataLookup@@@Z endp

; AppearanceBase::notifyDirty();
?notifyDirty@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+45*8]
?notifyDirty@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::reload();
?reload@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+46*8]
?reload@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::serialise(class GameData *);
?serialise@AppearanceBase@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+47*8]
?serialise@AppearanceBase@@QEAAXPEAVGameData@@@Z endp

?_NV_updateAppearance@AppearanceBase@@QEAAXXZ proc EXPORT
?_NV_updateAppearance@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::updateAppearance();
?updateAppearance@AppearanceBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+48*8]
?updateAppearance@AppearanceBase@@UEAAXXZ endp

; AppearanceBase::updatePortrait();
?updatePortrait@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+49*8]
?updatePortrait@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::updateMovementScale();
?updateMovementScale@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+50*8]
?updateMovementScale@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::switchLights(bool);
?switchLights@AppearanceBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+51*8]
?switchLights@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::hasLights();
?hasLights@AppearanceBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+52*8]
?hasLights@AppearanceBase@@QEBA_NXZ endp

; AppearanceBase::getLights(class lektor<Ogre::Light *> &);
?getLights@AppearanceBase@@QEAAXAEAV?$lektor@PEAVLight@Ogre@@@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+53*8]
?getLights@AppearanceBase@@QEAAXAEAV?$lektor@PEAVLight@Ogre@@@@@Z endp

; AppearanceBase::attachItem_Hair(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?attachItem_Hair@AppearanceBase@@QEAA_NPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+54*8]
?attachItem_Hair@AppearanceBase@@QEAA_NPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceBase::shaveHead(bool);
?shaveHead@AppearanceBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+55*8]
?shaveHead@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::isShaved();
?isShaved@AppearanceBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+56*8]
?isShaved@AppearanceBase@@QEBA_NXZ endp

?_NV_setFlayed@AppearanceBase@@QEAAX_N@Z proc EXPORT
?_NV_setFlayed@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::setFlayed(bool);
?setFlayed@AppearanceBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+57*8]
?setFlayed@AppearanceBase@@UEAAX_N@Z endp

?_NV_isFlayed@AppearanceBase@@QEBA_NXZ proc EXPORT
?_NV_isFlayed@AppearanceBase@@QEBA_NXZ endp

; AppearanceBase::isFlayed();
?isFlayed@AppearanceBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+58*8]
?isFlayed@AppearanceBase@@UEBA_NXZ endp

?_NV_isBarefoot@AppearanceBase@@QEBA_NXZ proc EXPORT
?_NV_isBarefoot@AppearanceBase@@QEBA_NXZ endp

; AppearanceBase::isBarefoot();
?isBarefoot@AppearanceBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+59*8]
?isBarefoot@AppearanceBase@@UEBA_NXZ endp

; AppearanceBase::setVisible(bool);
?setVisible@AppearanceBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+60*8]
?setVisible@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::getVisible();
?getVisible@AppearanceBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+61*8]
?getVisible@AppearanceBase@@QEBA_NXZ endp

; AppearanceBase::getAttachmentsLoaded();
?getAttachmentsLoaded@AppearanceBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+62*8]
?getAttachmentsLoaded@AppearanceBase@@QEBA_NXZ endp

?_NV_setAttachmentsVisible@AppearanceBase@@QEAAX_N@Z proc EXPORT
?_NV_setAttachmentsVisible@AppearanceBase@@QEAAX_N@Z endp

; AppearanceBase::setAttachmentsVisible(bool);
?setAttachmentsVisible@AppearanceBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+63*8]
?setAttachmentsVisible@AppearanceBase@@UEAAX_N@Z endp

; AppearanceBase::buildBody(class Ogre::SharedPtr<Ogre::Resource>, void *);
?buildBody@AppearanceBase@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+64*8]
?buildBody@AppearanceBase@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

; AppearanceBase::buildAttachments();
?buildAttachments@AppearanceBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+65*8]
?buildAttachments@AppearanceBase@@QEAAXXZ endp

; AppearanceBase::createEntity(class AttachedEntity *);
?createEntity@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+66*8]
?createEntity@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z endp

; AppearanceBase::createPhysicsAttachment(class AttachedEntity *);
?createPhysicsAttachment@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+67*8]
?createPhysicsAttachment@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z endp

; AppearanceBase::createEntityCallback(class Ogre::SharedPtr<Ogre::Resource>, void *);
?createEntityCallback@AppearanceBase@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+68*8]
?createEntityCallback@AppearanceBase@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

; AppearanceBase::attachEntity(class AttachedObject *);
?attachEntity@AppearanceBase@@QEAAXPEAVAttachedObject@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+69*8]
?attachEntity@AppearanceBase@@QEAAXPEAVAttachedObject@@@Z endp

; AppearanceBase::getSlotPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class AttachedObject *);
?getSlotPosition@AppearanceBase@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAttachedObject@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+70*8]
?getSlotPosition@AppearanceBase@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAttachedObject@@@Z endp

; AppearanceBase::setupItemMaterial(class AttachedEntity *);
?setupItemMaterial@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+71*8]
?setupItemMaterial@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z endp

; AppearanceBase::setupHairMaterial(class AttachedEntity *);
?setupHairMaterial@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+72*8]
?setupHairMaterial@AppearanceBase@@QEAAXPEAVAttachedEntity@@@Z endp

; AppearanceBase::setHairTexture(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, const class Ogre::Vector3 &, bool);
?setHairTexture@AppearanceBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHAEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+73*8]
?setHairTexture@AppearanceBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHAEBVVector3@Ogre@@_N@Z endp

; symbol is too long
jmp function_pointers[_AppearanceBase_base+74*8]

; AppearanceBase::createAttachedObject(class Item *);
?createAttachedObject@AppearanceBase@@QEAAPEAVAttachedEntity@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+75*8]
?createAttachedObject@AppearanceBase@@QEAAPEAVAttachedEntity@@PEAVItem@@@Z endp

; AppearanceBase::affectsPortrait(class AttachedEntity *);
?affectsPortrait@AppearanceBase@@QEBA_NPEAVAttachedEntity@@@Z proc EXPORT
jmp function_pointers[_AppearanceBase_base+76*8]
?affectsPortrait@AppearanceBase@@QEBA_NPEAVAttachedEntity@@@Z endp

; AppearanceBase::updateOverlap();
?updateOverlap@AppearanceBase@@QEBAXXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+77*8]
?updateOverlap@AppearanceBase@@QEBAXXZ endp

; AppearanceBase::getCharacterHeightSpeedMultiplier();
?getCharacterHeightSpeedMultiplier@AppearanceBase@@QEAAMXZ proc EXPORT
jmp function_pointers[_AppearanceBase_base+78*8]
?getCharacterHeightSpeedMultiplier@AppearanceBase@@QEAAMXZ endp
