
; AppearanceManager::getInstance();
?getInstance@AppearanceManager@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_base+0*8]
?getInstance@AppearanceManager@@SAPEAV1@XZ endp

; AppearanceManager::createAppearanceData(class GameData *);
?createAppearanceData@AppearanceManager@@QEAAPEAVGameDataCopyStandalone@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+1*8]
?createAppearanceData@AppearanceManager@@QEAAPEAVGameDataCopyStandalone@@PEAVGameData@@@Z endp

; AppearanceManager::cleanValidateAppearanceData(class GameData *);
?cleanValidateAppearanceData@AppearanceManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+2*8]
?cleanValidateAppearanceData@AppearanceManager@@QEAAXPEAVGameData@@@Z endp

; AppearanceManager::resetAll(class GameData *, bool);
?resetAll@AppearanceManager@@QEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+3*8]
?resetAll@AppearanceManager@@QEAAXPEAVGameData@@_N@Z endp

; AppearanceManager::randomiseAll(class GameData *);
?randomiseAll@AppearanceManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+4*8]
?randomiseAll@AppearanceManager@@QEAAXPEAVGameData@@@Z endp

; AppearanceManager::randomiseAllManual(class GameData *, float, float);
?randomiseAllManual@AppearanceManager@@QEAAXPEAVGameData@@MM@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+5*8]
?randomiseAllManual@AppearanceManager@@QEAAXPEAVGameData@@MM@Z endp

; AppearanceManager::randomHair(class GameData *, class Faction *);
?randomHair@AppearanceManager@@QEAAXPEAVGameData@@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+6*8]
?randomHair@AppearanceManager@@QEAAXPEAVGameData@@PEAVFaction@@@Z endp

; AppearanceManager::randomFace(class GameData *);
?randomFace@AppearanceManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+7*8]
?randomFace@AppearanceManager@@QEAAXPEAVGameData@@@Z endp

; AppearanceManager::randomFaceManual(class GameData *, float);
?randomFaceManual@AppearanceManager@@QEAAXPEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+8*8]
?randomFaceManual@AppearanceManager@@QEAAXPEAVGameData@@M@Z endp

; AppearanceManager::randomPoses(class GameData *, float);
?randomPoses@AppearanceManager@@QEAAXPEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+9*8]
?randomPoses@AppearanceManager@@QEAAXPEAVGameData@@M@Z endp

; AppearanceManager::randomBody(class GameData *, bool);
?randomBody@AppearanceManager@@QEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+10*8]
?randomBody@AppearanceManager@@QEAAXPEAVGameData@@_N@Z endp

; AppearanceManager::randomBodyManual(class GameData *, float);
?randomBodyManual@AppearanceManager@@QEAAXPEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+11*8]
?randomBodyManual@AppearanceManager@@QEAAXPEAVGameData@@M@Z endp

; AppearanceManager::randomGender(class GameData *, float);
?randomGender@AppearanceManager@@QEAAXPEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+12*8]
?randomGender@AppearanceManager@@QEAAXPEAVGameData@@M@Z endp

; AppearanceManager::randomAnimations(class GameData *, class Character *);
?randomAnimations@AppearanceManager@@QEAAXPEAVGameData@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+13*8]
?randomAnimations@AppearanceManager@@QEAAXPEAVGameData@@PEAVCharacter@@@Z endp

; AppearanceManager::getRaceData(int);
?getRaceData@AppearanceManager@@QEAAPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+14*8]
?getRaceData@AppearanceManager@@QEAAPEAVGameData@@H@Z endp

; AppearanceManager::getRaceIndex(class GameData *);
?getRaceIndex@AppearanceManager@@QEAAHPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+15*8]
?getRaceIndex@AppearanceManager@@QEAAHPEAVGameData@@@Z endp

; AppearanceManager::getRacesCount();
?getRacesCount@AppearanceManager@@QEBAHXZ proc EXPORT
jmp function_pointers[_AppearanceManager_base+16*8]
?getRacesCount@AppearanceManager@@QEBAHXZ endp

; AppearanceManager::isSingleGender(class GameData *);
?isSingleGender@AppearanceManager@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+17*8]
?isSingleGender@AppearanceManager@@QEAA_NPEAVGameData@@@Z endp

; AppearanceManager::setGender(class GameData *, enum AppearanceManager::Gender::Enum);
?setGender@AppearanceManager@@QEAAXPEAVGameData@@W4Enum@Gender@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+18*8]
?setGender@AppearanceManager@@QEAAXPEAVGameData@@W4Enum@Gender@1@@Z endp

; symbol is too long
jmp function_pointers[_AppearanceManager_base+19*8]

; AppearanceManager::setHead(class GameData *, class GameData *);
?setHead@AppearanceManager@@QEAAXPEAVGameData@@0@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+20*8]
?setHead@AppearanceManager@@QEAAXPEAVGameData@@0@Z endp

; AppearanceManager::getHeadName(class GameData *, class AppearanceManager::AppearanceData *);
?getHeadName@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@PEAVAppearanceData@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+21*8]
?getHeadName@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@PEAVAppearanceData@1@@Z endp

; AppearanceManager::setRandomHead(class GameData *, class GameData *);
?setRandomHead@AppearanceManager@@QEAAXPEAVGameData@@0@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+22*8]
?setRandomHead@AppearanceManager@@QEAAXPEAVGameData@@0@Z endp

; AppearanceManager::getHeadIsValid(class GameData *, class GameData *, class GameData *);
?getHeadIsValid@AppearanceManager@@QEAA_NPEAVGameData@@00@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+23*8]
?getHeadIsValid@AppearanceManager@@QEAA_NPEAVGameData@@00@Z endp

; AppearanceManager::setAttachment(class GameData *, class AppearanceManager::AppearanceData *, const enum AttachSlot, const int);
?setAttachment@AppearanceManager@@QEAAXPEAVGameData@@PEAVAppearanceData@1@W4AttachSlot@@H@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+24*8]
?setAttachment@AppearanceManager@@QEAAXPEAVGameData@@PEAVAppearanceData@1@W4AttachSlot@@H@Z endp

; AppearanceManager::getAttachmentName(class GameData *, class AppearanceManager::AppearanceData *, const enum AttachSlot);
?getAttachmentName@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@PEAVAppearanceData@1@W4AttachSlot@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+25*8]
?getAttachmentName@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@PEAVAppearanceData@1@W4AttachSlot@@@Z endp

; AppearanceManager::updateModifiers(class GameData *, class GameData *, const class AppearanceManager::Gender &);
?updateModifiers@AppearanceManager@@QEAAXPEAVGameData@@0AEBVGender@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+26*8]
?updateModifiers@AppearanceManager@@QEAAXPEAVGameData@@0AEBVGender@1@@Z endp

; AppearanceManager::getCharacterIdleAnimations();
?getCharacterIdleAnimations@AppearanceManager@@QEBAAEBV?$FastArray@PEAVAnimationData@@@Ogre@@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_base+27*8]
?getCharacterIdleAnimations@AppearanceManager@@QEBAAEBV?$FastArray@PEAVAnimationData@@@Ogre@@XZ endp

; AppearanceManager::getNormalMap_Plain(class GameData *, const class AppearanceManager::Gender &);
?getNormalMap_Plain@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@AEBVGender@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+28*8]
?getNormalMap_Plain@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@AEBVGender@1@@Z endp

; AppearanceManager::getNormalMap_Muscle(class GameData *, const class AppearanceManager::Gender &);
?getNormalMap_Muscle@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@AEBVGender@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+29*8]
?getNormalMap_Muscle@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@AEBVGender@1@@Z endp

; AppearanceManager::getNormalMap_Starving(class GameData *, const class AppearanceManager::Gender &);
?getNormalMap_Starving@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@AEBVGender@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+30*8]
?getNormalMap_Starving@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@AEBVGender@1@@Z endp

?_CONSTRUCTOR@AppearanceManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@AppearanceManager@@QEAAPEAV1@XZ endp

; AppearanceManager::AppearanceManager();
??0AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_base+31*8]
??0AppearanceManager@@QEAA@XZ endp

?_DESTRUCTOR@AppearanceManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::~AppearanceManager();
??1AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_base+32*8]
??1AppearanceManager@@QEAA@XZ endp

; AppearanceManager::setupData();
?setupData@AppearanceManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceManager_base+33*8]
?setupData@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::setupFaces(class GameData *, class AppearanceManager::AppearanceData &);
?setupFaces@AppearanceManager@@QEAAXPEAVGameData@@AEAVAppearanceData@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+34*8]
?setupFaces@AppearanceManager@@QEAAXPEAVGameData@@AEAVAppearanceData@1@@Z endp

; AppearanceManager::setupFactionHair(class AppearanceManager::AppearanceData &, class Faction *, enum AttachSlot);
?setupFactionHair@AppearanceManager@@QEAAXAEAVAppearanceData@1@PEAVFaction@@W4AttachSlot@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+35*8]
?setupFactionHair@AppearanceManager@@QEAAXAEAVAppearanceData@1@PEAVFaction@@W4AttachSlot@@@Z endp

; AppearanceManager::loadEditorXMLData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class GameData *);
?loadEditorXMLData@AppearanceManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+36*8]
?loadEditorXMLData@AppearanceManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp

; AppearanceManager::isValidAttachment(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class AppearanceManager::AppearanceData &, const enum AttachSlot);
?isValidAttachment@AppearanceManager@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAppearanceData@1@W4AttachSlot@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+37*8]
?isValidAttachment@AppearanceManager@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAppearanceData@1@W4AttachSlot@@@Z endp

; AppearanceManager::getRandomAttachment(const class AppearanceManager::AppearanceData &, const enum AttachSlot, class Faction *);
?getRandomAttachment@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAppearanceData@1@W4AttachSlot@@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+38*8]
?getRandomAttachment@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAppearanceData@1@W4AttachSlot@@PEAVFaction@@@Z endp

; AppearanceManager::getNoneAttachment(const class AppearanceManager::AppearanceData &, const enum AttachSlot);
?getNoneAttachment@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAppearanceData@1@W4AttachSlot@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+39*8]
?getNoneAttachment@AppearanceManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAppearanceData@1@W4AttachSlot@@@Z endp

; AppearanceManager::getRandomValue(const class Ogre::FastArray<GameData *> &, const class Ogre::FastArray<float> &);
?getRandomValue@AppearanceManager@@QEAAPEAVGameData@@AEBV?$FastArray@PEAVGameData@@@Ogre@@AEBV?$FastArray@M@4@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+40*8]
?getRandomValue@AppearanceManager@@QEAAPEAVGameData@@AEBV?$FastArray@PEAVGameData@@@Ogre@@AEBV?$FastArray@M@4@@Z endp

; AppearanceManager::getCategoryRange(const class AppearanceManager::AppearanceData &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int &, int &, int &);
?getCategoryRange@AppearanceManager@@QEBA_NAEBVAppearanceData@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAH22@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+41*8]
?getCategoryRange@AppearanceManager@@QEBA_NAEBVAppearanceData@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAH22@Z endp

; AppearanceManager::randomiseRanges(const class Ogre::FastArray<AppearanceManager::DataRangeVector> &, class GameData *);
?randomiseRanges@AppearanceManager@@QEAAXAEBV?$FastArray@VDataRangeVector@AppearanceManager@@@Ogre@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+42*8]
?randomiseRanges@AppearanceManager@@QEAAXAEBV?$FastArray@VDataRangeVector@AppearanceManager@@@Ogre@@PEAVGameData@@@Z endp

; AppearanceManager::randomiseRanges(const class Ogre::FastArray<AppearanceManager::DataRangePose> &, class GameData *, float);
?randomiseRanges@AppearanceManager@@QEAAXAEBV?$FastArray@VDataRangePose@AppearanceManager@@@Ogre@@PEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+43*8]
?randomiseRanges@AppearanceManager@@QEAAXAEBV?$FastArray@VDataRangePose@AppearanceManager@@@Ogre@@PEAVGameData@@M@Z endp

; AppearanceManager::randomiseRanges(const class Ogre::FastArray<AppearanceManager::DataRange> &, class GameData *);
?randomiseRanges@AppearanceManager@@QEAAXAEBV?$FastArray@VDataRange@AppearanceManager@@@Ogre@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+44*8]
?randomiseRanges@AppearanceManager@@QEAAXAEBV?$FastArray@VDataRange@AppearanceManager@@@Ogre@@PEAVGameData@@@Z endp

; AppearanceManager::randomFeatureSingle(const class AppearanceManager::DataRangePose &, float);
?randomFeatureSingle@AppearanceManager@@QEBAHAEBVDataRangePose@1@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+45*8]
?randomFeatureSingle@AppearanceManager@@QEBAHAEBVDataRangePose@1@M@Z endp

; AppearanceManager::randomFeatureSingle(const class AppearanceManager::DataRange &, float);
?randomFeatureSingle@AppearanceManager@@QEBAHAEBVDataRange@1@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+46*8]
?randomFeatureSingle@AppearanceManager@@QEBAHAEBVDataRange@1@M@Z endp

; AppearanceManager::randomFeatureVector(const class AppearanceManager::DataRangeVector &, float);
?randomFeatureVector@AppearanceManager@@QEBA?AVVector3@Ogre@@AEBVDataRangeVector@1@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+47*8]
?randomFeatureVector@AppearanceManager@@QEBA?AVVector3@Ogre@@AEBVDataRangeVector@1@M@Z endp

; AppearanceManager::randomFeatureSingleManual(const class AppearanceManager::DataRangePose &, float);
?randomFeatureSingleManual@AppearanceManager@@QEBAHAEBVDataRangePose@1@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+48*8]
?randomFeatureSingleManual@AppearanceManager@@QEBAHAEBVDataRangePose@1@M@Z endp

; AppearanceManager::randomFeatureSingleManual(const class AppearanceManager::DataRange &, float);
?randomFeatureSingleManual@AppearanceManager@@QEBAHAEBVDataRange@1@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+49*8]
?randomFeatureSingleManual@AppearanceManager@@QEBAHAEBVDataRange@1@M@Z endp

; AppearanceManager::randomFeatureVectorManual(const class AppearanceManager::DataRangeVector &, float);
?randomFeatureVectorManual@AppearanceManager@@QEBA?AVVector3@Ogre@@AEBVDataRangeVector@1@M@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+50*8]
?randomFeatureVectorManual@AppearanceManager@@QEBA?AVVector3@Ogre@@AEBVDataRangeVector@1@M@Z endp

; AppearanceManager::getValidateRace(class GameData *);
?getValidateRace@AppearanceManager@@QEAAPEAVGameData@@PEAV2@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+51*8]
?getValidateRace@AppearanceManager@@QEAAPEAVGameData@@PEAV2@@Z endp

; symbol is too long
jmp function_pointers[_AppearanceManager_base+52*8]

; AppearanceManager::getBodyMesh(class GameData *, enum AppearanceManager::Gender::Enum);
?getBodyMesh@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@W4Enum@Gender@1@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+53*8]
?getBodyMesh@AppearanceManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@W4Enum@Gender@1@@Z endp

; AppearanceManager::switchBodyMesh(class Ogre::Entity *, class Ogre::SharedPtr<Ogre::Mesh>);
?switchBodyMesh@AppearanceManager@@SAPEAVEntity@Ogre@@PEAV23@V?$SharedPtr@VMesh@Ogre@@@3@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+54*8]
?switchBodyMesh@AppearanceManager@@SAPEAVEntity@Ogre@@PEAV23@V?$SharedPtr@VMesh@Ogre@@@3@@Z endp

; AppearanceManager::createMorphedMesh(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Ogre::Entity *, class GameData *, bool);
?createMorphedMesh@AppearanceManager@@SAPEAVEntity@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV23@PEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+55*8]
?createMorphedMesh@AppearanceManager@@SAPEAVEntity@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV23@PEAVGameData@@_N@Z endp

; AppearanceManager::getMorphedBodyMesh(class GameData *, class Ogre::Entity *, bool, float, bool);
?getMorphedBodyMesh@AppearanceManager@@QEAAPEAVEntity@Ogre@@PEAVGameData@@PEAV23@_NM2@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+56*8]
?getMorphedBodyMesh@AppearanceManager@@QEAAPEAVEntity@Ogre@@PEAVGameData@@PEAV23@_NM2@Z endp

; AppearanceManager::getBodyMeshForEditor(class Ogre::Entity *);
?getBodyMeshForEditor@AppearanceManager@@QEAAPEAVEntity@Ogre@@PEAV23@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_base+57*8]
?getBodyMeshForEditor@AppearanceManager@@QEAAPEAVEntity@Ogre@@PEAV23@@Z endp
