
?_CONSTRUCTOR@Gender@AppearanceManager@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@Gender@AppearanceManager@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; AppearanceManager::Gender::Gender(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0Gender@AppearanceManager@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+0*8]
??0Gender@AppearanceManager@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@Gender@AppearanceManager@@QEAAPEAV12@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@Gender@AppearanceManager@@QEAAPEAV12@PEAVGameData@@@Z endp

; AppearanceManager::Gender::Gender(class GameData *);
??0Gender@AppearanceManager@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+1*8]
??0Gender@AppearanceManager@@QEAA@PEAVGameData@@@Z endp

?_CONSTRUCTOR@Gender@AppearanceManager@@QEAAPEAV12@W4Enum@12@@Z proc EXPORT
?_CONSTRUCTOR@Gender@AppearanceManager@@QEAAPEAV12@W4Enum@12@@Z endp

; AppearanceManager::Gender::Gender(enum AppearanceManager::Gender::Enum);
??0Gender@AppearanceManager@@QEAA@W4Enum@01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+2*8]
??0Gender@AppearanceManager@@QEAA@W4Enum@01@@Z endp

; AppearanceManager::Gender::isMale();
?isMale@Gender@AppearanceManager@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+3*8]
?isMale@Gender@AppearanceManager@@QEBA_NXZ endp

; AppearanceManager::Gender::isFemale();
?isFemale@Gender@AppearanceManager@@QEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+4*8]
?isFemale@Gender@AppearanceManager@@QEBA_NXZ endp

; AppearanceManager::Gender::toString();
?toString@Gender@AppearanceManager@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+5*8]
?toString@Gender@AppearanceManager@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; AppearanceManager::Gender::getValue();
?getValue@Gender@AppearanceManager@@QEBA?AW4Enum@12@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_Gender_base+6*8]
?getValue@Gender@AppearanceManager@@QEBA?AW4Enum@12@XZ endp
