
?_CONSTRUCTOR@AppearanceHuman@@QEAAPEAV1@PEAVAnimationClassHuman@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@AppearanceHuman@@QEAAPEAV1@PEAVAnimationClassHuman@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z endp

; AppearanceHuman::AppearanceHuman(class AnimationClassHuman *, class GameDataCopyStandalone *, class Character *, class GameData *);
??0AppearanceHuman@@QEAA@PEAVAnimationClassHuman@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+0*8]
??0AppearanceHuman@@QEAA@PEAVAnimationClassHuman@@PEAVGameDataCopyStandalone@@PEAVCharacter@@PEAVGameData@@@Z endp

?_DESTRUCTOR@AppearanceHuman@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::~AppearanceHuman();
??1AppearanceHuman@@UEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+1*8]
??1AppearanceHuman@@UEAA@XZ endp

?_NV_setGender@AppearanceHuman@@QEAAX_N@Z proc EXPORT
?_NV_setGender@AppearanceHuman@@QEAAX_N@Z endp

; AppearanceHuman::setGender(bool);
?setGender@AppearanceHuman@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+2*8]
?setGender@AppearanceHuman@@UEAAX_N@Z endp

?_NV_periodicUpdate@AppearanceHuman@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::periodicUpdate();
?periodicUpdate@AppearanceHuman@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+3*8]
?periodicUpdate@AppearanceHuman@@UEAAXXZ endp

?_NV_setAttachmentsVisible@AppearanceHuman@@QEAAX_N@Z proc EXPORT
?_NV_setAttachmentsVisible@AppearanceHuman@@QEAAX_N@Z endp

; AppearanceHuman::setAttachmentsVisible(bool);
?setAttachmentsVisible@AppearanceHuman@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+4*8]
?setAttachmentsVisible@AppearanceHuman@@UEAAX_N@Z endp

; AppearanceHuman::setHiddenPartsEnabled(bool);
?setHiddenPartsEnabled@AppearanceHuman@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+5*8]
?setHiddenPartsEnabled@AppearanceHuman@@QEAAX_N@Z endp

; AppearanceHuman::showFace(bool);
?showFace@AppearanceHuman@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+6*8]
?showFace@AppearanceHuman@@QEAAX_N@Z endp

?_NV_setFlayed@AppearanceHuman@@QEAAX_N@Z proc EXPORT
?_NV_setFlayed@AppearanceHuman@@QEAAX_N@Z endp

; AppearanceHuman::setFlayed(bool);
?setFlayed@AppearanceHuman@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+7*8]
?setFlayed@AppearanceHuman@@UEAAX_N@Z endp

?_NV_isFlayed@AppearanceHuman@@QEBA_NXZ proc EXPORT
?_NV_isFlayed@AppearanceHuman@@QEBA_NXZ endp

; AppearanceHuman::isFlayed();
?isFlayed@AppearanceHuman@@UEBA_NXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+8*8]
?isFlayed@AppearanceHuman@@UEBA_NXZ endp

; AppearanceHuman::updateProportions();
?updateProportions@AppearanceHuman@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+9*8]
?updateProportions@AppearanceHuman@@QEAAXXZ endp

?_NV_createBody@AppearanceHuman@@QEAAXXZ proc EXPORT
?_NV_createBody@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::createBody();
?createBody@AppearanceHuman@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+10*8]
?createBody@AppearanceHuman@@UEAAXXZ endp

?_NV_updateAppearance@AppearanceHuman@@QEAAXXZ proc EXPORT
?_NV_updateAppearance@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::updateAppearance();
?updateAppearance@AppearanceHuman@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+11*8]
?updateAppearance@AppearanceHuman@@UEAAXXZ endp

; AppearanceHuman::updateHiddenParts();
?updateHiddenParts@AppearanceHuman@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+12*8]
?updateHiddenParts@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::updatePysiqueFromStats();
?updatePysiqueFromStats@AppearanceHuman@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+13*8]
?updatePysiqueFromStats@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::updatePhysiqueMuscleMults();
?updatePhysiqueMuscleMults@AppearanceHuman@@QEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+14*8]
?updatePhysiqueMuscleMults@AppearanceHuman@@QEAAXXZ endp

?_NV_updateCharaterTexture@AppearanceHuman@@QEAAXXZ proc EXPORT
?_NV_updateCharaterTexture@AppearanceHuman@@QEAAXXZ endp

; AppearanceHuman::updateCharaterTexture();
?updateCharaterTexture@AppearanceHuman@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceHuman_base+15*8]
?updateCharaterTexture@AppearanceHuman@@UEAAXXZ endp

; symbol is too long
jmp function_pointers[_AppearanceHuman_base+16*8]

; AppearanceHuman::setPosture(float, float, float);
?setPosture@AppearanceHuman@@QEAAXMMM@Z proc EXPORT
jmp function_pointers[_AppearanceHuman_base+17*8]
?setPosture@AppearanceHuman@@QEAAXMMM@Z endp
