
?_CONSTRUCTOR@AppearanceAnimal@@QEAAPEAV1@PEAVAnimationClassAnimal@@PEAVGameDataCopyStandalone@@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@AppearanceAnimal@@QEAAPEAV1@PEAVAnimationClassAnimal@@PEAVGameDataCopyStandalone@@PEAVCharacter@@@Z endp

; AppearanceAnimal::AppearanceAnimal(class AnimationClassAnimal *, class GameDataCopyStandalone *, class Character *);
??0AppearanceAnimal@@QEAA@PEAVAnimationClassAnimal@@PEAVGameDataCopyStandalone@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_AppearanceAnimal_base+0*8]
??0AppearanceAnimal@@QEAA@PEAVAnimationClassAnimal@@PEAVGameDataCopyStandalone@@PEAVCharacter@@@Z endp

?_DESTRUCTOR@AppearanceAnimal@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AppearanceAnimal@@QEAAXXZ endp

; AppearanceAnimal::~AppearanceAnimal();
??1AppearanceAnimal@@UEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceAnimal_base+1*8]
??1AppearanceAnimal@@UEAA@XZ endp

?_NV_createBody@AppearanceAnimal@@QEAAXXZ proc EXPORT
?_NV_createBody@AppearanceAnimal@@QEAAXXZ endp

; AppearanceAnimal::createBody();
?createBody@AppearanceAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceAnimal_base+2*8]
?createBody@AppearanceAnimal@@UEAAXXZ endp

?_NV_updateCharaterTexture@AppearanceAnimal@@QEAAXXZ proc EXPORT
?_NV_updateCharaterTexture@AppearanceAnimal@@QEAAXXZ endp

; AppearanceAnimal::updateCharaterTexture();
?updateCharaterTexture@AppearanceAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_AppearanceAnimal_base+3*8]
?updateCharaterTexture@AppearanceAnimal@@UEAAXXZ endp
