
?_NV_clamp@DataRangePose@AppearanceManager@@QEBAXPEAVGameData@@@Z proc EXPORT
?_NV_clamp@DataRangePose@AppearanceManager@@QEBAXPEAVGameData@@@Z endp

; AppearanceManager::DataRangePose::clamp(class GameData *);
?clamp@DataRangePose@AppearanceManager@@UEBAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangePose_base+0*8]
?clamp@DataRangePose@AppearanceManager@@UEBAXPEAVGameData@@@Z endp

?_CONSTRUCTOR@DataRangePose@AppearanceManager@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@DataRangePose@AppearanceManager@@QEAAPEAV12@AEBV12@@Z endp

; AppearanceManager::DataRangePose::DataRangePose(const class AppearanceManager::DataRangePose &);
??0DataRangePose@AppearanceManager@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangePose_base+1*8]
??0DataRangePose@AppearanceManager@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@DataRangePose@AppearanceManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@DataRangePose@AppearanceManager@@QEAAPEAV12@XZ endp

; AppearanceManager::DataRangePose::DataRangePose();
??0DataRangePose@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangePose_base+2*8]
??0DataRangePose@AppearanceManager@@QEAA@XZ endp

?_DESTRUCTOR@DataRangePose@AppearanceManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataRangePose@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::DataRangePose::~DataRangePose();
??1DataRangePose@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangePose_base+3*8]
??1DataRangePose@AppearanceManager@@QEAA@XZ endp

; AppearanceManager::DataRangePose::operator=(const class AppearanceManager::DataRangePose &);
??4DataRangePose@AppearanceManager@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_DataRangePose_base+4*8]
??4DataRangePose@AppearanceManager@@QEAAAEAV01@AEBV01@@Z endp
