
?_CONSTRUCTOR@AppearanceData@AppearanceManager@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@AppearanceData@AppearanceManager@@QEAAPEAV12@AEBV12@@Z endp

; AppearanceManager::AppearanceData::AppearanceData(const class AppearanceManager::AppearanceData &);
??0AppearanceData@AppearanceManager@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_AppearanceData_base+0*8]
??0AppearanceData@AppearanceManager@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@AppearanceData@AppearanceManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@AppearanceData@AppearanceManager@@QEAAPEAV12@XZ endp

; AppearanceManager::AppearanceData::AppearanceData();
??0AppearanceData@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_AppearanceData_base+1*8]
??0AppearanceData@AppearanceManager@@QEAA@XZ endp

?_DESTRUCTOR@AppearanceData@AppearanceManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AppearanceData@AppearanceManager@@QEAAXXZ endp

; AppearanceManager::AppearanceData::~AppearanceData();
??1AppearanceData@AppearanceManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_AppearanceManager_AppearanceData_base+2*8]
??1AppearanceData@AppearanceManager@@QEAA@XZ endp

; AppearanceManager::AppearanceData::operator=(const class AppearanceManager::AppearanceData &);
??4AppearanceData@AppearanceManager@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_AppearanceManager_AppearanceData_base+3*8]
??4AppearanceData@AppearanceManager@@QEAAAEAV01@AEBV01@@Z endp
