
?_NV_getClassType@Armour@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@Armour@@QEBA?AW4itemType@@XZ endp

; Armour::getClassType();
?getClassType@Armour@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Armour_base+0*8]
?getClassType@Armour@@UEBA?AW4itemType@@XZ endp

?_NV_isArmour@Armour@@QEAAPEAV1@XZ proc EXPORT
?_NV_isArmour@Armour@@QEAAPEAV1@XZ endp

; Armour::isArmour();
?isArmour@Armour@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Armour_base+1*8]
?isArmour@Armour@@UEAAPEAV1@XZ endp

?_NV_getItemWeight@Armour@@QEBAMXZ proc EXPORT
?_NV_getItemWeight@Armour@@QEBAMXZ endp

; Armour::getItemWeight();
?getItemWeight@Armour@@UEBAMXZ proc EXPORT
jmp function_pointers[_Armour_base+2*8]
?getItemWeight@Armour@@UEBAMXZ endp

?_NV_getValueSingle@Armour@@QEBAH_N@Z proc EXPORT
?_NV_getValueSingle@Armour@@QEBAH_N@Z endp

; Armour::getValueSingle(bool);
?getValueSingle@Armour@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_Armour_base+3*8]
?getValueSingle@Armour@@UEBAH_N@Z endp

?_NV_getTooltipData1@Armour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@Armour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Armour::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@Armour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Armour_base+4*8]
?getTooltipData1@Armour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@Armour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@Armour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Armour::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@Armour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Armour_base+5*8]
?getTooltipData2@Armour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Armour::didIHitFlesh(class GameData *);
?didIHitFlesh@Armour@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Armour_base+6*8]
?didIHitFlesh@Armour@@QEAA_NPEAVGameData@@@Z endp

; Armour::hasArmourCoverage();
?hasArmourCoverage@Armour@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Armour_base+7*8]
?hasArmourCoverage@Armour@@QEBA_NXZ endp

?_NV_getCraftTime@Armour@@QEAAMXZ proc EXPORT
?_NV_getCraftTime@Armour@@QEAAMXZ endp

; Armour::getCraftTime();
?getCraftTime@Armour@@UEAAMXZ proc EXPORT
jmp function_pointers[_Armour_base+8*8]
?getCraftTime@Armour@@UEAAMXZ endp

; Armour::getArmourCraftingMaterialConsumptionRate(class GameData *);
?getArmourCraftingMaterialConsumptionRate@Armour@@SAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Armour_base+9*8]
?getArmourCraftingMaterialConsumptionRate@Armour@@SAMPEAVGameData@@@Z endp

; Armour::getWeatherProtection_simple(enum WeatherAffecting);
?getWeatherProtection_simple@Armour@@QEAAMW4WeatherAffecting@@@Z proc EXPORT
jmp function_pointers[_Armour_base+10*8]
?getWeatherProtection_simple@Armour@@QEAAMW4WeatherAffecting@@@Z endp

?_CONSTRUCTOR@Armour@@QEAAPEAV1@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z proc EXPORT
?_CONSTRUCTOR@Armour@@QEAAPEAV1@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z endp

; Armour::Armour(class GameData *, class GameData *, class hand, class Faction *, int);
??0Armour@@QEAA@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z proc EXPORT
jmp function_pointers[_Armour_base+11*8]
??0Armour@@QEAA@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z endp

?_DESTRUCTOR@Armour@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Armour@@QEAAXXZ endp

; Armour::~Armour();
??1Armour@@UEAA@XZ proc EXPORT
jmp function_pointers[_Armour_base+12*8]
??1Armour@@UEAA@XZ endp
