
?_CONSTRUCTOR@BackpackInventoryLayout@@QEAAPEAV1@_N@Z proc EXPORT
?_CONSTRUCTOR@BackpackInventoryLayout@@QEAAPEAV1@_N@Z endp

; BackpackInventoryLayout::BackpackInventoryLayout(bool);
??0BackpackInventoryLayout@@QEAA@_N@Z proc EXPORT
jmp function_pointers[_BackpackInventoryLayout_base+0*8]
??0BackpackInventoryLayout@@QEAA@_N@Z endp

; symbol is too long
; ?setupSections@BackpackInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; BackpackInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
BackpackInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_BackpackInventoryLayout_base+1*8]
BackpackInventoryLayout_setupSections_PLACEHOLDER endp

?_DESTRUCTOR@BackpackInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BackpackInventoryLayout@@QEAAXXZ endp

; BackpackInventoryLayout::~BackpackInventoryLayout();
??1BackpackInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_BackpackInventoryLayout_base+2*8]
??1BackpackInventoryLayout@@UEAA@XZ endp
