
?_CONSTRUCTOR@Bounty@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Bounty@@QEAAPEAV1@XZ endp

; Bounty::Bounty();
??0Bounty@@QEAA@XZ proc EXPORT
jmp function_pointers[_Bounty_base+0*8]
??0Bounty@@QEAA@XZ endp

; Bounty::addCrime(enum CrimeEnum);
?addCrime@Bounty@@QEAAXW4CrimeEnum@@@Z proc EXPORT
jmp function_pointers[_Bounty_base+1*8]
?addCrime@Bounty@@QEAAXW4CrimeEnum@@@Z endp

; Bounty::hasCrime(enum CrimeEnum);
?hasCrime@Bounty@@QEBA_NW4CrimeEnum@@@Z proc EXPORT
jmp function_pointers[_Bounty_base+2*8]
?hasCrime@Bounty@@QEBA_NW4CrimeEnum@@@Z endp
