
?_CONSTRUCTOR@BuildModeWindow@@QEAAPEAV1@PEAVPlayerBuildMode@@_N@Z proc EXPORT
?_CONSTRUCTOR@BuildModeWindow@@QEAAPEAV1@PEAVPlayerBuildMode@@_N@Z endp

; BuildModeWindow::BuildModeWindow(class PlayerBuildMode *, bool);
??0BuildModeWindow@@QEAA@PEAVPlayerBuildMode@@_N@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+0*8]
??0BuildModeWindow@@QEAA@PEAVPlayerBuildMode@@_N@Z endp

?_DESTRUCTOR@BuildModeWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::~BuildModeWindow();
??1BuildModeWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+1*8]
??1BuildModeWindow@@UEAA@XZ endp

; BuildModeWindow::setMessage(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setMessage@BuildModeWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+2*8]
?setMessage@BuildModeWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; BuildModeWindow::getBuildingListWidget();
?getBuildingListWidget@BuildModeWindow@@QEBAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+3*8]
?getBuildingListWidget@BuildModeWindow@@QEBAPEAVWidget@MyGUI@@XZ endp

; BuildModeWindow::setVisible(bool);
?setVisible@BuildModeWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+4*8]
?setVisible@BuildModeWindow@@QEAAX_N@Z endp

; BuildModeWindow::setupData();
?setupData@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+5*8]
?setupData@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::listCategories();
?listCategories@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+6*8]
?listCategories@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::listBuildingGroups();
?listBuildingGroups@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+7*8]
?listBuildingGroups@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::updateBuildingUI();
?updateBuildingUI@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+8*8]
?updateBuildingUI@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::categorySelected(class MyGUI::ListBox *, unsigned __int64);
?categorySelected@BuildModeWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+9*8]
?categorySelected@BuildModeWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; BuildModeWindow::buildingSelected(class MyGUI::ListBox *, unsigned __int64);
?buildingSelected@BuildModeWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+10*8]
?buildingSelected@BuildModeWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; BuildModeWindow::build();
?build@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+11*8]
?build@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::confirm(class MyGUI::Widget *);
?confirm@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+12*8]
?confirm@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::undo(class MyGUI::Widget *);
?undo@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+13*8]
?undo@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::close(class MyGUI::Widget *);
?close@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+14*8]
?close@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::buildingTypePrev(class MyGUI::Widget *);
?buildingTypePrev@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+15*8]
?buildingTypePrev@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::buildingTypeNext(class MyGUI::Widget *);
?buildingTypeNext@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+16*8]
?buildingTypeNext@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::showBuildingStats();
?showBuildingStats@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+17*8]
?showBuildingStats@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::update();
?update@BuildModeWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_BuildModeWindow_base+18*8]
?update@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::compareBuildMaterials(const class GameData *, const class GameData *);
?compareBuildMaterials@BuildModeWindow@@SA_NPEBVGameData@@0@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+19*8]
?compareBuildMaterials@BuildModeWindow@@SA_NPEBVGameData@@0@Z endp

; BuildModeWindow::changeFloorButtonUp(class MyGUI::Widget *);
?changeFloorButtonUp@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+20*8]
?changeFloorButtonUp@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::changeFloorButtonDown(class MyGUI::Widget *);
?changeFloorButtonDown@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+21*8]
?changeFloorButtonDown@BuildModeWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; BuildModeWindow::changeCurrentIndex(int);
?changeCurrentIndex@BuildModeWindow@@QEAAXH@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_base+22*8]
?changeCurrentIndex@BuildModeWindow@@QEAAXH@Z endp
