
; Building::getScale();
?getScale@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_base+0*8]
?getScale@Building@@QEBAMXZ endp

?_NV_getBuildState@Building@@QEAAPEAVConstructionState@1@XZ proc EXPORT
?_NV_getBuildState@Building@@QEAAPEAVConstructionState@1@XZ endp

; Building::getBuildState();
?getBuildState@Building@@UEAAPEAVConstructionState@1@XZ proc EXPORT
jmp function_pointers[_Building_base+1*8]
?getBuildState@Building@@UEAAPEAVConstructionState@1@XZ endp

; Building::getBuildState_ActualNonShared();
?getBuildState_ActualNonShared@Building@@QEAAPEAVConstructionState@1@XZ proc EXPORT
jmp function_pointers[_Building_base+2*8]
?getBuildState_ActualNonShared@Building@@QEAAPEAVConstructionState@1@XZ endp

?_NV_select@Building@@QEAAXXZ proc EXPORT
?_NV_select@Building@@QEAAXXZ endp

; Building::select();
?select@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+3*8]
?select@Building@@UEAAXXZ endp

; Building::getBuildingDesignation();
?getBuildingDesignation@Building@@QEBA?AW4BuildingDesignation@@XZ proc EXPORT
jmp function_pointers[_Building_base+4*8]
?getBuildingDesignation@Building@@QEBA?AW4BuildingDesignation@@XZ endp

?_NV_addConstructionProgress@Building@@QEAAXM@Z proc EXPORT
?_NV_addConstructionProgress@Building@@QEAAXM@Z endp

; Building::addConstructionProgress(float);
?addConstructionProgress@Building@@UEAAXM@Z proc EXPORT
jmp function_pointers[_Building_base+5*8]
?addConstructionProgress@Building@@UEAAXM@Z endp

?_NV_setConstructionProgress@Building@@QEAAXM@Z proc EXPORT
?_NV_setConstructionProgress@Building@@QEAAXM@Z endp

; Building::setConstructionProgress(float);
?setConstructionProgress@Building@@UEAAXM@Z proc EXPORT
jmp function_pointers[_Building_base+6*8]
?setConstructionProgress@Building@@UEAAXM@Z endp

?_NV_notifyConstructionComplete@Building@@QEAAXXZ proc EXPORT
?_NV_notifyConstructionComplete@Building@@QEAAXXZ endp

; Building::notifyConstructionComplete();
?notifyConstructionComplete@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+7*8]
?notifyConstructionComplete@Building@@UEAAXXZ endp

?_NV_addDismantleProgress@Building@@QEAA_NM@Z proc EXPORT
?_NV_addDismantleProgress@Building@@QEAA_NM@Z endp

; Building::addDismantleProgress(float);
?addDismantleProgress@Building@@UEAA_NM@Z proc EXPORT
jmp function_pointers[_Building_base+8*8]
?addDismantleProgress@Building@@UEAA_NM@Z endp

?_NV_notifyConstructionDismantling@Building@@QEAAXXZ proc EXPORT
?_NV_notifyConstructionDismantling@Building@@QEAAXXZ endp

; Building::notifyConstructionDismantling();
?notifyConstructionDismantling@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+9*8]
?notifyConstructionDismantling@Building@@UEAAXXZ endp

; Building::dropMats();
?dropMats@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+10*8]
?dropMats@Building@@QEAAXXZ endp

?_NV_upgrade@Building@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_upgrade@Building@@QEAAXPEAVDataPanelLine@@@Z endp

; Building::upgrade(class DataPanelLine *);
?upgrade@Building@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_Building_base+11*8]
?upgrade@Building@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_downgrade@Building@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_downgrade@Building@@QEAAXPEAVDataPanelLine@@@Z endp

; Building::downgrade(class DataPanelLine *);
?downgrade@Building@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_Building_base+12*8]
?downgrade@Building@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_canUpgrade@Building@@QEAAPEAVGameData@@XZ proc EXPORT
?_NV_canUpgrade@Building@@QEAAPEAVGameData@@XZ endp

; Building::canUpgrade();
?canUpgrade@Building@@UEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Building_base+13*8]
?canUpgrade@Building@@UEAAPEAVGameData@@XZ endp

?_NV_canDowngrade@Building@@QEAAPEAVGameData@@XZ proc EXPORT
?_NV_canDowngrade@Building@@QEAAPEAVGameData@@XZ endp

; Building::canDowngrade();
?canDowngrade@Building@@UEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Building_base+14*8]
?canDowngrade@Building@@UEAAPEAVGameData@@XZ endp

?_NV_canDismantle@Building@@QEBA_NXZ proc EXPORT
?_NV_canDismantle@Building@@QEBA_NXZ endp

; Building::canDismantle();
?canDismantle@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+15*8]
?canDismantle@Building@@UEBA_NXZ endp

?_NV_buyMeAsk@Building@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_buyMeAsk@Building@@QEAAXPEAVDataPanelLine@@@Z endp

; Building::buyMeAsk(class DataPanelLine *);
?buyMeAsk@Building@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_Building_base+16*8]
?buyMeAsk@Building@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_buyMeCallback@Building@@QEAAXH@Z proc EXPORT
?_NV_buyMeCallback@Building@@QEAAXH@Z endp

; Building::buyMeCallback(int);
?buyMeCallback@Building@@UEAAXH@Z proc EXPORT
jmp function_pointers[_Building_base+17*8]
?buyMeCallback@Building@@UEAAXH@Z endp

; Building::calculateSaleValue();
?calculateSaleValue@Building@@QEAAHXZ proc EXPORT
jmp function_pointers[_Building_base+18*8]
?calculateSaleValue@Building@@QEAAHXZ endp

; Building::loadNodes();
?loadNodes@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+19*8]
?loadNodes@Building@@QEAAXXZ endp

?_NV_isPublic@Building@@QEBA_NXZ proc EXPORT
?_NV_isPublic@Building@@QEBA_NXZ endp

; Building::isPublic();
?isPublic@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+20*8]
?isPublic@Building@@UEBA_NXZ endp

?_NV_togglePublic@Building@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_togglePublic@Building@@QEAAXPEAVDataPanelLine@@@Z endp

; Building::togglePublic(class DataPanelLine *);
?togglePublic@Building@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_Building_base+21*8]
?togglePublic@Building@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_dismantleButton@Building@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_dismantleButton@Building@@QEAAXPEAVDataPanelLine@@@Z endp

; Building::dismantleButton(class DataPanelLine *);
?dismantleButton@Building@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_Building_base+22*8]
?dismantleButton@Building@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_pauseButton@Building@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_pauseButton@Building@@QEAAXPEAVDataPanelLine@@@Z endp

; Building::pauseButton(class DataPanelLine *);
?pauseButton@Building@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_Building_base+23*8]
?pauseButton@Building@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_confirmDismantle@Building@@QEAAXH@Z proc EXPORT
?_NV_confirmDismantle@Building@@QEAAXH@Z endp

; Building::confirmDismantle(int);
?confirmDismantle@Building@@UEAAXH@Z proc EXPORT
jmp function_pointers[_Building_base+24*8]
?confirmDismantle@Building@@UEAAXH@Z endp

?_NV_isAShop@Building@@QEAA_NXZ proc EXPORT
?_NV_isAShop@Building@@QEAA_NXZ endp

; Building::isAShop();
?isAShop@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+25*8]
?isAShop@Building@@UEAA_NXZ endp

?_NV_isForSale@Building@@QEAA_NXZ proc EXPORT
?_NV_isForSale@Building@@QEAA_NXZ endp

; Building::isForSale();
?isForSale@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+26*8]
?isForSale@Building@@UEAA_NXZ endp

?_NV_isAWall@Building@@QEAAPEAVWallBuilding@@XZ proc EXPORT
?_NV_isAWall@Building@@QEAAPEAVWallBuilding@@XZ endp

; Building::isAWall();
?isAWall@Building@@UEAAPEAVWallBuilding@@XZ proc EXPORT
jmp function_pointers[_Building_base+27*8]
?isAWall@Building@@UEAAPEAVWallBuilding@@XZ endp

?_NV_isAWallRamp@Building@@QEAA_NXZ proc EXPORT
?_NV_isAWallRamp@Building@@QEAA_NXZ endp

; Building::isAWallRamp();
?isAWallRamp@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+28*8]
?isAWallRamp@Building@@UEAA_NXZ endp

; Building::hasInterior();
?hasInterior@Building@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+29*8]
?hasInterior@Building@@QEAA_NXZ endp

; Building::affectsNavmesh();
?affectsNavmesh@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+30*8]
?affectsNavmesh@Building@@QEBA_NXZ endp

; Building::setResidentSquad(class Platoon *);
?setResidentSquad@Building@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Building_base+31*8]
?setResidentSquad@Building@@QEAAXPEAVPlatoon@@@Z endp

; Building::getResidentSquadLeader();
?getResidentSquadLeader@Building@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_Building_base+32*8]
?getResidentSquadLeader@Building@@QEBAPEAVCharacter@@XZ endp

; Building::setDesignation(enum BuildingDesignation);
?setDesignation@Building@@QEAAXW4BuildingDesignation@@@Z proc EXPORT
jmp function_pointers[_Building_base+33*8]
?setDesignation@Building@@QEAAXW4BuildingDesignation@@@Z endp

; Building::getWallEndPosition();
?getWallEndPosition@Building@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Building_base+34*8]
?getWallEndPosition@Building@@QEAA?AVVector3@Ogre@@XZ endp

?_NV_setupMiningResourceLevel@Building@@QEAAXXZ proc EXPORT
?_NV_setupMiningResourceLevel@Building@@QEAAXXZ endp

; Building::setupMiningResourceLevel();
?setupMiningResourceLevel@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+35*8]
?setupMiningResourceLevel@Building@@UEAAXXZ endp

?_NV_getMiningResourceLevel@Building@@QEBAMXZ proc EXPORT
?_NV_getMiningResourceLevel@Building@@QEBAMXZ endp

; Building::getMiningResourceLevel();
?getMiningResourceLevel@Building@@UEBAMXZ proc EXPORT
jmp function_pointers[_Building_base+36*8]
?getMiningResourceLevel@Building@@UEBAMXZ endp

; Building::addAnInternalBuilding(class Building *);
?addAnInternalBuilding@Building@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_Building_base+37*8]
?addAnInternalBuilding@Building@@QEAAXPEAV1@@Z endp

; Building::removeAnInternalBuilding(const class hand &);
?removeAnInternalBuilding@Building@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Building_base+38*8]
?removeAnInternalBuilding@Building@@QEAAXAEBVhand@@@Z endp

; Building::getNumInternalBuildings();
?getNumInternalBuildings@Building@@QEBAHXZ proc EXPORT
jmp function_pointers[_Building_base+39*8]
?getNumInternalBuildings@Building@@QEBAHXZ endp

; Building::addAnInternalItem(class BuildingItemGroup *);
?addAnInternalItem@Building@@QEAAXPEAVBuildingItemGroup@@@Z proc EXPORT
jmp function_pointers[_Building_base+40*8]
?addAnInternalItem@Building@@QEAAXPEAVBuildingItemGroup@@@Z endp

; Building::removeAnInternalItem(class BuildingItemGroup *);
?removeAnInternalItem@Building@@QEAAXPEAVBuildingItemGroup@@@Z proc EXPORT
jmp function_pointers[_Building_base+41*8]
?removeAnInternalItem@Building@@QEAAXPEAVBuildingItemGroup@@@Z endp

; Building::getMountedBuildings(class lektor<Building *> *);
?getMountedBuildings@Building@@QEAAHPEAV?$lektor@PEAVBuilding@@@@@Z proc EXPORT
jmp function_pointers[_Building_base+42*8]
?getMountedBuildings@Building@@QEAAHPEAV?$lektor@PEAVBuilding@@@@@Z endp

; Building::moveMountedBuildings();
?moveMountedBuildings@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+43*8]
?moveMountedBuildings@Building@@QEAAXXZ endp

?_NV_setHandle@Building@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@Building@@QEAAXAEBVhand@@@Z endp

; Building::setHandle(const class hand &);
?setHandle@Building@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Building_base+44*8]
?setHandle@Building@@UEAAXAEBVhand@@@Z endp

; Building::reCheckInsideOutsideFortificationStatus();
?reCheckInsideOutsideFortificationStatus@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+45*8]
?reCheckInsideOutsideFortificationStatus@Building@@QEAAXXZ endp

?_NV_setInsideTownWalls@Building@@QEAAXH@Z proc EXPORT
?_NV_setInsideTownWalls@Building@@QEAAXH@Z endp

; Building::setInsideTownWalls(int);
?setInsideTownWalls@Building@@UEAAXH@Z proc EXPORT
jmp function_pointers[_Building_base+46*8]
?setInsideTownWalls@Building@@UEAAXH@Z endp

?_NV_postCreationPathfinderSetupStuff@Building@@QEAAXXZ proc EXPORT
?_NV_postCreationPathfinderSetupStuff@Building@@QEAAXXZ endp

; Building::postCreationPathfinderSetupStuff();
?postCreationPathfinderSetupStuff@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+47*8]
?postCreationPathfinderSetupStuff@Building@@UEAAXXZ endp

?_NV_getSpecialFunction@Building@@QEBA?AW4BuildingFunction@@XZ proc EXPORT
?_NV_getSpecialFunction@Building@@QEBA?AW4BuildingFunction@@XZ endp

; Building::getSpecialFunction();
?getSpecialFunction@Building@@UEBA?AW4BuildingFunction@@XZ proc EXPORT
jmp function_pointers[_Building_base+48*8]
?getSpecialFunction@Building@@UEBA?AW4BuildingFunction@@XZ endp

?_NV_getFunctionStuff@Building@@QEAAPEAVStorageBuilding@@XZ proc EXPORT
?_NV_getFunctionStuff@Building@@QEAAPEAVStorageBuilding@@XZ endp

; Building::getFunctionStuff();
?getFunctionStuff@Building@@UEAAPEAVStorageBuilding@@XZ proc EXPORT
jmp function_pointers[_Building_base+49*8]
?getFunctionStuff@Building@@UEAAPEAVStorageBuilding@@XZ endp

?_NV_getUseableStuff@Building@@QEAAPEAVUseableStuff@@XZ proc EXPORT
?_NV_getUseableStuff@Building@@QEAAPEAVUseableStuff@@XZ endp

; Building::getUseableStuff();
?getUseableStuff@Building@@UEAAPEAVUseableStuff@@XZ proc EXPORT
jmp function_pointers[_Building_base+50*8]
?getUseableStuff@Building@@UEAAPEAVUseableStuff@@XZ endp

?_NV_isBroken@Building@@QEBA_NXZ proc EXPORT
?_NV_isBroken@Building@@QEBA_NXZ endp

; Building::isBroken();
?isBroken@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+51*8]
?isBroken@Building@@UEBA_NXZ endp

?_NV_setBroken@Building@@QEAAX_N@Z proc EXPORT
?_NV_setBroken@Building@@QEAAX_N@Z endp

; Building::setBroken(bool);
?setBroken@Building@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+52*8]
?setBroken@Building@@UEAAX_N@Z endp

?_NV_switchPowerOn@Building@@QEAAX_N@Z proc EXPORT
?_NV_switchPowerOn@Building@@QEAAX_N@Z endp

; Building::switchPowerOn(bool);
?switchPowerOn@Building@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+53*8]
?switchPowerOn@Building@@UEAAX_N@Z endp

?_NV_isPowerOn@Building@@QEBA_NXZ proc EXPORT
?_NV_isPowerOn@Building@@QEBA_NXZ endp

; Building::isPowerOn();
?isPowerOn@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+54*8]
?isPowerOn@Building@@UEBA_NXZ endp

?_NV_isDamaged@Building@@QEAA_NXZ proc EXPORT
?_NV_isDamaged@Building@@QEAA_NXZ endp

; Building::isDamaged();
?isDamaged@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+55*8]
?isDamaged@Building@@UEAA_NXZ endp

?_NV_isDestroyed@Building@@QEBA_NXZ proc EXPORT
?_NV_isDestroyed@Building@@QEBA_NXZ endp

; Building::isDestroyed();
?isDestroyed@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+56*8]
?isDestroyed@Building@@UEBA_NXZ endp

?_NV_isSign@Building@@QEBA_NXZ proc EXPORT
?_NV_isSign@Building@@QEBA_NXZ endp

; Building::isSign();
?isSign@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+57*8]
?isSign@Building@@UEBA_NXZ endp

?_NV_setDestroyed@Building@@QEAAX_N@Z proc EXPORT
?_NV_setDestroyed@Building@@QEAAX_N@Z endp

; Building::setDestroyed(bool);
?setDestroyed@Building@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+58*8]
?setDestroyed@Building@@UEAAX_N@Z endp

?_NV_canBeDestroyed@Building@@QEBA_NXZ proc EXPORT
?_NV_canBeDestroyed@Building@@QEBA_NXZ endp

; Building::canBeDestroyed();
?canBeDestroyed@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+59*8]
?canBeDestroyed@Building@@UEBA_NXZ endp

; Building::setNestTag();
?setNestTag@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+60*8]
?setNestTag@Building@@QEAAXXZ endp

?_NV_getReachRange@Building@@QEBAMXZ proc EXPORT
?_NV_getReachRange@Building@@QEBAMXZ endp

; Building::getReachRange();
?getReachRange@Building@@UEBAMXZ proc EXPORT
jmp function_pointers[_Building_base+61*8]
?getReachRange@Building@@UEBAMXZ endp

; Building::hasShopCountersSelling(enum ItemFunction);
?hasShopCountersSelling@Building@@QEAA_NW4ItemFunction@@@Z proc EXPORT
jmp function_pointers[_Building_base+62*8]
?hasShopCountersSelling@Building@@QEAA_NW4ItemFunction@@@Z endp

?_NV_getBuildingClass@Building@@QEBA?AW4BuildingClassType@@XZ proc EXPORT
?_NV_getBuildingClass@Building@@QEBA?AW4BuildingClassType@@XZ endp

; Building::getBuildingClass();
?getBuildingClass@Building@@UEBA?AW4BuildingClassType@@XZ proc EXPORT
jmp function_pointers[_Building_base+63*8]
?getBuildingClass@Building@@UEBA?AW4BuildingClassType@@XZ endp

?_NV_needsSaving@Building@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_needsSaving@Building@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Building::needsSaving(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?needsSaving@Building@@UEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Building_base+64*8]
?needsSaving@Building@@UEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Building::notifyChange();
?notifyChange@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+65*8]
?notifyChange@Building@@QEAAXXZ endp

?_NV_getInstanceID@Building@@QEAAPEAVInstanceID@@XZ proc EXPORT
?_NV_getInstanceID@Building@@QEAAPEAVInstanceID@@XZ endp

; Building::getInstanceID();
?getInstanceID@Building@@UEAAPEAVInstanceID@@XZ proc EXPORT
jmp function_pointers[_Building_base+66*8]
?getInstanceID@Building@@UEAAPEAVInstanceID@@XZ endp

?_NV_getLayoutInstanceID@Building@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getLayoutInstanceID@Building@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Building::getLayoutInstanceID();
?getLayoutInstanceID@Building@@UEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Building_base+67*8]
?getLayoutInstanceID@Building@@UEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_CONSTRUCTOR@Building@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAV1@@Z proc EXPORT
?_CONSTRUCTOR@Building@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAV1@@Z endp

; Building::Building(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0Building@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAV0@@Z proc EXPORT
jmp function_pointers[_Building_base+68*8]
??0Building@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAV0@@Z endp

; Building::setToDefaultFactionDivision();
?setToDefaultFactionDivision@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+69*8]
?setToDefaultFactionDivision@Building@@QEAAXXZ endp

?_NV_getOutputBasedRotationSpeedMult@Building@@QEAAMXZ proc EXPORT
?_NV_getOutputBasedRotationSpeedMult@Building@@QEAAMXZ endp

; Building::getOutputBasedRotationSpeedMult();
?getOutputBasedRotationSpeedMult@Building@@UEAAMXZ proc EXPORT
jmp function_pointers[_Building_base+70*8]
?getOutputBasedRotationSpeedMult@Building@@UEAAMXZ endp

?_NV_calculateEfficiencyMult@Building@@QEBAMXZ proc EXPORT
?_NV_calculateEfficiencyMult@Building@@QEBAMXZ endp

; Building::calculateEfficiencyMult();
?calculateEfficiencyMult@Building@@UEBAMXZ proc EXPORT
jmp function_pointers[_Building_base+71*8]
?calculateEfficiencyMult@Building@@UEBAMXZ endp

?_NV_getSoundIntensity@Building@@QEAAMXZ proc EXPORT
?_NV_getSoundIntensity@Building@@QEAAMXZ endp

; Building::getSoundIntensity();
?getSoundIntensity@Building@@UEAAMXZ proc EXPORT
jmp function_pointers[_Building_base+72*8]
?getSoundIntensity@Building@@UEAAMXZ endp

?_NV_loadUnloadCheck@Building@@QEAAXXZ proc EXPORT
?_NV_loadUnloadCheck@Building@@QEAAXXZ endp

; Building::loadUnloadCheck();
?loadUnloadCheck@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+73*8]
?loadUnloadCheck@Building@@UEAAXXZ endp

?_DESTRUCTOR@Building@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Building@@QEAAXXZ endp

; Building::~Building();
??1Building@@UEAA@XZ proc EXPORT
jmp function_pointers[_Building_base+74*8]
??1Building@@UEAA@XZ endp

?_NV__saveBuildingState@Building@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV__saveBuildingState@Building@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Building::_saveBuildingState(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_saveBuildingState@Building@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Building_base+75*8]
?_saveBuildingState@Building@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV__loadBuildingState@Building@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV__loadBuildingState@Building@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Building::_loadBuildingState(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_loadBuildingState@Building@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Building_base+76*8]
?_loadBuildingState@Building@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getGUIName@Building@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIName@Building@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Building::getGUIName(class DatapanelGUI *, int);
?getGUIName@Building@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Building_base+77*8]
?getGUIName@Building@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIState@Building@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@Building@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Building::getGUIState(class DatapanelGUI *, int);
?getGUIState@Building@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Building_base+78*8]
?getGUIState@Building@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUICondition@Building@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUICondition@Building@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Building::getGUICondition(class DatapanelGUI *, int);
?getGUICondition@Building@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Building_base+79*8]
?getGUICondition@Building@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIUpgrade@Building@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIUpgrade@Building@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Building::getGUIUpgrade(class DatapanelGUI *, int);
?getGUIUpgrade@Building@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Building_base+80*8]
?getGUIUpgrade@Building@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIDestroyButton@Building@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIDestroyButton@Building@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Building::getGUIDestroyButton(class DatapanelGUI *, int);
?getGUIDestroyButton@Building@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Building_base+81*8]
?getGUIDestroyButton@Building@@UEAAXPEAVDatapanelGUI@@H@Z endp

; Building::findAllFurnitureWithFunction(class lektor<Building *> &, enum BuildingFunction);
?findAllFurnitureWithFunction@Building@@QEAAXAEAV?$lektor@PEAVBuilding@@@@W4BuildingFunction@@@Z proc EXPORT
jmp function_pointers[_Building_base+82*8]
?findAllFurnitureWithFunction@Building@@QEAAXAEAV?$lektor@PEAVBuilding@@@@W4BuildingFunction@@@Z endp

?_NV_getProductionBuilding@Building@@QEAAPEAVProductionBuilding@@XZ proc EXPORT
?_NV_getProductionBuilding@Building@@QEAAPEAVProductionBuilding@@XZ endp

; Building::getProductionBuilding();
?getProductionBuilding@Building@@UEAAPEAVProductionBuilding@@XZ proc EXPORT
jmp function_pointers[_Building_base+83*8]
?getProductionBuilding@Building@@UEAAPEAVProductionBuilding@@XZ endp

?_NV_getProductionMultForGUI@Building@@QEAAMXZ proc EXPORT
?_NV_getProductionMultForGUI@Building@@QEAAMXZ endp

; Building::getProductionMultForGUI();
?getProductionMultForGUI@Building@@UEAAMXZ proc EXPORT
jmp function_pointers[_Building_base+84*8]
?getProductionMultForGUI@Building@@UEAAMXZ endp

?_NV_getProductionMult@Building@@QEAAMXZ proc EXPORT
?_NV_getProductionMult@Building@@QEAAMXZ endp

; Building::getProductionMult();
?getProductionMult@Building@@UEAAMXZ proc EXPORT
jmp function_pointers[_Building_base+85*8]
?getProductionMult@Building@@UEAAMXZ endp

; Building::isThePlayer();
?isThePlayer@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+86*8]
?isThePlayer@Building@@QEBA_NXZ endp

?_NV_doorStuff@Building@@QEAAPEAVDoorStuff@@XZ proc EXPORT
?_NV_doorStuff@Building@@QEAAPEAVDoorStuff@@XZ endp

; Building::doorStuff();
?doorStuff@Building@@UEAAPEAVDoorStuff@@XZ proc EXPORT
jmp function_pointers[_Building_base+87*8]
?doorStuff@Building@@UEAAPEAVDoorStuff@@XZ endp

?_NV_doorParentBuilding@Building@@QEBAPEAV1@XZ proc EXPORT
?_NV_doorParentBuilding@Building@@QEBAPEAV1@XZ endp

; Building::doorParentBuilding();
?doorParentBuilding@Building@@UEBAPEAV1@XZ proc EXPORT
jmp function_pointers[_Building_base+88*8]
?doorParentBuilding@Building@@UEBAPEAV1@XZ endp

; Building::isDoor();
?isDoor@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+89*8]
?isDoor@Building@@QEBA_NXZ endp

?_NV_isGate@Building@@QEAAPEAVGatewayBuilding@@XZ proc EXPORT
?_NV_isGate@Building@@QEAAPEAVGatewayBuilding@@XZ endp

; Building::isGate();
?isGate@Building@@UEAAPEAVGatewayBuilding@@XZ proc EXPORT
jmp function_pointers[_Building_base+90*8]
?isGate@Building@@UEAAPEAVGatewayBuilding@@XZ endp

?_NV_getDoor@Building@@QEAAPEAVDoorStuff@@XZ proc EXPORT
?_NV_getDoor@Building@@QEAAPEAVDoorStuff@@XZ endp

; Building::getDoor();
?getDoor@Building@@UEAAPEAVDoorStuff@@XZ proc EXPORT
jmp function_pointers[_Building_base+91*8]
?getDoor@Building@@UEAAPEAVDoorStuff@@XZ endp

; Building::getParentLayout();
?getParentLayout@Building@@QEAAPEAVLayout@@XZ proc EXPORT
jmp function_pointers[_Building_base+92*8]
?getParentLayout@Building@@QEAAPEAVLayout@@XZ endp

; Building::isFurniture();
?isFurniture@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+93*8]
?isFurniture@Building@@QEBA_NXZ endp

; Building::isFurnitureOrDoor();
?isFurnitureOrDoor@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+94*8]
?isFurnitureOrDoor@Building@@QEBA_NXZ endp

; Building::getIsOutsideFurniture();
?getIsOutsideFurniture@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+95*8]
?getIsOutsideFurniture@Building@@QEBA_NXZ endp

; Building::setIsOutsideFurniture(bool);
?setIsOutsideFurniture@Building@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+96*8]
?setIsOutsideFurniture@Building@@QEAAX_N@Z endp

?_NV_getCurrentTownLocation@Building@@QEAAPEAVTownBase@@XZ proc EXPORT
?_NV_getCurrentTownLocation@Building@@QEAAPEAVTownBase@@XZ endp

; Building::getCurrentTownLocation();
?getCurrentTownLocation@Building@@UEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_Building_base+97*8]
?getCurrentTownLocation@Building@@UEAAPEAVTownBase@@XZ endp

; Building::furnitureParentBuilding();
?furnitureParentBuilding@Building@@QEBAPEAV1@XZ proc EXPORT
jmp function_pointers[_Building_base+98*8]
?furnitureParentBuilding@Building@@QEBAPEAV1@XZ endp

; Building::hasAnOpenDoor();
?hasAnOpenDoor@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+99*8]
?hasAnOpenDoor@Building@@QEBA_NXZ endp

; Building::allowAnimals();
?allowAnimals@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+100*8]
?allowAnimals@Building@@QEBA_NXZ endp

?_NV_update@Building@@QEAAXXZ proc EXPORT
?_NV_update@Building@@QEAAXXZ endp

; Building::update();
?update@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+101*8]
?update@Building@@UEAAXXZ endp

?_NV_threadedUpdate@Building@@QEAAXXZ proc EXPORT
?_NV_threadedUpdate@Building@@QEAAXXZ endp

; Building::threadedUpdate();
?threadedUpdate@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+102*8]
?threadedUpdate@Building@@UEAAXXZ endp

?_NV_needsUpdate@Building@@QEAA_NXZ proc EXPORT
?_NV_needsUpdate@Building@@QEAA_NXZ endp

; Building::needsUpdate();
?needsUpdate@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+103*8]
?needsUpdate@Building@@UEAA_NXZ endp

?_NV_isPhysical@Building@@QEBA_NXZ proc EXPORT
?_NV_isPhysical@Building@@QEBA_NXZ endp

; Building::isPhysical();
?isPhysical@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+104*8]
?isPhysical@Building@@UEBA_NXZ endp

?_NV_checkLoadedProperly@Building@@QEAAXXZ proc EXPORT
?_NV_checkLoadedProperly@Building@@QEAAXXZ endp

; Building::checkLoadedProperly();
?checkLoadedProperly@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+105*8]
?checkLoadedProperly@Building@@UEAAXXZ endp

?_NV_serialise@Building@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@Building@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; Building::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@Building@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_Building_base+106*8]
?serialise@Building@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@Building@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@Building@@QEAAXPEAVGameSaveState@@@Z endp

; Building::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@Building@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Building_base+107*8]
?loadFromSerialise@Building@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_loadFromSerialise_TheDoors@Building@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise_TheDoors@Building@@QEAAXPEAVGameSaveState@@@Z endp

; Building::loadFromSerialise_TheDoors(class GameSaveState *);
?loadFromSerialise_TheDoors@Building@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Building_base+108*8]
?loadFromSerialise_TheDoors@Building@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_getGUIData@Building@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@Building@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Building::getGUIData(class DatapanelGUI *, int);
?getGUIData@Building@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Building_base+109*8]
?getGUIData@Building@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_setVisible@Building@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@Building@@QEAAX_N@Z endp

; Building::setVisible(bool);
?setVisible@Building@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+110*8]
?setVisible@Building@@UEAAX_N@Z endp

?_NV_getVisible@Building@@QEBA_NXZ proc EXPORT
?_NV_getVisible@Building@@QEBA_NXZ endp

; Building::getVisible();
?getVisible@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+111*8]
?getVisible@Building@@UEBA_NXZ endp

?_NV_getDoorLock@Building@@QEAAPEAVDoorLock@@XZ proc EXPORT
?_NV_getDoorLock@Building@@QEAAPEAVDoorLock@@XZ endp

; Building::getDoorLock();
?getDoorLock@Building@@UEAAPEAVDoorLock@@XZ proc EXPORT
jmp function_pointers[_Building_base+112*8]
?getDoorLock@Building@@UEAAPEAVDoorLock@@XZ endp

?_NV_hasDoorLock@Building@@QEBA_NXZ proc EXPORT
?_NV_hasDoorLock@Building@@QEBA_NXZ endp

; Building::hasDoorLock();
?hasDoorLock@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+113*8]
?hasDoorLock@Building@@UEBA_NXZ endp

?_NV_getMouseCursor@Building@@QEAA?AW4CursorType@@XZ proc EXPORT
?_NV_getMouseCursor@Building@@QEAA?AW4CursorType@@XZ endp

; Building::getMouseCursor();
?getMouseCursor@Building@@UEAA?AW4CursorType@@XZ proc EXPORT
jmp function_pointers[_Building_base+114*8]
?getMouseCursor@Building@@UEAA?AW4CursorType@@XZ endp

?_NV_getDefaultTask@Building@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@Building@@QEAA?AW4TaskType@@XZ endp

; Building::getDefaultTask();
?getDefaultTask@Building@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_Building_base+115*8]
?getDefaultTask@Building@@UEAA?AW4TaskType@@XZ endp

?_NV_getInventory@Building@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@Building@@QEBAPEAVInventory@@XZ endp

; Building::getInventory();
?getInventory@Building@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_Building_base+116*8]
?getInventory@Building@@UEBAPEAVInventory@@XZ endp

?_NV_getAABB@Building@@QEBA?AUAabb@Ogre@@M@Z proc EXPORT
?_NV_getAABB@Building@@QEBA?AUAabb@Ogre@@M@Z endp

; Building::getAABB(float);
?getAABB@Building@@UEBA?AUAabb@Ogre@@M@Z proc EXPORT
jmp function_pointers[_Building_base+117*8]
?getAABB@Building@@UEBA?AUAabb@Ogre@@M@Z endp

?_NV_getAABB@Building@@QEBAAEBUAabb@Ogre@@XZ proc EXPORT
?_NV_getAABB@Building@@QEBAAEBUAabb@Ogre@@XZ endp

; Building::getAABB();
?getAABB@Building@@UEBAAEBUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_Building_base+118*8]
?getAABB@Building@@UEBAAEBUAabb@Ogre@@XZ endp

; Building::setAABB(const struct Ogre::Aabb &);
?setAABB@Building@@QEAAXAEBUAabb@Ogre@@@Z proc EXPORT
jmp function_pointers[_Building_base+119*8]
?setAABB@Building@@QEAAXAEBUAabb@Ogre@@@Z endp

; Building::_changeTown(class Town *);
?_changeTown@Building@@QEAAXPEAVTown@@@Z proc EXPORT
jmp function_pointers[_Building_base+120*8]
?_changeTown@Building@@QEAAXPEAVTown@@@Z endp

; Building::getTownHandle();
?getTownHandle@Building@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Building_base+121*8]
?getTownHandle@Building@@QEBA?AVhand@@XZ endp

; Building::getTown();
?getTown@Building@@QEBAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_Building_base+122*8]
?getTown@Building@@QEBAPEAVTownBase@@XZ endp

; Building::getRealTown();
?getRealTown@Building@@QEBAPEAVTown@@XZ proc EXPORT
jmp function_pointers[_Building_base+123*8]
?getRealTown@Building@@QEBAPEAVTown@@XZ endp

?_NV_createPhysical@Building@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@Building@@QEAA_NXZ endp

; Building::createPhysical();
?createPhysical@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+124*8]
?createPhysical@Building@@UEAA_NXZ endp

?_NV_destroyPhysical@Building@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@Building@@QEAAXXZ endp

; Building::destroyPhysical();
?destroyPhysical@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+125*8]
?destroyPhysical@Building@@UEAAXXZ endp

; Building::destroyDoors();
?destroyDoors@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+126*8]
?destroyDoors@Building@@QEAAXXZ endp

; Building::createTriggerHull();
?createTriggerHull@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+127*8]
?createTriggerHull@Building@@QEAAXXZ endp

; Building::destroyAudioObject();
?destroyAudioObject@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+128*8]
?destroyAudioObject@Building@@QEAAXXZ endp

; Building::getAudioObject();
?getAudioObject@Building@@QEAA_KXZ proc EXPORT
jmp function_pointers[_Building_base+129*8]
?getAudioObject@Building@@QEAA_KXZ endp

; Building::getGroundType(bool);
?getGroundType@Building@@QEBA?AW4GroundType@@_N@Z proc EXPORT
jmp function_pointers[_Building_base+130*8]
?getGroundType@Building@@QEBA?AW4GroundType@@_N@Z endp

?_NV_isCeilingMounted@Building@@QEAA_NXZ proc EXPORT
?_NV_isCeilingMounted@Building@@QEAA_NXZ endp

; Building::isCeilingMounted();
?isCeilingMounted@Building@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+131*8]
?isCeilingMounted@Building@@UEAA_NXZ endp

?_NV_isIndoors@Building@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_isIndoors@Building@@QEBAAEBVhand@@XZ endp

; Building::isIndoors();
?isIndoors@Building@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Building_base+132*8]
?isIndoors@Building@@UEBAAEBVhand@@XZ endp

?_NV_isIndoors_notDestroyed@Building@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_isIndoors_notDestroyed@Building@@QEBAAEBVhand@@XZ endp

; Building::isIndoors_notDestroyed();
?isIndoors_notDestroyed@Building@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Building_base+133*8]
?isIndoors_notDestroyed@Building@@UEBAAEBVhand@@XZ endp

?_NV_getMountedBuilding@Building@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_getMountedBuilding@Building@@QEBAAEBVhand@@XZ endp

; Building::getMountedBuilding();
?getMountedBuilding@Building@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Building_base+134*8]
?getMountedBuilding@Building@@UEBAAEBVhand@@XZ endp

; Building::getLights(class lektor<PhysicsCollection::LightEnt const *> &, const class Ogre::Vector3 &, float);
?getLights@Building@@QEBAHAEAV?$lektor@PEBVLightEnt@PhysicsCollection@@@@AEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_Building_base+135*8]
?getLights@Building@@QEBAHAEAV?$lektor@PEBVLightEnt@PhysicsCollection@@@@AEBVVector3@Ogre@@M@Z endp

; Building::setFloorVisibility(int, bool);
?setFloorVisibility@Building@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_Building_base+136*8]
?setFloorVisibility@Building@@QEAAXH_N@Z endp

; Building::getNumFloors();
?getNumFloors@Building@@QEBAHXZ proc EXPORT
jmp function_pointers[_Building_base+137*8]
?getNumFloors@Building@@QEBAHXZ endp

; Building::buildingComplete_RestoreMaterial();
?buildingComplete_RestoreMaterial@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+138*8]
?buildingComplete_RestoreMaterial@Building@@QEAAXXZ endp

; Building::loadInteriorPhysical(bool);
?loadInteriorPhysical@Building@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+139*8]
?loadInteriorPhysical@Building@@QEAAX_N@Z endp

; Building::loadInteriorGraphics(bool);
?loadInteriorGraphics@Building@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+140*8]
?loadInteriorGraphics@Building@@QEAAX_N@Z endp

?_NV_setFaction@Building@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
?_NV_setFaction@Building@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

; Building::setFaction(class Faction *, class ActivePlatoon *);
?setFaction@Building@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_Building_base+141*8]
?setFaction@Building@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

; Building::calculateLeftPost();
?calculateLeftPost@Building@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Building_base+142*8]
?calculateLeftPost@Building@@QEBA?AVVector3@Ogre@@XZ endp

; Building::setupLevelData(class Faction *, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setupLevelData@Building@@QEAAXPEAVFaction@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2@Z proc EXPORT
jmp function_pointers[_Building_base+143*8]
?setupLevelData@Building@@QEAAXPEAVFaction@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2@Z endp

?_NV_getLinkLength@Building@@QEBAMXZ proc EXPORT
?_NV_getLinkLength@Building@@QEBAMXZ endp

; Building::getLinkLength();
?getLinkLength@Building@@UEBAMXZ proc EXPORT
jmp function_pointers[_Building_base+144*8]
?getLinkLength@Building@@UEBAMXZ endp

; Building::getRootNode();
?getRootNode@Building@@QEBAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_Building_base+145*8]
?getRootNode@Building@@QEBAPEAVSceneNode@Ogre@@XZ endp

?_NV_getZoneMapLocation@Building@@QEAAPEAVZoneMap@@XZ proc EXPORT
?_NV_getZoneMapLocation@Building@@QEAAPEAVZoneMap@@XZ endp

; Building::getZoneMapLocation();
?getZoneMapLocation@Building@@UEAAPEAVZoneMap@@XZ proc EXPORT
jmp function_pointers[_Building_base+146*8]
?getZoneMapLocation@Building@@UEAAPEAVZoneMap@@XZ endp

?_NV_clearTownBuildingsManagerPtr@Building@@QEAAXXZ proc EXPORT
?_NV_clearTownBuildingsManagerPtr@Building@@QEAAXXZ endp

; Building::clearTownBuildingsManagerPtr();
?clearTownBuildingsManagerPtr@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+147*8]
?clearTownBuildingsManagerPtr@Building@@UEAAXXZ endp

?_NV_setup@Building@@QEAAXXZ proc EXPORT
?_NV_setup@Building@@QEAAXXZ endp

; Building::setup();
?setup@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+148*8]
?setup@Building@@UEAAXXZ endp

?_NV_setupFromData@Building@@QEAAXXZ proc EXPORT
?_NV_setupFromData@Building@@QEAAXXZ endp

; Building::setupFromData();
?setupFromData@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+149*8]
?setupFromData@Building@@UEAAXXZ endp

; Building::setupAudio();
?setupAudio@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+150*8]
?setupAudio@Building@@QEAAXXZ endp

?_NV_switchLights@Building@@QEAAX_N@Z proc EXPORT
?_NV_switchLights@Building@@QEAAX_N@Z endp

; Building::switchLights(bool);
?switchLights@Building@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+151*8]
?switchLights@Building@@UEAAX_N@Z endp

?_NV_switchEffects@Building@@QEAAX_N@Z proc EXPORT
?_NV_switchEffects@Building@@QEAAX_N@Z endp

; Building::switchEffects(bool);
?switchEffects@Building@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Building_base+152*8]
?switchEffects@Building@@UEAAX_N@Z endp

; Building::hasAnyGoodPositionMarkersLeft();
?hasAnyGoodPositionMarkersLeft@Building@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Building_base+153*8]
?hasAnyGoodPositionMarkersLeft@Building@@QEAA_NXZ endp

; Building::notifyBadPositionMarker(const class Ogre::Vector3 &);
?notifyBadPositionMarker@Building@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Building_base+154*8]
?notifyBadPositionMarker@Building@@QEAAXAEBVVector3@Ogre@@@Z endp

?_NV_getPositionMarker@Building@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getPositionMarker@Building@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; Building::getPositionMarker(const class Ogre::Vector3 &);
?getPositionMarker@Building@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_Building_base+155*8]
?getPositionMarker@Building@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_getDirectionMarker@Building@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getDirectionMarker@Building@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; Building::getDirectionMarker(const class Ogre::Vector3 &);
?getDirectionMarker@Building@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_Building_base+156*8]
?getDirectionMarker@Building@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_getDirectionMarkerQuat@Building@@QEAA?AVQuaternion@Ogre@@AEBVVector3@3@@Z proc EXPORT
?_NV_getDirectionMarkerQuat@Building@@QEAA?AVQuaternion@Ogre@@AEBVVector3@3@@Z endp

; Building::getDirectionMarkerQuat(const class Ogre::Vector3 &);
?getDirectionMarkerQuat@Building@@UEAA?AVQuaternion@Ogre@@AEBVVector3@3@@Z proc EXPORT
jmp function_pointers[_Building_base+157*8]
?getDirectionMarkerQuat@Building@@UEAA?AVQuaternion@Ogre@@AEBVVector3@3@@Z endp

?_NV_isCreated@Building@@QEBA_NXZ proc EXPORT
?_NV_isCreated@Building@@QEBA_NXZ endp

; Building::isCreated();
?isCreated@Building@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Building_base+158*8]
?isCreated@Building@@UEBA_NXZ endp

; Building::updateUsageNodes();
?updateUsageNodes@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+159*8]
?updateUsageNodes@Building@@QEAAXXZ endp

; Building::forceValidUsageNodesValidation();
?forceValidUsageNodesValidation@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+160*8]
?forceValidUsageNodesValidation@Building@@QEAAXXZ endp

; Building::addUsageNode(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addUsageNode@Building@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Building_base+161*8]
?addUsageNode@Building@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Building::removeUsageNode(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?removeUsageNode@Building@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Building_base+162*8]
?removeUsageNode@Building@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Building::clearUsageNodes();
?clearUsageNodes@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+163*8]
?clearUsageNodes@Building@@QEAAXXZ endp

?_NV_notifyEffect@Building@@QEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z proc EXPORT
?_NV_notifyEffect@Building@@QEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z endp

; Building::notifyEffect(enum EffectType::Enum, enum WeatherAffecting, float);
?notifyEffect@Building@@UEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z proc EXPORT
jmp function_pointers[_Building_base+164*8]
?notifyEffect@Building@@UEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z endp

; Building::getBuildingPartMaterial(class GameData *, bool, bool, bool, const class Ogre::Vector3 &);
?getBuildingPartMaterial@Building@@SA?AV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVGameData@@_N11AEBVVector3@3@@Z proc EXPORT
jmp function_pointers[_Building_base+165*8]
?getBuildingPartMaterial@Building@@SA?AV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVGameData@@_N11AEBVVector3@3@@Z endp

; Building::setBuildingPartMaterial(class Ogre::Entity *, class GameData *, bool, bool, const class Ogre::Vector3 &);
?setBuildingPartMaterial@Building@@SAXPEAVEntity@Ogre@@PEAVGameData@@_N2AEBVVector3@3@@Z proc EXPORT
jmp function_pointers[_Building_base+166*8]
?setBuildingPartMaterial@Building@@SAXPEAVEntity@Ogre@@PEAVGameData@@_N2AEBVVector3@3@@Z endp

; Building::restoreMaterialToPhysical(class PhysicsCollection *, bool);
?restoreMaterialToPhysical@Building@@QEAAXPEAVPhysicsCollection@@_N@Z proc EXPORT
jmp function_pointers[_Building_base+167*8]
?restoreMaterialToPhysical@Building@@QEAAXPEAVPhysicsCollection@@_N@Z endp

; Building::updatePhysicalWithProgress();
?updatePhysicalWithProgress@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+168*8]
?updatePhysicalWithProgress@Building@@QEAAXXZ endp

; Building::updateWorldAABB(class Ogre::MovableObject *);
?updateWorldAABB@Building@@QEAAXPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_Building_base+169*8]
?updateWorldAABB@Building@@QEAAXPEAVMovableObject@Ogre@@@Z endp

; Building::recalculateWorldAABB();
?recalculateWorldAABB@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+170*8]
?recalculateWorldAABB@Building@@QEAAXXZ endp

; Building::selectPartMaterial(class GameData *);
?selectPartMaterial@Building@@QEAAPEAVGameData@@PEAV2@@Z proc EXPORT
jmp function_pointers[_Building_base+171*8]
?selectPartMaterial@Building@@QEAAPEAVGameData@@PEAV2@@Z endp

; Building::getPartMaterial(class GameData *, class Ogre::Entity *, bool, bool);
?getPartMaterial@Building@@QEAA?AV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVGameData@@PEAVEntity@3@_N2@Z proc EXPORT
jmp function_pointers[_Building_base+172*8]
?getPartMaterial@Building@@QEAA?AV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVGameData@@PEAVEntity@3@_N2@Z endp

; Building::selectParts(const class std::vector<GameDataReference,Ogre::STLAllocator<GameDataReference,Ogre::CategorisedAllocPolicy<0> > > *, class lektor<GameData *> &);
?selectParts@Building@@SAXPEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_Building_base+173*8]
?selectParts@Building@@SAXPEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAV?$lektor@PEAVGameData@@@@@Z endp

; Building::loadParts(class GameData *, class PhysicalEntity *, class PhysicsCollection *, unsigned char, int);
?loadParts@Building@@QEAAXPEAVGameData@@PEAVPhysicalEntity@@PEAVPhysicsCollection@@EH@Z proc EXPORT
jmp function_pointers[_Building_base+174*8]
?loadParts@Building@@QEAAXPEAVGameData@@PEAVPhysicalEntity@@PEAVPhysicsCollection@@EH@Z endp

; Building::loadPartEntity(class PhysicsCollection *, class GameData *, class Ogre::SceneNode *, unsigned char, int, class GameData *);
?loadPartEntity@Building@@QEAAPEAVPhysicalEntity@@PEAVPhysicsCollection@@PEAVGameData@@PEAVSceneNode@Ogre@@EH1@Z proc EXPORT
jmp function_pointers[_Building_base+175*8]
?loadPartEntity@Building@@QEAAPEAVPhysicalEntity@@PEAVPhysicsCollection@@PEAVGameData@@PEAVSceneNode@Ogre@@EH1@Z endp

; Building::loadEntity(class GameData *, class Ogre::SceneNode *, unsigned char);
?loadEntity@Building@@QEAAPEAVMovableObject@Ogre@@PEAVGameData@@PEAVSceneNode@3@E@Z proc EXPORT
jmp function_pointers[_Building_base+176*8]
?loadEntity@Building@@QEAAPEAVMovableObject@Ogre@@PEAVGameData@@PEAVSceneNode@3@E@Z endp

; Building::loadEntityCallback(class Ogre::SharedPtr<Ogre::Resource>, void *);
?loadEntityCallback@Building@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_Building_base+177*8]
?loadEntityCallback@Building@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

; Building::loadInstances(class GameData *, class PhysicalEntity *, class Ogre::SceneNode *);
?loadInstances@Building@@QEAAXPEAVGameData@@PEAVPhysicalEntity@@PEAVSceneNode@Ogre@@@Z proc EXPORT
jmp function_pointers[_Building_base+178*8]
?loadInstances@Building@@QEAAXPEAVGameData@@PEAVPhysicalEntity@@PEAVSceneNode@Ogre@@@Z endp

; Building::getSeed();
?getSeed@Building@@QEBAIXZ proc EXPORT
jmp function_pointers[_Building_base+179*8]
?getSeed@Building@@QEBAIXZ endp

; Building::findPhysicalEntity(class Ogre::MovableObject *);
?findPhysicalEntity@Building@@QEBAPEAVPhysicalEntity@@PEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_Building_base+180*8]
?findPhysicalEntity@Building@@QEBAPEAVPhysicalEntity@@PEAVMovableObject@Ogre@@@Z endp

; Building::findPhysicalEntityInCollection(class Ogre::MovableObject *, class PhysicsCollection *);
?findPhysicalEntityInCollection@Building@@SAPEAVPhysicalEntity@@PEAVMovableObject@Ogre@@PEAVPhysicsCollection@@@Z proc EXPORT
jmp function_pointers[_Building_base+181*8]
?findPhysicalEntityInCollection@Building@@SAPEAVPhysicalEntity@@PEAVMovableObject@Ogre@@PEAVPhysicsCollection@@@Z endp

; Building::buildingContainsEntity(class Ogre::MovableObject *, class PhysicsCollection *);
?buildingContainsEntity@Building@@SA_NPEAVMovableObject@Ogre@@PEAVPhysicsCollection@@@Z proc EXPORT
jmp function_pointers[_Building_base+182*8]
?buildingContainsEntity@Building@@SA_NPEAVMovableObject@Ogre@@PEAVPhysicsCollection@@@Z endp

; Building::getEntityMaterialName(class Ogre::MovableObject *);
?getEntityMaterialName@Building@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_Building_base+183*8]
?getEntityMaterialName@Building@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVMovableObject@Ogre@@@Z endp

?_NV_onBuildingLoaded@Building@@QEAAXXZ proc EXPORT
?_NV_onBuildingLoaded@Building@@QEAAXXZ endp

; Building::onBuildingLoaded();
?onBuildingLoaded@Building@@UEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+184*8]
?onBuildingLoaded@Building@@UEAAXXZ endp

?_NV_setPartVisible@Building@@QEAAXPEAVPhysicalEntity@@_N@Z proc EXPORT
?_NV_setPartVisible@Building@@QEAAXPEAVPhysicalEntity@@_N@Z endp

; Building::setPartVisible(class PhysicalEntity *, bool);
?setPartVisible@Building@@UEAAXPEAVPhysicalEntity@@_N@Z proc EXPORT
jmp function_pointers[_Building_base+185*8]
?setPartVisible@Building@@UEAAXPEAVPhysicalEntity@@_N@Z endp

; Building::updateBadNodes();
?updateBadNodes@Building@@QEAAXXZ proc EXPORT
jmp function_pointers[_Building_base+186*8]
?updateBadNodes@Building@@QEAAXXZ endp
