
?_CONSTRUCTOR@ConstructionState@Building@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@ConstructionState@Building@@QEAAPEAV12@AEBV12@@Z endp

; Building::ConstructionState::ConstructionState(const class Building::ConstructionState &);
??0ConstructionState@Building@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+0*8]
??0ConstructionState@Building@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@ConstructionState@Building@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ConstructionState@Building@@QEAAPEAV12@XZ endp

; Building::ConstructionState::ConstructionState();
??0ConstructionState@Building@@QEAA@XZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+1*8]
??0ConstructionState@Building@@QEAA@XZ endp

?_DESTRUCTOR@ConstructionState@Building@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ConstructionState@Building@@QEAAXXZ endp

; Building::ConstructionState::~ConstructionState();
??1ConstructionState@Building@@QEAA@XZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+2*8]
??1ConstructionState@Building@@QEAA@XZ endp

; Building::ConstructionState::addMaterials(class GameData *);
?addMaterials@ConstructionState@Building@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+3*8]
?addMaterials@ConstructionState@Building@@QEAAXPEAVGameData@@@Z endp

; Building::ConstructionState::materialsEmpty();
?materialsEmpty@ConstructionState@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+4*8]
?materialsEmpty@ConstructionState@Building@@QEBA_NXZ endp

; Building::ConstructionState::isOverThreshold();
?isOverThreshold@ConstructionState@Building@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+5*8]
?isOverThreshold@ConstructionState@Building@@QEBA_NXZ endp

; Building::ConstructionState::getHealthBarProgress();
?getHealthBarProgress@ConstructionState@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+6*8]
?getHealthBarProgress@ConstructionState@Building@@QEBAMXZ endp

; Building::ConstructionState::getConstructionMaterialProgress();
?getConstructionMaterialProgress@ConstructionState@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+7*8]
?getConstructionMaterialProgress@ConstructionState@Building@@QEBAMXZ endp

; Building::ConstructionState::getHealthBarActual();
?getHealthBarActual@ConstructionState@Building@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+8*8]
?getHealthBarActual@ConstructionState@Building@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Building::ConstructionState::getMaterial(const class GameData *);
?getMaterial@ConstructionState@Building@@QEAAPEAVBuildMaterial@12@PEBVGameData@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+9*8]
?getMaterial@ConstructionState@Building@@QEAAPEAVBuildMaterial@12@PEBVGameData@@@Z endp

; Building::ConstructionState::setup(class GameData *);
?setup@ConstructionState@Building@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+10*8]
?setup@ConstructionState@Building@@QEAAXPEAVGameData@@@Z endp

; Building::ConstructionState::getTotalMats();
?getTotalMats@ConstructionState@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+11*8]
?getTotalMats@ConstructionState@Building@@QEBAMXZ endp

; Building::ConstructionState::getTotalMatsPresent();
?getTotalMatsPresent@ConstructionState@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+12*8]
?getTotalMatsPresent@ConstructionState@Building@@QEBAMXZ endp

; Building::ConstructionState::getNeededMats(class lektor<Building::ConstructionState::BuildMaterial *> &);
?getNeededMats@ConstructionState@Building@@QEAAXAEAV?$lektor@PEAVBuildMaterial@ConstructionState@Building@@@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+13*8]
?getNeededMats@ConstructionState@Building@@QEAAXAEAV?$lektor@PEAVBuildMaterial@ConstructionState@Building@@@@@Z endp

; Building::ConstructionState::needsMat(class GameData *);
?needsMat@ConstructionState@Building@@QEAAHPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+14*8]
?needsMat@ConstructionState@Building@@QEAAHPEAVGameData@@@Z endp

; Building::ConstructionState::needMats();
?needMats@ConstructionState@Building@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+15*8]
?needMats@ConstructionState@Building@@QEAA_NXZ endp

; Building::ConstructionState::getBuildingSpeedMultiplier(class GameData *);
?getBuildingSpeedMultiplier@ConstructionState@Building@@SAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+16*8]
?getBuildingSpeedMultiplier@ConstructionState@Building@@SAMPEAVGameData@@@Z endp

; Building::ConstructionState::getBuildingTimeInHours(class GameData *);
?getBuildingTimeInHours@ConstructionState@Building@@SAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Building_ConstructionState_base+17*8]
?getBuildingTimeInHours@ConstructionState@Building@@SAMPEAVGameData@@@Z endp
