
; BuildModeWindow::BuildingCategory::operator<(const class BuildModeWindow::BuildingCategory &);
??MBuildingCategory@BuildModeWindow@@QEBA_NAEBV01@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingCategory_base+0*8]
??MBuildingCategory@BuildModeWindow@@QEBA_NAEBV01@@Z endp

?_CONSTRUCTOR@BuildingCategory@BuildModeWindow@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@BuildingCategory@BuildModeWindow@@QEAAPEAV12@AEBV12@@Z endp

; BuildModeWindow::BuildingCategory::BuildingCategory(const class BuildModeWindow::BuildingCategory &);
??0BuildingCategory@BuildModeWindow@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingCategory_base+1*8]
??0BuildingCategory@BuildModeWindow@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@BuildingCategory@BuildModeWindow@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@BuildingCategory@BuildModeWindow@@QEAAPEAV12@XZ endp

; BuildModeWindow::BuildingCategory::BuildingCategory();
??0BuildingCategory@BuildModeWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingCategory_base+2*8]
??0BuildingCategory@BuildModeWindow@@QEAA@XZ endp

?_DESTRUCTOR@BuildingCategory@BuildModeWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildingCategory@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::BuildingCategory::~BuildingCategory();
??1BuildingCategory@BuildModeWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingCategory_base+3*8]
??1BuildingCategory@BuildModeWindow@@QEAA@XZ endp

; BuildModeWindow::BuildingCategory::operator=(const class BuildModeWindow::BuildingCategory &);
??4BuildingCategory@BuildModeWindow@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingCategory_base+4*8]
??4BuildingCategory@BuildModeWindow@@QEAAAEAV01@AEBV01@@Z endp
