
?_CONSTRUCTOR@BuildingContainerInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@BuildingContainerInventoryLayout@@QEAAPEAV1@XZ endp

; BuildingContainerInventoryLayout::BuildingContainerInventoryLayout();
??0BuildingContainerInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_BuildingContainerInventoryLayout_base+0*8]
??0BuildingContainerInventoryLayout@@QEAA@XZ endp

; symbol is too long
; ?setupSections@BuildingContainerInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; BuildingContainerInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
BuildingContainerInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_BuildingContainerInventoryLayout_base+1*8]
BuildingContainerInventoryLayout_setupSections_PLACEHOLDER endp

; BuildingContainerInventoryLayout::setCapacity(int, bool);
?setCapacity@BuildingContainerInventoryLayout@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_BuildingContainerInventoryLayout_base+2*8]
?setCapacity@BuildingContainerInventoryLayout@@QEAAXH_N@Z endp

?_DESTRUCTOR@BuildingContainerInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildingContainerInventoryLayout@@QEAAXXZ endp

; BuildingContainerInventoryLayout::~BuildingContainerInventoryLayout();
??1BuildingContainerInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_BuildingContainerInventoryLayout_base+3*8]
??1BuildingContainerInventoryLayout@@UEAA@XZ endp
