
?_CONSTRUCTOR@BuildInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH_N@Z proc EXPORT
?_CONSTRUCTOR@BuildInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH_N@Z endp

; BuildInventoryLayout::BuildInventoryLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, bool);
??0BuildInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH_N@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+0*8]
??0BuildInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH_N@Z endp

; symbol is too long
; ?setupSections@BuildInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; BuildInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
BuildInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+1*8]
BuildInventoryLayout_setupSections_PLACEHOLDER endp

; BuildInventoryLayout::setInput(int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setInput@BuildInventoryLayout@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+2*8]
?setInput@BuildInventoryLayout@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; BuildInventoryLayout::setOutput(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setOutput@BuildInventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+3*8]
?setOutput@BuildInventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; BuildInventoryLayout::setInputProgress(int, float);
?setInputProgress@BuildInventoryLayout@@QEAAXHM@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+4*8]
?setInputProgress@BuildInventoryLayout@@QEAAXHM@Z endp

; BuildInventoryLayout::setInputEnabled(int, bool);
?setInputEnabled@BuildInventoryLayout@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+5*8]
?setInputEnabled@BuildInventoryLayout@@QEAAXH_N@Z endp

; BuildInventoryLayout::setOutputProgress(float);
?setOutputProgress@BuildInventoryLayout@@QEAAXM@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+6*8]
?setOutputProgress@BuildInventoryLayout@@QEAAXM@Z endp

; BuildInventoryLayout::setInputItem(int, class Item *, bool);
?setInputItem@BuildInventoryLayout@@QEAAXHPEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+7*8]
?setInputItem@BuildInventoryLayout@@QEAAXHPEAVItem@@_N@Z endp

; BuildInventoryLayout::setOutputItem(class Item *, bool);
?setOutputItem@BuildInventoryLayout@@QEAAXPEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+8*8]
?setOutputItem@BuildInventoryLayout@@QEAAXPEAVItem@@_N@Z endp

?_DESTRUCTOR@BuildInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildInventoryLayout@@QEAAXXZ endp

; BuildInventoryLayout::~BuildInventoryLayout();
??1BuildInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_BuildInventoryLayout_base+9*8]
??1BuildInventoryLayout@@UEAA@XZ endp
