
; BuildModeWindow::BuildingGroup::operator<(const class BuildModeWindow::BuildingGroup &);
??MBuildingGroup@BuildModeWindow@@QEBA_NAEBV01@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingGroup_base+0*8]
??MBuildingGroup@BuildModeWindow@@QEBA_NAEBV01@@Z endp

?_CONSTRUCTOR@BuildingGroup@BuildModeWindow@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@BuildingGroup@BuildModeWindow@@QEAAPEAV12@AEBV12@@Z endp

; BuildModeWindow::BuildingGroup::BuildingGroup(const class BuildModeWindow::BuildingGroup &);
??0BuildingGroup@BuildModeWindow@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingGroup_base+1*8]
??0BuildingGroup@BuildModeWindow@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@BuildingGroup@BuildModeWindow@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@BuildingGroup@BuildModeWindow@@QEAAPEAV12@XZ endp

; BuildModeWindow::BuildingGroup::BuildingGroup();
??0BuildingGroup@BuildModeWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingGroup_base+2*8]
??0BuildingGroup@BuildModeWindow@@QEAA@XZ endp

?_DESTRUCTOR@BuildingGroup@BuildModeWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildingGroup@BuildModeWindow@@QEAAXXZ endp

; BuildModeWindow::BuildingGroup::~BuildingGroup();
??1BuildingGroup@BuildModeWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingGroup_base+3*8]
??1BuildingGroup@BuildModeWindow@@QEAA@XZ endp

; BuildModeWindow::BuildingGroup::operator=(const class BuildModeWindow::BuildingGroup &);
??4BuildingGroup@BuildModeWindow@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_BuildModeWindow_BuildingGroup_base+4*8]
??4BuildingGroup@BuildModeWindow@@QEAAAEAV01@AEBV01@@Z endp
