
; Building::ConstructionState::BuildMaterial::getMaterialsBarProgress();
?getMaterialsBarProgress@BuildMaterial@ConstructionState@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_BuildMaterial_base+0*8]
?getMaterialsBarProgress@BuildMaterial@ConstructionState@Building@@QEBAMXZ endp

; Building::ConstructionState::BuildMaterial::getNumRemaining();
?getNumRemaining@BuildMaterial@ConstructionState@Building@@QEBAMXZ proc EXPORT
jmp function_pointers[_Building_ConstructionState_BuildMaterial_base+1*8]
?getNumRemaining@BuildMaterial@ConstructionState@Building@@QEBAMXZ endp
