
?_CONSTRUCTOR@CameraClass@@QEAAPEAV1@PEAVCamera@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@CameraClass@@QEAAPEAV1@PEAVCamera@Ogre@@@Z endp

; CameraClass::CameraClass(class Ogre::Camera *);
??0CameraClass@@QEAA@PEAVCamera@Ogre@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+0*8]
??0CameraClass@@QEAA@PEAVCamera@Ogre@@@Z endp

; CameraClass::reset();
?reset@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+1*8]
?reset@CameraClass@@QEAAXXZ endp

; CameraClass::update(bool);
?update@CameraClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_CameraClass_base+2*8]
?update@CameraClass@@QEAAX_N@Z endp

; CameraClass::focusCameraOnObject(class RootObject *, const class Ogre::Vector3 &, bool);
?focusCameraOnObject@CameraClass@@QEAAXPEAVRootObject@@AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_CameraClass_base+3*8]
?focusCameraOnObject@CameraClass@@QEAAXPEAVRootObject@@AEBVVector3@Ogre@@_N@Z endp

; CameraClass::updateOptionSettings();
?updateOptionSettings@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+4*8]
?updateOptionSettings@CameraClass@@QEAAXXZ endp

; CameraClass::save(class GameData *);
?save@CameraClass@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+5*8]
?save@CameraClass@@QEAAXPEAVGameData@@@Z endp

; CameraClass::load(class GameData *);
?load@CameraClass@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+6*8]
?load@CameraClass@@QEAAXPEAVGameData@@@Z endp

; CameraClass::isVisible(const class Ogre::Vector3 &, float);
?isVisible@CameraClass@@QEBA_NAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_CameraClass_base+7*8]
?isVisible@CameraClass@@QEBA_NAEBVVector3@Ogre@@M@Z endp

; CameraClass::isVisible(const class Ogre::Vector3 &);
?isVisible@CameraClass@@QEBA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+8*8]
?isVisible@CameraClass@@QEBA_NAEBVVector3@Ogre@@@Z endp

; CameraClass::intersectScreenEdge(const class Ogre::Vector3 &, const class Ogre::Vector3 &, float, float &);
?intersectScreenEdge@CameraClass@@QEBAHAEBVVector3@Ogre@@0MAEAM@Z proc EXPORT
jmp function_pointers[_CameraClass_base+9*8]
?intersectScreenEdge@CameraClass@@QEBAHAEBVVector3@Ogre@@0MAEAM@Z endp

; CameraClass::teleport(const class Ogre::Vector3 &);
?teleport@CameraClass@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+10*8]
?teleport@CameraClass@@QEAAXAEBVVector3@Ogre@@@Z endp

; CameraClass::followObject(const class hand &);
?followObject@CameraClass@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+11*8]
?followObject@CameraClass@@QEAAXAEBVhand@@@Z endp

; CameraClass::stopFollowing();
?stopFollowing@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+12*8]
?stopFollowing@CameraClass@@QEAAXXZ endp

; CameraClass::getFollowObject();
?getFollowObject@CameraClass@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_CameraClass_base+13*8]
?getFollowObject@CameraClass@@QEBAAEBVhand@@XZ endp

; CameraClass::manuallySetOrientationAndZoom(class Ogre::Quaternion, float);
?manuallySetOrientationAndZoom@CameraClass@@QEAAXVQuaternion@Ogre@@M@Z proc EXPORT
jmp function_pointers[_CameraClass_base+14*8]
?manuallySetOrientationAndZoom@CameraClass@@QEAAXVQuaternion@Ogre@@M@Z endp

; CameraClass::getFacingDirection();
?getFacingDirection@CameraClass@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_CameraClass_base+15*8]
?getFacingDirection@CameraClass@@QEBA?AVVector3@Ogre@@XZ endp

; CameraClass::getCenter();
?getCenter@CameraClass@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_CameraClass_base+16*8]
?getCenter@CameraClass@@QEBA?BVVector3@Ogre@@XZ endp

; CameraClass::getCameraPos();
?getCameraPos@CameraClass@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_CameraClass_base+17*8]
?getCameraPos@CameraClass@@QEBA?BVVector3@Ogre@@XZ endp

; CameraClass::getCenterNode();
?getCenterNode@CameraClass@@QEBAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_CameraClass_base+18*8]
?getCenterNode@CameraClass@@QEBAPEAVSceneNode@Ogre@@XZ endp

; CameraClass::getCameraNode();
?getCameraNode@CameraClass@@QEBAPEAVSceneNode@Ogre@@XZ proc EXPORT
jmp function_pointers[_CameraClass_base+19*8]
?getCameraNode@CameraClass@@QEBAPEAVSceneNode@Ogre@@XZ endp

; CameraClass::isInitialised();
?isInitialised@CameraClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CameraClass_base+20*8]
?isInitialised@CameraClass@@QEBA_NXZ endp

; CameraClass::restrictPosition(class lektor<Character *> &);
?restrictPosition@CameraClass@@QEAAXAEAV?$lektor@PEAVCharacter@@@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+21*8]
?restrictPosition@CameraClass@@QEAAXAEAV?$lektor@PEAVCharacter@@@@@Z endp

; CameraClass::isFreeCameraMode();
?isFreeCameraMode@CameraClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CameraClass_base+22*8]
?isFreeCameraMode@CameraClass@@QEBA_NXZ endp

; CameraClass::setFreeCameraMode(bool);
?setFreeCameraMode@CameraClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_CameraClass_base+23*8]
?setFreeCameraMode@CameraClass@@QEAAX_N@Z endp

; CameraClass::updateFreeCamera();
?updateFreeCamera@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+24*8]
?updateFreeCamera@CameraClass@@QEAAXXZ endp

; CameraClass::move(const class Ogre::Vector3 &);
?move@CameraClass@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CameraClass_base+25*8]
?move@CameraClass@@QEAAXAEBVVector3@Ogre@@@Z endp

; CameraClass::zoom();
?zoom@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+26*8]
?zoom@CameraClass@@QEAAXXZ endp

; CameraClass::toGround(bool);
?toGround@CameraClass@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_CameraClass_base+27*8]
?toGround@CameraClass@@QEAAX_N@Z endp

; CameraClass::setZoomDist(float);
?setZoomDist@CameraClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CameraClass_base+28*8]
?setZoomDist@CameraClass@@QEAAXM@Z endp

; CameraClass::rotate(float, float);
?rotate@CameraClass@@QEAAXMM@Z proc EXPORT
jmp function_pointers[_CameraClass_base+29*8]
?rotate@CameraClass@@QEAAXMM@Z endp

; CameraClass::rotationUpdate();
?rotationUpdate@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+30*8]
?rotationUpdate@CameraClass@@QEAAXXZ endp

; CameraClass::updateAudio();
?updateAudio@CameraClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CameraClass_base+31*8]
?updateAudio@CameraClass@@QEAAXXZ endp
