
?_CONSTRUCTOR@CharacterEditWindow@@QEAAPEAV1@AEBV?$lektor@PEAVCharacter@@@@W4CharacterEditMode@@PEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_CONSTRUCTOR@CharacterEditWindow@@QEAAPEAV1@AEBV?$lektor@PEAVCharacter@@@@W4CharacterEditMode@@PEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; CharacterEditWindow::CharacterEditWindow(const class lektor<Character *> &, enum CharacterEditMode, const class std::vector<GameDataReference,Ogre::STLAllocator<GameDataReference,Ogre::CategorisedAllocPolicy<0> > > *);
??0CharacterEditWindow@@QEAA@AEBV?$lektor@PEAVCharacter@@@@W4CharacterEditMode@@PEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+0*8]
??0CharacterEditWindow@@QEAA@AEBV?$lektor@PEAVCharacter@@@@W4CharacterEditMode@@PEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_DESTRUCTOR@CharacterEditWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::~CharacterEditWindow();
??1CharacterEditWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+1*8]
??1CharacterEditWindow@@UEAA@XZ endp

; CharacterEditWindow::update();
?update@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+2*8]
?update@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::loadData();
?loadData@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+3*8]
?loadData@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::initCharacters();
?initCharacters@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+4*8]
?initCharacters@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::nameChanged(class MyGUI::EditBox *);
?nameChanged@CharacterEditWindow@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+5*8]
?nameChanged@CharacterEditWindow@@QEAAXPEAVEditBox@MyGUI@@@Z endp

; CharacterEditWindow::prevRace(class MyGUI::Widget *);
?prevRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+6*8]
?prevRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::nextRace(class MyGUI::Widget *);
?nextRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+7*8]
?nextRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::prevSubRace(class MyGUI::Widget *);
?prevSubRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+8*8]
?prevSubRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::nextSubRace(class MyGUI::Widget *);
?nextSubRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+9*8]
?nextSubRace@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::updateRace();
?updateRace@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+10*8]
?updateRace@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::changeGender(class MyGUI::Widget *);
?changeGender@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+11*8]
?changeGender@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::changeAppearanceData(class GameData *, const class AppearanceManager::Gender &);
?changeAppearanceData@CharacterEditWindow@@QEAAXPEAVGameData@@AEBVGender@AppearanceManager@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+12*8]
?changeAppearanceData@CharacterEditWindow@@QEAAXPEAVGameData@@AEBVGender@AppearanceManager@@@Z endp

; CharacterEditWindow::updateCharacterPoses();
?updateCharacterPoses@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+13*8]
?updateCharacterPoses@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::clearCharacterPoses();
?clearCharacterPoses@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+14*8]
?clearCharacterPoses@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::prevCharacter(class MyGUI::Widget *);
?prevCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+15*8]
?prevCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::nextCharacter(class MyGUI::Widget *);
?nextCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+16*8]
?nextCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::updateCharacter();
?updateCharacter@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+17*8]
?updateCharacter@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::showCharacter(class Character *, bool);
?showCharacter@CharacterEditWindow@@QEAAXPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+18*8]
?showCharacter@CharacterEditWindow@@QEAAXPEAVCharacter@@_N@Z endp

; CharacterEditWindow::changeCategory(class MyGUI::Widget *);
?changeCategory@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+19*8]
?changeCategory@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::updateCurrentCategory();
?updateCurrentCategory@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+20*8]
?updateCurrentCategory@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::resetAppearance(class MyGUI::Widget *);
?resetAppearance@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+21*8]
?resetAppearance@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::randomiseAll(class MyGUI::Widget *);
?randomiseAll@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+22*8]
?randomiseAll@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::randomisePart(class MyGUI::Widget *);
?randomisePart@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+23*8]
?randomisePart@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::importCharacter(class MyGUI::Widget *);
?importCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+24*8]
?importCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::exportCharacter(class MyGUI::Widget *);
?exportCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+25*8]
?exportCharacter@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::loadImportedCharacter(class OpenSaveFileDialog *, bool, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?loadImportedCharacter@CharacterEditWindow@@QEAAXPEAVOpenSaveFileDialog@@_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+26*8]
?loadImportedCharacter@CharacterEditWindow@@QEAAXPEAVOpenSaveFileDialog@@_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharacterEditWindow::toggleClothes(class MyGUI::Widget *);
?toggleClothes@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+27*8]
?toggleClothes@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::setClothesVisible(class Character *, bool);
?setClothesVisible@CharacterEditWindow@@QEAAXPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+28*8]
?setClothesVisible@CharacterEditWindow@@QEAAXPEAVCharacter@@_N@Z endp

; CharacterEditWindow::updateAppearanceSlider(class MyGUI::Slider *, int);
?updateAppearanceSlider@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+29*8]
?updateAppearanceSlider@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z endp

; CharacterEditWindow::updateAppearanceSliderPose(class MyGUI::Slider *, int);
?updateAppearanceSliderPose@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+30*8]
?updateAppearanceSliderPose@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z endp

; CharacterEditWindow::updateAppearanceSliderVector(class MyGUI::Slider *, int);
?updateAppearanceSliderVector@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+31*8]
?updateAppearanceSliderVector@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z endp

; CharacterEditWindow::updateAppearanceList(class MyGUI::ListScrollBar *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?updateAppearanceList@CharacterEditWindow@@QEAAXPEAVListScrollBar@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+32*8]
?updateAppearanceList@CharacterEditWindow@@QEAAXPEAVListScrollBar@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; CharacterEditWindow::updateAppearanceMultiSlider(class MyGUI::MultiSlider *, class MyGUI::Slider *, int, int);
?updateAppearanceMultiSlider@CharacterEditWindow@@QEAAXPEAVMultiSlider@MyGUI@@PEAVSlider@3@HH@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+33*8]
?updateAppearanceMultiSlider@CharacterEditWindow@@QEAAXPEAVMultiSlider@MyGUI@@PEAVSlider@3@HH@Z endp

; CharacterEditWindow::updateAnimationIdle(class MyGUI::Slider *, int);
?updateAnimationIdle@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+34*8]
?updateAnimationIdle@CharacterEditWindow@@QEAAXPEAVSlider@MyGUI@@H@Z endp

; CharacterEditWindow::confirmButton(class MyGUI::Widget *);
?confirmButton@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+35*8]
?confirmButton@CharacterEditWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CharacterEditWindow::confirmMessageCallback(int);
?confirmMessageCallback@CharacterEditWindow@@QEAAXH@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+36*8]
?confirmMessageCallback@CharacterEditWindow@@QEAAXH@Z endp

; CharacterEditWindow::setupUI();
?setupUI@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+37*8]
?setupUI@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::setUIEnabled(bool);
?setUIEnabled@CharacterEditWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+38*8]
?setUIEnabled@CharacterEditWindow@@QEAAX_N@Z endp

; CharacterEditWindow::refreshUI();
?refreshUI@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+39*8]
?refreshUI@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::updateLiveObject();
?updateLiveObject@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+40*8]
?updateLiveObject@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::refreshCharacterPoses();
?refreshCharacterPoses@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+41*8]
?refreshCharacterPoses@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::exportMeshes();
?exportMeshes@CharacterEditWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+42*8]
?exportMeshes@CharacterEditWindow@@QEAAXXZ endp

; CharacterEditWindow::getCurrentHeadName();
?getCurrentHeadName@CharacterEditWindow@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+43*8]
?getCurrentHeadName@CharacterEditWindow@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; CharacterEditWindow::getCurrentAttachmentName(enum AttachSlot);
?getCurrentAttachmentName@CharacterEditWindow@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4AttachSlot@@@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+44*8]
?getCurrentAttachmentName@CharacterEditWindow@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4AttachSlot@@@Z endp

; CharacterEditWindow::setCurrentHeadName(unsigned __int64);
?setCurrentHeadName@CharacterEditWindow@@QEBAX_K@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+45*8]
?setCurrentHeadName@CharacterEditWindow@@QEBAX_K@Z endp

; CharacterEditWindow::setCurrentAttachmentName(enum AttachSlot, unsigned __int64);
?setCurrentAttachmentName@CharacterEditWindow@@QEBAXW4AttachSlot@@_K@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+46*8]
?setCurrentAttachmentName@CharacterEditWindow@@QEBAXW4AttachSlot@@_K@Z endp

; CharacterEditWindow::getCharacterEntity(unsigned __int64);
?getCharacterEntity@CharacterEditWindow@@QEAAPEAVEntity@Ogre@@_K@Z proc EXPORT
jmp function_pointers[_CharacterEditWindow_base+47*8]
?getCharacterEntity@CharacterEditWindow@@QEAAPEAVEntity@Ogre@@_K@Z endp
