
; CharStats::getWeatherProtection(enum WeatherAffecting);
?getWeatherProtection@CharStats@@QEBAMW4WeatherAffecting@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+0*8]
?getWeatherProtection@CharStats@@QEBAMW4WeatherAffecting@@@Z endp

?_CONSTRUCTOR@CharStats@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@CharStats@@QEAAPEAV1@XZ endp

; CharStats::CharStats();
??0CharStats@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharStats_base+1*8]
??0CharStats@@QEAA@XZ endp

; CharStats::unarmedEncumbrancePenalty();
?unarmedEncumbrancePenalty@CharStats@@QEBAHXZ proc EXPORT
jmp function_pointers[_CharStats_base+2*8]
?unarmedEncumbrancePenalty@CharStats@@QEBAHXZ endp

; CharStats::skillBonusUnarmed_forGUI(bool);
?skillBonusUnarmed_forGUI@CharStats@@QEBAH_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+3*8]
?skillBonusUnarmed_forGUI@CharStats@@QEBAH_N@Z endp

; CharStats::skillBonusAttack_melee(bool);
?skillBonusAttack_melee@CharStats@@QEBAH_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+4*8]
?skillBonusAttack_melee@CharStats@@QEBAH_N@Z endp

; CharStats::skillBonusAttack_unarmed(bool);
?skillBonusAttack_unarmed@CharStats@@QEBAH_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+5*8]
?skillBonusAttack_unarmed@CharStats@@QEBAH_N@Z endp

; CharStats::skillBonusDefence(bool);
?skillBonusDefence@CharStats@@QEBAH_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+6*8]
?skillBonusDefence@CharStats@@QEBAH_N@Z endp

; CharStats::serialise(class GameData *);
?serialise@CharStats@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+7*8]
?serialise@CharStats@@QEAAXPEAVGameData@@@Z endp

; CharStats::updateStats(class GameData *);
?updateStats@CharStats@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+8*8]
?updateStats@CharStats@@QEAAXPEAVGameData@@@Z endp

?_NV_init@CharStats@@QEAAXPEAVGameData@@PEAVMedicalSystem@@PEAVCharacter@@@Z proc EXPORT
?_NV_init@CharStats@@QEAAXPEAVGameData@@PEAVMedicalSystem@@PEAVCharacter@@@Z endp

; CharStats::init(class GameData *, class MedicalSystem *, class Character *);
?init@CharStats@@UEAAXPEAVGameData@@PEAVMedicalSystem@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+9*8]
?init@CharStats@@UEAAXPEAVGameData@@PEAVMedicalSystem@@PEAVCharacter@@@Z endp

; CharStats::_randomiseStats(float);
?_randomiseStats@CharStats@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CharStats_base+10*8]
?_randomiseStats@CharStats@@QEAAXM@Z endp

; CharStats::getGUIData(class DatapanelGUI *, int);
?getGUIData@CharStats@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_CharStats_base+11*8]
?getGUIData@CharStats@@QEAAXPEAVDatapanelGUI@@H@Z endp

; CharStats::printStealthStats(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?printStealthStats@CharStats@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+12*8]
?printStealthStats@CharStats@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharStats::getStealthTooltip(class lektor<StringPair> *);
?getStealthTooltip@CharStats@@QEAAXPEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+13*8]
?getStealthTooltip@CharStats@@QEAAXPEAV?$lektor@VStringPair@@@@@Z endp

; CharStats::printRunSpeedStatMax(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?printRunSpeedStatMax@CharStats@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+14*8]
?printRunSpeedStatMax@CharStats@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharStats::getAthleticsTooltip(class lektor<StringPair> *);
?getAthleticsTooltip@CharStats@@QEAAXPEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+15*8]
?getAthleticsTooltip@CharStats@@QEAAXPEAV?$lektor@VStringPair@@@@@Z endp

; CharStats::getGUIDataForMainInfo(class DatapanelGUI *, int, bool);
?getGUIDataForMainInfo@CharStats@@QEAAXPEAVDatapanelGUI@@H_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+16*8]
?getGUIDataForMainInfo@CharStats@@QEAAXPEAVDatapanelGUI@@H_N@Z endp

; CharStats::formatWholeStatStringWithBonuses(int, int);
?formatWholeStatStringWithBonuses@CharStats@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
jmp function_pointers[_CharStats_base+17*8]
?formatWholeStatStringWithBonuses@CharStats@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; CharStats::formatWholeStatStringWithBonuses(enum StatsEnumerated);
?formatWholeStatStringWithBonuses@CharStats@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+18*8]
?formatWholeStatStringWithBonuses@CharStats@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z endp

; CharStats::getGUIStatsDisplayMode();
?getGUIStatsDisplayMode@CharStats@@QEAA?AW4GUIStatsDisplayMode@1@XZ proc EXPORT
jmp function_pointers[_CharStats_base+19*8]
?getGUIStatsDisplayMode@CharStats@@QEAA?AW4GUIStatsDisplayMode@1@XZ endp

?_NV_periodicUpdate@CharStats@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@CharStats@@QEAAXXZ endp

; CharStats::periodicUpdate();
?periodicUpdate@CharStats@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+20*8]
?periodicUpdate@CharStats@@UEAAXXZ endp

; CharStats::calculateStumbleThresholdDamageAmount();
?calculateStumbleThresholdDamageAmount@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+21*8]
?calculateStumbleThresholdDamageAmount@CharStats@@QEAAMXZ endp

; CharStats::setEquipmentStatBonuses(float, float, int, int, float, int, float, float, int, float, float, float, float);
?setEquipmentStatBonuses@CharStats@@QEAAXMMHHMHMMHMMMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+22*8]
?setEquipmentStatBonuses@CharStats@@QEAAXMMHHMHMMHMMMM@Z endp

; CharStats::getOverallSkillLevel_0_100();
?getOverallSkillLevel_0_100@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+23*8]
?getOverallSkillLevel_0_100@CharStats@@QEBAMXZ endp

; CharStats::getStatRef(enum StatsEnumerated);
?getStatRef@CharStats@@QEAAAEAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+24*8]
?getStatRef@CharStats@@QEAAAEAMW4StatsEnumerated@@@Z endp

; CharStats::getStat(enum StatsEnumerated, bool);
?getStat@CharStats@@QEBAMW4StatsEnumerated@@_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+25*8]
?getStat@CharStats@@QEBAMW4StatsEnumerated@@_N@Z endp

; CharStats::getStatName(enum StatsEnumerated);
?getStatName@CharStats@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+26*8]
?getStatName@CharStats@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z endp

; CharStats::getStatMultiplier(enum StatsEnumerated);
?getStatMultiplier@CharStats@@QEBAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+27*8]
?getStatMultiplier@CharStats@@QEBAMW4StatsEnumerated@@@Z endp

; CharStats::getStatMultiplierForGUI(enum StatsEnumerated);
?getStatMultiplierForGUI@CharStats@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+28*8]
?getStatMultiplierForGUI@CharStats@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z endp

; CharStats::getStatPenaltiesForGUI(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum StatsEnumerated, class lektor<StringPair> &);
?getStatPenaltiesForGUI@CharStats@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@AEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+29*8]
?getStatPenaltiesForGUI@CharStats@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@AEAV?$lektor@VStringPair@@@@@Z endp

; CharStats::getStatPenaltiesTotalForGUI(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum StatsEnumerated);
?getStatPenaltiesTotalForGUI@CharStats@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+30*8]
?getStatPenaltiesTotalForGUI@CharStats@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4StatsEnumerated@@@Z endp

; CharStats::xpStat_timeBased(enum StatsEnumerated);
?xpStat_timeBased@CharStats@@QEAAXW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+31*8]
?xpStat_timeBased@CharStats@@QEAAXW4StatsEnumerated@@@Z endp

; CharStats::xpStat_eventBased(enum StatsEnumerated, float);
?xpStat_eventBased@CharStats@@QEAAXW4StatsEnumerated@@M@Z proc EXPORT
jmp function_pointers[_CharStats_base+32*8]
?xpStat_eventBased@CharStats@@QEAAXW4StatsEnumerated@@M@Z endp

; CharStats::xpDodgeEvent(float, bool);
?xpDodgeEvent@CharStats@@QEAAXM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+33*8]
?xpDodgeEvent@CharStats@@QEAAXM_N@Z endp

; CharStats::strengthActual();
?strengthActual@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+34*8]
?strengthActual@CharStats@@QEBAMXZ endp

?_NV_strengthBase@CharStats@@QEBAMXZ proc EXPORT
?_NV_strengthBase@CharStats@@QEBAMXZ endp

; CharStats::strengthBase();
?strengthBase@CharStats@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+35*8]
?strengthBase@CharStats@@UEBAMXZ endp

; CharStats::dexterityBase();
?dexterityBase@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+36*8]
?dexterityBase@CharStats@@QEBAMXZ endp

; CharStats::dexterityActual();
?dexterityActual@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+37*8]
?dexterityActual@CharStats@@QEBAMXZ endp

; CharStats::toughness();
?toughness@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+38*8]
?toughness@CharStats@@QEBAMXZ endp

; CharStats::getToughnessMult();
?getToughnessMult@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+39*8]
?getToughnessMult@CharStats@@QEAAMXZ endp

; CharStats::getRangedFriendlyFireAvoidanceChance();
?getRangedFriendlyFireAvoidanceChance@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+40*8]
?getRangedFriendlyFireAvoidanceChance@CharStats@@QEAAMXZ endp

; CharStats::getRangedAccuracyMult(enum StatsEnumerated);
?getRangedAccuracyMult@CharStats@@QEAAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+41*8]
?getRangedAccuracyMult@CharStats@@QEAAMW4StatsEnumerated@@@Z endp

; CharStats::getReloadSkill(enum StatsEnumerated);
?getReloadSkill@CharStats@@QEAAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+42*8]
?getReloadSkill@CharStats@@QEAAMW4StatsEnumerated@@@Z endp

; CharStats::animalRecruitReduceStats();
?animalRecruitReduceStats@CharStats@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+43*8]
?animalRecruitReduceStats@CharStats@@QEAAXXZ endp

; CharStats::getMeleeAttackRef();
?getMeleeAttackRef@CharStats@@QEAAAEAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+44*8]
?getMeleeAttackRef@CharStats@@QEAAAEAMXZ endp

; CharStats::_chooseAttacks(class FitnessSelector<CombatTechniqueData *> &, float, float, class CombatTechniqueData *, bool, bool, enum WeaponCategory, float);
?_chooseAttacks@CharStats@@QEAAXAEAV?$FitnessSelector@PEAVCombatTechniqueData@@@@MMPEAVCombatTechniqueData@@_N2W4WeaponCategory@@M@Z proc EXPORT
jmp function_pointers[_CharStats_base+45*8]
?_chooseAttacks@CharStats@@QEAAXAEAV?$FitnessSelector@PEAVCombatTechniqueData@@@@MMPEAVCombatTechniqueData@@_N2W4WeaponCategory@@M@Z endp

; CharStats::getMeleeDefence(bool);
?getMeleeDefence@CharStats@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+46*8]
?getMeleeDefence@CharStats@@QEBAM_N@Z endp

; CharStats::getDodge(bool);
?getDodge@CharStats@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+47*8]
?getDodge@CharStats@@QEBAM_N@Z endp

; CharStats::getDodgePenalty_encumbrance();
?getDodgePenalty_encumbrance@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+48*8]
?getDodgePenalty_encumbrance@CharStats@@QEBAMXZ endp

; CharStats::getDodgePenalty_injuries();
?getDodgePenalty_injuries@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+49*8]
?getDodgePenalty_injuries@CharStats@@QEBAMXZ endp

; CharStats::getDodgePenalty_gear();
?getDodgePenalty_gear@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+50*8]
?getDodgePenalty_gear@CharStats@@QEBAMXZ endp

; CharStats::getMeleeDefence_melee(bool);
?getMeleeDefence_melee@CharStats@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+51*8]
?getMeleeDefence_melee@CharStats@@QEBAM_N@Z endp

; CharStats::getMeleeAttack();
?getMeleeAttack@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+52*8]
?getMeleeAttack@CharStats@@QEBAMXZ endp

; CharStats::getMeleeAttack_unarmed(bool);
?getMeleeAttack_unarmed@CharStats@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+53*8]
?getMeleeAttack_unarmed@CharStats@@QEBAM_N@Z endp

; CharStats::getMeleeAttack_melee();
?getMeleeAttack_melee@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+54*8]
?getMeleeAttack_melee@CharStats@@QEBAMXZ endp

; CharStats::_getMeleeAttackBase();
?_getMeleeAttackBase@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+55*8]
?_getMeleeAttackBase@CharStats@@QEBAMXZ endp

; CharStats::getMaxHealAmount(class Item *, class Building *, bool);
?getMaxHealAmount@CharStats@@QEAAMPEAVItem@@PEAVBuilding@@_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+56*8]
?getMaxHealAmount@CharStats@@QEAAMPEAVItem@@PEAVBuilding@@_N@Z endp

; CharStats::isDefensiveMode();
?isDefensiveMode@CharStats@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharStats_base+57*8]
?isDefensiveMode@CharStats@@QEBA_NXZ endp

; CharStats::holdPositionMode();
?holdPositionMode@CharStats@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharStats_base+58*8]
?holdPositionMode@CharStats@@QEBA_NXZ endp

; CharStats::setHoldLocation(const class Ogre::Vector3 &);
?setHoldLocation@CharStats@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+59*8]
?setHoldLocation@CharStats@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharStats::clearHoldLocation();
?clearHoldLocation@CharStats@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+60*8]
?clearHoldLocation@CharStats@@QEAAXXZ endp

; CharStats::getBashAnimation(float);
?getBashAnimation@CharStats@@QEAAPEAVCombatTechniqueData@@M@Z proc EXPORT
jmp function_pointers[_CharStats_base+61*8]
?getBashAnimation@CharStats@@QEAAPEAVCombatTechniqueData@@M@Z endp

; CharStats::chooseAttack(float, float, class CombatTechniqueData *, bool);
?chooseAttack@CharStats@@QEAAPEAVCombatTechniqueData@@MMPEAV2@_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+62*8]
?chooseAttack@CharStats@@QEAAPEAVCombatTechniqueData@@MMPEAV2@_N@Z endp

; CharStats::chooseBlock(enum CutDirection, float, enum CutOrigination, class Character *);
?chooseBlock@CharStats@@QEAAPEAVCombatTechniqueData@@W4CutDirection@@MW4CutOrigination@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+63*8]
?chooseBlock@CharStats@@QEAAPEAVCombatTechniqueData@@W4CutDirection@@MW4CutOrigination@@PEAVCharacter@@@Z endp

; CharStats::calculateStumbleBlockTimer(float);
?calculateStumbleBlockTimer@CharStats@@QEAAMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+64*8]
?calculateStumbleBlockTimer@CharStats@@QEAAMM@Z endp

; CharStats::getPainAnim(class GameData *);
?getPainAnim@CharStats@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+65*8]
?getPainAnim@CharStats@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp

; CharStats::calculateTechniqueInegrityCheckTimer();
?calculateTechniqueInegrityCheckTimer@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+66*8]
?calculateTechniqueInegrityCheckTimer@CharStats@@QEAAMXZ endp

; CharStats::calculateToughnessDamageResistanceMult();
?calculateToughnessDamageResistanceMult@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+67*8]
?calculateToughnessDamageResistanceMult@CharStats@@QEAAMXZ endp

; CharStats::calculateToughnessWoundDegenerationRate();
?calculateToughnessWoundDegenerationRate@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+68*8]
?calculateToughnessWoundDegenerationRate@CharStats@@QEAAMXZ endp

; CharStats::getAttackChance();
?getAttackChance@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+69*8]
?getAttackChance@CharStats@@QEAAMXZ endp

; CharStats::getAttackCuttingDamage();
?getAttackCuttingDamage@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+70*8]
?getAttackCuttingDamage@CharStats@@QEAAMXZ endp

; CharStats::getAttackBluntPower();
?getAttackBluntPower@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+71*8]
?getAttackBluntPower@CharStats@@QEAAMXZ endp

; CharStats::getAttackBleedDamageMult();
?getAttackBleedDamageMult@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+72*8]
?getAttackBleedDamageMult@CharStats@@QEAAMXZ endp

; CharStats::getAttackPierceDamage();
?getAttackPierceDamage@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+73*8]
?getAttackPierceDamage@CharStats@@QEAAMXZ endp

; CharStats::getTotalAttackDamageFor(class Character *);
?getTotalAttackDamageFor@CharStats@@QEAA?AVDamages@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+74*8]
?getTotalAttackDamageFor@CharStats@@QEAA?AVDamages@@PEAVCharacter@@@Z endp

?_NV_getEquippedWeaponSkill@CharStats@@QEBAMXZ proc EXPORT
?_NV_getEquippedWeaponSkill@CharStats@@QEBAMXZ endp

; CharStats::getEquippedWeaponSkill();
?getEquippedWeaponSkill@CharStats@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+75*8]
?getEquippedWeaponSkill@CharStats@@UEBAMXZ endp

; CharStats::getSkillDifferenceRatio(float, float);
?getSkillDifferenceRatio@CharStats@@QEAAMMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+76*8]
?getSkillDifferenceRatio@CharStats@@QEAAMMM@Z endp

; CharStats::calculateDeadTime(enum CharStats::DeadTimeState);
?calculateDeadTime@CharStats@@QEAAMW4DeadTimeState@1@@Z proc EXPORT
jmp function_pointers[_CharStats_base+77*8]
?calculateDeadTime@CharStats@@QEAAMW4DeadTimeState@1@@Z endp

; CharStats::xpMelee(enum CharStats::DeadTimeState, class Character *, const class Damages &);
?xpMelee@CharStats@@QEAAXW4DeadTimeState@1@PEAVCharacter@@AEBVDamages@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+78*8]
?xpMelee@CharStats@@QEAAXW4DeadTimeState@1@PEAVCharacter@@AEBVDamages@@@Z endp

; CharStats::xpToughness_RagdollEvent();
?xpToughness_RagdollEvent@CharStats@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+79*8]
?xpToughness_RagdollEvent@CharStats@@QEAAXXZ endp

; CharStats::xpToughness_GetUpEvent();
?xpToughness_GetUpEvent@CharStats@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+80*8]
?xpToughness_GetUpEvent@CharStats@@QEAAXXZ endp

; CharStats::xpToughness_PunchSomething(enum HitMaterialType);
?xpToughness_PunchSomething@CharStats@@QEAAXW4HitMaterialType@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+81*8]
?xpToughness_PunchSomething@CharStats@@QEAAXW4HitMaterialType@@@Z endp

; CharStats::xpFirstAid(class Character *, float, enum StatsEnumerated);
?xpFirstAid@CharStats@@QEAAXPEAVCharacter@@MW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+82*8]
?xpFirstAid@CharStats@@QEAAXPEAVCharacter@@MW4StatsEnumerated@@@Z endp

; CharStats::xpRunning(float, float);
?xpRunning@CharStats@@QEAAXMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+83*8]
?xpRunning@CharStats@@QEAAXMM@Z endp

; CharStats::xpStealth(float, bool, class YesNoMaybe, bool);
?xpStealth@CharStats@@QEAAXM_NVYesNoMaybe@@0@Z proc EXPORT
jmp function_pointers[_CharStats_base+84*8]
?xpStealth@CharStats@@QEAAXM_NVYesNoMaybe@@0@Z endp

; CharStats::xpStealthHearCheckEvent(bool, bool, bool);
?xpStealthHearCheckEvent@CharStats@@QEAAX_N00@Z proc EXPORT
jmp function_pointers[_CharStats_base+85*8]
?xpStealthHearCheckEvent@CharStats@@QEAAX_N00@Z endp

; CharStats::stealthXPMultForGUI();
?stealthXPMultForGUI@CharStats@@QEAA?AVStringPair@@XZ proc EXPORT
jmp function_pointers[_CharStats_base+86*8]
?stealthXPMultForGUI@CharStats@@QEAA?AVStringPair@@XZ endp

; CharStats::xpMassCombat();
?xpMassCombat@CharStats@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+87*8]
?xpMassCombat@CharStats@@QEAAXXZ endp

; CharStats::xpEngineering(float);
?xpEngineering@CharStats@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CharStats_base+88*8]
?xpEngineering@CharStats@@QEAAXM@Z endp

; CharStats::xpLockpicking(int, bool);
?xpLockpicking@CharStats@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+89*8]
?xpLockpicking@CharStats@@QEAAXH_N@Z endp

; CharStats::xpTraining(float, float, float &, float, enum StatsEnumerated);
?xpTraining@CharStats@@QEAAXMMAEAMMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+90*8]
?xpTraining@CharStats@@QEAAXMMAEAMMW4StatsEnumerated@@@Z endp

; CharStats::xpGeneral(float, float, enum StatsEnumerated);
?xpGeneral@CharStats@@QEAAXMMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+91*8]
?xpGeneral@CharStats@@QEAAXMMW4StatsEnumerated@@@Z endp

; CharStats::calculateAthleticsXPMult(float);
?calculateAthleticsXPMult@CharStats@@QEAAMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+92*8]
?calculateAthleticsXPMult@CharStats@@QEAAMM@Z endp

; CharStats::calculateStrengthXPMultFromWalking();
?calculateStrengthXPMultFromWalking@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+93*8]
?calculateStrengthXPMultFromWalking@CharStats@@QEAAMXZ endp

; CharStats::setWeapon(class Weapon *);
?setWeapon@CharStats@@QEAAXPEAVWeapon@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+94*8]
?setWeapon@CharStats@@QEAAXPEAVWeapon@@@Z endp

; CharStats::isUnarmed();
?isUnarmed@CharStats@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharStats_base+95*8]
?isUnarmed@CharStats@@QEBA_NXZ endp

; CharStats::getWeaponWeightXPBonus();
?getWeaponWeightXPBonus@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+96*8]
?getWeaponWeightXPBonus@CharStats@@QEAAMXZ endp

; CharStats::getAttackSpeed();
?getAttackSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+97*8]
?getAttackSpeed@CharStats@@QEAAMXZ endp

; CharStats::getBlockSpeed();
?getBlockSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+98*8]
?getBlockSpeed@CharStats@@QEAAMXZ endp

; CharStats::getMaxRunSpeed();
?getMaxRunSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+99*8]
?getMaxRunSpeed@CharStats@@QEAAMXZ endp

; CharStats::getCurrentWeaponLength();
?getCurrentWeaponLength@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+100*8]
?getCurrentWeaponLength@CharStats@@QEBAMXZ endp

; CharStats::getStealthSkill01(bool);
?getStealthSkill01@CharStats@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+101*8]
?getStealthSkill01@CharStats@@QEBAM_N@Z endp

; CharStats::getAttackSuccessChanceSkill();
?getAttackSuccessChanceSkill@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+102*8]
?getAttackSuccessChanceSkill@CharStats@@QEAAMXZ endp

; CharStats::_convertWeaponWeightToBluntMultiplier(float);
?_convertWeaponWeightToBluntMultiplier@CharStats@@SAMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+103*8]
?_convertWeaponWeightToBluntMultiplier@CharStats@@SAMM@Z endp

; CharStats::_convertBluntMultiplierToWeaponWeight(float);
?_convertBluntMultiplierToWeaponWeight@CharStats@@SAMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+104*8]
?_convertBluntMultiplierToWeaponWeight@CharStats@@SAMM@Z endp

; CharStats::getEncumbranceMult();
?getEncumbranceMult@CharStats@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+105*8]
?getEncumbranceMult@CharStats@@QEBAMXZ endp

; CharStats::calculateHungerMult();
?calculateHungerMult@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+106*8]
?calculateHungerMult@CharStats@@QEAAMXZ endp

; CharStats::printExertionHungerMultTooltip(class lektor<StringPair> *);
?printExertionHungerMultTooltip@CharStats@@QEAAXPEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_CharStats_base+107*8]
?printExertionHungerMultTooltip@CharStats@@QEAAXPEAV?$lektor@VStringPair@@@@@Z endp

; CharStats::calculateTheoreticalIdealMaxRunSpeed();
?calculateTheoreticalIdealMaxRunSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+108*8]
?calculateTheoreticalIdealMaxRunSpeed@CharStats@@QEAAMXZ endp

; CharStats::calculateWeaponWeightXPMult(float);
?calculateWeaponWeightXPMult@CharStats@@QEAAMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+109*8]
?calculateWeaponWeightXPMult@CharStats@@QEAAMM@Z endp

; CharStats::hasWeapon();
?hasWeapon@CharStats@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharStats_base+110*8]
?hasWeapon@CharStats@@QEBA_NXZ endp

; CharStats::calculateMaxStealthSpeed();
?calculateMaxStealthSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+111*8]
?calculateMaxStealthSpeed@CharStats@@QEAAMXZ endp

; CharStats::_calculateMaxSwimSpeed();
?_calculateMaxSwimSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+112*8]
?_calculateMaxSwimSpeed@CharStats@@QEAAMXZ endp

; CharStats::calculateSwimSpeed();
?calculateSwimSpeed@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+113*8]
?calculateSwimSpeed@CharStats@@QEAAMXZ endp

; CharStats::calculateDodgeChance(float, bool);
?calculateDodgeChance@CharStats@@QEAAMM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+114*8]
?calculateDodgeChance@CharStats@@QEAAMM_N@Z endp

; CharStats::calculateMaxRunSpeed();
?calculateMaxRunSpeed@CharStats@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+115*8]
?calculateMaxRunSpeed@CharStats@@QEAAXXZ endp

; CharStats::_calculateEncumberanceMult();
?_calculateEncumberanceMult@CharStats@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharStats_base+116*8]
?_calculateEncumberanceMult@CharStats@@QEAAMXZ endp

; CharStats::_calculateWeaponWeightSpeedMultiplier(float);
?_calculateWeaponWeightSpeedMultiplier@CharStats@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CharStats_base+117*8]
?_calculateWeaponWeightSpeedMultiplier@CharStats@@QEAAXM@Z endp

; CharStats::currentWeaponHand();
?currentWeaponHand@CharStats@@QEAA?AW4LeftRight@@XZ proc EXPORT
jmp function_pointers[_CharStats_base+118*8]
?currentWeaponHand@CharStats@@QEAA?AW4LeftRight@@XZ endp

; CharStats::calculateAttackOrBlockSpeed(float, float, bool);
?calculateAttackOrBlockSpeed@CharStats@@QEAAMMM_N@Z proc EXPORT
jmp function_pointers[_CharStats_base+119*8]
?calculateAttackOrBlockSpeed@CharStats@@QEAAMMM_N@Z endp

; CharStats::_calculateBlockChance(float);
?_calculateBlockChance@CharStats@@QEAAMM@Z proc EXPORT
jmp function_pointers[_CharStats_base+120*8]
?_calculateBlockChance@CharStats@@QEAAMM@Z endp

?_NV__recalculateStats@CharStats@@QEAAXXZ proc EXPORT
?_NV__recalculateStats@CharStats@@QEAAXXZ endp

; CharStats::_recalculateStats();
?_recalculateStats@CharStats@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+121*8]
?_recalculateStats@CharStats@@UEAAXXZ endp

; CharStats::setupCombatTechniques();
?setupCombatTechniques@CharStats@@SAXXZ proc EXPORT
jmp function_pointers[_CharStats_base+122*8]
?setupCombatTechniques@CharStats@@SAXXZ endp

?_NV_setEquippedWeaponSkill@CharStats@@QEAAXM@Z proc EXPORT
?_NV_setEquippedWeaponSkill@CharStats@@QEAAXM@Z endp

; CharStats::setEquippedWeaponSkill(float);
?setEquippedWeaponSkill@CharStats@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CharStats_base+123*8]
?setEquippedWeaponSkill@CharStats@@UEAAXM@Z endp

?_DESTRUCTOR@CharStats@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharStats@@QEAAXXZ endp

; CharStats::~CharStats();
??1CharStats@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharStats_base+124*8]
??1CharStats@@QEAA@XZ endp
