
?_CONSTRUCTOR@CharacterInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@CharacterInventoryLayout@@QEAAPEAV1@XZ endp

; CharacterInventoryLayout::CharacterInventoryLayout();
??0CharacterInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharacterInventoryLayout_base+0*8]
??0CharacterInventoryLayout@@QEAA@XZ endp

; symbol is too long
; ?setupSections@CharacterInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; CharacterInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
CharacterInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_CharacterInventoryLayout_base+1*8]
CharacterInventoryLayout_setupSections_PLACEHOLDER endp

?_DESTRUCTOR@CharacterInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharacterInventoryLayout@@QEAAXXZ endp

; CharacterInventoryLayout::~CharacterInventoryLayout();
??1CharacterInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_CharacterInventoryLayout_base+2*8]
??1CharacterInventoryLayout@@UEAA@XZ endp
