
?_CONSTRUCTOR@Character@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@Character@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@AEBVhand@@@Z endp

; Character::Character(class GameData *, class Faction *, const class hand &);
??0Character@@QEAA@PEAVGameData@@PEAVFaction@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+0*8]
??0Character@@QEAA@PEAVGameData@@PEAVFaction@@AEBVhand@@@Z endp

; Character::isImmuneToOffscreenMode();
?isImmuneToOffscreenMode@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+1*8]
?isImmuneToOffscreenMode@Character@@QEAA_NXZ endp

?_NV_init@Character@@QEAAXXZ proc EXPORT
?_NV_init@Character@@QEAAXXZ endp

; Character::init();
?init@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+2*8]
?init@Character@@UEAAXXZ endp

?_DESTRUCTOR@Character@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Character@@QEAAXXZ endp

; Character::~Character();
??1Character@@UEAA@XZ proc EXPORT
jmp function_pointers[_Character_base+3*8]
??1Character@@UEAA@XZ endp

?_NV_isOnARoof@Character@@QEAA_NXZ proc EXPORT
?_NV_isOnARoof@Character@@QEAA_NXZ endp

; Character::isOnARoof();
?isOnARoof@Character@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+4*8]
?isOnARoof@Character@@UEAA_NXZ endp

?_NV_isOnAWall@Character@@QEAA_NXZ proc EXPORT
?_NV_isOnAWall@Character@@QEAA_NXZ endp

; Character::isOnAWall();
?isOnAWall@Character@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+5*8]
?isOnAWall@Character@@UEAA_NXZ endp

; Character::getLightLevel();
?getLightLevel@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+6*8]
?getLightLevel@Character@@QEAAMXZ endp

?_NV_getHPMultiplier@Character@@QEBAMXZ proc EXPORT
?_NV_getHPMultiplier@Character@@QEBAMXZ endp

; Character::getHPMultiplier();
?getHPMultiplier@Character@@UEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+7*8]
?getHPMultiplier@Character@@UEBAMXZ endp

; Character::healCompletely();
?healCompletely@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+8*8]
?healCompletely@Character@@QEAAXXZ endp

; Character::resetRagdollNavmeshSafePos();
?resetRagdollNavmeshSafePos@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+9*8]
?resetRagdollNavmeshSafePos@Character@@QEAAXXZ endp

; Character::setRagdollNavmeshSafePos();
?setRagdollNavmeshSafePos@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+10*8]
?setRagdollNavmeshSafePos@Character@@QEAAXXZ endp

; Character::getFrameTime();
?getFrameTime@Character@@QEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+11*8]
?getFrameTime@Character@@QEBAMXZ endp

; Character::frameSkip();
?frameSkip@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+12*8]
?frameSkip@Character@@QEAAXXZ endp

; Character::getCurrentNoiseRange();
?getCurrentNoiseRange@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+13*8]
?getCurrentNoiseRange@Character@@QEAAMXZ endp

?_NV_isDestroyed@Character@@QEBA_NXZ proc EXPORT
?_NV_isDestroyed@Character@@QEBA_NXZ endp

; Character::isDestroyed();
?isDestroyed@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+14*8]
?isDestroyed@Character@@UEBA_NXZ endp

; Character::isLawEnforcement();
?isLawEnforcement@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+15*8]
?isLawEnforcement@Character@@QEAA_NXZ endp

; Character::canAssignBounties();
?canAssignBounties@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+16*8]
?canAssignBounties@Character@@QEAA_NXZ endp

?_NV_getDataType@Character@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@Character@@QEBA?AW4itemType@@XZ endp

; Character::getDataType();
?getDataType@Character@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Character_base+17*8]
?getDataType@Character@@UEBA?AW4itemType@@XZ endp

; Character::isDiplomaticStatus(bool);
?isDiplomaticStatus@Character@@QEAA_N_N@Z proc EXPORT
jmp function_pointers[_Character_base+18*8]
?isDiplomaticStatus@Character@@QEAA_N_N@Z endp

; Character::isLeadingAWarCampaign();
?isLeadingAWarCampaign@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+19*8]
?isLeadingAWarCampaign@Character@@QEAA_NXZ endp

; Character::isInAWarCampaign();
?isInAWarCampaign@Character@@QEAAPEAVCampaignInstance@@XZ proc EXPORT
jmp function_pointers[_Character_base+20*8]
?isInAWarCampaign@Character@@QEAAPEAVCampaignInstance@@XZ endp

; Character::wantsToTriggerCampaigns();
?wantsToTriggerCampaigns@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+21*8]
?wantsToTriggerCampaigns@Character@@QEAA_NXZ endp

; Character::isUnique();
?isUnique@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+22*8]
?isUnique@Character@@QEAA_NXZ endp

; Character::canSpeakNormally();
?canSpeakNormally@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+23*8]
?canSpeakNormally@Character@@QEAA_NXZ endp

?_NV_isAnimal@Character@@QEAAPEAVCharacterAnimal@@XZ proc EXPORT
?_NV_isAnimal@Character@@QEAAPEAVCharacterAnimal@@XZ endp

; Character::isAnimal();
?isAnimal@Character@@UEAAPEAVCharacterAnimal@@XZ proc EXPORT
jmp function_pointers[_Character_base+24*8]
?isAnimal@Character@@UEAAPEAVCharacterAnimal@@XZ endp

?_NV_isHuman@Character@@QEAAPEAVCharacterHuman@@XZ proc EXPORT
?_NV_isHuman@Character@@QEAAPEAVCharacterHuman@@XZ endp

; Character::isHuman();
?isHuman@Character@@UEAAPEAVCharacterHuman@@XZ proc EXPORT
jmp function_pointers[_Character_base+25*8]
?isHuman@Character@@UEAAPEAVCharacterHuman@@XZ endp

?_NV_takeMoney@Character@@QEAA_NH@Z proc EXPORT
?_NV_takeMoney@Character@@QEAA_NH@Z endp

; Character::takeMoney(int);
?takeMoney@Character@@UEAA_NH@Z proc EXPORT
jmp function_pointers[_Character_base+26*8]
?takeMoney@Character@@UEAA_NH@Z endp

?_NV_getMoney@Character@@QEBAHXZ proc EXPORT
?_NV_getMoney@Character@@QEBAHXZ endp

; Character::getMoney();
?getMoney@Character@@UEBAHXZ proc EXPORT
jmp function_pointers[_Character_base+27*8]
?getMoney@Character@@UEBAHXZ endp

; Character::setSquadMemberType(enum SquadMemberType);
?setSquadMemberType@Character@@QEAAXW4SquadMemberType@@@Z proc EXPORT
jmp function_pointers[_Character_base+28*8]
?setSquadMemberType@Character@@QEAAXW4SquadMemberType@@@Z endp

; Character::isResident();
?isResident@Character@@QEBAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_Character_base+29*8]
?isResident@Character@@QEBAPEAVTownBase@@XZ endp

; Character::dailyUpdate();
?dailyUpdate@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+30*8]
?dailyUpdate@Character@@QEAAXXZ endp

; Character::updateOnScreenCheck();
?updateOnScreenCheck@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+31*8]
?updateOnScreenCheck@Character@@QEAA_NXZ endp

; Character::offscreenUpdate();
?offscreenUpdate@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+32*8]
?offscreenUpdate@Character@@QEAAXXZ endp

; Character::updateTimes();
?updateTimes@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+33*8]
?updateTimes@Character@@QEAAXXZ endp

?_NV_getSensoryData@Character@@QEAAPEAVSensoryData@@XZ proc EXPORT
?_NV_getSensoryData@Character@@QEAAPEAVSensoryData@@XZ endp

; Character::getSensoryData();
?getSensoryData@Character@@UEAAPEAVSensoryData@@XZ proc EXPORT
jmp function_pointers[_Character_base+34*8]
?getSensoryData@Character@@UEAAPEAVSensoryData@@XZ endp

?_NV_getStateBroadcast@Character@@QEAAPEAVStateBroadcastData@@XZ proc EXPORT
?_NV_getStateBroadcast@Character@@QEAAPEAVStateBroadcastData@@XZ endp

; Character::getStateBroadcast();
?getStateBroadcast@Character@@UEAAPEAVStateBroadcastData@@XZ proc EXPORT
jmp function_pointers[_Character_base+35*8]
?getStateBroadcast@Character@@UEAAPEAVStateBroadcastData@@XZ endp

?_NV_getFormation@Character@@QEBAPEAVFormation@@XZ proc EXPORT
?_NV_getFormation@Character@@QEBAPEAVFormation@@XZ endp

; Character::getFormation();
?getFormation@Character@@UEBAPEAVFormation@@XZ proc EXPORT
jmp function_pointers[_Character_base+36*8]
?getFormation@Character@@UEBAPEAVFormation@@XZ endp

?_NV_getEnemyFormation@Character@@QEBAPEAVFormation@@XZ proc EXPORT
?_NV_getEnemyFormation@Character@@QEBAPEAVFormation@@XZ endp

; Character::getEnemyFormation();
?getEnemyFormation@Character@@UEBAPEAVFormation@@XZ proc EXPORT
jmp function_pointers[_Character_base+37*8]
?getEnemyFormation@Character@@UEBAPEAVFormation@@XZ endp

; Character::formationUpdateCallback(const class Ogre::Vector3 &, const class hand &, const class Ogre::Vector3 &, class Formation *);
?formationUpdateCallback@Character@@QEAAXAEBVVector3@Ogre@@AEBVhand@@0PEAVFormation@@@Z proc EXPORT
jmp function_pointers[_Character_base+38*8]
?formationUpdateCallback@Character@@QEAAXAEBVVector3@Ogre@@AEBVhand@@0PEAVFormation@@@Z endp

; Character::AIDestinationIndoorOutdoorCheck(class RootObject *);
?AIDestinationIndoorOutdoorCheck@Character@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Character_base+39*8]
?AIDestinationIndoorOutdoorCheck@Character@@QEAA_NPEAVRootObject@@@Z endp

?_NV_setHandle@Character@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@Character@@QEAAXAEBVhand@@@Z endp

; Character::setHandle(const class hand &);
?setHandle@Character@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+40*8]
?setHandle@Character@@UEAAXAEBVhand@@@Z endp

?_NV_update@Character@@QEAAXXZ proc EXPORT
?_NV_update@Character@@QEAAXXZ endp

; Character::update();
?update@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+41*8]
?update@Character@@UEAAXXZ endp

?_NV_postUpdate@Character@@QEAAXXZ proc EXPORT
?_NV_postUpdate@Character@@QEAAXXZ endp

; Character::postUpdate();
?postUpdate@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+42*8]
?postUpdate@Character@@UEAAXXZ endp

; Character::ragdollUpdatesUT();
?ragdollUpdatesUT@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+43*8]
?ragdollUpdatesUT@Character@@QEAAXXZ endp

; Character::fourFrameUpdate();
?fourFrameUpdate@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+44*8]
?fourFrameUpdate@Character@@QEAAXXZ endp

?_NV_periodicUpdate@Character@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@Character@@QEAAXXZ endp

; Character::periodicUpdate();
?periodicUpdate@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+45*8]
?periodicUpdate@Character@@UEAAXXZ endp

?_NV_pausedUpdate@Character@@QEAAXXZ proc EXPORT
?_NV_pausedUpdate@Character@@QEAAXXZ endp

; Character::pausedUpdate();
?pausedUpdate@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+46*8]
?pausedUpdate@Character@@UEAAXXZ endp

; Character::updateUT();
?updateUT@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+47*8]
?updateUT@Character@@QEAAXXZ endp

?_NV_threadedUpdate@Character@@QEAAXXZ proc EXPORT
?_NV_threadedUpdate@Character@@QEAAXXZ endp

; Character::threadedUpdate();
?threadedUpdate@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+48*8]
?threadedUpdate@Character@@UEAAXXZ endp

?_NV_threadedUpdate4@Character@@QEAAXXZ proc EXPORT
?_NV_threadedUpdate4@Character@@QEAAXXZ endp

; Character::threadedUpdate4();
?threadedUpdate4@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+49*8]
?threadedUpdate4@Character@@UEAAXXZ endp

?_NV_threadedUpdatePeriodic@Character@@QEAAXXZ proc EXPORT
?_NV_threadedUpdatePeriodic@Character@@QEAAXXZ endp

; Character::threadedUpdatePeriodic();
?threadedUpdatePeriodic@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+50*8]
?threadedUpdatePeriodic@Character@@UEAAXXZ endp

; Character::pathExists(const class Ogre::Vector3 &);
?pathExists@Character@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+51*8]
?pathExists@Character@@QEAA_NAEBVVector3@Ogre@@@Z endp

?_NV_weatherUpdate@Character@@QEAAXM@Z proc EXPORT
?_NV_weatherUpdate@Character@@QEAAXM@Z endp

; Character::weatherUpdate(float);
?weatherUpdate@Character@@UEAAXM@Z proc EXPORT
jmp function_pointers[_Character_base+52*8]
?weatherUpdate@Character@@UEAAXM@Z endp

; Character::stealthUpdate(float);
?stealthUpdate@Character@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Character_base+53*8]
?stealthUpdate@Character@@QEAAXM@Z endp

; Character::lineOfSightCheck(class Character *);
?lineOfSightCheck@Character@@QEAAMPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+54*8]
?lineOfSightCheck@Character@@QEAAMPEAV1@@Z endp

; Character::getPerceptionMult();
?getPerceptionMult@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+55*8]
?getPerceptionMult@Character@@QEAAMXZ endp

; Character::isWithThePlayer();
?isWithThePlayer@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+56*8]
?isWithThePlayer@Character@@QEAA_NXZ endp

; Character::notifyICanSeeYouSneaking(class Character *, class YesNoMaybe, float);
?notifyICanSeeYouSneaking@Character@@QEAAXPEAV1@VYesNoMaybe@@M@Z proc EXPORT
jmp function_pointers[_Character_base+57*8]
?notifyICanSeeYouSneaking@Character@@QEAAXPEAV1@VYesNoMaybe@@M@Z endp

; Character::isItSafeToGetUp();
?isItSafeToGetUp@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+58*8]
?isItSafeToGetUp@Character@@QEAA_NXZ endp

; Character::separateIntoMyOwnSquad(bool);
?separateIntoMyOwnSquad@Character@@QEAAPEAVPlatoon@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+59*8]
?separateIntoMyOwnSquad@Character@@QEAAPEAVPlatoon@@_N@Z endp

; Character::dropGearOnDeath(bool);
?dropGearOnDeath@Character@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+60*8]
?dropGearOnDeath@Character@@QEAAX_N@Z endp

?_NV_isItOkForMeToLoot@Character@@QEAA_NPEAVRootObject@@PEAVItem@@@Z proc EXPORT
?_NV_isItOkForMeToLoot@Character@@QEAA_NPEAVRootObject@@PEAVItem@@@Z endp

; Character::isItOkForMeToLoot(class RootObject *, class Item *);
?isItOkForMeToLoot@Character@@UEAA_NPEAVRootObject@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_Character_base+61*8]
?isItOkForMeToLoot@Character@@UEAA_NPEAVRootObject@@PEAVItem@@@Z endp

?_NV_ImStealingDoYouNotice@Character@@QEAA_NPEAVRootObject@@PEAVItem@@@Z proc EXPORT
?_NV_ImStealingDoYouNotice@Character@@QEAA_NPEAVRootObject@@PEAVItem@@@Z endp

; Character::ImStealingDoYouNotice(class RootObject *, class Item *);
?ImStealingDoYouNotice@Character@@UEAA_NPEAVRootObject@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_Character_base+62*8]
?ImStealingDoYouNotice@Character@@UEAA_NPEAVRootObject@@PEAVItem@@@Z endp

; Character::getFencingSuccessChance(class Item *, class RootObject *);
?getFencingSuccessChance@Character@@QEAAMPEAVItem@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Character_base+63*8]
?getFencingSuccessChance@Character@@QEAAMPEAVItem@@PEAVRootObject@@@Z endp

?_NV_stolenGoodsDetectionCheck@Character@@QEAA_NPEAVItem@@PEAVRootObject@@@Z proc EXPORT
?_NV_stolenGoodsDetectionCheck@Character@@QEAA_NPEAVItem@@PEAVRootObject@@@Z endp

; Character::stolenGoodsDetectionCheck(class Item *, class RootObject *);
?stolenGoodsDetectionCheck@Character@@UEAA_NPEAVItem@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Character_base+64*8]
?stolenGoodsDetectionCheck@Character@@UEAA_NPEAVItem@@PEAVRootObject@@@Z endp

?_NV_sellingUniformDetectionCheck@Character@@QEAA_NPEAVItem@@PEAV1@@Z proc EXPORT
?_NV_sellingUniformDetectionCheck@Character@@QEAA_NPEAVItem@@PEAV1@@Z endp

; Character::sellingUniformDetectionCheck(class Item *, class Character *);
?sellingUniformDetectionCheck@Character@@UEAA_NPEAVItem@@PEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+65*8]
?sellingUniformDetectionCheck@Character@@UEAA_NPEAVItem@@PEAV1@@Z endp

?_NV_smugglingTradeCheck@Character@@QEAA?AVYesNoMaybe@@PEAVItem@@PEAV1@@Z proc EXPORT
?_NV_smugglingTradeCheck@Character@@QEAA?AVYesNoMaybe@@PEAVItem@@PEAV1@@Z endp

; Character::smugglingTradeCheck(class Item *, class Character *);
?smugglingTradeCheck@Character@@UEAA?AVYesNoMaybe@@PEAVItem@@PEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+66*8]
?smugglingTradeCheck@Character@@UEAA?AVYesNoMaybe@@PEAVItem@@PEAV1@@Z endp

; Character::getStealingSuccessChance(class RootObject *, class Item *, class Character * *);
?getStealingSuccessChance@Character@@QEAAMPEAVRootObject@@PEAVItem@@PEAPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+67*8]
?getStealingSuccessChance@Character@@QEAAMPEAVRootObject@@PEAVItem@@PEAPEAV1@@Z endp

; Character::getCurrentWeatherAffectStatus();
?getCurrentWeatherAffectStatus@Character@@QEBA?AW4WeatherAffecting@@XZ proc EXPORT
jmp function_pointers[_Character_base+68*8]
?getCurrentWeatherAffectStatus@Character@@QEBA?AW4WeatherAffecting@@XZ endp

; Character::getCurrentWeatherAffectStrength();
?getCurrentWeatherAffectStrength@Character@@QEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+69*8]
?getCurrentWeatherAffectStrength@Character@@QEBAMXZ endp

; Character::getWaterLevel();
?getWaterLevel@Character@@QEAA?AW4Enum@WaterState@@XZ proc EXPORT
jmp function_pointers[_Character_base+70*8]
?getWaterLevel@Character@@QEAA?AW4Enum@WaterState@@XZ endp

; Character::setTerrainHeightPosition(float);
?setTerrainHeightPosition@Character@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Character_base+71*8]
?setTerrainHeightPosition@Character@@QEAAXM@Z endp

; Character::getTerrainHeightPosition();
?getTerrainHeightPosition@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+72*8]
?getTerrainHeightPosition@Character@@QEAAMXZ endp

; Character::setDisguiseMessage(enum Character::DisguiseGUIFeedback);
?setDisguiseMessage@Character@@QEAAXW4DisguiseGUIFeedback@1@@Z proc EXPORT
jmp function_pointers[_Character_base+73*8]
?setDisguiseMessage@Character@@QEAAXW4DisguiseGUIFeedback@1@@Z endp

; Character::uniqueStateUpdate();
?uniqueStateUpdate@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+74*8]
?uniqueStateUpdate@Character@@QEAAXXZ endp

?_NV_foodUpdate@Character@@QEAAXXZ proc EXPORT
?_NV_foodUpdate@Character@@QEAAXXZ endp

; Character::foodUpdate();
?foodUpdate@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+75*8]
?foodUpdate@Character@@UEAAXXZ endp

; Character::eatItem(class Item *, class Inventory *);
?eatItem@Character@@QEAA_NPEAVItem@@PEAVInventory@@@Z proc EXPORT
jmp function_pointers[_Character_base+76*8]
?eatItem@Character@@QEAA_NPEAVItem@@PEAVInventory@@@Z endp

?_NV_serialise@Character@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@Character@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; Character::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@Character@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_Character_base+77*8]
?serialise@Character@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@Character@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@Character@@QEAAXPEAVGameSaveState@@@Z endp

; Character::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@Character@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Character_base+78*8]
?loadFromSerialise@Character@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_loadFromSerialisePostCreationStage@Character@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialisePostCreationStage@Character@@QEAAXPEAVGameSaveState@@@Z endp

; Character::loadFromSerialisePostCreationStage(class GameSaveState *);
?loadFromSerialisePostCreationStage@Character@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Character_base+79*8]
?loadFromSerialisePostCreationStage@Character@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_setupInventorySections@Character@@QEAA_NPEAVGameSaveState@@@Z proc EXPORT
?_NV_setupInventorySections@Character@@QEAA_NPEAVGameSaveState@@@Z endp

; Character::setupInventorySections(class GameSaveState *);
?setupInventorySections@Character@@UEAA_NPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Character_base+80*8]
?setupInventorySections@Character@@UEAA_NPEAVGameSaveState@@@Z endp

?_NV_getPosition@Character@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@Character@@QEAA?AVVector3@Ogre@@XZ endp

; Character::getPosition();
?getPosition@Character@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+81*8]
?getPosition@Character@@UEAA?AVVector3@Ogre@@XZ endp

; Character::_getRawPosition();
?_getRawPosition@Character@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+82*8]
?_getRawPosition@Character@@QEBA?AVVector3@Ogre@@XZ endp

; Character::getRawEntityPosition();
?getRawEntityPosition@Character@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+83*8]
?getRawEntityPosition@Character@@QEAA?AVVector3@Ogre@@XZ endp

?_NV_getMovementSpeed@Character@@QEBAMXZ proc EXPORT
?_NV_getMovementSpeed@Character@@QEBAMXZ endp

; Character::getMovementSpeed();
?getMovementSpeed@Character@@UEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+84*8]
?getMovementSpeed@Character@@UEBAMXZ endp

?_NV_getMovementSpeedOrders@Character@@QEBA?AW4MoveSpeed@@XZ proc EXPORT
?_NV_getMovementSpeedOrders@Character@@QEBA?AW4MoveSpeed@@XZ endp

; Character::getMovementSpeedOrders();
?getMovementSpeedOrders@Character@@UEBA?AW4MoveSpeed@@XZ proc EXPORT
jmp function_pointers[_Character_base+85*8]
?getMovementSpeedOrders@Character@@UEBA?AW4MoveSpeed@@XZ endp

?_NV_getMovementDirection@Character@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getMovementDirection@Character@@QEBA?AVVector3@Ogre@@XZ endp

; Character::getMovementDirection();
?getMovementDirection@Character@@UEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+86*8]
?getMovementDirection@Character@@UEBA?AVVector3@Ogre@@XZ endp

?_NV_isPhysical@Character@@QEBA_NXZ proc EXPORT
?_NV_isPhysical@Character@@QEBA_NXZ endp

; Character::isPhysical();
?isPhysical@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+87*8]
?isPhysical@Character@@UEBA_NXZ endp

?_NV_setVisible@Character@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@Character@@QEAAX_N@Z endp

; Character::setVisible(bool);
?setVisible@Character@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+88*8]
?setVisible@Character@@UEAAX_N@Z endp

?_NV_getVisible@Character@@QEBA_NXZ proc EXPORT
?_NV_getVisible@Character@@QEBA_NXZ endp

; Character::getVisible();
?getVisible@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+89*8]
?getVisible@Character@@UEBA_NXZ endp

; Character::switchLights(bool);
?switchLights@Character@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+90*8]
?switchLights@Character@@QEAAX_N@Z endp

?_NV_isDisabled@Character@@QEAA_NXZ proc EXPORT
?_NV_isDisabled@Character@@QEAA_NXZ endp

; Character::isDisabled();
?isDisabled@Character@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+91*8]
?isDisabled@Character@@UEAA_NXZ endp

?_NV_setInsideTownWalls@Character@@QEAAXH@Z proc EXPORT
?_NV_setInsideTownWalls@Character@@QEAAXH@Z endp

; Character::setInsideTownWalls(int);
?setInsideTownWalls@Character@@UEAAXH@Z proc EXPORT
jmp function_pointers[_Character_base+92*8]
?setInsideTownWalls@Character@@UEAAXH@Z endp

?_NV_sheatheWeapon@Character@@QEAAXXZ proc EXPORT
?_NV_sheatheWeapon@Character@@QEAAXXZ endp

; Character::sheatheWeapon();
?sheatheWeapon@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+93*8]
?sheatheWeapon@Character@@UEAAXXZ endp

?_NV_select@Character@@QEAAXXZ proc EXPORT
?_NV_select@Character@@QEAAXXZ endp

; Character::select();
?select@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+94*8]
?select@Character@@UEAAXXZ endp

?_NV_unselect@Character@@QEAAXXZ proc EXPORT
?_NV_unselect@Character@@QEAAXXZ endp

; Character::unselect();
?unselect@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+95*8]
?unselect@Character@@UEAAXXZ endp

?_NV_getGUIData@Character@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@Character@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Character::getGUIData(class DatapanelGUI *, int);
?getGUIData@Character@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Character_base+96*8]
?getGUIData@Character@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getCurrentTownLocation@Character@@QEAAPEAVTownBase@@XZ proc EXPORT
?_NV_getCurrentTownLocation@Character@@QEAAPEAVTownBase@@XZ endp

; Character::getCurrentTownLocation();
?getCurrentTownLocation@Character@@UEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_Character_base+97*8]
?getCurrentTownLocation@Character@@UEAAPEAVTownBase@@XZ endp

?_NV_say_WithARepeatLimiter@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_say_WithARepeatLimiter@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::say_WithARepeatLimiter(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?say_WithARepeatLimiter@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Character_base+98*8]
?say_WithARepeatLimiter@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_say@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_say@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::say(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?say@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Character_base+99*8]
?say@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_isInventoryVisible@Character@@QEBA_NXZ proc EXPORT
?_NV_isInventoryVisible@Character@@QEBA_NXZ endp

; Character::isInventoryVisible();
?isInventoryVisible@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+100*8]
?isInventoryVisible@Character@@UEBA_NXZ endp

?_NV_giveItem@Character@@QEAA_NPEAVItem@@_N1@Z proc EXPORT
?_NV_giveItem@Character@@QEAA_NPEAVItem@@_N1@Z endp

; Character::giveItem(class Item *, bool, bool);
?giveItem@Character@@UEAA_NPEAVItem@@_N1@Z proc EXPORT
jmp function_pointers[_Character_base+101*8]
?giveItem@Character@@UEAA_NPEAVItem@@_N1@Z endp

?_NV_hasRoomForItem@Character@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_hasRoomForItem@Character@@QEAA_NPEAVGameData@@@Z endp

; Character::hasRoomForItem(class GameData *);
?hasRoomForItem@Character@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Character_base+102*8]
?hasRoomForItem@Character@@UEAA_NPEAVGameData@@@Z endp

?_NV_hasItem@Character@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_hasItem@Character@@QEAA_NPEAVGameData@@@Z endp

; Character::hasItem(class GameData *);
?hasItem@Character@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Character_base+103*8]
?hasItem@Character@@UEAA_NPEAVGameData@@@Z endp

?_NV_hasAmmoFor@Character@@QEAA_NPEAVCrossbow@@@Z proc EXPORT
?_NV_hasAmmoFor@Character@@QEAA_NPEAVCrossbow@@@Z endp

; Character::hasAmmoFor(class Crossbow *);
?hasAmmoFor@Character@@UEAA_NPEAVCrossbow@@@Z proc EXPORT
jmp function_pointers[_Character_base+104*8]
?hasAmmoFor@Character@@UEAA_NPEAVCrossbow@@@Z endp

?_NV_getNumFoodItems@Character@@QEAAHXZ proc EXPORT
?_NV_getNumFoodItems@Character@@QEAAHXZ endp

; Character::getNumFoodItems();
?getNumFoodItems@Character@@UEAAHXZ proc EXPORT
jmp function_pointers[_Character_base+105*8]
?getNumFoodItems@Character@@UEAAHXZ endp

?_NV_hasSimilarItem@Character@@QEAA_NW4itemType@@@Z proc EXPORT
?_NV_hasSimilarItem@Character@@QEAA_NW4itemType@@@Z endp

; Character::hasSimilarItem(enum itemType);
?hasSimilarItem@Character@@UEAA_NW4itemType@@@Z proc EXPORT
jmp function_pointers[_Character_base+106*8]
?hasSimilarItem@Character@@UEAA_NW4itemType@@@Z endp

; Character::ifImASmithShouldIDitchMyBackWeapon();
?ifImASmithShouldIDitchMyBackWeapon@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+107*8]
?ifImASmithShouldIDitchMyBackWeapon@Character@@QEAA_NXZ endp

?_NV_hasItemsFrom@Character@@QEAA_NPEAVStorageBuilding@@AEAV?$unordered_set@PEAVGameData@@U?$hash@PEAVGameData@@@boost@@U?$equal_to@PEAVGameData@@@std@@V?$STLAllocator@PEAVGameData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z proc EXPORT
?_NV_hasItemsFrom@Character@@QEAA_NPEAVStorageBuilding@@AEAV?$unordered_set@PEAVGameData@@U?$hash@PEAVGameData@@@boost@@U?$equal_to@PEAVGameData@@@std@@V?$STLAllocator@PEAVGameData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z endp

; Character::hasItemsFrom(class StorageBuilding *, class boost::unordered::unordered_set<GameData *,boost::hash<GameData *>,std::equal_to<GameData *>,Ogre::STLAllocator<GameData *,Ogre::CategorisedAllocPolicy<0> > > &);
?hasItemsFrom@Character@@UEAA_NPEAVStorageBuilding@@AEAV?$unordered_set@PEAVGameData@@U?$hash@PEAVGameData@@@boost@@U?$equal_to@PEAVGameData@@@std@@V?$STLAllocator@PEAVGameData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z proc EXPORT
jmp function_pointers[_Character_base+108*8]
?hasItemsFrom@Character@@UEAA_NPEAVStorageBuilding@@AEAV?$unordered_set@PEAVGameData@@U?$hash@PEAVGameData@@@boost@@U?$equal_to@PEAVGameData@@@std@@V?$STLAllocator@PEAVGameData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z endp

?_NV_getInventory@Character@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@Character@@QEBAPEAVInventory@@XZ endp

; Character::getInventory();
?getInventory@Character@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_Character_base+109*8]
?getInventory@Character@@UEBAPEAVInventory@@XZ endp

; Character::hasABackpackOn();
?hasABackpackOn@Character@@QEBAPEAVContainerItem@@XZ proc EXPORT
jmp function_pointers[_Character_base+110*8]
?hasABackpackOn@Character@@QEBAPEAVContainerItem@@XZ endp

; Character::isATrader();
?isATrader@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+111*8]
?isATrader@Character@@QEBA_NXZ endp

; Character::isFemale();
?isFemale@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+112*8]
?isFemale@Character@@QEAA_NXZ endp

; Character::isFleeing();
?isFleeing@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+113*8]
?isFleeing@Character@@QEAA_NXZ endp

?_NV_createInventoryLayout@Character@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@Character@@QEAAPEAVInventoryLayout@@XZ endp

; Character::createInventoryLayout();
?createInventoryLayout@Character@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_Character_base+114*8]
?createInventoryLayout@Character@@UEAAPEAVInventoryLayout@@XZ endp

; Character::getStealthKOChance(class Character *, bool);
?getStealthKOChance@Character@@QEAAMPEAV1@_N@Z proc EXPORT
jmp function_pointers[_Character_base+115*8]
?getStealthKOChance@Character@@QEAAMPEAV1@_N@Z endp

; Character::getKidnappingChance(class Character *);
?getKidnappingChance@Character@@QEAAMPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+116*8]
?getKidnappingChance@Character@@QEAAMPEAV1@@Z endp

; Character::getKidnappingEscapeChance_skill(class Character *);
?getKidnappingEscapeChance_skill@Character@@QEAAMPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+117*8]
?getKidnappingEscapeChance_skill@Character@@QEAAMPEAV1@@Z endp

; Character::getKidnappingEscapeChance_strength(class Character *);
?getKidnappingEscapeChance_strength@Character@@QEAAMPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+118*8]
?getKidnappingEscapeChance_strength@Character@@QEAAMPEAV1@@Z endp

; Character::getLockpickChance(class DoorLock *);
?getLockpickChance@Character@@QEAAMPEAVDoorLock@@@Z proc EXPORT
jmp function_pointers[_Character_base+119*8]
?getLockpickChance@Character@@QEAAMPEAVDoorLock@@@Z endp

; Character::shouldIHelpThisGuy(class Character *);
?shouldIHelpThisGuy@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+120*8]
?shouldIHelpThisGuy@Character@@QEAA_NPEAV1@@Z endp

; Character::shouldIScrewThisGuyOver(class Character *);
?shouldIScrewThisGuyOver@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+121*8]
?shouldIScrewThisGuyOver@Character@@QEAA_NPEAV1@@Z endp

; Character::ILoveThisGuyBecauseOfStuffThatHappened(class Character *);
?ILoveThisGuyBecauseOfStuffThatHappened@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+122*8]
?ILoveThisGuyBecauseOfStuffThatHappened@Character@@QEAA_NPEAV1@@Z endp

; Character::IHateThisGuyBecauseOfStuffThatHappened(class Character *);
?IHateThisGuyBecauseOfStuffThatHappened@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+123*8]
?IHateThisGuyBecauseOfStuffThatHappened@Character@@QEAA_NPEAV1@@Z endp

; Character::getRoughLevel();
?getRoughLevel@Character@@QEAAHXZ proc EXPORT
jmp function_pointers[_Character_base+124*8]
?getRoughLevel@Character@@QEAAHXZ endp

?_NV_setStandingOrder@Character@@QEAAXW4StandingOrder@MessageForB@@_N@Z proc EXPORT
?_NV_setStandingOrder@Character@@QEAAXW4StandingOrder@MessageForB@@_N@Z endp

; Character::setStandingOrder(enum MessageForB::StandingOrder, bool);
?setStandingOrder@Character@@UEAAXW4StandingOrder@MessageForB@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+125*8]
?setStandingOrder@Character@@UEAAXW4StandingOrder@MessageForB@@_N@Z endp

; Character::getStandingOrder(enum MessageForB::StandingOrder);
?getStandingOrder@Character@@QEBA_NW4StandingOrder@MessageForB@@@Z proc EXPORT
jmp function_pointers[_Character_base+126*8]
?getStandingOrder@Character@@QEBA_NW4StandingOrder@MessageForB@@@Z endp

; Character::setStealthMode(bool);
?setStealthMode@Character@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+127*8]
?setStealthMode@Character@@QEAAX_N@Z endp

; Character::isStealthMode();
?isStealthMode@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+128*8]
?isStealthMode@Character@@QEBA_NXZ endp

; Character::isStealthModeOrCrawling();
?isStealthModeOrCrawling@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+129*8]
?isStealthModeOrCrawling@Character@@QEBA_NXZ endp

; Character::declareDead();
?declareDead@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+130*8]
?declareDead@Character@@QEAAXXZ endp

; Character::updateGUIStatsDetails(class DatapanelGUI *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?updateGUIStatsDetails@Character@@QEAAXPEAVDatapanelGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_Character_base+131*8]
?updateGUIStatsDetails@Character@@QEAAXPEAVDatapanelGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; Character::_printRaceXPBonusLine(class DatapanelGUI *, enum StatsEnumerated);
?_printRaceXPBonusLine@Character@@QEAAXPEAVDatapanelGUI@@W4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_Character_base+132*8]
?_printRaceXPBonusLine@Character@@QEAAXPEAVDatapanelGUI@@W4StatsEnumerated@@@Z endp

; Character::addGoal(enum TaskType, class RootObjectBase *);
?addGoal@Character@@QEAAXW4TaskType@@PEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_Character_base+133*8]
?addGoal@Character@@QEAAXW4TaskType@@PEAVRootObjectBase@@@Z endp

; Character::addJob(enum TaskType, class RootObject *, bool, bool, const class Ogre::Vector3 &);
?addJob@Character@@QEAAXW4TaskType@@PEAVRootObject@@_N2AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+134*8]
?addJob@Character@@QEAAXW4TaskType@@PEAVRootObject@@_N2AEBVVector3@Ogre@@@Z endp

; Character::removeJob(enum TaskType);
?removeJob@Character@@QEAAXW4TaskType@@@Z proc EXPORT
jmp function_pointers[_Character_base+135*8]
?removeJob@Character@@QEAAXW4TaskType@@@Z endp

; Character::removePermajob(int);
?removePermajob@Character@@QEAAXH@Z proc EXPORT
jmp function_pointers[_Character_base+136*8]
?removePermajob@Character@@QEAAXH@Z endp

; Character::clearPermajobs();
?clearPermajobs@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+137*8]
?clearPermajobs@Character@@QEAAXXZ endp

; Character::movePermajob(int, int);
?movePermajob@Character@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_Character_base+138*8]
?movePermajob@Character@@QEAAXHH@Z endp

; Character::getPermajobName(int);
?getPermajobName@Character@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_Character_base+139*8]
?getPermajobName@Character@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; Character::getPermajob(int);
?getPermajob@Character@@QEBA?AW4TaskType@@H@Z proc EXPORT
jmp function_pointers[_Character_base+140*8]
?getPermajob@Character@@QEBA?AW4TaskType@@H@Z endp

; Character::getPermajobData(int);
?getPermajobData@Character@@QEBAPEBVTasker@@H@Z proc EXPORT
jmp function_pointers[_Character_base+141*8]
?getPermajobData@Character@@QEBAPEBVTasker@@H@Z endp

; Character::getPermajobCount();
?getPermajobCount@Character@@QEBAHXZ proc EXPORT
jmp function_pointers[_Character_base+142*8]
?getPermajobCount@Character@@QEBAHXZ endp

?_NV_getAABB@Character@@QEBAAEBUAabb@Ogre@@XZ proc EXPORT
?_NV_getAABB@Character@@QEBAAEBUAabb@Ogre@@XZ endp

; Character::getAABB();
?getAABB@Character@@UEBAAEBUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+143*8]
?getAABB@Character@@UEBAAEBUAabb@Ogre@@XZ endp

; Character::addOrder(class Building *, enum TaskType, class RootObject *, bool, bool, const class Ogre::Vector3 &);
?addOrder@Character@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@_N3AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+144*8]
?addOrder@Character@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@_N3AEBVVector3@Ogre@@@Z endp

?_NV_updateLastTask@Character@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_updateLastTask@Character@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@AEBVVector3@Ogre@@@Z endp

; Character::updateLastTask(class Building *, enum TaskType, class RootObject *, const class Ogre::Vector3 &);
?updateLastTask@Character@@UEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+145*8]
?updateLastTask@Character@@UEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@AEBVVector3@Ogre@@@Z endp

?_NV_playerMoveOrderDefault@Character@@QEAAXPEAVBuilding@@PEAVRootObject@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_playerMoveOrderDefault@Character@@QEAAXPEAVBuilding@@PEAVRootObject@@AEBVVector3@Ogre@@@Z endp

; Character::playerMoveOrderDefault(class Building *, class RootObject *, const class Ogre::Vector3 &);
?playerMoveOrderDefault@Character@@UEAAXPEAVBuilding@@PEAVRootObject@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+146*8]
?playerMoveOrderDefault@Character@@UEAAXPEAVBuilding@@PEAVRootObject@@AEBVVector3@Ogre@@@Z endp

; Character::endCombatMode();
?endCombatMode@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+147*8]
?endCombatMode@Character@@QEAAXXZ endp

?_NV_getTotalRelativeStrengthOfAttackers@Character@@QEAAMXZ proc EXPORT
?_NV_getTotalRelativeStrengthOfAttackers@Character@@QEAAMXZ endp

; Character::getTotalRelativeStrengthOfAttackers();
?getTotalRelativeStrengthOfAttackers@Character@@UEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+148*8]
?getTotalRelativeStrengthOfAttackers@Character@@UEAAMXZ endp

?_NV_canGoIndoors@Character@@QEBA_NPEAVBuilding@@@Z proc EXPORT
?_NV_canGoIndoors@Character@@QEBA_NPEAVBuilding@@@Z endp

; Character::canGoIndoors(class Building *);
?canGoIndoors@Character@@UEBA_NPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_Character_base+149*8]
?canGoIndoors@Character@@UEBA_NPEAVBuilding@@@Z endp

?_NV_isIndoors@Character@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_isIndoors@Character@@QEBAAEBVhand@@XZ endp

; Character::isIndoors();
?isIndoors@Character@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Character_base+150*8]
?isIndoors@Character@@UEBAAEBVhand@@XZ endp

?_NV_isStandingOnBuilding@Character@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_isStandingOnBuilding@Character@@QEBAAEBVhand@@XZ endp

; Character::isStandingOnBuilding();
?isStandingOnBuilding@Character@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Character_base+151*8]
?isStandingOnBuilding@Character@@UEBAAEBVhand@@XZ endp

?_NV_isIndoorsRagdoll@Character@@QEBA_NXZ proc EXPORT
?_NV_isIndoorsRagdoll@Character@@QEBA_NXZ endp

; Character::isIndoorsRagdoll();
?isIndoorsRagdoll@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+152*8]
?isIndoorsRagdoll@Character@@UEBA_NXZ endp

?_NV_notifyIndoors@Character@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_notifyIndoors@Character@@QEAAXAEBVhand@@@Z endp

; Character::notifyIndoors(const class hand &);
?notifyIndoors@Character@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+153*8]
?notifyIndoors@Character@@UEAAXAEBVhand@@@Z endp

; Character::destinationIndoors(class RootObject *);
?destinationIndoors@Character@@QEBA?AVhand@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Character_base+154*8]
?destinationIndoors@Character@@QEBA?AVhand@@PEAVRootObject@@@Z endp

; Character::destinationInsideWalls(class RootObject *);
?destinationInsideWalls@Character@@QEAAHPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Character_base+155*8]
?destinationInsideWalls@Character@@QEAAHPEAVRootObject@@@Z endp

; Character::setDestinationIndoors(const class hand &);
?setDestinationIndoors@Character@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+156*8]
?setDestinationIndoors@Character@@QEAAXAEBVhand@@@Z endp

?_NV_getIntendedAggression@Character@@QEAAMXZ proc EXPORT
?_NV_getIntendedAggression@Character@@QEAAMXZ endp

; Character::getIntendedAggression();
?getIntendedAggression@Character@@UEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+157*8]
?getIntendedAggression@Character@@UEAAMXZ endp

; Character::getPositionBip01();
?getPositionBip01@Character@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+158*8]
?getPositionBip01@Character@@QEAA?AVVector3@Ogre@@XZ endp

?_NV_amInsideTownWalls@Character@@QEAAHXZ proc EXPORT
?_NV_amInsideTownWalls@Character@@QEAAHXZ endp

; Character::amInsideTownWalls();
?amInsideTownWalls@Character@@UEAAHXZ proc EXPORT
jmp function_pointers[_Character_base+159*8]
?amInsideTownWalls@Character@@UEAAHXZ endp

?_NV_setName@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setName@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Character_base+160*8]
?setName@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::setNameTagVisible(bool);
?setNameTagVisible@Character@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+161*8]
?setNameTagVisible@Character@@QEAAX_N@Z endp

; Character::ragdollMode(bool, enum RagdollPart::Enum);
?ragdollMode@Character@@QEAAX_NW4Enum@RagdollPart@@@Z proc EXPORT
jmp function_pointers[_Character_base+162*8]
?ragdollMode@Character@@QEAAX_NW4Enum@RagdollPart@@@Z endp

; Character::isRagdoll();
?isRagdoll@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+163*8]
?isRagdoll@Character@@QEBA_NXZ endp

; Character::isDown();
?isDown@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+164*8]
?isDown@Character@@QEAA_NXZ endp

; Character::getRagdollPhysicsRootPos();
?getRagdollPhysicsRootPos@Character@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_Character_base+165*8]
?getRagdollPhysicsRootPos@Character@@QEAA?AVVector3@Ogre@@XZ endp

?_NV_amSomeoneWhoNeedsToEatToLive@Character@@QEAA_NXZ proc EXPORT
?_NV_amSomeoneWhoNeedsToEatToLive@Character@@QEAA_NXZ endp

; Character::amSomeoneWhoNeedsToEatToLive();
?amSomeoneWhoNeedsToEatToLive@Character@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+166*8]
?amSomeoneWhoNeedsToEatToLive@Character@@UEAA_NXZ endp

?_NV_getMagicHungerSetting@Character@@QEAAMXZ proc EXPORT
?_NV_getMagicHungerSetting@Character@@QEAAMXZ endp

; Character::getMagicHungerSetting();
?getMagicHungerSetting@Character@@UEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+167*8]
?getMagicHungerSetting@Character@@UEAAMXZ endp

; Character::wantsToEatNow();
?wantsToEatNow@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+168*8]
?wantsToEatNow@Character@@QEAA_NXZ endp

?_NV_isKidnapped@Character@@QEAA_NXZ proc EXPORT
?_NV_isKidnapped@Character@@QEAA_NXZ endp

; Character::isKidnapped();
?isKidnapped@Character@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+169*8]
?isKidnapped@Character@@UEAA_NXZ endp

?_NV_isLiterallyUnconciousNotPretending@Character@@QEBA_NXZ proc EXPORT
?_NV_isLiterallyUnconciousNotPretending@Character@@QEBA_NXZ endp

; Character::isLiterallyUnconciousNotPretending();
?isLiterallyUnconciousNotPretending@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+170*8]
?isLiterallyUnconciousNotPretending@Character@@UEBA_NXZ endp

?_NV_isUnconcious@Character@@QEBA_NXZ proc EXPORT
?_NV_isUnconcious@Character@@QEBA_NXZ endp

; Character::isUnconcious();
?isUnconcious@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+171*8]
?isUnconcious@Character@@UEBA_NXZ endp

?_NV_isCrippled@Character@@QEBA_NXZ proc EXPORT
?_NV_isCrippled@Character@@QEBA_NXZ endp

; Character::isCrippled();
?isCrippled@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+172*8]
?isCrippled@Character@@UEBA_NXZ endp

?_NV_getProneState@Character@@QEBA?AW4ProneState@@XZ proc EXPORT
?_NV_getProneState@Character@@QEBA?AW4ProneState@@XZ endp

; Character::getProneState();
?getProneState@Character@@UEBA?AW4ProneState@@XZ proc EXPORT
jmp function_pointers[_Character_base+173*8]
?getProneState@Character@@UEBA?AW4ProneState@@XZ endp

?_NV_setProneState@Character@@QEAAXW4ProneState@@@Z proc EXPORT
?_NV_setProneState@Character@@QEAAXW4ProneState@@@Z endp

; Character::setProneState(enum ProneState);
?setProneState@Character@@UEAAXW4ProneState@@@Z proc EXPORT
jmp function_pointers[_Character_base+174*8]
?setProneState@Character@@UEAAXW4ProneState@@@Z endp

; Character::_killRagdoll(bool);
?_killRagdoll@Character@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+175*8]
?_killRagdoll@Character@@QEAAX_N@Z endp

?_NV_giveBirth@Character@@QEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z proc EXPORT
?_NV_giveBirth@Character@@QEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z endp

; Character::giveBirth(class GameDataCopyStandalone *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class GameSaveState *, class ActivePlatoon *, class Faction *);
?giveBirth@Character@@UEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_Character_base+176*8]
?giveBirth@Character@@UEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z endp

; Character::setupAI();
?setupAI@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+177*8]
?setupAI@Character@@QEAAXXZ endp

; Character::clearAllAIGoals();
?clearAllAIGoals@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+178*8]
?clearAllAIGoals@Character@@QEAAXXZ endp

; Character::setupPlatoonAI();
?setupPlatoonAI@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+179*8]
?setupPlatoonAI@Character@@QEAAXXZ endp

; Character::setAppearanceData(class GameDataCopyStandalone *);
?setAppearanceData@Character@@QEAAXPEAVGameDataCopyStandalone@@@Z proc EXPORT
jmp function_pointers[_Character_base+180*8]
?setAppearanceData@Character@@QEAAXPEAVGameDataCopyStandalone@@@Z endp

; Character::getAppearanceData();
?getAppearanceData@Character@@QEAAPEAVGameDataCopyStandalone@@XZ proc EXPORT
jmp function_pointers[_Character_base+181*8]
?getAppearanceData@Character@@QEAAPEAVGameDataCopyStandalone@@XZ endp

; Character::setDestination(const class Ogre::Vector3 &, bool);
?setDestination@Character@@QEAAXAEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+182*8]
?setDestination@Character@@QEAAXAEBVVector3@Ogre@@_N@Z endp

; Character::sendDialogEventOverride(class Character *, enum EventTriggerEnum, bool);
?sendDialogEventOverride@Character@@QEAA_NPEAV1@W4EventTriggerEnum@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+183*8]
?sendDialogEventOverride@Character@@QEAA_NPEAV1@W4EventTriggerEnum@@_N@Z endp

; Character::sendDialogEvent(class Character *, enum EventTriggerEnum);
?sendDialogEvent@Character@@QEAA_NPEAV1@W4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Character_base+184*8]
?sendDialogEvent@Character@@QEAA_NPEAV1@W4EventTriggerEnum@@@Z endp

; Character::sayALine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?sayALine@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+185*8]
?sayALine@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; Character::hasDialogue();
?hasDialogue@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+186*8]
?hasDialogue@Character@@QEBA_NXZ endp

; Character::willTalkToEnemies();
?willTalkToEnemies@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+187*8]
?willTalkToEnemies@Character@@QEAA_NXZ endp

; Character::relocationTeleport(const class Ogre::Vector3 &);
?relocationTeleport@Character@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+188*8]
?relocationTeleport@Character@@QEAAXAEBVVector3@Ogre@@@Z endp

; Character::teleport(const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?teleport@Character@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z proc EXPORT
jmp function_pointers[_Character_base+189*8]
?teleport@Character@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z endp

; Character::teleport(const class Ogre::Vector3 &);
?teleport@Character@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+190*8]
?teleport@Character@@QEAAXAEBVVector3@Ogre@@@Z endp

; Character::teleportVisuallyOnly(const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?teleportVisuallyOnly@Character@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z proc EXPORT
jmp function_pointers[_Character_base+191*8]
?teleportVisuallyOnly@Character@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z endp

; Character::teleportFromAnimation();
?teleportFromAnimation@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+192*8]
?teleportFromAnimation@Character@@QEAAXXZ endp

; Character::debugIndicateCharacters(class lektor<Character *>);
?debugIndicateCharacters@Character@@QEAAXV?$lektor@PEAVCharacter@@@@@Z proc EXPORT
jmp function_pointers[_Character_base+193*8]
?debugIndicateCharacters@Character@@QEAAXV?$lektor@PEAVCharacter@@@@@Z endp

; Character::attackTarget(class Character *);
?attackTarget@Character@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+194*8]
?attackTarget@Character@@QEAAXPEAV1@@Z endp

; Character::notifyTheCampaignOfAnAttack(class Character *);
?notifyTheCampaignOfAnAttack@Character@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+195*8]
?notifyTheCampaignOfAnAttack@Character@@QEAAXPEAV1@@Z endp

; Character::iShouldntAggravateThisTarget(class Character *);
?iShouldntAggravateThisTarget@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+196*8]
?iShouldntAggravateThisTarget@Character@@QEAA_NPEAV1@@Z endp

; Character::sendMessage(enum CharacterMessage, class RootObject *, class RootObject *);
?sendMessage@Character@@QEAAXW4CharacterMessage@@PEAVRootObject@@1@Z proc EXPORT
jmp function_pointers[_Character_base+197*8]
?sendMessage@Character@@QEAAXW4CharacterMessage@@PEAVRootObject@@1@Z endp

; Character::attackingYou(class Character *, bool, bool);
?attackingYou@Character@@QEAAXPEAV1@_N1@Z proc EXPORT
jmp function_pointers[_Character_base+198*8]
?attackingYou@Character@@QEAAXPEAV1@_N1@Z endp

; Character::iShotYou(class Character *, class Harpoon *, bool);
?iShotYou@Character@@QEAA_NPEAV1@PEAVHarpoon@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+199*8]
?iShotYou@Character@@QEAA_NPEAV1@PEAVHarpoon@@_N@Z endp

?_NV_hitByMeleeAttack@Character@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAV1@PEAVCombatTechniqueData@@H@Z proc EXPORT
?_NV_hitByMeleeAttack@Character@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAV1@PEAVCombatTechniqueData@@H@Z endp

; Character::hitByMeleeAttack(enum CutDirection, class Damages &, class Character *, class CombatTechniqueData *, int);
?hitByMeleeAttack@Character@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAV1@PEAVCombatTechniqueData@@H@Z proc EXPORT
jmp function_pointers[_Character_base+200*8]
?hitByMeleeAttack@Character@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAV1@PEAVCombatTechniqueData@@H@Z endp

?_NV_gettingEaten@Character@@QEAA_NMPEAV1@@Z proc EXPORT
?_NV_gettingEaten@Character@@QEAA_NMPEAV1@@Z endp

; Character::gettingEaten(float, class Character *);
?gettingEaten@Character@@UEAA_NMPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+201*8]
?gettingEaten@Character@@UEAA_NMPEAV1@@Z endp

; Character::_startStumble(enum CutDirection, class Damages &, class GameData *, class Character *);
?_startStumble@Character@@QEAAXW4CutDirection@@AEAVDamages@@PEAVGameData@@PEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+202*8]
?_startStumble@Character@@QEAAXW4CutDirection@@AEAVDamages@@PEAVGameData@@PEAV1@@Z endp

; Character::getAttackOriginationDirection(class Character *);
?getAttackOriginationDirection@Character@@QEAA?AW4CutOrigination@@PEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+203*8]
?getAttackOriginationDirection@Character@@QEAA?AW4CutOrigination@@PEAV1@@Z endp

; Character::convertCutDirection(enum CutDirection, enum CutOrigination);
?convertCutDirection@Character@@QEAA?AW4CutDirection@@W42@W4CutOrigination@@@Z proc EXPORT
jmp function_pointers[_Character_base+204*8]
?convertCutDirection@Character@@QEAA?AW4CutDirection@@W42@W4CutOrigination@@@Z endp

; Character::convertCutDirection(enum CutDirection, class Character *);
?convertCutDirection@Character@@QEAA?AW4CutDirection@@W42@PEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+205*8]
?convertCutDirection@Character@@QEAA?AW4CutDirection@@W42@PEAV1@@Z endp

; Character::stumbleState();
?stumbleState@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+206*8]
?stumbleState@Character@@QEAA_NXZ endp

?_NV_setAge@Character@@QEAAXM@Z proc EXPORT
?_NV_setAge@Character@@QEAAXM@Z endp

; Character::setAge(float);
?setAge@Character@@UEAAXM@Z proc EXPORT
jmp function_pointers[_Character_base+207*8]
?setAge@Character@@UEAAXM@Z endp

?_NV_setFaction@Character@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
?_NV_setFaction@Character@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

; Character::setFaction(class Faction *, class ActivePlatoon *);
?setFaction@Character@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_Character_base+208*8]
?setFaction@Character@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

?_NV_getAge@Character@@QEBAMXZ proc EXPORT
?_NV_getAge@Character@@QEBAMXZ endp

; Character::getAge();
?getAge@Character@@UEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+209*8]
?getAge@Character@@UEBAMXZ endp

?_NV_getAge0to1@Character@@QEBAMXZ proc EXPORT
?_NV_getAge0to1@Character@@QEBAMXZ endp

; Character::getAge0to1();
?getAge0to1@Character@@UEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+210*8]
?getAge0to1@Character@@UEBAMXZ endp

?_NV_getAgeString@Character@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getAgeString@Character@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Character::getAgeString();
?getAgeString@Character@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Character_base+211*8]
?getAgeString@Character@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getAgeInverse@Character@@QEBAMXZ proc EXPORT
?_NV_getAgeInverse@Character@@QEBAMXZ endp

; Character::getAgeInverse();
?getAgeInverse@Character@@UEBAMXZ proc EXPORT
jmp function_pointers[_Character_base+212*8]
?getAgeInverse@Character@@UEBAMXZ endp

; Character::reThinkCurrentAIAction();
?reThinkCurrentAIAction@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+213*8]
?reThinkCurrentAIAction@Character@@QEAAXXZ endp

; Character::getBody();
?getBody@Character@@QEAAPEAVCharBody@@XZ proc EXPORT
jmp function_pointers[_Character_base+214*8]
?getBody@Character@@QEAAPEAVCharBody@@XZ endp

; Character::getCombatClass();
?getCombatClass@Character@@QEBAPEAVCombatClass@@XZ proc EXPORT
jmp function_pointers[_Character_base+215*8]
?getCombatClass@Character@@QEBAPEAVCombatClass@@XZ endp

; Character::getStats();
?getStats@Character@@QEAAPEAVCharStats@@XZ proc EXPORT
jmp function_pointers[_Character_base+216*8]
?getStats@Character@@QEAAPEAVCharStats@@XZ endp

; Character::getMedical();
?getMedical@Character@@QEAAPEAVMedicalSystem@@XZ proc EXPORT
jmp function_pointers[_Character_base+217*8]
?getMedical@Character@@QEAAPEAVMedicalSystem@@XZ endp

; Character::getOwnerships();
?getOwnerships@Character@@QEBAPEAVOwnerships@@XZ proc EXPORT
jmp function_pointers[_Character_base+218*8]
?getOwnerships@Character@@QEBAPEAVOwnerships@@XZ endp

; Character::getAI();
?getAI@Character@@QEAAPEAVAI@@XZ proc EXPORT
jmp function_pointers[_Character_base+219*8]
?getAI@Character@@QEAAPEAVAI@@XZ endp

; Character::getSquadMissionTarget(class hand &);
?getSquadMissionTarget@Character@@QEAAXAEAVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+220*8]
?getSquadMissionTarget@Character@@QEAAXAEAVhand@@@Z endp

; Character::getAttackTarget();
?getAttackTarget@Character@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Character_base+221*8]
?getAttackTarget@Character@@QEBA?AVhand@@XZ endp

; Character::isInCombatMode(bool, bool);
?isInCombatMode@Character@@QEBA_N_N0@Z proc EXPORT
jmp function_pointers[_Character_base+222*8]
?isInCombatMode@Character@@QEBA_N_N0@Z endp

; Character::isInRangedCombatMode();
?isInRangedCombatMode@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+223*8]
?isInRangedCombatMode@Character@@QEBA_NXZ endp

; Character::isLiterallyUnderMeleeAttackRightNowForSure();
?isLiterallyUnderMeleeAttackRightNowForSure@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+224*8]
?isLiterallyUnderMeleeAttackRightNowForSure@Character@@QEBA_NXZ endp

; Character::_isLiterallyUnderMeleeAttackRightNowForSure_update();
?_isLiterallyUnderMeleeAttackRightNowForSure_update@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+225*8]
?_isLiterallyUnderMeleeAttackRightNowForSure_update@Character@@QEAAXXZ endp

; Character::conglomerateTagsFor(class Character *);
?conglomerateTagsFor@Character@@QEAAIPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+226*8]
?conglomerateTagsFor@Character@@QEAAIPEAV1@@Z endp

; Character::isPrisonerFreeToGo();
?isPrisonerFreeToGo@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+227*8]
?isPrisonerFreeToGo@Character@@QEAA_NXZ endp

; Character::clearTempEnemyStatus(class Character *);
?clearTempEnemyStatus@Character@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+228*8]
?clearTempEnemyStatus@Character@@QEAAXPEAV1@@Z endp

; Character::clearAllTempEnemyStatuses(enum CharacterPerceptionTags_ShortTerm);
?clearAllTempEnemyStatuses@Character@@QEAAXW4CharacterPerceptionTags_ShortTerm@@@Z proc EXPORT
jmp function_pointers[_Character_base+229*8]
?clearAllTempEnemyStatuses@Character@@QEAAXW4CharacterPerceptionTags_ShortTerm@@@Z endp

; Character::rememberCharacter(class Character *, enum CharacterPerceptionTags_ShortTerm);
?rememberCharacter@Character@@QEAAXPEAV1@W4CharacterPerceptionTags_ShortTerm@@@Z proc EXPORT
jmp function_pointers[_Character_base+230*8]
?rememberCharacter@Character@@QEAAXPEAV1@W4CharacterPerceptionTags_ShortTerm@@@Z endp

; Character::rememberCharacter(class Character *, enum CharacterPerceptionTags_LongTerm);
?rememberCharacter@Character@@QEAAXPEAV1@W4CharacterPerceptionTags_LongTerm@@@Z proc EXPORT
jmp function_pointers[_Character_base+231*8]
?rememberCharacter@Character@@QEAAXPEAV1@W4CharacterPerceptionTags_LongTerm@@@Z endp

; Character::getCharacterMemoryTag(class Character *, enum CharacterPerceptionTags_LongTerm);
?getCharacterMemoryTag@Character@@QEAA_NPEAV1@W4CharacterPerceptionTags_LongTerm@@@Z proc EXPORT
jmp function_pointers[_Character_base+232*8]
?getCharacterMemoryTag@Character@@QEAA_NPEAV1@W4CharacterPerceptionTags_LongTerm@@@Z endp

; Character::getCharacterMemoryTag(class Character *, enum CharacterPerceptionTags_ShortTerm);
?getCharacterMemoryTag@Character@@QEAA_NPEAV1@W4CharacterPerceptionTags_ShortTerm@@@Z proc EXPORT
jmp function_pointers[_Character_base+233*8]
?getCharacterMemoryTag@Character@@QEAA_NPEAV1@W4CharacterPerceptionTags_ShortTerm@@@Z endp

; Character::lastSeenInHoursAgo(class Character *);
?lastSeenInHoursAgo@Character@@QEAAMPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+234*8]
?lastSeenInHoursAgo@Character@@QEAAMPEAV1@@Z endp

; Character::haveMetBefore(class Character *);
?haveMetBefore@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+235*8]
?haveMetBefore@Character@@QEAA_NPEAV1@@Z endp

; Character::getIDForMemoryTagging();
?getIDForMemoryTagging@Character@@QEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Character_base+236*8]
?getIDForMemoryTagging@Character@@QEAA?AVhand@@XZ endp

; Character::getMovement();
?getMovement@Character@@QEAAPEAVCharMovement@@XZ proc EXPORT
jmp function_pointers[_Character_base+237*8]
?getMovement@Character@@QEAAPEAVCharMovement@@XZ endp

?_NV_lookatPosition@Character@@QEAAXAEBVVector3@Ogre@@_N@Z proc EXPORT
?_NV_lookatPosition@Character@@QEAAXAEBVVector3@Ogre@@_N@Z endp

; Character::lookatPosition(const class Ogre::Vector3 &, bool);
?lookatPosition@Character@@UEAAXAEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+238*8]
?lookatPosition@Character@@UEAAXAEBVVector3@Ogre@@_N@Z endp

; Character::areYouGonnaGetMe(class Character *);
?areYouGonnaGetMe@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+239*8]
?areYouGonnaGetMe@Character@@QEAA_NPEAV1@@Z endp

; Character::getAllAttackers(class lektor<hand> &);
?getAllAttackers@Character@@QEAAAEAV?$lektor@Vhand@@@@AEAV2@@Z proc EXPORT
jmp function_pointers[_Character_base+240*8]
?getAllAttackers@Character@@QEAAAEAV?$lektor@Vhand@@@@AEAV2@@Z endp

; Character::getAllAttackersCount();
?getAllAttackersCount@Character@@QEAAHXZ proc EXPORT
jmp function_pointers[_Character_base+241*8]
?getAllAttackersCount@Character@@QEAAHXZ endp

?_NV_getRace@Character@@QEBAPEAVRaceData@@XZ proc EXPORT
?_NV_getRace@Character@@QEBAPEAVRaceData@@XZ endp

; Character::getRace();
?getRace@Character@@UEBAPEAVRaceData@@XZ proc EXPORT
jmp function_pointers[_Character_base+242*8]
?getRace@Character@@UEBAPEAVRaceData@@XZ endp

?_NV_setRace@Character@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_setRace@Character@@QEAAXPEAVGameData@@@Z endp

; Character::setRace(class GameData *);
?setRace@Character@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Character_base+243*8]
?setRace@Character@@UEAAXPEAVGameData@@@Z endp

; Character::getRadius();
?getRadius@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+244*8]
?getRadius@Character@@QEAAMXZ endp

; Character::isPlayerCharacter();
?isPlayerCharacter@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+245*8]
?isPlayerCharacter@Character@@QEBA_NXZ endp

; Character::checkPlayerOrderForProblems(enum TaskType, class RootObject *);
?checkPlayerOrderForProblems@Character@@QEAA_NW4TaskType@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Character_base+246*8]
?checkPlayerOrderForProblems@Character@@QEAA_NW4TaskType@@PEAVRootObject@@@Z endp

; Character::breakFollowOrderLoop(const class hand &);
?breakFollowOrderLoop@Character@@QEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+247*8]
?breakFollowOrderLoop@Character@@QEAA_NAEBVhand@@@Z endp

; Character::getTotalCarryWeight();
?getTotalCarryWeight@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+248*8]
?getTotalCarryWeight@Character@@QEAAMXZ endp

?_NV_getRangedWeapon@Character@@QEAAPEAVCrossbow@@XZ proc EXPORT
?_NV_getRangedWeapon@Character@@QEAAPEAVCrossbow@@XZ endp

; Character::getRangedWeapon();
?getRangedWeapon@Character@@UEAAPEAVCrossbow@@XZ proc EXPORT
jmp function_pointers[_Character_base+249*8]
?getRangedWeapon@Character@@UEAAPEAVCrossbow@@XZ endp

; Character::getUpperBodyArmour();
?getUpperBodyArmour@Character@@QEAAPEAVItem@@XZ proc EXPORT
jmp function_pointers[_Character_base+250*8]
?getUpperBodyArmour@Character@@QEAAPEAVItem@@XZ endp

; Character::getLowerBodyArmour();
?getLowerBodyArmour@Character@@QEAAPEAVItem@@XZ proc EXPORT
jmp function_pointers[_Character_base+251*8]
?getLowerBodyArmour@Character@@QEAAPEAVItem@@XZ endp

; Character::isInjured(bool);
?isInjured@Character@@QEBA_N_N@Z proc EXPORT
jmp function_pointers[_Character_base+252*8]
?isInjured@Character@@QEBA_N_N@Z endp

; Character::shouldUseRangedWeapons();
?shouldUseRangedWeapons@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+253*8]
?shouldUseRangedWeapons@Character@@QEAA_NXZ endp

; Character::getBoneWorldPosition(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBoneWorldPosition@Character@@QEAA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Character_base+254*8]
?getBoneWorldPosition@Character@@QEAA?AVVector3@Ogre@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::getAppearance();
?getAppearance@Character@@QEAAPEAVAppearanceBase@@XZ proc EXPORT
jmp function_pointers[_Character_base+255*8]
?getAppearance@Character@@QEAAPEAVAppearanceBase@@XZ endp

; Character::_setPlatoon(class ActivePlatoon *, int);
?_setPlatoon@Character@@QEAAXPEAVActivePlatoon@@H@Z proc EXPORT
jmp function_pointers[_Character_base+256*8]
?_setPlatoon@Character@@QEAAXPEAVActivePlatoon@@H@Z endp

; Character::getPlatoon();
?getPlatoon@Character@@QEBAPEAVActivePlatoon@@XZ proc EXPORT
jmp function_pointers[_Character_base+257*8]
?getPlatoon@Character@@QEBAPEAVActivePlatoon@@XZ endp

; Character::hasPlatoon();
?hasPlatoon@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+258*8]
?hasPlatoon@Character@@QEBA_NXZ endp

; Character::isInAPersistentPlatoon();
?isInAPersistentPlatoon@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+259*8]
?isInAPersistentPlatoon@Character@@QEBA_NXZ endp

; Character::getBlackboard();
?getBlackboard@Character@@QEAAPEAVBlackboard@@XZ proc EXPORT
jmp function_pointers[_Character_base+260*8]
?getBlackboard@Character@@QEAAPEAVBlackboard@@XZ endp

; Character::getSquadLeader();
?getSquadLeader@Character@@QEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Character_base+261*8]
?getSquadLeader@Character@@QEAAPEAV1@XZ endp

; Character::getOrdersReciever();
?getOrdersReciever@Character@@QEBAPEAVOrdersReceiver@@XZ proc EXPORT
jmp function_pointers[_Character_base+262*8]
?getOrdersReciever@Character@@QEBAPEAVOrdersReceiver@@XZ endp

; Character::preventRagdollMode();
?preventRagdollMode@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+263*8]
?preventRagdollMode@Character@@QEBA_NXZ endp

; Character::setPrisonMode(bool, class UseableStuff *);
?setPrisonMode@Character@@QEAAX_NPEAVUseableStuff@@@Z proc EXPORT
jmp function_pointers[_Character_base+264*8]
?setPrisonMode@Character@@QEAAX_NPEAVUseableStuff@@@Z endp

; Character::setBedMode(bool, class UseableStuff *);
?setBedMode@Character@@QEAAX_NPEAVUseableStuff@@@Z proc EXPORT
jmp function_pointers[_Character_base+265*8]
?setBedMode@Character@@QEAAX_NPEAVUseableStuff@@@Z endp

; Character::setSlaveAIJob(bool);
?setSlaveAIJob@Character@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Character_base+266*8]
?setSlaveAIJob@Character@@QEAAX_N@Z endp

; Character::setChainedMode(bool, const class hand &);
?setChainedMode@Character@@QEAAX_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+267*8]
?setChainedMode@Character@@QEAAX_NAEBVhand@@@Z endp

; Character::isChainedMode();
?isChainedMode@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+268*8]
?isChainedMode@Character@@QEBA_NXZ endp

; Character::getChainedModeShackles();
?getChainedModeShackles@Character@@QEAAPEAVLockedArmour@@XZ proc EXPORT
jmp function_pointers[_Character_base+269*8]
?getChainedModeShackles@Character@@QEAAPEAVLockedArmour@@XZ endp

; Character::getMySlaveOwner();
?getMySlaveOwner@Character@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Character_base+270*8]
?getMySlaveOwner@Character@@QEBA?AVhand@@XZ endp

; Character::isSlave();
?isSlave@Character@@QEAA?AW4SlaveStateEnum@@XZ proc EXPORT
jmp function_pointers[_Character_base+271*8]
?isSlave@Character@@QEAA?AW4SlaveStateEnum@@XZ endp

; Character::changeSlaveOwner(const class hand &);
?changeSlaveOwner@Character@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Character_base+272*8]
?changeSlaveOwner@Character@@QEAAXAEBVhand@@@Z endp

; Character::isMySlave(class Character *);
?isMySlave@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+273*8]
?isMySlave@Character@@QEAA_NPEAV1@@Z endp

; Character::isMyFactionsSlave(class Character *);
?isMyFactionsSlave@Character@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+274*8]
?isMyFactionsSlave@Character@@QEAA_NPEAV1@@Z endp

?_NV_isHeadShaven@Character@@QEBA_NXZ proc EXPORT
?_NV_isHeadShaven@Character@@QEBA_NXZ endp

; Character::isHeadShaven();
?isHeadShaven@Character@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+275*8]
?isHeadShaven@Character@@UEBA_NXZ endp

; Character::runSlaveAnim(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float);
?runSlaveAnim@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM@Z proc EXPORT
jmp function_pointers[_Character_base+276*8]
?runSlaveAnim@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MM@Z endp

; Character::endSlaveAnim(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?endSlaveAnim@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Character_base+277*8]
?endSlaveAnim@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::updatePortraitGUIState();
?updatePortraitGUIState@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+278*8]
?updatePortraitGUIState@Character@@QEAAXXZ endp

; Character::pickupObject(class Character *);
?pickupObject@Character@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+279*8]
?pickupObject@Character@@QEAAXPEAV1@@Z endp

; Character::getPickedUp(class Character *);
?getPickedUp@Character@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_Character_base+280*8]
?getPickedUp@Character@@QEAAXPEAV1@@Z endp

; Character::slaveAttachToBoneMode(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?slaveAttachToBoneMode@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Character_base+281*8]
?slaveAttachToBoneMode@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Character::isDead();
?isDead@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+282*8]
?isDead@Character@@QEBA_NXZ endp

; Character::isBeingCarried();
?isBeingCarried@Character@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Character_base+283*8]
?isBeingCarried@Character@@QEBA_NXZ endp

; Character::getCarryingObject();
?getCarryingObject@Character@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Character_base+284*8]
?getCarryingObject@Character@@QEBA?AVhand@@XZ endp

; Character::chooseCarryObjectLeftOrRight();
?chooseCarryObjectLeftOrRight@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+285*8]
?chooseCarryObjectLeftOrRight@Character@@QEAAXXZ endp

; Character::dropCarriedObject(bool, bool);
?dropCarriedObject@Character@@QEAAX_N0@Z proc EXPORT
jmp function_pointers[_Character_base+286*8]
?dropCarriedObject@Character@@QEAAX_N0@Z endp

; Character::getDropped(bool, bool);
?getDropped@Character@@QEAAX_N0@Z proc EXPORT
jmp function_pointers[_Character_base+287*8]
?getDropped@Character@@QEAAX_N0@Z endp

; Character::getDiplomacyMultiplier();
?getDiplomacyMultiplier@Character@@QEAAMXZ proc EXPORT
jmp function_pointers[_Character_base+288*8]
?getDiplomacyMultiplier@Character@@QEAAMXZ endp

?_NV_isEnemy@Character@@QEAA_NPEAV1@_N@Z proc EXPORT
?_NV_isEnemy@Character@@QEAA_NPEAV1@_N@Z endp

; Character::isEnemy(class Character *, bool);
?isEnemy@Character@@UEAA_NPEAV1@_N@Z proc EXPORT
jmp function_pointers[_Character_base+289*8]
?isEnemy@Character@@UEAA_NPEAV1@_N@Z endp

?_NV_isAlly@Character@@QEAA_NPEAV1@_N@Z proc EXPORT
?_NV_isAlly@Character@@QEAA_NPEAV1@_N@Z endp

; Character::isAlly(class Character *, bool);
?isAlly@Character@@UEAA_NPEAV1@_N@Z proc EXPORT
jmp function_pointers[_Character_base+290*8]
?isAlly@Character@@UEAA_NPEAV1@_N@Z endp

?_NV_getDefaultTaskRepertoireEnum@Character@@QEBAIXZ proc EXPORT
?_NV_getDefaultTaskRepertoireEnum@Character@@QEBAIXZ endp

; Character::getDefaultTaskRepertoireEnum();
?getDefaultTaskRepertoireEnum@Character@@UEBAIXZ proc EXPORT
jmp function_pointers[_Character_base+291*8]
?getDefaultTaskRepertoireEnum@Character@@UEBAIXZ endp

; Character::getAnimationClass();
?getAnimationClass@Character@@QEAAPEAVAnimationClass@@XZ proc EXPORT
jmp function_pointers[_Character_base+292*8]
?getAnimationClass@Character@@QEAAPEAVAnimationClass@@XZ endp

; Character::getPredictedPosition(float);
?getPredictedPosition@Character@@QEAA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_Character_base+293*8]
?getPredictedPosition@Character@@QEAA?AVVector3@Ogre@@M@Z endp

; Character::carryModeT(bool, bool, bool);
?carryModeT@Character@@QEAAX_N00@Z proc EXPORT
jmp function_pointers[_Character_base+294*8]
?carryModeT@Character@@QEAAX_N00@Z endp

; Character::_carryMode(bool, bool, bool);
?_carryMode@Character@@QEAAX_N00@Z proc EXPORT
jmp function_pointers[_Character_base+295*8]
?_carryMode@Character@@QEAAX_N00@Z endp

; Character::recalculateTotalEquipmentSkillBonus();
?recalculateTotalEquipmentSkillBonus@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+296*8]
?recalculateTotalEquipmentSkillBonus@Character@@QEAAXXZ endp

?_NV_setupAudio@Character@@QEAAXXZ proc EXPORT
?_NV_setupAudio@Character@@QEAAXXZ endp

; Character::setupAudio();
?setupAudio@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+297*8]
?setupAudio@Character@@UEAAXXZ endp

; Character::getAudioObject();
?getAudioObject@Character@@QEBA_KXZ proc EXPORT
jmp function_pointers[_Character_base+298*8]
?getAudioObject@Character@@QEBA_KXZ endp

; Character::audioEvent(const char *, enum SoundRange);
?audioEvent@Character@@QEAA_NPEBDW4SoundRange@@@Z proc EXPORT
jmp function_pointers[_Character_base+299*8]
?audioEvent@Character@@QEAA_NPEBDW4SoundRange@@@Z endp

; Character::audioValue(const char *, float);
?audioValue@Character@@QEBAXPEBDM@Z proc EXPORT
jmp function_pointers[_Character_base+300*8]
?audioValue@Character@@QEBAXPEBDM@Z endp

; Character::audioValue(const char *, const char *);
?audioValue@Character@@QEBAXPEBD0@Z proc EXPORT
jmp function_pointers[_Character_base+301*8]
?audioValue@Character@@QEBAXPEBD0@Z endp

; Character::setGroundType(enum GroundType);
?setGroundType@Character@@QEAAXW4GroundType@@@Z proc EXPORT
jmp function_pointers[_Character_base+302*8]
?setGroundType@Character@@QEAAXW4GroundType@@@Z endp

; Character::getGroundType();
?getGroundType@Character@@QEAA?AW4GroundType@@XZ proc EXPORT
jmp function_pointers[_Character_base+303*8]
?getGroundType@Character@@QEAA?AW4GroundType@@XZ endp

; Character::calculateMainArmourType();
?calculateMainArmourType@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+304*8]
?calculateMainArmourType@Character@@QEAAXXZ endp

; Character::getMainArmourType();
?getMainArmourType@Character@@QEBA?AW4ArmourType@@XZ proc EXPORT
jmp function_pointers[_Character_base+305*8]
?getMainArmourType@Character@@QEBA?AW4ArmourType@@XZ endp

?_NV_wearingUniformOf@Character@@QEAA_NPEAVFaction@@@Z proc EXPORT
?_NV_wearingUniformOf@Character@@QEAA_NPEAVFaction@@@Z endp

; Character::wearingUniformOf(class Faction *);
?wearingUniformOf@Character@@UEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_Character_base+306*8]
?wearingUniformOf@Character@@UEAA_NPEAVFaction@@@Z endp

; Character::getUniformColorScheme();
?getUniformColorScheme@Character@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Character_base+307*8]
?getUniformColorScheme@Character@@QEAAPEAVGameData@@XZ endp

; Character::canTakePlayerOrdersAtThisTime();
?canTakePlayerOrdersAtThisTime@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+308*8]
?canTakePlayerOrdersAtThisTime@Character@@QEAA_NXZ endp

; Character::startEffect(class GameData *);
?startEffect@Character@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Character_base+309*8]
?startEffect@Character@@QEAA_NPEAVGameData@@@Z endp

; Character::stopEffect(class GameData *);
?stopEffect@Character@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Character_base+310*8]
?stopEffect@Character@@QEAA_NPEAVGameData@@@Z endp

; Character::stopAllEffects();
?stopAllEffects@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+311*8]
?stopAllEffects@Character@@QEAAXXZ endp

?_NV_notifyEffect@Character@@QEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z proc EXPORT
?_NV_notifyEffect@Character@@QEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z endp

; Character::notifyEffect(enum EffectType::Enum, enum WeatherAffecting, float);
?notifyEffect@Character@@UEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z proc EXPORT
jmp function_pointers[_Character_base+312*8]
?notifyEffect@Character@@UEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z endp

?_NV_equipItem@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_equipItem@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; Character::equipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?equipItem@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_Character_base+313*8]
?equipItem@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_unequipItem@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_unequipItem@Character@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; Character::unequipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?unequipItem@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_Character_base+314*8]
?unequipItem@Character@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_validateInventorySections@Character@@QEAAXXZ proc EXPORT
?_NV_validateInventorySections@Character@@QEAAXXZ endp

; Character::validateInventorySections();
?validateInventorySections@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+315*8]
?validateInventorySections@Character@@UEAAXXZ endp

; Character::processCharacterLoadTimeMessages();
?processCharacterLoadTimeMessages@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+316*8]
?processCharacterLoadTimeMessages@Character@@QEAAXXZ endp

; Character::wantsPathfinderActive();
?wantsPathfinderActive@Character@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+317*8]
?wantsPathfinderActive@Character@@QEAA_NXZ endp

; Character::_ragdollMode(const struct Character::RagdollMsg &);
?_ragdollMode@Character@@QEAA_NAEBURagdollMsg@1@@Z proc EXPORT
jmp function_pointers[_Character_base+318*8]
?_ragdollMode@Character@@QEAA_NAEBURagdollMsg@1@@Z endp

; Character::calculateDestinationState(class Building *, class RootObject *, const class Ogre::Vector3 &);
?calculateDestinationState@Character@@QEAAXPEAVBuilding@@PEAVRootObject@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Character_base+319*8]
?calculateDestinationState@Character@@QEAAXPEAVBuilding@@PEAVRootObject@@AEBVVector3@Ogre@@@Z endp

; Character::generateWeapon(class GameData *, class GameData *);
?generateWeapon@Character@@QEAAPEAVItem@@PEAVGameData@@0@Z proc EXPORT
jmp function_pointers[_Character_base+320*8]
?generateWeapon@Character@@QEAAPEAVItem@@PEAVGameData@@0@Z endp

?_NV_createPhysical@Character@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@Character@@QEAA_NXZ endp

; Character::createPhysical();
?createPhysical@Character@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Character_base+321*8]
?createPhysical@Character@@UEAA_NXZ endp

?_NV_destroyPhysical@Character@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@Character@@QEAAXXZ endp

; Character::destroyPhysical();
?destroyPhysical@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+322*8]
?destroyPhysical@Character@@UEAAXXZ endp

; Character::createComponents(class GameDataCopyStandalone *);
?createComponents@Character@@QEAA_NPEAVGameDataCopyStandalone@@@Z proc EXPORT
jmp function_pointers[_Character_base+323*8]
?createComponents@Character@@QEAA_NPEAVGameDataCopyStandalone@@@Z endp

?_NV_loadUnloadCheck@Character@@QEAAXXZ proc EXPORT
?_NV_loadUnloadCheck@Character@@QEAAXXZ endp

; Character::loadUnloadCheck();
?loadUnloadCheck@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+324*8]
?loadUnloadCheck@Character@@UEAAXXZ endp

; Character::updateStateBroadcast(float);
?updateStateBroadcast@Character@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Character_base+325*8]
?updateStateBroadcast@Character@@QEAAXM@Z endp

; Character::setEffectBT(class GameData *, bool);
?setEffectBT@Character@@QEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_Character_base+326*8]
?setEffectBT@Character@@QEAAXPEAVGameData@@_N@Z endp

?_NV_postRagdollCallback@Character@@QEAAX_NW4Enum@RagdollPart@@@Z proc EXPORT
?_NV_postRagdollCallback@Character@@QEAAX_NW4Enum@RagdollPart@@@Z endp

; Character::postRagdollCallback(bool, enum RagdollPart::Enum);
?postRagdollCallback@Character@@UEAAX_NW4Enum@RagdollPart@@@Z proc EXPORT
jmp function_pointers[_Character_base+327*8]
?postRagdollCallback@Character@@UEAAX_NW4Enum@RagdollPart@@@Z endp

?_NV_reCalculateNaturalWeapon@Character@@QEAAXXZ proc EXPORT
?_NV_reCalculateNaturalWeapon@Character@@QEAAXXZ endp

; Character::reCalculateNaturalWeapon();
?reCalculateNaturalWeapon@Character@@UEAAXXZ proc EXPORT
jmp function_pointers[_Character_base+328*8]
?reCalculateNaturalWeapon@Character@@UEAAXXZ endp
