
?_NV_isAnimal@CharacterAnimal@@QEAAPEAV1@XZ proc EXPORT
?_NV_isAnimal@CharacterAnimal@@QEAAPEAV1@XZ endp

; CharacterAnimal::isAnimal();
?isAnimal@CharacterAnimal@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+0*8]
?isAnimal@CharacterAnimal@@UEAAPEAV1@XZ endp

?_NV_createAnimationClass@CharacterAnimal@@QEAAXXZ proc EXPORT
?_NV_createAnimationClass@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::createAnimationClass();
?createAnimationClass@CharacterAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+1*8]
?createAnimationClass@CharacterAnimal@@UEAAXXZ endp

?_NV_drawWeapon@CharacterAnimal@@QEAA_NPEAVItem@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_drawWeapon@CharacterAnimal@@QEAA_NPEAVItem@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharacterAnimal::drawWeapon(class Item *, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?drawWeapon@CharacterAnimal@@UEAA_NPEAVItem@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+2*8]
?drawWeapon@CharacterAnimal@@UEAA_NPEAVItem@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_sheatheWeapon@CharacterAnimal@@QEAAXXZ proc EXPORT
?_NV_sheatheWeapon@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::sheatheWeapon();
?sheatheWeapon@CharacterAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+3*8]
?sheatheWeapon@CharacterAnimal@@UEAAXXZ endp

?_NV_getCurrentWeapon@CharacterAnimal@@QEAAPEAVWeapon@@XZ proc EXPORT
?_NV_getCurrentWeapon@CharacterAnimal@@QEAAPEAVWeapon@@XZ endp

; CharacterAnimal::getCurrentWeapon();
?getCurrentWeapon@CharacterAnimal@@UEAAPEAVWeapon@@XZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+4*8]
?getCurrentWeapon@CharacterAnimal@@UEAAPEAVWeapon@@XZ endp

?_NV_getThePreferredWeapon@CharacterAnimal@@QEAAPEAVWeapon@@XZ proc EXPORT
?_NV_getThePreferredWeapon@CharacterAnimal@@QEAAPEAVWeapon@@XZ endp

; CharacterAnimal::getThePreferredWeapon();
?getThePreferredWeapon@CharacterAnimal@@UEAAPEAVWeapon@@XZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+5*8]
?getThePreferredWeapon@CharacterAnimal@@UEAAPEAVWeapon@@XZ endp

?_NV_createInventoryLayout@CharacterAnimal@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@CharacterAnimal@@QEAAPEAVInventoryLayout@@XZ endp

; CharacterAnimal::createInventoryLayout();
?createInventoryLayout@CharacterAnimal@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+6*8]
?createInventoryLayout@CharacterAnimal@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_giveBirth@CharacterAnimal@@QEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z proc EXPORT
?_NV_giveBirth@CharacterAnimal@@QEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z endp

; CharacterAnimal::giveBirth(class GameDataCopyStandalone *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class GameSaveState *, class ActivePlatoon *, class Faction *);
?giveBirth@CharacterAnimal@@UEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+7*8]
?giveBirth@CharacterAnimal@@UEAA_NPEAVGameDataCopyStandalone@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVGameSaveState@@PEAVActivePlatoon@@PEAVFaction@@@Z endp

?_NV_setupInventorySections@CharacterAnimal@@QEAA_NPEAVGameSaveState@@@Z proc EXPORT
?_NV_setupInventorySections@CharacterAnimal@@QEAA_NPEAVGameSaveState@@@Z endp

; CharacterAnimal::setupInventorySections(class GameSaveState *);
?setupInventorySections@CharacterAnimal@@UEAA_NPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+8*8]
?setupInventorySections@CharacterAnimal@@UEAA_NPEAVGameSaveState@@@Z endp

?_NV_setupAudio@CharacterAnimal@@QEAAXXZ proc EXPORT
?_NV_setupAudio@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::setupAudio();
?setupAudio@CharacterAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+9*8]
?setupAudio@CharacterAnimal@@UEAAXXZ endp

?_NV_periodicUpdate@CharacterAnimal@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::periodicUpdate();
?periodicUpdate@CharacterAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+10*8]
?periodicUpdate@CharacterAnimal@@UEAAXXZ endp

?_NV_setAge@CharacterAnimal@@QEAAXM@Z proc EXPORT
?_NV_setAge@CharacterAnimal@@QEAAXM@Z endp

; CharacterAnimal::setAge(float);
?setAge@CharacterAnimal@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+11*8]
?setAge@CharacterAnimal@@UEAAXM@Z endp

?_NV_getAge@CharacterAnimal@@QEBAMXZ proc EXPORT
?_NV_getAge@CharacterAnimal@@QEBAMXZ endp

; CharacterAnimal::getAge();
?getAge@CharacterAnimal@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+12*8]
?getAge@CharacterAnimal@@UEBAMXZ endp

?_NV_getAgeInverse@CharacterAnimal@@QEBAMXZ proc EXPORT
?_NV_getAgeInverse@CharacterAnimal@@QEBAMXZ endp

; CharacterAnimal::getAgeInverse();
?getAgeInverse@CharacterAnimal@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+13*8]
?getAgeInverse@CharacterAnimal@@UEBAMXZ endp

?_NV_getAge0to1@CharacterAnimal@@QEBAMXZ proc EXPORT
?_NV_getAge0to1@CharacterAnimal@@QEBAMXZ endp

; CharacterAnimal::getAge0to1();
?getAge0to1@CharacterAnimal@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+14*8]
?getAge0to1@CharacterAnimal@@UEBAMXZ endp

?_NV_getDefaultTaskRepertoireEnum@CharacterAnimal@@QEBAIXZ proc EXPORT
?_NV_getDefaultTaskRepertoireEnum@CharacterAnimal@@QEBAIXZ endp

; CharacterAnimal::getDefaultTaskRepertoireEnum();
?getDefaultTaskRepertoireEnum@CharacterAnimal@@UEBAIXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+15*8]
?getDefaultTaskRepertoireEnum@CharacterAnimal@@UEBAIXZ endp

?_NV_canGoIndoors@CharacterAnimal@@QEBA_NPEAVBuilding@@@Z proc EXPORT
?_NV_canGoIndoors@CharacterAnimal@@QEBA_NPEAVBuilding@@@Z endp

; CharacterAnimal::canGoIndoors(class Building *);
?canGoIndoors@CharacterAnimal@@UEBA_NPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+16*8]
?canGoIndoors@CharacterAnimal@@UEBA_NPEAVBuilding@@@Z endp

?_NV_getSmellHuntingThresholdBlood@CharacterAnimal@@QEBAMXZ proc EXPORT
?_NV_getSmellHuntingThresholdBlood@CharacterAnimal@@QEBAMXZ endp

; CharacterAnimal::getSmellHuntingThresholdBlood();
?getSmellHuntingThresholdBlood@CharacterAnimal@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+17*8]
?getSmellHuntingThresholdBlood@CharacterAnimal@@UEBAMXZ endp

?_NV_getSmellHuntingThresholdEggs@CharacterAnimal@@QEBAMXZ proc EXPORT
?_NV_getSmellHuntingThresholdEggs@CharacterAnimal@@QEBAMXZ endp

; CharacterAnimal::getSmellHuntingThresholdEggs();
?getSmellHuntingThresholdEggs@CharacterAnimal@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+18*8]
?getSmellHuntingThresholdEggs@CharacterAnimal@@UEBAMXZ endp

?_NV_getHPMultiplier@CharacterAnimal@@QEBAMXZ proc EXPORT
?_NV_getHPMultiplier@CharacterAnimal@@QEBAMXZ endp

; CharacterAnimal::getHPMultiplier();
?getHPMultiplier@CharacterAnimal@@UEBAMXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+19*8]
?getHPMultiplier@CharacterAnimal@@UEBAMXZ endp

?_NV_foodUpdate@CharacterAnimal@@QEAAXXZ proc EXPORT
?_NV_foodUpdate@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::foodUpdate();
?foodUpdate@CharacterAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+20*8]
?foodUpdate@CharacterAnimal@@UEAAXXZ endp

; CharacterAnimal::pickupItemInMouth(class Item *);
?pickupItemInMouth@CharacterAnimal@@QEAA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+21*8]
?pickupItemInMouth@CharacterAnimal@@QEAA_NPEAVItem@@@Z endp

; CharacterAnimal::dropItemInMouth();
?dropItemInMouth@CharacterAnimal@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+22*8]
?dropItemInMouth@CharacterAnimal@@QEAA_NXZ endp

; CharacterAnimal::getItemInMouth();
?getItemInMouth@CharacterAnimal@@QEAAPEAVItem@@XZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+23*8]
?getItemInMouth@CharacterAnimal@@QEAAPEAVItem@@XZ endp

; CharacterAnimal::eatItemInMouth();
?eatItemInMouth@CharacterAnimal@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+24*8]
?eatItemInMouth@CharacterAnimal@@QEAAXXZ endp

?_CONSTRUCTOR@CharacterAnimal@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@Vhand@@M@Z proc EXPORT
?_CONSTRUCTOR@CharacterAnimal@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@Vhand@@M@Z endp

; CharacterAnimal::CharacterAnimal(class GameData *, class Faction *, class hand, float);
??0CharacterAnimal@@QEAA@PEAVGameData@@PEAVFaction@@Vhand@@M@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+25*8]
??0CharacterAnimal@@QEAA@PEAVGameData@@PEAVFaction@@Vhand@@M@Z endp

?_DESTRUCTOR@CharacterAnimal@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::~CharacterAnimal();
??1CharacterAnimal@@UEAA@XZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+26*8]
??1CharacterAnimal@@UEAA@XZ endp

?_NV_init@CharacterAnimal@@QEAAXXZ proc EXPORT
?_NV_init@CharacterAnimal@@QEAAXXZ endp

; CharacterAnimal::init();
?init@CharacterAnimal@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterAnimal_base+27*8]
?init@CharacterAnimal@@UEAAXXZ endp

?_NV_dropItem@CharacterAnimal@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_dropItem@CharacterAnimal@@QEAAXPEAVRootObject@@@Z endp

; CharacterAnimal::dropItem(class RootObject *);
?dropItem@CharacterAnimal@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_CharacterAnimal_base+28*8]
?dropItem@CharacterAnimal@@UEAAXPEAVRootObject@@@Z endp
