
?_CONSTRUCTOR@CharMovement@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@CharMovement@@QEAAPEAV1@XZ endp

; CharMovement::CharMovement();
??0CharMovement@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+0*8]
??0CharMovement@@QEAA@XZ endp

?_DESTRUCTOR@CharMovement@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharMovement@@QEAAXXZ endp

; CharMovement::~CharMovement();
??1CharMovement@@UEAA@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+1*8]
??1CharMovement@@UEAA@XZ endp

?_NV_create@CharMovement@@QEAAXPEAVCharacter@@PEAVAnimationClass@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_create@CharMovement@@QEAAXPEAVCharacter@@PEAVAnimationClass@@AEBVVector3@Ogre@@@Z endp

; CharMovement::create(class Character *, class AnimationClass *, const class Ogre::Vector3 &);
?create@CharMovement@@UEAAXPEAVCharacter@@PEAVAnimationClass@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+2*8]
?create@CharMovement@@UEAAXPEAVCharacter@@PEAVAnimationClass@@AEBVVector3@Ogre@@@Z endp

?_NV__setPositionAndTeleport@CharMovement@@QEAAXAEBVVector3@Ogre@@H@Z proc EXPORT
?_NV__setPositionAndTeleport@CharMovement@@QEAAXAEBVVector3@Ogre@@H@Z endp

; CharMovement::_setPositionAndTeleport(const class Ogre::Vector3 &, int);
?_setPositionAndTeleport@CharMovement@@UEAAXAEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_CharMovement_base+3*8]
?_setPositionAndTeleport@CharMovement@@UEAAXAEBVVector3@Ogre@@H@Z endp

?_NV__setPositionDirectionAndTeleport@CharMovement@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z proc EXPORT
?_NV__setPositionDirectionAndTeleport@CharMovement@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z endp

; CharMovement::_setPositionDirectionAndTeleport(const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?_setPositionDirectionAndTeleport@CharMovement@@UEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+4*8]
?_setPositionDirectionAndTeleport@CharMovement@@UEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z endp

?_NV__setPositionSimple@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV__setPositionSimple@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::_setPositionSimple(const class Ogre::Vector3 &);
?_setPositionSimple@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+5*8]
?_setPositionSimple@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::isRunning();
?isRunning@CharMovement@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+6*8]
?isRunning@CharMovement@@QEAA_NXZ endp

; CharMovement::isRunningAway(const class Ogre::Vector3 &);
?isRunningAway@CharMovement@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+7*8]
?isRunningAway@CharMovement@@QEAA_NAEBVVector3@Ogre@@@Z endp

; CharMovement::formationUpdateCallback(const class Ogre::Vector3 &, const class hand &, const class Ogre::Vector3 &, class Formation *);
?formationUpdateCallback@CharMovement@@QEAAXAEBVVector3@Ogre@@AEBVhand@@0PEAVFormation@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+8*8]
?formationUpdateCallback@CharMovement@@QEAAXAEBVVector3@Ogre@@AEBVhand@@0PEAVFormation@@@Z endp

; CharMovement::trackAnimationMovement(bool);
?trackAnimationMovement@CharMovement@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_CharMovement_base+9*8]
?trackAnimationMovement@CharMovement@@QEAAX_N@Z endp

?_NV_getHandle@CharMovement@@QEAA?AVhand@@XZ proc EXPORT
?_NV_getHandle@CharMovement@@QEAA?AVhand@@XZ endp

; CharMovement::getHandle();
?getHandle@CharMovement@@UEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+10*8]
?getHandle@CharMovement@@UEAA?AVhand@@XZ endp

?_NV_handleChanged@CharMovement@@QEAAXXZ proc EXPORT
?_NV_handleChanged@CharMovement@@QEAAXXZ endp

; CharMovement::handleChanged();
?handleChanged@CharMovement@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+11*8]
?handleChanged@CharMovement@@UEAAXXZ endp

; CharMovement::getRadius();
?getRadius@CharMovement@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharMovement_base+12*8]
?getRadius@CharMovement@@QEAAMXZ endp

?_NV_update@CharMovement@@QEAAXM@Z proc EXPORT
?_NV_update@CharMovement@@QEAAXM@Z endp

; CharMovement::update(float);
?update@CharMovement@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CharMovement_base+13*8]
?update@CharMovement@@UEAAXM@Z endp

; CharMovement::pausedUpdate();
?pausedUpdate@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+14*8]
?pausedUpdate@CharMovement@@QEAAXXZ endp

; CharMovement::twoFrameUpdate(float);
?twoFrameUpdate@CharMovement@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CharMovement_base+15*8]
?twoFrameUpdate@CharMovement@@QEAAXM@Z endp

; CharMovement::postAnimationUpdate();
?postAnimationUpdate@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+16*8]
?postAnimationUpdate@CharMovement@@QEAAXXZ endp

; CharMovement::periodicUpdate(float);
?periodicUpdate@CharMovement@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CharMovement_base+17*8]
?periodicUpdate@CharMovement@@QEAAXM@Z endp

; CharMovement::predictNextPosition(bool);
?predictNextPosition@CharMovement@@QEAA?AVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_CharMovement_base+18*8]
?predictNextPosition@CharMovement@@QEAA?AVVector3@Ogre@@_N@Z endp

; CharMovement::getMaximumPossibleMovement();
?getMaximumPossibleMovement@CharMovement@@QEBAMXZ proc EXPORT
jmp function_pointers[_CharMovement_base+19*8]
?getMaximumPossibleMovement@CharMovement@@QEBAMXZ endp

?_NV_faceDirection@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_faceDirection@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::faceDirection(const class Ogre::Vector3 &);
?faceDirection@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+20*8]
?faceDirection@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_lookatPosition@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_lookatPosition@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::lookatPosition(const class Ogre::Vector3 &);
?lookatPosition@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+21*8]
?lookatPosition@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_pathOk@CharMovement@@QEBA_NXZ proc EXPORT
?_NV_pathOk@CharMovement@@QEBA_NXZ endp

; CharMovement::pathOk();
?pathOk@CharMovement@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+22*8]
?pathOk@CharMovement@@UEBA_NXZ endp

?_NV_pathFailed@CharMovement@@QEBA_NXZ proc EXPORT
?_NV_pathFailed@CharMovement@@QEBA_NXZ endp

; CharMovement::pathFailed();
?pathFailed@CharMovement@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+23*8]
?pathFailed@CharMovement@@UEBA_NXZ endp

?_NV_isDestinationReached@CharMovement@@QEBA_NXZ proc EXPORT
?_NV_isDestinationReached@CharMovement@@QEBA_NXZ endp

; CharMovement::isDestinationReached();
?isDestinationReached@CharMovement@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+24*8]
?isDestinationReached@CharMovement@@UEBA_NXZ endp

?_NV_isIdle@CharMovement@@QEBA_NXZ proc EXPORT
?_NV_isIdle@CharMovement@@QEBA_NXZ endp

; CharMovement::isIdle();
?isIdle@CharMovement@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+25*8]
?isIdle@CharMovement@@UEBA_NXZ endp

; CharMovement::isStandingOnSomething();
?isStandingOnSomething@CharMovement@@QEAAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+26*8]
?isStandingOnSomething@CharMovement@@QEAAAEBVhand@@XZ endp

?_NV_setDestination@CharMovement@@QEAAXPEAVBuilding@@W4UpdatePriority@@@Z proc EXPORT
?_NV_setDestination@CharMovement@@QEAAXPEAVBuilding@@W4UpdatePriority@@@Z endp

; CharMovement::setDestination(class Building *, enum UpdatePriority);
?setDestination@CharMovement@@UEAAXPEAVBuilding@@W4UpdatePriority@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+27*8]
?setDestination@CharMovement@@UEAAXPEAVBuilding@@W4UpdatePriority@@@Z endp

?_NV_setDestination@CharMovement@@QEAAXPEAVCharacter@@W4UpdatePriority@@@Z proc EXPORT
?_NV_setDestination@CharMovement@@QEAAXPEAVCharacter@@W4UpdatePriority@@@Z endp

; CharMovement::setDestination(class Character *, enum UpdatePriority);
?setDestination@CharMovement@@UEAAXPEAVCharacter@@W4UpdatePriority@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+28*8]
?setDestination@CharMovement@@UEAAXPEAVCharacter@@W4UpdatePriority@@@Z endp

?_NV_setDestination@CharMovement@@QEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z proc EXPORT
?_NV_setDestination@CharMovement@@QEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z endp

; CharMovement::setDestination(class RootObjectBase *, enum UpdatePriority);
?setDestination@CharMovement@@UEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+29*8]
?setDestination@CharMovement@@UEAAXPEAVRootObjectBase@@W4UpdatePriority@@@Z endp

?_NV_setDestination@CharMovement@@QEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z proc EXPORT
?_NV_setDestination@CharMovement@@QEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z endp

; CharMovement::setDestination(const class Ogre::Vector3 &, enum UpdatePriority, bool);
?setDestination@CharMovement@@UEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z proc EXPORT
jmp function_pointers[_CharMovement_base+30*8]
?setDestination@CharMovement@@UEAAXAEBVVector3@Ogre@@W4UpdatePriority@@_N@Z endp

?_NV_playerMoveOrderWhileInCombatMode@CharMovement@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_playerMoveOrderWhileInCombatMode@CharMovement@@QEAA_NAEBVVector3@Ogre@@@Z endp

; CharMovement::playerMoveOrderWhileInCombatMode(const class Ogre::Vector3 &);
?playerMoveOrderWhileInCombatMode@CharMovement@@UEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+31*8]
?playerMoveOrderWhileInCombatMode@CharMovement@@UEAA_NAEBVVector3@Ogre@@@Z endp

?_NV_halt@CharMovement@@QEAAXXZ proc EXPORT
?_NV_halt@CharMovement@@QEAAXXZ endp

; CharMovement::halt();
?halt@CharMovement@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+32*8]
?halt@CharMovement@@UEAAXXZ endp

; CharMovement::invalidatePath();
?invalidatePath@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+33*8]
?invalidatePath@CharMovement@@QEAAXXZ endp

?_NV_setPatrolInput@CharMovement@@QEAAXAEAVPatrolInfo@@@Z proc EXPORT
?_NV_setPatrolInput@CharMovement@@QEAAXAEAVPatrolInfo@@@Z endp

; CharMovement::setPatrolInput(class PatrolInfo &);
?setPatrolInput@CharMovement@@UEAAXAEAVPatrolInfo@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+34*8]
?setPatrolInput@CharMovement@@UEAAXAEAVPatrolInfo@@@Z endp

; CharMovement::movedBy(const class Ogre::Vector3 &);
?movedBy@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+35*8]
?movedBy@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::combatMovementOffensive(const class hand &, float, float, float, bool, float);
?combatMovementOffensive@CharMovement@@QEAAXAEBVhand@@MMM_NM@Z proc EXPORT
jmp function_pointers[_CharMovement_base+36*8]
?combatMovementOffensive@CharMovement@@QEAAXAEBVhand@@MMM_NM@Z endp

; CharMovement::isCombatMovementBlockedByCharacters();
?isCombatMovementBlockedByCharacters@CharMovement@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+37*8]
?isCombatMovementBlockedByCharacters@CharMovement@@QEAA_NXZ endp

; CharMovement::setLookatTarget(const class hand &);
?setLookatTarget@CharMovement@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+38*8]
?setLookatTarget@CharMovement@@QEAAXAEBVhand@@@Z endp

; CharMovement::destroy();
?destroy@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+39*8]
?destroy@CharMovement@@QEAAXXZ endp

; CharMovement::restore();
?restore@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+40*8]
?restore@CharMovement@@QEAAXXZ endp

; CharMovement::getAABB();
?getAABB@CharMovement@@QEBA?AUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+41*8]
?getAABB@CharMovement@@QEBA?AUAabb@Ogre@@XZ endp

; CharMovement::refreshClickHull();
?refreshClickHull@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+42*8]
?refreshClickHull@CharMovement@@QEAAXXZ endp

; CharMovement::teleportCollisionHull(const class Ogre::Vector3 &);
?teleportCollisionHull@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+43*8]
?teleportCollisionHull@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::getCurrentFloor();
?getCurrentFloor@CharMovement@@QEBAHXZ proc EXPORT
jmp function_pointers[_CharMovement_base+44*8]
?getCurrentFloor@CharMovement@@QEBAHXZ endp

; CharMovement::isIndoorsHideMeCheck();
?isIndoorsHideMeCheck@CharMovement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+45*8]
?isIndoorsHideMeCheck@CharMovement@@QEBA_NXZ endp

; CharMovement::isIndoors();
?isIndoors@CharMovement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+46*8]
?isIndoors@CharMovement@@QEBA_NXZ endp

?_NV_manualMovement@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_manualMovement@CharMovement@@QEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::manualMovement(const class Ogre::Vector3 &);
?manualMovement@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+47*8]
?manualMovement@CharMovement@@UEAAXAEBVVector3@Ogre@@@Z endp

; CharMovement::isInsideBuildingLoadedInterior();
?isInsideBuildingLoadedInterior@CharMovement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+48*8]
?isInsideBuildingLoadedInterior@CharMovement@@QEBA_NXZ endp

; CharMovement::hasClickHull();
?hasClickHull@CharMovement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+49*8]
?hasClickHull@CharMovement@@QEBA_NXZ endp

; CharMovement::isTrackingAnimationMode();
?isTrackingAnimationMode@CharMovement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+50*8]
?isTrackingAnimationMode@CharMovement@@QEBA_NXZ endp

; CharMovement::isWaypointMoveMode();
?isWaypointMoveMode@CharMovement@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+51*8]
?isWaypointMoveMode@CharMovement@@QEBA_NXZ endp

; CharMovement::setMovementMode(enum MovementMode);
?setMovementMode@CharMovement@@QEAAXW4MovementMode@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+52*8]
?setMovementMode@CharMovement@@QEAAXW4MovementMode@@@Z endp

; CharMovement::setDirectMovement(const class Ogre::Vector3 &, float);
?setDirectMovement@CharMovement@@QEAAXAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_CharMovement_base+53*8]
?setDirectMovement@CharMovement@@QEAAXAEBVVector3@Ogre@@M@Z endp

; CharMovement::getLastGroundTraceResultMT();
?getLastGroundTraceResultMT@CharMovement@@QEAA?AVphysHit@@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+54*8]
?getLastGroundTraceResultMT@CharMovement@@QEAA?AVphysHit@@XZ endp

; CharMovement::getCharacter();
?getCharacter@CharMovement@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_CharMovement_base+55*8]
?getCharacter@CharMovement@@QEAAPEAVCharacter@@XZ endp

?_NV_onShapeHit@CharMovement@@QEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z proc EXPORT
?_NV_onShapeHit@CharMovement@@QEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z endp

; CharMovement::onShapeHit(const struct NxControllerShapeHit &);
?onShapeHit@CharMovement@@UEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+56*8]
?onShapeHit@CharMovement@@UEAA?AW4NxControllerAction@@AEBUNxControllerShapeHit@@@Z endp

?_NV_onControllerHit@CharMovement@@QEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z proc EXPORT
?_NV_onControllerHit@CharMovement@@QEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z endp

; CharMovement::onControllerHit(const struct NxControllersHit &);
?onControllerHit@CharMovement@@UEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z proc EXPORT
jmp function_pointers[_CharMovement_base+57*8]
?onControllerHit@CharMovement@@UEAA?AW4NxControllerAction@@AEBUNxControllersHit@@@Z endp

; CharMovement::toGround();
?toGround@CharMovement@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CharMovement_base+58*8]
?toGround@CharMovement@@QEAA_NXZ endp

; CharMovement::updateGroundMaterial();
?updateGroundMaterial@CharMovement@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharMovement_base+59*8]
?updateGroundMaterial@CharMovement@@QEAAXXZ endp

; CharMovement::getCombatMoveSpeedMult();
?getCombatMoveSpeedMult@CharMovement@@QEAAMXZ proc EXPORT
jmp function_pointers[_CharMovement_base+60*8]
?getCombatMoveSpeedMult@CharMovement@@QEAAMXZ endp
