
?_CONSTRUCTOR@RagdollMsg@Character@@QEAAPEAV12@_NW4Enum@RagdollPart@@@Z proc EXPORT
?_CONSTRUCTOR@RagdollMsg@Character@@QEAAPEAV12@_NW4Enum@RagdollPart@@@Z endp

; Character::RagdollMsg::RagdollMsg(bool, enum RagdollPart::Enum);
??0RagdollMsg@Character@@QEAA@_NW4Enum@RagdollPart@@@Z proc EXPORT
jmp function_pointers[_Character_RagdollMsg_base+0*8]
??0RagdollMsg@Character@@QEAA@_NW4Enum@RagdollPart@@@Z endp

; Character::RagdollMsg::operator==(const struct Character::RagdollMsg &);
??8RagdollMsg@Character@@QEBA_NAEBU01@@Z proc EXPORT
jmp function_pointers[_Character_RagdollMsg_base+1*8]
??8RagdollMsg@Character@@QEBA_NAEBU01@@Z endp
