
?_CONSTRUCTOR@Stat@CharacterStatsWindow@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@Stat@CharacterStatsWindow@@QEAAPEAV12@AEBV12@@Z endp

; CharacterStatsWindow::Stat::Stat(const class CharacterStatsWindow::Stat &);
??0Stat@CharacterStatsWindow@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_Stat_base+0*8]
??0Stat@CharacterStatsWindow@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@Stat@CharacterStatsWindow@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Stat@CharacterStatsWindow@@QEAAPEAV12@XZ endp

; CharacterStatsWindow::Stat::Stat();
??0Stat@CharacterStatsWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_Stat_base+1*8]
??0Stat@CharacterStatsWindow@@QEAA@XZ endp

?_CONSTRUCTOR@Stat@CharacterStatsWindow@@QEAAPEAV12@W4StatsEnumerated@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N1@Z proc EXPORT
?_CONSTRUCTOR@Stat@CharacterStatsWindow@@QEAAPEAV12@W4StatsEnumerated@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N1@Z endp

; CharacterStatsWindow::Stat::Stat(enum StatsEnumerated, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0Stat@CharacterStatsWindow@@QEAA@W4StatsEnumerated@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N1@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_Stat_base+2*8]
??0Stat@CharacterStatsWindow@@QEAA@W4StatsEnumerated@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N1@Z endp

?_DESTRUCTOR@Stat@CharacterStatsWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Stat@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::Stat::~Stat();
??1Stat@CharacterStatsWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_Stat_base+3*8]
??1Stat@CharacterStatsWindow@@QEAA@XZ endp

; CharacterStatsWindow::Stat::operator=(const class CharacterStatsWindow::Stat &);
??4Stat@CharacterStatsWindow@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_Stat_base+4*8]
??4Stat@CharacterStatsWindow@@QEAAAEAV01@AEBV01@@Z endp
