
?_CONSTRUCTOR@WhoSeesMe@Character@@QEAAPEAV12@NVYesNoMaybe@@M@Z proc EXPORT
?_CONSTRUCTOR@WhoSeesMe@Character@@QEAAPEAV12@NVYesNoMaybe@@M@Z endp

; Character::WhoSeesMe::WhoSeesMe(double, class YesNoMaybe, float);
??0WhoSeesMe@Character@@QEAA@NVYesNoMaybe@@M@Z proc EXPORT
jmp function_pointers[_Character_WhoSeesMe_base+0*8]
??0WhoSeesMe@Character@@QEAA@NVYesNoMaybe@@M@Z endp

?_CONSTRUCTOR@WhoSeesMe@Character@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@WhoSeesMe@Character@@QEAAPEAV12@XZ endp

; Character::WhoSeesMe::WhoSeesMe();
??0WhoSeesMe@Character@@QEAA@XZ proc EXPORT
jmp function_pointers[_Character_WhoSeesMe_base+1*8]
??0WhoSeesMe@Character@@QEAA@XZ endp
