
?_CONSTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAPEAV12@AEBV12@@Z endp

; CharacterStatsWindow::StatGroup::StatGroup(const class CharacterStatsWindow::StatGroup &);
??0StatGroup@CharacterStatsWindow@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_StatGroup_base+0*8]
??0StatGroup@CharacterStatsWindow@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAPEAV12@W4Group@12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAPEAV12@W4Group@12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharacterStatsWindow::StatGroup::StatGroup(enum CharacterStatsWindow::StatGroup::Group, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0StatGroup@CharacterStatsWindow@@QEAA@W4Group@01@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_StatGroup_base+1*8]
??0StatGroup@CharacterStatsWindow@@QEAA@W4Group@01@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAPEAV12@XZ endp

; CharacterStatsWindow::StatGroup::StatGroup();
??0StatGroup@CharacterStatsWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_StatGroup_base+2*8]
??0StatGroup@CharacterStatsWindow@@QEAA@XZ endp

?_DESTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@StatGroup@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::StatGroup::~StatGroup();
??1StatGroup@CharacterStatsWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_StatGroup_base+3*8]
??1StatGroup@CharacterStatsWindow@@QEAA@XZ endp
