
?_CONSTRUCTOR@CharacterStatsWindow@@QEAAPEAV1@AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@CharacterStatsWindow@@QEAAPEAV1@AEBVhand@@@Z endp

; CharacterStatsWindow::CharacterStatsWindow(const class hand &);
??0CharacterStatsWindow@@QEAA@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+0*8]
??0CharacterStatsWindow@@QEAA@AEBVhand@@@Z endp

?_DESTRUCTOR@CharacterStatsWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::~CharacterStatsWindow();
??1CharacterStatsWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+1*8]
??1CharacterStatsWindow@@UEAA@XZ endp

?_NV_clear@CharacterStatsWindow@@QEAAXXZ proc EXPORT
?_NV_clear@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::clear();
?clear@CharacterStatsWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+2*8]
?clear@CharacterStatsWindow@@UEAAXXZ endp

?_NV_create@CharacterStatsWindow@@QEAAXXZ proc EXPORT
?_NV_create@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::create();
?create@CharacterStatsWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+3*8]
?create@CharacterStatsWindow@@UEAAXXZ endp

?_NV_update@CharacterStatsWindow@@QEAAXXZ proc EXPORT
?_NV_update@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::update();
?update@CharacterStatsWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+4*8]
?update@CharacterStatsWindow@@UEAAXXZ endp

?_NV_show@CharacterStatsWindow@@QEAAX_N@Z proc EXPORT
?_NV_show@CharacterStatsWindow@@QEAAX_N@Z endp

; CharacterStatsWindow::show(bool);
?show@CharacterStatsWindow@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+5*8]
?show@CharacterStatsWindow@@UEAAX_N@Z endp

?_NV_isVisible@CharacterStatsWindow@@QEBA_NXZ proc EXPORT
?_NV_isVisible@CharacterStatsWindow@@QEBA_NXZ endp

; CharacterStatsWindow::isVisible();
?isVisible@CharacterStatsWindow@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+6*8]
?isVisible@CharacterStatsWindow@@UEBA_NXZ endp

?_NV_autoChangeSelectedObject@CharacterStatsWindow@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_autoChangeSelectedObject@CharacterStatsWindow@@QEAAXAEBVhand@@@Z endp

; CharacterStatsWindow::autoChangeSelectedObject(const class hand &);
?autoChangeSelectedObject@CharacterStatsWindow@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+7*8]
?autoChangeSelectedObject@CharacterStatsWindow@@UEAAXAEBVhand@@@Z endp

; CharacterStatsWindow::setAutoUpdateMode(bool);
?setAutoUpdateMode@CharacterStatsWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+8*8]
?setAutoUpdateMode@CharacterStatsWindow@@QEAAX_N@Z endp

; CharacterStatsWindow::setupStats();
?setupStats@CharacterStatsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+9*8]
?setupStats@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::updateStats();
?updateStats@CharacterStatsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+10*8]
?updateStats@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::clearDesctiption();
?clearDesctiption@CharacterStatsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+11*8]
?clearDesctiption@CharacterStatsWindow@@QEAAXXZ endp

; CharacterStatsWindow::sumStats();
?sumStats@CharacterStatsWindow@@QEBAHXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+12*8]
?sumStats@CharacterStatsWindow@@QEBAHXZ endp

; CharacterStatsWindow::closeWindow(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeWindow@CharacterStatsWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+13*8]
?closeWindow@CharacterStatsWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharacterStatsWindow::statMouseOver(class MyGUI::Widget *, int, int);
?statMouseOver@CharacterStatsWindow@@QEAAXPEAVWidget@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+14*8]
?statMouseOver@CharacterStatsWindow@@QEAAXPEAVWidget@MyGUI@@HH@Z endp

; CharacterStatsWindow::getStatsPanel(enum CharacterStatsWindow::StatGroup::Group);
?getStatsPanel@CharacterStatsWindow@@QEAAPEAVDatapanelGUI@@W4Group@StatGroup@1@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+15*8]
?getStatsPanel@CharacterStatsWindow@@QEAAPEAVDatapanelGUI@@W4Group@StatGroup@1@@Z endp

; CharacterStatsWindow::addStat(enum StatsEnumerated, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addStat@CharacterStatsWindow@@SAXW4StatsEnumerated@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N1@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+16*8]
?addStat@CharacterStatsWindow@@SAXW4StatsEnumerated@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N1@Z endp

; CharacterStatsWindow::getStat(enum StatsEnumerated);
?getStat@CharacterStatsWindow@@SAPEAVStat@1@W4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+17*8]
?getStat@CharacterStatsWindow@@SAPEAVStat@1@W4StatsEnumerated@@@Z endp

; CharacterStatsWindow::getStatById(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getStatById@CharacterStatsWindow@@SAPEAVStat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+18*8]
?getStatById@CharacterStatsWindow@@SAPEAVStat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CharacterStatsWindow::BuildStats();
?BuildStats@CharacterStatsWindow@@SAXXZ proc EXPORT
jmp function_pointers[_CharacterStatsWindow_base+19*8]
?BuildStats@CharacterStatsWindow@@SAXXZ endp
