
?_CONSTRUCTOR@CharBody@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@CharBody@@QEAAPEAV1@XZ endp

; CharBody::CharBody();
??0CharBody@@QEAA@XZ proc EXPORT
jmp function_pointers[_CharBody_base+0*8]
??0CharBody@@QEAA@XZ endp

?_DESTRUCTOR@CharBody@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CharBody@@QEAAXXZ endp

; CharBody::~CharBody();
??1CharBody@@UEAA@XZ proc EXPORT
jmp function_pointers[_CharBody_base+1*8]
??1CharBody@@UEAA@XZ endp

; CharBody::create(class CharMovement *, class AI *, class AnimationClass *, class Character *, class CharStats *);
?create@CharBody@@QEAAXPEAVCharMovement@@PEAVAI@@PEAVAnimationClass@@PEAVCharacter@@PEAVCharStats@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+2*8]
?create@CharBody@@QEAAXPEAVCharMovement@@PEAVAI@@PEAVAnimationClass@@PEAVCharacter@@PEAVCharStats@@@Z endp

?_NV_update@CharBody@@QEAAXM@Z proc EXPORT
?_NV_update@CharBody@@QEAAXM@Z endp

; CharBody::update(float);
?update@CharBody@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CharBody_base+3*8]
?update@CharBody@@UEAAXM@Z endp

; CharBody::periodicUpdate(float);
?periodicUpdate@CharBody@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CharBody_base+4*8]
?periodicUpdate@CharBody@@QEAAXM@Z endp

?_NV_setCurrentAction@CharBody@@QEAA_NW4TaskType@@PEAVRootObject@@@Z proc EXPORT
?_NV_setCurrentAction@CharBody@@QEAA_NW4TaskType@@PEAVRootObject@@@Z endp

; CharBody::setCurrentAction(enum TaskType, class RootObject *);
?setCurrentAction@CharBody@@UEAA_NW4TaskType@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+5*8]
?setCurrentAction@CharBody@@UEAA_NW4TaskType@@PEAVRootObject@@@Z endp

?_NV_setCurrentAction@CharBody@@QEAA_NPEAVTasker@@@Z proc EXPORT
?_NV_setCurrentAction@CharBody@@QEAA_NPEAVTasker@@@Z endp

; CharBody::setCurrentAction(class Tasker *);
?setCurrentAction@CharBody@@UEAA_NPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+6*8]
?setCurrentAction@CharBody@@UEAA_NPEAVTasker@@@Z endp

; CharBody::notifyBodyTaskComplete();
?notifyBodyTaskComplete@CharBody@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharBody_base+7*8]
?notifyBodyTaskComplete@CharBody@@QEAAXXZ endp

?_NV_notifyTaskComplete@CharBody@@QEAAXXZ proc EXPORT
?_NV_notifyTaskComplete@CharBody@@QEAAXXZ endp

; CharBody::notifyTaskComplete();
?notifyTaskComplete@CharBody@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharBody_base+8*8]
?notifyTaskComplete@CharBody@@UEAAXXZ endp

?_NV_notifyTaskImpossible@CharBody@@QEAAXXZ proc EXPORT
?_NV_notifyTaskImpossible@CharBody@@QEAAXXZ endp

; CharBody::notifyTaskImpossible();
?notifyTaskImpossible@CharBody@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharBody_base+9*8]
?notifyTaskImpossible@CharBody@@UEAAXXZ endp

?_NV_notifyPathImpossible@CharBody@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_notifyPathImpossible@CharBody@@QEAAXAEBVhand@@@Z endp

; CharBody::notifyPathImpossible(const class hand &);
?notifyPathImpossible@CharBody@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+10*8]
?notifyPathImpossible@CharBody@@UEAAXAEBVhand@@@Z endp

; CharBody::getCombatClass();
?getCombatClass@CharBody@@QEBAPEAVCombatClass@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+11*8]
?getCombatClass@CharBody@@QEBAPEAVCombatClass@@XZ endp

; CharBody::isCrouched();
?isCrouched@CharBody@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharBody_base+12*8]
?isCrouched@CharBody@@QEBA_NXZ endp

?_NV_getPosition@CharBody@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@CharBody@@QEAA?AVVector3@Ogre@@XZ endp

; CharBody::getPosition();
?getPosition@CharBody@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+13*8]
?getPosition@CharBody@@UEAA?AVVector3@Ogre@@XZ endp

; CharBody::getName();
?getName@CharBody@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+14*8]
?getName@CharBody@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_isCharacter@CharBody@@QEBA_NXZ proc EXPORT
?_NV_isCharacter@CharBody@@QEBA_NXZ endp

; CharBody::isCharacter();
?isCharacter@CharBody@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CharBody_base+15*8]
?isCharacter@CharBody@@UEBA_NXZ endp

?_NV_getCharacter@CharBody@@QEAAPEAVCharacter@@XZ proc EXPORT
?_NV_getCharacter@CharBody@@QEAAPEAVCharacter@@XZ endp

; CharBody::getCharacter();
?getCharacter@CharBody@@UEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+16*8]
?getCharacter@CharBody@@UEAAPEAVCharacter@@XZ endp

?_NV_getCharBody@CharBody@@QEAAPEAV1@XZ proc EXPORT
?_NV_getCharBody@CharBody@@QEAAPEAV1@XZ endp

; CharBody::getCharBody();
?getCharBody@CharBody@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_CharBody_base+17*8]
?getCharBody@CharBody@@UEAAPEAV1@XZ endp

; CharBody::getUpFromRagdoll(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getUpFromRagdoll@CharBody@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+18*8]
?getUpFromRagdoll@CharBody@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getPlatoon@CharBody@@QEBAPEAVPlatoon@@XZ proc EXPORT
?_NV_getPlatoon@CharBody@@QEBAPEAVPlatoon@@XZ endp

; CharBody::getPlatoon();
?getPlatoon@CharBody@@UEBAPEAVPlatoon@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+19*8]
?getPlatoon@CharBody@@UEBAPEAVPlatoon@@XZ endp

; CharBody::getCurrentAction();
?getCurrentAction@CharBody@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+20*8]
?getCurrentAction@CharBody@@QEAAPEAVTasker@@XZ endp

; CharBody::getCurrentActionOrMessage();
?getCurrentActionOrMessage@CharBody@@QEAAPEAVTasker@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+21*8]
?getCurrentActionOrMessage@CharBody@@QEAAPEAVTasker@@XZ endp

; CharBody::endAction();
?endAction@CharBody@@QEAAXXZ proc EXPORT
jmp function_pointers[_CharBody_base+22*8]
?endAction@CharBody@@QEAAXXZ endp

; CharBody::isIdle();
?isIdle@CharBody@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CharBody_base+23*8]
?isIdle@CharBody@@QEBA_NXZ endp

; CharBody::getHandle();
?getHandle@CharBody@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+24*8]
?getHandle@CharBody@@QEBA?AVhand@@XZ endp

; CharBody::getFaction();
?getFaction@CharBody@@QEBAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+25*8]
?getFaction@CharBody@@QEBAPEAVFaction@@XZ endp

; CharBody::_move(class RootObjectBase *, const class Ogre::Vector3 &);
?_move@CharBody@@QEAAXPEAVRootObjectBase@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+26*8]
?_move@CharBody@@QEAAXPEAVRootObjectBase@@AEBVVector3@Ogre@@@Z endp

; CharBody::_patrol(class Tasker *, int, class Ogre::Vector3, class PatrolInfo *, class AITaskSytem *, class TownBase *);
?_patrol@CharBody@@QEAAXPEAVTasker@@HVVector3@Ogre@@PEAVPatrolInfo@@PEAVAITaskSytem@@PEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_CharBody_base+27*8]
?_patrol@CharBody@@QEAAXPEAVTasker@@HVVector3@Ogre@@PEAVPatrolInfo@@PEAVAITaskSytem@@PEAVTownBase@@@Z endp

; CharBody::getCurrentSubject();
?getCurrentSubject@CharBody@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_CharBody_base+28*8]
?getCurrentSubject@CharBody@@QEBA?AVhand@@XZ endp

?_NV__endAction@CharBody@@QEAAXXZ proc EXPORT
?_NV__endAction@CharBody@@QEAAXXZ endp

; CharBody::_endAction();
?_endAction@CharBody@@UEAAXXZ proc EXPORT
jmp function_pointers[_CharBody_base+29*8]
?_endAction@CharBody@@UEAAXXZ endp
