
?_DESTRUCTOR@AttachedArrowManager@Character@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AttachedArrowManager@Character@@QEAAXXZ endp

; Character::AttachedArrowManager::~AttachedArrowManager();
??1AttachedArrowManager@Character@@QEAA@XZ proc EXPORT
jmp function_pointers[_Character_AttachedArrowManager_base+0*8]
??1AttachedArrowManager@Character@@QEAA@XZ endp

; Character::AttachedArrowManager::clearAll();
?clearAll@AttachedArrowManager@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_AttachedArrowManager_base+1*8]
?clearAll@AttachedArrowManager@Character@@QEAAXXZ endp

; Character::AttachedArrowManager::updateStart();
?updateStart@AttachedArrowManager@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_AttachedArrowManager_base+2*8]
?updateStart@AttachedArrowManager@Character@@QEAAXXZ endp

; Character::AttachedArrowManager::addArrow(class Ogre::Vector3 &, class Ogre::Vector3 &, int);
?addArrow@AttachedArrowManager@Character@@QEAAXAEAVVector3@Ogre@@0H@Z proc EXPORT
jmp function_pointers[_Character_AttachedArrowManager_base+3*8]
?addArrow@AttachedArrowManager@Character@@QEAAXAEAVVector3@Ogre@@0H@Z endp

; Character::AttachedArrowManager::updateEnd();
?updateEnd@AttachedArrowManager@Character@@QEAAXXZ proc EXPORT
jmp function_pointers[_Character_AttachedArrowManager_base+4*8]
?updateEnd@AttachedArrowManager@Character@@QEAAXXZ endp

?_CONSTRUCTOR@AttachedArrowManager@Character@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@AttachedArrowManager@Character@@QEAAPEAV12@XZ endp

; Character::AttachedArrowManager::AttachedArrowManager();
??0AttachedArrowManager@Character@@QEAA@XZ proc EXPORT
jmp function_pointers[_Character_AttachedArrowManager_base+5*8]
??0AttachedArrowManager@Character@@QEAA@XZ endp
