
?_CONSTRUCTOR@EffectData@CombatClass@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@EffectData@CombatClass@@QEAAPEAV12@XZ endp

; CombatClass::EffectData::EffectData();
??0EffectData@CombatClass@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatClass_EffectData_base+0*8]
??0EffectData@CombatClass@@QEAA@XZ endp

?_DESTRUCTOR@EffectData@CombatClass@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@EffectData@CombatClass@@QEAAXXZ endp

; CombatClass::EffectData::~EffectData();
??1EffectData@CombatClass@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatClass_EffectData_base+1*8]
??1EffectData@CombatClass@@QEAA@XZ endp

; CombatClass::EffectData::operator=(const struct CombatClass::EffectData &);
??4EffectData@CombatClass@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_CombatClass_EffectData_base+2*8]
??4EffectData@CombatClass@@QEAAAEAU01@AEBU01@@Z endp
