
?_CONSTRUCTOR@AttackSlotManager@CombatClass@@QEAAPEAV12@PEAVCharacter@@PEAV2@@Z proc EXPORT
?_CONSTRUCTOR@AttackSlotManager@CombatClass@@QEAAPEAV12@PEAVCharacter@@PEAV2@@Z endp

; CombatClass::AttackSlotManager::AttackSlotManager(class Character *, class CombatClass *);
??0AttackSlotManager@CombatClass@@QEAA@PEAVCharacter@@PEAV1@@Z proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+0*8]
??0AttackSlotManager@CombatClass@@QEAA@PEAVCharacter@@PEAV1@@Z endp

; CombatClass::AttackSlotManager::hasFreeAttackSlot();
?hasFreeAttackSlot@AttackSlotManager@CombatClass@@QEBA_NXZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+1*8]
?hasFreeAttackSlot@AttackSlotManager@CombatClass@@QEBA_NXZ endp

; CombatClass::AttackSlotManager::freeSlotH(const class hand &);
?freeSlotH@AttackSlotManager@CombatClass@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+2*8]
?freeSlotH@AttackSlotManager@CombatClass@@QEAAXAEBVhand@@@Z endp

; CombatClass::AttackSlotManager::freeAllSlotsH();
?freeAllSlotsH@AttackSlotManager@CombatClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+3*8]
?freeAllSlotsH@AttackSlotManager@CombatClass@@QEAAXXZ endp

; CombatClass::AttackSlotManager::addToSlotH(const class hand &);
?addToSlotH@AttackSlotManager@CombatClass@@QEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+4*8]
?addToSlotH@AttackSlotManager@CombatClass@@QEAA_NAEBVhand@@@Z endp

; CombatClass::AttackSlotManager::periodicUpdate(float);
?periodicUpdate@AttackSlotManager@CombatClass@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+5*8]
?periodicUpdate@AttackSlotManager@CombatClass@@QEAAXM@Z endp

; CombatClass::AttackSlotManager::update();
?update@AttackSlotManager@CombatClass@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+6*8]
?update@AttackSlotManager@CombatClass@@QEAAXXZ endp

; CombatClass::AttackSlotManager::getNumAttackSlots();
?getNumAttackSlots@AttackSlotManager@CombatClass@@QEBAHXZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+7*8]
?getNumAttackSlots@AttackSlotManager@CombatClass@@QEBAHXZ endp

; CombatClass::AttackSlotManager::getMaxPossibleAttackSlots();
?getMaxPossibleAttackSlots@AttackSlotManager@CombatClass@@QEBAHXZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+8*8]
?getMaxPossibleAttackSlots@AttackSlotManager@CombatClass@@QEBAHXZ endp

?_DESTRUCTOR@AttackSlotManager@CombatClass@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@AttackSlotManager@CombatClass@@QEAAXXZ endp

; CombatClass::AttackSlotManager::~AttackSlotManager();
??1AttackSlotManager@CombatClass@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_base+9*8]
??1AttackSlotManager@CombatClass@@QEAA@XZ endp
