
?_CONSTRUCTOR@CombatMovementController@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@CombatMovementController@@QEAAPEAV1@XZ endp

; CombatMovementController::CombatMovementController();
??0CombatMovementController@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatMovementController_base+0*8]
??0CombatMovementController@@QEAA@XZ endp

; CombatMovementController::collisionUpdate(float);
?collisionUpdate@CombatMovementController@@QEAAXM@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+1*8]
?collisionUpdate@CombatMovementController@@QEAAXM@Z endp

; CombatMovementController::chasingModeCheck(class Character *);
?chasingModeCheck@CombatMovementController@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+2*8]
?chasingModeCheck@CombatMovementController@@QEAA_NPEAVCharacter@@@Z endp

; CombatMovementController::create(class FlockingTools *, class CharMovement *, class CharStats *, bool);
?create@CombatMovementController@@QEAAXPEAVFlockingTools@@PEAVCharMovement@@PEAVCharStats@@_N@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+3*8]
?create@CombatMovementController@@QEAAXPEAVFlockingTools@@PEAVCharMovement@@PEAVCharStats@@_N@Z endp

; CombatMovementController::areTherePeopleInMyWay();
?areTherePeopleInMyWay@CombatMovementController@@QEAA_NXZ proc EXPORT
jmp function_pointers[_CombatMovementController_base+4*8]
?areTherePeopleInMyWay@CombatMovementController@@QEAA_NXZ endp

; CombatMovementController::addACharacterObstruction(class Character *);
?addACharacterObstruction@CombatMovementController@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+5*8]
?addACharacterObstruction@CombatMovementController@@QEAAXPEAVCharacter@@@Z endp

; CombatMovementController::setupCombatMovementVariables(class Character *);
?setupCombatMovementVariables@CombatMovementController@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+6*8]
?setupCombatMovementVariables@CombatMovementController@@QEAAXPEAVCharacter@@@Z endp

; CombatMovementController::combatMovementUpdate(float, const class Ogre::Vector3 &, const class Ogre::Vector3 &, bool, class Ogre::Vector3 &, class Ogre::Vector3 &, bool, enum swordStateEnum, float);
?combatMovementUpdate@CombatMovementController@@QEAAXMAEBVVector3@Ogre@@0_NAEAV23@21W4swordStateEnum@@M@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+7*8]
?combatMovementUpdate@CombatMovementController@@QEAAXMAEBVVector3@Ogre@@0_NAEAV23@21W4swordStateEnum@@M@Z endp

; CombatMovementController::combatMovementUpdate_crippleMode(float, const class Ogre::Vector3 &, const class Ogre::Vector3 &, bool, class Ogre::Vector3 &, class Ogre::Vector3 &, bool, enum swordStateEnum, float);
?combatMovementUpdate_crippleMode@CombatMovementController@@QEAAXMAEBVVector3@Ogre@@0_NAEAV23@21W4swordStateEnum@@M@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+8*8]
?combatMovementUpdate_crippleMode@CombatMovementController@@QEAAXMAEBVVector3@Ogre@@0_NAEAV23@21W4swordStateEnum@@M@Z endp

; CombatMovementController::getUrgentVelocities(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?getUrgentVelocities@CombatMovementController@@QEAA?AVVector3@Ogre@@AEBV23@0@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+9*8]
?getUrgentVelocities@CombatMovementController@@QEAA?AVVector3@Ogre@@AEBV23@0@Z endp

; CombatMovementController::checkWeDontCollideWithCharacters(const class Ogre::Vector3 &, class Ogre::Vector3 &);
?checkWeDontCollideWithCharacters@CombatMovementController@@QEAAXAEBVVector3@Ogre@@AEAV23@@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+10*8]
?checkWeDontCollideWithCharacters@CombatMovementController@@QEAAXAEBVVector3@Ogre@@AEAV23@@Z endp

; CombatMovementController::checkCharacterCollision(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?checkCharacterCollision@CombatMovementController@@QEBA_NAEBVVector3@Ogre@@0@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+11*8]
?checkCharacterCollision@CombatMovementController@@QEBA_NAEBVVector3@Ogre@@0@Z endp

; CombatMovementController::setForcedWP(const class Ogre::Vector3 &);
?setForcedWP@CombatMovementController@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+12*8]
?setForcedWP@CombatMovementController@@QEAAXAEBVVector3@Ogre@@@Z endp

; CombatMovementController::getGUIData(class DatapanelGUI *, int);
?getGUIData@CombatMovementController@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+13*8]
?getGUIData@CombatMovementController@@QEAAXPEAVDatapanelGUI@@H@Z endp

; CombatMovementController::combatMovementOffensive(const class hand &, float, float, float, bool, float);
?combatMovementOffensive@CombatMovementController@@QEAAXAEBVhand@@MMM_NM@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+14*8]
?combatMovementOffensive@CombatMovementController@@QEAAXAEBVhand@@MMM_NM@Z endp

; CombatMovementController::disable();
?disable@CombatMovementController@@QEAAXXZ proc EXPORT
jmp function_pointers[_CombatMovementController_base+15*8]
?disable@CombatMovementController@@QEAAXXZ endp

; CombatMovementController::combatMovementAnimationUpdate(const class Ogre::Vector3 &, const class Ogre::Vector3 &, class AnimationClass *, bool);
?combatMovementAnimationUpdate@CombatMovementController@@QEAAXAEBVVector3@Ogre@@0PEAVAnimationClass@@_N@Z proc EXPORT
jmp function_pointers[_CombatMovementController_base+16*8]
?combatMovementAnimationUpdate@CombatMovementController@@QEAAXAEBVVector3@Ogre@@0PEAVAnimationClass@@_N@Z endp

?_DESTRUCTOR@CombatMovementController@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CombatMovementController@@QEAAXXZ endp

; CombatMovementController::~CombatMovementController();
??1CombatMovementController@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatMovementController_base+17*8]
??1CombatMovementController@@QEAA@XZ endp
