
?_CONSTRUCTOR@SlotData@AttackSlotManager@CombatClass@@QEAAPEAV123@XZ proc EXPORT
?_CONSTRUCTOR@SlotData@AttackSlotManager@CombatClass@@QEAAPEAV123@XZ endp

; CombatClass::AttackSlotManager::SlotData::SlotData();
??0SlotData@AttackSlotManager@CombatClass@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_SlotData_base+0*8]
??0SlotData@AttackSlotManager@CombatClass@@QEAA@XZ endp

?_DESTRUCTOR@SlotData@AttackSlotManager@CombatClass@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SlotData@AttackSlotManager@CombatClass@@QEAAXXZ endp

; CombatClass::AttackSlotManager::SlotData::~SlotData();
??1SlotData@AttackSlotManager@CombatClass@@QEAA@XZ proc EXPORT
jmp function_pointers[_CombatClass_AttackSlotManager_SlotData_base+1*8]
??1SlotData@AttackSlotManager@CombatClass@@QEAA@XZ endp
