
?_CONSTRUCTOR@CombatTechniqueData@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@CombatTechniqueData@@QEAAPEAV1@PEAVGameData@@@Z endp

; CombatTechniqueData::CombatTechniqueData(class GameData *);
??0CombatTechniqueData@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CombatTechniqueData_base+0*8]
??0CombatTechniqueData@@QEAA@PEAVGameData@@@Z endp

; CombatTechniqueData::hasSkillType(enum WeaponCategory);
?hasSkillType@CombatTechniqueData@@QEBA_NW4WeaponCategory@@@Z proc EXPORT
jmp function_pointers[_CombatTechniqueData_base+1*8]
?hasSkillType@CombatTechniqueData@@QEBA_NW4WeaponCategory@@@Z endp

; CombatTechniqueData::numImpactPoints();
?numImpactPoints@CombatTechniqueData@@QEBAHXZ proc EXPORT
jmp function_pointers[_CombatTechniqueData_base+2*8]
?numImpactPoints@CombatTechniqueData@@QEBAHXZ endp

; CombatTechniqueData::impactPoint(int);
?impactPoint@CombatTechniqueData@@QEAAPEAVImpactPoint@1@H@Z proc EXPORT
jmp function_pointers[_CombatTechniqueData_base+3*8]
?impactPoint@CombatTechniqueData@@QEAAPEAVImpactPoint@1@H@Z endp
