
?_DESTRUCTOR@ContainerItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ContainerItem@@QEAAXXZ endp

; ContainerItem::~ContainerItem();
??1ContainerItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_ContainerItem_base+0*8]
??1ContainerItem@@UEAA@XZ endp

?_NV_getClassType@ContainerItem@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@ContainerItem@@QEBA?AW4itemType@@XZ endp

; ContainerItem::getClassType();
?getClassType@ContainerItem@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_ContainerItem_base+1*8]
?getClassType@ContainerItem@@UEBA?AW4itemType@@XZ endp

?_NV_canEquip@ContainerItem@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_canEquip@ContainerItem@@QEAA_NPEAVGameData@@@Z endp

; ContainerItem::canEquip(class GameData *);
?canEquip@ContainerItem@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+2*8]
?canEquip@ContainerItem@@UEAA_NPEAVGameData@@@Z endp

?_NV_equipItem@ContainerItem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_equipItem@ContainerItem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; ContainerItem::equipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?equipItem@ContainerItem@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+3*8]
?equipItem@ContainerItem@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_unequipItem@ContainerItem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_unequipItem@ContainerItem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; ContainerItem::unequipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?unequipItem@ContainerItem@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+4*8]
?unequipItem@ContainerItem@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_dropItem@ContainerItem@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_dropItem@ContainerItem@@QEAAXPEAVRootObject@@@Z endp

; ContainerItem::dropItem(class RootObject *);
?dropItem@ContainerItem@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+5*8]
?dropItem@ContainerItem@@UEAAXPEAVRootObject@@@Z endp

?_NV_takeMoney@ContainerItem@@QEAA_NH@Z proc EXPORT
?_NV_takeMoney@ContainerItem@@QEAA_NH@Z endp

; ContainerItem::takeMoney(int);
?takeMoney@ContainerItem@@UEAA_NH@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+6*8]
?takeMoney@ContainerItem@@UEAA_NH@Z endp

?_NV_getMoney@ContainerItem@@QEBAHXZ proc EXPORT
?_NV_getMoney@ContainerItem@@QEBAHXZ endp

; ContainerItem::getMoney();
?getMoney@ContainerItem@@UEBAHXZ proc EXPORT
jmp function_pointers[_ContainerItem_base+7*8]
?getMoney@ContainerItem@@UEBAHXZ endp

; ContainerItem::doubleCheckHandle();
?doubleCheckHandle@ContainerItem@@QEAAXXZ proc EXPORT
jmp function_pointers[_ContainerItem_base+8*8]
?doubleCheckHandle@ContainerItem@@QEAAXXZ endp

?_NV_getPosition@ContainerItem@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@ContainerItem@@QEAA?AVVector3@Ogre@@XZ endp

; ContainerItem::getPosition();
?getPosition@ContainerItem@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_ContainerItem_base+9*8]
?getPosition@ContainerItem@@UEAA?AVVector3@Ogre@@XZ endp

?_NV_getInventory@ContainerItem@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@ContainerItem@@QEBAPEAVInventory@@XZ endp

; ContainerItem::getInventory();
?getInventory@ContainerItem@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_ContainerItem_base+10*8]
?getInventory@ContainerItem@@UEBAPEAVInventory@@XZ endp

?_NV_createInventoryLayout@ContainerItem@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@ContainerItem@@QEAAPEAVInventoryLayout@@XZ endp

; ContainerItem::createInventoryLayout();
?createInventoryLayout@ContainerItem@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_ContainerItem_base+11*8]
?createInventoryLayout@ContainerItem@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_getTooltipData1@ContainerItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@ContainerItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; ContainerItem::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@ContainerItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+12*8]
?getTooltipData1@ContainerItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@ContainerItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@ContainerItem@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; ContainerItem::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@ContainerItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+13*8]
?getTooltipData2@ContainerItem@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV__serialise@ContainerItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@ContainerItem@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; ContainerItem::_serialise(class GameDataContainer *, enum itemType);
?_serialise@ContainerItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+14*8]
?_serialise@ContainerItem@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_NV__loadFromSerialise@ContainerItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@ContainerItem@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; ContainerItem::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@ContainerItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+15*8]
?_loadFromSerialise@ContainerItem@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_serialise@ContainerItem@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@ContainerItem@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; ContainerItem::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@ContainerItem@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+16*8]
?serialise@ContainerItem@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@ContainerItem@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@ContainerItem@@QEAAXPEAVGameSaveState@@@Z endp

; ContainerItem::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@ContainerItem@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+17*8]
?loadFromSerialise@ContainerItem@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_setProperOwner@ContainerItem@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setProperOwner@ContainerItem@@QEAAXAEBVhand@@@Z endp

; ContainerItem::setProperOwner(const class hand &);
?setProperOwner@ContainerItem@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+18*8]
?setProperOwner@ContainerItem@@UEAAXAEBVhand@@@Z endp

?_CONSTRUCTOR@ContainerItem@@QEAAPEAV1@PEAVGameData@@0Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@ContainerItem@@QEAAPEAV1@PEAVGameData@@0Vhand@@@Z endp

; ContainerItem::ContainerItem(class GameData *, class GameData *, class hand);
??0ContainerItem@@QEAA@PEAVGameData@@0Vhand@@@Z proc EXPORT
jmp function_pointers[_ContainerItem_base+19*8]
??0ContainerItem@@QEAA@PEAVGameData@@0Vhand@@@Z endp
