
?_CONSTRUCTOR@ContextMenuGUI@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ContextMenuGUI@@QEAAPEAV1@XZ endp

; ContextMenuGUI::ContextMenuGUI();
??0ContextMenuGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+0*8]
??0ContextMenuGUI@@QEAA@XZ endp

?_DESTRUCTOR@ContextMenuGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ContextMenuGUI@@QEAAXXZ endp

; ContextMenuGUI::~ContextMenuGUI();
??1ContextMenuGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+1*8]
??1ContextMenuGUI@@UEAA@XZ endp

; ContextMenuGUI::getMainWidget();
?getMainWidget@ContextMenuGUI@@QEBAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+2*8]
?getMainWidget@ContextMenuGUI@@QEBAPEAVWidget@MyGUI@@XZ endp

; ContextMenuGUI::getVisible();
?getVisible@ContextMenuGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+3*8]
?getVisible@ContextMenuGUI@@QEBA_NXZ endp

; ContextMenuGUI::setVisible(bool);
?setVisible@ContextMenuGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+4*8]
?setVisible@ContextMenuGUI@@QEAAX_N@Z endp

; ContextMenuGUI::show(const class lektor<int> &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?show@ContextMenuGUI@@QEAAXAEBV?$lektor@H@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+5*8]
?show@ContextMenuGUI@@QEAAXAEBV?$lektor@H@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; ContextMenuGUI::optionSelected(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?optionSelected@ContextMenuGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_ContextMenuGUI_base+6*8]
?optionSelected@ContextMenuGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp
