
?_CONSTRUCTOR@ContextMenu@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ContextMenu@@QEAAPEAV1@XZ endp

; ContextMenu::ContextMenu();
??0ContextMenu@@QEAA@XZ proc EXPORT
jmp function_pointers[_ContextMenu_base+0*8]
??0ContextMenu@@QEAA@XZ endp

?_DESTRUCTOR@ContextMenu@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ContextMenu@@QEAAXXZ endp

; ContextMenu::~ContextMenu();
??1ContextMenu@@QEAA@XZ proc EXPORT
jmp function_pointers[_ContextMenu_base+1*8]
??1ContextMenu@@QEAA@XZ endp

; ContextMenu::showContextMenu(bool, class RootObject *);
?showContextMenu@ContextMenu@@QEAAX_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ContextMenu_base+2*8]
?showContextMenu@ContextMenu@@QEAAX_NPEAVRootObject@@@Z endp

; ContextMenu::isVisible();
?isVisible@ContextMenu@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ContextMenu_base+3*8]
?isVisible@ContextMenu@@QEBA_NXZ endp

; ContextMenu::update();
?update@ContextMenu@@QEAAXXZ proc EXPORT
jmp function_pointers[_ContextMenu_base+4*8]
?update@ContextMenu@@QEAAXXZ endp

; ContextMenu::_destroyMenuGUICheck();
?_destroyMenuGUICheck@ContextMenu@@QEAAXXZ proc EXPORT
jmp function_pointers[_ContextMenu_base+5*8]
?_destroyMenuGUICheck@ContextMenu@@QEAAXXZ endp
