
?_CONSTRUCTOR@CraftingInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
?_CONSTRUCTOR@CraftingInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; CraftingInventoryLayout::CraftingInventoryLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int);
??0CraftingInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+0*8]
??0CraftingInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; symbol is too long
; ?setupSections@CraftingInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; CraftingInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
CraftingInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+1*8]
CraftingInventoryLayout_setupSections_PLACEHOLDER endp

; CraftingInventoryLayout::refresh();
?refresh@CraftingInventoryLayout@@QEAAXXZ proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+2*8]
?refresh@CraftingInventoryLayout@@QEAAXXZ endp

; CraftingInventoryLayout::setOutputType(enum itemType);
?setOutputType@CraftingInventoryLayout@@QEAAXW4itemType@@@Z proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+3*8]
?setOutputType@CraftingInventoryLayout@@QEAAXW4itemType@@@Z endp

; CraftingInventoryLayout::setCraftingName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCraftingName@CraftingInventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+4*8]
?setCraftingName@CraftingInventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; CraftingInventoryLayout::getQueueButton();
?getQueueButton@CraftingInventoryLayout@@QEBAPEAVButton@MyGUI@@XZ proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+5*8]
?getQueueButton@CraftingInventoryLayout@@QEBAPEAVButton@MyGUI@@XZ endp

?_DESTRUCTOR@CraftingInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CraftingInventoryLayout@@QEAAXXZ endp

; CraftingInventoryLayout::~CraftingInventoryLayout();
??1CraftingInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_CraftingInventoryLayout_base+6*8]
??1CraftingInventoryLayout@@UEAA@XZ endp
