
?_CONSTRUCTOR@CraftingBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@CraftingBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; CraftingBuilding::CraftingBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0CraftingBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+0*8]
??0CraftingBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@CraftingBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@CraftingBuilding@@QEAAXXZ endp

; CraftingBuilding::~CraftingBuilding();
??1CraftingBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+1*8]
??1CraftingBuilding@@UEAA@XZ endp

?_NV_createInventoryLayout@CraftingBuilding@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@CraftingBuilding@@QEAAPEAVInventoryLayout@@XZ endp

; CraftingBuilding::createInventoryLayout();
?createInventoryLayout@CraftingBuilding@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+2*8]
?createInventoryLayout@CraftingBuilding@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_update@CraftingBuilding@@QEAAXXZ proc EXPORT
?_NV_update@CraftingBuilding@@QEAAXXZ endp

; CraftingBuilding::update();
?update@CraftingBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+3*8]
?update@CraftingBuilding@@UEAAXXZ endp

?_NV_operate@CraftingBuilding@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@CraftingBuilding@@QEAAXPEAVCharacter@@M@Z endp

; CraftingBuilding::operate(class Character *, float);
?operate@CraftingBuilding@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+4*8]
?operate@CraftingBuilding@@UEAAXPEAVCharacter@@M@Z endp

?_NV_givePower@CraftingBuilding@@QEAAXM@Z proc EXPORT
?_NV_givePower@CraftingBuilding@@QEAAXM@Z endp

; CraftingBuilding::givePower(float);
?givePower@CraftingBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+5*8]
?givePower@CraftingBuilding@@UEAAXM@Z endp

?_NV_getGUIData@CraftingBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@CraftingBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; CraftingBuilding::getGUIData(class DatapanelGUI *, int);
?getGUIData@CraftingBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+6*8]
?getGUIData@CraftingBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_serialise@CraftingBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@CraftingBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; CraftingBuilding::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@CraftingBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+7*8]
?serialise@CraftingBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@CraftingBuilding@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@CraftingBuilding@@QEAAXPEAVGameSaveState@@@Z endp

; CraftingBuilding::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@CraftingBuilding@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+8*8]
?loadFromSerialise@CraftingBuilding@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_hasCraftingQueued@CraftingBuilding@@QEBA_NXZ proc EXPORT
?_NV_hasCraftingQueued@CraftingBuilding@@QEBA_NXZ endp

; CraftingBuilding::hasCraftingQueued();
?hasCraftingQueued@CraftingBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+9*8]
?hasCraftingQueued@CraftingBuilding@@UEBA_NXZ endp

?_NV_isProductionFull@CraftingBuilding@@QEAA_NXZ proc EXPORT
?_NV_isProductionFull@CraftingBuilding@@QEAA_NXZ endp

; CraftingBuilding::isProductionFull();
?isProductionFull@CraftingBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+10*8]
?isProductionFull@CraftingBuilding@@UEAA_NXZ endp

?_NV_getProductionItemData@CraftingBuilding@@QEAAPEAVGameData@@XZ proc EXPORT
?_NV_getProductionItemData@CraftingBuilding@@QEAAPEAVGameData@@XZ endp

; CraftingBuilding::getProductionItemData();
?getProductionItemData@CraftingBuilding@@UEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+11*8]
?getProductionItemData@CraftingBuilding@@UEAAPEAVGameData@@XZ endp

?_NV_getCurrentProductionQuantity@CraftingBuilding@@QEAAHXZ proc EXPORT
?_NV_getCurrentProductionQuantity@CraftingBuilding@@QEAAHXZ endp

; CraftingBuilding::getCurrentProductionQuantity();
?getCurrentProductionQuantity@CraftingBuilding@@UEAAHXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+12*8]
?getCurrentProductionQuantity@CraftingBuilding@@UEAAHXZ endp

?_NV_isAnyInputsInvalidType@CraftingBuilding@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsInvalidType@CraftingBuilding@@QEBA_NXZ endp

; CraftingBuilding::isAnyInputsInvalidType();
?isAnyInputsInvalidType@CraftingBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+13*8]
?isAnyInputsInvalidType@CraftingBuilding@@UEBA_NXZ endp

?_NV_newCraftingButton@CraftingBuilding@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_newCraftingButton@CraftingBuilding@@QEAAXPEAVWidget@MyGUI@@@Z endp

; CraftingBuilding::newCraftingButton(class MyGUI::Widget *);
?newCraftingButton@CraftingBuilding@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+14*8]
?newCraftingButton@CraftingBuilding@@UEAAXPEAVWidget@MyGUI@@@Z endp

; CraftingBuilding::addFinishedCraftItem(class Item *);
?addFinishedCraftItem@CraftingBuilding@@QEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+15*8]
?addFinishedCraftItem@CraftingBuilding@@QEAAXPEAVItem@@@Z endp

; CraftingBuilding::notifyCraftFailiure();
?notifyCraftFailiure@CraftingBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+16*8]
?notifyCraftFailiure@CraftingBuilding@@QEAAXXZ endp

?_NV_tryOperate@CraftingBuilding@@QEAA_NAEBVhand@@@Z proc EXPORT
?_NV_tryOperate@CraftingBuilding@@QEAA_NAEBVhand@@@Z endp

; CraftingBuilding::tryOperate(const class hand &);
?tryOperate@CraftingBuilding@@UEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+17*8]
?tryOperate@CraftingBuilding@@UEAA_NAEBVhand@@@Z endp

; CraftingBuilding::playerManufacturerData();
?playerManufacturerData@CraftingBuilding@@SAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+18*8]
?playerManufacturerData@CraftingBuilding@@SAPEAVGameData@@XZ endp

; CraftingBuilding::getAvailableCrafts(class lektor<GameDataGroup> &);
?getAvailableCrafts@CraftingBuilding@@QEAAXAEAV?$lektor@VGameDataGroup@@@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+19*8]
?getAvailableCrafts@CraftingBuilding@@QEAAXAEAV?$lektor@VGameDataGroup@@@@@Z endp

; CraftingBuilding::_addCraft(class GameData *, class GameData *, float, class YesNoMaybe);
?_addCraft@CraftingBuilding@@QEAAPEAVCraftingItem@@PEAVGameData@@0MVYesNoMaybe@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+20*8]
?_addCraft@CraftingBuilding@@QEAAPEAVCraftingItem@@PEAVGameData@@0MVYesNoMaybe@@@Z endp

; CraftingBuilding::_removeCraft(int);
?_removeCraft@CraftingBuilding@@QEAAXH@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+21*8]
?_removeCraft@CraftingBuilding@@QEAAXH@Z endp

; CraftingBuilding::getCraft(int);
?getCraft@CraftingBuilding@@QEAAPEAVCraftingItem@@H@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+22*8]
?getCraft@CraftingBuilding@@QEAAPEAVCraftingItem@@H@Z endp

; CraftingBuilding::destroyProductionItem();
?destroyProductionItem@CraftingBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+23*8]
?destroyProductionItem@CraftingBuilding@@QEAAXXZ endp

; CraftingBuilding::predictCraftersBestWeapon(const class hand &, int);
?predictCraftersBestWeapon@CraftingBuilding@@QEAAPEAVGameData@@AEBVhand@@H@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+24*8]
?predictCraftersBestWeapon@CraftingBuilding@@QEAAPEAVGameData@@AEBVhand@@H@Z endp

; CraftingBuilding::calculateCriticalChance(class Character *);
?calculateCriticalChance@CraftingBuilding@@QEAAMPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+25*8]
?calculateCriticalChance@CraftingBuilding@@QEAAMPEAVCharacter@@@Z endp

; CraftingBuilding::getCriticalSuccessWeapon(int);
?getCriticalSuccessWeapon@CraftingBuilding@@QEAAPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+26*8]
?getCriticalSuccessWeapon@CraftingBuilding@@QEAAPEAVGameData@@H@Z endp

?_NV_getItemsWeWantRidOf@CraftingBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z proc EXPORT
?_NV_getItemsWeWantRidOf@CraftingBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z endp

; CraftingBuilding::getItemsWeWantRidOf(class lektor<GameData *> &, bool);
?getItemsWeWantRidOf@CraftingBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+27*8]
?getItemsWeWantRidOf@CraftingBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z endp

?_NV_canHaveSomeOfThese@CraftingBuilding@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_canHaveSomeOfThese@CraftingBuilding@@QEAA_NPEAVGameData@@@Z endp

; CraftingBuilding::canHaveSomeOfThese(class GameData *);
?canHaveSomeOfThese@CraftingBuilding@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+28*8]
?canHaveSomeOfThese@CraftingBuilding@@UEAA_NPEAVGameData@@@Z endp

?_NV_setupFromData@CraftingBuilding@@QEAAXXZ proc EXPORT
?_NV_setupFromData@CraftingBuilding@@QEAAXXZ endp

; CraftingBuilding::setupFromData();
?setupFromData@CraftingBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+29*8]
?setupFromData@CraftingBuilding@@UEAAXXZ endp

?_NV_updateOutput@CraftingBuilding@@QEAAXM@Z proc EXPORT
?_NV_updateOutput@CraftingBuilding@@QEAAXM@Z endp

; CraftingBuilding::updateOutput(float);
?updateOutput@CraftingBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+30*8]
?updateOutput@CraftingBuilding@@UEAAXM@Z endp

; CraftingBuilding::getPlayerCraftedWeaponLevel(class GameData *);
?getPlayerCraftedWeaponLevel@CraftingBuilding@@QEAAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+31*8]
?getPlayerCraftedWeaponLevel@CraftingBuilding@@QEAAMPEAVGameData@@@Z endp

?_NV_getGUIState@CraftingBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@CraftingBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; CraftingBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@CraftingBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+32*8]
?getGUIState@CraftingBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_updateInventoryWindow@CraftingBuilding@@QEAAXXZ proc EXPORT
?_NV_updateInventoryWindow@CraftingBuilding@@QEAAXXZ endp

; CraftingBuilding::updateInventoryWindow();
?updateInventoryWindow@CraftingBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_CraftingBuilding_base+33*8]
?updateInventoryWindow@CraftingBuilding@@UEAAXXZ endp

?_NV_setProductionItem@CraftingBuilding@@QEAAXPEAVGameData@@HM@Z proc EXPORT
?_NV_setProductionItem@CraftingBuilding@@QEAAXPEAVGameData@@HM@Z endp

; CraftingBuilding::setProductionItem(class GameData *, int, float);
?setProductionItem@CraftingBuilding@@UEAAXPEAVGameData@@HM@Z proc EXPORT
jmp function_pointers[_CraftingBuilding_base+34*8]
?setProductionItem@CraftingBuilding@@UEAAXPEAVGameData@@HM@Z endp
