
?_CONSTRUCTOR@Crossbow@@QEAAPEAV1@PEAVGameData@@Vhand@@H@Z proc EXPORT
?_CONSTRUCTOR@Crossbow@@QEAAPEAV1@PEAVGameData@@Vhand@@H@Z endp

; Crossbow::Crossbow(class GameData *, class hand, int);
??0Crossbow@@QEAA@PEAVGameData@@Vhand@@H@Z proc EXPORT
jmp function_pointers[_Crossbow_base+0*8]
??0Crossbow@@QEAA@PEAVGameData@@Vhand@@H@Z endp

?_NV_isCrossbow@Crossbow@@QEAAPEAV1@XZ proc EXPORT
?_NV_isCrossbow@Crossbow@@QEAAPEAV1@XZ endp

; Crossbow::isCrossbow();
?isCrossbow@Crossbow@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Crossbow_base+1*8]
?isCrossbow@Crossbow@@UEAAPEAV1@XZ endp

?_NV_getClassType@Crossbow@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@Crossbow@@QEBA?AW4itemType@@XZ endp

; Crossbow::getClassType();
?getClassType@Crossbow@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Crossbow_base+2*8]
?getClassType@Crossbow@@UEBA?AW4itemType@@XZ endp

?_NV_getCraftMaterialMult@Crossbow@@QEAAMXZ proc EXPORT
?_NV_getCraftMaterialMult@Crossbow@@QEAAMXZ endp

; Crossbow::getCraftMaterialMult();
?getCraftMaterialMult@Crossbow@@UEAAMXZ proc EXPORT
jmp function_pointers[_Crossbow_base+3*8]
?getCraftMaterialMult@Crossbow@@UEAAMXZ endp

?_NV_getCraftTime@Crossbow@@QEAAMXZ proc EXPORT
?_NV_getCraftTime@Crossbow@@QEAAMXZ endp

; Crossbow::getCraftTime();
?getCraftTime@Crossbow@@UEAAMXZ proc EXPORT
jmp function_pointers[_Crossbow_base+4*8]
?getCraftTime@Crossbow@@UEAAMXZ endp

; Crossbow::getRangeInUnits();
?getRangeInUnits@Crossbow@@QEBAMXZ proc EXPORT
jmp function_pointers[_Crossbow_base+5*8]
?getRangeInUnits@Crossbow@@QEBAMXZ endp

; Crossbow::getEquipPositionOffset();
?getEquipPositionOffset@Crossbow@@QEAAMXZ proc EXPORT
jmp function_pointers[_Crossbow_base+6*8]
?getEquipPositionOffset@Crossbow@@QEAAMXZ endp

?_NV_getTooltipData1@Crossbow@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@Crossbow@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Crossbow::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@Crossbow@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Crossbow_base+7*8]
?getTooltipData1@Crossbow@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@Crossbow@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@Crossbow@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Crossbow::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@Crossbow@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Crossbow_base+8*8]
?getTooltipData2@Crossbow@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_createItemEntityCallback_Equipping@Crossbow@@QEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z proc EXPORT
?_NV_createItemEntityCallback_Equipping@Crossbow@@QEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z endp

; Crossbow::createItemEntityCallback_Equipping(class Ogre::Entity *, class Ogre::SceneNode *);
?createItemEntityCallback_Equipping@Crossbow@@UEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z proc EXPORT
jmp function_pointers[_Crossbow_base+9*8]
?createItemEntityCallback_Equipping@Crossbow@@UEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z endp

?_NV_destroyItemEntityCallback_Equipping@Crossbow@@QEAAXXZ proc EXPORT
?_NV_destroyItemEntityCallback_Equipping@Crossbow@@QEAAXXZ endp

; Crossbow::destroyItemEntityCallback_Equipping();
?destroyItemEntityCallback_Equipping@Crossbow@@UEAAXXZ proc EXPORT
jmp function_pointers[_Crossbow_base+10*8]
?destroyItemEntityCallback_Equipping@Crossbow@@UEAAXXZ endp

?_NV_setVisible@Crossbow@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@Crossbow@@QEAAX_N@Z endp

; Crossbow::setVisible(bool);
?setVisible@Crossbow@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Crossbow_base+11*8]
?setVisible@Crossbow@@UEAAX_N@Z endp

?_DESTRUCTOR@Crossbow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Crossbow@@QEAAXXZ endp

; Crossbow::~Crossbow();
??1Crossbow@@UEAA@XZ proc EXPORT
jmp function_pointers[_Crossbow_base+12*8]
??1Crossbow@@UEAA@XZ endp
