
?_CONSTRUCTOR@Damages@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@Damages@@QEAAPEAV1@AEBV1@@Z endp

; Damages::Damages(const class Damages &);
??0Damages@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_Damages_base+0*8]
??0Damages@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@Damages@@QEAAPEAV1@MMMMM@Z proc EXPORT
?_CONSTRUCTOR@Damages@@QEAAPEAV1@MMMMM@Z endp

; Damages::Damages(float, float, float, float, float);
??0Damages@@QEAA@MMMMM@Z proc EXPORT
jmp function_pointers[_Damages_base+1*8]
??0Damages@@QEAA@MMMMM@Z endp

?_CONSTRUCTOR@Damages@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Damages@@QEAAPEAV1@XZ endp

; Damages::Damages();
??0Damages@@QEAA@XZ proc EXPORT
jmp function_pointers[_Damages_base+2*8]
??0Damages@@QEAA@XZ endp

; Damages::multiply(float);
?multiply@Damages@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Damages_base+3*8]
?multiply@Damages@@QEAAXM@Z endp

; Damages::total();
?total@Damages@@QEBAMXZ proc EXPORT
jmp function_pointers[_Damages_base+4*8]
?total@Damages@@QEBAMXZ endp

?_DESTRUCTOR@Damages@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Damages@@QEAAXXZ endp

; Damages::~Damages();
??1Damages@@QEAA@XZ proc EXPORT
jmp function_pointers[_Damages_base+5*8]
??1Damages@@QEAA@XZ endp
