
?_CONSTRUCTOR@DataPanelLine_Faction@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HMM@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_Faction@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HMM@Z endp

; DataPanelLine_Faction::DataPanelLine_Faction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, float);
??0DataPanelLine_Faction@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HMM@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Faction_base+0*8]
??0DataPanelLine_Faction@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HMM@Z endp

?_NV_createMe@DataPanelLine_Faction@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_Faction@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_Faction::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_Faction@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Faction_base+1*8]
?createMe@DataPanelLine_Faction@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_DESTRUCTOR@DataPanelLine_Faction@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_Faction@@QEAAXXZ endp

; DataPanelLine_Faction::~DataPanelLine_Faction();
??1DataPanelLine_Faction@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Faction_base+2*8]
??1DataPanelLine_Faction@@UEAA@XZ endp
