
; DatapanelGUI::setFrequentUpdateMode();
?setFrequentUpdateMode@DatapanelGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+0*8]
?setFrequentUpdateMode@DatapanelGUI@@QEAAXXZ endp

?_NV_setPositionReal@DatapanelGUI@@QEAAXMM@Z proc EXPORT
?_NV_setPositionReal@DatapanelGUI@@QEAAXMM@Z endp

; DatapanelGUI::setPositionReal(float, float);
?setPositionReal@DatapanelGUI@@UEAAXMM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+1*8]
?setPositionReal@DatapanelGUI@@UEAAXMM@Z endp

?_NV_setPosition@DatapanelGUI@@QEAAXHH@Z proc EXPORT
?_NV_setPosition@DatapanelGUI@@QEAAXHH@Z endp

; DatapanelGUI::setPosition(int, int);
?setPosition@DatapanelGUI@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+2*8]
?setPosition@DatapanelGUI@@UEAAXHH@Z endp

?_NV_resize@DatapanelGUI@@QEAAXHH@Z proc EXPORT
?_NV_resize@DatapanelGUI@@QEAAXHH@Z endp

; DatapanelGUI::resize(int, int);
?resize@DatapanelGUI@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+3*8]
?resize@DatapanelGUI@@UEAAXHH@Z endp

?_NV_clear@DatapanelGUI@@QEAAXXZ proc EXPORT
?_NV_clear@DatapanelGUI@@QEAAXXZ endp

; DatapanelGUI::clear();
?clear@DatapanelGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+4*8]
?clear@DatapanelGUI@@UEAAXXZ endp

?_NV_clearPage@DatapanelGUI@@QEAAXH@Z proc EXPORT
?_NV_clearPage@DatapanelGUI@@QEAAXH@Z endp

; DatapanelGUI::clearPage(int);
?clearPage@DatapanelGUI@@UEAAXH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+5*8]
?clearPage@DatapanelGUI@@UEAAXH@Z endp

?_NV_hideAllWidgets@DatapanelGUI@@QEAAXXZ proc EXPORT
?_NV_hideAllWidgets@DatapanelGUI@@QEAAXXZ endp

; DatapanelGUI::hideAllWidgets();
?hideAllWidgets@DatapanelGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+6*8]
?hideAllWidgets@DatapanelGUI@@UEAAXXZ endp

?_NV_create@DatapanelGUI@@QEAAXXZ proc EXPORT
?_NV_create@DatapanelGUI@@QEAAXXZ endp

; DatapanelGUI::create();
?create@DatapanelGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+7*8]
?create@DatapanelGUI@@UEAAXXZ endp

?_NV_show@DatapanelGUI@@QEAAX_N@Z proc EXPORT
?_NV_show@DatapanelGUI@@QEAAX_N@Z endp

; DatapanelGUI::show(bool);
?show@DatapanelGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+8*8]
?show@DatapanelGUI@@UEAAX_N@Z endp

; DatapanelGUI::show_NonSmooth(bool);
?show_NonSmooth@DatapanelGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+9*8]
?show_NonSmooth@DatapanelGUI@@QEAAX_N@Z endp

?_NV_update@DatapanelGUI@@QEAAXXZ proc EXPORT
?_NV_update@DatapanelGUI@@QEAAXXZ endp

; DatapanelGUI::update();
?update@DatapanelGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+10*8]
?update@DatapanelGUI@@UEAAXXZ endp

; DatapanelGUI::setPanelName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setPanelName@DatapanelGUI@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+11*8]
?setPanelName@DatapanelGUI@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_showTabs@DatapanelGUI@@QEAAX_N@Z proc EXPORT
?_NV_showTabs@DatapanelGUI@@QEAAX_N@Z endp

; DatapanelGUI::showTabs(bool);
?showTabs@DatapanelGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+12*8]
?showTabs@DatapanelGUI@@UEAAX_N@Z endp

?_NV_addTab@DatapanelGUI@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
?_NV_addTab@DatapanelGUI@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; DatapanelGUI::addTab(int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addTab@DatapanelGUI@@UEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+13*8]
?addTab@DatapanelGUI@@UEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

?_NV_setTabEnabled@DatapanelGUI@@QEAAXHAEB_N@Z proc EXPORT
?_NV_setTabEnabled@DatapanelGUI@@QEAAXHAEB_N@Z endp

; DatapanelGUI::setTabEnabled(int, const bool &);
?setTabEnabled@DatapanelGUI@@UEAAXHAEB_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+14*8]
?setTabEnabled@DatapanelGUI@@UEAAXHAEB_N@Z endp

?_NV_setTabName@DatapanelGUI@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setTabName@DatapanelGUI@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::setTabName(int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setTabName@DatapanelGUI@@UEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+15*8]
?setTabName@DatapanelGUI@@UEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::setCaption(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCaption@DatapanelGUI@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+16*8]
?setCaption@DatapanelGUI@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::setCloseCallback(class MyGUI::delegates::IDelegate2<MyGUI::Window *,std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &> *);
?setCloseCallback@DatapanelGUI@@QEAAXPEAV?$IDelegate2@PEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@delegates@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+17*8]
?setCloseCallback@DatapanelGUI@@QEAAXPEAV?$IDelegate2@PEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@delegates@MyGUI@@@Z endp

?_NV_setAutomaticRefresh@DatapanelGUI@@QEAAX_N@Z proc EXPORT
?_NV_setAutomaticRefresh@DatapanelGUI@@QEAAX_N@Z endp

; DatapanelGUI::setAutomaticRefresh(bool);
?setAutomaticRefresh@DatapanelGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+18*8]
?setAutomaticRefresh@DatapanelGUI@@UEAAX_N@Z endp

?_NV_setAutomaticTargeting@DatapanelGUI@@QEAAX_N@Z proc EXPORT
?_NV_setAutomaticTargeting@DatapanelGUI@@QEAAX_N@Z endp

; DatapanelGUI::setAutomaticTargeting(bool);
?setAutomaticTargeting@DatapanelGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+19*8]
?setAutomaticTargeting@DatapanelGUI@@UEAAX_N@Z endp

?_NV__zeroLines@DatapanelGUI@@QEAAPEAVDataPanelLine@@H@Z proc EXPORT
?_NV__zeroLines@DatapanelGUI@@QEAAPEAVDataPanelLine@@H@Z endp

; DatapanelGUI::_zeroLines(int);
?_zeroLines@DatapanelGUI@@UEAAPEAVDataPanelLine@@H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+20*8]
?_zeroLines@DatapanelGUI@@UEAAPEAVDataPanelLine@@H@Z endp

; DatapanelGUI::setLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0000H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+21*8]
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0000H@Z endp

; DatapanelGUI::setLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, bool);
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H_N1@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+22*8]
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H_N1@Z endp

; DatapanelGUI::setLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@000H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+23*8]
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@000H@Z endp

; DatapanelGUI::setLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, int);
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+24*8]
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MH@Z endp

; DatapanelGUI::setLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, bool);
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+25*8]
?setLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1@Z endp

; DatapanelGUI::setLineStatInfo(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?setLineStatInfo@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+26*8]
?setLineStatInfo@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z endp

; DatapanelGUI::setLineFaction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, float);
?setLineFaction@DatapanelGUI@@QEAAPEAVDataPanelLine_Faction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HMM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+27*8]
?setLineFaction@DatapanelGUI@@QEAAPEAVDataPanelLine_Faction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HMM@Z endp

; DatapanelGUI::setLineResearch(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setLineResearch@DatapanelGUI@@QEAAPEAVDataPanelLine_Research@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+28*8]
?setLineResearch@DatapanelGUI@@QEAAPEAVDataPanelLine_Research@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0_N@Z endp

; DatapanelGUI::setLineResearch(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setLineResearch@DatapanelGUI@@QEAAPEAVDataPanelLine_Research@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00HM0_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+29*8]
?setLineResearch@DatapanelGUI@@QEAAPEAVDataPanelLine_Research@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00HM0_N@Z endp

; DatapanelGUI::setLineTextButton(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setLineTextButton@DatapanelGUI@@QEAAPEAVDataPanelLine_Button@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+30*8]
?setLineTextButton@DatapanelGUI@@QEAAPEAVDataPanelLine_Button@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0@Z endp

; DatapanelGUI::setLineButton(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?setLineButton@DatapanelGUI@@QEAAPEAVDataPanelLine_Button@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+31*8]
?setLineButton@DatapanelGUI@@QEAAPEAVDataPanelLine_Button@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z endp

; DatapanelGUI::setLineToggleButton(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?setLineToggleButton@DatapanelGUI@@QEAAPEAVDataPanelLine_Button@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+32*8]
?setLineToggleButton@DatapanelGUI@@QEAAPEAVDataPanelLine_Button@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z endp

; DatapanelGUI::setLineSliderEditable(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, float, float, float *);
?setLineSliderEditable@DatapanelGUI@@QEAAPEAVDataPanelLine_SliderEditable@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_NMMPEAM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+33*8]
?setLineSliderEditable@DatapanelGUI@@QEAAPEAVDataPanelLine_SliderEditable@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_NMMPEAM@Z endp

; DatapanelGUI::setLineText(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, const struct MyGUI::Align &);
?setLineText@DatapanelGUI@@QEAAPEAVDataPanelLine_Text@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NAEBUAlign@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+34*8]
?setLineText@DatapanelGUI@@QEAAPEAVDataPanelLine_Text@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NAEBUAlign@MyGUI@@@Z endp

; DatapanelGUI::setLineTextEditable(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, bool, const struct MyGUI::Align &, float);
?setLineTextEditable@DatapanelGUI@@QEAAPEAVDataPanelLine_TextEditable@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1AEBUAlign@MyGUI@@M@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+35*8]
?setLineTextEditable@DatapanelGUI@@QEAAPEAVDataPanelLine_TextEditable@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1AEBUAlign@MyGUI@@M@Z endp

; DatapanelGUI::setLineSlider(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, int, float *, float);
?setLineSlider@DatapanelGUI@@QEAAPEAVDataPanelLine_Slider@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MMHPEAMM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+36*8]
?setLineSlider@DatapanelGUI@@QEAAPEAVDataPanelLine_Slider@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MMHPEAMM@Z endp

; DatapanelGUI::setLineProgress(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setLineProgress@DatapanelGUI@@QEAAPEAVDataPanelLine_Progress@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HM0_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+37*8]
?setLineProgress@DatapanelGUI@@QEAAPEAVDataPanelLine_Progress@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HM0_N@Z endp

; DatapanelGUI::removeLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?removeLine@DatapanelGUI@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+38*8]
?removeLine@DatapanelGUI@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; DatapanelGUI::setLineCheckbox(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool *, int);
?setLineCheckbox@DatapanelGUI@@QEAAPEAVDataPanelLine_CheckBox@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEA_NH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+39*8]
?setLineCheckbox@DatapanelGUI@@QEAAPEAVDataPanelLine_CheckBox@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEA_NH@Z endp

; DatapanelGUI::setLineDropBox(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int *, bool, float);
?setLineDropBox@DatapanelGUI@@QEAAPEAVDataPanelLine_DropBox@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEAH_NM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+40*8]
?setLineDropBox@DatapanelGUI@@QEAAPEAVDataPanelLine_DropBox@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEAH_NM@Z endp

; DatapanelGUI::addSpace(int, float);
?addSpace@DatapanelGUI@@QEAAXHM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+41*8]
?addSpace@DatapanelGUI@@QEAAXHM@Z endp

; DatapanelGUI::setLines(const class lektor<StringPair> &, int);
?setLines@DatapanelGUI@@QEAAXAEBV?$lektor@VStringPair@@@@H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+42*8]
?setLines@DatapanelGUI@@QEAAXAEBV?$lektor@VStringPair@@@@H@Z endp

?_NV_setCategoryIcon@DatapanelGUI@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setCategoryIcon@DatapanelGUI@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::setCategoryIcon(int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCategoryIcon@DatapanelGUI@@UEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+43*8]
?setCategoryIcon@DatapanelGUI@@UEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_changeCategory@DatapanelGUI@@QEAAXH@Z proc EXPORT
?_NV_changeCategory@DatapanelGUI@@QEAAXH@Z endp

; DatapanelGUI::changeCategory(int);
?changeCategory@DatapanelGUI@@UEAAXH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+44*8]
?changeCategory@DatapanelGUI@@UEAAXH@Z endp

?_NV_getCurrentCategory@DatapanelGUI@@QEBAHXZ proc EXPORT
?_NV_getCurrentCategory@DatapanelGUI@@QEBAHXZ endp

; DatapanelGUI::getCurrentCategory();
?getCurrentCategory@DatapanelGUI@@UEBAHXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+45*8]
?getCurrentCategory@DatapanelGUI@@UEBAHXZ endp

; DatapanelGUI::addCustomLine(class DataPanelLine *);
?addCustomLine@DatapanelGUI@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+46*8]
?addCustomLine@DatapanelGUI@@QEAAXPEAVDataPanelLine@@@Z endp

?_NV_autoChangeSelectedObject@DatapanelGUI@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_autoChangeSelectedObject@DatapanelGUI@@QEAAXAEBVhand@@@Z endp

; DatapanelGUI::autoChangeSelectedObject(const class hand &);
?autoChangeSelectedObject@DatapanelGUI@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+47*8]
?autoChangeSelectedObject@DatapanelGUI@@UEAAXAEBVhand@@@Z endp

?_NV_getObject@DatapanelGUI@@QEBA?AVhand@@XZ proc EXPORT
?_NV_getObject@DatapanelGUI@@QEBA?AVhand@@XZ endp

; DatapanelGUI::getObject();
?getObject@DatapanelGUI@@UEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+48*8]
?getObject@DatapanelGUI@@UEBA?AVhand@@XZ endp

?_NV_setObject@DatapanelGUI@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setObject@DatapanelGUI@@QEAAXAEBVhand@@@Z endp

; DatapanelGUI::setObject(const class hand &);
?setObject@DatapanelGUI@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+49*8]
?setObject@DatapanelGUI@@UEAAXAEBVhand@@@Z endp

?_NV_setLineSpacing@DatapanelGUI@@QEAAXM@Z proc EXPORT
?_NV_setLineSpacing@DatapanelGUI@@QEAAXM@Z endp

; DatapanelGUI::setLineSpacing(float);
?setLineSpacing@DatapanelGUI@@UEAAXM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+50*8]
?setLineSpacing@DatapanelGUI@@UEAAXM@Z endp

?_NV_setMouseOverCallback@DatapanelGUI@@QEAAXP6AXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAX@Z1@Z proc EXPORT
?_NV_setMouseOverCallback@DatapanelGUI@@QEAAXP6AXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAX@Z1@Z endp

; DatapanelGUI::setMouseOverCallback(function  *, void *);
?setMouseOverCallback@DatapanelGUI@@UEAAXP6AXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAX@Z1@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+51*8]
?setMouseOverCallback@DatapanelGUI@@UEAAXP6AXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAX@Z1@Z endp

?_NV_getLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
?_NV_getLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; DatapanelGUI::getLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?getLine@DatapanelGUI@@UEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+52*8]
?getLine@DatapanelGUI@@UEAAPEAVDataPanelLine@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; DatapanelGUI::lineExists(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?lineExists@DatapanelGUI@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+53*8]
?lineExists@DatapanelGUI@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; DatapanelGUI::getContentHeight(int);
?getContentHeight@DatapanelGUI@@QEBAHH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+54*8]
?getContentHeight@DatapanelGUI@@QEBAHH@Z endp

; DatapanelGUI::tabButton(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?tabButton@DatapanelGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+55*8]
?tabButton@DatapanelGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; DatapanelGUI::getNumLines(int);
?getNumLines@DatapanelGUI@@QEAAHH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+56*8]
?getNumLines@DatapanelGUI@@QEAAHH@Z endp

; DatapanelGUI::getLineByNum(int, int);
?getLineByNum@DatapanelGUI@@QEAAPEAVDataPanelLine@@HH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+57*8]
?getLineByNum@DatapanelGUI@@QEAAPEAVDataPanelLine@@HH@Z endp

?_CONSTRUCTOR@DatapanelGUI@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N@Z proc EXPORT
?_CONSTRUCTOR@DatapanelGUI@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N@Z endp

; DatapanelGUI::DatapanelGUI(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class MyGUI::Widget *, bool);
??0DatapanelGUI@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+58*8]
??0DatapanelGUI@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N@Z endp

?_CONSTRUCTOR@DatapanelGUI@@QEAAPEAV1@MMMM_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@DatapanelGUI@@QEAAPEAV1@MMMM_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::DatapanelGUI(float, float, float, float, bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0DatapanelGUI@@QEAA@MMMM_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+59*8]
??0DatapanelGUI@@QEAA@MMMM_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@DatapanelGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DatapanelGUI@@QEAAXXZ endp

; DatapanelGUI::~DatapanelGUI();
??1DatapanelGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+60*8]
??1DatapanelGUI@@UEAA@XZ endp

; DatapanelGUI::createLine(class DataPanelLine *, int, bool);
?createLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@PEAV2@H_N@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+61*8]
?createLine@DatapanelGUI@@QEAAPEAVDataPanelLine@@PEAV2@H_N@Z endp

; DatapanelGUI::getNextVerticalPos(int);
?getNextVerticalPos@DatapanelGUI@@QEAAMH@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+62*8]
?getNextVerticalPos@DatapanelGUI@@QEAAMH@Z endp

; DatapanelGUI::closeButtonCallback(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeButtonCallback@DatapanelGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+63*8]
?closeButtonCallback@DatapanelGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::mouseOverCallback(class MyGUI::Widget *);
?mouseOverCallback@DatapanelGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+64*8]
?mouseOverCallback@DatapanelGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; DatapanelGUI::notifyMouseWheel(class MyGUI::Widget *, int);
?notifyMouseWheel@DatapanelGUI@@QEAAXPEAVWidget@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+65*8]
?notifyMouseWheel@DatapanelGUI@@QEAAXPEAVWidget@MyGUI@@H@Z endp

; DatapanelGUI::getCoords(float, float, float, float);
?getCoords@DatapanelGUI@@QEAA?AU?$TCoord@H@types@MyGUI@@MMMM@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+66*8]
?getCoords@DatapanelGUI@@QEAA?AU?$TCoord@H@types@MyGUI@@MMMM@Z endp

; DatapanelGUI::dataExists(int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?dataExists@DatapanelGUI@@QEAA_NHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DatapanelGUI_base+67*8]
?dataExists@DatapanelGUI@@QEAA_NHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DatapanelGUI::clearCategoryTabs();
?clearCategoryTabs@DatapanelGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_DatapanelGUI_base+68*8]
?clearCategoryTabs@DatapanelGUI@@QEAAXXZ endp
