
; DataPanelLine_TextEditable::getEditBox();
?getEditBox@DataPanelLine_TextEditable@@QEAAPEAVEditBox@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_TextEditable_base+0*8]
?getEditBox@DataPanelLine_TextEditable@@QEAAPEAVEditBox@MyGUI@@XZ endp

; DataPanelLine_TextEditable::getNameBox();
?getNameBox@DataPanelLine_TextEditable@@QEAAPEAVEditBox@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_TextEditable_base+1*8]
?getNameBox@DataPanelLine_TextEditable@@QEAAPEAVEditBox@MyGUI@@XZ endp

?_CONSTRUCTOR@DataPanelLine_TextEditable@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1AEBUAlign@MyGUI@@M@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_TextEditable@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1AEBUAlign@MyGUI@@M@Z endp

; DataPanelLine_TextEditable::DataPanelLine_TextEditable(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, bool, const struct MyGUI::Align &, float);
??0DataPanelLine_TextEditable@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1AEBUAlign@MyGUI@@M@Z proc EXPORT
jmp function_pointers[_DataPanelLine_TextEditable_base+2*8]
??0DataPanelLine_TextEditable@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_N1AEBUAlign@MyGUI@@M@Z endp

?_NV_createMe@DataPanelLine_TextEditable@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_TextEditable@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_TextEditable::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_TextEditable@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_TextEditable_base+3*8]
?createMe@DataPanelLine_TextEditable@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_TextEditable::textChanged(class MyGUI::EditBox *);
?textChanged@DataPanelLine_TextEditable@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_TextEditable_base+4*8]
?textChanged@DataPanelLine_TextEditable@@QEAAXPEAVEditBox@MyGUI@@@Z endp

?_DESTRUCTOR@DataPanelLine_TextEditable@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_TextEditable@@QEAAXXZ endp

; DataPanelLine_TextEditable::~DataPanelLine_TextEditable();
??1DataPanelLine_TextEditable@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_TextEditable_base+5*8]
??1DataPanelLine_TextEditable@@UEAA@XZ endp
