
?_CONSTRUCTOR@DataPanelLine_Research@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0_N@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_Research@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0_N@Z endp

; DataPanelLine_Research::DataPanelLine_Research(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
??0DataPanelLine_Research@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Research_base+0*8]
??0DataPanelLine_Research@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0_N@Z endp

?_NV_setToolTipMainBar@DataPanelLine_Research@@QEAAXAEBV?$lektor@VStringPair@@@@_N@Z proc EXPORT
?_NV_setToolTipMainBar@DataPanelLine_Research@@QEAAXAEBV?$lektor@VStringPair@@@@_N@Z endp

; DataPanelLine_Research::setToolTipMainBar(const class lektor<StringPair> &, bool);
?setToolTipMainBar@DataPanelLine_Research@@UEAAXAEBV?$lektor@VStringPair@@@@_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Research_base+1*8]
?setToolTipMainBar@DataPanelLine_Research@@UEAAXAEBV?$lektor@VStringPair@@@@_N@Z endp

?_NV_setToolTipMainBar@DataPanelLine_Research@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
?_NV_setToolTipMainBar@DataPanelLine_Research@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; DataPanelLine_Research::setToolTipMainBar(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setToolTipMainBar@DataPanelLine_Research@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Research_base+2*8]
?setToolTipMainBar@DataPanelLine_Research@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

?_NV_createMe@DataPanelLine_Research@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_Research@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_Research::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_Research@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Research_base+3*8]
?createMe@DataPanelLine_Research@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_DESTRUCTOR@DataPanelLine_Research@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_Research@@QEAAXXZ endp

; DataPanelLine_Research::~DataPanelLine_Research();
??1DataPanelLine_Research@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Research_base+4*8]
??1DataPanelLine_Research@@UEAA@XZ endp
