
?_CONSTRUCTOR@DataPanelLine_Text@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NAEBUAlign@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_Text@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NAEBUAlign@MyGUI@@@Z endp

; DataPanelLine_Text::DataPanelLine_Text(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, const struct MyGUI::Align &);
??0DataPanelLine_Text@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NAEBUAlign@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Text_base+0*8]
??0DataPanelLine_Text@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NAEBUAlign@MyGUI@@@Z endp

?_NV_createMe@DataPanelLine_Text@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_Text@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_Text::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_Text@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Text_base+1*8]
?createMe@DataPanelLine_Text@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_DESTRUCTOR@DataPanelLine_Text@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_Text@@QEAAXXZ endp

; DataPanelLine_Text::~DataPanelLine_Text();
??1DataPanelLine_Text@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Text_base+2*8]
??1DataPanelLine_Text@@UEAA@XZ endp
