
?_CONSTRUCTOR@DataPanelLine_Slider@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MMHM@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_Slider@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MMHM@Z endp

; DataPanelLine_Slider::DataPanelLine_Slider(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, int, float);
??0DataPanelLine_Slider@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MMHM@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+0*8]
??0DataPanelLine_Slider@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0MMHM@Z endp

; DataPanelLine_Slider::sliderValueChanged(class MyGUI::Slider *, int);
?sliderValueChanged@DataPanelLine_Slider@@QEAAXPEAVSlider@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+1*8]
?sliderValueChanged@DataPanelLine_Slider@@QEAAXPEAVSlider@MyGUI@@H@Z endp

?_NV_updateValuePtr@DataPanelLine_Slider@@QEAAXPEAX@Z proc EXPORT
?_NV_updateValuePtr@DataPanelLine_Slider@@QEAAXPEAX@Z endp

; DataPanelLine_Slider::updateValuePtr(void *);
?updateValuePtr@DataPanelLine_Slider@@UEAAXPEAX@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+2*8]
?updateValuePtr@DataPanelLine_Slider@@UEAAXPEAX@Z endp

; DataPanelLine_Slider::setValue(float);
?setValue@DataPanelLine_Slider@@QEAAXM@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+3*8]
?setValue@DataPanelLine_Slider@@QEAAXM@Z endp

; DataPanelLine_Slider::getValue();
?getValue@DataPanelLine_Slider@@QEBAMXZ proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+4*8]
?getValue@DataPanelLine_Slider@@QEBAMXZ endp

?_NV_refresh@DataPanelLine_Slider@@QEAAXXZ proc EXPORT
?_NV_refresh@DataPanelLine_Slider@@QEAAXXZ endp

; DataPanelLine_Slider::refresh();
?refresh@DataPanelLine_Slider@@UEAAXXZ proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+5*8]
?refresh@DataPanelLine_Slider@@UEAAXXZ endp

?_NV_createMe@DataPanelLine_Slider@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_Slider@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_Slider::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_Slider@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+6*8]
?createMe@DataPanelLine_Slider@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_DESTRUCTOR@DataPanelLine_Slider@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_Slider@@QEAAXXZ endp

; DataPanelLine_Slider::~DataPanelLine_Slider();
??1DataPanelLine_Slider@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Slider_base+7*8]
??1DataPanelLine_Slider@@UEAA@XZ endp
