
; DataPanelLine_Progress::setProgress(float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setProgress@DataPanelLine_Progress@@QEAAXMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Progress_base+0*8]
?setProgress@DataPanelLine_Progress@@QEAAXMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@DataPanelLine_Progress@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_N@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_Progress@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_N@Z endp

; DataPanelLine_Progress::DataPanelLine_Progress(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool);
??0DataPanelLine_Progress@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Progress_base+1*8]
??0DataPanelLine_Progress@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_N@Z endp

?_NV_createMe@DataPanelLine_Progress@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_Progress@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_Progress::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_Progress@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Progress_base+2*8]
?createMe@DataPanelLine_Progress@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_DESTRUCTOR@DataPanelLine_Progress@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_Progress@@QEAAXXZ endp

; DataPanelLine_Progress::~DataPanelLine_Progress();
??1DataPanelLine_Progress@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Progress_base+3*8]
??1DataPanelLine_Progress@@UEAA@XZ endp
