
?_CONSTRUCTOR@DataPanelLine@@QEAAPEAV1@PEAVTextBox@MyGUI@@0PEAVButton@3@H@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine@@QEAAPEAV1@PEAVTextBox@MyGUI@@0PEAVButton@3@H@Z endp

; DataPanelLine::DataPanelLine(class MyGUI::TextBox *, class MyGUI::TextBox *, class MyGUI::Button *, int);
??0DataPanelLine@@QEAA@PEAVTextBox@MyGUI@@0PEAVButton@2@H@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+0*8]
??0DataPanelLine@@QEAA@PEAVTextBox@MyGUI@@0PEAVButton@2@H@Z endp

?_CONSTRUCTOR@DataPanelLine@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H00@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H00@Z endp

; DataPanelLine::DataPanelLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0DataPanelLine@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H00@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+1*8]
??0DataPanelLine@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H00@Z endp

?_CONSTRUCTOR@DataPanelLine@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H00@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H00@Z endp

; DataPanelLine::DataPanelLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0DataPanelLine@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H00@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+2*8]
??0DataPanelLine@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H00@Z endp

?_DESTRUCTOR@DataPanelLine@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine@@QEAAXXZ endp

; DataPanelLine::~DataPanelLine();
??1DataPanelLine@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_base+3*8]
??1DataPanelLine@@UEAA@XZ endp

?_NV_setVisible@DataPanelLine@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@DataPanelLine@@QEAAX_N@Z endp

; DataPanelLine::setVisible(bool);
?setVisible@DataPanelLine@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+4*8]
?setVisible@DataPanelLine@@UEAAX_N@Z endp

?_NV_setEnabled@DataPanelLine@@QEAAX_N@Z proc EXPORT
?_NV_setEnabled@DataPanelLine@@QEAAX_N@Z endp

; DataPanelLine::setEnabled(bool);
?setEnabled@DataPanelLine@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+5*8]
?setEnabled@DataPanelLine@@UEAAX_N@Z endp

?_NV_refresh@DataPanelLine@@QEAAXXZ proc EXPORT
?_NV_refresh@DataPanelLine@@QEAAXXZ endp

; DataPanelLine::refresh();
?refresh@DataPanelLine@@UEAAXXZ proc EXPORT
jmp function_pointers[_DataPanelLine_base+6*8]
?refresh@DataPanelLine@@UEAAXXZ endp

?_NV_updateValuePtr@DataPanelLine@@QEAAXPEAX@Z proc EXPORT
?_NV_updateValuePtr@DataPanelLine@@QEAAXPEAX@Z endp

; DataPanelLine::updateValuePtr(void *);
?updateValuePtr@DataPanelLine@@UEAAXPEAX@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+7*8]
?updateValuePtr@DataPanelLine@@UEAAXPEAX@Z endp

?_NV_setToolTip@DataPanelLine@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVToolTip@@@Z proc EXPORT
?_NV_setToolTip@DataPanelLine@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVToolTip@@@Z endp

; DataPanelLine::setToolTip(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class ToolTip *);
?setToolTip@DataPanelLine@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVToolTip@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+8*8]
?setToolTip@DataPanelLine@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVToolTip@@@Z endp

?_NV_setToolTip@DataPanelLine@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setToolTip@DataPanelLine@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DataPanelLine::setToolTip(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setToolTip@DataPanelLine@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+9*8]
?setToolTip@DataPanelLine@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_setToolTipMainBar@DataPanelLine@@QEAAXAEBV?$lektor@VStringPair@@@@_N@Z proc EXPORT
?_NV_setToolTipMainBar@DataPanelLine@@QEAAXAEBV?$lektor@VStringPair@@@@_N@Z endp

; DataPanelLine::setToolTipMainBar(const class lektor<StringPair> &, bool);
?setToolTipMainBar@DataPanelLine@@UEAAXAEBV?$lektor@VStringPair@@@@_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+10*8]
?setToolTipMainBar@DataPanelLine@@UEAAXAEBV?$lektor@VStringPair@@@@_N@Z endp

?_NV_setToolTipMainBar@DataPanelLine@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
?_NV_setToolTipMainBar@DataPanelLine@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; DataPanelLine::setToolTipMainBar(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setToolTipMainBar@DataPanelLine@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+11*8]
?setToolTipMainBar@DataPanelLine@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

?_NV_createMe@DataPanelLine@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+12*8]
?createMe@DataPanelLine@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_NV_resize@DataPanelLine@@QEAAXHH@Z proc EXPORT
?_NV_resize@DataPanelLine@@QEAAXHH@Z endp

; DataPanelLine::resize(int, int);
?resize@DataPanelLine@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+13*8]
?resize@DataPanelLine@@UEAAXHH@Z endp

?_NV_getBottom@DataPanelLine@@QEAAHXZ proc EXPORT
?_NV_getBottom@DataPanelLine@@QEAAHXZ endp

; DataPanelLine::getBottom();
?getBottom@DataPanelLine@@UEAAHXZ proc EXPORT
jmp function_pointers[_DataPanelLine_base+14*8]
?getBottom@DataPanelLine@@UEAAHXZ endp

; DataPanelLine::getType();
?getType@DataPanelLine@@QEBA?AW4LineType@1@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_base+15*8]
?getType@DataPanelLine@@QEBA?AW4LineType@1@XZ endp

?_NV_getUserData@DataPanelLine@@QEAA?AVhand@@XZ proc EXPORT
?_NV_getUserData@DataPanelLine@@QEAA?AVhand@@XZ endp

; DataPanelLine::getUserData();
?getUserData@DataPanelLine@@UEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_base+16*8]
?getUserData@DataPanelLine@@UEAA?AVhand@@XZ endp

; DataPanelLine::getNumWidgets();
?getNumWidgets@DataPanelLine@@QEBAHXZ proc EXPORT
jmp function_pointers[_DataPanelLine_base+17*8]
?getNumWidgets@DataPanelLine@@QEBAHXZ endp

; DataPanelLine::getWidget(int);
?getWidget@DataPanelLine@@QEBAPEAVWidget@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_DataPanelLine_base+18*8]
?getWidget@DataPanelLine@@QEBAPEAVWidget@MyGUI@@H@Z endp
