
?_NV_updateValuePtr@DataPanelLine_CheckBox@@QEAAXPEAX@Z proc EXPORT
?_NV_updateValuePtr@DataPanelLine_CheckBox@@QEAAXPEAX@Z endp

; DataPanelLine_CheckBox::updateValuePtr(void *);
?updateValuePtr@DataPanelLine_CheckBox@@UEAAXPEAX@Z proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+0*8]
?updateValuePtr@DataPanelLine_CheckBox@@UEAAXPEAX@Z endp

?_NV_refresh@DataPanelLine_CheckBox@@QEAAXXZ proc EXPORT
?_NV_refresh@DataPanelLine_CheckBox@@QEAAXXZ endp

; DataPanelLine_CheckBox::refresh();
?refresh@DataPanelLine_CheckBox@@UEAAXXZ proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+1*8]
?refresh@DataPanelLine_CheckBox@@UEAAXXZ endp

; DataPanelLine_CheckBox::setValue(bool);
?setValue@DataPanelLine_CheckBox@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+2*8]
?setValue@DataPanelLine_CheckBox@@QEAAX_N@Z endp

; DataPanelLine_CheckBox::setValuePtr(bool *);
?setValuePtr@DataPanelLine_CheckBox@@QEAAXPEA_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+3*8]
?setValuePtr@DataPanelLine_CheckBox@@QEAAXPEA_N@Z endp

; DataPanelLine_CheckBox::getTextBox();
?getTextBox@DataPanelLine_CheckBox@@QEBAPEAVEditBox@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+4*8]
?getTextBox@DataPanelLine_CheckBox@@QEBAPEAVEditBox@MyGUI@@XZ endp

; DataPanelLine_CheckBox::getCheckBox();
?getCheckBox@DataPanelLine_CheckBox@@QEBAPEAVButton@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+5*8]
?getCheckBox@DataPanelLine_CheckBox@@QEBAPEAVButton@MyGUI@@XZ endp

?_CONSTRUCTOR@DataPanelLine_CheckBox@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEA_N@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_CheckBox@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEA_N@Z endp

; DataPanelLine_CheckBox::DataPanelLine_CheckBox(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool *);
??0DataPanelLine_CheckBox@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEA_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+6*8]
??0DataPanelLine_CheckBox@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEA_N@Z endp

; DataPanelLine_CheckBox::notifyToggleCheck(class MyGUI::Widget *);
?notifyToggleCheck@DataPanelLine_CheckBox@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+7*8]
?notifyToggleCheck@DataPanelLine_CheckBox@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_createMe@DataPanelLine_CheckBox@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_CheckBox@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_CheckBox::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_CheckBox@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+8*8]
?createMe@DataPanelLine_CheckBox@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_DESTRUCTOR@DataPanelLine_CheckBox@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_CheckBox@@QEAAXXZ endp

; DataPanelLine_CheckBox::~DataPanelLine_CheckBox();
??1DataPanelLine_CheckBox@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_CheckBox_base+9*8]
??1DataPanelLine_CheckBox@@UEAA@XZ endp
