
; DataPanelLine_DropBox::addAValue(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?addAValue@DataPanelLine_DropBox@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+0*8]
?addAValue@DataPanelLine_DropBox@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; DataPanelLine_DropBox::getSelectedValue();
?getSelectedValue@DataPanelLine_DropBox@@QEAAHXZ proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+1*8]
?getSelectedValue@DataPanelLine_DropBox@@QEAAHXZ endp

; DataPanelLine_DropBox::setSelectedValue(int);
?setSelectedValue@DataPanelLine_DropBox@@QEAAXH@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+2*8]
?setSelectedValue@DataPanelLine_DropBox@@QEAAXH@Z endp

; DataPanelLine_DropBox::getSelectedText();
?getSelectedText@DataPanelLine_DropBox@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+3*8]
?getSelectedText@DataPanelLine_DropBox@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; DataPanelLine_DropBox::clearValues();
?clearValues@DataPanelLine_DropBox@@QEAAXXZ proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+4*8]
?clearValues@DataPanelLine_DropBox@@QEAAXXZ endp

; DataPanelLine_DropBox::getComboBox();
?getComboBox@DataPanelLine_DropBox@@QEAAPEAVComboBox@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+5*8]
?getComboBox@DataPanelLine_DropBox@@QEAAPEAVComboBox@MyGUI@@XZ endp

?_NV_createMe@DataPanelLine_DropBox@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_DropBox@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_DropBox::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_DropBox@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+6*8]
?createMe@DataPanelLine_DropBox@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_NV_updateValuePtr@DataPanelLine_DropBox@@QEAAXPEAX@Z proc EXPORT
?_NV_updateValuePtr@DataPanelLine_DropBox@@QEAAXPEAX@Z endp

; DataPanelLine_DropBox::updateValuePtr(void *);
?updateValuePtr@DataPanelLine_DropBox@@UEAAXPEAX@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+7*8]
?updateValuePtr@DataPanelLine_DropBox@@UEAAXPEAX@Z endp

?_NV_refresh@DataPanelLine_DropBox@@QEAAXXZ proc EXPORT
?_NV_refresh@DataPanelLine_DropBox@@QEAAXXZ endp

; DataPanelLine_DropBox::refresh();
?refresh@DataPanelLine_DropBox@@UEAAXXZ proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+8*8]
?refresh@DataPanelLine_DropBox@@UEAAXXZ endp

?_CONSTRUCTOR@DataPanelLine_DropBox@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEAHM_N@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_DropBox@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEAHM_N@Z endp

; DataPanelLine_DropBox::DataPanelLine_DropBox(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int *, float, bool);
??0DataPanelLine_DropBox@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEAHM_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+9*8]
??0DataPanelLine_DropBox@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HPEAHM_N@Z endp

; DataPanelLine_DropBox::selectionChange(class MyGUI::ComboBox *, unsigned __int64);
?selectionChange@DataPanelLine_DropBox@@QEAAXPEAVComboBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+10*8]
?selectionChange@DataPanelLine_DropBox@@QEAAXPEAVComboBox@MyGUI@@_K@Z endp

; DataPanelLine_DropBox::goPressed(class MyGUI::Widget *);
?goPressed@DataPanelLine_DropBox@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+11*8]
?goPressed@DataPanelLine_DropBox@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@DataPanelLine_DropBox@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_DropBox@@QEAAXXZ endp

; DataPanelLine_DropBox::~DataPanelLine_DropBox();
??1DataPanelLine_DropBox@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_DropBox_base+12*8]
??1DataPanelLine_DropBox@@UEAA@XZ endp
