
?_CONSTRUCTOR@DataObjectContainer@@QEAAPEAV1@PEAVRootObjectContainer@@@Z proc EXPORT
?_CONSTRUCTOR@DataObjectContainer@@QEAAPEAV1@PEAVRootObjectContainer@@@Z endp

; DataObjectContainer::DataObjectContainer(class RootObjectContainer *);
??0DataObjectContainer@@QEAA@PEAVRootObjectContainer@@@Z proc EXPORT
jmp function_pointers[_DataObjectContainer_base+0*8]
??0DataObjectContainer@@QEAA@PEAVRootObjectContainer@@@Z endp

?_CONSTRUCTOR@DataObjectContainer@@QEAAPEAV1@W4GroupType@1@@Z proc EXPORT
?_CONSTRUCTOR@DataObjectContainer@@QEAAPEAV1@W4GroupType@1@@Z endp

; DataObjectContainer::DataObjectContainer(enum DataObjectContainer::GroupType);
??0DataObjectContainer@@QEAA@W4GroupType@0@@Z proc EXPORT
jmp function_pointers[_DataObjectContainer_base+1*8]
??0DataObjectContainer@@QEAA@W4GroupType@0@@Z endp

?_DESTRUCTOR@DataObjectContainer@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataObjectContainer@@QEAAXXZ endp

; DataObjectContainer::~DataObjectContainer();
??1DataObjectContainer@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataObjectContainer_base+2*8]
??1DataObjectContainer@@UEAA@XZ endp

; DataObjectContainer::getType();
?getType@DataObjectContainer@@QEBA?AW4GroupType@1@XZ proc EXPORT
jmp function_pointers[_DataObjectContainer_base+3*8]
?getType@DataObjectContainer@@QEBA?AW4GroupType@1@XZ endp

; DataObjectContainer::setupDataFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class GameDataContainer *);
?setupDataFile@DataObjectContainer@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameDataContainer@@@Z proc EXPORT
jmp function_pointers[_DataObjectContainer_base+4*8]
?setupDataFile@DataObjectContainer@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameDataContainer@@@Z endp

; DataObjectContainer::destroyObjectDatas();
?destroyObjectDatas@DataObjectContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_DataObjectContainer_base+5*8]
?destroyObjectDatas@DataObjectContainer@@QEAAXXZ endp

?_NV_loadFromDisk@DataObjectContainer@@QEAA_N_NPEAVSerialisable@@@Z proc EXPORT
?_NV_loadFromDisk@DataObjectContainer@@QEAA_N_NPEAVSerialisable@@@Z endp

; DataObjectContainer::loadFromDisk(bool, class Serialisable *);
?loadFromDisk@DataObjectContainer@@UEAA_N_NPEAVSerialisable@@@Z proc EXPORT
jmp function_pointers[_DataObjectContainer_base+6*8]
?loadFromDisk@DataObjectContainer@@UEAA_N_NPEAVSerialisable@@@Z endp
