
?_CONSTRUCTOR@DataPanelLine_Button@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_Button@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0@Z endp

; DataPanelLine_Button::DataPanelLine_Button(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0DataPanelLine_Button@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+0*8]
??0DataPanelLine_Button@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HM0@Z endp

; DataPanelLine_Button::pressCallback(class MyGUI::Widget *);
?pressCallback@DataPanelLine_Button@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+1*8]
?pressCallback@DataPanelLine_Button@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_getUserData@DataPanelLine_Button@@QEAA?AVhand@@XZ proc EXPORT
?_NV_getUserData@DataPanelLine_Button@@QEAA?AVhand@@XZ endp

; DataPanelLine_Button::getUserData();
?getUserData@DataPanelLine_Button@@UEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+2*8]
?getUserData@DataPanelLine_Button@@UEAA?AVhand@@XZ endp

?_NV_createMe@DataPanelLine_Button@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_Button@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_Button::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_Button@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+3*8]
?createMe@DataPanelLine_Button@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

?_NV_setToolTipMainBar@DataPanelLine_Button@@QEAAXAEBV?$lektor@VStringPair@@@@_N@Z proc EXPORT
?_NV_setToolTipMainBar@DataPanelLine_Button@@QEAAXAEBV?$lektor@VStringPair@@@@_N@Z endp

; DataPanelLine_Button::setToolTipMainBar(const class lektor<StringPair> &, bool);
?setToolTipMainBar@DataPanelLine_Button@@UEAAXAEBV?$lektor@VStringPair@@@@_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+4*8]
?setToolTipMainBar@DataPanelLine_Button@@UEAAXAEBV?$lektor@VStringPair@@@@_N@Z endp

?_NV_setToolTipMainBar@DataPanelLine_Button@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
?_NV_setToolTipMainBar@DataPanelLine_Button@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; DataPanelLine_Button::setToolTipMainBar(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setToolTipMainBar@DataPanelLine_Button@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+5*8]
?setToolTipMainBar@DataPanelLine_Button@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

?_DESTRUCTOR@DataPanelLine_Button@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_Button@@QEAAXXZ endp

; DataPanelLine_Button::~DataPanelLine_Button();
??1DataPanelLine_Button@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_Button_base+6*8]
??1DataPanelLine_Button@@UEAA@XZ endp
