
; DataPanelLine_SliderEditable::setEditableValuePtr(float *, float, float);
?setEditableValuePtr@DataPanelLine_SliderEditable@@QEAAXPEAMMM@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+0*8]
?setEditableValuePtr@DataPanelLine_SliderEditable@@QEAAXPEAMMM@Z endp

; DataPanelLine_SliderEditable::getSlider();
?getSlider@DataPanelLine_SliderEditable@@QEAAPEAVScrollBar@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+1*8]
?getSlider@DataPanelLine_SliderEditable@@QEAAPEAVScrollBar@MyGUI@@XZ endp

; DataPanelLine_SliderEditable::getEditBox();
?getEditBox@DataPanelLine_SliderEditable@@QEAAPEAVEditBox@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+2*8]
?getEditBox@DataPanelLine_SliderEditable@@QEAAPEAVEditBox@MyGUI@@XZ endp

?_NV_updateValuePtr@DataPanelLine_SliderEditable@@QEAAXPEAX@Z proc EXPORT
?_NV_updateValuePtr@DataPanelLine_SliderEditable@@QEAAXPEAX@Z endp

; DataPanelLine_SliderEditable::updateValuePtr(void *);
?updateValuePtr@DataPanelLine_SliderEditable@@UEAAXPEAX@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+3*8]
?updateValuePtr@DataPanelLine_SliderEditable@@UEAAXPEAX@Z endp

; DataPanelLine_SliderEditable::setValue(float);
?setValue@DataPanelLine_SliderEditable@@QEAAXM@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+4*8]
?setValue@DataPanelLine_SliderEditable@@QEAAXM@Z endp

?_NV_refresh@DataPanelLine_SliderEditable@@QEAAXXZ proc EXPORT
?_NV_refresh@DataPanelLine_SliderEditable@@QEAAXXZ endp

; DataPanelLine_SliderEditable::refresh();
?refresh@DataPanelLine_SliderEditable@@UEAAXXZ proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+5*8]
?refresh@DataPanelLine_SliderEditable@@UEAAXXZ endp

; DataPanelLine_SliderEditable::setPrecision(int);
?setPrecision@DataPanelLine_SliderEditable@@QEAAXH@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+6*8]
?setPrecision@DataPanelLine_SliderEditable@@QEAAXH@Z endp

?_CONSTRUCTOR@DataPanelLine_SliderEditable@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_NMMPEAM@Z proc EXPORT
?_CONSTRUCTOR@DataPanelLine_SliderEditable@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_NMMPEAM@Z endp

; DataPanelLine_SliderEditable::DataPanelLine_SliderEditable(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, float, float, float *);
??0DataPanelLine_SliderEditable@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_NMMPEAM@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+7*8]
??0DataPanelLine_SliderEditable@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H_NMMPEAM@Z endp

?_NV_createMe@DataPanelLine_SliderEditable@@QEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
?_NV_createMe@DataPanelLine_SliderEditable@@QEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_SliderEditable::createMe(class DatapanelGUI *, float, bool);
?createMe@DataPanelLine_SliderEditable@@UEAAXPEAVDatapanelGUI@@M_N@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+8*8]
?createMe@DataPanelLine_SliderEditable@@UEAAXPEAVDatapanelGUI@@M_N@Z endp

; DataPanelLine_SliderEditable::editCallback(class MyGUI::EditBox *);
?editCallback@DataPanelLine_SliderEditable@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+9*8]
?editCallback@DataPanelLine_SliderEditable@@QEAAXPEAVEditBox@MyGUI@@@Z endp

; DataPanelLine_SliderEditable::sliderCallback(class MyGUI::ScrollBar *, unsigned __int64);
?sliderCallback@DataPanelLine_SliderEditable@@QEAAXPEAVScrollBar@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+10*8]
?sliderCallback@DataPanelLine_SliderEditable@@QEAAXPEAVScrollBar@MyGUI@@_K@Z endp

?_DESTRUCTOR@DataPanelLine_SliderEditable@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DataPanelLine_SliderEditable@@QEAAXXZ endp

; DataPanelLine_SliderEditable::~DataPanelLine_SliderEditable();
??1DataPanelLine_SliderEditable@@UEAA@XZ proc EXPORT
jmp function_pointers[_DataPanelLine_SliderEditable_base+11*8]
??1DataPanelLine_SliderEditable@@UEAA@XZ endp
