
; DialogueWindow::getVisible();
?getVisible@DialogueWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+0*8]
?getVisible@DialogueWindow@@QEBA_NXZ endp

; DialogueWindow::setVisible(bool);
?setVisible@DialogueWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+1*8]
?setVisible@DialogueWindow@@QEAAX_N@Z endp

?_NV_show@DialogueWindow@@QEAAX_N@Z proc EXPORT
?_NV_show@DialogueWindow@@QEAAX_N@Z endp

; DialogueWindow::show(bool);
?show@DialogueWindow@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+2*8]
?show@DialogueWindow@@UEAAX_N@Z endp

; DialogueWindow::show(class Dialogue *);
?show@DialogueWindow@@QEAAXPEAVDialogue@@@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+3*8]
?show@DialogueWindow@@QEAAXPEAVDialogue@@@Z endp

; DialogueWindow::hide(class Dialogue *);
?hide@DialogueWindow@@QEAAXPEAVDialogue@@@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+4*8]
?hide@DialogueWindow@@QEAAXPEAVDialogue@@@Z endp

?_NV_isVisible@DialogueWindow@@QEBA_NXZ proc EXPORT
?_NV_isVisible@DialogueWindow@@QEBA_NXZ endp

; DialogueWindow::isVisible();
?isVisible@DialogueWindow@@UEBA_NXZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+5*8]
?isVisible@DialogueWindow@@UEBA_NXZ endp

?_NV_update@DialogueWindow@@QEAAXXZ proc EXPORT
?_NV_update@DialogueWindow@@QEAAXXZ endp

; DialogueWindow::update();
?update@DialogueWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+6*8]
?update@DialogueWindow@@UEAAXXZ endp

; DialogueWindow::getTop();
?getTop@DialogueWindow@@QEBAHXZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+7*8]
?getTop@DialogueWindow@@QEBAHXZ endp

; DialogueWindow::activateResponse(int);
?activateResponse@DialogueWindow@@QEAAXH@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+8*8]
?activateResponse@DialogueWindow@@QEAAXH@Z endp

; DialogueWindow::setNPCText(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setNPCText@DialogueWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+9*8]
?setNPCText@DialogueWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DialogueWindow::setResponses(const class std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,Ogre::STLAllocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,Ogre::CategorisedAllocPolicy<0> > > &);
?setResponses@DialogueWindow@@QEAAXAEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$STLAllocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+10*8]
?setResponses@DialogueWindow@@QEAAXAEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$STLAllocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; DialogueWindow::clearResponses();
?clearResponses@DialogueWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+11*8]
?clearResponses@DialogueWindow@@QEAAXXZ endp

; DialogueWindow::changePortrait(class Character *, bool);
?changePortrait@DialogueWindow@@QEAAXPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_DialogueWindow_base+12*8]
?changePortrait@DialogueWindow@@QEAAXPEAVCharacter@@_N@Z endp

?_CONSTRUCTOR@DialogueWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@DialogueWindow@@QEAAPEAV1@XZ endp

; DialogueWindow::DialogueWindow();
??0DialogueWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+13*8]
??0DialogueWindow@@QEAA@XZ endp

?_DESTRUCTOR@DialogueWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DialogueWindow@@QEAAXXZ endp

; DialogueWindow::~DialogueWindow();
??1DialogueWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+14*8]
??1DialogueWindow@@UEAA@XZ endp

; DialogueWindow::updatePanelsPosition();
?updatePanelsPosition@DialogueWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_DialogueWindow_base+15*8]
?updatePanelsPosition@DialogueWindow@@QEAAXXZ endp
