
; Dialogue::getWordSwap(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Character *, bool, class DialogLineData *);
?getWordSwap@Dialogue@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@PEAVCharacter@@_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+0*8]
?getWordSwap@Dialogue@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@PEAVCharacter@@_NPEAVDialogLineData@@@Z endp

; Dialogue::setupWordSwaps();
?setupWordSwaps@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+1*8]
?setupWordSwaps@Dialogue@@QEAAXXZ endp

; Dialogue::_insertWordSwapsRecurse(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Character *, bool, class DialogLineData *);
?_insertWordSwapsRecurse@Dialogue@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+2*8]
?_insertWordSwapsRecurse@Dialogue@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@_NPEAVDialogLineData@@@Z endp

?_CONSTRUCTOR@Dialogue@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@Dialogue@@QEAAPEAV1@XZ endp

; Dialogue::Dialogue();
??0Dialogue@@QEAA@XZ proc EXPORT
jmp function_pointers[_Dialogue_base+3*8]
??0Dialogue@@QEAA@XZ endp

?_DESTRUCTOR@Dialogue@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Dialogue@@QEAAXXZ endp

; Dialogue::~Dialogue();
??1Dialogue@@QEAA@XZ proc EXPORT
jmp function_pointers[_Dialogue_base+4*8]
??1Dialogue@@QEAA@XZ endp

; Dialogue::insertWordSwaps(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Character *, bool, class DialogLineData *);
?insertWordSwaps@Dialogue@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+5*8]
?insertWordSwaps@Dialogue@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVCharacter@@_NPEAVDialogLineData@@@Z endp

; Dialogue::getGUIData(class DatapanelGUI *, int);
?getGUIData@Dialogue@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Dialogue_base+6*8]
?getGUIData@Dialogue@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Dialogue::create(class Character *, class CharStats *, class CharMovement *);
?create@Dialogue@@QEAAXPEAVCharacter@@PEAVCharStats@@PEAVCharMovement@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+7*8]
?create@Dialogue@@QEAAXPEAVCharacter@@PEAVCharStats@@PEAVCharMovement@@@Z endp

; Dialogue::getHandle();
?getHandle@Dialogue@@QEBA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Dialogue_base+8*8]
?getHandle@Dialogue@@QEBA?AVhand@@XZ endp

; Dialogue::getCharacter();
?getCharacter@Dialogue@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_Dialogue_base+9*8]
?getCharacter@Dialogue@@QEAAPEAVCharacter@@XZ endp

; Dialogue::setLineLocked(class DialogLineData *, bool);
?setLineLocked@Dialogue@@QEAAXPEAVDialogLineData@@_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+10*8]
?setLineLocked@Dialogue@@QEAAXPEAVDialogLineData@@_N@Z endp

; Dialogue::isLocked(class DialogLineData *);
?isLocked@Dialogue@@QEAA_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+11*8]
?isLocked@Dialogue@@QEAA_NPEAVDialogLineData@@@Z endp

; Dialogue::setInDialog(bool);
?setInDialog@Dialogue@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+12*8]
?setInDialog@Dialogue@@QEAAX_N@Z endp

; Dialogue::clearDialogues();
?clearDialogues@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+13*8]
?clearDialogues@Dialogue@@QEAAXXZ endp

; Dialogue::clearAnnouncements();
?clearAnnouncements@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+14*8]
?clearAnnouncements@Dialogue@@QEAAXXZ endp

; Dialogue::needsDialogAssessmentUpdate();
?needsDialogAssessmentUpdate@Dialogue@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Dialogue_base+15*8]
?needsDialogAssessmentUpdate@Dialogue@@QEBA_NXZ endp

; Dialogue::addDialoguePackage(class GameData *);
?addDialoguePackage@Dialogue@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+16*8]
?addDialoguePackage@Dialogue@@QEAAXPEAVGameData@@@Z endp

; Dialogue::addConversation(class GameData *, enum EventTriggerEnum);
?addConversation@Dialogue@@QEAAXPEAVGameData@@W4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+17*8]
?addConversation@Dialogue@@QEAAXPEAVGameData@@W4EventTriggerEnum@@@Z endp

; Dialogue::clearConversationList(enum EventTriggerEnum);
?clearConversationList@Dialogue@@QEAAXW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+18*8]
?clearConversationList@Dialogue@@QEAAXW4EventTriggerEnum@@@Z endp

; Dialogue::willTalkToEnemies();
?willTalkToEnemies@Dialogue@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Dialogue_base+19*8]
?willTalkToEnemies@Dialogue@@QEAA_NXZ endp

; Dialogue::sendEventOverride(class Character *, enum EventTriggerEnum, bool);
?sendEventOverride@Dialogue@@QEAA_NPEAVCharacter@@W4EventTriggerEnum@@_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+20*8]
?sendEventOverride@Dialogue@@QEAA_NPEAVCharacter@@W4EventTriggerEnum@@_N@Z endp

; Dialogue::sendEvent(class Character *, enum EventTriggerEnum);
?sendEvent@Dialogue@@QEAA_NPEAVCharacter@@W4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+21*8]
?sendEvent@Dialogue@@QEAA_NPEAVCharacter@@W4EventTriggerEnum@@@Z endp

; Dialogue::stopEvent(enum EventTriggerEnum);
?stopEvent@Dialogue@@QEAAXW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+22*8]
?stopEvent@Dialogue@@QEAAXW4EventTriggerEnum@@@Z endp

; Dialogue::runCustomDialog(class GameData *);
?runCustomDialog@Dialogue@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+23*8]
?runCustomDialog@Dialogue@@QEAA_NPEAVGameData@@@Z endp

; Dialogue::scoreCustomDialog(class GameData *);
?scoreCustomDialog@Dialogue@@QEAAHPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+24*8]
?scoreCustomDialog@Dialogue@@QEAAHPEAVGameData@@@Z endp

; Dialogue::conversationHasEnded();
?conversationHasEnded@Dialogue@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Dialogue_base+25*8]
?conversationHasEnded@Dialogue@@QEBA_NXZ endp

; Dialogue::getConversationTarget();
?getConversationTarget@Dialogue@@QEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Dialogue_base+26*8]
?getConversationTarget@Dialogue@@QEAA?AVhand@@XZ endp

; Dialogue::changeConversationTarget(class Character *);
?changeConversationTarget@Dialogue@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+27*8]
?changeConversationTarget@Dialogue@@QEAAXPEAVCharacter@@@Z endp

; Dialogue::conversationHasEndedPrettyMuch();
?conversationHasEndedPrettyMuch@Dialogue@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Dialogue_base+28*8]
?conversationHasEndedPrettyMuch@Dialogue@@QEBA_NXZ endp

; Dialogue::makeAnnouncement(class GameData *);
?makeAnnouncement@Dialogue@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+29*8]
?makeAnnouncement@Dialogue@@QEAA_NPEAVGameData@@@Z endp

; Dialogue::update(float);
?update@Dialogue@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Dialogue_base+30*8]
?update@Dialogue@@QEAAXM@Z endp

; Dialogue::endDialogue(bool);
?endDialogue@Dialogue@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+31*8]
?endDialogue@Dialogue@@QEAAX_N@Z endp

; Dialogue::notifyUnderAttack(class Character *);
?notifyUnderAttack@Dialogue@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+32*8]
?notifyUnderAttack@Dialogue@@QEAAXPEAVCharacter@@@Z endp

; Dialogue::hasDialogue_Fast();
?hasDialogue_Fast@Dialogue@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Dialogue_base+33*8]
?hasDialogue_Fast@Dialogue@@QEAA_NXZ endp

; Dialogue::hasDialogue_Accurate();
?hasDialogue_Accurate@Dialogue@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Dialogue_base+34*8]
?hasDialogue_Accurate@Dialogue@@QEAA_NXZ endp

; Dialogue::hasDialogueEvent(enum EventTriggerEnum);
?hasDialogueEvent@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+35*8]
?hasDialogueEvent@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z endp

; Dialogue::say(class DialogLineData *);
?say@Dialogue@@QEAAXPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+36*8]
?say@Dialogue@@QEAAXPEAVDialogLineData@@@Z endp

; Dialogue::say(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class DialogLineData *);
?say@Dialogue@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+37*8]
?say@Dialogue@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVDialogLineData@@@Z endp

; Dialogue::dialogDelivered(enum EventTriggerEnum);
?dialogDelivered@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+38*8]
?dialogDelivered@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z endp

; Dialogue::_checkCondition(enum DialogConditionEnum, enum ComparisonEnum, int, class Character *, class Character *);
?_checkCondition@Dialogue@@QEAA_NW4DialogConditionEnum@@W4ComparisonEnum@@HPEAVCharacter@@2@Z proc EXPORT
jmp function_pointers[_Dialogue_base+39*8]
?_checkCondition@Dialogue@@QEAA_NW4DialogConditionEnum@@W4ComparisonEnum@@HPEAVCharacter@@2@Z endp

; Dialogue::dontLetTargetBeMe(class Character * *, class Character *);
?dontLetTargetBeMe@Dialogue@@QEAAXPEAPEAVCharacter@@PEAV2@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+40*8]
?dontLetTargetBeMe@Dialogue@@QEAAXPEAPEAVCharacter@@PEAV2@@Z endp

; Dialogue::isAtTownOf(const class std::set<Faction *,std::less<Faction *>,Ogre::STLAllocator<Faction *,Ogre::CategorisedAllocPolicy<0> > > &);
?isAtTownOf@Dialogue@@QEAA_NAEBV?$set@PEAVFaction@@U?$less@PEAVFaction@@@std@@V?$STLAllocator@PEAVFaction@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+41*8]
?isAtTownOf@Dialogue@@QEAA_NAEBV?$set@PEAVFaction@@U?$less@PEAVFaction@@@std@@V?$STLAllocator@PEAVFaction@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Dialogue::hasThisChanceLine(class DialogLineData *, float);
?hasThisChanceLine@Dialogue@@QEAA_NPEAVDialogLineData@@M@Z proc EXPORT
jmp function_pointers[_Dialogue_base+42*8]
?hasThisChanceLine@Dialogue@@QEAA_NPEAVDialogLineData@@M@Z endp

; Dialogue::_chooseDialog(class DialogChoiceList *, class Character *, bool);
?_chooseDialog@Dialogue@@QEAAPEAVDialogLineData@@PEAVDialogChoiceList@@PEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+43*8]
?_chooseDialog@Dialogue@@QEAAPEAVDialogLineData@@PEAVDialogChoiceList@@PEAVCharacter@@_N@Z endp

; Dialogue::triggerNextLine(class DialogLineData *);
?triggerNextLine@Dialogue@@QEAAXPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+44*8]
?triggerNextLine@Dialogue@@QEAAXPEAVDialogLineData@@@Z endp

; Dialogue::targetInTalkingRange(class Character *, float);
?targetInTalkingRange@Dialogue@@QEAA_NPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_Dialogue_base+45*8]
?targetInTalkingRange@Dialogue@@QEAA_NPEAVCharacter@@M@Z endp

; Dialogue::save(class GameData *);
?save@Dialogue@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+46*8]
?save@Dialogue@@QEAAXPEAVGameData@@@Z endp

; Dialogue::load(class GameData *);
?load@Dialogue@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+47*8]
?load@Dialogue@@QEAAXPEAVGameData@@@Z endp

; Dialogue::replyClicked(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?replyClicked@Dialogue@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+48*8]
?replyClicked@Dialogue@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Dialogue::replyClicked(int);
?replyClicked@Dialogue@@QEAAXH@Z proc EXPORT
jmp function_pointers[_Dialogue_base+49*8]
?replyClicked@Dialogue@@QEAAXH@Z endp

; Dialogue::getSpeaker(enum TalkerEnum, class DialogLineData *, bool);
?getSpeaker@Dialogue@@QEAAPEAVCharacter@@W4TalkerEnum@@PEAVDialogLineData@@_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+50*8]
?getSpeaker@Dialogue@@QEAAPEAVCharacter@@W4TalkerEnum@@PEAVDialogLineData@@_N@Z endp

; Dialogue::isCurrentConversationRunning(class DialogLineData *);
?isCurrentConversationRunning@Dialogue@@QEBA_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+51*8]
?isCurrentConversationRunning@Dialogue@@QEBA_NPEAVDialogLineData@@@Z endp

; Dialogue::resolveOverlappedSpeechBubbles();
?resolveOverlappedSpeechBubbles@Dialogue@@SAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+52*8]
?resolveOverlappedSpeechBubbles@Dialogue@@SAXXZ endp

; Dialogue::_wordSwapCharacterName(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_wordSwapCharacterName@Dialogue@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+53*8]
?_wordSwapCharacterName@Dialogue@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Dialogue::findInterjectionCharacter(class DialogLineData *);
?findInterjectionCharacter@Dialogue@@QEAAPEAVCharacter@@PEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+54*8]
?findInterjectionCharacter@Dialogue@@QEAAPEAVCharacter@@PEAVDialogLineData@@@Z endp

; Dialogue::isKOExempt(enum EventTriggerEnum);
?isKOExempt@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+55*8]
?isKOExempt@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z endp

; Dialogue::_endPlayerConversation(bool);
?_endPlayerConversation@Dialogue@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+56*8]
?_endPlayerConversation@Dialogue@@QEAAX_N@Z endp

; Dialogue::startPlayerConversation(class Character *, class DialogLineData *);
?startPlayerConversation@Dialogue@@QEAA_NPEAVCharacter@@PEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+57*8]
?startPlayerConversation@Dialogue@@QEAA_NPEAVCharacter@@PEAVDialogLineData@@@Z endp

; Dialogue::startConversation(class Character *, class DialogLineData *, enum EventTriggerEnum, bool);
?startConversation@Dialogue@@QEAA_NPEAVCharacter@@PEAVDialogLineData@@W4EventTriggerEnum@@_N@Z proc EXPORT
jmp function_pointers[_Dialogue_base+58*8]
?startConversation@Dialogue@@QEAA_NPEAVCharacter@@PEAVDialogLineData@@W4EventTriggerEnum@@_N@Z endp

; Dialogue::getConversationList(enum EventTriggerEnum);
?getConversationList@Dialogue@@QEAAPEAVDialogChoiceList@@W4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+59*8]
?getConversationList@Dialogue@@QEAAPEAVDialogChoiceList@@W4EventTriggerEnum@@@Z endp

; Dialogue::_doActions(class DialogLineData *);
?_doActions@Dialogue@@QEAAXPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+60*8]
?_doActions@Dialogue@@QEAAXPEAVDialogLineData@@@Z endp

; Dialogue::sayLine(class DialogLineData *);
?sayLine@Dialogue@@QEAA_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+61*8]
?sayLine@Dialogue@@QEAA_NPEAVDialogLineData@@@Z endp

; Dialogue::listPlayerReplies();
?listPlayerReplies@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+62*8]
?listPlayerReplies@Dialogue@@QEAAXXZ endp

; Dialogue::isLastLine(class DialogLineData *);
?isLastLine@Dialogue@@QEAA_NPEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+63*8]
?isLastLine@Dialogue@@QEAA_NPEAVDialogLineData@@@Z endp

; Dialogue::setSpeaker(enum TalkerEnum, class Character *);
?setSpeaker@Dialogue@@QEAAXW4TalkerEnum@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_Dialogue_base+64*8]
?setSpeaker@Dialogue@@QEAAXW4TalkerEnum@@PEAVCharacter@@@Z endp

; Dialogue::_updateTextPos();
?_updateTextPos@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+65*8]
?_updateTextPos@Dialogue@@QEAAXXZ endp

; Dialogue::clearSpeechBox();
?clearSpeechBox@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+66*8]
?clearSpeechBox@Dialogue@@QEAAXXZ endp

; Dialogue::clearRespones();
?clearRespones@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+67*8]
?clearRespones@Dialogue@@QEAAXXZ endp

; Dialogue::clearResponesGUI();
?clearResponesGUI@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+68*8]
?clearResponesGUI@Dialogue@@QEAAXXZ endp

; Dialogue::setResponesGUI();
?setResponesGUI@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+69*8]
?setResponesGUI@Dialogue@@QEAAXXZ endp

; Dialogue::setConversationReplyGUI();
?setConversationReplyGUI@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_base+70*8]
?setConversationReplyGUI@Dialogue@@QEAAXXZ endp
