
?_CONSTRUCTOR@DialogueSpeechBubble@@QEAAPEAV1@_N0@Z proc EXPORT
?_CONSTRUCTOR@DialogueSpeechBubble@@QEAAPEAV1@_N0@Z endp

; DialogueSpeechBubble::DialogueSpeechBubble(bool, bool);
??0DialogueSpeechBubble@@QEAA@_N0@Z proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+0*8]
??0DialogueSpeechBubble@@QEAA@_N0@Z endp

?_DESTRUCTOR@DialogueSpeechBubble@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DialogueSpeechBubble@@QEAAXXZ endp

; DialogueSpeechBubble::~DialogueSpeechBubble();
??1DialogueSpeechBubble@@UEAA@XZ proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+1*8]
??1DialogueSpeechBubble@@UEAA@XZ endp

; DialogueSpeechBubble::setText(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setText@DialogueSpeechBubble@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+2*8]
?setText@DialogueSpeechBubble@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DialogueSpeechBubble::setAlpha(float);
?setAlpha@DialogueSpeechBubble@@QEAAXM@Z proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+3*8]
?setAlpha@DialogueSpeechBubble@@QEAAXM@Z endp

; DialogueSpeechBubble::setPosition(int, int);
?setPosition@DialogueSpeechBubble@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+4*8]
?setPosition@DialogueSpeechBubble@@QEAAXHH@Z endp

; DialogueSpeechBubble::setPosition(const class Ogre::Vector3 &);
?setPosition@DialogueSpeechBubble@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+5*8]
?setPosition@DialogueSpeechBubble@@QEAAXAEBVVector3@Ogre@@@Z endp

; DialogueSpeechBubble::reset();
?reset@DialogueSpeechBubble@@QEAAXXZ proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+6*8]
?reset@DialogueSpeechBubble@@QEAAXXZ endp

; DialogueSpeechBubble::getAlpha();
?getAlpha@DialogueSpeechBubble@@QEBAMXZ proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+7*8]
?getAlpha@DialogueSpeechBubble@@QEBAMXZ endp

; DialogueSpeechBubble::getRect();
?getRect@DialogueSpeechBubble@@QEBA?AU?$TRect@H@types@MyGUI@@XZ proc EXPORT
jmp function_pointers[_DialogueSpeechBubble_base+8*8]
?getRect@DialogueSpeechBubble@@QEBA?AU?$TRect@H@types@MyGUI@@XZ endp
