
; Dialogue::RepetitionCounter::setup();
?setup@RepetitionCounter@Dialogue@@QEAAXXZ proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_base+0*8]
?setup@RepetitionCounter@Dialogue@@QEAAXXZ endp

; Dialogue::RepetitionCounter::count(enum EventTriggerEnum);
?count@RepetitionCounter@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_base+1*8]
?count@RepetitionCounter@Dialogue@@QEAA_NW4EventTriggerEnum@@@Z endp

; Dialogue::RepetitionCounter::getTimeSinceLastTrigger(enum EventTriggerEnum);
?getTimeSinceLastTrigger@RepetitionCounter@Dialogue@@QEAANW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_base+2*8]
?getTimeSinceLastTrigger@RepetitionCounter@Dialogue@@QEAANW4EventTriggerEnum@@@Z endp

; Dialogue::RepetitionCounter::getCount(enum EventTriggerEnum);
?getCount@RepetitionCounter@Dialogue@@QEAAHW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_base+3*8]
?getCount@RepetitionCounter@Dialogue@@QEAAHW4EventTriggerEnum@@@Z endp

?_CONSTRUCTOR@RepetitionCounter@Dialogue@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@RepetitionCounter@Dialogue@@QEAAPEAV12@XZ endp

; Dialogue::RepetitionCounter::RepetitionCounter();
??0RepetitionCounter@Dialogue@@QEAA@XZ proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_base+4*8]
??0RepetitionCounter@Dialogue@@QEAA@XZ endp

?_DESTRUCTOR@RepetitionCounter@Dialogue@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RepetitionCounter@Dialogue@@QEAAXXZ endp

; Dialogue::RepetitionCounter::~RepetitionCounter();
??1RepetitionCounter@Dialogue@@QEAA@XZ proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_base+5*8]
??1RepetitionCounter@Dialogue@@QEAA@XZ endp
