
?_CONSTRUCTOR@DialogChoiceList@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@DialogChoiceList@@QEAAPEAV1@XZ endp

; DialogChoiceList::DialogChoiceList();
??0DialogChoiceList@@QEAA@XZ proc EXPORT
jmp function_pointers[_DialogChoiceList_base+0*8]
??0DialogChoiceList@@QEAA@XZ endp

?_DESTRUCTOR@DialogChoiceList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DialogChoiceList@@QEAAXXZ endp

; DialogChoiceList::~DialogChoiceList();
??1DialogChoiceList@@QEAA@XZ proc EXPORT
jmp function_pointers[_DialogChoiceList_base+1*8]
??1DialogChoiceList@@QEAA@XZ endp

; DialogChoiceList::add(class GameData *, class DialogLineData *);
?add@DialogChoiceList@@QEAAXPEAVGameData@@PEAVDialogLineData@@@Z proc EXPORT
jmp function_pointers[_DialogChoiceList_base+2*8]
?add@DialogChoiceList@@QEAAXPEAVGameData@@PEAVDialogLineData@@@Z endp
