
; DialogDataManager::_createData(class GameData *);
?_createData@DialogDataManager@@SAPEAVDialogLineData@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_DialogDataManager_base+0*8]
?_createData@DialogDataManager@@SAPEAVDialogLineData@@PEAVGameData@@@Z endp

; DialogDataManager::initialise();
?initialise@DialogDataManager@@SAXXZ proc EXPORT
jmp function_pointers[_DialogDataManager_base+1*8]
?initialise@DialogDataManager@@SAXXZ endp

; DialogDataManager::save(class GameData *);
?save@DialogDataManager@@SAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_DialogDataManager_base+2*8]
?save@DialogDataManager@@SAXPEAVGameData@@@Z endp

; DialogDataManager::load(class GameData *);
?load@DialogDataManager@@SAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_DialogDataManager_base+3*8]
?load@DialogDataManager@@SAXPEAVGameData@@@Z endp

; DialogDataManager::newGameReset();
?newGameReset@DialogDataManager@@SAXXZ proc EXPORT
jmp function_pointers[_DialogDataManager_base+4*8]
?newGameReset@DialogDataManager@@SAXXZ endp

; DialogDataManager::getData(class GameData *);
?getData@DialogDataManager@@SAPEAVDialogLineData@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_DialogDataManager_base+5*8]
?getData@DialogDataManager@@SAPEAVDialogLineData@@PEAVGameData@@@Z endp
