
; DialogLineData::getParent();
?getParent@DialogLineData@@QEBAPEAV1@XZ proc EXPORT
jmp function_pointers[_DialogLineData_base+0*8]
?getParent@DialogLineData@@QEBAPEAV1@XZ endp

; DialogLineData::isForSpecificCharacter(class GameData *);
?isForSpecificCharacter@DialogLineData@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+1*8]
?isForSpecificCharacter@DialogLineData@@QEAA_NPEAVGameData@@@Z endp

; DialogLineData::hasSpecificCharacterRequirement();
?hasSpecificCharacterRequirement@DialogLineData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+2*8]
?hasSpecificCharacterRequirement@DialogLineData@@QEBA_NXZ endp

; DialogLineData::_initialiseAList(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class lektor<GameDataValuePair> *);
?_initialiseAList@DialogLineData@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$lektor@VGameDataValuePair@@@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+3*8]
?_initialiseAList@DialogLineData@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$lektor@VGameDataValuePair@@@@@Z endp

; DialogLineData::_initialiseAList(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class lektor<GameData *> *);
?_initialiseAList@DialogLineData@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+4*8]
?_initialiseAList@DialogLineData@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$lektor@PEAVGameData@@@@@Z endp

?_CONSTRUCTOR@DialogLineData@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@DialogLineData@@QEAAPEAV1@PEAVGameData@@@Z endp

; DialogLineData::DialogLineData(class GameData *);
??0DialogLineData@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+5*8]
??0DialogLineData@@QEAA@PEAVGameData@@@Z endp

?_DESTRUCTOR@DialogLineData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DialogLineData@@QEAAXXZ endp

; DialogLineData::~DialogLineData();
??1DialogLineData@@UEAA@XZ proc EXPORT
jmp function_pointers[_DialogLineData_base+6*8]
??1DialogLineData@@UEAA@XZ endp

; DialogLineData::setupChildren();
?setupChildren@DialogLineData@@QEAAXXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+7*8]
?setupChildren@DialogLineData@@QEAAXXZ endp

; DialogLineData::checkRepeatLimits();
?checkRepeatLimits@DialogLineData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+8*8]
?checkRepeatLimits@DialogLineData@@QEAA_NXZ endp

; DialogLineData::checkTags(class Character *, class Character *);
?checkTags@DialogLineData@@QEAA_NPEAVCharacter@@0@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+9*8]
?checkTags@DialogLineData@@QEAA_NPEAVCharacter@@0@Z endp

; DialogLineData::getName();
?getName@DialogLineData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_DialogLineData_base+10*8]
?getName@DialogLineData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; DialogLineData::saidItBefore();
?saidItBefore@DialogLineData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+11*8]
?saidItBefore@DialogLineData@@QEAA_NXZ endp

; DialogLineData::willTalkToEnemies();
?willTalkToEnemies@DialogLineData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+12*8]
?willTalkToEnemies@DialogLineData@@QEAA_NXZ endp

?_NV_isEmptyNode@DialogLineData@@QEBA_NXZ proc EXPORT
?_NV_isEmptyNode@DialogLineData@@QEBA_NXZ endp

; DialogLineData::isEmptyNode();
?isEmptyNode@DialogLineData@@UEBA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+13*8]
?isEmptyNode@DialogLineData@@UEBA_NXZ endp

; DialogLineData::isAnnouncement();
?isAnnouncement@DialogLineData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+14*8]
?isAnnouncement@DialogLineData@@QEAA_NXZ endp

; DialogLineData::stampLastTimeSaid();
?stampLastTimeSaid@DialogLineData@@QEAAXXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+15*8]
?stampLastTimeSaid@DialogLineData@@QEAAXXZ endp

; DialogLineData::getScore(class Character *);
?getScore@DialogLineData@@QEBAHPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+16*8]
?getScore@DialogLineData@@QEBAHPEAVCharacter@@@Z endp

; DialogLineData::getScorePlusChildrenIfEmpty(class Character *);
?getScorePlusChildrenIfEmpty@DialogLineData@@QEAAHPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+17*8]
?getScorePlusChildrenIfEmpty@DialogLineData@@QEAAHPEAVCharacter@@@Z endp

; DialogLineData::hasChildren();
?hasChildren@DialogLineData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+18*8]
?hasChildren@DialogLineData@@QEBA_NXZ endp

; DialogLineData::checkConditions(class Dialogue *, class Character *, bool);
?checkConditions@DialogLineData@@QEAA_NPEAVDialogue@@PEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+19*8]
?checkConditions@DialogLineData@@QEAA_NPEAVDialogue@@PEAVCharacter@@_N@Z endp

; DialogLineData::chooseAChild(class Dialogue *, class Character *, bool);
?chooseAChild@DialogLineData@@QEAAPEAV1@PEAVDialogue@@PEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+20*8]
?chooseAChild@DialogLineData@@QEAAPEAV1@PEAVDialogue@@PEAVCharacter@@_N@Z endp

; DialogLineData::getText(bool);
?getText@DialogLineData@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+21*8]
?getText@DialogLineData@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; DialogLineData::getText(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?getText@DialogLineData@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+22*8]
?getText@DialogLineData@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; DialogLineData::getStringID();
?getStringID@DialogLineData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_DialogLineData_base+23*8]
?getStringID@DialogLineData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; DialogLineData::getGameData();
?getGameData@DialogLineData@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_DialogLineData_base+24*8]
?getGameData@DialogLineData@@QEAAPEAVGameData@@XZ endp

; DialogLineData::getChildByStringID(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getChildByStringID@DialogLineData@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+25*8]
?getChildByStringID@DialogLineData@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DialogLineData::getPlayerReplies(class lektor<DialogLineData *> &, class Dialogue *, class Character *);
?getPlayerReplies@DialogLineData@@QEAAXAEAV?$lektor@PEAVDialogLineData@@@@PEAVDialogue@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+26*8]
?getPlayerReplies@DialogLineData@@QEAAXAEAV?$lektor@PEAVDialogLineData@@@@PEAVDialogue@@PEAVCharacter@@@Z endp

; DialogLineData::setParent(class DialogLineData *);
?setParent@DialogLineData@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_DialogLineData_base+27*8]
?setParent@DialogLineData@@QEAAXPEAV1@@Z endp

; DialogLineData::getMoneyCostForLine();
?getMoneyCostForLine@DialogLineData@@QEBAHXZ proc EXPORT
jmp function_pointers[_DialogLineData_base+28*8]
?getMoneyCostForLine@DialogLineData@@QEBAHXZ endp

; DialogLineData::getActions();
?getActions@DialogLineData@@QEBAPEBV?$lektor@PEAVDialogAction@DialogLineData@@@@XZ proc EXPORT
jmp function_pointers[_DialogLineData_base+29*8]
?getActions@DialogLineData@@QEBAPEBV?$lektor@PEAVDialogAction@DialogLineData@@@@XZ endp
