
?_CONSTRUCTOR@DialogState@RepetitionCounter@Dialogue@@QEAAPEAV123@XZ proc EXPORT
?_CONSTRUCTOR@DialogState@RepetitionCounter@Dialogue@@QEAAPEAV123@XZ endp

; Dialogue::RepetitionCounter::DialogState::DialogState();
??0DialogState@RepetitionCounter@Dialogue@@QEAA@XZ proc EXPORT
jmp function_pointers[_Dialogue_RepetitionCounter_DialogState_base+0*8]
??0DialogState@RepetitionCounter@Dialogue@@QEAA@XZ endp
