
?_CONSTRUCTOR@DoorStuff@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@6@Z proc EXPORT
?_CONSTRUCTOR@DoorStuff@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@6@Z endp

; DoorStuff::DoorStuff(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *, class Building *);
??0DoorStuff@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@6@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+0*8]
??0DoorStuff@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@6@Z endp

?_DESTRUCTOR@DoorStuff@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@DoorStuff@@QEAAXXZ endp

; DoorStuff::~DoorStuff();
??1DoorStuff@@UEAA@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+1*8]
??1DoorStuff@@UEAA@XZ endp

; DoorStuff::setupPhysicalUT();
?setupPhysicalUT@DoorStuff@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+2*8]
?setupPhysicalUT@DoorStuff@@QEAA_NXZ endp

?_NV_getFaction@DoorStuff@@QEBAPEAVFaction@@XZ proc EXPORT
?_NV_getFaction@DoorStuff@@QEBAPEAVFaction@@XZ endp

; DoorStuff::getFaction();
?getFaction@DoorStuff@@UEBAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+3*8]
?getFaction@DoorStuff@@UEBAPEAVFaction@@XZ endp

; DoorStuff::_getPhysActorUT();
?_getPhysActorUT@DoorStuff@@QEAAPEAVNxActor@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+4*8]
?_getPhysActorUT@DoorStuff@@QEAAPEAVNxActor@@XZ endp

?_NV_getGUIData@DoorStuff@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@DoorStuff@@QEAAXPEAVDatapanelGUI@@H@Z endp

; DoorStuff::getGUIData(class DatapanelGUI *, int);
?getGUIData@DoorStuff@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+5*8]
?getGUIData@DoorStuff@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_needsUpdate@DoorStuff@@QEAA_NXZ proc EXPORT
?_NV_needsUpdate@DoorStuff@@QEAA_NXZ endp

; DoorStuff::needsUpdate();
?needsUpdate@DoorStuff@@UEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+6*8]
?needsUpdate@DoorStuff@@UEAA_NXZ endp

; DoorStuff::getGateCode();
?getGateCode@DoorStuff@@QEAAGXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+7*8]
?getGateCode@DoorStuff@@QEAAGXZ endp

; DoorStuff::setGateCode(int);
?setGateCode@DoorStuff@@QEAAXH@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+8*8]
?setGateCode@DoorStuff@@QEAAXH@Z endp

?_NV_isGate@DoorStuff@@QEAAPEAVGatewayBuilding@@XZ proc EXPORT
?_NV_isGate@DoorStuff@@QEAAPEAVGatewayBuilding@@XZ endp

; DoorStuff::isGate();
?isGate@DoorStuff@@UEAAPEAVGatewayBuilding@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+9*8]
?isGate@DoorStuff@@UEAAPEAVGatewayBuilding@@XZ endp

?_NV_isPublic@DoorStuff@@QEBA_NXZ proc EXPORT
?_NV_isPublic@DoorStuff@@QEBA_NXZ endp

; DoorStuff::isPublic();
?isPublic@DoorStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+10*8]
?isPublic@DoorStuff@@UEBA_NXZ endp

?_NV_getMouseCursor@DoorStuff@@QEAA?AW4CursorType@@XZ proc EXPORT
?_NV_getMouseCursor@DoorStuff@@QEAA?AW4CursorType@@XZ endp

; DoorStuff::getMouseCursor();
?getMouseCursor@DoorStuff@@UEAA?AW4CursorType@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+11*8]
?getMouseCursor@DoorStuff@@UEAA?AW4CursorType@@XZ endp

?_NV_getDefaultTask@DoorStuff@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@DoorStuff@@QEAA?AW4TaskType@@XZ endp

; DoorStuff::getDefaultTask();
?getDefaultTask@DoorStuff@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+12*8]
?getDefaultTask@DoorStuff@@UEAA?AW4TaskType@@XZ endp

?_NV_setHandle@DoorStuff@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@DoorStuff@@QEAAXAEBVhand@@@Z endp

; DoorStuff::setHandle(const class hand &);
?setHandle@DoorStuff@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+13*8]
?setHandle@DoorStuff@@UEAAXAEBVhand@@@Z endp

?_NV_getReachRange@DoorStuff@@QEBAMXZ proc EXPORT
?_NV_getReachRange@DoorStuff@@QEBAMXZ endp

; DoorStuff::getReachRange();
?getReachRange@DoorStuff@@UEBAMXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+14*8]
?getReachRange@DoorStuff@@UEBAMXZ endp

?_NV_getDoor@DoorStuff@@QEAAPEAV1@XZ proc EXPORT
?_NV_getDoor@DoorStuff@@QEAAPEAV1@XZ endp

; DoorStuff::getDoor();
?getDoor@DoorStuff@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+15*8]
?getDoor@DoorStuff@@UEAAPEAV1@XZ endp

?_NV_getName@DoorStuff@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getName@DoorStuff@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; DoorStuff::getName();
?getName@DoorStuff@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+16*8]
?getName@DoorStuff@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getDoorLock@DoorStuff@@QEAAPEAVDoorLock@@XZ proc EXPORT
?_NV_getDoorLock@DoorStuff@@QEAAPEAVDoorLock@@XZ endp

; DoorStuff::getDoorLock();
?getDoorLock@DoorStuff@@UEAAPEAVDoorLock@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+17*8]
?getDoorLock@DoorStuff@@UEAAPEAVDoorLock@@XZ endp

?_NV_hasDoorLock@DoorStuff@@QEBA_NXZ proc EXPORT
?_NV_hasDoorLock@DoorStuff@@QEBA_NXZ endp

; DoorStuff::hasDoorLock();
?hasDoorLock@DoorStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+18*8]
?hasDoorLock@DoorStuff@@UEBA_NXZ endp

?_NV_hitByMeleeAttack@DoorStuff@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
?_NV_hitByMeleeAttack@DoorStuff@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

; DoorStuff::hitByMeleeAttack(enum CutDirection, class Damages &, class Character *, class CombatTechniqueData *, int);
?hitByMeleeAttack@DoorStuff@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+19*8]
?hitByMeleeAttack@DoorStuff@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

; DoorStuff::getActorClosedPosition();
?getActorClosedPosition@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+20*8]
?getActorClosedPosition@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ endp

; DoorStuff::updateGateCodeState();
?updateGateCodeState@DoorStuff@@QEBAXXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+21*8]
?updateGateCodeState@DoorStuff@@QEBAXXZ endp

?_NV_onBuildingLoaded@DoorStuff@@QEAAXXZ proc EXPORT
?_NV_onBuildingLoaded@DoorStuff@@QEAAXXZ endp

; DoorStuff::onBuildingLoaded();
?onBuildingLoaded@DoorStuff@@UEAAXXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+22*8]
?onBuildingLoaded@DoorStuff@@UEAAXXZ endp

; DoorStuff::setDoorOpenAmount(float, bool);
?setDoorOpenAmount@DoorStuff@@QEAAXM_N@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+23*8]
?setDoorOpenAmount@DoorStuff@@QEAAXM_N@Z endp

?_NV_isBroken@DoorStuff@@QEBA_NXZ proc EXPORT
?_NV_isBroken@DoorStuff@@QEBA_NXZ endp

; DoorStuff::isBroken();
?isBroken@DoorStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+24*8]
?isBroken@DoorStuff@@UEBA_NXZ endp

?_NV_setBroken@DoorStuff@@QEAAX_N@Z proc EXPORT
?_NV_setBroken@DoorStuff@@QEAAX_N@Z endp

; DoorStuff::setBroken(bool);
?setBroken@DoorStuff@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+25*8]
?setBroken@DoorStuff@@UEAAX_N@Z endp

?_NV_isDisabled@DoorStuff@@QEAA_NXZ proc EXPORT
?_NV_isDisabled@DoorStuff@@QEAA_NXZ endp

; DoorStuff::isDisabled();
?isDisabled@DoorStuff@@UEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+26*8]
?isDisabled@DoorStuff@@UEAA_NXZ endp

; DoorStuff::isLocked();
?isLocked@DoorStuff@@QEBA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+27*8]
?isLocked@DoorStuff@@QEBA_NXZ endp

; DoorStuff::lockDoor();
?lockDoor@DoorStuff@@QEAAXXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+28*8]
?lockDoor@DoorStuff@@QEAAXXZ endp

; DoorStuff::unlockDoor();
?unlockDoor@DoorStuff@@QEAAXXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+29*8]
?unlockDoor@DoorStuff@@QEAAXXZ endp

; DoorStuff::getDoorOpenAmount();
?getDoorOpenAmount@DoorStuff@@QEBAMXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+30*8]
?getDoorOpenAmount@DoorStuff@@QEBAMXZ endp

; DoorStuff::setDoorState(enum DoorState);
?setDoorState@DoorStuff@@QEAAXW4DoorState@@@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+31*8]
?setDoorState@DoorStuff@@QEAAXW4DoorState@@@Z endp

; DoorStuff::getDoorState();
?getDoorState@DoorStuff@@QEBA?AW4DoorState@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+32*8]
?getDoorState@DoorStuff@@QEBA?AW4DoorState@@XZ endp

; DoorStuff::openDoor();
?openDoor@DoorStuff@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+33*8]
?openDoor@DoorStuff@@QEAA_NXZ endp

; DoorStuff::closeDoor();
?closeDoor@DoorStuff@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+34*8]
?closeDoor@DoorStuff@@QEAA_NXZ endp

; DoorStuff::_forceDoorClosedUT();
?_forceDoorClosedUT@DoorStuff@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+35*8]
?_forceDoorClosedUT@DoorStuff@@QEAA_NXZ endp

; DoorStuff::_forceDoorOpenUT();
?_forceDoorOpenUT@DoorStuff@@QEAA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+36*8]
?_forceDoorOpenUT@DoorStuff@@QEAA_NXZ endp

?_NV_update@DoorStuff@@QEAAXXZ proc EXPORT
?_NV_update@DoorStuff@@QEAAXXZ endp

; DoorStuff::update();
?update@DoorStuff@@UEAAXXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+37*8]
?update@DoorStuff@@UEAAXXZ endp

; DoorStuff::getDoorPosition();
?getDoorPosition@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+38*8]
?getDoorPosition@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ endp

; DoorStuff::getDoorPosOutside();
?getDoorPosOutside@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+39*8]
?getDoorPosOutside@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ endp

; DoorStuff::getDoorPosOutside_extraFarOut(float);
?getDoorPosOutside_extraFarOut@DoorStuff@@QEBA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+40*8]
?getDoorPosOutside_extraFarOut@DoorStuff@@QEBA?AVVector3@Ogre@@M@Z endp

; DoorStuff::getDoorPosInside();
?getDoorPosInside@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+41*8]
?getDoorPosInside@DoorStuff@@QEBAAEBVVector3@Ogre@@XZ endp

; DoorStuff::getDoorPosInside_extraFarIn(float);
?getDoorPosInside_extraFarIn@DoorStuff@@QEBA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+42*8]
?getDoorPosInside_extraFarIn@DoorStuff@@QEBA?AVVector3@Ogre@@M@Z endp

; DoorStuff::isOpen();
?isOpen@DoorStuff@@QEBA_NXZ proc EXPORT
jmp function_pointers[_DoorStuff_base+43*8]
?isOpen@DoorStuff@@QEBA_NXZ endp

; DoorStuff::openButton(class DataPanelLine *);
?openButton@DoorStuff@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+44*8]
?openButton@DoorStuff@@QEAAXPEAVDataPanelLine@@@Z endp

; DoorStuff::lockButton(class DataPanelLine *);
?lockButton@DoorStuff@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+45*8]
?lockButton@DoorStuff@@QEAAXPEAVDataPanelLine@@@Z endp

?_NV__serialise@DoorStuff@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV__serialise@DoorStuff@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; DoorStuff::_serialise(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_serialise@DoorStuff@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+46*8]
?_serialise@DoorStuff@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV__loadFromSerialise@DoorStuff@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
?_NV__loadFromSerialise@DoorStuff@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; DoorStuff::_loadFromSerialise(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?_loadFromSerialise@DoorStuff@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_DoorStuff_base+47*8]
?_loadFromSerialise@DoorStuff@@UEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

?_NV_doorStuff@DoorStuff@@QEAAPEAV1@XZ proc EXPORT
?_NV_doorStuff@DoorStuff@@QEAAPEAV1@XZ endp

; DoorStuff::doorStuff();
?doorStuff@DoorStuff@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+48*8]
?doorStuff@DoorStuff@@UEAAPEAV1@XZ endp

?_NV_doorParentBuilding@DoorStuff@@QEBAPEAVBuilding@@XZ proc EXPORT
?_NV_doorParentBuilding@DoorStuff@@QEBAPEAVBuilding@@XZ endp

; DoorStuff::doorParentBuilding();
?doorParentBuilding@DoorStuff@@UEBAPEAVBuilding@@XZ proc EXPORT
jmp function_pointers[_DoorStuff_base+49*8]
?doorParentBuilding@DoorStuff@@UEBAPEAVBuilding@@XZ endp
