
?_CONSTRUCTOR@EdgeCache@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@EdgeCache@@QEAAPEAV1@XZ endp

; EdgeCache::EdgeCache();
??0EdgeCache@@QEAA@XZ proc EXPORT
jmp function_pointers[_EdgeCache_base+0*8]
??0EdgeCache@@QEAA@XZ endp

?_DESTRUCTOR@EdgeCache@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@EdgeCache@@QEAAXXZ endp

; EdgeCache::~EdgeCache();
??1EdgeCache@@QEAA@XZ proc EXPORT
jmp function_pointers[_EdgeCache_base+1*8]
??1EdgeCache@@QEAA@XZ endp
