
?_CONSTRUCTOR@RelationData@FactionRelations@@QEAAPEAV12@M_N@Z proc EXPORT
?_CONSTRUCTOR@RelationData@FactionRelations@@QEAAPEAV12@M_N@Z endp

; FactionRelations::RelationData::RelationData(float, bool);
??0RelationData@FactionRelations@@QEAA@M_N@Z proc EXPORT
jmp function_pointers[_FactionRelations_RelationData_base+0*8]
??0RelationData@FactionRelations@@QEAA@M_N@Z endp

?_CONSTRUCTOR@RelationData@FactionRelations@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@RelationData@FactionRelations@@QEAAPEAV12@XZ endp

; FactionRelations::RelationData::RelationData();
??0RelationData@FactionRelations@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionRelations_RelationData_base+1*8]
??0RelationData@FactionRelations@@QEAA@XZ endp

; FactionRelations::RelationData::save(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Faction *);
?save@RelationData@FactionRelations@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_RelationData_base+2*8]
?save@RelationData@FactionRelations@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVFaction@@@Z endp

; FactionRelations::RelationData::load(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Faction *);
?load@RelationData@FactionRelations@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_RelationData_base+3*8]
?load@RelationData@FactionRelations@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVFaction@@@Z endp

?_DESTRUCTOR@RelationData@FactionRelations@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RelationData@FactionRelations@@QEAAXXZ endp

; FactionRelations::RelationData::~RelationData();
??1RelationData@FactionRelations@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionRelations_RelationData_base+4*8]
??1RelationData@FactionRelations@@QEAA@XZ endp

; FactionRelations::RelationData::operator=(const class FactionRelations::RelationData &);
??4RelationData@FactionRelations@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_FactionRelations_RelationData_base+5*8]
??4RelationData@FactionRelations@@QEAAAEAV01@AEBV01@@Z endp
