
?_CONSTRUCTOR@FactionRelations@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@FactionRelations@@QEAAPEAV1@XZ endp

; FactionRelations::FactionRelations();
??0FactionRelations@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionRelations_base+0*8]
??0FactionRelations@@QEAA@XZ endp

; FactionRelations::setupPhase1(class Faction *);
?setupPhase1@FactionRelations@@QEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+1*8]
?setupPhase1@FactionRelations@@QEAAXPEAVFaction@@@Z endp

; FactionRelations::setupPhase2();
?setupPhase2@FactionRelations@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionRelations_base+2*8]
?setupPhase2@FactionRelations@@QEAAXXZ endp

; FactionRelations::isEnemyByDefault();
?isEnemyByDefault@FactionRelations@@QEBA_NXZ proc EXPORT
jmp function_pointers[_FactionRelations_base+3*8]
?isEnemyByDefault@FactionRelations@@QEBA_NXZ endp

; FactionRelations::reset();
?reset@FactionRelations@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionRelations_base+4*8]
?reset@FactionRelations@@QEAAXXZ endp

?_NV_save@FactionRelations@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_save@FactionRelations@@QEAAXPEAVGameData@@@Z endp

; FactionRelations::save(class GameData *);
?save@FactionRelations@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+5*8]
?save@FactionRelations@@UEAAXPEAVGameData@@@Z endp

?_NV_load@FactionRelations@@QEAAXPEAVGameData@@_N@Z proc EXPORT
?_NV_load@FactionRelations@@QEAAXPEAVGameData@@_N@Z endp

; FactionRelations::load(class GameData *, bool);
?load@FactionRelations@@UEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+6*8]
?load@FactionRelations@@UEAAXPEAVGameData@@_N@Z endp

?_NV_update@FactionRelations@@QEAAXXZ proc EXPORT
?_NV_update@FactionRelations@@QEAAXXZ endp

; FactionRelations::update();
?update@FactionRelations@@UEAAXXZ proc EXPORT
jmp function_pointers[_FactionRelations_base+7*8]
?update@FactionRelations@@UEAAXXZ endp

; FactionRelations::_isAlly(class Faction *);
?_isAlly@FactionRelations@@QEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+8*8]
?_isAlly@FactionRelations@@QEAA_NPEAVFaction@@@Z endp

; FactionRelations::_isEnemy(class Faction *);
?_isEnemy@FactionRelations@@QEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+9*8]
?_isEnemy@FactionRelations@@QEAA_NPEAVFaction@@@Z endp

; FactionRelations::isEnemy(class Faction *);
?isEnemy@FactionRelations@@QEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+10*8]
?isEnemy@FactionRelations@@QEAA_NPEAVFaction@@@Z endp

?_NV_setEnemy@FactionRelations@@QEAAXPEAVFaction@@@Z proc EXPORT
?_NV_setEnemy@FactionRelations@@QEAAXPEAVFaction@@@Z endp

; FactionRelations::setEnemy(class Faction *);
?setEnemy@FactionRelations@@UEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+11*8]
?setEnemy@FactionRelations@@UEAAXPEAVFaction@@@Z endp

; FactionRelations::isAlly(class Faction *);
?isAlly@FactionRelations@@QEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+12*8]
?isAlly@FactionRelations@@QEAA_NPEAVFaction@@@Z endp

; FactionRelations::isCoexisting(class Faction *);
?isCoexisting@FactionRelations@@QEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+13*8]
?isCoexisting@FactionRelations@@QEAA_NPEAVFaction@@@Z endp

; FactionRelations::getFactionRelation(class Faction *);
?getFactionRelation@FactionRelations@@QEAAMPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+14*8]
?getFactionRelation@FactionRelations@@QEAAMPEAVFaction@@@Z endp

; FactionRelations::getFactionRelationMultiplier(class Faction *);
?getFactionRelationMultiplier@FactionRelations@@QEAAMPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+15*8]
?getFactionRelationMultiplier@FactionRelations@@QEAAMPEAVFaction@@@Z endp

; FactionRelations::getFactionRelationMultiplierInverse(class Faction *);
?getFactionRelationMultiplierInverse@FactionRelations@@QEAAMPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+16*8]
?getFactionRelationMultiplierInverse@FactionRelations@@QEAAMPEAVFaction@@@Z endp

; FactionRelations::setRelation(class Faction *, float);
?setRelation@FactionRelations@@QEAAXPEAVFaction@@M@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+17*8]
?setRelation@FactionRelations@@QEAAXPEAVFaction@@M@Z endp

?_NV_affectRelations@FactionRelations@@QEAAXPEAVFaction@@MM@Z proc EXPORT
?_NV_affectRelations@FactionRelations@@QEAAXPEAVFaction@@MM@Z endp

; FactionRelations::affectRelations(class Faction *, float, float);
?affectRelations@FactionRelations@@UEAAXPEAVFaction@@MM@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+18*8]
?affectRelations@FactionRelations@@UEAAXPEAVFaction@@MM@Z endp

?_NV_affectRelations@FactionRelations@@QEAAXPEAVFaction@@W4FactionEvent@1@M@Z proc EXPORT
?_NV_affectRelations@FactionRelations@@QEAAXPEAVFaction@@W4FactionEvent@1@M@Z endp

; FactionRelations::affectRelations(class Faction *, enum FactionRelations::FactionEvent, float);
?affectRelations@FactionRelations@@UEAAXPEAVFaction@@W4FactionEvent@1@M@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+19*8]
?affectRelations@FactionRelations@@UEAAXPEAVFaction@@W4FactionEvent@1@M@Z endp

?_NV_affectTrust@FactionRelations@@QEAAXPEAVFaction@@MM@Z proc EXPORT
?_NV_affectTrust@FactionRelations@@QEAAXPEAVFaction@@MM@Z endp

; FactionRelations::affectTrust(class Faction *, float, float);
?affectTrust@FactionRelations@@UEAAXPEAVFaction@@MM@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+20*8]
?affectTrust@FactionRelations@@UEAAXPEAVFaction@@MM@Z endp

?_NV_setNoLongerEnemies@FactionRelations@@QEAAXPEAVFaction@@@Z proc EXPORT
?_NV_setNoLongerEnemies@FactionRelations@@QEAAXPEAVFaction@@@Z endp

; FactionRelations::setNoLongerEnemies(class Faction *);
?setNoLongerEnemies@FactionRelations@@UEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+21*8]
?setNoLongerEnemies@FactionRelations@@UEAAXPEAVFaction@@@Z endp

?_NV_declareWar@FactionRelations@@QEAAXPEAVFaction@@@Z proc EXPORT
?_NV_declareWar@FactionRelations@@QEAAXPEAVFaction@@@Z endp

; FactionRelations::declareWar(class Faction *);
?declareWar@FactionRelations@@UEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+22*8]
?declareWar@FactionRelations@@UEAAXPEAVFaction@@@Z endp

?_NV_affectReputation@FactionRelations@@QEAAXPEAVFaction@@M@Z proc EXPORT
?_NV_affectReputation@FactionRelations@@QEAAXPEAVFaction@@M@Z endp

; FactionRelations::affectReputation(class Faction *, float);
?affectReputation@FactionRelations@@UEAAXPEAVFaction@@M@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+23*8]
?affectReputation@FactionRelations@@UEAAXPEAVFaction@@M@Z endp

?_NV_getRelationData@FactionRelations@@QEAAPEAVRelationData@1@PEAVFaction@@@Z proc EXPORT
?_NV_getRelationData@FactionRelations@@QEAAPEAVRelationData@1@PEAVFaction@@@Z endp

; FactionRelations::getRelationData(class Faction *);
?getRelationData@FactionRelations@@UEAAPEAVRelationData@1@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+24*8]
?getRelationData@FactionRelations@@UEAAPEAVRelationData@1@PEAVFaction@@@Z endp

; FactionRelations::getGUIData(class DatapanelGUI *, int);
?getGUIData@FactionRelations@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+25*8]
?getGUIData@FactionRelations@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FactionRelations::getRelationsData(class boost::unordered::unordered_map<Faction *,float,boost::hash<Faction *>,std::equal_to<Faction *>,Ogre::STLAllocator<std::pair<Faction * const,float>,Ogre::CategorisedAllocPolicy<0> > > &);
?getRelationsData@FactionRelations@@QEAAXAEAV?$unordered_map@PEAVFaction@@MU?$hash@PEAVFaction@@@boost@@U?$equal_to@PEAVFaction@@@std@@V?$STLAllocator@U?$pair@QEAVFaction@@M@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+26*8]
?getRelationsData@FactionRelations@@QEAAXAEAV?$unordered_map@PEAVFaction@@MU?$hash@PEAVFaction@@@boost@@U?$equal_to@PEAVFaction@@@std@@V?$STLAllocator@U?$pair@QEAVFaction@@M@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z endp

; FactionRelations::checkStateCondition(enum DialogConditionEnum, enum ComparisonEnum, int, class Faction *);
?checkStateCondition@FactionRelations@@QEAA_NW4DialogConditionEnum@@W4ComparisonEnum@@HPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionRelations_base+27*8]
?checkStateCondition@FactionRelations@@QEAA_NW4DialogConditionEnum@@W4ComparisonEnum@@HPEAVFaction@@@Z endp

?_DESTRUCTOR@FactionRelations@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionRelations@@QEAAXXZ endp

; FactionRelations::~FactionRelations();
??1FactionRelations@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionRelations_base+28*8]
??1FactionRelations@@QEAA@XZ endp
