
?_CONSTRUCTOR@FactionRelationsLine@FactionsScreen@@QEAAPEAV12@PEAVFaction@@@Z proc EXPORT
?_CONSTRUCTOR@FactionRelationsLine@FactionsScreen@@QEAAPEAV12@PEAVFaction@@@Z endp

; FactionsScreen::FactionRelationsLine::FactionRelationsLine(class Faction *);
??0FactionRelationsLine@FactionsScreen@@QEAA@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionsScreen_FactionRelationsLine_base+0*8]
??0FactionRelationsLine@FactionsScreen@@QEAA@PEAVFaction@@@Z endp

; FactionsScreen::FactionRelationsLine::attachToWidget(class MyGUI::Widget *);
?attachToWidget@FactionRelationsLine@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_FactionsScreen_FactionRelationsLine_base+1*8]
?attachToWidget@FactionRelationsLine@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; FactionsScreen::FactionRelationsLine::update();
?update@FactionRelationsLine@FactionsScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionsScreen_FactionRelationsLine_base+2*8]
?update@FactionRelationsLine@FactionsScreen@@QEAAXXZ endp

?_DESTRUCTOR@FactionRelationsLine@FactionsScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionRelationsLine@FactionsScreen@@QEAAXXZ endp

; FactionsScreen::FactionRelationsLine::~FactionRelationsLine();
??1FactionRelationsLine@FactionsScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_FactionsScreen_FactionRelationsLine_base+3*8]
??1FactionRelationsLine@FactionsScreen@@UEAA@XZ endp
