
?_CONSTRUCTOR@FactionLeader@@QEAAPEAV1@PEAVFaction@@@Z proc EXPORT
?_CONSTRUCTOR@FactionLeader@@QEAAPEAV1@PEAVFaction@@@Z endp

; FactionLeader::FactionLeader(class Faction *);
??0FactionLeader@@QEAA@PEAVFaction@@@Z proc EXPORT
jmp function_pointers[_FactionLeader_base+0*8]
??0FactionLeader@@QEAA@PEAVFaction@@@Z endp

; FactionLeader::setNewLeader(class Character *);
?setNewLeader@FactionLeader@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_FactionLeader_base+1*8]
?setNewLeader@FactionLeader@@QEAAXPEAVCharacter@@@Z endp

; FactionLeader::getEnemyMissionTargetList(class lektor<RootObject *> &, class GameData *);
?getEnemyMissionTargetList@FactionLeader@@QEAAXAEAV?$lektor@PEAVRootObject@@@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionLeader_base+2*8]
?getEnemyMissionTargetList@FactionLeader@@QEAAXAEAV?$lektor@PEAVRootObject@@@@PEAVGameData@@@Z endp

; FactionLeader::getGUIData(class DatapanelGUI *, int);
?getGUIData@FactionLeader@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FactionLeader_base+3*8]
?getGUIData@FactionLeader@@QEAAXPEAVDatapanelGUI@@H@Z endp

?_DESTRUCTOR@FactionLeader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionLeader@@QEAAXXZ endp

; FactionLeader::~FactionLeader();
??1FactionLeader@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionLeader_base+4*8]
??1FactionLeader@@QEAA@XZ endp
