
?_CONSTRUCTOR@FactionManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@FactionManager@@QEAAPEAV1@XZ endp

; FactionManager::FactionManager();
??0FactionManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionManager_base+0*8]
??0FactionManager@@QEAA@XZ endp

; FactionManager::saveGameState(class GameDataContainer *);
?saveGameState@FactionManager@@QEAAXPEAVGameDataContainer@@@Z proc EXPORT
jmp function_pointers[_FactionManager_base+1*8]
?saveGameState@FactionManager@@QEAAXPEAVGameDataContainer@@@Z endp

; FactionManager::savePlayerGameState(class GameDataContainer *);
?savePlayerGameState@FactionManager@@QEAAXPEAVGameDataContainer@@@Z proc EXPORT
jmp function_pointers[_FactionManager_base+2*8]
?savePlayerGameState@FactionManager@@QEAAXPEAVGameDataContainer@@@Z endp

; FactionManager::clearAndDestroy();
?clearAndDestroy@FactionManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionManager_base+3*8]
?clearAndDestroy@FactionManager@@QEAAXXZ endp

; FactionManager::activateUnloadedPlatoons();
?activateUnloadedPlatoons@FactionManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionManager_base+4*8]
?activateUnloadedPlatoons@FactionManager@@QEAAXXZ endp

; FactionManager::getOrCreateFaction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getOrCreateFaction@FactionManager@@QEAAPEAVFaction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_FactionManager_base+5*8]
?getOrCreateFaction@FactionManager@@QEAAPEAVFaction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; FactionManager::getOrCreateFaction(class GameData *);
?getOrCreateFaction@FactionManager@@QEAAPEAVFaction@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionManager_base+6*8]
?getOrCreateFaction@FactionManager@@QEAAPEAVFaction@@PEAVGameData@@@Z endp

; FactionManager::getFactionByName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getFactionByName@FactionManager@@QEAAPEAVFaction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_FactionManager_base+7*8]
?getFactionByName@FactionManager@@QEAAPEAVFaction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; FactionManager::getFactionByStringID(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getFactionByStringID@FactionManager@@QEAAPEAVFaction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_FactionManager_base+8*8]
?getFactionByStringID@FactionManager@@QEAAPEAVFaction@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; FactionManager::getEmptyFaction();
?getEmptyFaction@FactionManager@@QEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_FactionManager_base+9*8]
?getEmptyFaction@FactionManager@@QEAAPEAVFaction@@XZ endp

; FactionManager::setupAndLinkAllFactions();
?setupAndLinkAllFactions@FactionManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionManager_base+10*8]
?setupAndLinkAllFactions@FactionManager@@QEAAXXZ endp

; FactionManager::getFactionBySquad(class GameData *);
?getFactionBySquad@FactionManager@@QEAAPEAVFaction@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionManager_base+11*8]
?getFactionBySquad@FactionManager@@QEAAPEAVFaction@@PEAVGameData@@@Z endp

; FactionManager::getCampaignGUIInfos(class DatapanelGUI *, int, bool);
?getCampaignGUIInfos@FactionManager@@QEAAXPEAVDatapanelGUI@@H_N@Z proc EXPORT
jmp function_pointers[_FactionManager_base+12*8]
?getCampaignGUIInfos@FactionManager@@QEAAXPEAVDatapanelGUI@@H_N@Z endp

; FactionManager::areAnyHostileCampaignsRunning();
?areAnyHostileCampaignsRunning@FactionManager@@QEAA_NXZ proc EXPORT
jmp function_pointers[_FactionManager_base+13*8]
?areAnyHostileCampaignsRunning@FactionManager@@QEAA_NXZ endp

; FactionManager::getNumTempPlatoons();
?getNumTempPlatoons@FactionManager@@QEAAHXZ proc EXPORT
jmp function_pointers[_FactionManager_base+14*8]
?getNumTempPlatoons@FactionManager@@QEAAHXZ endp

; FactionManager::updateMT(float);
?updateMT@FactionManager@@QEAAXM@Z proc EXPORT
jmp function_pointers[_FactionManager_base+15*8]
?updateMT@FactionManager@@QEAAXM@Z endp

; FactionManager::updateThreaded(float);
?updateThreaded@FactionManager@@QEAAXM@Z proc EXPORT
jmp function_pointers[_FactionManager_base+16*8]
?updateThreaded@FactionManager@@QEAAXM@Z endp

; FactionManager::_showDebugPlatoonMarkers(bool);
?_showDebugPlatoonMarkers@FactionManager@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_FactionManager_base+17*8]
?_showDebugPlatoonMarkers@FactionManager@@QEAAX_N@Z endp

; FactionManager::getAllFactions();
?getAllFactions@FactionManager@@QEAAPEBV?$lektor@PEAVFaction@@@@XZ proc EXPORT
jmp function_pointers[_FactionManager_base+18*8]
?getAllFactions@FactionManager@@QEAAPEBV?$lektor@PEAVFaction@@@@XZ endp

?_DESTRUCTOR@FactionManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionManager@@QEAAXXZ endp

; FactionManager::~FactionManager();
??1FactionManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionManager_base+19*8]
??1FactionManager@@QEAA@XZ endp
