
?_CONSTRUCTOR@UniqueSpawnData@FactionUniqueSquadManager@@QEAAPEAV12@PEAVGameData@@H@Z proc EXPORT
?_CONSTRUCTOR@UniqueSpawnData@FactionUniqueSquadManager@@QEAAPEAV12@PEAVGameData@@H@Z endp

; FactionUniqueSquadManager::UniqueSpawnData::UniqueSpawnData(class GameData *, int);
??0UniqueSpawnData@FactionUniqueSquadManager@@QEAA@PEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_UniqueSpawnData_base+0*8]
??0UniqueSpawnData@FactionUniqueSquadManager@@QEAA@PEAVGameData@@H@Z endp

; FactionUniqueSquadManager::UniqueSpawnData::currentNumber();
?currentNumber@UniqueSpawnData@FactionUniqueSquadManager@@QEBAHXZ proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_UniqueSpawnData_base+1*8]
?currentNumber@UniqueSpawnData@FactionUniqueSquadManager@@QEBAHXZ endp

?_DESTRUCTOR@UniqueSpawnData@FactionUniqueSquadManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@UniqueSpawnData@FactionUniqueSquadManager@@QEAAXXZ endp

; FactionUniqueSquadManager::UniqueSpawnData::~UniqueSpawnData();
??1UniqueSpawnData@FactionUniqueSquadManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_UniqueSpawnData_base+2*8]
??1UniqueSpawnData@FactionUniqueSquadManager@@QEAA@XZ endp
