
?_CONSTRUCTOR@FactionUniqueSquadManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@FactionUniqueSquadManager@@QEAAPEAV1@XZ endp

; FactionUniqueSquadManager::FactionUniqueSquadManager();
??0FactionUniqueSquadManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+0*8]
??0FactionUniqueSquadManager@@QEAA@XZ endp

?_DESTRUCTOR@FactionUniqueSquadManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionUniqueSquadManager@@QEAAXXZ endp

; FactionUniqueSquadManager::~FactionUniqueSquadManager();
??1FactionUniqueSquadManager@@UEAA@XZ proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+1*8]
??1FactionUniqueSquadManager@@UEAA@XZ endp

; FactionUniqueSquadManager::clearAndReset();
?clearAndReset@FactionUniqueSquadManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+2*8]
?clearAndReset@FactionUniqueSquadManager@@QEAAXXZ endp

; FactionUniqueSquadManager::initialiseNew(class Faction *, class GameData *, class Town *);
?initialiseNew@FactionUniqueSquadManager@@QEAAXPEAVFaction@@PEAVGameData@@PEAVTown@@@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+3*8]
?initialiseNew@FactionUniqueSquadManager@@QEAAXPEAVFaction@@PEAVGameData@@PEAVTown@@@Z endp

; FactionUniqueSquadManager::chooseRandomSquadToSpawn(float);
?chooseRandomSquadToSpawn@FactionUniqueSquadManager@@QEAAPEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+4*8]
?chooseRandomSquadToSpawn@FactionUniqueSquadManager@@QEAAPEAVGameData@@M@Z endp

; FactionUniqueSquadManager::periodicUpdate(float);
?periodicUpdate@FactionUniqueSquadManager@@QEAAXM@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+5*8]
?periodicUpdate@FactionUniqueSquadManager@@QEAAXM@Z endp

; FactionUniqueSquadManager::serialise(class GameData *);
?serialise@FactionUniqueSquadManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+6*8]
?serialise@FactionUniqueSquadManager@@QEAAXPEAVGameData@@@Z endp

; FactionUniqueSquadManager::load(class GameData *, bool);
?load@FactionUniqueSquadManager@@QEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+7*8]
?load@FactionUniqueSquadManager@@QEAAXPEAVGameData@@_N@Z endp

; FactionUniqueSquadManager::getGUIData(class DatapanelGUI *, int);
?getGUIData@FactionUniqueSquadManager@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+8*8]
?getGUIData@FactionUniqueSquadManager@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FactionUniqueSquadManager::endOfUniqueSquad(class UniquePlatoon *);
?endOfUniqueSquad@FactionUniqueSquadManager@@QEAAXPEAVUniquePlatoon@@@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+9*8]
?endOfUniqueSquad@FactionUniqueSquadManager@@QEAAXPEAVUniquePlatoon@@@Z endp

; FactionUniqueSquadManager::getExistingSquadsFor(class GameData *);
?getExistingSquadsFor@FactionUniqueSquadManager@@QEAAPEAVUniqueSpawnData@1@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+10*8]
?getExistingSquadsFor@FactionUniqueSquadManager@@QEAAPEAVUniqueSpawnData@1@PEAVGameData@@@Z endp

; FactionUniqueSquadManager::spawnNewUniqueSquad(class GameData *);
?spawnNewUniqueSquad@FactionUniqueSquadManager@@QEAAPEAVUniquePlatoon@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FactionUniqueSquadManager_base+11*8]
?spawnNewUniqueSquad@FactionUniqueSquadManager@@QEAAPEAVUniquePlatoon@@PEAVGameData@@@Z endp
