
?_CONSTRUCTOR@CampaignRequest@FactionWarMgr@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@CampaignRequest@FactionWarMgr@@QEAAPEAV12@XZ endp

; FactionWarMgr::CampaignRequest::CampaignRequest();
??0CampaignRequest@FactionWarMgr@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionWarMgr_CampaignRequest_base+0*8]
??0CampaignRequest@FactionWarMgr@@QEAA@XZ endp

; FactionWarMgr::CampaignRequest::tryToChangeTarget();
?tryToChangeTarget@CampaignRequest@FactionWarMgr@@QEAA_NXZ proc EXPORT
jmp function_pointers[_FactionWarMgr_CampaignRequest_base+1*8]
?tryToChangeTarget@CampaignRequest@FactionWarMgr@@QEAA_NXZ endp
