
?_CONSTRUCTOR@BuildingSwaps@Faction@@QEAAPEAV12@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@BuildingSwaps@Faction@@QEAAPEAV12@PEAVGameData@@@Z endp

; Faction::BuildingSwaps::BuildingSwaps(class GameData *);
??0BuildingSwaps@Faction@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Faction_BuildingSwaps_base+0*8]
??0BuildingSwaps@Faction@@QEAA@PEAVGameData@@@Z endp

?_CONSTRUCTOR@BuildingSwaps@Faction@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@BuildingSwaps@Faction@@QEAAPEAV12@XZ endp

; Faction::BuildingSwaps::BuildingSwaps();
??0BuildingSwaps@Faction@@QEAA@XZ proc EXPORT
jmp function_pointers[_Faction_BuildingSwaps_base+1*8]
??0BuildingSwaps@Faction@@QEAA@XZ endp

; Faction::BuildingSwaps::hasReplacement(class GameData *);
?hasReplacement@BuildingSwaps@Faction@@QEBA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Faction_BuildingSwaps_base+2*8]
?hasReplacement@BuildingSwaps@Faction@@QEBA_NPEAVGameData@@@Z endp

; Faction::BuildingSwaps::getReplacement(class GameData *);
?getReplacement@BuildingSwaps@Faction@@QEBAPEAVGameData@@PEAV3@@Z proc EXPORT
jmp function_pointers[_Faction_BuildingSwaps_base+3*8]
?getReplacement@BuildingSwaps@Faction@@QEBAPEAVGameData@@PEAV3@@Z endp

?_DESTRUCTOR@BuildingSwaps@Faction@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildingSwaps@Faction@@QEAAXXZ endp

; Faction::BuildingSwaps::~BuildingSwaps();
??1BuildingSwaps@Faction@@QEAA@XZ proc EXPORT
jmp function_pointers[_Faction_BuildingSwaps_base+4*8]
??1BuildingSwaps@Faction@@QEAA@XZ endp

; Faction::BuildingSwaps::operator=(const class Faction::BuildingSwaps &);
??4BuildingSwaps@Faction@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_Faction_BuildingSwaps_base+5*8]
??4BuildingSwaps@Faction@@QEAAAEAV01@AEBV01@@Z endp
