
?_CONSTRUCTOR@Faction@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@Faction@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Faction::Faction(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0Faction@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Faction_base+0*8]
??0Faction@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@Faction@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Faction@@QEAAXXZ endp

; Faction::~Faction();
??1Faction@@QEAA@XZ proc EXPORT
jmp function_pointers[_Faction_base+1*8]
??1Faction@@QEAA@XZ endp

; Faction::getFundamentalNPCType();
?getFundamentalNPCType@Faction@@QEAA?AW4CharacterTypeEnum@@XZ proc EXPORT
jmp function_pointers[_Faction_base+2*8]
?getFundamentalNPCType@Faction@@QEAA?AW4CharacterTypeEnum@@XZ endp

; Faction::getProsperityMultiplier();
?getProsperityMultiplier@Faction@@QEAAMXZ proc EXPORT
jmp function_pointers[_Faction_base+3*8]
?getProsperityMultiplier@Faction@@QEAAMXZ endp

; Faction::clearAndDestroy();
?clearAndDestroy@Faction@@QEAAXXZ proc EXPORT
jmp function_pointers[_Faction_base+4*8]
?clearAndDestroy@Faction@@QEAAXXZ endp

; Faction::setup(class GameData *);
?setup@Faction@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Faction_base+5*8]
?setup@Faction@@QEAA_NPEAVGameData@@@Z endp

; Faction::setup2();
?setup2@Faction@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Faction_base+6*8]
?setup2@Faction@@QEAA_NXZ endp

; Faction::setup3();
?setup3@Faction@@QEAAXXZ proc EXPORT
jmp function_pointers[_Faction_base+7*8]
?setup3@Faction@@QEAAXXZ endp

; Faction::getNewPlatoonID();
?getNewPlatoonID@Faction@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Faction_base+8*8]
?getNewPlatoonID@Faction@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Faction::resetPlatoonID();
?resetPlatoonID@Faction@@QEAAXXZ proc EXPORT
jmp function_pointers[_Faction_base+9*8]
?resetPlatoonID@Faction@@QEAAXXZ endp

; Faction::createNewEmptyUnloadedPlatoon(class GameData *, const class Ogre::Vector3 &, class GameDataContainer *, bool);
?createNewEmptyUnloadedPlatoon@Faction@@QEAAPEAVPlatoon@@PEAVGameData@@AEBVVector3@Ogre@@PEAVGameDataContainer@@_N@Z proc EXPORT
jmp function_pointers[_Faction_base+10*8]
?createNewEmptyUnloadedPlatoon@Faction@@QEAAPEAVPlatoon@@PEAVGameData@@AEBVVector3@Ogre@@PEAVGameDataContainer@@_N@Z endp

; Faction::createNewEmptyActivePlatoon(class GameData *, bool, const class Ogre::Vector3 &);
?createNewEmptyActivePlatoon@Faction@@QEAAPEAVPlatoon@@PEAVGameData@@_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Faction_base+11*8]
?createNewEmptyActivePlatoon@Faction@@QEAAPEAVPlatoon@@PEAVGameData@@_NAEBVVector3@Ogre@@@Z endp

; Faction::createPlatoonUnloaded(class GameData *, class GameDataContainer *, class GameData *, const class Ogre::Vector3 &, bool);
?createPlatoonUnloaded@Faction@@QEAAXPEAVGameData@@PEAVGameDataContainer@@0AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_Faction_base+12*8]
?createPlatoonUnloaded@Faction@@QEAAXPEAVGameData@@PEAVGameDataContainer@@0AEBVVector3@Ogre@@_N@Z endp

; Faction::createPlatoonAuto(class GameData *, class GameData *, const class Ogre::Vector3 &);
?createPlatoonAuto@Faction@@QEAAXPEAVGameData@@0AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Faction_base+13*8]
?createPlatoonAuto@Faction@@QEAAXPEAVGameData@@0AEBVVector3@Ogre@@@Z endp

; Faction::createPlatoonsAuto(class lektor<GameData *> &);
?createPlatoonsAuto@Faction@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_Faction_base+14*8]
?createPlatoonsAuto@Faction@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; Faction::createReplacementPlatoonForPlayerWhenSavegameIsCorrupt(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createReplacementPlatoonForPlayerWhenSavegameIsCorrupt@Faction@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Faction_base+15*8]
?createReplacementPlatoonForPlayerWhenSavegameIsCorrupt@Faction@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Faction::restorePlatoon(class Platoon *);
?restorePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+16*8]
?restorePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::resetSquadPositions(const class Ogre::Vector3 &);
?resetSquadPositions@Faction@@QEAA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Faction_base+17*8]
?resetSquadPositions@Faction@@QEAA_NAEBVVector3@Ogre@@@Z endp

; Faction::countPopulation(class TownBase *);
?countPopulation@Faction@@QEAAHPEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_Faction_base+18*8]
?countPopulation@Faction@@QEAAHPEAVTownBase@@@Z endp

; Faction::countNumSquads(class GameData *, class TownBase *);
?countNumSquads@Faction@@QEAAHPEAVGameData@@PEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_Faction_base+19*8]
?countNumSquads@Faction@@QEAAHPEAVGameData@@PEAVTownBase@@@Z endp

; Faction::destroyPlatoon(class Platoon *);
?destroyPlatoon@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+20*8]
?destroyPlatoon@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::removePlatoon(class Platoon *);
?removePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+21*8]
?removePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::getRandomLockLevel(class GameData *);
?getRandomLockLevel@Faction@@QEBAHPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Faction_base+22*8]
?getRandomLockLevel@Faction@@QEBAHPEAVGameData@@@Z endp

; Faction::getData();
?getData@Faction@@QEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Faction_base+23*8]
?getData@Faction@@QEBAPEAVGameData@@XZ endp

; Faction::getGUIData(class DatapanelGUI *, int);
?getGUIData@Faction@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Faction_base+24*8]
?getGUIData@Faction@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Faction::getDefaultDivision();
?getDefaultDivision@Faction@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Faction_base+25*8]
?getDefaultDivision@Faction@@QEAAPEAVGameData@@XZ endp

; Faction::getFactionColorScheme();
?getFactionColorScheme@Faction@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Faction_base+26*8]
?getFactionColorScheme@Faction@@QEAAPEAVGameData@@XZ endp

; Faction::loadState(class GameDataContainer *, class GameData *);
?loadState@Faction@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Faction_base+27*8]
?loadState@Faction@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; Faction::saveState(class GameDataContainer *, bool);
?saveState@Faction@@QEAAPEAVGameData@@PEAVGameDataContainer@@_N@Z proc EXPORT
jmp function_pointers[_Faction_base+28*8]
?saveState@Faction@@QEAAPEAVGameData@@PEAVGameDataContainer@@_N@Z endp

; Faction::_activateUnloadedPlatoons();
?_activateUnloadedPlatoons@Faction@@QEAAXXZ proc EXPORT
jmp function_pointers[_Faction_base+29*8]
?_activateUnloadedPlatoons@Faction@@QEAAXXZ endp

?_NV_getCharactersInArea@Faction@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@M_N@Z proc EXPORT
?_NV_getCharactersInArea@Faction@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@M_N@Z endp

; Faction::getCharactersInArea(class lektor<RootObject *> &, const class Ogre::Vector3 &, float, bool);
?getCharactersInArea@Faction@@UEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@M_N@Z proc EXPORT
jmp function_pointers[_Faction_base+30*8]
?getCharactersInArea@Faction@@UEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@M_N@Z endp

?_NV_getSelectedObjects@Faction@@QEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z proc EXPORT
?_NV_getSelectedObjects@Faction@@QEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z endp

; Faction::getSelectedObjects(class lektor<RootObject *> &, enum itemType, bool);
?getSelectedObjects@Faction@@UEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z proc EXPORT
jmp function_pointers[_Faction_base+31*8]
?getSelectedObjects@Faction@@UEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z endp

?_NV_removeObject@Faction@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_removeObject@Faction@@QEAAXPEAVRootObject@@@Z endp

; Faction::removeObject(class RootObject *);
?removeObject@Faction@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Faction_base+32*8]
?removeObject@Faction@@UEAAXPEAVRootObject@@@Z endp

?_NV_destroyObject@Faction@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_destroyObject@Faction@@QEAAXPEAVRootObject@@@Z endp

; Faction::destroyObject(class RootObject *);
?destroyObject@Faction@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Faction_base+33*8]
?destroyObject@Faction@@UEAAXPEAVRootObject@@@Z endp

?_NV_processKillList@Faction@@QEAAXXZ proc EXPORT
?_NV_processKillList@Faction@@QEAAXXZ endp

; Faction::processKillList();
?processKillList@Faction@@UEAAXXZ proc EXPORT
jmp function_pointers[_Faction_base+34*8]
?processKillList@Faction@@UEAAXXZ endp

?_NV_addActiveObject@Faction@@QEAA_NPEAVRootObject@@PEAVActivePlatoon@@@Z proc EXPORT
?_NV_addActiveObject@Faction@@QEAA_NPEAVRootObject@@PEAVActivePlatoon@@@Z endp

; Faction::addActiveObject(class RootObject *, class ActivePlatoon *);
?addActiveObject@Faction@@UEAA_NPEAVRootObject@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+35*8]
?addActiveObject@Faction@@UEAA_NPEAVRootObject@@PEAVActivePlatoon@@@Z endp

; Faction::choosePlatoon();
?choosePlatoon@Faction@@QEAAPEAVActivePlatoon@@XZ proc EXPORT
jmp function_pointers[_Faction_base+36*8]
?choosePlatoon@Faction@@QEAAPEAVActivePlatoon@@XZ endp

; Faction::getActivePlatoons();
?getActivePlatoons@Faction@@QEBAPEBV?$lektor@PEAVPlatoon@@@@XZ proc EXPORT
jmp function_pointers[_Faction_base+37*8]
?getActivePlatoons@Faction@@QEBAPEBV?$lektor@PEAVPlatoon@@@@XZ endp

; Faction::getUnloadedPlatoons();
?getUnloadedPlatoons@Faction@@QEBAPEBV?$lektor@PEAVPlatoon@@@@XZ proc EXPORT
jmp function_pointers[_Faction_base+38*8]
?getUnloadedPlatoons@Faction@@QEBAPEBV?$lektor@PEAVPlatoon@@@@XZ endp

; Faction::getFactionSize();
?getFactionSize@Faction@@QEBAHXZ proc EXPORT
jmp function_pointers[_Faction_base+39*8]
?getFactionSize@Faction@@QEBAHXZ endp

; Faction::update(float);
?update@Faction@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Faction_base+40*8]
?update@Faction@@QEAAXM@Z endp

; Faction::periodicUpdateThreaded();
?periodicUpdateThreaded@Faction@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Faction_base+41*8]
?periodicUpdateThreaded@Faction@@QEAA_NXZ endp

; Faction::periodicUpdateMT();
?periodicUpdateMT@Faction@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Faction_base+42*8]
?periodicUpdateMT@Faction@@QEAA_NXZ endp

; Faction::isThePlayer();
?isThePlayer@Faction@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Faction_base+43*8]
?isThePlayer@Faction@@QEBA_NXZ endp

; Faction::isNotARealFaction();
?isNotARealFaction@Faction@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Faction_base+44*8]
?isNotARealFaction@Faction@@QEBA_NXZ endp

; Faction::getName();
?getName@Faction@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Faction_base+45*8]
?getName@Faction@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Faction::getNumPlatoons(class GameData *, bool, class TownBase *);
?getNumPlatoons@Faction@@QEBAHPEAVGameData@@_NPEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_Faction_base+46*8]
?getNumPlatoons@Faction@@QEBAHPEAVGameData@@_NPEAVTownBase@@@Z endp

; Faction::getSquadThatOwns(class Building *);
?getSquadThatOwns@Faction@@QEAAPEAVPlatoon@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_Faction_base+47*8]
?getSquadThatOwns@Faction@@QEAAPEAVPlatoon@@PEAVBuilding@@@Z endp

; Faction::getAllSquadsThatOwn(class lektor<Platoon *> &, class Building *);
?getAllSquadsThatOwn@Faction@@QEAAXAEAV?$lektor@PEAVPlatoon@@@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_Faction_base+48*8]
?getAllSquadsThatOwn@Faction@@QEAAXAEAV?$lektor@PEAVPlatoon@@@@PEAVBuilding@@@Z endp

; Faction::getAllActiveSquads();
?getAllActiveSquads@Faction@@QEAAPEBV?$lektor@PEAVPlatoon@@@@XZ proc EXPORT
jmp function_pointers[_Faction_base+49*8]
?getAllActiveSquads@Faction@@QEAAPEBV?$lektor@PEAVPlatoon@@@@XZ endp

; Faction::getRoadPreference();
?getRoadPreference@Faction@@QEBAMXZ proc EXPORT
jmp function_pointers[_Faction_base+50*8]
?getRoadPreference@Faction@@QEBAMXZ endp

; Faction::isAntiSlavery();
?isAntiSlavery@Faction@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Faction_base+51*8]
?isAntiSlavery@Faction@@QEAA_NXZ endp

; Faction::getLawEnforcementFaction();
?getLawEnforcementFaction@Faction@@QEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Faction_base+52*8]
?getLawEnforcementFaction@Faction@@QEAAPEAV1@XZ endp

; Faction::chooseARace(class GameData *, class GameData *);
?chooseARace@Faction@@QEAAPEAVGameData@@PEAV2@0@Z proc EXPORT
jmp function_pointers[_Faction_base+53*8]
?chooseARace@Faction@@QEAAPEAVGameData@@PEAV2@0@Z endp

; Faction::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@Faction@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Faction_base+54*8]
?setName@Faction@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Faction::getBuildingReplacement(class GameData *);
?getBuildingReplacement@Faction@@QEAAPEAVGameData@@PEAV2@@Z proc EXPORT
jmp function_pointers[_Faction_base+55*8]
?getBuildingReplacement@Faction@@QEAAPEAVGameData@@PEAV2@@Z endp

; Faction::_switchToUnloadedPlatoon(class ActivePlatoon *);
?_switchToUnloadedPlatoon@Faction@@QEAAXPEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+56*8]
?_switchToUnloadedPlatoon@Faction@@QEAAXPEAVActivePlatoon@@@Z endp

; Faction::_newPlatoon(class Faction *, class GameData *, class GameData *, const class Ogre::Vector3 &, bool);
?_newPlatoon@Faction@@QEAAPEAVPlatoon@@PEAV1@PEAVGameData@@1AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_Faction_base+57*8]
?_newPlatoon@Faction@@QEAAPEAVPlatoon@@PEAV1@PEAVGameData@@1AEBVVector3@Ogre@@_N@Z endp

; Faction::_addActivePlatoonToList(class Platoon *);
?_addActivePlatoonToList@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+58*8]
?_addActivePlatoonToList@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::addPlatoon(class Platoon *);
?addPlatoon@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+59*8]
?addPlatoon@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::changePlatoonIndex(class Platoon *, int);
?changePlatoonIndex@Faction@@QEAAXPEAVPlatoon@@H@Z proc EXPORT
jmp function_pointers[_Faction_base+60*8]
?changePlatoonIndex@Faction@@QEAAXPEAVPlatoon@@H@Z endp

; Faction::deactivatePlatoon(class Platoon *);
?deactivatePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+61*8]
?deactivatePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::activatePlatoon(class Platoon *);
?activatePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_Faction_base+62*8]
?activatePlatoon@Faction@@QEAAXPEAVPlatoon@@@Z endp

; Faction::updateUnloadedPlatoons(float);
?updateUnloadedPlatoons@Faction@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Faction_base+63*8]
?updateUnloadedPlatoons@Faction@@QEAAXM@Z endp

; Faction::updateActivePlatoons(float);
?updateActivePlatoons@Faction@@QEAAXM@Z proc EXPORT
jmp function_pointers[_Faction_base+64*8]
?updateActivePlatoons@Faction@@QEAAXM@Z endp

; Faction::spawnSquadMissionsUpdate();
?spawnSquadMissionsUpdate@Faction@@QEAAXXZ proc EXPORT
jmp function_pointers[_Faction_base+65*8]
?spawnSquadMissionsUpdate@Faction@@QEAAXXZ endp

; Faction::_spawnASquad(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?_spawnASquad@Faction@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_Faction_base+66*8]
?_spawnASquad@Faction@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp
