
?_CONSTRUCTOR@FactionsScreen@@QEAAPEAV1@PEAVManagementScreen@@@Z proc EXPORT
?_CONSTRUCTOR@FactionsScreen@@QEAAPEAV1@PEAVManagementScreen@@@Z endp

; FactionsScreen::FactionsScreen(class ManagementScreen *);
??0FactionsScreen@@QEAA@PEAVManagementScreen@@@Z proc EXPORT
jmp function_pointers[_FactionsScreen_base+0*8]
??0FactionsScreen@@QEAA@PEAVManagementScreen@@@Z endp

?_DESTRUCTOR@FactionsScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionsScreen@@QEAAXXZ endp

; FactionsScreen::~FactionsScreen();
??1FactionsScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_FactionsScreen_base+1*8]
??1FactionsScreen@@QEAA@XZ endp

; FactionsScreen::getVisible();
?getVisible@FactionsScreen@@QEBA_NXZ proc EXPORT
jmp function_pointers[_FactionsScreen_base+2*8]
?getVisible@FactionsScreen@@QEBA_NXZ endp

; FactionsScreen::clear();
?clear@FactionsScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionsScreen_base+3*8]
?clear@FactionsScreen@@QEAAXXZ endp

; FactionsScreen::update();
?update@FactionsScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionsScreen_base+4*8]
?update@FactionsScreen@@QEAAXXZ endp

; FactionsScreen::refresh();
?refresh@FactionsScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionsScreen_base+5*8]
?refresh@FactionsScreen@@QEAAXXZ endp

; FactionsScreen::updateInfo();
?updateInfo@FactionsScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_FactionsScreen_base+6*8]
?updateInfo@FactionsScreen@@QEAAXXZ endp

; FactionsScreen::notifyEditTextChange(class MyGUI::EditBox *);
?notifyEditTextChange@FactionsScreen@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_FactionsScreen_base+7*8]
?notifyEditTextChange@FactionsScreen@@QEAAXPEAVEditBox@MyGUI@@@Z endp

; FactionsScreen::setFocus(class MyGUI::Widget *, class MyGUI::Widget *);
?setFocus@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@0@Z proc EXPORT
jmp function_pointers[_FactionsScreen_base+8*8]
?setFocus@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@0@Z endp

; FactionsScreen::loseFocus(class MyGUI::Widget *, class MyGUI::Widget *);
?loseFocus@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@0@Z proc EXPORT
jmp function_pointers[_FactionsScreen_base+9*8]
?loseFocus@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@0@Z endp

; FactionsScreen::factionLineSelected(class MyGUI::Widget *);
?factionLineSelected@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_FactionsScreen_base+10*8]
?factionLineSelected@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; FactionsScreen::notifyMouseWheel(class MyGUI::Widget *, int);
?notifyMouseWheel@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_FactionsScreen_base+11*8]
?notifyMouseWheel@FactionsScreen@@QEAAXPEAVWidget@MyGUI@@H@Z endp
