
?_CONSTRUCTOR@Plant@FarmBuilding@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@Plant@FarmBuilding@@QEAAPEAV12@AEBU12@@Z endp

; FarmBuilding::Plant::Plant(const struct FarmBuilding::Plant &);
??0Plant@FarmBuilding@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_Plant_base+0*8]
??0Plant@FarmBuilding@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@Plant@FarmBuilding@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Plant@FarmBuilding@@QEAAPEAV12@XZ endp

; FarmBuilding::Plant::Plant();
??0Plant@FarmBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_FarmBuilding_Plant_base+1*8]
??0Plant@FarmBuilding@@QEAA@XZ endp

?_DESTRUCTOR@Plant@FarmBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Plant@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::Plant::~Plant();
??1Plant@FarmBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_FarmBuilding_Plant_base+2*8]
??1Plant@FarmBuilding@@QEAA@XZ endp

; FarmBuilding::Plant::operator=(const struct FarmBuilding::Plant &);
??4Plant@FarmBuilding@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_Plant_base+3*8]
??4Plant@FarmBuilding@@QEAAAEAU01@AEBU01@@Z endp
