
?_CONSTRUCTOR@FarmBatch@FarmBuilding@@QEAAPEAV12@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@FarmBatch@FarmBuilding@@QEAAPEAV12@PEAVGameData@@@Z endp

; FarmBuilding::FarmBatch::FarmBatch(class GameData *);
??0FarmBatch@FarmBuilding@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_FarmBatch_base+0*8]
??0FarmBatch@FarmBuilding@@QEAA@PEAVGameData@@@Z endp

; FarmBuilding::FarmBatch::load();
?load@FarmBatch@FarmBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_FarmBatch_base+1*8]
?load@FarmBatch@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::FarmBatch::meshLoaded(class Ogre::SharedPtr<Ogre::Resource>, void *);
?meshLoaded@FarmBatch@FarmBuilding@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_FarmBuilding_FarmBatch_base+2*8]
?meshLoaded@FarmBatch@FarmBuilding@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

; FarmBuilding::FarmBatch::createGeometry();
?createGeometry@FarmBatch@FarmBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_FarmBatch_base+3*8]
?createGeometry@FarmBatch@FarmBuilding@@QEAAXXZ endp

?_DESTRUCTOR@FarmBatch@FarmBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FarmBatch@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::FarmBatch::~FarmBatch();
??1FarmBatch@FarmBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_FarmBuilding_FarmBatch_base+4*8]
??1FarmBatch@FarmBuilding@@QEAA@XZ endp
