
?_CONSTRUCTOR@FarmBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@FarmBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; FarmBuilding::FarmBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0FarmBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+0*8]
??0FarmBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@FarmBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::~FarmBuilding();
??1FarmBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+1*8]
??1FarmBuilding@@UEAA@XZ endp

?_NV_createPhysical@FarmBuilding@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@FarmBuilding@@QEAA_NXZ endp

; FarmBuilding::createPhysical();
?createPhysical@FarmBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+2*8]
?createPhysical@FarmBuilding@@UEAA_NXZ endp

?_NV_destroyPhysical@FarmBuilding@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::destroyPhysical();
?destroyPhysical@FarmBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+3*8]
?destroyPhysical@FarmBuilding@@UEAAXXZ endp

?_NV_setVisible@FarmBuilding@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@FarmBuilding@@QEAAX_N@Z endp

; FarmBuilding::setVisible(bool);
?setVisible@FarmBuilding@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+4*8]
?setVisible@FarmBuilding@@UEAAX_N@Z endp

?_NV_update@FarmBuilding@@QEAAXXZ proc EXPORT
?_NV_update@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::update();
?update@FarmBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+5*8]
?update@FarmBuilding@@UEAAXXZ endp

?_NV_needsUpdate@FarmBuilding@@QEAA_NXZ proc EXPORT
?_NV_needsUpdate@FarmBuilding@@QEAA_NXZ endp

; FarmBuilding::needsUpdate();
?needsUpdate@FarmBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+6*8]
?needsUpdate@FarmBuilding@@UEAA_NXZ endp

?_NV_operate@FarmBuilding@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@FarmBuilding@@QEAAXPEAVCharacter@@M@Z endp

; FarmBuilding::operate(class Character *, float);
?operate@FarmBuilding@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+7*8]
?operate@FarmBuilding@@UEAAXPEAVCharacter@@M@Z endp

?_NV_isAnyInputsEmpty@FarmBuilding@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsEmpty@FarmBuilding@@QEBA_NXZ endp

; FarmBuilding::isAnyInputsEmpty();
?isAnyInputsEmpty@FarmBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+8*8]
?isAnyInputsEmpty@FarmBuilding@@UEBA_NXZ endp

?_NV_isProductionFull@FarmBuilding@@QEAA_NXZ proc EXPORT
?_NV_isProductionFull@FarmBuilding@@QEAA_NXZ endp

; FarmBuilding::isProductionFull();
?isProductionFull@FarmBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+9*8]
?isProductionFull@FarmBuilding@@UEAA_NXZ endp

?_NV_howMuchPowerDoYouWantForSortingFunction@FarmBuilding@@QEBAMXZ proc EXPORT
?_NV_howMuchPowerDoYouWantForSortingFunction@FarmBuilding@@QEBAMXZ endp

; FarmBuilding::howMuchPowerDoYouWantForSortingFunction();
?howMuchPowerDoYouWantForSortingFunction@FarmBuilding@@UEBAMXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+10*8]
?howMuchPowerDoYouWantForSortingFunction@FarmBuilding@@UEBAMXZ endp

?_NV_setupMiningResourceLevel@FarmBuilding@@QEAAXXZ proc EXPORT
?_NV_setupMiningResourceLevel@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::setupMiningResourceLevel();
?setupMiningResourceLevel@FarmBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+11*8]
?setupMiningResourceLevel@FarmBuilding@@UEAAXXZ endp

?_NV_getGUIData@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::getGUIData(class DatapanelGUI *, int);
?getGUIData@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+12*8]
?getGUIData@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIEfficiency@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIEfficiency@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::getGUIEfficiency(class DatapanelGUI *, int);
?getGUIEfficiency@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+13*8]
?getGUIEfficiency@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIWorkers@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIWorkers@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::getGUIWorkers(class DatapanelGUI *, int);
?getGUIWorkers@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+14*8]
?getGUIWorkers@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIState@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+15*8]
?getGUIState@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::destroyAPlant();
?destroyAPlant@FarmBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+16*8]
?destroyAPlant@FarmBuilding@@QEAA_NXZ endp

; FarmBuilding::timeSkip(float, bool);
?timeSkip@FarmBuilding@@QEAAXM_N@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+17*8]
?timeSkip@FarmBuilding@@QEAAXM_N@Z endp

; FarmBuilding::_updateInputs(float);
?_updateInputs@FarmBuilding@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+18*8]
?_updateInputs@FarmBuilding@@QEAA_NM@Z endp

?_NV_upgrade@FarmBuilding@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_upgrade@FarmBuilding@@QEAAXPEAVDataPanelLine@@@Z endp

; FarmBuilding::upgrade(class DataPanelLine *);
?upgrade@FarmBuilding@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+19*8]
?upgrade@FarmBuilding@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_downgrade@FarmBuilding@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_downgrade@FarmBuilding@@QEAAXPEAVDataPanelLine@@@Z endp

; FarmBuilding::downgrade(class DataPanelLine *);
?downgrade@FarmBuilding@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+20*8]
?downgrade@FarmBuilding@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_getGUIFertility@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIFertility@FarmBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::getGUIFertility(class DatapanelGUI *, int);
?getGUIFertility@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+21*8]
?getGUIFertility@FarmBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

; FarmBuilding::isCropsEdible();
?isCropsEdible@FarmBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+22*8]
?isCropsEdible@FarmBuilding@@QEAA_NXZ endp

; FarmBuilding::eat(float);
?eat@FarmBuilding@@QEAAXM@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+23*8]
?eat@FarmBuilding@@QEAAXM@Z endp

; FarmBuilding::getYieldChancePerCrop(class GameData *, class AreaBiomeGroup *, float, float);
?getYieldChancePerCrop@FarmBuilding@@SAMPEAVGameData@@PEAVAreaBiomeGroup@@MM@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+24*8]
?getYieldChancePerCrop@FarmBuilding@@SAMPEAVGameData@@PEAVAreaBiomeGroup@@MM@Z endp

; FarmBuilding::getYieldChancePerCrop(float);
?getYieldChancePerCrop@FarmBuilding@@QEAAMM@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+25*8]
?getYieldChancePerCrop@FarmBuilding@@QEAAMM@Z endp

; FarmBuilding::getCropMult(enum CropType);
?getCropMult@FarmBuilding@@QEAAMW4CropType@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+26*8]
?getCropMult@FarmBuilding@@QEAAMW4CropType@@@Z endp

?_NV_serialise@FarmBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@FarmBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; FarmBuilding::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@FarmBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+27*8]
?serialise@FarmBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@FarmBuilding@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@FarmBuilding@@QEAAXPEAVGameSaveState@@@Z endp

; FarmBuilding::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@FarmBuilding@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+28*8]
?loadFromSerialise@FarmBuilding@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_getDirectionMarker@FarmBuilding@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getDirectionMarker@FarmBuilding@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; FarmBuilding::getDirectionMarker(const class Ogre::Vector3 &);
?getDirectionMarker@FarmBuilding@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+29*8]
?getDirectionMarker@FarmBuilding@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_dontNeedWorkRightNow@FarmBuilding@@QEBA_NXZ proc EXPORT
?_NV_dontNeedWorkRightNow@FarmBuilding@@QEBA_NXZ endp

; FarmBuilding::dontNeedWorkRightNow();
?dontNeedWorkRightNow@FarmBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+30*8]
?dontNeedWorkRightNow@FarmBuilding@@UEBA_NXZ endp

; FarmBuilding::getFertilityMultiplier(float, class GameData *);
?getFertilityMultiplier@FarmBuilding@@SAMMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+31*8]
?getFertilityMultiplier@FarmBuilding@@SAMMPEAVGameData@@@Z endp

; FarmBuilding::setupMaterial();
?setupMaterial@FarmBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+32*8]
?setupMaterial@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::updateMaterial();
?updateMaterial@FarmBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+33*8]
?updateMaterial@FarmBuilding@@QEAAXXZ endp

; FarmBuilding::updatePlantInstance(struct FarmBuilding::Plant &);
?updatePlantInstance@FarmBuilding@@QEAAXAEAUPlant@1@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+34*8]
?updatePlantInstance@FarmBuilding@@QEAAXAEAUPlant@1@@Z endp

; FarmBuilding::createPlants(class FarmBuilding::FarmBatch *);
?createPlants@FarmBuilding@@QEAAXPEAVFarmBatch@1@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+35*8]
?createPlants@FarmBuilding@@QEAAXPEAVFarmBatch@1@@Z endp

; FarmBuilding::createClickHull(class FarmBuilding::FarmBatch *);
?createClickHull@FarmBuilding@@QEAAXPEAVFarmBatch@1@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+36*8]
?createClickHull@FarmBuilding@@QEAAXPEAVFarmBatch@1@@Z endp

; FarmBuilding::createEntity(class FarmBuilding::FarmBatch *);
?createEntity@FarmBuilding@@QEAAXPEAVFarmBatch@1@@Z proc EXPORT
jmp function_pointers[_FarmBuilding_base+37*8]
?createEntity@FarmBuilding@@QEAAXPEAVFarmBatch@1@@Z endp

; FarmBuilding::resetFarm();
?resetFarm@FarmBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_FarmBuilding_base+38*8]
?resetFarm@FarmBuilding@@QEAAXXZ endp
