
?_CONSTRUCTOR@FloatingProgressBar@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@FloatingProgressBar@@QEAAPEAV1@XZ endp

; FloatingProgressBar::FloatingProgressBar();
??0FloatingProgressBar@@QEAA@XZ proc EXPORT
jmp function_pointers[_FloatingProgressBar_base+0*8]
??0FloatingProgressBar@@QEAA@XZ endp

?_DESTRUCTOR@FloatingProgressBar@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FloatingProgressBar@@QEAAXXZ endp

; FloatingProgressBar::~FloatingProgressBar();
??1FloatingProgressBar@@UEAA@XZ proc EXPORT
jmp function_pointers[_FloatingProgressBar_base+1*8]
??1FloatingProgressBar@@UEAA@XZ endp

; FloatingProgressBar::setProgress(float);
?setProgress@FloatingProgressBar@@QEAAXM@Z proc EXPORT
jmp function_pointers[_FloatingProgressBar_base+2*8]
?setProgress@FloatingProgressBar@@QEAAXM@Z endp

; FloatingProgressBar::setCaption(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCaption@FloatingProgressBar@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_FloatingProgressBar_base+3*8]
?setCaption@FloatingProgressBar@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_update@FloatingProgressBar@@QEAAXXZ proc EXPORT
?_NV_update@FloatingProgressBar@@QEAAXXZ endp

; FloatingProgressBar::update();
?update@FloatingProgressBar@@UEAAXXZ proc EXPORT
jmp function_pointers[_FloatingProgressBar_base+4*8]
?update@FloatingProgressBar@@UEAAXXZ endp
