
?_CONSTRUCTOR@ProgressBarWidget@FloatingProgressBar@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ProgressBarWidget@FloatingProgressBar@@QEAAPEAV12@XZ endp

; FloatingProgressBar::ProgressBarWidget::ProgressBarWidget();
??0ProgressBarWidget@FloatingProgressBar@@QEAA@XZ proc EXPORT
jmp function_pointers[_FloatingProgressBar_ProgressBarWidget_base+0*8]
??0ProgressBarWidget@FloatingProgressBar@@QEAA@XZ endp

?_DESTRUCTOR@ProgressBarWidget@FloatingProgressBar@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ProgressBarWidget@FloatingProgressBar@@QEAAXXZ endp

; FloatingProgressBar::ProgressBarWidget::~ProgressBarWidget();
??1ProgressBarWidget@FloatingProgressBar@@UEAA@XZ proc EXPORT
jmp function_pointers[_FloatingProgressBar_ProgressBarWidget_base+1*8]
??1ProgressBarWidget@FloatingProgressBar@@UEAA@XZ endp

; FloatingProgressBar::ProgressBarWidget::setVisible(bool);
?setVisible@ProgressBarWidget@FloatingProgressBar@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_FloatingProgressBar_ProgressBarWidget_base+2*8]
?setVisible@ProgressBarWidget@FloatingProgressBar@@QEAAX_N@Z endp

; FloatingProgressBar::ProgressBarWidget::setProgress(int);
?setProgress@ProgressBarWidget@FloatingProgressBar@@QEAAXH@Z proc EXPORT
jmp function_pointers[_FloatingProgressBar_ProgressBarWidget_base+3*8]
?setProgress@ProgressBarWidget@FloatingProgressBar@@QEAAXH@Z endp

; FloatingProgressBar::ProgressBarWidget::setPosition(int, int);
?setPosition@ProgressBarWidget@FloatingProgressBar@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_FloatingProgressBar_ProgressBarWidget_base+4*8]
?setPosition@ProgressBarWidget@FloatingProgressBar@@QEAAXHH@Z endp

; FloatingProgressBar::ProgressBarWidget::setCaption(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCaption@ProgressBarWidget@FloatingProgressBar@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_FloatingProgressBar_ProgressBarWidget_base+5*8]
?setCaption@ProgressBarWidget@FloatingProgressBar@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
