
?_CONSTRUCTOR@FogEditor@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@FogEditor@@QEAAPEAV1@XZ endp

; FogEditor::FogEditor();
??0FogEditor@@QEAA@XZ proc EXPORT
jmp function_pointers[_FogEditor_base+0*8]
??0FogEditor@@QEAA@XZ endp

; FogEditor::show();
?show@FogEditor@@QEAAXXZ proc EXPORT
jmp function_pointers[_FogEditor_base+1*8]
?show@FogEditor@@QEAAXXZ endp

; FogEditor::close();
?close@FogEditor@@QEAAXXZ proc EXPORT
jmp function_pointers[_FogEditor_base+2*8]
?close@FogEditor@@QEAAXXZ endp

; FogEditor::isActive();
?isActive@FogEditor@@QEBA_NXZ proc EXPORT
jmp function_pointers[_FogEditor_base+3*8]
?isActive@FogEditor@@QEBA_NXZ endp

; FogEditor::update();
?update@FogEditor@@QEAA_NXZ proc EXPORT
jmp function_pointers[_FogEditor_base+4*8]
?update@FogEditor@@QEAA_NXZ endp

; FogEditor::save(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?save@FogEditor@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+5*8]
?save@FogEditor@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; FogEditor::closeWindow(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeWindow@FogEditor@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+6*8]
?closeWindow@FogEditor@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; FogEditor::addFog(class MyGUI::Widget *);
?addFog@FogEditor@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+7*8]
?addFog@FogEditor@@QEAAXPEAVWidget@MyGUI@@@Z endp

; FogEditor::removeFog(class MyGUI::Widget *);
?removeFog@FogEditor@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+8*8]
?removeFog@FogEditor@@QEAAXPEAVWidget@MyGUI@@@Z endp

; FogEditor::selectFog(class MyGUI::ListBox *, unsigned __int64);
?selectFog@FogEditor@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_FogEditor_base+9*8]
?selectFog@FogEditor@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; FogEditor::updateFogName(class DataPanelLine *);
?updateFogName@FogEditor@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+10*8]
?updateFogName@FogEditor@@QEAAXPEAVDataPanelLine@@@Z endp

; FogEditor::updateFogValues(class DataPanelLine *);
?updateFogValues@FogEditor@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+11*8]
?updateFogValues@FogEditor@@QEAAXPEAVDataPanelLine@@@Z endp

; FogEditor::selectNextEdge(class DataPanelLine *);
?selectNextEdge@FogEditor@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_FogEditor_base+12*8]
?selectNextEdge@FogEditor@@QEAAXPEAVDataPanelLine@@@Z endp

?_DESTRUCTOR@FogEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FogEditor@@QEAAXXZ endp

; FogEditor::~FogEditor();
??1FogEditor@@UEAA@XZ proc EXPORT
jmp function_pointers[_FogEditor_base+13*8]
??1FogEditor@@UEAA@XZ endp
