
?_CONSTRUCTOR@TreeData@FoliageSystem@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TreeData@FoliageSystem@@QEAAPEAV12@XZ endp

; FoliageSystem::TreeData::TreeData();
??0TreeData@FoliageSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_FoliageSystem_TreeData_base+0*8]
??0TreeData@FoliageSystem@@QEAA@XZ endp

?_DESTRUCTOR@TreeData@FoliageSystem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TreeData@FoliageSystem@@QEAAXXZ endp

; FoliageSystem::TreeData::~TreeData();
??1TreeData@FoliageSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_FoliageSystem_TreeData_base+1*8]
??1TreeData@FoliageSystem@@QEAA@XZ endp

; FoliageSystem::TreeData::operator=(const class FoliageSystem::TreeData &);
??4TreeData@FoliageSystem@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_FoliageSystem_TreeData_base+2*8]
??4TreeData@FoliageSystem@@QEAAAEAV01@AEBV01@@Z endp
