
?_CONSTRUCTOR@EntData@FoliageSystem@@QEAAPEAV12@PEAVGameData@@_N0@Z proc EXPORT
?_CONSTRUCTOR@EntData@FoliageSystem@@QEAAPEAV12@PEAVGameData@@_N0@Z endp

; FoliageSystem::EntData::EntData(class GameData *, bool, class GameData *);
??0EntData@FoliageSystem@@QEAA@PEAVGameData@@_N0@Z proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+0*8]
??0EntData@FoliageSystem@@QEAA@PEAVGameData@@_N0@Z endp

?_DESTRUCTOR@EntData@FoliageSystem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@EntData@FoliageSystem@@QEAAXXZ endp

; FoliageSystem::EntData::~EntData();
??1EntData@FoliageSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+1*8]
??1EntData@FoliageSystem@@QEAA@XZ endp

; FoliageSystem::EntData::createEntity1();
?createEntity1@EntData@FoliageSystem@@QEAAPEAVEntity@Ogre@@XZ proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+2*8]
?createEntity1@EntData@FoliageSystem@@QEAAPEAVEntity@Ogre@@XZ endp

; FoliageSystem::EntData::createEntity1Callback(class Ogre::SharedPtr<Ogre::Resource>, void *);
?createEntity1Callback@EntData@FoliageSystem@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+3*8]
?createEntity1Callback@EntData@FoliageSystem@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

; FoliageSystem::EntData::createEntity2();
?createEntity2@EntData@FoliageSystem@@QEAAPEAVEntity@Ogre@@XZ proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+4*8]
?createEntity2@EntData@FoliageSystem@@QEAAPEAVEntity@Ogre@@XZ endp

; FoliageSystem::EntData::createEntity2Callback(class Ogre::SharedPtr<Ogre::Resource>, void *);
?createEntity2Callback@EntData@FoliageSystem@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+5*8]
?createEntity2Callback@EntData@FoliageSystem@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

; FoliageSystem::EntData::selectBiomeEntity(const class Ogre::Vector3 &);
?selectBiomeEntity@EntData@FoliageSystem@@QEAAPEAVEntity@Ogre@@AEBVVector3@4@@Z proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+6*8]
?selectBiomeEntity@EntData@FoliageSystem@@QEAAPEAVEntity@Ogre@@AEBVVector3@4@@Z endp

; FoliageSystem::EntData::isLoaded();
?isLoaded@EntData@FoliageSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_FoliageSystem_EntData_base+7*8]
?isLoaded@EntData@FoliageSystem@@QEBA_NXZ endp
