
?_CONSTRUCTOR@ForgottenGUI@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ForgottenGUI@@QEAAPEAV1@XZ endp

; ForgottenGUI::ForgottenGUI();
??0ForgottenGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+0*8]
??0ForgottenGUI@@QEAA@XZ endp

?_DESTRUCTOR@ForgottenGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::~ForgottenGUI();
??1ForgottenGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+1*8]
??1ForgottenGUI@@UEAA@XZ endp

; ForgottenGUI::clearGUI();
?clearGUI@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+2*8]
?clearGUI@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::shutDown();
?shutDown@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+3*8]
?shutDown@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::restart();
?restart@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+4*8]
?restart@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::changeFontSize();
?changeFontSize@ForgottenGUI@@SAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+5*8]
?changeFontSize@ForgottenGUI@@SAXXZ endp

; ForgottenGUI::setupGuiScaling();
?setupGuiScaling@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+6*8]
?setupGuiScaling@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::init();
?init@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+7*8]
?init@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::getTopOfScreenMessagePosition();
?getTopOfScreenMessagePosition@ForgottenGUI@@QEAAMXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+8*8]
?getTopOfScreenMessagePosition@ForgottenGUI@@QEAAMXZ endp

; ForgottenGUI::showLoadingMessage(bool);
?showLoadingMessage@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+9*8]
?showLoadingMessage@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::isLoadingMessageVisible();
?isLoadingMessageVisible@ForgottenGUI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+10*8]
?isLoadingMessageVisible@ForgottenGUI@@QEAA_NXZ endp

; ForgottenGUI::showPauseMessage(bool);
?showPauseMessage@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+11*8]
?showPauseMessage@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::isLoading();
?isLoading@ForgottenGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+12*8]
?isLoading@ForgottenGUI@@QEBA_NXZ endp

; ForgottenGUI::setLoading(bool);
?setLoading@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+13*8]
?setLoading@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::isPaused();
?isPaused@ForgottenGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+14*8]
?isPaused@ForgottenGUI@@QEBA_NXZ endp

; ForgottenGUI::inDialogue();
?inDialogue@ForgottenGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+15*8]
?inDialogue@ForgottenGUI@@QEBA_NXZ endp

; ForgottenGUI::destroy(class ScreenLabelInterface *);
?destroy@ForgottenGUI@@QEAAXPEAVScreenLabelInterface@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+16*8]
?destroy@ForgottenGUI@@QEAAXPEAVScreenLabelInterface@@@Z endp

; ForgottenGUI::destroy(class DatapanelGUI *);
?destroy@ForgottenGUI@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+17*8]
?destroy@ForgottenGUI@@QEAAXPEAVDatapanelGUI@@@Z endp

; ForgottenGUI::destroy(class GUIWindow *);
?destroy@ForgottenGUI@@QEAAXPEAVGUIWindow@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+18*8]
?destroy@ForgottenGUI@@QEAAXPEAVGUIWindow@@@Z endp

; ForgottenGUI::createDatapanel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class MyGUI::Widget *, bool);
?createDatapanel@ForgottenGUI@@QEAAPEAVDatapanelGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+19*8]
?createDatapanel@ForgottenGUI@@QEAAPEAVDatapanelGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N@Z endp

; ForgottenGUI::createDatapanel(float, float, float, float, bool, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, bool);
?createDatapanel@ForgottenGUI@@QEAAPEAVDatapanelGUI@@MMMM_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+20*8]
?createDatapanel@ForgottenGUI@@QEAAPEAVDatapanelGUI@@MMMM_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; ForgottenGUI::messageBox(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, bool, class MyGUI::delegates::IDelegate1<int> *);
?messageBox@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NPEAV?$IDelegate1@H@delegates@3@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+21*8]
?messageBox@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H_NPEAV?$IDelegate1@H@delegates@3@@Z endp

; ForgottenGUI::hideMessageBox(bool);
?hideMessageBox@ForgottenGUI@@QEAA_N_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+22*8]
?hideMessageBox@ForgottenGUI@@QEAA_N_N@Z endp

; ForgottenGUI::hasModalMessage();
?hasModalMessage@ForgottenGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+23*8]
?hasModalMessage@ForgottenGUI@@QEBA_NXZ endp

; ForgottenGUI::showMainbar(bool);
?showMainbar@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+24*8]
?showMainbar@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::updateBountyPanelVisibility();
?updateBountyPanelVisibility@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+25*8]
?updateBountyPanelVisibility@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::getInDialogue();
?getInDialogue@ForgottenGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+26*8]
?getInDialogue@ForgottenGUI@@QEBA_NXZ endp

; ForgottenGUI::getToolTip();
?getToolTip@ForgottenGUI@@QEAAPEAVToolTip@@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+27*8]
?getToolTip@ForgottenGUI@@QEAAPEAVToolTip@@XZ endp

; ForgottenGUI::isVisible();
?isVisible@ForgottenGUI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+28*8]
?isVisible@ForgottenGUI@@QEAA_NXZ endp

; ForgottenGUI::toggle();
?toggle@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+29*8]
?toggle@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::showNames(bool);
?showNames@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+30*8]
?showNames@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::showPrintOutput(bool);
?showPrintOutput@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+31*8]
?showPrintOutput@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::showCharacterEditor(const class lektor<Character *>, enum CharacterEditMode, const class std::vector<GameDataReference,Ogre::STLAllocator<GameDataReference,Ogre::CategorisedAllocPolicy<0> > > *);
?showCharacterEditor@ForgottenGUI@@QEAAXV?$lektor@PEAVCharacter@@@@W4CharacterEditMode@@PEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+32*8]
?showCharacterEditor@ForgottenGUI@@QEAAXV?$lektor@PEAVCharacter@@@@W4CharacterEditMode@@PEBV?$vector@VGameDataReference@@V?$STLAllocator@VGameDataReference@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; ForgottenGUI::closeCharacterEditor();
?closeCharacterEditor@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+33*8]
?closeCharacterEditor@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::isCharacterEditorMode();
?isCharacterEditorMode@ForgottenGUI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+34*8]
?isCharacterEditorMode@ForgottenGUI@@QEAA_NXZ endp

; ForgottenGUI::showCharacterStatsWindow(const class hand &);
?showCharacterStatsWindow@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+35*8]
?showCharacterStatsWindow@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::closeCharacterStatsWindow(const class hand &);
?closeCharacterStatsWindow@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+36*8]
?closeCharacterStatsWindow@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::closeAllCharacterStatsWindows();
?closeAllCharacterStatsWindows@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+37*8]
?closeAllCharacterStatsWindows@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::isStatsWindowOpen();
?isStatsWindowOpen@ForgottenGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+38*8]
?isStatsWindowOpen@ForgottenGUI@@QEBA_NXZ endp

; ForgottenGUI::toggleStatsWindow(const class hand &);
?toggleStatsWindow@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+39*8]
?toggleStatsWindow@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::toggleCharacterStatsWindowPermanent(const class hand &);
?toggleCharacterStatsWindowPermanent@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+40*8]
?toggleCharacterStatsWindowPermanent@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::characterStatsWindowVisible();
?characterStatsWindowVisible@ForgottenGUI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+41*8]
?characterStatsWindowVisible@ForgottenGUI@@QEAA_NXZ endp

; ForgottenGUI::selectedObjectsChanged();
?selectedObjectsChanged@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+42*8]
?selectedObjectsChanged@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::updateToOrdersPanel();
?updateToOrdersPanel@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+43*8]
?updateToOrdersPanel@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::notifyTownDeleted(class Town *);
?notifyTownDeleted@ForgottenGUI@@QEAAXPEAVTown@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+44*8]
?notifyTownDeleted@ForgottenGUI@@QEAAXPEAVTown@@@Z endp

; ForgottenGUI::update();
?update@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+45*8]
?update@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::showTradeWindow(const class hand &, const class hand &, enum TradeWindowType);
?showTradeWindow@ForgottenGUI@@QEAAXAEBVhand@@0W4TradeWindowType@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+46*8]
?showTradeWindow@ForgottenGUI@@QEAAXAEBVhand@@0W4TradeWindowType@@@Z endp

; ForgottenGUI::closeTradeWindow();
?closeTradeWindow@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+47*8]
?closeTradeWindow@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::showInventory(const class hand &, bool, float, float);
?showInventory@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@_NMM@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+48*8]
?showInventory@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@_NMM@Z endp

; ForgottenGUI::showTraderInventory(const class hand &);
?showTraderInventory@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+49*8]
?showTraderInventory@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z endp

; ForgottenGUI::showInventoryBuilding(const class hand &);
?showInventoryBuilding@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+50*8]
?showInventoryBuilding@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z endp

; ForgottenGUI::showInventoryNPC(const class hand &);
?showInventoryNPC@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+51*8]
?showInventoryNPC@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z endp

; ForgottenGUI::closeInventory(const class hand &);
?closeInventory@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+52*8]
?closeInventory@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::closeInventoryBuilding();
?closeInventoryBuilding@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+53*8]
?closeInventoryBuilding@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::closeAllInventories();
?closeAllInventories@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+54*8]
?closeAllInventories@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::closeAllWindows();
?closeAllWindows@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+55*8]
?closeAllWindows@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::getInventoryWindow(const class hand &);
?getInventoryWindow@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+56*8]
?getInventoryWindow@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@@Z endp

; ForgottenGUI::toggleInventory(const class hand &, class InventoryGUI *, bool);
?toggleInventory@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@PEAV2@_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+57*8]
?toggleInventory@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@PEAV2@_N@Z endp

; ForgottenGUI::getNumOpenInventoryWindows();
?getNumOpenInventoryWindows@ForgottenGUI@@QEBAHXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+58*8]
?getNumOpenInventoryWindows@ForgottenGUI@@QEBAHXZ endp

; ForgottenGUI::getInventoryWindowWithMouse();
?getInventoryWindowWithMouse@ForgottenGUI@@QEAAPEAVInventoryGUI@@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+59*8]
?getInventoryWindowWithMouse@ForgottenGUI@@QEAAPEAVInventoryGUI@@XZ endp

; ForgottenGUI::hasInventoryWindowOpen(const class hand &);
?hasInventoryWindowOpen@ForgottenGUI@@QEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+60*8]
?hasInventoryWindowOpen@ForgottenGUI@@QEAA_NAEBVhand@@@Z endp

; ForgottenGUI::isAnyInventoryWindowOpen();
?isAnyInventoryWindowOpen@ForgottenGUI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+61*8]
?isAnyInventoryWindowOpen@ForgottenGUI@@QEAA_NXZ endp

; ForgottenGUI::toggleInventoryWindowPermanent(const class hand &);
?toggleInventoryWindowPermanent@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+62*8]
?toggleInventoryWindowPermanent@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::toggleHelpWindow();
?toggleHelpWindow@ForgottenGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+63*8]
?toggleHelpWindow@ForgottenGUI@@QEAAXXZ endp

; ForgottenGUI::getSelectedObject();
?getSelectedObject@ForgottenGUI@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+64*8]
?getSelectedObject@ForgottenGUI@@QEBAAEBVhand@@XZ endp

; ForgottenGUI::getSelectedPlayerCharacter();
?getSelectedPlayerCharacter@ForgottenGUI@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+65*8]
?getSelectedPlayerCharacter@ForgottenGUI@@QEBAAEBVhand@@XZ endp

; ForgottenGUI::addWindowToUpdateList(class GUIWindow *);
?addWindowToUpdateList@ForgottenGUI@@QEAAXPEAVGUIWindow@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+66*8]
?addWindowToUpdateList@ForgottenGUI@@QEAAXPEAVGUIWindow@@@Z endp

; ForgottenGUI::removeWindowFromUpdateList(class GUIWindow *);
?removeWindowFromUpdateList@ForgottenGUI@@QEAAXPEAVGUIWindow@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+67*8]
?removeWindowFromUpdateList@ForgottenGUI@@QEAAXPEAVGUIWindow@@@Z endp

; ForgottenGUI::addScreenLabel(class ScreenLabelInterface *);
?addScreenLabel@ForgottenGUI@@QEAAXPEAVScreenLabelInterface@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+68*8]
?addScreenLabel@ForgottenGUI@@QEAAXPEAVScreenLabelInterface@@@Z endp

; ForgottenGUI::addDatapanelToUpdateList(class DatapanelGUI *);
?addDatapanelToUpdateList@ForgottenGUI@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+69*8]
?addDatapanelToUpdateList@ForgottenGUI@@QEAAXPEAVDatapanelGUI@@@Z endp

; ForgottenGUI::removeDatapanelFromUpdateList(class DatapanelGUI *);
?removeDatapanelFromUpdateList@ForgottenGUI@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+70*8]
?removeDatapanelFromUpdateList@ForgottenGUI@@QEAAXPEAVDatapanelGUI@@@Z endp

; ForgottenGUI::destroyWidget(class MyGUI::Widget *);
?destroyWidget@ForgottenGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+71*8]
?destroyWidget@ForgottenGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ForgottenGUI::destroyWidgets(class MyGUI::Enumerator<std::vector<MyGUI::Widget *,std::allocator<MyGUI::Widget *> > > &);
?destroyWidgets@ForgottenGUI@@QEAAXAEAV?$Enumerator@V?$vector@PEAVWidget@MyGUI@@V?$allocator@PEAVWidget@MyGUI@@@std@@@std@@@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+72*8]
?destroyWidgets@ForgottenGUI@@QEAAXAEAV?$Enumerator@V?$vector@PEAVWidget@MyGUI@@V?$allocator@PEAVWidget@MyGUI@@@std@@@std@@@MyGUI@@@Z endp

; ForgottenGUI::destroyWidgets(const class std::vector<MyGUI::Widget *,std::allocator<MyGUI::Widget *> > &);
?destroyWidgets@ForgottenGUI@@QEAAXAEBV?$vector@PEAVWidget@MyGUI@@V?$allocator@PEAVWidget@MyGUI@@@std@@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+73*8]
?destroyWidgets@ForgottenGUI@@QEAAXAEBV?$vector@PEAVWidget@MyGUI@@V?$allocator@PEAVWidget@MyGUI@@@std@@@std@@@Z endp

; ForgottenGUI::widgetHasMouse(class MyGUI::Widget *);
?widgetHasMouse@ForgottenGUI@@QEAA_NPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+74*8]
?widgetHasMouse@ForgottenGUI@@QEAA_NPEAVWidget@MyGUI@@@Z endp

; ForgottenGUI::setup(class Ogre::Root *, class Ogre::RenderWindow *);
?setup@ForgottenGUI@@QEAAXPEAVRoot@Ogre@@PEAVRenderWindow@3@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+75*8]
?setup@ForgottenGUI@@QEAAXPEAVRoot@Ogre@@PEAVRenderWindow@3@@Z endp

; ForgottenGUI::changeMouseCursor(enum CursorType, const class hand &, const class hand &);
?changeMouseCursor@ForgottenGUI@@QEAAXW4CursorType@@AEBVhand@@1@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+76*8]
?changeMouseCursor@ForgottenGUI@@QEAAXW4CursorType@@AEBVhand@@1@Z endp

; ForgottenGUI::changeMouseCursor(enum CursorType);
?changeMouseCursor@ForgottenGUI@@QEAAXW4CursorType@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+77*8]
?changeMouseCursor@ForgottenGUI@@QEAAXW4CursorType@@@Z endp

; ForgottenGUI::setMouseCursorVisible(bool);
?setMouseCursorVisible@ForgottenGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+78*8]
?setMouseCursorVisible@ForgottenGUI@@QEAAX_N@Z endp

; ForgottenGUI::getGuiManager();
?getGuiManager@ForgottenGUI@@QEAAPEAVGui@MyGUI@@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+79*8]
?getGuiManager@ForgottenGUI@@QEAAPEAVGui@MyGUI@@XZ endp

; ForgottenGUI::_showTradeWindow(class RootObject *, class RootObject *, enum TradeWindowType);
?_showTradeWindow@ForgottenGUI@@QEAAXPEAVRootObject@@0W4TradeWindowType@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+80*8]
?_showTradeWindow@ForgottenGUI@@QEAAXPEAVRootObject@@0W4TradeWindowType@@@Z endp

; ForgottenGUI::setInventoryPosition(const class hand &, class InventoryGUI *);
?setInventoryPosition@ForgottenGUI@@QEAAXAEBVhand@@PEAVInventoryGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+81*8]
?setInventoryPosition@ForgottenGUI@@QEAAXAEBVhand@@PEAVInventoryGUI@@@Z endp

; ForgottenGUI::createInventoryWindow(const class hand &, class Inventory *, class InventoryLayout *, class RootObject *);
?createInventoryWindow@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+82*8]
?createInventoryWindow@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z endp

; ForgottenGUI::createInventoryWindow(const class hand &, class InventoryLayout *);
?createInventoryWindow@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@PEAVInventoryLayout@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+83*8]
?createInventoryWindow@ForgottenGUI@@QEAAPEAVInventoryGUI@@AEBVhand@@PEAVInventoryLayout@@@Z endp

; ForgottenGUI::inventoriesSelectedObjectUpdate(const class hand &);
?inventoriesSelectedObjectUpdate@ForgottenGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+84*8]
?inventoriesSelectedObjectUpdate@ForgottenGUI@@QEAAXAEBVhand@@@Z endp

; ForgottenGUI::keepWindownOnScreen(class MyGUI::Widget *);
?keepWindownOnScreen@ForgottenGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+85*8]
?keepWindownOnScreen@ForgottenGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ForgottenGUI::getDataLineColor(int, int);
?getDataLineColor@ForgottenGUI@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+86*8]
?getDataLineColor@ForgottenGUI@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; ForgottenGUI::createPanel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float, float, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?createPanel@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@1@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+87*8]
?createPanel@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@1@Z endp

; ForgottenGUI::createPanelAbs(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float, float, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?createPanelAbs@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@1@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+88*8]
?createPanelAbs@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@1@Z endp

; ForgottenGUI::createImage(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createImage@ForgottenGUI@@QEAAPEAVImageBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+89*8]
?createImage@ForgottenGUI@@QEAAPEAVImageBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createImageAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createImageAbs@ForgottenGUI@@QEAAPEAVImageBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+90*8]
?createImageAbs@ForgottenGUI@@QEAAPEAVImageBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createRotatableImageAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createRotatableImageAbs@ForgottenGUI@@QEAAPEAVImageBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+91*8]
?createRotatableImageAbs@ForgottenGUI@@QEAAPEAVImageBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createTabPanel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createTabPanel@ForgottenGUI@@QEAAPEAVTabControl@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMM00@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+92*8]
?createTabPanel@ForgottenGUI@@QEAAPEAVTabControl@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMM00@Z endp

; ForgottenGUI::createButtonAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createButtonAbs@ForgottenGUI@@QEAAPEAVButton@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@11@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+93*8]
?createButtonAbs@ForgottenGUI@@QEAAPEAVButton@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@11@Z endp

; ForgottenGUI::createButton(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createButton@ForgottenGUI@@QEAAPEAVButton@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@11@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+94*8]
?createButton@ForgottenGUI@@QEAAPEAVButton@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@11@Z endp

; ForgottenGUI::createDropBox(class MyGUI::Widget *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float, float);
?createDropBox@ForgottenGUI@@QEAAPEAVComboBox@MyGUI@@PEAVWidget@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMM@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+95*8]
?createDropBox@ForgottenGUI@@QEAAPEAVComboBox@MyGUI@@PEAVWidget@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMM@Z endp

; ForgottenGUI::createDropBoxAbs(class MyGUI::Widget *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, int, int);
?createDropBoxAbs@ForgottenGUI@@QEAAPEAVComboBox@MyGUI@@PEAVWidget@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHHH@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+96*8]
?createDropBoxAbs@ForgottenGUI@@QEAAPEAVComboBox@MyGUI@@PEAVWidget@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHHH@Z endp

; ForgottenGUI::createProgressBar(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createProgressBar@ForgottenGUI@@QEAAPEAVProgressBar@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+97*8]
?createProgressBar@ForgottenGUI@@QEAAPEAVProgressBar@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createProgressBarAbs(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createProgressBarAbs@ForgottenGUI@@QEAAPEAVProgressBar@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+98*8]
?createProgressBarAbs@ForgottenGUI@@QEAAPEAVProgressBar@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createFloatingLabel(float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, struct MyGUI::Align, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?createFloatingLabel@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UAlign@3@V45@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+99*8]
?createFloatingLabel@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UAlign@3@V45@@Z endp

; ForgottenGUI::createLabel(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createLabel@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+100*8]
?createLabel@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; ForgottenGUI::createLabel(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, struct MyGUI::Align);
?createLabel@ForgottenGUI@@QEAAPEAVTextBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UAlign@3@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+101*8]
?createLabel@ForgottenGUI@@QEAAPEAVTextBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UAlign@3@@Z endp

; ForgottenGUI::createLabelAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, struct MyGUI::Align);
?createLabelAbs@ForgottenGUI@@QEAAPEAVTextBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UAlign@3@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+102*8]
?createLabelAbs@ForgottenGUI@@QEAAPEAVTextBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UAlign@3@@Z endp

; ForgottenGUI::createLabelAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createLabelAbs@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+103*8]
?createLabelAbs@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; ForgottenGUI::createValueEdit(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createValueEdit@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+104*8]
?createValueEdit@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createEditBox(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?createEditBox@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+105*8]
?createEditBox@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N@Z endp

; ForgottenGUI::createEditBox(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?createEditBox@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+106*8]
?createEditBox@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; ForgottenGUI::createEditBoxAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?createEditBoxAbs@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+107*8]
?createEditBoxAbs@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N@Z endp

; ForgottenGUI::createEditBoxAbs(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?createEditBoxAbs@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+108*8]
?createEditBoxAbs@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; ForgottenGUI::createScrollBarAbs(class MyGUI::Widget *, int, int, int, int, int, int);
?createScrollBarAbs@ForgottenGUI@@QEAAPEAVScrollBar@MyGUI@@PEAVWidget@3@HHHHHH@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+109*8]
?createScrollBarAbs@ForgottenGUI@@QEAAPEAVScrollBar@MyGUI@@PEAVWidget@3@HHHHHH@Z endp

; ForgottenGUI::createCheckbox(class MyGUI::Widget *, int, int, int, int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createCheckbox@ForgottenGUI@@QEAAPEAVButton@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+110*8]
?createCheckbox@ForgottenGUI@@QEAAPEAVButton@MyGUI@@PEAVWidget@3@HHHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createValueEditTransparent(class MyGUI::Widget *, float, float, float, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createValueEditTransparent@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+111*8]
?createValueEditTransparent@ForgottenGUI@@QEAAPEAVEditBox@MyGUI@@PEAVWidget@3@MMMMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ForgottenGUI::createListbox(class MyGUI::Window *, float, float, float, float);
?createListbox@ForgottenGUI@@QEAAPEAVListBox@MyGUI@@PEAVWindow@3@MMMM@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+112*8]
?createListbox@ForgottenGUI@@QEAAPEAVListBox@MyGUI@@PEAVWindow@3@MMMM@Z endp

; ForgottenGUI::createFloatingImage(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float, float, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?createFloatingImage@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+113*8]
?createFloatingImage@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@@Z endp

; ForgottenGUI::createFloatingImageAbs(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float, float, float, float, class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?createFloatingImageAbs@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+114*8]
?createFloatingImageAbs@ForgottenGUI@@QEAAPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMMMV45@@Z endp

; ForgottenGUI::createFloatingProgressBar();
?createFloatingProgressBar@ForgottenGUI@@QEAAPEAVFloatingProgressBar@@XZ proc EXPORT
jmp function_pointers[_ForgottenGUI_base+115*8]
?createFloatingProgressBar@ForgottenGUI@@QEAAPEAVFloatingProgressBar@@XZ endp

; ForgottenGUI::createScreenLabel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const struct MyGUI::Colour &, enum ScreenLabel::LabelSize, enum ScreenLabel::RisingSpeed);
?createScreenLabel@ForgottenGUI@@QEAAPEAVScreenLabel@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUColour@MyGUI@@W4LabelSize@2@W4RisingSpeed@2@@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+116*8]
?createScreenLabel@ForgottenGUI@@QEAAPEAVScreenLabel@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUColour@MyGUI@@W4LabelSize@2@W4RisingSpeed@2@@Z endp

; ForgottenGUI::createScreenLabelD(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?createScreenLabelD@ForgottenGUI@@QEAAPEAVScreenLabelDebug@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_ForgottenGUI_base+117*8]
?createScreenLabelD@ForgottenGUI@@QEAAPEAVScreenLabelDebug@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp
