
?_CONSTRUCTOR@FormationMover@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@FormationMover@@QEAAPEAV1@XZ endp

; FormationMover::FormationMover();
??0FormationMover@@QEAA@XZ proc EXPORT
jmp function_pointers[_FormationMover_base+0*8]
??0FormationMover@@QEAA@XZ endp

?_DESTRUCTOR@FormationMover@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FormationMover@@QEAAXXZ endp

; FormationMover::~FormationMover();
??1FormationMover@@QEAA@XZ proc EXPORT
jmp function_pointers[_FormationMover_base+1*8]
??1FormationMover@@QEAA@XZ endp

; FormationMover::update();
?update@FormationMover@@QEAAXXZ proc EXPORT
jmp function_pointers[_FormationMover_base+2*8]
?update@FormationMover@@QEAAXXZ endp

; FormationMover::getSpeeds(float &, float &, const class Ogre::Vector3 &, float);
?getSpeeds@FormationMover@@QEAAXAEAM0AEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_FormationMover_base+3*8]
?getSpeeds@FormationMover@@QEAAXAEAM0AEBVVector3@Ogre@@M@Z endp

; FormationMover::setFormationMode(const class hand &);
?setFormationMode@FormationMover@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_FormationMover_base+4*8]
?setFormationMode@FormationMover@@QEAAXAEBVhand@@@Z endp

; FormationMover::stopFormationMode();
?stopFormationMode@FormationMover@@QEAAXXZ proc EXPORT
jmp function_pointers[_FormationMover_base+5*8]
?stopFormationMode@FormationMover@@QEAAXXZ endp
