
?_NV_createInventoryLayout@FurnaceBuilding@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@FurnaceBuilding@@QEAAPEAVInventoryLayout@@XZ endp

; FurnaceBuilding::createInventoryLayout();
?createInventoryLayout@FurnaceBuilding@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+0*8]
?createInventoryLayout@FurnaceBuilding@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_setupFromData@FurnaceBuilding@@QEAAXXZ proc EXPORT
?_NV_setupFromData@FurnaceBuilding@@QEAAXXZ endp

; FurnaceBuilding::setupFromData();
?setupFromData@FurnaceBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+1*8]
?setupFromData@FurnaceBuilding@@UEAAXXZ endp

?_NV_getGUIData@FurnaceBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@FurnaceBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; FurnaceBuilding::getGUIData(class DatapanelGUI *, int);
?getGUIData@FurnaceBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+2*8]
?getGUIData@FurnaceBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

; FurnaceBuilding::getInputValueTotal();
?getInputValueTotal@FurnaceBuilding@@QEAAMXZ proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+3*8]
?getInputValueTotal@FurnaceBuilding@@QEAAMXZ endp

?_NV_getInputValue@FurnaceBuilding@@QEAAMPEAVItem@@@Z proc EXPORT
?_NV_getInputValue@FurnaceBuilding@@QEAAMPEAVItem@@@Z endp

; FurnaceBuilding::getInputValue(class Item *);
?getInputValue@FurnaceBuilding@@UEAAMPEAVItem@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+4*8]
?getInputValue@FurnaceBuilding@@UEAAMPEAVItem@@@Z endp

?_NV_getDefaultTask@FurnaceBuilding@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@FurnaceBuilding@@QEAA?AW4TaskType@@XZ endp

; FurnaceBuilding::getDefaultTask();
?getDefaultTask@FurnaceBuilding@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+5*8]
?getDefaultTask@FurnaceBuilding@@UEAA?AW4TaskType@@XZ endp

?_NV_getResourcesNeededBecauseNotFull@FurnaceBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
?_NV_getResourcesNeededBecauseNotFull@FurnaceBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; FurnaceBuilding::getResourcesNeededBecauseNotFull(class lektor<GameData *> &);
?getResourcesNeededBecauseNotFull@FurnaceBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+6*8]
?getResourcesNeededBecauseNotFull@FurnaceBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

?_NV_getResourcesNeededBecauseEmpty@FurnaceBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
?_NV_getResourcesNeededBecauseEmpty@FurnaceBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; FurnaceBuilding::getResourcesNeededBecauseEmpty(class lektor<GameData *> &);
?getResourcesNeededBecauseEmpty@FurnaceBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+7*8]
?getResourcesNeededBecauseEmpty@FurnaceBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

?_NV_canHaveSomeOfThese@FurnaceBuilding@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_canHaveSomeOfThese@FurnaceBuilding@@QEAA_NPEAVGameData@@@Z endp

; FurnaceBuilding::canHaveSomeOfThese(class GameData *);
?canHaveSomeOfThese@FurnaceBuilding@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+8*8]
?canHaveSomeOfThese@FurnaceBuilding@@UEAA_NPEAVGameData@@@Z endp

; FurnaceBuilding::incinerate(class DataPanelLine *);
?incinerate@FurnaceBuilding@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+9*8]
?incinerate@FurnaceBuilding@@QEAAXPEAVDataPanelLine@@@Z endp

?_CONSTRUCTOR@FurnaceBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@FurnaceBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; FurnaceBuilding::FurnaceBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0FurnaceBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+10*8]
??0FurnaceBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@FurnaceBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FurnaceBuilding@@QEAAXXZ endp

; FurnaceBuilding::~FurnaceBuilding();
??1FurnaceBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+11*8]
??1FurnaceBuilding@@UEAA@XZ endp

?_NV_operate@FurnaceBuilding@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@FurnaceBuilding@@QEAAXPEAVCharacter@@M@Z endp

; FurnaceBuilding::operate(class Character *, float);
?operate@FurnaceBuilding@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+12*8]
?operate@FurnaceBuilding@@UEAAXPEAVCharacter@@M@Z endp

?_NV_updateInputs@FurnaceBuilding@@QEAAXM@Z proc EXPORT
?_NV_updateInputs@FurnaceBuilding@@QEAAXM@Z endp

; FurnaceBuilding::updateInputs(float);
?updateInputs@FurnaceBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+13*8]
?updateInputs@FurnaceBuilding@@UEAAXM@Z endp

?_NV_updateOutput@FurnaceBuilding@@QEAAXM@Z proc EXPORT
?_NV_updateOutput@FurnaceBuilding@@QEAAXM@Z endp

; FurnaceBuilding::updateOutput(float);
?updateOutput@FurnaceBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+14*8]
?updateOutput@FurnaceBuilding@@UEAAXM@Z endp

?_NV_limitInputsOutputRate@FurnaceBuilding@@QEAA_NAEAM@Z proc EXPORT
?_NV_limitInputsOutputRate@FurnaceBuilding@@QEAA_NAEAM@Z endp

; FurnaceBuilding::limitInputsOutputRate(float &);
?limitInputsOutputRate@FurnaceBuilding@@UEAA_NAEAM@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+15*8]
?limitInputsOutputRate@FurnaceBuilding@@UEAA_NAEAM@Z endp

; FurnaceBuilding::getIronAmountInItem(class GameData *);
?getIronAmountInItem@FurnaceBuilding@@QEBAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_FurnaceBuilding_base+16*8]
?getIronAmountInItem@FurnaceBuilding@@QEBAMPEAVGameData@@@Z endp
