
?_CONSTRUCTOR@FurnaceInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
?_CONSTRUCTOR@FurnaceInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; FurnaceInventoryLayout::FurnaceInventoryLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int);
??0FurnaceInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
jmp function_pointers[_FurnaceInventoryLayout_base+0*8]
??0FurnaceInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; symbol is too long
; ?setupSections@FurnaceInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; FurnaceInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
FurnaceInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_FurnaceInventoryLayout_base+1*8]
FurnaceInventoryLayout_setupSections_PLACEHOLDER endp

?_DESTRUCTOR@FurnaceInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FurnaceInventoryLayout@@QEAAXXZ endp

; FurnaceInventoryLayout::~FurnaceInventoryLayout();
??1FurnaceInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_FurnaceInventoryLayout_base+2*8]
??1FurnaceInventoryLayout@@UEAA@XZ endp
