
?_DESTRUCTOR@GameDataEditorWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataEditorWindow@@QEAAXXZ endp

; GameDataEditorWindow::~GameDataEditorWindow();
??1GameDataEditorWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameDataEditorWindow_base+0*8]
??1GameDataEditorWindow@@UEAA@XZ endp

?_NV_show@GameDataEditorWindow@@QEAAX_N@Z proc EXPORT
?_NV_show@GameDataEditorWindow@@QEAAX_N@Z endp

; GameDataEditorWindow::show(bool);
?show@GameDataEditorWindow@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_GameDataEditorWindow_base+1*8]
?show@GameDataEditorWindow@@UEAAX_N@Z endp

; GameDataEditorWindow::show(bool, float, float, class GameData *);
?show@GameDataEditorWindow@@QEAAX_NMMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataEditorWindow_base+2*8]
?show@GameDataEditorWindow@@QEAAX_NMMPEAVGameData@@@Z endp

; GameDataEditorWindow::initDataValues();
?initDataValues@GameDataEditorWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataEditorWindow_base+3*8]
?initDataValues@GameDataEditorWindow@@QEAAXXZ endp
