
?_CONSTRUCTOR@GameLauncher@@QEAAPEAV1@PEAVRoot@Ogre@@PEAVCWnd@@@Z proc EXPORT
?_CONSTRUCTOR@GameLauncher@@QEAAPEAV1@PEAVRoot@Ogre@@PEAVCWnd@@@Z endp

; GameLauncher::GameLauncher(class Ogre::Root *, class CWnd *);
??0GameLauncher@@QEAA@PEAVRoot@Ogre@@PEAVCWnd@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_base+0*8]
??0GameLauncher@@QEAA@PEAVRoot@Ogre@@PEAVCWnd@@@Z endp

?_DESTRUCTOR@GameLauncher@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameLauncher@@QEAAXXZ endp

; GameLauncher::~GameLauncher();
??1GameLauncher@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_base+1*8]
??1GameLauncher@@UEAA@XZ endp

?_NV_OnInitDialog@GameLauncher@@QEAAHXZ proc EXPORT
?_NV_OnInitDialog@GameLauncher@@QEAAHXZ endp

; GameLauncher::OnInitDialog();
?OnInitDialog@GameLauncher@@UEAAHXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+2*8]
?OnInitDialog@GameLauncher@@UEAAHXZ endp

?_NV_DoDataExchange@GameLauncher@@QEAAXPEAVCDataExchange@@@Z proc EXPORT
?_NV_DoDataExchange@GameLauncher@@QEAAXPEAVCDataExchange@@@Z endp

; GameLauncher::DoDataExchange(class CDataExchange *);
?DoDataExchange@GameLauncher@@UEAAXPEAVCDataExchange@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_base+3*8]
?DoDataExchange@GameLauncher@@UEAAXPEAVCDataExchange@@@Z endp

; GameLauncher::addTab(int, const wchar_t *, unsigned int);
?addTab@GameLauncher@@QEAA_NHPEB_WI@Z proc EXPORT
jmp function_pointers[_GameLauncher_base+4*8]
?addTab@GameLauncher@@QEAA_NHPEB_WI@Z endp

; GameLauncher::saveSettings();
?saveSettings@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+5*8]
?saveSettings@GameLauncher@@QEAAXXZ endp

; GameLauncher::CStringToString(const class ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > > &);
?CStringToString@GameLauncher@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_base+6*8]
?CStringToString@GameLauncher@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z endp

; GameLauncher::GetThisMessageMap();
?GetThisMessageMap@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_base+7*8]
?GetThisMessageMap@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ endp

?_NV_GetMessageMap@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
?_NV_GetMessageMap@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::GetMessageMap();
?GetMessageMap@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_base+8*8]
?GetMessageMap@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::OnPaint();
?OnPaint@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+9*8]
?OnPaint@GameLauncher@@QEAAXXZ endp

; GameLauncher::OnBnClickedLauncherOk();
?OnBnClickedLauncherOk@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+10*8]
?OnBnClickedLauncherOk@GameLauncher@@QEAAXXZ endp

; GameLauncher::OnClickedLauncherCancel();
?OnClickedLauncherCancel@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+11*8]
?OnClickedLauncherCancel@GameLauncher@@QEAAXXZ endp

; GameLauncher::OnSelchangeLauncherTabs(struct tagNMHDR *, __int64 *);
?OnSelchangeLauncherTabs@GameLauncher@@QEAAXPEAUtagNMHDR@@PEA_J@Z proc EXPORT
jmp function_pointers[_GameLauncher_base+12*8]
?OnSelchangeLauncherTabs@GameLauncher@@QEAAXPEAUtagNMHDR@@PEA_J@Z endp

; GameLauncher::OnBnClickedLauncherBtnSaveConfig();
?OnBnClickedLauncherBtnSaveConfig@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+13*8]
?OnBnClickedLauncherBtnSaveConfig@GameLauncher@@QEAAXXZ endp

; GameLauncher::OnBnClickedLauncherBtnAdvConfig();
?OnBnClickedLauncherBtnAdvConfig@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+14*8]
?OnBnClickedLauncherBtnAdvConfig@GameLauncher@@QEAAXXZ endp

; GameLauncher::OnCbnSelchangeLauncherComboLanguage();
?OnCbnSelchangeLauncherComboLanguage@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_base+15*8]
?OnCbnSelchangeLauncherComboLanguage@GameLauncher@@QEAAXXZ endp
