
?_CONSTRUCTOR@GameDataValuePair@@QEAAPEAV1@PEAVGameData@@H@Z proc EXPORT
?_CONSTRUCTOR@GameDataValuePair@@QEAAPEAV1@PEAVGameData@@H@Z endp

; GameDataValuePair::GameDataValuePair(class GameData *, int);
??0GameDataValuePair@@QEAA@PEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_GameDataValuePair_base+0*8]
??0GameDataValuePair@@QEAA@PEAVGameData@@H@Z endp

?_CONSTRUCTOR@GameDataValuePair@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataValuePair@@QEAAPEAV1@XZ endp

; GameDataValuePair::GameDataValuePair();
??0GameDataValuePair@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataValuePair_base+1*8]
??0GameDataValuePair@@QEAA@XZ endp
