
?_CONSTRUCTOR@VideoDevice@GameLauncher@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@VideoDevice@GameLauncher@@QEAAPEAV12@AEBV12@@Z endp

; GameLauncher::VideoDevice::VideoDevice(const class GameLauncher::VideoDevice &);
??0VideoDevice@GameLauncher@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoDevice_base+0*8]
??0VideoDevice@GameLauncher@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@VideoDevice@GameLauncher@@QEAAPEAV12@W4RendererType@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@VideoDevice@GameLauncher@@QEAAPEAV12@W4RendererType@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameLauncher::VideoDevice::VideoDevice(enum GameLauncher::RendererType, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0VideoDevice@GameLauncher@@QEAA@W4RendererType@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoDevice_base+1*8]
??0VideoDevice@GameLauncher@@QEAA@W4RendererType@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@VideoDevice@GameLauncher@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@VideoDevice@GameLauncher@@QEAAXXZ endp

; GameLauncher::VideoDevice::~VideoDevice();
??1VideoDevice@GameLauncher@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_VideoDevice_base+2*8]
??1VideoDevice@GameLauncher@@QEAA@XZ endp

; GameLauncher::VideoDevice::operator=(const class GameLauncher::VideoDevice &);
??4VideoDevice@GameLauncher@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoDevice_base+3*8]
??4VideoDevice@GameLauncher@@QEAAAEAV01@AEBV01@@Z endp
