
; GameWorld::justLoadFactionRelations(class GameDataManager *);
?justLoadFactionRelations@GameWorld@@QEAAXPEAVGameDataManager@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+0*8]
?justLoadFactionRelations@GameWorld@@QEAAXPEAVGameDataManager@@@Z endp

; GameWorld::startUpThreads();
?startUpThreads@GameWorld@@QEAA_NXZ proc EXPORT
jmp function_pointers[_GameWorld_base+1*8]
?startUpThreads@GameWorld@@QEAA_NXZ endp

?_CONSTRUCTOR@GameWorld@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameWorld@@QEAAPEAV1@XZ endp

; GameWorld::GameWorld();
??0GameWorld@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+2*8]
??0GameWorld@@QEAA@XZ endp

?_DESTRUCTOR@GameWorld@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameWorld@@QEAAXXZ endp

; GameWorld::~GameWorld();
??1GameWorld@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+3*8]
??1GameWorld@@QEAA@XZ endp

; GameWorld::start(class RendererT *);
?start@GameWorld@@QEAA_NPEAVRendererT@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+4*8]
?start@GameWorld@@QEAA_NPEAVRendererT@@@Z endp

; GameWorld::resetGame();
?resetGame@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+5*8]
?resetGame@GameWorld@@QEAAXXZ endp

; GameWorld::_clearAndDestroyGameWorldStuff();
?_clearAndDestroyGameWorldStuff@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+6*8]
?_clearAndDestroyGameWorldStuff@GameWorld@@QEAAXXZ endp

; GameWorld::initialisation();
?initialisation@GameWorld@@QEAA_NXZ proc EXPORT
jmp function_pointers[_GameWorld_base+7*8]
?initialisation@GameWorld@@QEAA_NXZ endp

; GameWorld::initialisationGameData();
?initialisationGameData@GameWorld@@QEAA_NXZ proc EXPORT
jmp function_pointers[_GameWorld_base+8*8]
?initialisationGameData@GameWorld@@QEAA_NXZ endp

; GameWorld::dailyUpdates();
?dailyUpdates@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+9*8]
?dailyUpdates@GameWorld@@QEAAXXZ endp

; GameWorld::initialiseNewGameWorld(class GameDataManager *);
?initialiseNewGameWorld@GameWorld@@QEAAXPEAVGameDataManager@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+10*8]
?initialiseNewGameWorld@GameWorld@@QEAAXPEAVGameDataManager@@@Z endp

; GameWorld::errorToLogReleaseMode(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?errorToLogReleaseMode@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+11*8]
?errorToLogReleaseMode@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameWorld::errorD(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?errorD@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+12*8]
?errorD@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameWorld::logToSave(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?logToSave@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+13*8]
?logToSave@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameWorld::log(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?log@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+14*8]
?log@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameWorld::logDebug(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?logDebug@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_GameWorld_base+15*8]
?logDebug@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; GameWorld::logDebug(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?logDebug@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+16*8]
?logDebug@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameWorld::destroy(class Ogre::MovableObject *);
?destroy@GameWorld@@QEAAXPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+17*8]
?destroy@GameWorld@@QEAAXPEAVMovableObject@Ogre@@@Z endp

; GameWorld::destroy(class AttachedEntity *);
?destroy@GameWorld@@QEAAXPEAVAttachedEntity@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+18*8]
?destroy@GameWorld@@QEAAXPEAVAttachedEntity@@@Z endp

; GameWorld::destroy(class TownBuildingsManager *);
?destroy@GameWorld@@QEAAXPEAVTownBuildingsManager@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+19*8]
?destroy@GameWorld@@QEAAXPEAVTownBuildingsManager@@@Z endp

; GameWorld::destroy(class NestBatcher *);
?destroy@GameWorld@@QEAAXPEAVNestBatcher@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+20*8]
?destroy@GameWorld@@QEAAXPEAVNestBatcher@@@Z endp

; GameWorld::destroy(class RootObject *, bool, const char *);
?destroy@GameWorld@@QEAA_NPEAVRootObject@@_NPEBD@Z proc EXPORT
jmp function_pointers[_GameWorld_base+21*8]
?destroy@GameWorld@@QEAA_NPEAVRootObject@@_NPEBD@Z endp

; GameWorld::destroy(class GameData *);
?destroy@GameWorld@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+22*8]
?destroy@GameWorld@@QEAAXPEAVGameData@@@Z endp

; GameWorld::getIsInKillList(class RootObject *);
?getIsInKillList@GameWorld@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+23*8]
?getIsInKillList@GameWorld@@QEAA_NPEAVRootObject@@@Z endp

; GameWorld::flushKillList();
?flushKillList@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+24*8]
?flushKillList@GameWorld@@QEAAXXZ endp

; GameWorld::dynamicDestroyBuilding(const class hand &);
?dynamicDestroyBuilding@GameWorld@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+25*8]
?dynamicDestroyBuilding@GameWorld@@QEAAXAEBVhand@@@Z endp

; GameWorld::allThreadQueuesAreClear();
?allThreadQueuesAreClear@GameWorld@@QEAA_NXZ proc EXPORT
jmp function_pointers[_GameWorld_base+26*8]
?allThreadQueuesAreClear@GameWorld@@QEAA_NXZ endp

; GameWorld::initBaseMods();
?initBaseMods@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+27*8]
?initBaseMods@GameWorld@@QEAAXXZ endp

; GameWorld::initModsList();
?initModsList@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+28*8]
?initModsList@GameWorld@@QEAAXXZ endp

; GameWorld::getModsListFromConfig();
?getModsListFromConfig@GameWorld@@QEAA?AV?$lektor@PEAVModInfo@@@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+29*8]
?getModsListFromConfig@GameWorld@@QEAA?AV?$lektor@PEAVModInfo@@@@XZ endp

; GameWorld::getAllModsList();
?getAllModsList@GameWorld@@QEBAAEBV?$lektor@PEAVModInfo@@@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+30*8]
?getAllModsList@GameWorld@@QEBAAEBV?$lektor@PEAVModInfo@@@@XZ endp

; GameWorld::getModIndex(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getModIndex@GameWorld@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+31*8]
?getModIndex@GameWorld@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameWorld::getModLeveldataFolder(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getModLeveldataFolder@GameWorld@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+32*8]
?getModLeveldataFolder@GameWorld@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; GameWorld::getObjectsWithinSphere(class lektor<RootObject *> &, const class Ogre::Vector3 &, float, enum itemType, int, class RootObject *);
?getObjectsWithinSphere@GameWorld@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@MW4itemType@@HPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+33*8]
?getObjectsWithinSphere@GameWorld@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@MW4itemType@@HPEAVRootObject@@@Z endp

; GameWorld::getCharactersWithinSphere(class lektor<RootObject *> &, const class Ogre::Vector3 &, float, float, float, int, int, class RootObject *);
?getCharactersWithinSphere@GameWorld@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@MMMHHPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+34*8]
?getCharactersWithinSphere@GameWorld@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@MMMHHPEAVRootObject@@@Z endp

; GameWorld::getObjectsWithinBox(class lektor<RootObject *> &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, const class Ogre::Quaternion &, enum itemType, int, class RootObject *);
?getObjectsWithinBox@GameWorld@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@1AEBVQuaternion@4@W4itemType@@HPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+35*8]
?getObjectsWithinBox@GameWorld@@QEAAXAEAV?$lektor@PEAVRootObject@@@@AEBVVector3@Ogre@@1AEBVQuaternion@4@W4itemType@@HPEAVRootObject@@@Z endp

; GameWorld::buildingIntersectionTestCapsule(const class Ogre::Vector3 &, float, float, class RootObject *);
?buildingIntersectionTestCapsule@GameWorld@@QEAA_NAEBVVector3@Ogre@@MMPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+36*8]
?buildingIntersectionTestCapsule@GameWorld@@QEAA_NAEBVVector3@Ogre@@MMPEAVRootObject@@@Z endp

; GameWorld::getLightLevel(const class Ogre::Vector3 &, int, bool);
?getLightLevel@GameWorld@@QEBAMAEBVVector3@Ogre@@H_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+37*8]
?getLightLevel@GameWorld@@QEBAMAEBVVector3@Ogre@@H_N@Z endp

; GameWorld::populateMapArea_nonPermanent(class ZoneMap *, int, bool);
?populateMapArea_nonPermanent@GameWorld@@QEAAXPEAVZoneMap@@H_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+38*8]
?populateMapArea_nonPermanent@GameWorld@@QEAAXPEAVZoneMap@@H_N@Z endp

; GameWorld::findValidSpawnPos(class Ogre::Vector3 &, const class Ogre::Vector3 &);
?findValidSpawnPos@GameWorld@@QEAA_NAEAVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+39*8]
?findValidSpawnPos@GameWorld@@QEAA_NAEAVVector3@Ogre@@AEBV23@@Z endp

; GameWorld::togglePause(bool);
?togglePause@GameWorld@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+40*8]
?togglePause@GameWorld@@QEAAX_N@Z endp

; GameWorld::getFrameSpeedMultiplier();
?getFrameSpeedMultiplier@GameWorld@@QEBAMXZ proc EXPORT
jmp function_pointers[_GameWorld_base+41*8]
?getFrameSpeedMultiplier@GameWorld@@QEBAMXZ endp

; GameWorld::setFrameSpeedMultiplier(float);
?setFrameSpeedMultiplier@GameWorld@@QEAAXM@Z proc EXPORT
jmp function_pointers[_GameWorld_base+42*8]
?setFrameSpeedMultiplier@GameWorld@@QEAAXM@Z endp

; GameWorld::setGameSpeed(float, bool);
?setGameSpeed@GameWorld@@QEAAXM_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+43*8]
?setGameSpeed@GameWorld@@QEAAXM_N@Z endp

; GameWorld::userPause(bool);
?userPause@GameWorld@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+44*8]
?userPause@GameWorld@@QEAAX_N@Z endp

; GameWorld::isPaused();
?isPaused@GameWorld@@QEBA_NXZ proc EXPORT
jmp function_pointers[_GameWorld_base+45*8]
?isPaused@GameWorld@@QEBA_NXZ endp

; GameWorld::getCameraCenter();
?getCameraCenter@GameWorld@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+46*8]
?getCameraCenter@GameWorld@@QEBA?BVVector3@Ogre@@XZ endp

; GameWorld::getCameraPos();
?getCameraPos@GameWorld@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+47*8]
?getCameraPos@GameWorld@@QEBA?BVVector3@Ogre@@XZ endp

; GameWorld::fixNaNPosition(class Ogre::Vector3 &);
?fixNaNPosition@GameWorld@@QEBA_NAEAVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+48*8]
?fixNaNPosition@GameWorld@@QEBA_NAEAVVector3@Ogre@@@Z endp

; GameWorld::getWindSpeed(const class Ogre::Vector3 &);
?getWindSpeed@GameWorld@@QEBAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+49*8]
?getWindSpeed@GameWorld@@QEBAMAEBVVector3@Ogre@@@Z endp

; GameWorld::isLoadingFromASaveGame();
?isLoadingFromASaveGame@GameWorld@@QEAA_NXZ proc EXPORT
jmp function_pointers[_GameWorld_base+50*8]
?isLoadingFromASaveGame@GameWorld@@QEAA_NXZ endp

; GameWorld::addToUpdateListMain(class Character *);
?addToUpdateListMain@GameWorld@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+51*8]
?addToUpdateListMain@GameWorld@@QEAAXPEAVCharacter@@@Z endp

; GameWorld::removeFromUpdateListMain(class Character *);
?removeFromUpdateListMain@GameWorld@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+52*8]
?removeFromUpdateListMain@GameWorld@@QEAAXPEAVCharacter@@@Z endp

; GameWorld::getCharacterUpdateList();
?getCharacterUpdateList@GameWorld@@QEBAAEBV?$unordered_set@PEAVCharacter@@U?$hash@PEAVCharacter@@@boost@@U?$equal_to@PEAVCharacter@@@std@@V?$STLAllocator@PEAVCharacter@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+53*8]
?getCharacterUpdateList@GameWorld@@QEBAAEBV?$unordered_set@PEAVCharacter@@U?$hash@PEAVCharacter@@@boost@@U?$equal_to@PEAVCharacter@@@std@@V?$STLAllocator@PEAVCharacter@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ endp

; GameWorld::addToDeathParade(class Character *);
?addToDeathParade@GameWorld@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+54*8]
?addToDeathParade@GameWorld@@QEAAXPEAVCharacter@@@Z endp

; GameWorld::removeFromDeathParade(class Character *);
?removeFromDeathParade@GameWorld@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+55*8]
?removeFromDeathParade@GameWorld@@QEAA_NPEAVCharacter@@@Z endp

; GameWorld::removeFromDeathParadeByPlatoon(class Platoon *);
?removeFromDeathParadeByPlatoon@GameWorld@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+56*8]
?removeFromDeathParadeByPlatoon@GameWorld@@QEAAXPEAVPlatoon@@@Z endp

; GameWorld::getFromDeathParade(const class hand &);
?getFromDeathParade@GameWorld@@QEAAPEAVCharacter@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+57*8]
?getFromDeathParade@GameWorld@@QEAAPEAVCharacter@@AEBVhand@@@Z endp

; GameWorld::hideContextMenu();
?hideContextMenu@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+58*8]
?hideContextMenu@GameWorld@@QEAAXXZ endp

; GameWorld::showPlayerAMessage_withLog(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?showPlayerAMessage_withLog@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+59*8]
?showPlayerAMessage_withLog@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; GameWorld::showPlayerAMessage(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?showPlayerAMessage@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+60*8]
?showPlayerAMessage@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; GameWorld::showPlayerAMessageD(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?showPlayerAMessageD@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+61*8]
?showPlayerAMessageD@GameWorld@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; GameWorld::playNotification(const char *);
?playNotification@GameWorld@@QEBAXPEBD@Z proc EXPORT
jmp function_pointers[_GameWorld_base+62*8]
?playNotification@GameWorld@@QEBAXPEBD@Z endp

; GameWorld::sysMessage(const class GameWorld::SysMessage &);
?sysMessage@GameWorld@@QEAAXAEBVSysMessage@1@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+63*8]
?sysMessage@GameWorld@@QEAAXAEBVSysMessage@1@@Z endp

; GameWorld::sysMessageUrgent(const class GameWorld::SysMessage &);
?sysMessageUrgent@GameWorld@@QEAAXAEBVSysMessage@1@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+64*8]
?sysMessageUrgent@GameWorld@@QEAAXAEBVSysMessage@1@@Z endp

; GameWorld::sysMessage_noDuplicates(const class GameWorld::SysMessage &);
?sysMessage_noDuplicates@GameWorld@@QEAAXAEBVSysMessage@1@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+65*8]
?sysMessage_noDuplicates@GameWorld@@QEAAXAEBVSysMessage@1@@Z endp

?_NV_mainLoop_GPUSensitiveStuff@GameWorld@@QEAAXM@Z proc EXPORT
?_NV_mainLoop_GPUSensitiveStuff@GameWorld@@QEAAXM@Z endp

; GameWorld::mainLoop_GPUSensitiveStuff(float);
?mainLoop_GPUSensitiveStuff@GameWorld@@UEAAXM@Z proc EXPORT
jmp function_pointers[_GameWorld_base+66*8]
?mainLoop_GPUSensitiveStuff@GameWorld@@UEAAXM@Z endp

; GameWorld::clearPortaitsUpdate();
?clearPortaitsUpdate@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+67*8]
?clearPortaitsUpdate@GameWorld@@QEAAXXZ endp

; GameWorld::addPortraitUpdate(const class hand &);
?addPortraitUpdate@GameWorld@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+68*8]
?addPortraitUpdate@GameWorld@@QEAAXAEBVhand@@@Z endp

; GameWorld::removePortaitUpdate(const class hand &);
?removePortaitUpdate@GameWorld@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+69*8]
?removePortaitUpdate@GameWorld@@QEAAXAEBVhand@@@Z endp

; GameWorld::processSysMessages();
?processSysMessages@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+70*8]
?processSysMessages@GameWorld@@QEAAXXZ endp

; GameWorld::getCollisionGroupType(enum itemType, enum NxShapesType &, unsigned int &);
?getCollisionGroupType@GameWorld@@QEAAXW4itemType@@AEAW4NxShapesType@@AEAI@Z proc EXPORT
jmp function_pointers[_GameWorld_base+71*8]
?getCollisionGroupType@GameWorld@@QEAAXW4itemType@@AEAW4NxShapesType@@AEAI@Z endp

; GameWorld::destroyDeathParade();
?destroyDeathParade@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+72*8]
?destroyDeathParade@GameWorld@@QEAAXXZ endp

; GameWorld::processKeys();
?processKeys@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+73*8]
?processKeys@GameWorld@@QEAAXXZ endp

; GameWorld::processThreadMessages();
?processThreadMessages@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+74*8]
?processThreadMessages@GameWorld@@QEAAXXZ endp

; GameWorld::charsUpdate();
?charsUpdate@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+75*8]
?charsUpdate@GameWorld@@QEAAXXZ endp

; GameWorld::charsUpdateUT();
?charsUpdateUT@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+76*8]
?charsUpdateUT@GameWorld@@QEAAXXZ endp

; GameWorld::charsUpdatePaused();
?charsUpdatePaused@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+77*8]
?charsUpdatePaused@GameWorld@@QEAAXXZ endp

; GameWorld::charsUpdateDeathParade();
?charsUpdateDeathParade@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+78*8]
?charsUpdateDeathParade@GameWorld@@QEAAXXZ endp

; GameWorld::threadSafeRagdollUpdates();
?threadSafeRagdollUpdates@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+79*8]
?threadSafeRagdollUpdates@GameWorld@@QEAAXXZ endp

; GameWorld::AINonRenderThread();
?AINonRenderThread@GameWorld@@QEAAPEAVThreadWannabe@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+80*8]
?AINonRenderThread@GameWorld@@QEAAPEAVThreadWannabe@@XZ endp

; GameWorld::processAttachmentsKillList();
?processAttachmentsKillList@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+81*8]
?processAttachmentsKillList@GameWorld@@QEAAXXZ endp

; GameWorld::processKillList(bool);
?processKillList@GameWorld@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_GameWorld_base+82*8]
?processKillList@GameWorld@@QEAAX_N@Z endp

; GameWorld::processUpdateRemovalList();
?processUpdateRemovalList@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+83*8]
?processUpdateRemovalList@GameWorld@@QEAAXXZ endp

; GameWorld::loadAllPlatoons();
?loadAllPlatoons@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+84*8]
?loadAllPlatoons@GameWorld@@QEAAXXZ endp

; GameWorld::reCalculateFortificationInsideOutsideStateForAllCharacters();
?reCalculateFortificationInsideOutsideStateForAllCharacters@GameWorld@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameWorld_base+85*8]
?reCalculateFortificationInsideOutsideStateForAllCharacters@GameWorld@@QEAAXXZ endp

; GameWorld::getTimeStamp();
?getTimeStamp@GameWorld@@QEAANXZ proc EXPORT
jmp function_pointers[_GameWorld_base+86*8]
?getTimeStamp@GameWorld@@QEAANXZ endp

; GameWorld::getTimeFromStamp(const class TimeOfDay &);
?getTimeFromStamp@GameWorld@@QEAA?AVTimeOfDay@@AEBV2@@Z proc EXPORT
jmp function_pointers[_GameWorld_base+87*8]
?getTimeFromStamp@GameWorld@@QEAA?AVTimeOfDay@@AEBV2@@Z endp

; GameWorld::getTimeFromStamp(double);
?getTimeFromStamp@GameWorld@@QEAAMN@Z proc EXPORT
jmp function_pointers[_GameWorld_base+88*8]
?getTimeFromStamp@GameWorld@@QEAAMN@Z endp

; GameWorld::getTimeFromStamp_inGameHours(double);
?getTimeFromStamp_inGameHours@GameWorld@@QEAAMN@Z proc EXPORT
jmp function_pointers[_GameWorld_base+89*8]
?getTimeFromStamp_inGameHours@GameWorld@@QEAAMN@Z endp

; GameWorld::getTimeStamp_inGameHours();
?getTimeStamp_inGameHours@GameWorld@@QEAA?AVTimeOfDay@@XZ proc EXPORT
jmp function_pointers[_GameWorld_base+90*8]
?getTimeStamp_inGameHours@GameWorld@@QEAA?AVTimeOfDay@@XZ endp

; GameWorld::getLengthOfHourInRealSeconds();
?getLengthOfHourInRealSeconds@GameWorld@@QEAAMXZ proc EXPORT
jmp function_pointers[_GameWorld_base+91*8]
?getLengthOfHourInRealSeconds@GameWorld@@QEAAMXZ endp
