
?_CONSTRUCTOR@GameDataReference@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@GameDataReference@@QEAAPEAV1@AEBV1@@Z endp

; GameDataReference::GameDataReference(const class GameDataReference &);
??0GameDataReference@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_GameDataReference_base+0*8]
??0GameDataReference@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@GameDataReference@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTripleInt@@@Z proc EXPORT
?_CONSTRUCTOR@GameDataReference@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTripleInt@@@Z endp

; GameDataReference::GameDataReference(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class TripleInt);
??0GameDataReference@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTripleInt@@@Z proc EXPORT
jmp function_pointers[_GameDataReference_base+1*8]
??0GameDataReference@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VTripleInt@@@Z endp

?_CONSTRUCTOR@GameDataReference@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataReference@@QEAAPEAV1@XZ endp

; GameDataReference::GameDataReference();
??0GameDataReference@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataReference_base+2*8]
??0GameDataReference@@QEAA@XZ endp

; GameDataReference::getPtr(class GameDataContainer *);
?getPtr@GameDataReference@@QEBAPEAVGameData@@PEAVGameDataContainer@@@Z proc EXPORT
jmp function_pointers[_GameDataReference_base+3*8]
?getPtr@GameDataReference@@QEBAPEAVGameData@@PEAVGameDataContainer@@@Z endp

?_DESTRUCTOR@GameDataReference@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataReference@@QEAAXXZ endp

; GameDataReference::~GameDataReference();
??1GameDataReference@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataReference_base+4*8]
??1GameDataReference@@QEAA@XZ endp

; GameDataReference::operator=(const class GameDataReference &);
??4GameDataReference@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_GameDataReference_base+5*8]
??4GameDataReference@@QEAAAEAV0@AEBV0@@Z endp
