
?_CONSTRUCTOR@VideoRenderer@GameLauncher@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@VideoRenderer@GameLauncher@@QEAAPEAV12@AEBV12@@Z endp

; GameLauncher::VideoRenderer::VideoRenderer(const class GameLauncher::VideoRenderer &);
??0VideoRenderer@GameLauncher@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+0*8]
??0VideoRenderer@GameLauncher@@QEAA@AEBV01@@Z endp

; symbol is too long
; ??0VideoRenderer@GameLauncher@@QEAA@PEAVRenderSystem@Ogre@@AEAV?$unordered_map@HV?$set@U?$pair@HH@std@@U?$less@U?$pair@HH@std@@@2@V?$STLAllocator@U?$pair@HH@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@U?$hash@H@boost@@U?$equal_to@H@2@V?$STLAllocator@U?$pair@$$CBHV?$set@U?$pair@HH@std@@U?$less@U?$pair@HH@std@@@2@V?$STLAllocator@U?$pair@HH@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z
; GameLauncher::VideoRenderer::VideoRenderer(class Ogre::RenderSystem *, class boost::unordered::unordered_map<int,std::set<std::pair<int,int>,std::less<std::pair<int,int> >,Ogre::STLAllocator<std::pair<int,int>,Ogre::CategorisedAllocPolicy<0> > >,boost::hash<int>,std::equal_to<int>,Ogre::STLAllocator<std::pair<int const ,std::set<std::pair<int,int>,std::less<std::pair<int,int> >,Ogre::STLAllocator<std::pair<int,int>,Ogre::CategorisedAllocPolicy<0> > > >,Ogre::CategorisedAllocPolicy<0> > > &);
GameLauncher_VideoRenderer_VideoRenderer_PLACEHOLDER proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+1*8]
GameLauncher_VideoRenderer_VideoRenderer_PLACEHOLDER endp

; symbol is too long
; ?init@VideoRenderer@GameLauncher@@QEAAXAEAV?$unordered_map@HV?$set@U?$pair@HH@std@@U?$less@U?$pair@HH@std@@@2@V?$STLAllocator@U?$pair@HH@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@U?$hash@H@boost@@U?$equal_to@H@2@V?$STLAllocator@U?$pair@$$CBHV?$set@U?$pair@HH@std@@U?$less@U?$pair@HH@std@@@2@V?$STLAllocator@U?$pair@HH@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z
; GameLauncher::VideoRenderer::init(class boost::unordered::unordered_map<int,std::set<std::pair<int,int>,std::less<std::pair<int,int> >,Ogre::STLAllocator<std::pair<int,int>,Ogre::CategorisedAllocPolicy<0> > >,boost::hash<int>,std::equal_to<int>,Ogre::STLAllocator<std::pair<int const ,std::set<std::pair<int,int>,std::less<std::pair<int,int> >,Ogre::STLAllocator<std::pair<int,int>,Ogre::CategorisedAllocPolicy<0> > > >,Ogre::CategorisedAllocPolicy<0> > > &);
GameLauncher_VideoRenderer_init_PLACEHOLDER proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+2*8]
GameLauncher_VideoRenderer_init_PLACEHOLDER endp

; GameLauncher::VideoRenderer::apply();
?apply@VideoRenderer@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+3*8]
?apply@VideoRenderer@GameLauncher@@QEAAXXZ endp

; symbol is too long
; ?getResolutionsList@VideoRenderer@GameLauncher@@QEAAXAEAV?$vector@V?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@V?$STLAllocator@V?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAH@Z
; GameLauncher::VideoRenderer::getResolutionsList(class std::vector<ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > >,Ogre::STLAllocator<ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > >,Ogre::CategorisedAllocPolicy<0> > > &, int &);
GameLauncher_VideoRenderer_getResolutionsList_PLACEHOLDER proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+4*8]
GameLauncher_VideoRenderer_getResolutionsList_PLACEHOLDER endp

; symbol is too long
; ?getDevicesList@VideoRenderer@GameLauncher@@QEAAXAEAV?$vector@V?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@V?$STLAllocator@V?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAH@Z
; GameLauncher::VideoRenderer::getDevicesList(class std::vector<ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > >,Ogre::STLAllocator<ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > >,Ogre::CategorisedAllocPolicy<0> > > &, int &);
GameLauncher_VideoRenderer_getDevicesList_PLACEHOLDER proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+5*8]
GameLauncher_VideoRenderer_getDevicesList_PLACEHOLDER endp

; symbol is too long
; ?getMonitorsList@VideoRenderer@GameLauncher@@QEAAXAEAV?$vector@V?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@V?$STLAllocator@V?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@AEAH@Z
; GameLauncher::VideoRenderer::getMonitorsList(class std::vector<ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > >,Ogre::STLAllocator<ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > >,Ogre::CategorisedAllocPolicy<0> > > &, int &);
GameLauncher_VideoRenderer_getMonitorsList_PLACEHOLDER proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+6*8]
GameLauncher_VideoRenderer_getMonitorsList_PLACEHOLDER endp

; GameLauncher::VideoRenderer::setResolution(const class ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > > &);
?setResolution@VideoRenderer@GameLauncher@@QEAAXAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+7*8]
?setResolution@VideoRenderer@GameLauncher@@QEAAXAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z endp

; GameLauncher::VideoRenderer::setRenderingDevice(const class ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > > &);
?setRenderingDevice@VideoRenderer@GameLauncher@@QEAAXAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+8*8]
?setRenderingDevice@VideoRenderer@GameLauncher@@QEAAXAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z endp

; GameLauncher::VideoRenderer::setMonitor(const class ATL::CStringT<wchar_t,StrTraitMFC_DLL<wchar_t,ATL::ChTraitsCRT<wchar_t> > > &);
?setMonitor@VideoRenderer@GameLauncher@@QEAAXAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+9*8]
?setMonitor@VideoRenderer@GameLauncher@@QEAAXAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z endp

; GameLauncher::VideoRenderer::getIsValidResolution(const class GameLauncher::VideoDevice &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int &, int &, int &);
?getIsValidResolution@VideoRenderer@GameLauncher@@QEAA_NAEBVVideoDevice@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAH22@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+10*8]
?getIsValidResolution@VideoRenderer@GameLauncher@@QEAA_NAEBVVideoDevice@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAH22@Z endp

; GameLauncher::VideoRenderer::getResolutionDisplay(const struct std::pair<int,int> &);
?getResolutionDisplay@VideoRenderer@GameLauncher@@QEAA?AV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@AEBU?$pair@HH@std@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+11*8]
?getResolutionDisplay@VideoRenderer@GameLauncher@@QEAA?AV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@AEBU?$pair@HH@std@@@Z endp

; GameLauncher::VideoRenderer::getVideoModeString(const struct std::pair<int,int> &);
?getVideoModeString@VideoRenderer@GameLauncher@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBU?$pair@HH@4@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+12*8]
?getVideoModeString@VideoRenderer@GameLauncher@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBU?$pair@HH@4@@Z endp

?_DESTRUCTOR@VideoRenderer@GameLauncher@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@VideoRenderer@GameLauncher@@QEAAXXZ endp

; GameLauncher::VideoRenderer::~VideoRenderer();
??1VideoRenderer@GameLauncher@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+13*8]
??1VideoRenderer@GameLauncher@@QEAA@XZ endp

; GameLauncher::VideoRenderer::operator=(const class GameLauncher::VideoRenderer &);
??4VideoRenderer@GameLauncher@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameLauncher_VideoRenderer_base+14*8]
??4VideoRenderer@GameLauncher@@QEAAAEAV01@AEBV01@@Z endp
