
?_CONSTRUCTOR@TabMods@GameLauncher@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TabMods@GameLauncher@@QEAAPEAV12@XZ endp

; GameLauncher::TabMods::TabMods();
??0TabMods@GameLauncher@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+0*8]
??0TabMods@GameLauncher@@QEAA@XZ endp

?_NV_DoDataExchange@TabMods@GameLauncher@@QEAAXPEAVCDataExchange@@@Z proc EXPORT
?_NV_DoDataExchange@TabMods@GameLauncher@@QEAAXPEAVCDataExchange@@@Z endp

; GameLauncher::TabMods::DoDataExchange(class CDataExchange *);
?DoDataExchange@TabMods@GameLauncher@@UEAAXPEAVCDataExchange@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+1*8]
?DoDataExchange@TabMods@GameLauncher@@UEAAXPEAVCDataExchange@@@Z endp

?_NV_OnInitDialog@TabMods@GameLauncher@@QEAAHXZ proc EXPORT
?_NV_OnInitDialog@TabMods@GameLauncher@@QEAAHXZ endp

; GameLauncher::TabMods::OnInitDialog();
?OnInitDialog@TabMods@GameLauncher@@UEAAHXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+2*8]
?OnInitDialog@TabMods@GameLauncher@@UEAAHXZ endp

; GameLauncher::TabMods::validModList();
?validModList@TabMods@GameLauncher@@QEBA_NXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+3*8]
?validModList@TabMods@GameLauncher@@QEBA_NXZ endp

; GameLauncher::TabMods::loadMods();
?loadMods@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+4*8]
?loadMods@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::saveMods();
?saveMods@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+5*8]
?saveMods@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::arrangeMods();
?arrangeMods@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+6*8]
?arrangeMods@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::updateModsList(bool);
?updateModsList@TabMods@GameLauncher@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+7*8]
?updateModsList@TabMods@GameLauncher@@QEAAX_N@Z endp

; GameLauncher::TabMods::GetThisMessageMap();
?GetThisMessageMap@TabMods@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+8*8]
?GetThisMessageMap@TabMods@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ endp

?_NV_GetMessageMap@TabMods@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
?_NV_GetMessageMap@TabMods@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::TabMods::GetMessageMap();
?GetMessageMap@TabMods@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+9*8]
?GetMessageMap@TabMods@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::TabMods::OnBnClickedLauncherBtnModsSelectNone();
?OnBnClickedLauncherBtnModsSelectNone@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+10*8]
?OnBnClickedLauncherBtnModsSelectNone@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::OnBnClickedLauncherBtnModsSelectAll();
?OnBnClickedLauncherBtnModsSelectAll@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+11*8]
?OnBnClickedLauncherBtnModsSelectAll@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::OnBnClickedLauncherBtnModsReload();
?OnBnClickedLauncherBtnModsReload@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+12*8]
?OnBnClickedLauncherBtnModsReload@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::OnBnClickedLauncherBtnModsUp();
?OnBnClickedLauncherBtnModsUp@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+13*8]
?OnBnClickedLauncherBtnModsUp@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::OnBnClickedLauncherBtnModsDown();
?OnBnClickedLauncherBtnModsDown@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+14*8]
?OnBnClickedLauncherBtnModsDown@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::OnBnClickedLauncherBtnModsInfo();
?OnBnClickedLauncherBtnModsInfo@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+15*8]
?OnBnClickedLauncherBtnModsInfo@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::OnCheckListChange();
?OnCheckListChange@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+16*8]
?OnCheckListChange@TabMods@GameLauncher@@QEAAXXZ endp

?_DESTRUCTOR@TabMods@GameLauncher@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TabMods@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabMods::~TabMods();
??1TabMods@GameLauncher@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabMods_base+17*8]
??1TabMods@GameLauncher@@UEAA@XZ endp
