
?_CONSTRUCTOR@GameDataCopyStandalone@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataCopyStandalone@@QEAAPEAV1@XZ endp

; GameDataCopyStandalone::GameDataCopyStandalone();
??0GameDataCopyStandalone@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataCopyStandalone_base+0*8]
??0GameDataCopyStandalone@@QEAA@XZ endp

?_DESTRUCTOR@GameDataCopyStandalone@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataCopyStandalone@@QEAAXXZ endp

; GameDataCopyStandalone::~GameDataCopyStandalone();
??1GameDataCopyStandalone@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameDataCopyStandalone_base+1*8]
??1GameDataCopyStandalone@@UEAA@XZ endp
