
?_CONSTRUCTOR@TabChangelog@GameLauncher@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TabChangelog@GameLauncher@@QEAAPEAV12@XZ endp

; GameLauncher::TabChangelog::TabChangelog();
??0TabChangelog@GameLauncher@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+0*8]
??0TabChangelog@GameLauncher@@QEAA@XZ endp

?_NV_DoDataExchange@TabChangelog@GameLauncher@@QEAAXPEAVCDataExchange@@@Z proc EXPORT
?_NV_DoDataExchange@TabChangelog@GameLauncher@@QEAAXPEAVCDataExchange@@@Z endp

; GameLauncher::TabChangelog::DoDataExchange(class CDataExchange *);
?DoDataExchange@TabChangelog@GameLauncher@@UEAAXPEAVCDataExchange@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+1*8]
?DoDataExchange@TabChangelog@GameLauncher@@UEAAXPEAVCDataExchange@@@Z endp

?_NV_OnInitDialog@TabChangelog@GameLauncher@@QEAAHXZ proc EXPORT
?_NV_OnInitDialog@TabChangelog@GameLauncher@@QEAAHXZ endp

; GameLauncher::TabChangelog::OnInitDialog();
?OnInitDialog@TabChangelog@GameLauncher@@UEAAHXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+2*8]
?OnInitDialog@TabChangelog@GameLauncher@@UEAAHXZ endp

?_NV_setVisible@TabChangelog@GameLauncher@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@TabChangelog@GameLauncher@@QEAAX_N@Z endp

; GameLauncher::TabChangelog::setVisible(bool);
?setVisible@TabChangelog@GameLauncher@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+3*8]
?setVisible@TabChangelog@GameLauncher@@UEAAX_N@Z endp

; GameLauncher::TabChangelog::loadChangelog();
?loadChangelog@TabChangelog@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+4*8]
?loadChangelog@TabChangelog@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabChangelog::GetThisMessageMap();
?GetThisMessageMap@TabChangelog@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+5*8]
?GetThisMessageMap@TabChangelog@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ endp

?_NV_GetMessageMap@TabChangelog@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
?_NV_GetMessageMap@TabChangelog@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::TabChangelog::GetMessageMap();
?GetMessageMap@TabChangelog@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+6*8]
?GetMessageMap@TabChangelog@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ endp

?_DESTRUCTOR@TabChangelog@GameLauncher@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TabChangelog@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabChangelog::~TabChangelog();
??1TabChangelog@GameLauncher@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabChangelog_base+7*8]
??1TabChangelog@GameLauncher@@UEAA@XZ endp
