
?_CONSTRUCTOR@ObjectInstance@GameData@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@ObjectInstance@GameData@@QEAAPEAV12@AEBV12@@Z endp

; GameData::ObjectInstance::ObjectInstance(const class GameData::ObjectInstance &);
??0ObjectInstance@GameData@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameData_ObjectInstance_base+0*8]
??0ObjectInstance@GameData@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@ObjectInstance@GameData@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ObjectInstance@GameData@@QEAAPEAV12@XZ endp

; GameData::ObjectInstance::ObjectInstance();
??0ObjectInstance@GameData@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameData_ObjectInstance_base+1*8]
??0ObjectInstance@GameData@@QEAA@XZ endp

; GameData::ObjectInstance::operator=(const class GameData::ObjectInstance &);
??4ObjectInstance@GameData@@QEAAAEBV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameData_ObjectInstance_base+2*8]
??4ObjectInstance@GameData@@QEAAAEBV01@AEBV01@@Z endp

; symbol is too long
; ?updateInstancedObjectAttachedDatas@ObjectInstance@GameData@@QEAAXAEBV?$unordered_map@W4itemType@@PEAVGameData@@U?$hash@W4itemType@@@boost@@U?$equal_to@W4itemType@@@std@@V?$STLAllocator@U?$pair@$$CBW4itemType@@PEAVGameData@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@@Z
; GameData::ObjectInstance::updateInstancedObjectAttachedDatas(const class boost::unordered::unordered_map<enum itemType,GameData *,boost::hash<enum itemType>,std::equal_to<enum itemType>,Ogre::STLAllocator<std::pair<enum itemType const ,GameData *>,Ogre::CategorisedAllocPolicy<0> > > &);
GameData_ObjectInstance_updateInstancedObjectAttachedDatas_PLACEHOLDER proc EXPORT
jmp function_pointers[_GameData_ObjectInstance_base+3*8]
GameData_ObjectInstance_updateInstancedObjectAttachedDatas_PLACEHOLDER endp

?_DESTRUCTOR@ObjectInstance@GameData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ObjectInstance@GameData@@QEAAXXZ endp

; GameData::ObjectInstance::~ObjectInstance();
??1ObjectInstance@GameData@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameData_ObjectInstance_base+4*8]
??1ObjectInstance@GameData@@QEAA@XZ endp
