
?_CONSTRUCTOR@SysMessage@GameWorld@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@SysMessage@GameWorld@@QEAAPEAV12@AEBV12@@Z endp

; GameWorld::SysMessage::SysMessage(const class GameWorld::SysMessage &);
??0SysMessage@GameWorld@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_GameWorld_SysMessage_base+0*8]
??0SysMessage@GameWorld@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@SysMessage@GameWorld@@QEAAPEAV12@W4SysMessageEnum@2@AEBVhand@@1_NMPEAX@Z proc EXPORT
?_CONSTRUCTOR@SysMessage@GameWorld@@QEAAPEAV12@W4SysMessageEnum@2@AEBVhand@@1_NMPEAX@Z endp

; GameWorld::SysMessage::SysMessage(enum GameWorld::SysMessageEnum, const class hand &, const class hand &, bool, float, void *);
??0SysMessage@GameWorld@@QEAA@W4SysMessageEnum@1@AEBVhand@@1_NMPEAX@Z proc EXPORT
jmp function_pointers[_GameWorld_SysMessage_base+1*8]
??0SysMessage@GameWorld@@QEAA@W4SysMessageEnum@1@AEBVhand@@1_NMPEAX@Z endp

; GameWorld::SysMessage::operator==(const class GameWorld::SysMessage &);
??8SysMessage@GameWorld@@QEBA_NAEBV01@@Z proc EXPORT
jmp function_pointers[_GameWorld_SysMessage_base+2*8]
??8SysMessage@GameWorld@@QEBA_NAEBV01@@Z endp
