
?_CONSTRUCTOR@TabVideo@GameLauncher@@QEAAPEAV12@PEAVRoot@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@TabVideo@GameLauncher@@QEAAPEAV12@PEAVRoot@Ogre@@@Z endp

; GameLauncher::TabVideo::TabVideo(class Ogre::Root *);
??0TabVideo@GameLauncher@@QEAA@PEAVRoot@Ogre@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+0*8]
??0TabVideo@GameLauncher@@QEAA@PEAVRoot@Ogre@@@Z endp

?_NV_DoDataExchange@TabVideo@GameLauncher@@QEAAXPEAVCDataExchange@@@Z proc EXPORT
?_NV_DoDataExchange@TabVideo@GameLauncher@@QEAAXPEAVCDataExchange@@@Z endp

; GameLauncher::TabVideo::DoDataExchange(class CDataExchange *);
?DoDataExchange@TabVideo@GameLauncher@@UEAAXPEAVCDataExchange@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+1*8]
?DoDataExchange@TabVideo@GameLauncher@@UEAAXPEAVCDataExchange@@@Z endp

?_NV_OnInitDialog@TabVideo@GameLauncher@@QEAAHXZ proc EXPORT
?_NV_OnInitDialog@TabVideo@GameLauncher@@QEAAHXZ endp

; GameLauncher::TabVideo::OnInitDialog();
?OnInitDialog@TabVideo@GameLauncher@@UEAAHXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+2*8]
?OnInitDialog@TabVideo@GameLauncher@@UEAAHXZ endp

?_NV_PreTranslateMessage@TabVideo@GameLauncher@@QEAAHPEAUtagMSG@@@Z proc EXPORT
?_NV_PreTranslateMessage@TabVideo@GameLauncher@@QEAAHPEAUtagMSG@@@Z endp

; GameLauncher::TabVideo::PreTranslateMessage(struct tagMSG *);
?PreTranslateMessage@TabVideo@GameLauncher@@UEAAHPEAUtagMSG@@@Z proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+3*8]
?PreTranslateMessage@TabVideo@GameLauncher@@UEAAHPEAUtagMSG@@@Z endp

; GameLauncher::TabVideo::setupRenderers();
?setupRenderers@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+4*8]
?setupRenderers@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::updateRendererSettings();
?updateRendererSettings@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+5*8]
?updateRendererSettings@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::updateResolutions();
?updateResolutions@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+6*8]
?updateResolutions@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::GetThisMessageMap();
?GetThisMessageMap@TabVideo@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+7*8]
?GetThisMessageMap@TabVideo@GameLauncher@@SAPEBUAFX_MSGMAP@@XZ endp

?_NV_GetMessageMap@TabVideo@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
?_NV_GetMessageMap@TabVideo@GameLauncher@@QEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::TabVideo::GetMessageMap();
?GetMessageMap@TabVideo@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+8*8]
?GetMessageMap@TabVideo@GameLauncher@@UEBAPEBUAFX_MSGMAP@@XZ endp

; GameLauncher::TabVideo::OnCbnSelchangeLauncherComboRenderer();
?OnCbnSelchangeLauncherComboRenderer@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+9*8]
?OnCbnSelchangeLauncherComboRenderer@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnCbnSelchangeLauncherComboResolution();
?OnCbnSelchangeLauncherComboResolution@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+10*8]
?OnCbnSelchangeLauncherComboResolution@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnCbnSelchangeLauncherComboDevices();
?OnCbnSelchangeLauncherComboDevices@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+11*8]
?OnCbnSelchangeLauncherComboDevices@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnCbnSelchangeLauncherComboMonitors();
?OnCbnSelchangeLauncherComboMonitors@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+12*8]
?OnCbnSelchangeLauncherComboMonitors@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnBnClickedLauncherCheckFullscreen();
?OnBnClickedLauncherCheckFullscreen@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+13*8]
?OnBnClickedLauncherCheckFullscreen@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnBnClickedLauncherCheckBorderless();
?OnBnClickedLauncherCheckBorderless@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+14*8]
?OnBnClickedLauncherCheckBorderless@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnBnClickedLauncherCheckVSync();
?OnBnClickedLauncherCheckVSync@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+15*8]
?OnBnClickedLauncherCheckVSync@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::OnBnClickedLauncherVideoInfo();
?OnBnClickedLauncherVideoInfo@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+16*8]
?OnBnClickedLauncherVideoInfo@TabVideo@GameLauncher@@QEAAXXZ endp

?_DESTRUCTOR@TabVideo@GameLauncher@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TabVideo@GameLauncher@@QEAAXXZ endp

; GameLauncher::TabVideo::~TabVideo();
??1TabVideo@GameLauncher@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameLauncher_TabVideo_base+17*8]
??1TabVideo@GameLauncher@@UEAA@XZ endp
