
?_CONSTRUCTOR@GameplayOptions@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameplayOptions@@QEAAPEAV1@XZ endp

; GameplayOptions::GameplayOptions();
??0GameplayOptions@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameplayOptions_base+0*8]
??0GameplayOptions@@QEAA@XZ endp

; GameplayOptions::reset();
?reset@GameplayOptions@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameplayOptions_base+1*8]
?reset@GameplayOptions@@QEAAXXZ endp

; GameplayOptions::getStarvationTimeInHours();
?getStarvationTimeInHours@GameplayOptions@@QEAAMXZ proc EXPORT
jmp function_pointers[_GameplayOptions_base+2*8]
?getStarvationTimeInHours@GameplayOptions@@QEAAMXZ endp

; GameplayOptions::save(class GameData *);
?save@GameplayOptions@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameplayOptions_base+3*8]
?save@GameplayOptions@@QEAAXPEAVGameData@@@Z endp

; GameplayOptions::load(class GameData *);
?load@GameplayOptions@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameplayOptions_base+4*8]
?load@GameplayOptions@@QEAAXPEAVGameData@@@Z endp
