
; GameDataContainer::addNewData(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addNewData@GameDataContainer@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+0*8]
?addNewData@GameDataContainer@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameDataContainer::addNewData(const class lektor<GameData *> &);
?addNewData@GameDataContainer@@QEAAXAEBV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+1*8]
?addNewData@GameDataContainer@@QEAAXAEBV?$lektor@PEAVGameData@@@@@Z endp

?_CONSTRUCTOR@GameDataContainer@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataContainer@@QEAAPEAV1@XZ endp

; GameDataContainer::GameDataContainer();
??0GameDataContainer@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+2*8]
??0GameDataContainer@@QEAA@XZ endp

?_DESTRUCTOR@GameDataContainer@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::~GameDataContainer();
??1GameDataContainer@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+3*8]
??1GameDataContainer@@UEAA@XZ endp

; GameDataContainer::createNewData(enum itemType, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createNewData@GameDataContainer@@QEAAPEAVGameData@@W4itemType@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+4*8]
?createNewData@GameDataContainer@@QEAAPEAVGameData@@W4itemType@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; GameDataContainer::getData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getData@GameDataContainer@@QEAAPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+5*8]
?getData@GameDataContainer@@QEAAPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameDataContainer::getData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum itemType);
?getData@GameDataContainer@@QEAAPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+6*8]
?getData@GameDataContainer@@QEAAPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@@Z endp

; GameDataContainer::getData(int);
?getData@GameDataContainer@@QEAAPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+7*8]
?getData@GameDataContainer@@QEAAPEAVGameData@@H@Z endp

; GameDataContainer::getDataByName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum itemType);
?getDataByName@GameDataContainer@@QEAAPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+8*8]
?getDataByName@GameDataContainer@@QEAAPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@@Z endp

; GameDataContainer::getDataOfType(class lektor<GameData *> &, enum itemType);
?getDataOfType@GameDataContainer@@QEAAXAEAV?$lektor@PEAVGameData@@@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+9*8]
?getDataOfType@GameDataContainer@@QEAAXAEAV?$lektor@PEAVGameData@@@@W4itemType@@@Z endp

; GameDataContainer::_getAllData();
?_getAllData@GameDataContainer@@QEBAAEBV?$unordered_map@HPEAVGameData@@U?$hash@H@boost@@U?$equal_to@H@std@@V?$STLAllocator@U?$pair@$$CBHPEAVGameData@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+10*8]
?_getAllData@GameDataContainer@@QEBAAEBV?$unordered_map@HPEAVGameData@@U?$hash@H@boost@@U?$equal_to@H@std@@V?$STLAllocator@U?$pair@$$CBHPEAVGameData@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ endp

; GameDataContainer::renameData(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?renameData@GameDataContainer@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+11*8]
?renameData@GameDataContainer@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameDataContainer::removeData(class GameData *);
?removeData@GameDataContainer@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+12*8]
?removeData@GameDataContainer@@QEAAXPEAVGameData@@@Z endp

; GameDataContainer::removeDuplicatesOf(class GameData *);
?removeDuplicatesOf@GameDataContainer@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+13*8]
?removeDuplicatesOf@GameDataContainer@@QEAAXPEAVGameData@@@Z endp

; GameDataContainer::removeAllDataOfType(enum itemType);
?removeAllDataOfType@GameDataContainer@@QEAAXW4itemType@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+14*8]
?removeAllDataOfType@GameDataContainer@@QEAAXW4itemType@@@Z endp

; GameDataContainer::loadGameDataReturn(class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, bool, bool, class Serialisable *);
?loadGameDataReturn@GameDataContainer@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N1PEAVSerialisable@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+15*8]
?loadGameDataReturn@GameDataContainer@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N1PEAVSerialisable@@@Z endp

; GameDataContainer::load(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, class Serialisable *, bool);
?load@GameDataContainer@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HPEAVSerialisable@@_N@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+16*8]
?load@GameDataContainer@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0HPEAVSerialisable@@_N@Z endp

; GameDataContainer::save(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Serialisable *);
?save@GameDataContainer@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVSerialisable@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+17*8]
?save@GameDataContainer@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVSerialisable@@@Z endp

; GameDataContainer::clearInstances();
?clearInstances@GameDataContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+18*8]
?clearInstances@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::clearButDontDestroy();
?clearButDontDestroy@GameDataContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+19*8]
?clearButDontDestroy@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::clearButDontDestroyPlatoons();
?clearButDontDestroyPlatoons@GameDataContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+20*8]
?clearButDontDestroyPlatoons@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::clearAndDestroy();
?clearAndDestroy@GameDataContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+21*8]
?clearAndDestroy@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::getNewID();
?getNewID@GameDataContainer@@QEAAHXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+22*8]
?getNewID@GameDataContainer@@QEAAHXZ endp

; GameDataContainer::flushKillList();
?flushKillList@GameDataContainer@@SAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+23*8]
?flushKillList@GameDataContainer@@SAXXZ endp

; GameDataContainer::destroyHomelessData(class GameData *);
?destroyHomelessData@GameDataContainer@@SAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+24*8]
?destroyHomelessData@GameDataContainer@@SAXPEAVGameData@@@Z endp

; GameDataContainer::destroyData(class GameData *);
?destroyData@GameDataContainer@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+25*8]
?destroyData@GameDataContainer@@QEAAXPEAVGameData@@@Z endp

; GameDataContainer::preLoadAllReferencePtrs();
?preLoadAllReferencePtrs@GameDataContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+26*8]
?preLoadAllReferencePtrs@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::clearAllReferencePtrs();
?clearAllReferencePtrs@GameDataContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataContainer_base+27*8]
?clearAllReferencePtrs@GameDataContainer@@QEAAXXZ endp

; GameDataContainer::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@GameDataContainer@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+28*8]
?setName@GameDataContainer@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameDataContainer::findAllDataThatReferencesThis(class lektor<GameData *> &, class GameData *, enum itemType, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?findAllDataThatReferencesThis@GameDataContainer@@QEAAXAEAV?$lektor@PEAVGameData@@@@PEAVGameData@@W4itemType@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+29*8]
?findAllDataThatReferencesThis@GameDataContainer@@QEAAXAEAV?$lektor@PEAVGameData@@@@PEAVGameData@@W4itemType@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameDataContainer::checkForDuplicates(class GameData *);
?checkForDuplicates@GameDataContainer@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+30*8]
?checkForDuplicates@GameDataContainer@@QEAAXPEAVGameData@@@Z endp

; GameDataContainer::_addToKillList(class GameData *);
?_addToKillList@GameDataContainer@@SAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_GameDataContainer_base+31*8]
?_addToKillList@GameDataContainer@@SAXPEAVGameData@@@Z endp
