
?_CONSTRUCTOR@GameDataHeader@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@GameDataHeader@@QEAAPEAV1@AEBV1@@Z endp

; GameDataHeader::GameDataHeader(const class GameDataHeader &);
??0GameDataHeader@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_GameDataHeader_base+0*8]
??0GameDataHeader@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@GameDataHeader@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
?_CONSTRUCTOR@GameDataHeader@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; GameDataHeader::GameDataHeader(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0GameDataHeader@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_GameDataHeader_base+1*8]
??0GameDataHeader@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

?_CONSTRUCTOR@GameDataHeader@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataHeader@@QEAAPEAV1@XZ endp

; GameDataHeader::GameDataHeader();
??0GameDataHeader@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataHeader_base+2*8]
??0GameDataHeader@@QEAA@XZ endp

?_DESTRUCTOR@GameDataHeader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataHeader@@QEAAXXZ endp

; GameDataHeader::~GameDataHeader();
??1GameDataHeader@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataHeader_base+3*8]
??1GameDataHeader@@QEAA@XZ endp

; GameDataHeader::operator=(const class GameDataHeader &);
??4GameDataHeader@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_GameDataHeader_base+4*8]
??4GameDataHeader@@QEAAAEAV0@AEBV0@@Z endp
