
?_CONSTRUCTOR@GameDataManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GameDataManager@@QEAAPEAV1@XZ endp

; GameDataManager::GameDataManager();
??0GameDataManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_GameDataManager_base+0*8]
??0GameDataManager@@QEAA@XZ endp

; GameDataManager::reloadGameData(class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, bool, bool);
?reloadGameData@GameDataManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N1@Z proc EXPORT
jmp function_pointers[_GameDataManager_base+1*8]
?reloadGameData@GameDataManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N1@Z endp

; GameDataManager::postProcessingTheDatas();
?postProcessingTheDatas@GameDataManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_GameDataManager_base+2*8]
?postProcessingTheDatas@GameDataManager@@QEAAXXZ endp

; GameDataManager::getBuildings(class lektor<GameData *> &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getBuildings@GameDataManager@@QEAAXAEAV?$lektor@PEAVGameData@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GameDataManager_base+3*8]
?getBuildings@GameDataManager@@QEAAXAEAV?$lektor@PEAVGameData@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GameDataManager::getMapSector(int, int);
?getMapSector@GameDataManager@@QEAAPEAVGameData@@HH@Z proc EXPORT
jmp function_pointers[_GameDataManager_base+4*8]
?getMapSector@GameDataManager@@QEAAPEAVGameData@@HH@Z endp

; GameDataManager::updateDatasOfType(class GameDataContainer *, enum itemType, bool);
?updateDatasOfType@GameDataManager@@QEAAXPEAVGameDataContainer@@W4itemType@@_N@Z proc EXPORT
jmp function_pointers[_GameDataManager_base+5*8]
?updateDatasOfType@GameDataManager@@QEAAXPEAVGameDataContainer@@W4itemType@@_N@Z endp

; GameDataManager::updateData(class GameData *, bool);
?updateData@GameDataManager@@QEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_GameDataManager_base+6*8]
?updateData@GameDataManager@@QEAAXPEAVGameData@@_N@Z endp

?_DESTRUCTOR@GameDataManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GameDataManager@@QEAAXXZ endp

; GameDataManager::~GameDataManager();
??1GameDataManager@@UEAA@XZ proc EXPORT
jmp function_pointers[_GameDataManager_base+7*8]
??1GameDataManager@@UEAA@XZ endp
