
?_DESTRUCTOR@GatewayBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GatewayBuilding@@QEAAXXZ endp

; GatewayBuilding::~GatewayBuilding();
??1GatewayBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+0*8]
??1GatewayBuilding@@UEAA@XZ endp

?_CONSTRUCTOR@GatewayBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4@Z proc EXPORT
?_CONSTRUCTOR@GatewayBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4@Z endp

; GatewayBuilding::GatewayBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &);
??0GatewayBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4@Z proc EXPORT
jmp function_pointers[_GatewayBuilding_base+1*8]
??0GatewayBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4@Z endp

; GatewayBuilding::reAnnounceGateToPathfinder();
?reAnnounceGateToPathfinder@GatewayBuilding@@QEAAXXZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+2*8]
?reAnnounceGateToPathfinder@GatewayBuilding@@QEAAXXZ endp

?_NV_postCreationPathfinderSetupStuff@GatewayBuilding@@QEAAXXZ proc EXPORT
?_NV_postCreationPathfinderSetupStuff@GatewayBuilding@@QEAAXXZ endp

; GatewayBuilding::postCreationPathfinderSetupStuff();
?postCreationPathfinderSetupStuff@GatewayBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+3*8]
?postCreationPathfinderSetupStuff@GatewayBuilding@@UEAAXXZ endp

?_NV_setHandle@GatewayBuilding@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@GatewayBuilding@@QEAAXAEBVhand@@@Z endp

; GatewayBuilding::setHandle(const class hand &);
?setHandle@GatewayBuilding@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GatewayBuilding_base+4*8]
?setHandle@GatewayBuilding@@UEAAXAEBVhand@@@Z endp

?_NV_getPositionForWaypoint@GatewayBuilding@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getPositionForWaypoint@GatewayBuilding@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; GatewayBuilding::getPositionForWaypoint(const class Ogre::Vector3 &);
?getPositionForWaypoint@GatewayBuilding@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_GatewayBuilding_base+5*8]
?getPositionForWaypoint@GatewayBuilding@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_getUseableStuff@GatewayBuilding@@QEAAPEAVUseableStuff@@XZ proc EXPORT
?_NV_getUseableStuff@GatewayBuilding@@QEAAPEAVUseableStuff@@XZ endp

; GatewayBuilding::getUseableStuff();
?getUseableStuff@GatewayBuilding@@UEAAPEAVUseableStuff@@XZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+6*8]
?getUseableStuff@GatewayBuilding@@UEAAPEAVUseableStuff@@XZ endp

?_NV_isGate@GatewayBuilding@@QEAAPEAV1@XZ proc EXPORT
?_NV_isGate@GatewayBuilding@@QEAAPEAV1@XZ endp

; GatewayBuilding::isGate();
?isGate@GatewayBuilding@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+7*8]
?isGate@GatewayBuilding@@UEAAPEAV1@XZ endp

?_NV_isForSale@GatewayBuilding@@QEAA_NXZ proc EXPORT
?_NV_isForSale@GatewayBuilding@@QEAA_NXZ endp

; GatewayBuilding::isForSale();
?isForSale@GatewayBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+8*8]
?isForSale@GatewayBuilding@@UEAA_NXZ endp

?_NV_setup@GatewayBuilding@@QEAAXXZ proc EXPORT
?_NV_setup@GatewayBuilding@@QEAAXXZ endp

; GatewayBuilding::setup();
?setup@GatewayBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+9*8]
?setup@GatewayBuilding@@UEAAXXZ endp

; GatewayBuilding::getGateCodeAt(const class Ogre::Vector3 &);
?getGateCodeAt@GatewayBuilding@@QEAAHAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_GatewayBuilding_base+10*8]
?getGateCodeAt@GatewayBuilding@@QEAAHAEBVVector3@Ogre@@@Z endp

; GatewayBuilding::getOutsideGateCode();
?getOutsideGateCode@GatewayBuilding@@QEAAHXZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+11*8]
?getOutsideGateCode@GatewayBuilding@@QEAAHXZ endp

; GatewayBuilding::separatesAreas();
?separatesAreas@GatewayBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_GatewayBuilding_base+12*8]
?separatesAreas@GatewayBuilding@@QEAA_NXZ endp
