
?_CONSTRUCTOR@Gear@@QEAAPEAV1@PEAVGameData@@00Vhand@@HPEAVFaction@@@Z proc EXPORT
?_CONSTRUCTOR@Gear@@QEAAPEAV1@PEAVGameData@@00Vhand@@HPEAVFaction@@@Z endp

; Gear::Gear(class GameData *, class GameData *, class GameData *, class hand, int, class Faction *);
??0Gear@@QEAA@PEAVGameData@@00Vhand@@HPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_Gear_base+0*8]
??0Gear@@QEAA@PEAVGameData@@00Vhand@@HPEAVFaction@@@Z endp

?_NV_isGear@Gear@@QEAAPEAV1@XZ proc EXPORT
?_NV_isGear@Gear@@QEAAPEAV1@XZ endp

; Gear::isGear();
?isGear@Gear@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Gear_base+1*8]
?isGear@Gear@@UEAAPEAV1@XZ endp

?_NV_getLevel01@Gear@@QEBAMXZ proc EXPORT
?_NV_getLevel01@Gear@@QEBAMXZ endp

; Gear::getLevel01();
?getLevel01@Gear@@UEBAMXZ proc EXPORT
jmp function_pointers[_Gear_base+2*8]
?getLevel01@Gear@@UEBAMXZ endp

?_NV_getLevel@Gear@@QEBAHXZ proc EXPORT
?_NV_getLevel@Gear@@QEBAHXZ endp

; Gear::getLevel();
?getLevel@Gear@@UEBAHXZ proc EXPORT
jmp function_pointers[_Gear_base+3*8]
?getLevel@Gear@@UEBAHXZ endp

?_NV_isAFactionUniform@Gear@@QEAAPEAVFaction@@XZ proc EXPORT
?_NV_isAFactionUniform@Gear@@QEAAPEAVFaction@@XZ endp

; Gear::isAFactionUniform();
?isAFactionUniform@Gear@@UEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_Gear_base+4*8]
?isAFactionUniform@Gear@@UEAAPEAVFaction@@XZ endp

?_NV__serialise@Gear@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@Gear@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; Gear::_serialise(class GameDataContainer *, enum itemType);
?_serialise@Gear@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_Gear_base+5*8]
?_serialise@Gear@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_NV__loadFromSerialise@Gear@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@Gear@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; Gear::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@Gear@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Gear_base+6*8]
?_loadFromSerialise@Gear@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_setInventoryWeAreIn@Gear@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setInventoryWeAreIn@Gear@@QEAAXAEBVhand@@@Z endp

; Gear::setInventoryWeAreIn(const class hand &);
?setInventoryWeAreIn@Gear@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Gear_base+7*8]
?setInventoryWeAreIn@Gear@@UEAAXAEBVhand@@@Z endp

; Gear::isPlayerCrafted();
?isPlayerCrafted@Gear@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Gear_base+8*8]
?isPlayerCrafted@Gear@@QEBA_NXZ endp

?_DESTRUCTOR@Gear@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Gear@@QEAAXXZ endp

; Gear::~Gear();
??1Gear@@UEAA@XZ proc EXPORT
jmp function_pointers[_Gear_base+9*8]
??1Gear@@UEAA@XZ endp
