
?_CONSTRUCTOR@GenericFixedInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GenericFixedInventoryLayout@@QEAAPEAV1@XZ endp

; GenericFixedInventoryLayout::GenericFixedInventoryLayout();
??0GenericFixedInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_GenericFixedInventoryLayout_base+0*8]
??0GenericFixedInventoryLayout@@QEAA@XZ endp

?_NV_setSize@GenericFixedInventoryLayout@@QEAAXHH@Z proc EXPORT
?_NV_setSize@GenericFixedInventoryLayout@@QEAAXHH@Z endp

; GenericFixedInventoryLayout::setSize(int, int);
?setSize@GenericFixedInventoryLayout@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_GenericFixedInventoryLayout_base+1*8]
?setSize@GenericFixedInventoryLayout@@UEAAXHH@Z endp

?_DESTRUCTOR@GenericFixedInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GenericFixedInventoryLayout@@QEAAXXZ endp

; GenericFixedInventoryLayout::~GenericFixedInventoryLayout();
??1GenericFixedInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_GenericFixedInventoryLayout_base+2*8]
??1GenericFixedInventoryLayout@@UEAA@XZ endp
