
?_CONSTRUCTOR@GeneratorBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@GeneratorBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; GeneratorBuilding::GeneratorBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0GeneratorBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_GeneratorBuilding_base+0*8]
??0GeneratorBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_NV_getPowerOutput@GeneratorBuilding@@QEBAMXZ proc EXPORT
?_NV_getPowerOutput@GeneratorBuilding@@QEBAMXZ endp

; GeneratorBuilding::getPowerOutput();
?getPowerOutput@GeneratorBuilding@@UEBAMXZ proc EXPORT
jmp function_pointers[_GeneratorBuilding_base+1*8]
?getPowerOutput@GeneratorBuilding@@UEBAMXZ endp

?_NV_getGUIState@GeneratorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@GeneratorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; GeneratorBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@GeneratorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_GeneratorBuilding_base+2*8]
?getGUIState@GeneratorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getInputValue@GeneratorBuilding@@QEAAMPEAVItem@@@Z proc EXPORT
?_NV_getInputValue@GeneratorBuilding@@QEAAMPEAVItem@@@Z endp

; GeneratorBuilding::getInputValue(class Item *);
?getInputValue@GeneratorBuilding@@UEAAMPEAVItem@@@Z proc EXPORT
jmp function_pointers[_GeneratorBuilding_base+3*8]
?getInputValue@GeneratorBuilding@@UEAAMPEAVItem@@@Z endp

?_NV_getFuelConsumptionRate@GeneratorBuilding@@QEAAMXZ proc EXPORT
?_NV_getFuelConsumptionRate@GeneratorBuilding@@QEAAMXZ endp

; GeneratorBuilding::getFuelConsumptionRate();
?getFuelConsumptionRate@GeneratorBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_GeneratorBuilding_base+4*8]
?getFuelConsumptionRate@GeneratorBuilding@@UEAAMXZ endp

?_DESTRUCTOR@GeneratorBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GeneratorBuilding@@QEAAXXZ endp

; GeneratorBuilding::~GeneratorBuilding();
??1GeneratorBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_GeneratorBuilding_base+5*8]
??1GeneratorBuilding@@UEAA@XZ endp
