
?_CONSTRUCTOR@GenericInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@GenericInventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; GenericInventoryLayout::GenericInventoryLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0GenericInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_GenericInventoryLayout_base+0*8]
??0GenericInventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@GenericInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GenericInventoryLayout@@QEAAPEAV1@XZ endp

; GenericInventoryLayout::GenericInventoryLayout();
??0GenericInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_GenericInventoryLayout_base+1*8]
??0GenericInventoryLayout@@QEAA@XZ endp

?_NV_setSize@GenericInventoryLayout@@QEAAXHH_N0@Z proc EXPORT
?_NV_setSize@GenericInventoryLayout@@QEAAXHH_N0@Z endp

; GenericInventoryLayout::setSize(int, int, bool, bool);
?setSize@GenericInventoryLayout@@UEAAXHH_N0@Z proc EXPORT
jmp function_pointers[_GenericInventoryLayout_base+2*8]
?setSize@GenericInventoryLayout@@UEAAXHH_N0@Z endp

?_DESTRUCTOR@GenericInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GenericInventoryLayout@@QEAAXXZ endp

; GenericInventoryLayout::~GenericInventoryLayout();
??1GenericInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_GenericInventoryLayout_base+3*8]
??1GenericInventoryLayout@@UEAA@XZ endp
