
?_CONSTRUCTOR@GUIWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@GUIWindow@@QEAAPEAV1@XZ endp

; GUIWindow::GUIWindow();
??0GUIWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_GUIWindow_base+0*8]
??0GUIWindow@@QEAA@XZ endp

?_DESTRUCTOR@GUIWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GUIWindow@@QEAAXXZ endp

; GUIWindow::~GUIWindow();
??1GUIWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_GUIWindow_base+1*8]
??1GUIWindow@@UEAA@XZ endp

?_NV_clear@GUIWindow@@QEAAXXZ proc EXPORT
?_NV_clear@GUIWindow@@QEAAXXZ endp

; GUIWindow::clear();
?clear@GUIWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+2*8]
?clear@GUIWindow@@UEAAXXZ endp

?_NV_setPositionReal@GUIWindow@@QEAAXMM@Z proc EXPORT
?_NV_setPositionReal@GUIWindow@@QEAAXMM@Z endp

; GUIWindow::setPositionReal(float, float);
?setPositionReal@GUIWindow@@UEAAXMM@Z proc EXPORT
jmp function_pointers[_GUIWindow_base+3*8]
?setPositionReal@GUIWindow@@UEAAXMM@Z endp

?_NV_setPosition@GUIWindow@@QEAAXHH@Z proc EXPORT
?_NV_setPosition@GUIWindow@@QEAAXHH@Z endp

; GUIWindow::setPosition(int, int);
?setPosition@GUIWindow@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_GUIWindow_base+4*8]
?setPosition@GUIWindow@@UEAAXHH@Z endp

?_NV_getWidth@GUIWindow@@QEBAHXZ proc EXPORT
?_NV_getWidth@GUIWindow@@QEBAHXZ endp

; GUIWindow::getWidth();
?getWidth@GUIWindow@@UEBAHXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+5*8]
?getWidth@GUIWindow@@UEBAHXZ endp

?_NV_getHeight@GUIWindow@@QEBAHXZ proc EXPORT
?_NV_getHeight@GUIWindow@@QEBAHXZ endp

; GUIWindow::getHeight();
?getHeight@GUIWindow@@UEBAHXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+6*8]
?getHeight@GUIWindow@@UEBAHXZ endp

?_NV_getWidthReal@GUIWindow@@QEBAMXZ proc EXPORT
?_NV_getWidthReal@GUIWindow@@QEBAMXZ endp

; GUIWindow::getWidthReal();
?getWidthReal@GUIWindow@@UEBAMXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+7*8]
?getWidthReal@GUIWindow@@UEBAMXZ endp

?_NV_getHeightReal@GUIWindow@@QEBAMXZ proc EXPORT
?_NV_getHeightReal@GUIWindow@@QEBAMXZ endp

; GUIWindow::getHeightReal();
?getHeightReal@GUIWindow@@UEBAMXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+8*8]
?getHeightReal@GUIWindow@@UEBAMXZ endp

?_NV_isVisible@GUIWindow@@QEBA_NXZ proc EXPORT
?_NV_isVisible@GUIWindow@@QEBA_NXZ endp

; GUIWindow::isVisible();
?isVisible@GUIWindow@@UEBA_NXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+9*8]
?isVisible@GUIWindow@@UEBA_NXZ endp

?_NV_update@GUIWindow@@QEAAXXZ proc EXPORT
?_NV_update@GUIWindow@@QEAAXXZ endp

; GUIWindow::update();
?update@GUIWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_GUIWindow_base+10*8]
?update@GUIWindow@@UEAAXXZ endp

?_NV_autoChangeSelectedObject@GUIWindow@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_autoChangeSelectedObject@GUIWindow@@QEAAXAEBVhand@@@Z endp

; GUIWindow::autoChangeSelectedObject(const class hand &);
?autoChangeSelectedObject@GUIWindow@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_GUIWindow_base+11*8]
?autoChangeSelectedObject@GUIWindow@@UEAAXAEBVhand@@@Z endp

; GUIWindow::getWidget();
?getWidget@GUIWindow@@QEAAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_GUIWindow_base+12*8]
?getWidget@GUIWindow@@QEAAPEAVWidget@MyGUI@@XZ endp

?_NV_resize@GUIWindow@@QEAAXHH@Z proc EXPORT
?_NV_resize@GUIWindow@@QEAAXHH@Z endp

; GUIWindow::resize(int, int);
?resize@GUIWindow@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_GUIWindow_base+13*8]
?resize@GUIWindow@@UEAAXHH@Z endp
