
?_CONSTRUCTOR@hand@@QEAAPEAV1@PEAVGameData@@W4itemType@@@Z proc EXPORT
?_CONSTRUCTOR@hand@@QEAAPEAV1@PEAVGameData@@W4itemType@@@Z endp

; hand::hand(class GameData *, enum itemType);
??0hand@@QEAA@PEAVGameData@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_hand_base+0*8]
??0hand@@QEAA@PEAVGameData@@W4itemType@@@Z endp

?_CONSTRUCTOR@hand@@QEAAPEAV1@PEAVRootObjectBase@@@Z proc EXPORT
?_CONSTRUCTOR@hand@@QEAAPEAV1@PEAVRootObjectBase@@@Z endp

; hand::hand(class RootObjectBase *);
??0hand@@QEAA@PEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_hand_base+1*8]
??0hand@@QEAA@PEAVRootObjectBase@@@Z endp

?_CONSTRUCTOR@hand@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@hand@@QEAAPEAV1@H@Z endp

; hand::hand(const int);
??0hand@@QEAA@H@Z proc EXPORT
jmp function_pointers[_hand_base+2*8]
??0hand@@QEAA@H@Z endp

?_CONSTRUCTOR@hand@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@hand@@QEAAPEAV1@AEBV1@@Z endp

; hand::hand(const class hand &);
??0hand@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_hand_base+3*8]
??0hand@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@hand@@QEAAPEAV1@IIW4itemType@@II@Z proc EXPORT
?_CONSTRUCTOR@hand@@QEAAPEAV1@IIW4itemType@@II@Z endp

; hand::hand(unsigned int, unsigned int, enum itemType, unsigned int, unsigned int);
??0hand@@QEAA@IIW4itemType@@II@Z proc EXPORT
jmp function_pointers[_hand_base+4*8]
??0hand@@QEAA@IIW4itemType@@II@Z endp

?_CONSTRUCTOR@hand@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@hand@@QEAAPEAV1@XZ endp

; hand::hand();
??0hand@@QEAA@XZ proc EXPORT
jmp function_pointers[_hand_base+5*8]
??0hand@@QEAA@XZ endp

; hand::toString();
?toString@hand@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_hand_base+6*8]
?toString@hand@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; hand::fromString(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?fromString@hand@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_hand_base+7*8]
?fromString@hand@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_operator_equal@hand@@QEBA_N_N@Z proc EXPORT
?_NV_operator_equal@hand@@QEBA_N_N@Z endp

; hand::operator==(bool);
??8hand@@UEBA_N_N@Z proc EXPORT
jmp function_pointers[_hand_base+8*8]
??8hand@@UEBA_N_N@Z endp

; hand::operator==(const class RootObjectBase *);
??8hand@@QEBA_NPEBVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_hand_base+9*8]
??8hand@@QEBA_NPEBVRootObjectBase@@@Z endp

?_NV_operator_equal@hand@@QEBA_NAEBV1@@Z proc EXPORT
?_NV_operator_equal@hand@@QEBA_NAEBV1@@Z endp

; hand::operator==(const class hand &);
??8hand@@UEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_hand_base+10*8]
??8hand@@UEBA_NAEBV0@@Z endp

; hand::operator!=(const class RootObjectBase *);
??9hand@@QEBA_NPEBVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_hand_base+11*8]
??9hand@@QEBA_NPEBVRootObjectBase@@@Z endp

?_NV_operator_notequal@hand@@QEBA_NAEBV1@@Z proc EXPORT
?_NV_operator_notequal@hand@@QEBA_NAEBV1@@Z endp

; hand::operator!=(const class hand &);
??9hand@@UEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_hand_base+12*8]
??9hand@@UEBA_NAEBV0@@Z endp

; hand::operator bool();
??Bhand@@QEBA_NXZ proc EXPORT
jmp function_pointers[_hand_base+13*8]
??Bhand@@QEBA_NXZ endp

; hand::getCharacter();
?getCharacter@hand@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_hand_base+14*8]
?getCharacter@hand@@QEBAPEAVCharacter@@XZ endp

; hand::getPlatoon();
?getPlatoon@hand@@QEBAPEAVPlatoon@@XZ proc EXPORT
jmp function_pointers[_hand_base+15*8]
?getPlatoon@hand@@QEBAPEAVPlatoon@@XZ endp

; hand::getActivePlatoon();
?getActivePlatoon@hand@@QEBAPEAVActivePlatoon@@XZ proc EXPORT
jmp function_pointers[_hand_base+16*8]
?getActivePlatoon@hand@@QEBAPEAVActivePlatoon@@XZ endp

; hand::getBuilding();
?getBuilding@hand@@QEBAPEAVBuilding@@XZ proc EXPORT
jmp function_pointers[_hand_base+17*8]
?getBuilding@hand@@QEBAPEAVBuilding@@XZ endp

; hand::getItem();
?getItem@hand@@QEBAPEAVItem@@XZ proc EXPORT
jmp function_pointers[_hand_base+18*8]
?getItem@hand@@QEBAPEAVItem@@XZ endp

; hand::getRootObject();
?getRootObject@hand@@QEBAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_hand_base+19*8]
?getRootObject@hand@@QEBAPEAVRootObject@@XZ endp

; hand::getRootObjectBase();
?getRootObjectBase@hand@@QEBAPEAVRootObjectBase@@XZ proc EXPORT
jmp function_pointers[_hand_base+20*8]
?getRootObjectBase@hand@@QEBAPEAVRootObjectBase@@XZ endp

; hand::getTown();
?getTown@hand@@QEBAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_hand_base+21*8]
?getTown@hand@@QEBAPEAVTownBase@@XZ endp

; hand::debugWhatHappenedToMe();
?debugWhatHappenedToMe@hand@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_hand_base+22*8]
?debugWhatHappenedToMe@hand@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; hand::operator<(const class hand &);
??Mhand@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_hand_base+23*8]
??Mhand@@QEBA_NAEBV0@@Z endp

; hand::operator=(const class hand &);
??4hand@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_hand_base+24*8]
??4hand@@QEAAAEAV0@AEBV0@@Z endp

; hand::operator=(class RootObjectBase *);
??4hand@@QEAAAEBV0@PEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_hand_base+25*8]
??4hand@@QEAAAEBV0@PEAVRootObjectBase@@@Z endp

; hand::operator=(const int &);
??4hand@@QEAAAEBV0@AEBH@Z proc EXPORT
jmp function_pointers[_hand_base+26*8]
??4hand@@QEAAAEBV0@AEBH@Z endp

; hand::setNull();
?setNull@hand@@QEAAXXZ proc EXPORT
jmp function_pointers[_hand_base+27*8]
?setNull@hand@@QEAAXXZ endp

; hand::isNull();
?isNull@hand@@QEBA_NXZ proc EXPORT
jmp function_pointers[_hand_base+28*8]
?isNull@hand@@QEBA_NXZ endp

; hand::isValid();
?isValid@hand@@QEBA_NXZ proc EXPORT
jmp function_pointers[_hand_base+29*8]
?isValid@hand@@QEBA_NXZ endp

; hand::canCastToRootObject();
?canCastToRootObject@hand@@QEBA_NXZ proc EXPORT
jmp function_pointers[_hand_base+30*8]
?canCastToRootObject@hand@@QEBA_NXZ endp

; hand::squadMatch(const class hand &);
?squadMatch@hand@@QEBA_NAEBV1@@Z proc EXPORT
jmp function_pointers[_hand_base+31*8]
?squadMatch@hand@@QEBA_NAEBV1@@Z endp
