
; HavokCharacter::operator new(unsigned __int64);
??2HavokCharacter@@SAPEAX_K@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+0*8]
??2HavokCharacter@@SAPEAX_K@Z endp

; HavokCharacter::operator delete(void *);
??3HavokCharacter@@SAXPEAX@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+1*8]
??3HavokCharacter@@SAXPEAX@Z endp

?_CONSTRUCTOR@HavokCharacter@@QEAAPEAV1@AEBVhand@@AEBVVector3@Ogre@@MMPEAVSensoryData@@@Z proc EXPORT
?_CONSTRUCTOR@HavokCharacter@@QEAAPEAV1@AEBVhand@@AEBVVector3@Ogre@@MMPEAVSensoryData@@@Z endp

; HavokCharacter::HavokCharacter(const class hand &, const class Ogre::Vector3 &, float, float, class SensoryData *);
??0HavokCharacter@@QEAA@AEBVhand@@AEBVVector3@Ogre@@MMPEAVSensoryData@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+2*8]
??0HavokCharacter@@QEAA@AEBVhand@@AEBVVector3@Ogre@@MMPEAVSensoryData@@@Z endp

?_DESTRUCTOR@HavokCharacter@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@HavokCharacter@@QEAAXXZ endp

; HavokCharacter::~HavokCharacter();
??1HavokCharacter@@QEAA@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+3*8]
??1HavokCharacter@@QEAA@XZ endp

; HavokCharacter::setHandle(const class hand &);
?setHandle@HavokCharacter@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+4*8]
?setHandle@HavokCharacter@@QEAAXAEBVhand@@@Z endp

; HavokCharacter::setPosition(const class Ogre::Vector3 &, unsigned int);
?setPosition@HavokCharacter@@QEAAXAEBVVector3@Ogre@@I@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+5*8]
?setPosition@HavokCharacter@@QEAAXAEBVVector3@Ogre@@I@Z endp

; HavokCharacter::getPosition();
?getPosition@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+6*8]
?getPosition@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ endp

; HavokCharacter::setVelocity(const class Ogre::Vector3 &);
?setVelocity@HavokCharacter@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+7*8]
?setVelocity@HavokCharacter@@QEAAXAEBVVector3@Ogre@@@Z endp

; HavokCharacter::getVelocity();
?getVelocity@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+8*8]
?getVelocity@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ endp

; HavokCharacter::getWaypointDirection();
?getWaypointDirection@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+9*8]
?getWaypointDirection@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ endp

; HavokCharacter::getDirectionMoved();
?getDirectionMoved@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+10*8]
?getDirectionMoved@HavokCharacter@@QEBA?AVVector3@Ogre@@XZ endp

; HavokCharacter::setWaterModifier(float);
?setWaterModifier@HavokCharacter@@QEAAXM@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+11*8]
?setWaterModifier@HavokCharacter@@QEAAXM@Z endp

; HavokCharacter::setManualMode(bool);
?setManualMode@HavokCharacter@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+12*8]
?setManualMode@HavokCharacter@@QEAAX_N@Z endp

; HavokCharacter::setDesiredSpeed(float);
?setDesiredSpeed@HavokCharacter@@QEAAXM@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+13*8]
?setDesiredSpeed@HavokCharacter@@QEAAXM@Z endp

; HavokCharacter::getState();
?getState@HavokCharacter@@QEBA?AW4CharacterState@1@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+14*8]
?getState@HavokCharacter@@QEBA?AW4CharacterState@1@XZ endp

; HavokCharacter::getPathState();
?getPathState@HavokCharacter@@QEBA?AW4PathState@1@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+15*8]
?getPathState@HavokCharacter@@QEBA?AW4PathState@1@XZ endp

; HavokCharacter::isOnNavmesh();
?isOnNavmesh@HavokCharacter@@QEBA_NXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+16*8]
?isOnNavmesh@HavokCharacter@@QEBA_NXZ endp

; HavokCharacter::getCollidedCharacter();
?getCollidedCharacter@HavokCharacter@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+17*8]
?getCollidedCharacter@HavokCharacter@@QEBAAEBVhand@@XZ endp

; HavokCharacter::getClosestPoint(const class Ogre::Vector3 &, float, class Building *);
?getClosestPoint@HavokCharacter@@QEAA?AVVector3@Ogre@@AEBV23@MPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+18*8]
?getClosestPoint@HavokCharacter@@QEAA?AVVector3@Ogre@@AEBV23@MPEAVBuilding@@@Z endp

; HavokCharacter::requestPath(const class Ogre::Vector3 &, int);
?requestPath@HavokCharacter@@QEAAXAEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+19*8]
?requestPath@HavokCharacter@@QEAAXAEBVVector3@Ogre@@H@Z endp

; HavokCharacter::clearPath();
?clearPath@HavokCharacter@@QEAAXXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+20*8]
?clearPath@HavokCharacter@@QEAAXXZ endp

; HavokCharacter::calculateFuturePosition(float, class hkVector4f &, class hkVector4f &, bool);
?calculateFuturePosition@HavokCharacter@@QEAAHMAEAVhkVector4f@@0_N@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+21*8]
?calculateFuturePosition@HavokCharacter@@QEAAHMAEAVhkVector4f@@0_N@Z endp

; HavokCharacter::calculateFuturePosition(float);
?calculateFuturePosition@HavokCharacter@@QEAA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+22*8]
?calculateFuturePosition@HavokCharacter@@QEAA?AVVector3@Ogre@@M@Z endp

; HavokCharacter::update(float);
?update@HavokCharacter@@QEAAXM@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+23*8]
?update@HavokCharacter@@QEAAXM@Z endp

; HavokCharacter::moveAlongPath(float);
?moveAlongPath@HavokCharacter@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+24*8]
?moveAlongPath@HavokCharacter@@QEAA_NM@Z endp

; HavokCharacter::handleCollision();
?handleCollision@HavokCharacter@@QEAA_NXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+25*8]
?handleCollision@HavokCharacter@@QEAA_NXZ endp

; HavokCharacter::invalidate(int);
?invalidate@HavokCharacter@@QEAAXH@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+26*8]
?invalidate@HavokCharacter@@QEAAXH@Z endp

; HavokCharacter::updateVelocity(const class hkVector4f &, float);
?updateVelocity@HavokCharacter@@QEAAXAEBVhkVector4f@@M@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+27*8]
?updateVelocity@HavokCharacter@@QEAAXAEBVhkVector4f@@M@Z endp

; HavokCharacter::_getFace(class hkVector4f &, unsigned int &);
?_getFace@HavokCharacter@@QEBAXAEAVhkVector4f@@AEAI@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+28*8]
?_getFace@HavokCharacter@@QEBAXAEAVhkVector4f@@AEAI@Z endp

; HavokCharacter::_getFaceKey();
?_getFaceKey@HavokCharacter@@QEBAIXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+29*8]
?_getFaceKey@HavokCharacter@@QEBAIXZ endp

; HavokCharacter::setPath(struct HavokCharacterMessage *);
?setPath@HavokCharacter@@QEAAXPEAUHavokCharacterMessage@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+30*8]
?setPath@HavokCharacter@@QEAAXPEAUHavokCharacterMessage@@@Z endp

; HavokCharacter::calculatePathVector(class hkVector4f &, class hkVector4f &, bool);
?calculatePathVector@HavokCharacter@@QEAAHAEAVhkVector4f@@0_N@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+31*8]
?calculatePathVector@HavokCharacter@@QEAAHAEAVhkVector4f@@0_N@Z endp

; HavokCharacter::calculateAvoidanceVector(class hkVector4f &, class hkSimdFloat32 &);
?calculateAvoidanceVector@HavokCharacter@@QEAAHAEAVhkVector4f@@AEAVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+32*8]
?calculateAvoidanceVector@HavokCharacter@@QEAAHAEAVhkVector4f@@AEAVhkSimdFloat32@@@Z endp

; HavokCharacter::pullThroughVertex(int, int);
?pullThroughVertex@HavokCharacter@@QEAAHHH@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+33*8]
?pullThroughVertex@HavokCharacter@@QEAAHHH@Z endp

; HavokCharacter::updateNextEdge();
?updateNextEdge@HavokCharacter@@QEAAHXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+34*8]
?updateNextEdge@HavokCharacter@@QEAAHXZ endp

; HavokCharacter::updateEdgeCache(const class hkVector4f &, float);
?updateEdgeCache@HavokCharacter@@QEAA_NAEBVhkVector4f@@M@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+35*8]
?updateEdgeCache@HavokCharacter@@QEAA_NAEBVhkVector4f@@M@Z endp

; HavokCharacter::moveCollide(const class hkVector4f &, const class hkVector4f &, float, float &, class hkVector4f &);
?moveCollide@HavokCharacter@@QEBAHAEBVhkVector4f@@0MAEAMAEAV2@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+36*8]
?moveCollide@HavokCharacter@@QEBAHAEBVhkVector4f@@0MAEAMAEAV2@@Z endp

; HavokCharacter::edgeCollision(float, class hkVector4f &);
?edgeCollision@HavokCharacter@@QEBAHMAEAVhkVector4f@@@Z proc EXPORT
jmp function_pointers[_HavokCharacter_base+37*8]
?edgeCollision@HavokCharacter@@QEBAHMAEAVhkVector4f@@@Z endp

; HavokCharacter::resolveProblems();
?resolveProblems@HavokCharacter@@QEAAXXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+38*8]
?resolveProblems@HavokCharacter@@QEAAXXZ endp

; HavokCharacter::atGoal();
?atGoal@HavokCharacter@@QEBA_NXZ proc EXPORT
jmp function_pointers[_HavokCharacter_base+39*8]
?atGoal@HavokCharacter@@QEBA_NXZ endp
