
?_CONSTRUCTOR@hkBool@@QEAAPEAV1@_N@Z proc EXPORT
?_CONSTRUCTOR@hkBool@@QEAAPEAV1@_N@Z endp

; hkBool::hkBool(bool);
??0hkBool@@QEAA@_N@Z proc EXPORT
jmp function_pointers[_hkBool_base+0*8]
??0hkBool@@QEAA@_N@Z endp

?_CONSTRUCTOR@hkBool@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@hkBool@@QEAAPEAV1@XZ endp

; hkBool::hkBool();
??0hkBool@@QEAA@XZ proc EXPORT
jmp function_pointers[_hkBool_base+1*8]
??0hkBool@@QEAA@XZ endp

; hkBool::operator bool();
??BhkBool@@QEBA_NXZ proc EXPORT
jmp function_pointers[_hkBool_base+2*8]
??BhkBool@@QEBA_NXZ endp

; hkBool::operator==(bool);
??8hkBool@@QEBA?AV0@_N@Z proc EXPORT
jmp function_pointers[_hkBool_base+3*8]
??8hkBool@@QEBA?AV0@_N@Z endp

; hkBool::operator!=(bool);
??9hkBool@@QEBA?AV0@_N@Z proc EXPORT
jmp function_pointers[_hkBool_base+4*8]
??9hkBool@@QEBA?AV0@_N@Z endp
