
; hkContainerHeapAllocator::Allocator::operator delete(void *, unsigned __int64);
??3Allocator@hkContainerHeapAllocator@@SAXPEAX_K@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+0*8]
??3Allocator@hkContainerHeapAllocator@@SAXPEAX_K@Z endp

?_NV_blockAlloc@Allocator@hkContainerHeapAllocator@@QEAAPEAXH@Z proc EXPORT
?_NV_blockAlloc@Allocator@hkContainerHeapAllocator@@QEAAPEAXH@Z endp

; hkContainerHeapAllocator::Allocator::blockAlloc(int);
?blockAlloc@Allocator@hkContainerHeapAllocator@@UEAAPEAXH@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+1*8]
?blockAlloc@Allocator@hkContainerHeapAllocator@@UEAAPEAXH@Z endp

?_NV_blockFree@Allocator@hkContainerHeapAllocator@@QEAAXPEAXH@Z proc EXPORT
?_NV_blockFree@Allocator@hkContainerHeapAllocator@@QEAAXPEAXH@Z endp

; hkContainerHeapAllocator::Allocator::blockFree(void *, int);
?blockFree@Allocator@hkContainerHeapAllocator@@UEAAXPEAXH@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+2*8]
?blockFree@Allocator@hkContainerHeapAllocator@@UEAAXPEAXH@Z endp

?_NV_bufAlloc@Allocator@hkContainerHeapAllocator@@QEAAPEAXAEAH@Z proc EXPORT
?_NV_bufAlloc@Allocator@hkContainerHeapAllocator@@QEAAPEAXAEAH@Z endp

; hkContainerHeapAllocator::Allocator::bufAlloc(int &);
?bufAlloc@Allocator@hkContainerHeapAllocator@@UEAAPEAXAEAH@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+3*8]
?bufAlloc@Allocator@hkContainerHeapAllocator@@UEAAPEAXAEAH@Z endp

?_NV_bufFree@Allocator@hkContainerHeapAllocator@@QEAAXPEAXH@Z proc EXPORT
?_NV_bufFree@Allocator@hkContainerHeapAllocator@@QEAAXPEAXH@Z endp

; hkContainerHeapAllocator::Allocator::bufFree(void *, int);
?bufFree@Allocator@hkContainerHeapAllocator@@UEAAXPEAXH@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+4*8]
?bufFree@Allocator@hkContainerHeapAllocator@@UEAAXPEAXH@Z endp

?_NV_bufRealloc@Allocator@hkContainerHeapAllocator@@QEAAPEAXPEAXHAEAH@Z proc EXPORT
?_NV_bufRealloc@Allocator@hkContainerHeapAllocator@@QEAAPEAXPEAXHAEAH@Z endp

; hkContainerHeapAllocator::Allocator::bufRealloc(void *, int, int &);
?bufRealloc@Allocator@hkContainerHeapAllocator@@UEAAPEAXPEAXHAEAH@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+5*8]
?bufRealloc@Allocator@hkContainerHeapAllocator@@UEAAPEAXPEAXHAEAH@Z endp

?_NV_getMemoryStatistics@Allocator@hkContainerHeapAllocator@@QEBAXAEAUMemoryStatistics@hkMemoryAllocator@@@Z proc EXPORT
?_NV_getMemoryStatistics@Allocator@hkContainerHeapAllocator@@QEBAXAEAUMemoryStatistics@hkMemoryAllocator@@@Z endp

; hkContainerHeapAllocator::Allocator::getMemoryStatistics(struct hkMemoryAllocator::MemoryStatistics &);
?getMemoryStatistics@Allocator@hkContainerHeapAllocator@@UEBAXAEAUMemoryStatistics@hkMemoryAllocator@@@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+6*8]
?getMemoryStatistics@Allocator@hkContainerHeapAllocator@@UEBAXAEAUMemoryStatistics@hkMemoryAllocator@@@Z endp

?_NV_getAllocatedSize@Allocator@hkContainerHeapAllocator@@QEBAHPEBXH@Z proc EXPORT
?_NV_getAllocatedSize@Allocator@hkContainerHeapAllocator@@QEBAHPEBXH@Z endp

; hkContainerHeapAllocator::Allocator::getAllocatedSize(const void *, int);
?getAllocatedSize@Allocator@hkContainerHeapAllocator@@UEBAHPEBXH@Z proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+7*8]
?getAllocatedSize@Allocator@hkContainerHeapAllocator@@UEBAHPEBXH@Z endp

?_CONSTRUCTOR@Allocator@hkContainerHeapAllocator@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Allocator@hkContainerHeapAllocator@@QEAAPEAV12@XZ endp

; hkContainerHeapAllocator::Allocator::Allocator();
??0Allocator@hkContainerHeapAllocator@@QEAA@XZ proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+8*8]
??0Allocator@hkContainerHeapAllocator@@QEAA@XZ endp

?_DESTRUCTOR@Allocator@hkContainerHeapAllocator@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Allocator@hkContainerHeapAllocator@@QEAAXXZ endp

; hkContainerHeapAllocator::Allocator::~Allocator();
??1Allocator@hkContainerHeapAllocator@@UEAA@XZ proc EXPORT
jmp function_pointers[_hkContainerHeapAllocator_Allocator_base+9*8]
??1Allocator@hkContainerHeapAllocator@@UEAA@XZ endp
