
; hkMemoryAllocator::operator delete(void *, unsigned __int64);
??3hkMemoryAllocator@@SAXPEAX_K@Z proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+0*8]
??3hkMemoryAllocator@@SAXPEAX_K@Z endp

?_DESTRUCTOR@hkMemoryAllocator@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@hkMemoryAllocator@@QEAAXXZ endp

; hkMemoryAllocator::~hkMemoryAllocator();
??1hkMemoryAllocator@@UEAA@XZ proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+1*8]
??1hkMemoryAllocator@@UEAA@XZ endp

?_NV_bufAlloc@hkMemoryAllocator@@QEAAPEAXAEAH@Z proc EXPORT
?_NV_bufAlloc@hkMemoryAllocator@@QEAAPEAXAEAH@Z endp

; hkMemoryAllocator::bufAlloc(int &);
?bufAlloc@hkMemoryAllocator@@UEAAPEAXAEAH@Z proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+2*8]
?bufAlloc@hkMemoryAllocator@@UEAAPEAXAEAH@Z endp

?_NV_bufFree@hkMemoryAllocator@@QEAAXPEAXH@Z proc EXPORT
?_NV_bufFree@hkMemoryAllocator@@QEAAXPEAXH@Z endp

; hkMemoryAllocator::bufFree(void *, int);
?bufFree@hkMemoryAllocator@@UEAAXPEAXH@Z proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+3*8]
?bufFree@hkMemoryAllocator@@UEAAXPEAXH@Z endp

?_NV_bufRealloc@hkMemoryAllocator@@QEAAPEAXPEAXHAEAH@Z proc EXPORT
?_NV_bufRealloc@hkMemoryAllocator@@QEAAPEAXPEAXHAEAH@Z endp

; hkMemoryAllocator::bufRealloc(void *, int, int &);
?bufRealloc@hkMemoryAllocator@@UEAAPEAXPEAXHAEAH@Z proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+4*8]
?bufRealloc@hkMemoryAllocator@@UEAAPEAXPEAXHAEAH@Z endp

?_NV_blockAllocBatch@hkMemoryAllocator@@QEAAXPEAPEAXHH@Z proc EXPORT
?_NV_blockAllocBatch@hkMemoryAllocator@@QEAAXPEAPEAXHH@Z endp

; hkMemoryAllocator::blockAllocBatch(void * *, int, int);
?blockAllocBatch@hkMemoryAllocator@@UEAAXPEAPEAXHH@Z proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+5*8]
?blockAllocBatch@hkMemoryAllocator@@UEAAXPEAPEAXHH@Z endp

?_NV_blockFreeBatch@hkMemoryAllocator@@QEAAXPEAPEAXHH@Z proc EXPORT
?_NV_blockFreeBatch@hkMemoryAllocator@@QEAAXPEAPEAXHH@Z endp

; hkMemoryAllocator::blockFreeBatch(void * *, int, int);
?blockFreeBatch@hkMemoryAllocator@@UEAAXPEAPEAXHH@Z proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+6*8]
?blockFreeBatch@hkMemoryAllocator@@UEAAXPEAPEAXHH@Z endp

?_NV_resetPeakMemoryStatistics@hkMemoryAllocator@@QEAAXXZ proc EXPORT
?_NV_resetPeakMemoryStatistics@hkMemoryAllocator@@QEAAXXZ endp

; hkMemoryAllocator::resetPeakMemoryStatistics();
?resetPeakMemoryStatistics@hkMemoryAllocator@@UEAAXXZ proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+7*8]
?resetPeakMemoryStatistics@hkMemoryAllocator@@UEAAXXZ endp

?_NV_getExtendedInterface@hkMemoryAllocator@@QEAAPEAUExtendedInterface@1@XZ proc EXPORT
?_NV_getExtendedInterface@hkMemoryAllocator@@QEAAPEAUExtendedInterface@1@XZ endp

; hkMemoryAllocator::getExtendedInterface();
?getExtendedInterface@hkMemoryAllocator@@UEAAPEAUExtendedInterface@1@XZ proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+8*8]
?getExtendedInterface@hkMemoryAllocator@@UEAAPEAUExtendedInterface@1@XZ endp

?_CONSTRUCTOR@hkMemoryAllocator@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@hkMemoryAllocator@@QEAAPEAV1@XZ endp

; hkMemoryAllocator::hkMemoryAllocator();
??0hkMemoryAllocator@@QEAA@XZ proc EXPORT
jmp function_pointers[_hkMemoryAllocator_base+9*8]
??0hkMemoryAllocator@@QEAA@XZ endp
