
?_DESTRUCTOR@ExtendedInterface@hkMemoryAllocator@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ExtendedInterface@hkMemoryAllocator@@QEAAXXZ endp

; hkMemoryAllocator::ExtendedInterface::~ExtendedInterface();
??1ExtendedInterface@hkMemoryAllocator@@UEAA@XZ proc EXPORT
jmp function_pointers[_hkMemoryAllocator_ExtendedInterface_base+0*8]
??1ExtendedInterface@hkMemoryAllocator@@UEAA@XZ endp

?_CONSTRUCTOR@ExtendedInterface@hkMemoryAllocator@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ExtendedInterface@hkMemoryAllocator@@QEAAPEAV12@XZ endp

; hkMemoryAllocator::ExtendedInterface::ExtendedInterface();
??0ExtendedInterface@hkMemoryAllocator@@QEAA@XZ proc EXPORT
jmp function_pointers[_hkMemoryAllocator_ExtendedInterface_base+1*8]
??0ExtendedInterface@hkMemoryAllocator@@QEAA@XZ endp
