
; hkVector4fComparison::convert(const union __m128 &);
?convert@hkVector4fComparison@@SA?BV1@AEBT__m128@@@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+0*8]
?convert@hkVector4fComparison@@SA?BV1@AEBT__m128@@@Z endp

; hkVector4fComparison::getMaskForComponent(int);
?getMaskForComponent@hkVector4fComparison@@SA?AW4Mask@hkVector4ComparisonMask@@H@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+1*8]
?getMaskForComponent@hkVector4fComparison@@SA?AW4Mask@hkVector4ComparisonMask@@H@Z endp

; hkVector4fComparison::getIndexOfLastComponentSet();
?getIndexOfLastComponentSet@hkVector4fComparison@@QEBAHXZ proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+2*8]
?getIndexOfLastComponentSet@hkVector4fComparison@@QEBAHXZ endp

; hkVector4fComparison::getIndexOfFirstComponentSet();
?getIndexOfFirstComponentSet@hkVector4fComparison@@QEBAHXZ proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+3*8]
?getIndexOfFirstComponentSet@hkVector4fComparison@@QEBAHXZ endp

; hkVector4fComparison::setAnd(const class hkVector4fComparison &, const class hkVector4fComparison &);
?setAnd@hkVector4fComparison@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+4*8]
?setAnd@hkVector4fComparison@@QEAAXAEBV1@0@Z endp

; hkVector4fComparison::setAndNot(const class hkVector4fComparison &, const class hkVector4fComparison &);
?setAndNot@hkVector4fComparison@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+5*8]
?setAndNot@hkVector4fComparison@@QEAAXAEBV1@0@Z endp

; hkVector4fComparison::setXor(const class hkVector4fComparison &, const class hkVector4fComparison &);
?setXor@hkVector4fComparison@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+6*8]
?setXor@hkVector4fComparison@@QEAAXAEBV1@0@Z endp

; hkVector4fComparison::setOr(const class hkVector4fComparison &, const class hkVector4fComparison &);
?setOr@hkVector4fComparison@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+7*8]
?setOr@hkVector4fComparison@@QEAAXAEBV1@0@Z endp

; hkVector4fComparison::setNot(const class hkVector4fComparison &);
?setNot@hkVector4fComparison@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+8*8]
?setNot@hkVector4fComparison@@QEAAXAEBV1@@Z endp

; hkVector4fComparison::setSelect(const class hkVector4fComparison &, const class hkVector4fComparison &, const class hkVector4fComparison &);
?setSelect@hkVector4fComparison@@QEAAXAEBV1@00@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+9*8]
?setSelect@hkVector4fComparison@@QEAAXAEBV1@00@Z endp

; hkVector4fComparison::set(enum hkVector4ComparisonMask::Mask);
?set@hkVector4fComparison@@QEAAXW4Mask@hkVector4ComparisonMask@@@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+10*8]
?set@hkVector4fComparison@@QEAAXW4Mask@hkVector4ComparisonMask@@@Z endp

; hkVector4fComparison::allAreSet();
?allAreSet@hkVector4fComparison@@QEBAIXZ proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+11*8]
?allAreSet@hkVector4fComparison@@QEBAIXZ endp

; hkVector4fComparison::anyIsSet();
?anyIsSet@hkVector4fComparison@@QEBAIXZ proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+12*8]
?anyIsSet@hkVector4fComparison@@QEBAIXZ endp

; hkVector4fComparison::anyIsSet(enum hkVector4ComparisonMask::Mask);
?anyIsSet@hkVector4fComparison@@QEBAIW4Mask@hkVector4ComparisonMask@@@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+13*8]
?anyIsSet@hkVector4fComparison@@QEBAIW4Mask@hkVector4ComparisonMask@@@Z endp

; hkVector4fComparison::getMask(enum hkVector4ComparisonMask::Mask);
?getMask@hkVector4fComparison@@QEBA?AW4Mask@hkVector4ComparisonMask@@W423@@Z proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+14*8]
?getMask@hkVector4fComparison@@QEBA?AW4Mask@hkVector4ComparisonMask@@W423@@Z endp

; hkVector4fComparison::getMask();
?getMask@hkVector4fComparison@@QEBA?AW4Mask@hkVector4ComparisonMask@@XZ proc EXPORT
jmp function_pointers[_hkVector4fComparison_base+15*8]
?getMask@hkVector4fComparison@@QEBA?AW4Mask@hkVector4ComparisonMask@@XZ endp
