
; hkVector4f::operator new(unsigned __int64);
??2hkVector4f@@SAPEAX_K@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+0*8]
??2hkVector4f@@SAPEAX_K@Z endp

; hkVector4f::operator delete(void *, unsigned __int64);
??3hkVector4f@@SAXPEAX_K@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+1*8]
??3hkVector4f@@SAXPEAX_K@Z endp

?_CONSTRUCTOR@hkVector4f@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@hkVector4f@@QEAAPEAV1@AEBV1@@Z endp

; hkVector4f::hkVector4f(const class hkVector4f &);
??0hkVector4f@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+2*8]
??0hkVector4f@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@hkVector4f@@QEAAPEAV1@MMMM@Z proc EXPORT
?_CONSTRUCTOR@hkVector4f@@QEAAPEAV1@MMMM@Z endp

; hkVector4f::hkVector4f(float, float, float, float);
??0hkVector4f@@QEAA@MMMM@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+3*8]
??0hkVector4f@@QEAA@MMMM@Z endp

?_CONSTRUCTOR@hkVector4f@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@hkVector4f@@QEAAPEAV1@XZ endp

; hkVector4f::hkVector4f();
??0hkVector4f@@QEAA@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+4*8]
??0hkVector4f@@QEAA@XZ endp

; hkVector4f::operator=(const class hkVector4f &);
??4hkVector4f@@QEAAXAEBV0@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+5*8]
??4hkVector4f@@QEAAXAEBV0@@Z endp

; hkVector4f::set(float, float, float, float);
?set@hkVector4f@@QEAAXMMMM@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+6*8]
?set@hkVector4f@@QEAAXMMMM@Z endp

; hkVector4f::set(const class hkSimdFloat32 &, const class hkSimdFloat32 &, const class hkSimdFloat32 &, const class hkSimdFloat32 &);
?set@hkVector4f@@QEAAXAEBVhkSimdFloat32@@000@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+7*8]
?set@hkVector4f@@QEAAXAEBVhkSimdFloat32@@000@Z endp

; hkVector4f::setAll(const float &);
?setAll@hkVector4f@@QEAAXAEBM@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+8*8]
?setAll@hkVector4f@@QEAAXAEBM@Z endp

; hkVector4f::setAll(const class hkSimdFloat32 &);
?setAll@hkVector4f@@QEAAXAEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+9*8]
?setAll@hkVector4f@@QEAAXAEBVhkSimdFloat32@@@Z endp

; hkVector4f::setZero();
?setZero@hkVector4f@@QEAAXXZ proc EXPORT
jmp function_pointers[_hkVector4f_base+10*8]
?setZero@hkVector4f@@QEAAXXZ endp

; hkVector4f::zeroComponent(const int);
?zeroComponent@hkVector4f@@QEAAXH@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+11*8]
?zeroComponent@hkVector4f@@QEAAXH@Z endp

; hkVector4f::add(const class hkVector4f &);
?add@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+12*8]
?add@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::sub(const class hkVector4f &);
?sub@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+13*8]
?sub@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::mul(const class hkSimdFloat32 &);
?mul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+14*8]
?mul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@@Z endp

; hkVector4f::mul(const class hkVector4f &);
?mul@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+15*8]
?mul@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::div(const class hkVector4f &);
?div@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+16*8]
?div@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setAdd(const class hkVector4f &, const class hkSimdFloat32 &);
?setAdd@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+17*8]
?setAdd@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setAdd(const class hkVector4f &, const class hkVector4f &);
?setAdd@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+18*8]
?setAdd@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setSub(const class hkVector4f &, const class hkSimdFloat32 &);
?setSub@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+19*8]
?setSub@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setSub(const class hkVector4f &, const class hkVector4f &);
?setSub@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+20*8]
?setSub@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setMul(const class hkSimdFloat32 &, const class hkVector4f &);
?setMul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+21*8]
?setMul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::setMul(const class hkVector4f &, const class hkSimdFloat32 &);
?setMul@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+22*8]
?setMul@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setMul(const class hkVector4f &, const class hkVector4f &);
?setMul@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+23*8]
?setMul@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setDiv(const class hkVector4f &, const class hkVector4f &);
?setDiv@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+24*8]
?setDiv@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setReciprocal(const class hkVector4f &);
?setReciprocal@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+25*8]
?setReciprocal@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setSqrt(const class hkVector4f &);
?setSqrt@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+26*8]
?setSqrt@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setSqrtInverse(const class hkVector4f &);
?setSqrtInverse@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+27*8]
?setSqrtInverse@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::addMul(const class hkSimdFloat32 &, const class hkVector4f &);
?addMul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+28*8]
?addMul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::addMul(const class hkVector4f &, const class hkSimdFloat32 &);
?addMul@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+29*8]
?addMul@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::addMul(const class hkVector4f &, const class hkVector4f &);
?addMul@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+30*8]
?addMul@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setAddMul(const class hkVector4f &, const class hkVector4f &, const class hkSimdFloat32 &);
?setAddMul@hkVector4f@@QEAAXAEBV1@0AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+31*8]
?setAddMul@hkVector4f@@QEAAXAEBV1@0AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setAddMul(const class hkVector4f &, const class hkVector4f &, const class hkVector4f &);
?setAddMul@hkVector4f@@QEAAXAEBV1@00@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+32*8]
?setAddMul@hkVector4f@@QEAAXAEBV1@00@Z endp

; hkVector4f::subMul(const class hkSimdFloat32 &, const class hkVector4f &);
?subMul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+33*8]
?subMul@hkVector4f@@QEAAXAEBVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::subMul(const class hkVector4f &, const class hkSimdFloat32 &);
?subMul@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+34*8]
?subMul@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::subMul(const class hkVector4f &, const class hkVector4f &);
?subMul@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+35*8]
?subMul@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setSubMul(const class hkVector4f &, const class hkVector4f &, const class hkSimdFloat32 &);
?setSubMul@hkVector4f@@QEAAXAEBV1@0AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+36*8]
?setSubMul@hkVector4f@@QEAAXAEBV1@0AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setSubMul(const class hkVector4f &, const class hkVector4f &, const class hkVector4f &);
?setSubMul@hkVector4f@@QEAAXAEBV1@00@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+37*8]
?setSubMul@hkVector4f@@QEAAXAEBV1@00@Z endp

; hkVector4f::setCross(const class hkVector4f &, const class hkVector4f &);
?setCross@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+38*8]
?setCross@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setInterpolate(const class hkVector4f &, const class hkVector4f &, const class hkSimdFloat32 &);
?setInterpolate@hkVector4f@@QEAAXAEBV1@0AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+39*8]
?setInterpolate@hkVector4f@@QEAAXAEBV1@0AEBVhkSimdFloat32@@@Z endp

; hkVector4f::less(const class hkVector4f &);
?less@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+40*8]
?less@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z endp

; hkVector4f::lessEqual(const class hkVector4f &);
?lessEqual@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+41*8]
?lessEqual@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z endp

; hkVector4f::greater(const class hkVector4f &);
?greater@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+42*8]
?greater@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z endp

; hkVector4f::greaterEqual(const class hkVector4f &);
?greaterEqual@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+43*8]
?greaterEqual@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z endp

; hkVector4f::equal(const class hkVector4f &);
?equal@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+44*8]
?equal@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z endp

; hkVector4f::notEqual(const class hkVector4f &);
?notEqual@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+45*8]
?notEqual@hkVector4f@@QEBA?BVhkVector4fComparison@@AEBV1@@Z endp

; hkVector4f::lessZero();
?lessZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+46*8]
?lessZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ endp

; hkVector4f::lessEqualZero();
?lessEqualZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+47*8]
?lessEqualZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ endp

; hkVector4f::greaterZero();
?greaterZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+48*8]
?greaterZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ endp

; hkVector4f::greaterEqualZero();
?greaterEqualZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+49*8]
?greaterEqualZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ endp

; hkVector4f::equalZero();
?equalZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+50*8]
?equalZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ endp

; hkVector4f::notEqualZero();
?notEqualZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+51*8]
?notEqualZero@hkVector4f@@QEBA?BVhkVector4fComparison@@XZ endp

; hkVector4f::setSelect(const class hkVector4fComparison &, const class hkVector4f &, const class hkVector4f &);
?setSelect@hkVector4f@@QEAAXAEBVhkVector4fComparison@@AEBV1@1@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+52*8]
?setSelect@hkVector4f@@QEAAXAEBVhkVector4fComparison@@AEBV1@1@Z endp

; hkVector4f::zeroIfFalse(const class hkVector4fComparison &);
?zeroIfFalse@hkVector4f@@QEAAXAEBVhkVector4fComparison@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+53*8]
?zeroIfFalse@hkVector4f@@QEAAXAEBVhkVector4fComparison@@@Z endp

; hkVector4f::zeroIfTrue(const class hkVector4fComparison &);
?zeroIfTrue@hkVector4f@@QEAAXAEBVhkVector4fComparison@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+54*8]
?zeroIfTrue@hkVector4f@@QEAAXAEBVhkVector4fComparison@@@Z endp

; hkVector4f::setFlipSign(const class hkVector4f &, const class hkSimdFloat32 &);
?setFlipSign@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+55*8]
?setFlipSign@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setFlipSign(const class hkVector4f &, const class hkVector4f &);
?setFlipSign@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+56*8]
?setFlipSign@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setFlipSign(const class hkVector4f &, const class hkVector4fComparison &);
?setFlipSign@hkVector4f@@QEAAXAEBV1@AEBVhkVector4fComparison@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+57*8]
?setFlipSign@hkVector4f@@QEAAXAEBV1@AEBVhkVector4fComparison@@@Z endp

; hkVector4f::setAbs(const class hkVector4f &);
?setAbs@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+58*8]
?setAbs@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setMin(const class hkVector4f &, const class hkVector4f &);
?setMin@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+59*8]
?setMin@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setMax(const class hkVector4f &, const class hkVector4f &);
?setMax@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+60*8]
?setMax@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setClamped(const class hkVector4f &, const class hkVector4f &, const class hkVector4f &);
?setClamped@hkVector4f@@QEAAXAEBV1@00@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+61*8]
?setClamped@hkVector4f@@QEAAXAEBV1@00@Z endp

; hkVector4f::setClampedZeroOne(const class hkVector4f &);
?setClampedZeroOne@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+62*8]
?setClampedZeroOne@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setClampedToMaxLength(const class hkVector4f &, const class hkSimdFloat32 &);
?setClampedToMaxLength@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+63*8]
?setClampedToMaxLength@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setRotatedDir(const class hkQuaternionf &, const class hkVector4f &);
?setRotatedDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+64*8]
?setRotatedDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z endp

; hkVector4f::setRotatedDir(const class hkMatrix3f &, const class hkVector4f &);
?setRotatedDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+65*8]
?setRotatedDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z endp

; hkVector4f::setRotatedInverseDir(const class hkQuaternionf &, const class hkVector4f &);
?setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+66*8]
?setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z endp

; hkVector4f::setRotatedInverseDir(const class hkMatrix3f &, const class hkVector4f &);
?setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+67*8]
?setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z endp

; hkVector4f::setTransformedPos(const class hkQTransformf &, const class hkVector4f &);
?setTransformedPos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+68*8]
?setTransformedPos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z endp

; hkVector4f::setTransformedPos(const class hkQsTransformf &, const class hkVector4f &);
?setTransformedPos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+69*8]
?setTransformedPos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z endp

; hkVector4f::setTransformedPos(const class hkTransformf &, const class hkVector4f &);
?setTransformedPos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+70*8]
?setTransformedPos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z endp

; hkVector4f::setTransformedInversePos(const class hkQTransformf &, const class hkVector4f &);
?setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+71*8]
?setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z endp

; hkVector4f::setTransformedInversePos(const class hkQsTransformf &, const class hkVector4f &);
?setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+72*8]
?setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z endp

; hkVector4f::setTransformedInversePos(const class hkTransformf &, const class hkVector4f &);
?setTransformedInversePos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+73*8]
?setTransformedInversePos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z endp

; hkVector4f::_setRotatedDir(const class hkQuaternionf &, const class hkVector4f &);
?_setRotatedDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+74*8]
?_setRotatedDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z endp

; hkVector4f::_setRotatedDir(const class hkMatrix3f &, const class hkVector4f &);
?_setRotatedDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+75*8]
?_setRotatedDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z endp

; hkVector4f::_setRotatedInverseDir(const class hkQuaternionf &, const class hkVector4f &);
?_setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+76*8]
?_setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkQuaternionf@@AEBV1@@Z endp

; hkVector4f::_setRotatedInverseDir(const class hkMatrix3f &, const class hkVector4f &);
?_setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+77*8]
?_setRotatedInverseDir@hkVector4f@@QEAAXAEBVhkMatrix3f@@AEBV1@@Z endp

; hkVector4f::_setTransformedPos(const class hkQTransformf &, const class hkVector4f &);
?_setTransformedPos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+78*8]
?_setTransformedPos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z endp

; hkVector4f::_setTransformedPos(const class hkQsTransformf &, const class hkVector4f &);
?_setTransformedPos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+79*8]
?_setTransformedPos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z endp

; hkVector4f::_setTransformedPos(const class hkTransformf &, const class hkVector4f &);
?_setTransformedPos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+80*8]
?_setTransformedPos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z endp

; hkVector4f::_setTransformedInversePos(const class hkQTransformf &, const class hkVector4f &);
?_setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+81*8]
?_setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQTransformf@@AEBV1@@Z endp

; hkVector4f::_setTransformedInversePos(const class hkQsTransformf &, const class hkVector4f &);
?_setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+82*8]
?_setTransformedInversePos@hkVector4f@@QEAAXAEBVhkQsTransformf@@AEBV1@@Z endp

; hkVector4f::_setTransformedInversePos(const class hkTransformf &, const class hkVector4f &);
?_setTransformedInversePos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+83*8]
?_setTransformedInversePos@hkVector4f@@QEAAXAEBVhkTransformf@@AEBV1@@Z endp

; hkVector4f::setPlaneConstant(const class hkVector4f &);
?setPlaneConstant@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+84*8]
?setPlaneConstant@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::dot4xyz1(const class hkVector4f &);
?dot4xyz1@hkVector4f@@QEBA?BVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+85*8]
?dot4xyz1@hkVector4f@@QEBA?BVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::distanceTo(const class hkVector4f &);
?distanceTo@hkVector4f@@QEBA?BVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+86*8]
?distanceTo@hkVector4f@@QEBA?BVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::distanceToSquared(const class hkVector4f &);
?distanceToSquared@hkVector4f@@QEBA?BVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+87*8]
?distanceToSquared@hkVector4f@@QEBA?BVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::setXYZ_W(const class hkVector4f &, const class hkSimdFloat32 &);
?setXYZ_W@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+88*8]
?setXYZ_W@hkVector4f@@QEAAXAEBV1@AEBVhkSimdFloat32@@@Z endp

; hkVector4f::setXYZ_W(const class hkVector4f &, const class hkVector4f &);
?setXYZ_W@hkVector4f@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+89*8]
?setXYZ_W@hkVector4f@@QEAAXAEBV1@0@Z endp

; hkVector4f::setW(const class hkSimdFloat32 &);
?setW@hkVector4f@@QEAAXAEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+90*8]
?setW@hkVector4f@@QEAAXAEBVhkSimdFloat32@@@Z endp

; hkVector4f::setW(const class hkVector4f &);
?setW@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+91*8]
?setW@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setXYZ(float);
?setXYZ@hkVector4f@@QEAAXM@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+92*8]
?setXYZ@hkVector4f@@QEAAXM@Z endp

; hkVector4f::setXYZ(const class hkVector4f &);
?setXYZ@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+93*8]
?setXYZ@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setXYZ_0(const class hkVector4f &);
?setXYZ_0@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+94*8]
?setXYZ_0@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::setInt24W(int);
?setInt24W@hkVector4f@@QEAAXH@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+95*8]
?setInt24W@hkVector4f@@QEAAXH@Z endp

; hkVector4f::getInt24W();
?getInt24W@hkVector4f@@QEBAHXZ proc EXPORT
jmp function_pointers[_hkVector4f_base+96*8]
?getInt24W@hkVector4f@@QEBAHXZ endp

; hkVector4f::getInt16W();
?getInt16W@hkVector4f@@QEBAHXZ proc EXPORT
jmp function_pointers[_hkVector4f_base+97*8]
?getInt16W@hkVector4f@@QEBAHXZ endp

; hkVector4f::operator()(int);
??RhkVector4f@@QEBAAEBMH@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+98*8]
??RhkVector4f@@QEBAAEBMH@Z endp

; hkVector4f::operator()(int);
??RhkVector4f@@QEAAAEAMH@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+99*8]
??RhkVector4f@@QEAAAEAMH@Z endp

; hkVector4f::getComponent(const int);
?getComponent@hkVector4f@@QEBA?BVhkSimdFloat32@@H@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+100*8]
?getComponent@hkVector4f@@QEBA?BVhkSimdFloat32@@H@Z endp

; hkVector4f::getW();
?getW@hkVector4f@@QEBA?BVhkSimdFloat32@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+101*8]
?getW@hkVector4f@@QEBA?BVhkSimdFloat32@@XZ endp

; hkVector4f::setComponent(const int, const class hkSimdFloat32 &);
?setComponent@hkVector4f@@QEAAXHAEBVhkSimdFloat32@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+102*8]
?setComponent@hkVector4f@@QEAAXHAEBVhkSimdFloat32@@@Z endp

; hkVector4f::getZero();
?getZero@hkVector4f@@SAAEBV1@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+103*8]
?getZero@hkVector4f@@SAAEBV1@XZ endp

; hkVector4f::getConstant(enum hkVectorConstant);
?getConstant@hkVector4f@@SAAEBV1@W4hkVectorConstant@@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+104*8]
?getConstant@hkVector4f@@SAAEBV1@W4hkVectorConstant@@@Z endp

; hkVector4f::dot3(const class hkVector4f &);
?dot3@hkVector4f@@QEBA?AVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+105*8]
?dot3@hkVector4f@@QEBA?AVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::setZero4();
?setZero4@hkVector4f@@QEAAXXZ proc EXPORT
jmp function_pointers[_hkVector4f_base+106*8]
?setZero4@hkVector4f@@QEAAXXZ endp

; hkVector4f::setNeg3(const class hkVector4f &);
?setNeg3@hkVector4f@@QEAAXAEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+107*8]
?setNeg3@hkVector4f@@QEAAXAEBV1@@Z endp

; hkVector4f::normalize3();
?normalize3@hkVector4f@@QEAAXXZ proc EXPORT
jmp function_pointers[_hkVector4f_base+108*8]
?normalize3@hkVector4f@@QEAAXXZ endp

; hkVector4f::normalizeWithLength3();
?normalizeWithLength3@hkVector4f@@QEAA?AVhkSimdFloat32@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+109*8]
?normalizeWithLength3@hkVector4f@@QEAA?AVhkSimdFloat32@@XZ endp

; hkVector4f::length3();
?length3@hkVector4f@@QEBA?AVhkSimdFloat32@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+110*8]
?length3@hkVector4f@@QEBA?AVhkSimdFloat32@@XZ endp

; hkVector4f::lengthSquared3();
?lengthSquared3@hkVector4f@@QEBA?AVhkSimdFloat32@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+111*8]
?lengthSquared3@hkVector4f@@QEBA?AVhkSimdFloat32@@XZ endp

; hkVector4f::equals3(const class hkVector4f &, float);
?equals3@hkVector4f@@QEBAIAEBV1@M@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+112*8]
?equals3@hkVector4f@@QEBAIAEBV1@M@Z endp

; hkVector4f::distanceTo3(const class hkVector4f &);
?distanceTo3@hkVector4f@@QEBA?AVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+113*8]
?distanceTo3@hkVector4f@@QEBA?AVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::distanceToSquared3(const class hkVector4f &);
?distanceToSquared3@hkVector4f@@QEBA?AVhkSimdFloat32@@AEBV1@@Z proc EXPORT
jmp function_pointers[_hkVector4f_base+114*8]
?distanceToSquared3@hkVector4f@@QEBA?AVhkSimdFloat32@@AEBV1@@Z endp

; hkVector4f::isOk3();
?isOk3@hkVector4f@@QEBA?AVhkBool@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+115*8]
?isOk3@hkVector4f@@QEBA?AVhkBool@@XZ endp

; hkVector4f::isOk4();
?isOk4@hkVector4f@@QEBA?AVhkBool@@XZ proc EXPORT
jmp function_pointers[_hkVector4f_base+116*8]
?isOk4@hkVector4f@@QEBA?AVhkBool@@XZ endp
