
?_CONSTRUCTOR@ImportGameMenu@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ImportGameMenu@@QEAAPEAV1@XZ endp

; ImportGameMenu::ImportGameMenu();
??0ImportGameMenu@@QEAA@XZ proc EXPORT
jmp function_pointers[_ImportGameMenu_base+0*8]
??0ImportGameMenu@@QEAA@XZ endp

?_DESTRUCTOR@ImportGameMenu@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ImportGameMenu@@QEAAXXZ endp

; ImportGameMenu::~ImportGameMenu();
??1ImportGameMenu@@UEAA@XZ proc EXPORT
jmp function_pointers[_ImportGameMenu_base+1*8]
??1ImportGameMenu@@UEAA@XZ endp

; ImportGameMenu::importPress(class MyGUI::Widget *);
?importPress@ImportGameMenu@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ImportGameMenu_base+2*8]
?importPress@ImportGameMenu@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ImportGameMenu::toggleAdvancedOptions(class MyGUI::Widget *);
?toggleAdvancedOptions@ImportGameMenu@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ImportGameMenu_base+3*8]
?toggleAdvancedOptions@ImportGameMenu@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_select@ImportGameMenu@@QEAAXH@Z proc EXPORT
?_NV_select@ImportGameMenu@@QEAAXH@Z endp

; ImportGameMenu::select(int);
?select@ImportGameMenu@@UEAAXH@Z proc EXPORT
jmp function_pointers[_ImportGameMenu_base+4*8]
?select@ImportGameMenu@@UEAAXH@Z endp
