
?_CONSTRUCTOR@Command@InputHandler@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@Command@InputHandler@@QEAAPEAV12@AEBU12@@Z endp

; InputHandler::Command::Command(const struct InputHandler::Command &);
??0Command@InputHandler@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_InputHandler_Command_base+0*8]
??0Command@InputHandler@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@Command@InputHandler@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Command@InputHandler@@QEAAPEAV12@XZ endp

; InputHandler::Command::Command();
??0Command@InputHandler@@QEAA@XZ proc EXPORT
jmp function_pointers[_InputHandler_Command_base+1*8]
??0Command@InputHandler@@QEAA@XZ endp

?_DESTRUCTOR@Command@InputHandler@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Command@InputHandler@@QEAAXXZ endp

; InputHandler::Command::~Command();
??1Command@InputHandler@@QEAA@XZ proc EXPORT
jmp function_pointers[_InputHandler_Command_base+2*8]
??1Command@InputHandler@@QEAA@XZ endp

; InputHandler::Command::operator=(const struct InputHandler::Command &);
??4Command@InputHandler@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_InputHandler_Command_base+3*8]
??4Command@InputHandler@@QEAAAEAU01@AEBU01@@Z endp
