
; InstanceID::getModIndex();
?getModIndex@InstanceID@@QEBAHXZ proc EXPORT
jmp function_pointers[_InstanceID_base+0*8]
?getModIndex@InstanceID@@QEBAHXZ endp

; InstanceID::getModIndex(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getModIndex@InstanceID@@SAFAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+1*8]
?getModIndex@InstanceID@@SAFAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@InstanceID@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@InstanceID@@QEAAPEAV1@AEBV1@@Z endp

; InstanceID::InstanceID(const class InstanceID &);
??0InstanceID@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+2*8]
??0InstanceID@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@InstanceID@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVObjectInstance@GameData@@@Z proc EXPORT
?_CONSTRUCTOR@InstanceID@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVObjectInstance@GameData@@@Z endp

; InstanceID::InstanceID(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class GameData::ObjectInstance &);
??0InstanceID@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVObjectInstance@GameData@@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+3*8]
??0InstanceID@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVObjectInstance@GameData@@@Z endp

?_CONSTRUCTOR@InstanceID@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@InstanceID@@QEAAPEAV1@XZ endp

; InstanceID::InstanceID();
??0InstanceID@@QEAA@XZ proc EXPORT
jmp function_pointers[_InstanceID_base+4*8]
??0InstanceID@@QEAA@XZ endp

; InstanceID::assign(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?assign@InstanceID@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+5*8]
?assign@InstanceID@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InstanceID::clear();
?clear@InstanceID@@QEAAXXZ proc EXPORT
jmp function_pointers[_InstanceID_base+6*8]
?clear@InstanceID@@QEAAXXZ endp

; InstanceID::needsSaving(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?needsSaving@InstanceID@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+7*8]
?needsSaving@InstanceID@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InstanceID::notifyChange();
?notifyChange@InstanceID@@QEAAXXZ proc EXPORT
jmp function_pointers[_InstanceID_base+8*8]
?notifyChange@InstanceID@@QEAAXXZ endp

; InstanceID::hasChanges();
?hasChanges@InstanceID@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InstanceID_base+9*8]
?hasChanges@InstanceID@@QEBA_NXZ endp

; InstanceID::notifySaved(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?notifySaved@InstanceID@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+10*8]
?notifySaved@InstanceID@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InstanceID::empty();
?empty@InstanceID@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InstanceID_base+11*8]
?empty@InstanceID@@QEBA_NXZ endp

; InstanceID::operator==(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??8InstanceID@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+12*8]
??8InstanceID@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InstanceID::getBaseIndex();
?getBaseIndex@InstanceID@@QEBAHXZ proc EXPORT
jmp function_pointers[_InstanceID_base+13*8]
?getBaseIndex@InstanceID@@QEBAHXZ endp

?_DESTRUCTOR@InstanceID@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InstanceID@@QEAAXXZ endp

; InstanceID::~InstanceID();
??1InstanceID@@QEAA@XZ proc EXPORT
jmp function_pointers[_InstanceID_base+14*8]
??1InstanceID@@QEAA@XZ endp

; InstanceID::operator=(const class InstanceID &);
??4InstanceID@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_InstanceID_base+15*8]
??4InstanceID@@QEAAAEAV0@AEBV0@@Z endp
