
?_CONSTRUCTOR@InteriorModeButtonWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@InteriorModeButtonWindow@@QEAAPEAV1@XZ endp

; InteriorModeButtonWindow::InteriorModeButtonWindow();
??0InteriorModeButtonWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+0*8]
??0InteriorModeButtonWindow@@QEAA@XZ endp

?_DESTRUCTOR@InteriorModeButtonWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InteriorModeButtonWindow@@QEAAXXZ endp

; InteriorModeButtonWindow::~InteriorModeButtonWindow();
??1InteriorModeButtonWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+1*8]
??1InteriorModeButtonWindow@@UEAA@XZ endp

; InteriorModeButtonWindow::toggleInteriorMode();
?toggleInteriorMode@InteriorModeButtonWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+2*8]
?toggleInteriorMode@InteriorModeButtonWindow@@QEAAXXZ endp

; InteriorModeButtonWindow::setVisible(bool);
?setVisible@InteriorModeButtonWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+3*8]
?setVisible@InteriorModeButtonWindow@@QEAAX_N@Z endp

; InteriorModeButtonWindow::wantExteriorsInvisible();
?wantExteriorsInvisible@InteriorModeButtonWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+4*8]
?wantExteriorsInvisible@InteriorModeButtonWindow@@QEBA_NXZ endp

; InteriorModeButtonWindow::setSelectedBuilding(class Building *);
?setSelectedBuilding@InteriorModeButtonWindow@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+5*8]
?setSelectedBuilding@InteriorModeButtonWindow@@QEAAXPEAVBuilding@@@Z endp

; InteriorModeButtonWindow::getSelectedBuilding();
?getSelectedBuilding@InteriorModeButtonWindow@@QEAAPEAVBuilding@@XZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+6*8]
?getSelectedBuilding@InteriorModeButtonWindow@@QEAAPEAVBuilding@@XZ endp

; InteriorModeButtonWindow::updateUsageNodes();
?updateUsageNodes@InteriorModeButtonWindow@@QEAA_NXZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+7*8]
?updateUsageNodes@InteriorModeButtonWindow@@QEAA_NXZ endp

; InteriorModeButtonWindow::refresh();
?refresh@InteriorModeButtonWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+8*8]
?refresh@InteriorModeButtonWindow@@QEAAXXZ endp

; InteriorModeButtonWindow::activateInteriorMode(bool);
?activateInteriorMode@InteriorModeButtonWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+9*8]
?activateInteriorMode@InteriorModeButtonWindow@@QEAAX_N@Z endp

; InteriorModeButtonWindow::closeWindow(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeWindow@InteriorModeButtonWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+10*8]
?closeWindow@InteriorModeButtonWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InteriorModeButtonWindow::toggleVisButtonPressed(class MyGUI::Widget *);
?toggleVisButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+11*8]
?toggleVisButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::interiorModePressed(class MyGUI::Widget *);
?interiorModePressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+12*8]
?interiorModePressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::interiorModeButtonUpdate(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?interiorModeButtonUpdate@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+13*8]
?interiorModeButtonUpdate@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; InteriorModeButtonWindow::interiorModeButtonUpdate2(class MyGUI::Widget *, class MyGUI::Widget *);
?interiorModeButtonUpdate2@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@0@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+14*8]
?interiorModeButtonUpdate2@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@0@Z endp

; InteriorModeButtonWindow::notifyEditTextChange(class MyGUI::EditBox *);
?notifyEditTextChange@InteriorModeButtonWindow@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+15*8]
?notifyEditTextChange@InteriorModeButtonWindow@@QEAAXPEAVEditBox@MyGUI@@@Z endp

; InteriorModeButtonWindow::centerButtonPressed(class MyGUI::Widget *);
?centerButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+16*8]
?centerButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::saveButtonPressed(class MyGUI::Widget *);
?saveButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+17*8]
?saveButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::deleteButtonPressed(class MyGUI::Widget *);
?deleteButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+18*8]
?deleteButtonPressed@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::clearNodes(class MyGUI::Widget *);
?clearNodes@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+19*8]
?clearNodes@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::clearAll(class MyGUI::Widget *);
?clearAll@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+20*8]
?clearAll@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::listItemSelected(class MyGUI::ListBox *, unsigned __int64);
?listItemSelected@InteriorModeButtonWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+21*8]
?listItemSelected@InteriorModeButtonWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; InteriorModeButtonWindow::confirmDeleteInteriorLayout(int);
?confirmDeleteInteriorLayout@InteriorModeButtonWindow@@QEAAXH@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+22*8]
?confirmDeleteInteriorLayout@InteriorModeButtonWindow@@QEAAXH@Z endp

; InteriorModeButtonWindow::confirmDeleteExteriorLayout(int);
?confirmDeleteExteriorLayout@InteriorModeButtonWindow@@QEAAXH@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+23*8]
?confirmDeleteExteriorLayout@InteriorModeButtonWindow@@QEAAXH@Z endp

; InteriorModeButtonWindow::saveButtonPressed2(class MyGUI::Widget *);
?saveButtonPressed2@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+24*8]
?saveButtonPressed2@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::deleteButtonPressed2(class MyGUI::Widget *);
?deleteButtonPressed2@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+25*8]
?deleteButtonPressed2@InteriorModeButtonWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InteriorModeButtonWindow::listItemSelected2(class MyGUI::ListBox *, unsigned __int64);
?listItemSelected2@InteriorModeButtonWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+26*8]
?listItemSelected2@InteriorModeButtonWindow@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; InteriorModeButtonWindow::notifyEditTextChange2(class MyGUI::EditBox *);
?notifyEditTextChange2@InteriorModeButtonWindow@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+27*8]
?notifyEditTextChange2@InteriorModeButtonWindow@@QEAAXPEAVEditBox@MyGUI@@@Z endp

; InteriorModeButtonWindow::setInteriorLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setInteriorLayout@InteriorModeButtonWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+28*8]
?setInteriorLayout@InteriorModeButtonWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InteriorModeButtonWindow::setExteriorLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setExteriorLayout@InteriorModeButtonWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+29*8]
?setExteriorLayout@InteriorModeButtonWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InteriorModeButtonWindow::recheckOutsideFurniture(class Building *);
?recheckOutsideFurniture@InteriorModeButtonWindow@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+30*8]
?recheckOutsideFurniture@InteriorModeButtonWindow@@QEAAXPEAVBuilding@@@Z endp

; InteriorModeButtonWindow::wasTheInteriorLoadedFromASave(class BuildingInterior *);
?wasTheInteriorLoadedFromASave@InteriorModeButtonWindow@@SA_NPEAVBuildingInterior@@@Z proc EXPORT
jmp function_pointers[_InteriorModeButtonWindow_base+31*8]
?wasTheInteriorLoadedFromASave@InteriorModeButtonWindow@@SA_NPEAVBuildingInterior@@@Z endp
