
?_CONSTRUCTOR@TradeResult@InventoryGUI@@QEAAPEAV12@W4Enum@12@@Z proc EXPORT
?_CONSTRUCTOR@TradeResult@InventoryGUI@@QEAAPEAV12@W4Enum@12@@Z endp

; InventoryGUI::TradeResult::TradeResult(enum InventoryGUI::TradeResult::Enum);
??0TradeResult@InventoryGUI@@QEAA@W4Enum@01@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_TradeResult_base+0*8]
??0TradeResult@InventoryGUI@@QEAA@W4Enum@01@@Z endp

; InventoryGUI::TradeResult::operator==(const class InventoryGUI::TradeResult &);
??8TradeResult@InventoryGUI@@QEBA_NAEBV01@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_TradeResult_base+1*8]
??8TradeResult@InventoryGUI@@QEBA_NAEBV01@@Z endp

; InventoryGUI::TradeResult::operator!=(const class InventoryGUI::TradeResult &);
??9TradeResult@InventoryGUI@@QEBA_NAEBV01@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_TradeResult_base+2*8]
??9TradeResult@InventoryGUI@@QEBA_NAEBV01@@Z endp

; InventoryGUI::TradeResult::showMessage();
?showMessage@TradeResult@InventoryGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_TradeResult_base+3*8]
?showMessage@TradeResult@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::TradeResult::ShowMessage(enum InventoryGUI::TradeResult::Enum);
?ShowMessage@TradeResult@InventoryGUI@@SAXW4Enum@12@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_TradeResult_base+4*8]
?ShowMessage@TradeResult@InventoryGUI@@SAXW4Enum@12@@Z endp
