
; Inventory::HasRoomCache::modified();
?modified@HasRoomCache@Inventory@@QEAAXXZ proc EXPORT
jmp function_pointers[_Inventory_HasRoomCache_base+0*8]
?modified@HasRoomCache@Inventory@@QEAAXXZ endp

; Inventory::HasRoomCache::knowsAbout(class GameData *);
?knowsAbout@HasRoomCache@Inventory@@QEBA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Inventory_HasRoomCache_base+1*8]
?knowsAbout@HasRoomCache@Inventory@@QEBA_NPEAVGameData@@@Z endp

; Inventory::HasRoomCache::hasRoomFor(class GameData *);
?hasRoomFor@HasRoomCache@Inventory@@QEBA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Inventory_HasRoomCache_base+2*8]
?hasRoomFor@HasRoomCache@Inventory@@QEBA_NPEAVGameData@@@Z endp

; Inventory::HasRoomCache::remember(class GameData *, bool);
?remember@HasRoomCache@Inventory@@QEAAXPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_Inventory_HasRoomCache_base+3*8]
?remember@HasRoomCache@Inventory@@QEAAXPEAVGameData@@_N@Z endp

?_CONSTRUCTOR@HasRoomCache@Inventory@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@HasRoomCache@Inventory@@QEAAPEAV12@XZ endp

; Inventory::HasRoomCache::HasRoomCache();
??0HasRoomCache@Inventory@@QEAA@XZ proc EXPORT
jmp function_pointers[_Inventory_HasRoomCache_base+4*8]
??0HasRoomCache@Inventory@@QEAA@XZ endp

?_DESTRUCTOR@HasRoomCache@Inventory@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@HasRoomCache@Inventory@@QEAAXXZ endp

; Inventory::HasRoomCache::~HasRoomCache();
??1HasRoomCache@Inventory@@QEAA@XZ proc EXPORT
jmp function_pointers[_Inventory_HasRoomCache_base+5*8]
??1HasRoomCache@Inventory@@QEAA@XZ endp
