
?_CONSTRUCTOR@InventorySectionGUI@@QEAAPEAV1@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@InventorySectionGUI@@QEAAPEAV1@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventorySectionGUI::InventorySectionGUI(class MyGUI::Widget *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0InventorySectionGUI@@QEAA@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+0*8]
??0InventorySectionGUI@@QEAA@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@InventorySectionGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InventorySectionGUI@@QEAAXXZ endp

; InventorySectionGUI::~InventorySectionGUI();
??1InventorySectionGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+1*8]
??1InventorySectionGUI@@QEAA@XZ endp

; InventorySectionGUI::hasMouse();
?hasMouse@InventorySectionGUI@@QEAA_NXZ proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+2*8]
?hasMouse@InventorySectionGUI@@QEAA_NXZ endp

; InventorySectionGUI::getItemAbsolutePosition(int, int);
?getItemAbsolutePosition@InventorySectionGUI@@QEAA?AU?$TPoint@H@types@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+3*8]
?getItemAbsolutePosition@InventorySectionGUI@@QEAA?AU?$TPoint@H@types@MyGUI@@HH@Z endp

; InventorySectionGUI::getWidget();
?getWidget@InventorySectionGUI@@QEAAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+4*8]
?getWidget@InventorySectionGUI@@QEAAPEAVWidget@MyGUI@@XZ endp

; InventorySectionGUI::getPositionSlot(const struct MyGUI::types::TPoint<int> &, class InventorySection *, bool);
?getPositionSlot@InventorySectionGUI@@QEAA?AU?$TPoint@H@types@MyGUI@@AEBU234@PEAVInventorySection@@_N@Z proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+5*8]
?getPositionSlot@InventorySectionGUI@@QEAA?AU?$TPoint@H@types@MyGUI@@AEBU234@PEAVInventorySection@@_N@Z endp

; InventorySectionGUI::getBestPositionSlot(const struct MyGUI::types::TPoint<int> &, class InventorySection *, class Item *, struct MyGUI::types::TPoint<int> &);
?getBestPositionSlot@InventorySectionGUI@@QEAA_NAEBU?$TPoint@H@types@MyGUI@@PEAVInventorySection@@PEAVItem@@AEAU234@@Z proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+6*8]
?getBestPositionSlot@InventorySectionGUI@@QEAA_NAEBU?$TPoint@H@types@MyGUI@@PEAVInventorySection@@PEAVItem@@AEAU234@@Z endp

; InventorySectionGUI::setEnabled(bool);
?setEnabled@InventorySectionGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+7*8]
?setEnabled@InventorySectionGUI@@QEAAX_N@Z endp

; InventorySectionGUI::refreshIcons(class InventorySection *);
?refreshIcons@InventorySectionGUI@@QEAAXPEAVInventorySection@@@Z proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+8*8]
?refreshIcons@InventorySectionGUI@@QEAAXPEAVInventorySection@@@Z endp

; InventorySectionGUI::update();
?update@InventorySectionGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventorySectionGUI_base+9*8]
?update@InventorySectionGUI@@QEAAXXZ endp
