
?_CONSTRUCTOR@InventoryIcon@@QEAAPEAV1@PEAVItem@@AEBU?$TPoint@H@types@MyGUI@@PEAVWidget@5@@Z proc EXPORT
?_CONSTRUCTOR@InventoryIcon@@QEAAPEAV1@PEAVItem@@AEBU?$TPoint@H@types@MyGUI@@PEAVWidget@5@@Z endp

; InventoryIcon::InventoryIcon(class Item *, const struct MyGUI::types::TPoint<int> &, class MyGUI::Widget *);
??0InventoryIcon@@QEAA@PEAVItem@@AEBU?$TPoint@H@types@MyGUI@@PEAVWidget@4@@Z proc EXPORT
jmp function_pointers[_InventoryIcon_base+0*8]
??0InventoryIcon@@QEAA@PEAVItem@@AEBU?$TPoint@H@types@MyGUI@@PEAVWidget@4@@Z endp

; InventoryIcon::setPosition(const struct MyGUI::types::TPoint<int> &);
?setPosition@InventoryIcon@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryIcon_base+1*8]
?setPosition@InventoryIcon@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; InventoryIcon::getSize();
?getSize@InventoryIcon@@QEBA?AU?$TSize@H@types@MyGUI@@XZ proc EXPORT
jmp function_pointers[_InventoryIcon_base+2*8]
?getSize@InventoryIcon@@QEBA?AU?$TSize@H@types@MyGUI@@XZ endp

; InventoryIcon::update();
?update@InventoryIcon@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryIcon_base+3*8]
?update@InventoryIcon@@QEAAXXZ endp

; InventoryIcon::getWidget();
?getWidget@InventoryIcon@@QEBAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_InventoryIcon_base+4*8]
?getWidget@InventoryIcon@@QEBAPEAVWidget@MyGUI@@XZ endp

; InventoryIcon::createIconImage(class Item *, class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class iVector2 &);
?createIconImage@InventoryIcon@@SAXPEAVItem@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAViVector2@@@Z proc EXPORT
jmp function_pointers[_InventoryIcon_base+5*8]
?createIconImage@InventoryIcon@@SAXPEAVItem@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAViVector2@@@Z endp

; InventoryIcon::getItemSize(class GameData *);
?getItemSize@InventoryIcon@@SA?AU?$TSize@H@types@MyGUI@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_InventoryIcon_base+6*8]
?getItemSize@InventoryIcon@@SA?AU?$TSize@H@types@MyGUI@@PEAVGameData@@@Z endp

; InventoryIcon::getItemPosition(int, int);
?getItemPosition@InventoryIcon@@SA?AU?$TPoint@H@types@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_InventoryIcon_base+7*8]
?getItemPosition@InventoryIcon@@SA?AU?$TPoint@H@types@MyGUI@@HH@Z endp

?_DESTRUCTOR@InventoryIcon@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InventoryIcon@@QEAAXXZ endp

; InventoryIcon::~InventoryIcon();
??1InventoryIcon@@UEAA@XZ proc EXPORT
jmp function_pointers[_InventoryIcon_base+8*8]
??1InventoryIcon@@UEAA@XZ endp
