
?_CONSTRUCTOR@InventoryTraderGUI@@QEAAPEAV1@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z proc EXPORT
?_CONSTRUCTOR@InventoryTraderGUI@@QEAAPEAV1@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z endp

; InventoryTraderGUI::InventoryTraderGUI(class Inventory *, class InventoryLayout *, class RootObject *);
??0InventoryTraderGUI@@QEAA@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_InventoryTraderGUI_base+0*8]
??0InventoryTraderGUI@@QEAA@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z endp

?_DESTRUCTOR@InventoryTraderGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InventoryTraderGUI@@QEAAXXZ endp

; InventoryTraderGUI::~InventoryTraderGUI();
??1InventoryTraderGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_InventoryTraderGUI_base+1*8]
??1InventoryTraderGUI@@UEAA@XZ endp

?_NV_getInventory@InventoryTraderGUI@@QEAAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@InventoryTraderGUI@@QEAAPEAVInventory@@XZ endp

; InventoryTraderGUI::getInventory();
?getInventory@InventoryTraderGUI@@UEAAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_InventoryTraderGUI_base+2*8]
?getInventory@InventoryTraderGUI@@UEAAPEAVInventory@@XZ endp

?_NV_getCallbackCharacter@InventoryTraderGUI@@QEAAPEAVCharacter@@XZ proc EXPORT
?_NV_getCallbackCharacter@InventoryTraderGUI@@QEAAPEAVCharacter@@XZ endp

; InventoryTraderGUI::getCallbackCharacter();
?getCallbackCharacter@InventoryTraderGUI@@UEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_InventoryTraderGUI_base+3*8]
?getCallbackCharacter@InventoryTraderGUI@@UEAAPEAVCharacter@@XZ endp

?_NV_getCallbackObject@InventoryTraderGUI@@QEBAPEAVRootObject@@XZ proc EXPORT
?_NV_getCallbackObject@InventoryTraderGUI@@QEBAPEAVRootObject@@XZ endp

; InventoryTraderGUI::getCallbackObject();
?getCallbackObject@InventoryTraderGUI@@UEBAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_InventoryTraderGUI_base+4*8]
?getCallbackObject@InventoryTraderGUI@@UEBAPEAVRootObject@@XZ endp

?_NV_refreshSection@InventoryTraderGUI@@QEAAXPEAVInventorySection@@@Z proc EXPORT
?_NV_refreshSection@InventoryTraderGUI@@QEAAXPEAVInventorySection@@@Z endp

; InventoryTraderGUI::refreshSection(class InventorySection *);
?refreshSection@InventoryTraderGUI@@UEAAXPEAVInventorySection@@@Z proc EXPORT
jmp function_pointers[_InventoryTraderGUI_base+5*8]
?refreshSection@InventoryTraderGUI@@UEAAXPEAVInventorySection@@@Z endp
