
?_CONSTRUCTOR@InventoryTradeData@InventoryGUI@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@InventoryTradeData@InventoryGUI@@QEAAPEAV12@AEBV12@@Z endp

; InventoryGUI::InventoryTradeData::InventoryTradeData(const class InventoryGUI::InventoryTradeData &);
??0InventoryTradeData@InventoryGUI@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_InventoryTradeData_base+0*8]
??0InventoryTradeData@InventoryGUI@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@InventoryTradeData@InventoryGUI@@QEAAPEAV12@PEAV2@_N11AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@InventoryTradeData@InventoryGUI@@QEAAPEAV12@PEAV2@_N11AEBVhand@@@Z endp

; InventoryGUI::InventoryTradeData::InventoryTradeData(class InventoryGUI *, bool, bool, bool, const class hand &);
??0InventoryTradeData@InventoryGUI@@QEAA@PEAV1@_N11AEBVhand@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_InventoryTradeData_base+1*8]
??0InventoryTradeData@InventoryGUI@@QEAA@PEAV1@_N11AEBVhand@@@Z endp

?_CONSTRUCTOR@InventoryTradeData@InventoryGUI@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@InventoryTradeData@InventoryGUI@@QEAAPEAV12@XZ endp

; InventoryGUI::InventoryTradeData::InventoryTradeData();
??0InventoryTradeData@InventoryGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_InventoryTradeData_base+2*8]
??0InventoryTradeData@InventoryGUI@@QEAA@XZ endp

; InventoryGUI::InventoryTradeData::isValid();
?isValid@InventoryTradeData@InventoryGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InventoryGUI_InventoryTradeData_base+3*8]
?isValid@InventoryTradeData@InventoryGUI@@QEBA_NXZ endp

; InventoryGUI::InventoryTradeData::operator=(const class InventoryGUI::InventoryTradeData &);
??4InventoryTradeData@InventoryGUI@@QEAAAEAV01@AEBV01@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_InventoryTradeData_base+4*8]
??4InventoryTradeData@InventoryGUI@@QEAAAEAV01@AEBV01@@Z endp
