
?_CONSTRUCTOR@FenceCallbackData@InventoryGUI@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@FenceCallbackData@InventoryGUI@@QEAAPEAV12@XZ endp

; InventoryGUI::FenceCallbackData::FenceCallbackData();
??0FenceCallbackData@InventoryGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_FenceCallbackData_base+0*8]
??0FenceCallbackData@InventoryGUI@@QEAA@XZ endp

?_DESTRUCTOR@FenceCallbackData@InventoryGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FenceCallbackData@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::FenceCallbackData::~FenceCallbackData();
??1FenceCallbackData@InventoryGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_FenceCallbackData_base+1*8]
??1FenceCallbackData@InventoryGUI@@QEAA@XZ endp
