
?_CONSTRUCTOR@InventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@InventoryLayout@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventoryLayout::InventoryLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0InventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+0*8]
??0InventoryLayout@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@InventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InventoryLayout@@QEAAXXZ endp

; InventoryLayout::~InventoryLayout();
??1InventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_InventoryLayout_base+1*8]
??1InventoryLayout@@UEAA@XZ endp

; InventoryLayout::getWindow();
?getWindow@InventoryLayout@@QEBAPEAVWindow@MyGUI@@XZ proc EXPORT
jmp function_pointers[_InventoryLayout_base+2*8]
?getWindow@InventoryLayout@@QEBAPEAVWindow@MyGUI@@XZ endp

; InventoryLayout::getWidget(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getWidget@InventoryLayout@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+3*8]
?getWidget@InventoryLayout@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getDatapanel@InventoryLayout@@QEBAPEAVDatapanelGUI@@XZ proc EXPORT
?_NV_getDatapanel@InventoryLayout@@QEBAPEAVDatapanelGUI@@XZ endp

; InventoryLayout::getDatapanel();
?getDatapanel@InventoryLayout@@UEBAPEAVDatapanelGUI@@XZ proc EXPORT
jmp function_pointers[_InventoryLayout_base+4*8]
?getDatapanel@InventoryLayout@@UEBAPEAVDatapanelGUI@@XZ endp

; InventoryLayout::setupDataPanelInfos(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setupDataPanelInfos@InventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+5*8]
?setupDataPanelInfos@InventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventoryLayout::notifyCellSizeChanged();
?notifyCellSizeChanged@InventoryLayout@@SAXXZ proc EXPORT
jmp function_pointers[_InventoryLayout_base+6*8]
?notifyCellSizeChanged@InventoryLayout@@SAXXZ endp

; InventoryLayout::createSectionGUI(class InventorySection *);
?createSectionGUI@InventoryLayout@@QEAAPEAVInventorySectionGUI@@PEAVInventorySection@@@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+7*8]
?createSectionGUI@InventoryLayout@@QEAAPEAVInventorySectionGUI@@PEAVInventorySection@@@Z endp

; InventoryLayout::setSectionGUIDisabled(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int);
?setSectionGUIDisabled@InventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+8*8]
?setSectionGUIDisabled@InventoryLayout@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HH@Z endp

; InventoryLayout::resizeSection(class InventorySection *, class InventorySectionGUI *);
?resizeSection@InventoryLayout@@QEAA?AU?$TSize@H@types@MyGUI@@PEAVInventorySection@@PEAVInventorySectionGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+9*8]
?resizeSection@InventoryLayout@@QEAA?AU?$TSize@H@types@MyGUI@@PEAVInventorySection@@PEAVInventorySectionGUI@@@Z endp

; InventoryLayout::resizeSectionWidget(int, int, class MyGUI::Widget *);
?resizeSectionWidget@InventoryLayout@@QEAA?AU?$TSize@H@types@MyGUI@@HHPEAVWidget@4@@Z proc EXPORT
jmp function_pointers[_InventoryLayout_base+10*8]
?resizeSectionWidget@InventoryLayout@@QEAA?AU?$TSize@H@types@MyGUI@@HHPEAVWidget@4@@Z endp
