
; InventoryGUI::lockedItemCheck(class LockedArmour *);
?lockedItemCheck@InventoryGUI@@SA_NPEAVLockedArmour@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+0*8]
?lockedItemCheck@InventoryGUI@@SA_NPEAVLockedArmour@@@Z endp

; InventoryGUI::setTradingTown(const class hand &);
?setTradingTown@InventoryGUI@@SAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+1*8]
?setTradingTown@InventoryGUI@@SAXAEBVhand@@@Z endp

; InventoryGUI::getTradingTown();
?getTradingTown@InventoryGUI@@SAPEAVTown@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+2*8]
?getTradingTown@InventoryGUI@@SAPEAVTown@@XZ endp

; InventoryGUI::addTradePartner(class InventoryGUI *, bool, bool, bool, const class hand &);
?addTradePartner@InventoryGUI@@SAXPEAV1@_N11AEBVhand@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+3*8]
?addTradePartner@InventoryGUI@@SAXPEAV1@_N11AEBVhand@@@Z endp

; InventoryGUI::removeTradePartner(class InventoryGUI *);
?removeTradePartner@InventoryGUI@@SAXPEAV1@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+4*8]
?removeTradePartner@InventoryGUI@@SAXPEAV1@@Z endp

; InventoryGUI::clearTradePartners();
?clearTradePartners@InventoryGUI@@SAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+5*8]
?clearTradePartners@InventoryGUI@@SAXXZ endp

; InventoryGUI::canDropMouseItemWithoutPaying(class InventoryGUI *);
?canDropMouseItemWithoutPaying@InventoryGUI@@SA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+6*8]
?canDropMouseItemWithoutPaying@InventoryGUI@@SA_NPEAV1@@Z endp

?_NV_autoChangeSelectedObject@InventoryGUI@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_autoChangeSelectedObject@InventoryGUI@@QEAAXAEBVhand@@@Z endp

; InventoryGUI::autoChangeSelectedObject(const class hand &);
?autoChangeSelectedObject@InventoryGUI@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+7*8]
?autoChangeSelectedObject@InventoryGUI@@UEAAXAEBVhand@@@Z endp

?_NV_update@InventoryGUI@@QEAAXXZ proc EXPORT
?_NV_update@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::update();
?update@InventoryGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+8*8]
?update@InventoryGUI@@UEAAXXZ endp

?_NV_show@InventoryGUI@@QEAAX_N@Z proc EXPORT
?_NV_show@InventoryGUI@@QEAAX_N@Z endp

; InventoryGUI::show(bool);
?show@InventoryGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+9*8]
?show@InventoryGUI@@UEAAX_N@Z endp

?_NV_setPositionReal@InventoryGUI@@QEAAXMM@Z proc EXPORT
?_NV_setPositionReal@InventoryGUI@@QEAAXMM@Z endp

; InventoryGUI::setPositionReal(float, float);
?setPositionReal@InventoryGUI@@UEAAXMM@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+10*8]
?setPositionReal@InventoryGUI@@UEAAXMM@Z endp

?_NV_isVisible@InventoryGUI@@QEBA_NXZ proc EXPORT
?_NV_isVisible@InventoryGUI@@QEBA_NXZ endp

; InventoryGUI::isVisible();
?isVisible@InventoryGUI@@UEBA_NXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+11*8]
?isVisible@InventoryGUI@@UEBA_NXZ endp

?_NV_refreshSection@InventoryGUI@@QEAAXPEAVInventorySection@@@Z proc EXPORT
?_NV_refreshSection@InventoryGUI@@QEAAXPEAVInventorySection@@@Z endp

; InventoryGUI::refreshSection(class InventorySection *);
?refreshSection@InventoryGUI@@UEAAXPEAVInventorySection@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+12*8]
?refreshSection@InventoryGUI@@UEAAXPEAVInventorySection@@@Z endp

; InventoryGUI::refreshSection();
?refreshSection@InventoryGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+13*8]
?refreshSection@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::autoArrangeButton(class MyGUI::Widget *);
?autoArrangeButton@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+14*8]
?autoArrangeButton@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InventoryGUI::openBackpackButton(class MyGUI::Widget *);
?openBackpackButton@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+15*8]
?openBackpackButton@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InventoryGUI::openLimbsInterface(class MyGUI::Widget *);
?openLimbsInterface@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+16*8]
?openLimbsInterface@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; InventoryGUI::showBackpack(bool);
?showBackpack@InventoryGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+17*8]
?showBackpack@InventoryGUI@@QEAAX_N@Z endp

; InventoryGUI::getBackpack();
?getBackpack@InventoryGUI@@QEAAPEAVContainerItem@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+18*8]
?getBackpack@InventoryGUI@@QEAAPEAVContainerItem@@XZ endp

; InventoryGUI::windowButtonPressed(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?windowButtonPressed@InventoryGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+19*8]
?windowButtonPressed@InventoryGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getInventory@InventoryGUI@@QEAAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@InventoryGUI@@QEAAPEAVInventory@@XZ endp

; InventoryGUI::getInventory();
?getInventory@InventoryGUI@@UEAAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+20*8]
?getInventory@InventoryGUI@@UEAAPEAVInventory@@XZ endp

; InventoryGUI::hasSameOwner(const class InventoryGUI *);
?hasSameOwner@InventoryGUI@@QEBA_NPEBV1@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+21*8]
?hasSameOwner@InventoryGUI@@QEBA_NPEBV1@@Z endp

?_NV_getCallbackCharacter@InventoryGUI@@QEAAPEAVCharacter@@XZ proc EXPORT
?_NV_getCallbackCharacter@InventoryGUI@@QEAAPEAVCharacter@@XZ endp

; InventoryGUI::getCallbackCharacter();
?getCallbackCharacter@InventoryGUI@@UEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+22*8]
?getCallbackCharacter@InventoryGUI@@UEAAPEAVCharacter@@XZ endp

?_NV_getCallbackObject@InventoryGUI@@QEBAPEAVRootObject@@XZ proc EXPORT
?_NV_getCallbackObject@InventoryGUI@@QEBAPEAVRootObject@@XZ endp

; InventoryGUI::getCallbackObject();
?getCallbackObject@InventoryGUI@@UEBAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+23*8]
?getCallbackObject@InventoryGUI@@UEBAPEAVRootObject@@XZ endp

; InventoryGUI::getSelectedItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getSelectedItem@InventoryGUI@@QEAAPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+24*8]
?getSelectedItem@InventoryGUI@@QEAAPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventoryGUI::getWindowCoord();
?getWindowCoord@InventoryGUI@@QEAA?AU?$TCoord@H@types@MyGUI@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+25*8]
?getWindowCoord@InventoryGUI@@QEAA?AU?$TCoord@H@types@MyGUI@@XZ endp

; InventoryGUI::stealingGUIInfoUpdate();
?stealingGUIInfoUpdate@InventoryGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+26*8]
?stealingGUIInfoUpdate@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::getTrader1Trader2(class InventoryGUI * &, class InventoryGUI * &);
?getTrader1Trader2@InventoryGUI@@QEAAXAEAPEAV1@0@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+27*8]
?getTrader1Trader2@InventoryGUI@@QEAAXAEAPEAV1@0@Z endp

; InventoryGUI::getNPCTrader();
?getNPCTrader@InventoryGUI@@SAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+28*8]
?getNPCTrader@InventoryGUI@@SAPEAVCharacter@@XZ endp

; InventoryGUI::isTradingForMoney_static();
?isTradingForMoney_static@InventoryGUI@@SAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+29*8]
?isTradingForMoney_static@InventoryGUI@@SAPEAVRootObject@@XZ endp

; InventoryGUI::isTradingAndStealing_static();
?isTradingAndStealing_static@InventoryGUI@@SAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+30*8]
?isTradingAndStealing_static@InventoryGUI@@SAPEAVRootObject@@XZ endp

; InventoryGUI::getTraderPriceMultiplier();
?getTraderPriceMultiplier@InventoryGUI@@SAMXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+31*8]
?getTraderPriceMultiplier@InventoryGUI@@SAMXZ endp

?_CONSTRUCTOR@InventoryGUI@@QEAAPEAV1@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z proc EXPORT
?_CONSTRUCTOR@InventoryGUI@@QEAAPEAV1@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z endp

; InventoryGUI::InventoryGUI(class Inventory *, class InventoryLayout *, class RootObject *);
??0InventoryGUI@@QEAA@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+32*8]
??0InventoryGUI@@QEAA@PEAVInventory@@PEAVInventoryLayout@@PEAVRootObject@@@Z endp

?_DESTRUCTOR@InventoryGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::~InventoryGUI();
??1InventoryGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+33*8]
??1InventoryGUI@@UEAA@XZ endp

; InventoryGUI::pickupItemToMouse(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?pickupItemToMouse@InventoryGUI@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+34*8]
?pickupItemToMouse@InventoryGUI@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventoryGUI::placeItemFromMouse(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> >, const struct MyGUI::types::TPoint<int> &);
?placeItemFromMouse@InventoryGUI@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+35*8]
?placeItemFromMouse@InventoryGUI@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBU?$TPoint@H@types@MyGUI@@@Z endp

; InventoryGUI::getMouseItem();
?getMouseItem@InventoryGUI@@QEAAPEAVItem@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+36*8]
?getMouseItem@InventoryGUI@@QEAAPEAVItem@@XZ endp

; InventoryGUI::takeCertainAmountFrom(class Item *, int);
?takeCertainAmountFrom@InventoryGUI@@QEAAPEAVItem@@PEAV2@H@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+37*8]
?takeCertainAmountFrom@InventoryGUI@@QEAAPEAVItem@@PEAV2@H@Z endp

; InventoryGUI::RClickAutoTrade(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, class InventoryGUI *, bool, bool);
?RClickAutoTrade@InventoryGUI@@QEAA?AVTradeResult@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAV1@_N2@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+38*8]
?RClickAutoTrade@InventoryGUI@@QEAA?AVTradeResult@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAV1@_N2@Z endp

; InventoryGUI::RClickAutoTradeAll(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, class InventoryGUI *, bool, bool);
?RClickAutoTradeAll@InventoryGUI@@QEAA?AVTradeResult@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAV1@_N2@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+39*8]
?RClickAutoTradeAll@InventoryGUI@@QEAA?AVTradeResult@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAV1@_N2@Z endp

; InventoryGUI::isTradingForMoney(class InventoryGUI *);
?isTradingForMoney@InventoryGUI@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+40*8]
?isTradingForMoney@InventoryGUI@@QEAA_NPEAV1@@Z endp

; InventoryGUI::isStealing(class InventoryGUI *);
?isStealing@InventoryGUI@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+41*8]
?isStealing@InventoryGUI@@QEAA_NPEAV1@@Z endp

; InventoryGUI::isWithinRangeToTrade(class RootObject *, bool);
?isWithinRangeToTrade@InventoryGUI@@QEAA_NPEAVRootObject@@_N@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+42*8]
?isWithinRangeToTrade@InventoryGUI@@QEAA_NPEAVRootObject@@_N@Z endp

; InventoryGUI::setItemToPlayerPortrait(class Item *, class Character *);
?setItemToPlayerPortrait@InventoryGUI@@QEAA_NPEAVItem@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+43*8]
?setItemToPlayerPortrait@InventoryGUI@@QEAA_NPEAVItem@@PEAVCharacter@@@Z endp

; InventoryGUI::playSound(const char *, class Item *);
?playSound@InventoryGUI@@QEAAXPEBDPEAVItem@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+44*8]
?playSound@InventoryGUI@@QEAAXPEBDPEAVItem@@@Z endp

; InventoryGUI::fencingConfirmation(class Item *, class RootObject *, class Character *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, struct MyGUI::types::TPoint<int>);
?fencingConfirmation@InventoryGUI@@QEAA_NPEAVItem@@PEAVRootObject@@PEAVCharacter@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+45*8]
?fencingConfirmation@InventoryGUI@@QEAA_NPEAVItem@@PEAVRootObject@@PEAVCharacter@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$TPoint@H@types@MyGUI@@@Z endp

; InventoryGUI::fencingConfirmationCallback(int);
?fencingConfirmationCallback@InventoryGUI@@QEAAXH@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+46*8]
?fencingConfirmationCallback@InventoryGUI@@QEAAXH@Z endp

; InventoryGUI::getPlayerTradeCharacter();
?getPlayerTradeCharacter@InventoryGUI@@QEAAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+47*8]
?getPlayerTradeCharacter@InventoryGUI@@QEAAPEAVRootObject@@XZ endp

; InventoryGUI::refreshAllSections();
?refreshAllSections@InventoryGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+48*8]
?refreshAllSections@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::updateDatapanel();
?updateDatapanel@InventoryGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+49*8]
?updateDatapanel@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::rightClickAutoEquipping();
?rightClickAutoEquipping@InventoryGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+50*8]
?rightClickAutoEquipping@InventoryGUI@@QEAAXXZ endp

; InventoryGUI::tryToEquip(class Item *, bool);
?tryToEquip@InventoryGUI@@QEAA_NPEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+51*8]
?tryToEquip@InventoryGUI@@QEAA_NPEAVItem@@_N@Z endp

; InventoryGUI::returnItem(class Item *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?returnItem@InventoryGUI@@QEAAXPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+52*8]
?returnItem@InventoryGUI@@QEAAXPEAVItem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventoryGUI::getSection(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getSection@InventoryGUI@@QEAAPEAVInventorySection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+53*8]
?getSection@InventoryGUI@@QEAAPEAVInventorySection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; InventoryGUI::getSection(class InventorySectionGUI *);
?getSection@InventoryGUI@@QEAAPEAVInventorySection@@PEAVInventorySectionGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+54*8]
?getSection@InventoryGUI@@QEAAPEAVInventorySection@@PEAVInventorySectionGUI@@@Z endp

; InventoryGUI::hasMouse();
?hasMouse@InventoryGUI@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+55*8]
?hasMouse@InventoryGUI@@QEBA_NXZ endp

; InventoryGUI::getSectionWithMouseLocal();
?getSectionWithMouseLocal@InventoryGUI@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+56*8]
?getSectionWithMouseLocal@InventoryGUI@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; InventoryGUI::getSlotWithMouse();
?getSlotWithMouse@InventoryGUI@@QEAA?AViVector2@@XZ proc EXPORT
jmp function_pointers[_InventoryGUI_base+57*8]
?getSlotWithMouse@InventoryGUI@@QEAA?AViVector2@@XZ endp

; InventoryGUI::sectionMouseButtonPressed(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?sectionMouseButtonPressed@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+58*8]
?sectionMouseButtonPressed@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; InventoryGUI::sectionMouseButtonReleased(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?sectionMouseButtonReleased@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+59*8]
?sectionMouseButtonReleased@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; InventoryGUI::onWindowFocus(class MyGUI::Widget *, bool);
?onWindowFocus@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@_N@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+60*8]
?onWindowFocus@InventoryGUI@@QEAAXPEAVWidget@MyGUI@@_N@Z endp

; InventoryGUI::windowMoved(class MyGUI::Window *);
?windowMoved@InventoryGUI@@QEAAXPEAVWindow@MyGUI@@@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+61*8]
?windowMoved@InventoryGUI@@QEAAXPEAVWindow@MyGUI@@@Z endp

; InventoryGUI::makeIconForItem(class Item *, int, int);
?makeIconForItem@InventoryGUI@@SAPEAVInventoryIcon@@PEAVItem@@HH@Z proc EXPORT
jmp function_pointers[_InventoryGUI_base+62*8]
?makeIconForItem@InventoryGUI@@SAPEAVInventoryIcon@@PEAVItem@@HH@Z endp
