
; InventoryItemBase::resetCharges(bool);
?resetCharges@InventoryItemBase@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+0*8]
?resetCharges@InventoryItemBase@@QEAAX_N@Z endp

; InventoryItemBase::getStolenItemGUIInfo(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getStolenItemGUIInfo@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+1*8]
?getStolenItemGUIInfo@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; InventoryItemBase::getBuyBackGUIInfo(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getBuyBackGUIInfo@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+2*8]
?getBuyBackGUIInfo@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; InventoryItemBase::getItemType();
?getItemType@InventoryItemBase@@QEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+3*8]
?getItemType@InventoryItemBase@@QEBA?AW4itemType@@XZ endp

?_NV_getItemWeightSingle@InventoryItemBase@@QEBAMXZ proc EXPORT
?_NV_getItemWeightSingle@InventoryItemBase@@QEBAMXZ endp

; InventoryItemBase::getItemWeightSingle();
?getItemWeightSingle@InventoryItemBase@@UEBAMXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+4*8]
?getItemWeightSingle@InventoryItemBase@@UEBAMXZ endp

?_NV_getItemWeight@InventoryItemBase@@QEBAMXZ proc EXPORT
?_NV_getItemWeight@InventoryItemBase@@QEBAMXZ endp

; InventoryItemBase::getItemWeight();
?getItemWeight@InventoryItemBase@@UEBAMXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+5*8]
?getItemWeight@InventoryItemBase@@UEBAMXZ endp

?_NV_getTooltipData1@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; InventoryItemBase::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@InventoryItemBase@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+6*8]
?getTooltipData1@InventoryItemBase@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; InventoryItemBase::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@InventoryItemBase@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+7*8]
?getTooltipData2@InventoryItemBase@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getGUIData@InventoryItemBase@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@InventoryItemBase@@QEAAXPEAVDatapanelGUI@@H@Z endp

; InventoryItemBase::getGUIData(class DatapanelGUI *, int);
?getGUIData@InventoryItemBase@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+8*8]
?getGUIData@InventoryItemBase@@UEAAXPEAVDatapanelGUI@@H@Z endp

; InventoryItemBase::getAvgPrice();
?getAvgPrice@InventoryItemBase@@QEAAHXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+9*8]
?getAvgPrice@InventoryItemBase@@QEAAHXZ endp

?_NV_getValueSingle@InventoryItemBase@@QEBAH_N@Z proc EXPORT
?_NV_getValueSingle@InventoryItemBase@@QEBAH_N@Z endp

; InventoryItemBase::getValueSingle(bool);
?getValueSingle@InventoryItemBase@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+10*8]
?getValueSingle@InventoryItemBase@@UEBAH_N@Z endp

?_NV_getValueAll@InventoryItemBase@@QEBAH_N@Z proc EXPORT
?_NV_getValueAll@InventoryItemBase@@QEBAH_N@Z endp

; InventoryItemBase::getValueAll(bool);
?getValueAll@InventoryItemBase@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+11*8]
?getValueAll@InventoryItemBase@@UEBAH_N@Z endp

?_NV_getMaxAffordableNum@InventoryItemBase@@QEAAHH_N@Z proc EXPORT
?_NV_getMaxAffordableNum@InventoryItemBase@@QEAAHH_N@Z endp

; InventoryItemBase::getMaxAffordableNum(int, bool);
?getMaxAffordableNum@InventoryItemBase@@UEAAHH_N@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+12*8]
?getMaxAffordableNum@InventoryItemBase@@UEAAHH_N@Z endp

; InventoryItemBase::isStackable(class InventorySection *);
?isStackable@InventoryItemBase@@QEBAHPEAVInventorySection@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+13*8]
?isStackable@InventoryItemBase@@QEBAHPEAVInventorySection@@@Z endp

; InventoryItemBase::canStackWith(class InventoryItemBase *);
?canStackWith@InventoryItemBase@@QEBA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+14*8]
?canStackWith@InventoryItemBase@@QEBA_NPEAV1@@Z endp

?_NV_getInventory@InventoryItemBase@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@InventoryItemBase@@QEBAPEAVInventory@@XZ endp

; InventoryItemBase::getInventory();
?getInventory@InventoryItemBase@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+15*8]
?getInventory@InventoryItemBase@@UEBAPEAVInventory@@XZ endp

?_NV_isSameAs@InventoryItemBase@@QEBA_NPEAV1@@Z proc EXPORT
?_NV_isSameAs@InventoryItemBase@@QEBA_NPEAV1@@Z endp

; InventoryItemBase::isSameAs(class InventoryItemBase *);
?isSameAs@InventoryItemBase@@UEBA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+16*8]
?isSameAs@InventoryItemBase@@UEBA_NPEAV1@@Z endp

; InventoryItemBase::onGround();
?onGround@InventoryItemBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+17*8]
?onGround@InventoryItemBase@@QEBA_NXZ endp

; InventoryItemBase::addQuantity(int &, class Item *, class InventorySection *);
?addQuantity@InventoryItemBase@@QEAAXAEAHPEAVItem@@PEAVInventorySection@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+18*8]
?addQuantity@InventoryItemBase@@QEAAXAEAHPEAVItem@@PEAVInventorySection@@@Z endp

?_NV_getProperOwner@InventoryItemBase@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_getProperOwner@InventoryItemBase@@QEBAAEBVhand@@XZ endp

; InventoryItemBase::getProperOwner();
?getProperOwner@InventoryItemBase@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+19*8]
?getProperOwner@InventoryItemBase@@UEBAAEBVhand@@XZ endp

?_NV_setProperOwner@InventoryItemBase@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setProperOwner@InventoryItemBase@@QEAAXAEBVhand@@@Z endp

; InventoryItemBase::setProperOwner(const class hand &);
?setProperOwner@InventoryItemBase@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+20*8]
?setProperOwner@InventoryItemBase@@UEAAXAEBVhand@@@Z endp

; InventoryItemBase::isResearchArtifact();
?isResearchArtifact@InventoryItemBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+21*8]
?isResearchArtifact@InventoryItemBase@@QEBA_NXZ endp

?_NV_getLevel@InventoryItemBase@@QEBAHXZ proc EXPORT
?_NV_getLevel@InventoryItemBase@@QEBAHXZ endp

; InventoryItemBase::getLevel();
?getLevel@InventoryItemBase@@UEBAHXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+22*8]
?getLevel@InventoryItemBase@@UEBAHXZ endp

; InventoryItemBase::getItemSound();
?getItemSound@InventoryItemBase@@QEBAPEBDXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+23*8]
?getItemSound@InventoryItemBase@@QEBAPEBDXZ endp

; InventoryItemBase::isStolen(bool);
?isStolen@InventoryItemBase@@QEBA_N_N@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+24*8]
?isStolen@InventoryItemBase@@QEBA_N_N@Z endp

?_CONSTRUCTOR@InventoryItemBase@@QEAAPEAV1@PEAVGameData@@Vhand@@00@Z proc EXPORT
?_CONSTRUCTOR@InventoryItemBase@@QEAAPEAV1@PEAVGameData@@Vhand@@00@Z endp

; InventoryItemBase::InventoryItemBase(class GameData *, class hand, class GameData *, class GameData *);
??0InventoryItemBase@@QEAA@PEAVGameData@@Vhand@@00@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+25*8]
??0InventoryItemBase@@QEAA@PEAVGameData@@Vhand@@00@Z endp

?_DESTRUCTOR@InventoryItemBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@InventoryItemBase@@QEAAXXZ endp

; InventoryItemBase::~InventoryItemBase();
??1InventoryItemBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+26*8]
??1InventoryItemBase@@UEAA@XZ endp

; InventoryItemBase::getTooltipTradeValue(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipTradeValue@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_InventoryItemBase_base+27*8]
?getTooltipTradeValue@InventoryItemBase@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; InventoryItemBase::merchantPriceMod();
?merchantPriceMod@InventoryItemBase@@QEBAMXZ proc EXPORT
jmp function_pointers[_InventoryItemBase_base+28*8]
?merchantPriceMod@InventoryItemBase@@QEBAMXZ endp
