
; Item::isFood(class GameData *);
?isFood@Item@@SA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Item_base+0*8]
?isFood@Item@@SA_NPEAVGameData@@@Z endp

?_NV_isGear@Item@@QEAAPEAVGear@@XZ proc EXPORT
?_NV_isGear@Item@@QEAAPEAVGear@@XZ endp

; Item::isGear();
?isGear@Item@@UEAAPEAVGear@@XZ proc EXPORT
jmp function_pointers[_Item_base+1*8]
?isGear@Item@@UEAAPEAVGear@@XZ endp

?_NV_getClassType@Item@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@Item@@QEBA?AW4itemType@@XZ endp

; Item::getClassType();
?getClassType@Item@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Item_base+2*8]
?getClassType@Item@@UEBA?AW4itemType@@XZ endp

?_NV_resetAfterCopy@Item@@QEAAXXZ proc EXPORT
?_NV_resetAfterCopy@Item@@QEAAXXZ endp

; Item::resetAfterCopy();
?resetAfterCopy@Item@@UEAAXXZ proc EXPORT
jmp function_pointers[_Item_base+3*8]
?resetAfterCopy@Item@@UEAAXXZ endp

?_NV_activate@Item@@QEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@0VYesNoMaybe@@0@Z proc EXPORT
?_NV_activate@Item@@QEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@0VYesNoMaybe@@0@Z endp

; Item::activate(bool, const class Ogre::Vector3 &, const class Ogre::Quaternion &, bool, class YesNoMaybe, bool);
?activate@Item@@UEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@0VYesNoMaybe@@0@Z proc EXPORT
jmp function_pointers[_Item_base+4*8]
?activate@Item@@UEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@0VYesNoMaybe@@0@Z endp

?_NV_activate@Item@@QEAAX_NVYesNoMaybe@@@Z proc EXPORT
?_NV_activate@Item@@QEAAX_NVYesNoMaybe@@@Z endp

; Item::activate(bool, class YesNoMaybe);
?activate@Item@@UEAAX_NVYesNoMaybe@@@Z proc EXPORT
jmp function_pointers[_Item_base+5*8]
?activate@Item@@UEAAX_NVYesNoMaybe@@@Z endp

?_NV_deactivate@Item@@QEAAXXZ proc EXPORT
?_NV_deactivate@Item@@QEAAXXZ endp

; Item::deactivate();
?deactivate@Item@@UEAAXXZ proc EXPORT
jmp function_pointers[_Item_base+6*8]
?deactivate@Item@@UEAAXXZ endp

?_NV_setPositionRotation@Item@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@_N@Z proc EXPORT
?_NV_setPositionRotation@Item@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@_N@Z endp

; Item::setPositionRotation(const class Ogre::Vector3 &, const class Ogre::Quaternion &, bool);
?setPositionRotation@Item@@UEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@_N@Z proc EXPORT
jmp function_pointers[_Item_base+7*8]
?setPositionRotation@Item@@UEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@_N@Z endp

?_NV_isCrossbow@Item@@QEAAPEAVCrossbow@@XZ proc EXPORT
?_NV_isCrossbow@Item@@QEAAPEAVCrossbow@@XZ endp

; Item::isCrossbow();
?isCrossbow@Item@@UEAAPEAVCrossbow@@XZ proc EXPORT
jmp function_pointers[_Item_base+8*8]
?isCrossbow@Item@@UEAAPEAVCrossbow@@XZ endp

?_NV_isArmour@Item@@QEAAPEAVArmour@@XZ proc EXPORT
?_NV_isArmour@Item@@QEAAPEAVArmour@@XZ endp

; Item::isArmour();
?isArmour@Item@@UEAAPEAVArmour@@XZ proc EXPORT
jmp function_pointers[_Item_base+9*8]
?isArmour@Item@@UEAAPEAVArmour@@XZ endp

?_NV_isWeapon@Item@@QEAAPEAVWeapon@@XZ proc EXPORT
?_NV_isWeapon@Item@@QEAAPEAVWeapon@@XZ endp

; Item::isWeapon();
?isWeapon@Item@@UEAAPEAVWeapon@@XZ proc EXPORT
jmp function_pointers[_Item_base+10*8]
?isWeapon@Item@@UEAAPEAVWeapon@@XZ endp

?_NV_isLockedArmour@Item@@QEAAPEAVLockedArmour@@XZ proc EXPORT
?_NV_isLockedArmour@Item@@QEAAPEAVLockedArmour@@XZ endp

; Item::isLockedArmour();
?isLockedArmour@Item@@UEAAPEAVLockedArmour@@XZ proc EXPORT
jmp function_pointers[_Item_base+11*8]
?isLockedArmour@Item@@UEAAPEAVLockedArmour@@XZ endp

?_NV_isAFactionUniform@Item@@QEAAPEAVFaction@@XZ proc EXPORT
?_NV_isAFactionUniform@Item@@QEAAPEAVFaction@@XZ endp

; Item::isAFactionUniform();
?isAFactionUniform@Item@@UEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_Item_base+12*8]
?isAFactionUniform@Item@@UEAAPEAVFaction@@XZ endp

?_NV_isPhysical@Item@@QEBA_NXZ proc EXPORT
?_NV_isPhysical@Item@@QEBA_NXZ endp

; Item::isPhysical();
?isPhysical@Item@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Item_base+13*8]
?isPhysical@Item@@UEBA_NXZ endp

?_NV_setVisible@Item@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@Item@@QEAAX_N@Z endp

; Item::setVisible(bool);
?setVisible@Item@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_Item_base+14*8]
?setVisible@Item@@UEAAX_N@Z endp

?_NV_getVisible@Item@@QEBA_NXZ proc EXPORT
?_NV_getVisible@Item@@QEBA_NXZ endp

; Item::getVisible();
?getVisible@Item@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Item_base+15*8]
?getVisible@Item@@UEBA_NXZ endp

?_NV_getModelName@Item@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getModelName@Item@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Item::getModelName();
?getModelName@Item@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Item_base+16*8]
?getModelName@Item@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getInventory@Item@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@Item@@QEBAPEAVInventory@@XZ endp

; Item::getInventory();
?getInventory@Item@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_Item_base+17*8]
?getInventory@Item@@UEBAPEAVInventory@@XZ endp

?_NV_hasIngredients@Item@@QEAA_NXZ proc EXPORT
?_NV_hasIngredients@Item@@QEAA_NXZ endp

; Item::hasIngredients();
?hasIngredients@Item@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Item_base+18*8]
?hasIngredients@Item@@UEAA_NXZ endp

?_NV_isGoodFood@Item@@QEAA_NXZ proc EXPORT
?_NV_isGoodFood@Item@@QEAA_NXZ endp

; Item::isGoodFood();
?isGoodFood@Item@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Item_base+19*8]
?isGoodFood@Item@@UEAA_NXZ endp

?_NV_getEntity@Item@@QEBAPEAVEntity@Ogre@@XZ proc EXPORT
?_NV_getEntity@Item@@QEBAPEAVEntity@Ogre@@XZ endp

; Item::getEntity();
?getEntity@Item@@UEBAPEAVEntity@Ogre@@XZ proc EXPORT
jmp function_pointers[_Item_base+20*8]
?getEntity@Item@@UEBAPEAVEntity@Ogre@@XZ endp

?_NV_getTimeout@Item@@QEBA?AVTimeOfDay@@XZ proc EXPORT
?_NV_getTimeout@Item@@QEBA?AVTimeOfDay@@XZ endp

; Item::getTimeout();
?getTimeout@Item@@UEBA?AVTimeOfDay@@XZ proc EXPORT
jmp function_pointers[_Item_base+21*8]
?getTimeout@Item@@UEBA?AVTimeOfDay@@XZ endp

?_NV__serialise@Item@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@Item@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; Item::_serialise(class GameDataContainer *, enum itemType);
?_serialise@Item@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_Item_base+22*8]
?_serialise@Item@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_NV__loadFromSerialise@Item@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@Item@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; Item::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@Item@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Item_base+23*8]
?_loadFromSerialise@Item@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_serialise@Item@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@Item@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; Item::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@Item@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_Item_base+24*8]
?serialise@Item@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@Item@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@Item@@QEAAXPEAVGameSaveState@@@Z endp

; Item::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@Item@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Item_base+25*8]
?loadFromSerialise@Item@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_serialiseInInventory@Item@@QEAAPEAVGameData@@PEAVGameDataContainer@@PEAV2@@Z proc EXPORT
?_NV_serialiseInInventory@Item@@QEAAPEAVGameData@@PEAVGameDataContainer@@PEAV2@@Z endp

; Item::serialiseInInventory(class GameDataContainer *, class GameData *);
?serialiseInInventory@Item@@UEAAPEAVGameData@@PEAVGameDataContainer@@PEAV2@@Z proc EXPORT
jmp function_pointers[_Item_base+26*8]
?serialiseInInventory@Item@@UEAAPEAVGameData@@PEAVGameDataContainer@@PEAV2@@Z endp

?_NV_loadFromSerialiseInInventory@Item@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV_loadFromSerialiseInInventory@Item@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; Item::loadFromSerialiseInInventory(class GameDataContainer *, class GameData *);
?loadFromSerialiseInInventory@Item@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Item_base+27*8]
?loadFromSerialiseInInventory@Item@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_getCraftTime@Item@@QEAAMXZ proc EXPORT
?_NV_getCraftTime@Item@@QEAAMXZ endp

; Item::getCraftTime();
?getCraftTime@Item@@UEAAMXZ proc EXPORT
jmp function_pointers[_Item_base+28*8]
?getCraftTime@Item@@UEAAMXZ endp

?_NV_getCraftMaterialMult@Item@@QEAAMXZ proc EXPORT
?_NV_getCraftMaterialMult@Item@@QEAAMXZ endp

; Item::getCraftMaterialMult();
?getCraftMaterialMult@Item@@UEAAMXZ proc EXPORT
jmp function_pointers[_Item_base+29*8]
?getCraftMaterialMult@Item@@UEAAMXZ endp

?_NV_getLevel@Item@@QEBAHXZ proc EXPORT
?_NV_getLevel@Item@@QEBAHXZ endp

; Item::getLevel();
?getLevel@Item@@UEBAHXZ proc EXPORT
jmp function_pointers[_Item_base+30*8]
?getLevel@Item@@UEBAHXZ endp

?_NV_createItemEntityCallback_Equipping@Item@@QEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z proc EXPORT
?_NV_createItemEntityCallback_Equipping@Item@@QEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z endp

; Item::createItemEntityCallback_Equipping(class Ogre::Entity *, class Ogre::SceneNode *);
?createItemEntityCallback_Equipping@Item@@UEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z proc EXPORT
jmp function_pointers[_Item_base+31*8]
?createItemEntityCallback_Equipping@Item@@UEAAXPEAVEntity@Ogre@@PEAVSceneNode@3@@Z endp

?_NV_destroyItemEntityCallback_Equipping@Item@@QEAAXXZ proc EXPORT
?_NV_destroyItemEntityCallback_Equipping@Item@@QEAAXXZ endp

; Item::destroyItemEntityCallback_Equipping();
?destroyItemEntityCallback_Equipping@Item@@UEAAXXZ proc EXPORT
jmp function_pointers[_Item_base+32*8]
?destroyItemEntityCallback_Equipping@Item@@UEAAXXZ endp

?_NV_notifyTheftFrom@Item@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_notifyTheftFrom@Item@@QEAAXPEAVRootObject@@@Z endp

; Item::notifyTheftFrom(class RootObject *);
?notifyTheftFrom@Item@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Item_base+33*8]
?notifyTheftFrom@Item@@UEAAXPEAVRootObject@@@Z endp

?_NV_notifyTheftFrom@Item@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_notifyTheftFrom@Item@@QEAAXAEBVhand@@@Z endp

; Item::notifyTheftFrom(const class hand &);
?notifyTheftFrom@Item@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Item_base+34*8]
?notifyTheftFrom@Item@@UEAAXAEBVhand@@@Z endp

; Item::findProperOwner(class RootObject *);
?findProperOwner@Item@@SAAEBVhand@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_Item_base+35*8]
?findProperOwner@Item@@SAAEBVhand@@PEAVRootObject@@@Z endp

; Item::findProperOwner(const class hand &);
?findProperOwner@Item@@SAAEBVhand@@AEBV2@@Z proc EXPORT
jmp function_pointers[_Item_base+36*8]
?findProperOwner@Item@@SAAEBVhand@@AEBV2@@Z endp

?_NV_setInventoryWeAreIn@Item@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setInventoryWeAreIn@Item@@QEAAXAEBVhand@@@Z endp

; Item::setInventoryWeAreIn(const class hand &);
?setInventoryWeAreIn@Item@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Item_base+37*8]
?setInventoryWeAreIn@Item@@UEAAXAEBVhand@@@Z endp

; Item::getInventoryWeAreIn();
?getInventoryWeAreIn@Item@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Item_base+38*8]
?getInventoryWeAreIn@Item@@QEBAAEBVhand@@XZ endp

; Item::isPersistant();
?isPersistant@Item@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Item_base+39*8]
?isPersistant@Item@@QEBA_NXZ endp

; Item::setPersistant(const class hand &);
?setPersistant@Item@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Item_base+40*8]
?setPersistant@Item@@QEAAXAEBVhand@@@Z endp

; Item::setPersistant(bool);
?setPersistant@Item@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Item_base+41*8]
?setPersistant@Item@@QEAAX_N@Z endp

; Item::persistantOwnerExists();
?persistantOwnerExists@Item@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Item_base+42*8]
?persistantOwnerExists@Item@@QEBA_NXZ endp

?_CONSTRUCTOR@Item@@QEAAPEAV1@PEAVGameData@@00Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@Item@@QEAAPEAV1@PEAVGameData@@00Vhand@@@Z endp

; Item::Item(class GameData *, class GameData *, class GameData *, class hand);
??0Item@@QEAA@PEAVGameData@@00Vhand@@@Z proc EXPORT
jmp function_pointers[_Item_base+43*8]
??0Item@@QEAA@PEAVGameData@@00Vhand@@@Z endp

?_DESTRUCTOR@Item@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Item@@QEAAXXZ endp

; Item::~Item();
??1Item@@UEAA@XZ proc EXPORT
jmp function_pointers[_Item_base+44*8]
??1Item@@UEAA@XZ endp

?_NV_createPhysical@Item@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@Item@@QEAA_NXZ endp

; Item::createPhysical();
?createPhysical@Item@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Item_base+45*8]
?createPhysical@Item@@UEAA_NXZ endp

?_NV_destroyPhysical@Item@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@Item@@QEAAXXZ endp

; Item::destroyPhysical();
?destroyPhysical@Item@@UEAAXXZ proc EXPORT
jmp function_pointers[_Item_base+46*8]
?destroyPhysical@Item@@UEAAXXZ endp

?_NV_loadUnloadCheck@Item@@QEAAXXZ proc EXPORT
?_NV_loadUnloadCheck@Item@@QEAAXXZ endp

; Item::loadUnloadCheck();
?loadUnloadCheck@Item@@UEAAXXZ proc EXPORT
jmp function_pointers[_Item_base+47*8]
?loadUnloadCheck@Item@@UEAAXXZ endp

; Item::createItemEntityCallback(class Ogre::SharedPtr<Ogre::Resource>, void *);
?createItemEntityCallback@Item@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z proc EXPORT
jmp function_pointers[_Item_base+48*8]
?createItemEntityCallback@Item@@QEAAXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z endp

?_NV_itemEntityCreated@Item@@QEAAXPEAVEntity@Ogre@@@Z proc EXPORT
?_NV_itemEntityCreated@Item@@QEAAXPEAVEntity@Ogre@@@Z endp

; Item::itemEntityCreated(class Ogre::Entity *);
?itemEntityCreated@Item@@UEAAXPEAVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_Item_base+49*8]
?itemEntityCreated@Item@@UEAAXPEAVEntity@Ogre@@@Z endp
