
?_CONSTRUCTOR@iVector2@@QEAAPEAV1@HH@Z proc EXPORT
?_CONSTRUCTOR@iVector2@@QEAAPEAV1@HH@Z endp

; iVector2::iVector2(int, int);
??0iVector2@@QEAA@HH@Z proc EXPORT
jmp function_pointers[_iVector2_base+0*8]
??0iVector2@@QEAA@HH@Z endp

?_CONSTRUCTOR@iVector2@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@iVector2@@QEAAPEAV1@XZ endp

; iVector2::iVector2();
??0iVector2@@QEAA@XZ proc EXPORT
jmp function_pointers[_iVector2_base+1*8]
??0iVector2@@QEAA@XZ endp

; iVector2::operator==(const class iVector2 &);
??8iVector2@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_iVector2_base+2*8]
??8iVector2@@QEBA_NAEBV0@@Z endp

; iVector2::operator!=(const class iVector2 &);
??9iVector2@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_iVector2_base+3*8]
??9iVector2@@QEBA_NAEBV0@@Z endp

; iVector2::getLinearValue();
?getLinearValue@iVector2@@QEBAHXZ proc EXPORT
jmp function_pointers[_iVector2_base+4*8]
?getLinearValue@iVector2@@QEBAHXZ endp

; iVector2::operator<(const class iVector2 &);
??MiVector2@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_iVector2_base+5*8]
??MiVector2@@QEBA_NAEBV0@@Z endp

; iVector2::getAsString();
?getAsString@iVector2@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_iVector2_base+6*8]
?getAsString@iVector2@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; iVector2::operator+(const class iVector2 &);
??HiVector2@@QEBA?AV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_iVector2_base+7*8]
??HiVector2@@QEBA?AV0@AEBV0@@Z endp
