
?_CONSTRUCTOR@GamedataSelectionList@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z proc EXPORT
?_CONSTRUCTOR@GamedataSelectionList@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z endp

; LevelEditor::GamedataSelectionList::GamedataSelectionList(class LevelEditor *, enum itemType, float, float, float, float);
??0GamedataSelectionList@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+0*8]
??0GamedataSelectionList@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z endp

?_DESTRUCTOR@GamedataSelectionList@LevelEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@GamedataSelectionList@LevelEditor@@QEAAXXZ endp

; LevelEditor::GamedataSelectionList::~GamedataSelectionList();
??1GamedataSelectionList@LevelEditor@@QEAA@XZ proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+1*8]
??1GamedataSelectionList@LevelEditor@@QEAA@XZ endp

; LevelEditor::GamedataSelectionList::deselectItem();
?deselectItem@GamedataSelectionList@LevelEditor@@QEAAXXZ proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+2*8]
?deselectItem@GamedataSelectionList@LevelEditor@@QEAAXXZ endp

; LevelEditor::GamedataSelectionList::selectItem(class GameData *);
?selectItem@GamedataSelectionList@LevelEditor@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+3*8]
?selectItem@GamedataSelectionList@LevelEditor@@QEAA_NPEAVGameData@@@Z endp

; LevelEditor::GamedataSelectionList::getSelectedItem();
?getSelectedItem@GamedataSelectionList@LevelEditor@@QEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+4*8]
?getSelectedItem@GamedataSelectionList@LevelEditor@@QEBAPEAVGameData@@XZ endp

; LevelEditor::GamedataSelectionList::listItemSelected(class MyGUI::ListBox *, unsigned __int64);
?listItemSelected@GamedataSelectionList@LevelEditor@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+5*8]
?listItemSelected@GamedataSelectionList@LevelEditor@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; LevelEditor::GamedataSelectionList::changeFilter(class MyGUI::EditBox *);
?changeFilter@GamedataSelectionList@LevelEditor@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+6*8]
?changeFilter@GamedataSelectionList@LevelEditor@@QEAAXPEAVEditBox@MyGUI@@@Z endp

?_NV_formatItem@GamedataSelectionList@LevelEditor@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
?_NV_formatItem@GamedataSelectionList@LevelEditor@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp

; LevelEditor::GamedataSelectionList::formatItem(class GameData *);
?formatItem@GamedataSelectionList@LevelEditor@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_GamedataSelectionList_base+7*8]
?formatItem@GamedataSelectionList@LevelEditor@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp
