
?_CONSTRUCTOR@NpcListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z proc EXPORT
?_CONSTRUCTOR@NpcListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z endp

; LevelEditor::NpcListWindow::NpcListWindow(class LevelEditor *, enum itemType, float, float, float, float);
??0NpcListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z proc EXPORT
jmp function_pointers[_LevelEditor_NpcListWindow_base+0*8]
??0NpcListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z endp

?_DESTRUCTOR@NpcListWindow@LevelEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NpcListWindow@LevelEditor@@QEAAXXZ endp

; LevelEditor::NpcListWindow::~NpcListWindow();
??1NpcListWindow@LevelEditor@@UEAA@XZ proc EXPORT
jmp function_pointers[_LevelEditor_NpcListWindow_base+1*8]
??1NpcListWindow@LevelEditor@@UEAA@XZ endp

?_NV_itemSelected@NpcListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_itemSelected@NpcListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z endp

; LevelEditor::NpcListWindow::itemSelected(class GameData *);
?itemSelected@NpcListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_NpcListWindow_base+2*8]
?itemSelected@NpcListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z endp
