
?_CONSTRUCTOR@SquadListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z proc EXPORT
?_CONSTRUCTOR@SquadListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z endp

; LevelEditor::SquadListWindow::SquadListWindow(class LevelEditor *, enum itemType, float, float, float, float);
??0SquadListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z proc EXPORT
jmp function_pointers[_LevelEditor_SquadListWindow_base+0*8]
??0SquadListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z endp

; LevelEditor::SquadListWindow::refresh(class GameData *);
?refresh@SquadListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_SquadListWindow_base+1*8]
?refresh@SquadListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z endp

?_NV_itemSelected@SquadListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_itemSelected@SquadListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z endp

; LevelEditor::SquadListWindow::itemSelected(class GameData *);
?itemSelected@SquadListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_SquadListWindow_base+2*8]
?itemSelected@SquadListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z endp

?_DESTRUCTOR@SquadListWindow@LevelEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SquadListWindow@LevelEditor@@QEAAXXZ endp

; LevelEditor::SquadListWindow::~SquadListWindow();
??1SquadListWindow@LevelEditor@@QEAA@XZ proc EXPORT
jmp function_pointers[_LevelEditor_SquadListWindow_base+3*8]
??1SquadListWindow@LevelEditor@@QEAA@XZ endp
