
?_CONSTRUCTOR@TownListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z proc EXPORT
?_CONSTRUCTOR@TownListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z endp

; LevelEditor::TownListWindow::TownListWindow(class LevelEditor *, enum itemType, float, float, float, float);
??0TownListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z proc EXPORT
jmp function_pointers[_LevelEditor_TownListWindow_base+0*8]
??0TownListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z endp

?_NV_formatItem@TownListWindow@LevelEditor@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
?_NV_formatItem@TownListWindow@LevelEditor@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp

; LevelEditor::TownListWindow::formatItem(class GameData *);
?formatItem@TownListWindow@LevelEditor@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_TownListWindow_base+1*8]
?formatItem@TownListWindow@LevelEditor@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp

?_DESTRUCTOR@TownListWindow@LevelEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TownListWindow@LevelEditor@@QEAAXXZ endp

; LevelEditor::TownListWindow::~TownListWindow();
??1TownListWindow@LevelEditor@@UEAA@XZ proc EXPORT
jmp function_pointers[_LevelEditor_TownListWindow_base+2*8]
??1TownListWindow@LevelEditor@@UEAA@XZ endp
