
?_CONSTRUCTOR@FactionListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z proc EXPORT
?_CONSTRUCTOR@FactionListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z endp

; LevelEditor::FactionListWindow::FactionListWindow(class LevelEditor *, enum itemType, float, float, float, float);
??0FactionListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z proc EXPORT
jmp function_pointers[_LevelEditor_FactionListWindow_base+0*8]
??0FactionListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z endp

?_NV_itemSelected@FactionListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_itemSelected@FactionListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z endp

; LevelEditor::FactionListWindow::itemSelected(class GameData *);
?itemSelected@FactionListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_FactionListWindow_base+1*8]
?itemSelected@FactionListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z endp

?_DESTRUCTOR@FactionListWindow@LevelEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FactionListWindow@LevelEditor@@QEAAXXZ endp

; LevelEditor::FactionListWindow::~FactionListWindow();
??1FactionListWindow@LevelEditor@@QEAA@XZ proc EXPORT
jmp function_pointers[_LevelEditor_FactionListWindow_base+2*8]
??1FactionListWindow@LevelEditor@@QEAA@XZ endp
