
?_CONSTRUCTOR@ItemListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z proc EXPORT
?_CONSTRUCTOR@ItemListWindow@LevelEditor@@QEAAPEAV12@PEAV2@W4itemType@@MMMM@Z endp

; LevelEditor::ItemListWindow::ItemListWindow(class LevelEditor *, enum itemType, float, float, float, float);
??0ItemListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z proc EXPORT
jmp function_pointers[_LevelEditor_ItemListWindow_base+0*8]
??0ItemListWindow@LevelEditor@@QEAA@PEAV1@W4itemType@@MMMM@Z endp

?_DESTRUCTOR@ItemListWindow@LevelEditor@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ItemListWindow@LevelEditor@@QEAAXXZ endp

; LevelEditor::ItemListWindow::~ItemListWindow();
??1ItemListWindow@LevelEditor@@UEAA@XZ proc EXPORT
jmp function_pointers[_LevelEditor_ItemListWindow_base+1*8]
??1ItemListWindow@LevelEditor@@UEAA@XZ endp

?_NV_itemSelected@ItemListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_itemSelected@ItemListWindow@LevelEditor@@QEAAXPEAVGameData@@@Z endp

; LevelEditor::ItemListWindow::itemSelected(class GameData *);
?itemSelected@ItemListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LevelEditor_ItemListWindow_base+2*8]
?itemSelected@ItemListWindow@LevelEditor@@UEAAXPEAVGameData@@@Z endp
