
?_CONSTRUCTOR@LightBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@LightBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; LightBuilding::LightBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0LightBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_LightBuilding_base+0*8]
??0LightBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_NV_serialise@LightBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@LightBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; LightBuilding::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@LightBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_LightBuilding_base+1*8]
?serialise@LightBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@LightBuilding@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@LightBuilding@@QEAAXPEAVGameSaveState@@@Z endp

; LightBuilding::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@LightBuilding@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_LightBuilding_base+2*8]
?loadFromSerialise@LightBuilding@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_createPhysical@LightBuilding@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@LightBuilding@@QEAA_NXZ endp

; LightBuilding::createPhysical();
?createPhysical@LightBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_LightBuilding_base+3*8]
?createPhysical@LightBuilding@@UEAA_NXZ endp

?_NV_getMouseCursor@LightBuilding@@QEAA?AW4CursorType@@XZ proc EXPORT
?_NV_getMouseCursor@LightBuilding@@QEAA?AW4CursorType@@XZ endp

; LightBuilding::getMouseCursor();
?getMouseCursor@LightBuilding@@UEAA?AW4CursorType@@XZ proc EXPORT
jmp function_pointers[_LightBuilding_base+4*8]
?getMouseCursor@LightBuilding@@UEAA?AW4CursorType@@XZ endp

?_NV_needPowerRightNow@LightBuilding@@QEBA_NXZ proc EXPORT
?_NV_needPowerRightNow@LightBuilding@@QEBA_NXZ endp

; LightBuilding::needPowerRightNow();
?needPowerRightNow@LightBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_LightBuilding_base+5*8]
?needPowerRightNow@LightBuilding@@UEBA_NXZ endp

?_NV_getMountedBuilding@LightBuilding@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_getMountedBuilding@LightBuilding@@QEBAAEBVhand@@XZ endp

; LightBuilding::getMountedBuilding();
?getMountedBuilding@LightBuilding@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_LightBuilding_base+6*8]
?getMountedBuilding@LightBuilding@@UEBAAEBVhand@@XZ endp

; LightBuilding::setMountedBuilding(class Building *);
?setMountedBuilding@LightBuilding@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_LightBuilding_base+7*8]
?setMountedBuilding@LightBuilding@@QEAAXPEAVBuilding@@@Z endp

?_NV_getPositionMarker@LightBuilding@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getPositionMarker@LightBuilding@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; LightBuilding::getPositionMarker(const class Ogre::Vector3 &);
?getPositionMarker@LightBuilding@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_LightBuilding_base+8*8]
?getPositionMarker@LightBuilding@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_DESTRUCTOR@LightBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LightBuilding@@QEAAXXZ endp

; LightBuilding::~LightBuilding();
??1LightBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_LightBuilding_base+9*8]
??1LightBuilding@@UEAA@XZ endp
