
?_CONSTRUCTOR@LimbsInventoryLayout@@QEAAPEAV1@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@LimbsInventoryLayout@@QEAAPEAV1@PEAVCharacter@@@Z endp

; LimbsInventoryLayout::LimbsInventoryLayout(class Character *);
??0LimbsInventoryLayout@@QEAA@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_LimbsInventoryLayout_base+0*8]
??0LimbsInventoryLayout@@QEAA@PEAVCharacter@@@Z endp

?_DESTRUCTOR@LimbsInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LimbsInventoryLayout@@QEAAXXZ endp

; LimbsInventoryLayout::~LimbsInventoryLayout();
??1LimbsInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_LimbsInventoryLayout_base+1*8]
??1LimbsInventoryLayout@@UEAA@XZ endp

; symbol is too long
; ?setupSections@LimbsInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; LimbsInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
LimbsInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_LimbsInventoryLayout_base+2*8]
LimbsInventoryLayout_setupSections_PLACEHOLDER endp
