
?_CONSTRUCTOR@LoadSaveWindow@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@LoadSaveWindow@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; LoadSaveWindow::LoadSaveWindow(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0LoadSaveWindow@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+0*8]
??0LoadSaveWindow@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@LoadSaveWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LoadSaveWindow@@QEAAXXZ endp

; LoadSaveWindow::~LoadSaveWindow();
??1LoadSaveWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+1*8]
??1LoadSaveWindow@@UEAA@XZ endp

; LoadSaveWindow::close(class MyGUI::Widget *);
?close@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+2*8]
?close@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; LoadSaveWindow::selectGame(class MyGUI::MultiListBox *, unsigned __int64);
?selectGame@LoadSaveWindow@@QEAAXPEAVMultiListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+3*8]
?selectGame@LoadSaveWindow@@QEAAXPEAVMultiListBox@MyGUI@@_K@Z endp

; LoadSaveWindow::keyPressed(class MyGUI::Widget *, struct MyGUI::KeyCode, unsigned int);
?keyPressed@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@UKeyCode@3@I@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+4*8]
?keyPressed@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@UKeyCode@3@I@Z endp

; LoadSaveWindow::toggleCheck(class MyGUI::Widget *);
?toggleCheck@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+5*8]
?toggleCheck@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_select@LoadSaveWindow@@QEAAXH@Z proc EXPORT
?_NV_select@LoadSaveWindow@@QEAAXH@Z endp

; LoadSaveWindow::select(int);
?select@LoadSaveWindow@@UEAAXH@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+6*8]
?select@LoadSaveWindow@@UEAAXH@Z endp

; LoadSaveWindow::getWidget();
?getWidget@LoadSaveWindow@@QEBAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+7*8]
?getWidget@LoadSaveWindow@@QEBAPEAVWidget@MyGUI@@XZ endp

; LoadSaveWindow::deleteSelectedSave(int);
?deleteSelectedSave@LoadSaveWindow@@QEAAXH@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+8*8]
?deleteSelectedSave@LoadSaveWindow@@QEAAXH@Z endp

; LoadSaveWindow::sortListComparer(class MyGUI::MultiListBox *, unsigned __int64, const class MyGUI::UString &, const class MyGUI::UString &, bool &);
?sortListComparer@LoadSaveWindow@@QEAAXPEAVMultiListBox@MyGUI@@_KAEBVUString@3@2AEA_N@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+9*8]
?sortListComparer@LoadSaveWindow@@QEAAXPEAVMultiListBox@MyGUI@@_KAEBVUString@3@2AEA_N@Z endp

; LoadSaveWindow::createInfo(class MyGUI::Widget *);
?createInfo@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+10*8]
?createInfo@LoadSaveWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; LoadSaveWindow::updateInfo(unsigned __int64);
?updateInfo@LoadSaveWindow@@QEAAX_K@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+11*8]
?updateInfo@LoadSaveWindow@@QEAAX_K@Z endp

; LoadSaveWindow::addOption(int, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addOption@LoadSaveWindow@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+12*8]
?addOption@LoadSaveWindow@@QEAAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z endp

; LoadSaveWindow::enableOption(int, bool);
?enableOption@LoadSaveWindow@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+13*8]
?enableOption@LoadSaveWindow@@QEAAXH_N@Z endp

; LoadSaveWindow::getOptions();
?getOptions@LoadSaveWindow@@QEBAHXZ proc EXPORT
jmp function_pointers[_LoadSaveWindow_base+14*8]
?getOptions@LoadSaveWindow@@QEBAHXZ endp
