
; LoadingWindow::getInstance();
?getInstance@LoadingWindow@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+0*8]
?getInstance@LoadingWindow@@SAPEAV1@XZ endp

; LoadingWindow::reload();
?reload@LoadingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+1*8]
?reload@LoadingWindow@@QEAAXXZ endp

; LoadingWindow::setVisible(bool);
?setVisible@LoadingWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_LoadingWindow_base+2*8]
?setVisible@LoadingWindow@@QEAAX_N@Z endp

; LoadingWindow::getVisible();
?getVisible@LoadingWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+3*8]
?getVisible@LoadingWindow@@QEBA_NXZ endp

; LoadingWindow::show();
?show@LoadingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+4*8]
?show@LoadingWindow@@QEAAXXZ endp

; LoadingWindow::hide();
?hide@LoadingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+5*8]
?hide@LoadingWindow@@QEAAXXZ endp

?_CONSTRUCTOR@LoadingWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@LoadingWindow@@QEAAPEAV1@XZ endp

; LoadingWindow::LoadingWindow();
??0LoadingWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+6*8]
??0LoadingWindow@@QEAA@XZ endp

?_DESTRUCTOR@LoadingWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LoadingWindow@@QEAAXXZ endp

; LoadingWindow::~LoadingWindow();
??1LoadingWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+7*8]
??1LoadingWindow@@UEAA@XZ endp

; LoadingWindow::frameEntered(float);
?frameEntered@LoadingWindow@@QEAAXM@Z proc EXPORT
jmp function_pointers[_LoadingWindow_base+8*8]
?frameEntered@LoadingWindow@@QEAAXM@Z endp

; LoadingWindow::setRandomBackground();
?setRandomBackground@LoadingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+9*8]
?setRandomBackground@LoadingWindow@@QEAAXXZ endp

; LoadingWindow::setRandomTip();
?setRandomTip@LoadingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_LoadingWindow_base+10*8]
?setRandomTip@LoadingWindow@@QEAAXXZ endp
