
?_CONSTRUCTOR@LockedArmour@@QEAAPEAV1@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z proc EXPORT
?_CONSTRUCTOR@LockedArmour@@QEAAPEAV1@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z endp

; LockedArmour::LockedArmour(class GameData *, class GameData *, class hand, class Faction *, int);
??0LockedArmour@@QEAA@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z proc EXPORT
jmp function_pointers[_LockedArmour_base+0*8]
??0LockedArmour@@QEAA@PEAVGameData@@0Vhand@@PEAVFaction@@H@Z endp

?_DESTRUCTOR@LockedArmour@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LockedArmour@@QEAAXXZ endp

; LockedArmour::~LockedArmour();
??1LockedArmour@@UEAA@XZ proc EXPORT
jmp function_pointers[_LockedArmour_base+1*8]
??1LockedArmour@@UEAA@XZ endp

?_NV_isArmour@LockedArmour@@QEAAPEAVArmour@@XZ proc EXPORT
?_NV_isArmour@LockedArmour@@QEAAPEAVArmour@@XZ endp

; LockedArmour::isArmour();
?isArmour@LockedArmour@@UEAAPEAVArmour@@XZ proc EXPORT
jmp function_pointers[_LockedArmour_base+2*8]
?isArmour@LockedArmour@@UEAAPEAVArmour@@XZ endp

?_NV_isLockedArmour@LockedArmour@@QEAAPEAV1@XZ proc EXPORT
?_NV_isLockedArmour@LockedArmour@@QEAAPEAV1@XZ endp

; LockedArmour::isLockedArmour();
?isLockedArmour@LockedArmour@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_LockedArmour_base+3*8]
?isLockedArmour@LockedArmour@@UEAAPEAV1@XZ endp

?_NV__serialise@LockedArmour@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
?_NV__serialise@LockedArmour@@QEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

; LockedArmour::_serialise(class GameDataContainer *, enum itemType);
?_serialise@LockedArmour@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_LockedArmour_base+4*8]
?_serialise@LockedArmour@@UEAAPEAVGameData@@PEAVGameDataContainer@@W4itemType@@@Z endp

?_NV__loadFromSerialise@LockedArmour@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
?_NV__loadFromSerialise@LockedArmour@@QEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

; LockedArmour::_loadFromSerialise(class GameDataContainer *, class GameData *);
?_loadFromSerialise@LockedArmour@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_LockedArmour_base+5*8]
?_loadFromSerialise@LockedArmour@@UEAAXPEAVGameDataContainer@@PEAVGameData@@@Z endp

?_NV_getTooltipData1@LockedArmour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@LockedArmour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; LockedArmour::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@LockedArmour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_LockedArmour_base+6*8]
?getTooltipData1@LockedArmour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@LockedArmour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@LockedArmour@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; LockedArmour::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@LockedArmour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_LockedArmour_base+7*8]
?getTooltipData2@LockedArmour@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp
