
?_CONSTRUCTOR@MainBarGUI@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@MainBarGUI@@QEAAPEAV1@XZ endp

; MainBarGUI::MainBarGUI();
??0MainBarGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+0*8]
??0MainBarGUI@@QEAA@XZ endp

?_DESTRUCTOR@MainBarGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::~MainBarGUI();
??1MainBarGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+1*8]
??1MainBarGUI@@UEAA@XZ endp

?_NV_clear@MainBarGUI@@QEAAXXZ proc EXPORT
?_NV_clear@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::clear();
?clear@MainBarGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+2*8]
?clear@MainBarGUI@@UEAAXXZ endp

?_NV_show@MainBarGUI@@QEAAX_N@Z proc EXPORT
?_NV_show@MainBarGUI@@QEAAX_N@Z endp

; MainBarGUI::show(bool);
?show@MainBarGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+3*8]
?show@MainBarGUI@@UEAAX_N@Z endp

?_NV_update@MainBarGUI@@QEAAXXZ proc EXPORT
?_NV_update@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::update();
?update@MainBarGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+4*8]
?update@MainBarGUI@@UEAAXXZ endp

; MainBarGUI::speedChanged();
?speedChanged@MainBarGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+5*8]
?speedChanged@MainBarGUI@@QEAAXXZ endp

?_NV_autoChangeSelectedObject@MainBarGUI@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_autoChangeSelectedObject@MainBarGUI@@QEAAXAEBVhand@@@Z endp

; MainBarGUI::autoChangeSelectedObject(const class hand &);
?autoChangeSelectedObject@MainBarGUI@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+6*8]
?autoChangeSelectedObject@MainBarGUI@@UEAAXAEBVhand@@@Z endp

?_NV_updateBountyPanelVisibility@MainBarGUI@@QEAAXXZ proc EXPORT
?_NV_updateBountyPanelVisibility@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::updateBountyPanelVisibility();
?updateBountyPanelVisibility@MainBarGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+7*8]
?updateBountyPanelVisibility@MainBarGUI@@UEAAXXZ endp

; MainBarGUI::setLevelEditMode(bool);
?setLevelEditMode@MainBarGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+8*8]
?setLevelEditMode@MainBarGUI@@QEAAX_N@Z endp

; MainBarGUI::setLevelEditInteriorMode(bool);
?setLevelEditInteriorMode@MainBarGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+9*8]
?setLevelEditInteriorMode@MainBarGUI@@QEAAX_N@Z endp

; MainBarGUI::pressedKey(unsigned int);
?pressedKey@MainBarGUI@@QEAAXI@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+10*8]
?pressedKey@MainBarGUI@@QEAAXI@Z endp

; MainBarGUI::getPortrait(const struct MyGUI::types::TPoint<int> &);
?getPortrait@MainBarGUI@@QEAAPEAVPortraitData@@AEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+11*8]
?getPortrait@MainBarGUI@@QEAAPEAVPortraitData@@AEBU?$TPoint@H@types@MyGUI@@@Z endp

; MainBarGUI::getPortrait(const class hand &);
?getPortrait@MainBarGUI@@QEAAPEAVPortraitData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+12*8]
?getPortrait@MainBarGUI@@QEAAPEAVPortraitData@@AEBVhand@@@Z endp

; MainBarGUI::updatePortrait(const class hand &);
?updatePortrait@MainBarGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+13*8]
?updatePortrait@MainBarGUI@@QEAAXAEBVhand@@@Z endp

; MainBarGUI::platoonUpdated(class RootObjectContainer *, bool);
?platoonUpdated@MainBarGUI@@QEAAXPEAVRootObjectContainer@@_N@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+14*8]
?platoonUpdated@MainBarGUI@@QEAAXPEAVRootObjectContainer@@_N@Z endp

; MainBarGUI::updatePotraitsPlatoon();
?updatePotraitsPlatoon@MainBarGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+15*8]
?updatePotraitsPlatoon@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::updatePortraits();
?updatePortraits@MainBarGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+16*8]
?updatePortraits@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::refreshPortraitTabs();
?refreshPortraitTabs@MainBarGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+17*8]
?refreshPortraitTabs@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::updatePortraitSize(class ActivePlatoon *);
?updatePortraitSize@MainBarGUI@@QEAAXPEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+18*8]
?updatePortraitSize@MainBarGUI@@QEAAXPEAVActivePlatoon@@@Z endp

; MainBarGUI::closeMapWindow(class MyGUI::Widget *);
?closeMapWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+19*8]
?closeMapWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleMapWindow(class MyGUI::Widget *);
?toggleMapWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+20*8]
?toggleMapWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleFactionWindow(class MyGUI::Widget *);
?toggleFactionWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+21*8]
?toggleFactionWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleTechWindow(class MyGUI::Widget *);
?toggleTechWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+22*8]
?toggleTechWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleCraftWindow(class MyGUI::Widget *);
?toggleCraftWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+23*8]
?toggleCraftWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleSquadWindow(class MyGUI::Widget *);
?toggleSquadWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+24*8]
?toggleSquadWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::changeFloorButtonUp(class MyGUI::Widget *);
?changeFloorButtonUp@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+25*8]
?changeFloorButtonUp@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::changeFloorButtonDown(class MyGUI::Widget *);
?changeFloorButtonDown@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+26*8]
?changeFloorButtonDown@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::getPausePanel();
?getPausePanel@MainBarGUI@@QEAAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+27*8]
?getPausePanel@MainBarGUI@@QEAAPEAVWidget@MyGUI@@XZ endp

; MainBarGUI::getLoadingPanel();
?getLoadingPanel@MainBarGUI@@QEAAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+28*8]
?getLoadingPanel@MainBarGUI@@QEAAPEAVWidget@MyGUI@@XZ endp

; MainBarGUI::getMedicalPanel();
?getMedicalPanel@MainBarGUI@@QEBAPEAVMedicalDatapanel@@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+29*8]
?getMedicalPanel@MainBarGUI@@QEBAPEAVMedicalDatapanel@@XZ endp

; MainBarGUI::ordersPanelFill(const class hand &);
?ordersPanelFill@MainBarGUI@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+30*8]
?ordersPanelFill@MainBarGUI@@QEAAXAEBVhand@@@Z endp

; MainBarGUI::ordersPanelClear();
?ordersPanelClear@MainBarGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+31*8]
?ordersPanelClear@MainBarGUI@@QEAAXXZ endp

?_NV_getToolTip@MainBarGUI@@QEAAPEAVToolTip@@XZ proc EXPORT
?_NV_getToolTip@MainBarGUI@@QEAAPEAVToolTip@@XZ endp

; MainBarGUI::getToolTip();
?getToolTip@MainBarGUI@@UEAAPEAVToolTip@@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+32*8]
?getToolTip@MainBarGUI@@UEAAPEAVToolTip@@XZ endp

; MainBarGUI::getDatapanel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getDatapanel@MainBarGUI@@QEBAPEAVDatapanelGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+33*8]
?getDatapanel@MainBarGUI@@QEBAPEAVDatapanelGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; MainBarGUI::getBuildingInventoryPosition();
?getBuildingInventoryPosition@MainBarGUI@@QEBAAEBU?$TPoint@H@types@MyGUI@@XZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+34*8]
?getBuildingInventoryPosition@MainBarGUI@@QEBAAEBU?$TPoint@H@types@MyGUI@@XZ endp

; MainBarGUI::setMessagePosition();
?setMessagePosition@MainBarGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainBarGUI_base+35*8]
?setMessagePosition@MainBarGUI@@QEAAXXZ endp

; MainBarGUI::serialise(class GameData *);
?serialise@MainBarGUI@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+36*8]
?serialise@MainBarGUI@@QEAAXPEAVGameData@@@Z endp

; MainBarGUI::loadFromSerialise(class GameData *);
?loadFromSerialise@MainBarGUI@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+37*8]
?loadFromSerialise@MainBarGUI@@QEAAXPEAVGameData@@@Z endp

; MainBarGUI::getTabPlatoonPortrait(int);
?getTabPlatoonPortrait@MainBarGUI@@QEAAAEBVMainTabPortraitPlatoon@@H@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+38*8]
?getTabPlatoonPortrait@MainBarGUI@@QEAAAEBVMainTabPortraitPlatoon@@H@Z endp

; MainBarGUI::getTabPlatoonPortrait(class ActivePlatoon *);
?getTabPlatoonPortrait@MainBarGUI@@QEAAAEBVMainTabPortraitPlatoon@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+39*8]
?getTabPlatoonPortrait@MainBarGUI@@QEAAAEBVMainTabPortraitPlatoon@@PEAVActivePlatoon@@@Z endp

; MainBarGUI::portraitChangeSelection(class MyGUI::ItemBox *, unsigned __int64, bool);
?portraitChangeSelection@MainBarGUI@@QEAAXPEAVItemBox@MyGUI@@_K_N@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+40*8]
?portraitChangeSelection@MainBarGUI@@QEAAXPEAVItemBox@MyGUI@@_K_N@Z endp

; MainBarGUI::portraitSelectItemAccept(class MyGUI::ItemBox *, unsigned __int64);
?portraitSelectItemAccept@MainBarGUI@@QEAAXPEAVItemBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+41*8]
?portraitSelectItemAccept@MainBarGUI@@QEAAXPEAVItemBox@MyGUI@@_K@Z endp

; MainBarGUI::portraitNotifyItem(class MyGUI::ItemBox *, const struct MyGUI::IBNotifyItemData &);
?portraitNotifyItem@MainBarGUI@@QEAAXPEAVItemBox@MyGUI@@AEBUIBNotifyItemData@3@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+42*8]
?portraitNotifyItem@MainBarGUI@@QEAAXPEAVItemBox@MyGUI@@AEBUIBNotifyItemData@3@@Z endp

; MainBarGUI::tabPlatoonChange(class MyGUI::TabControl *, unsigned __int64);
?tabPlatoonChange@MainBarGUI@@QEAAXPEAVTabControl@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+43*8]
?tabPlatoonChange@MainBarGUI@@QEAAXPEAVTabControl@MyGUI@@_K@Z endp

; MainBarGUI::setExtendInfoPanelEnabled(bool);
?setExtendInfoPanelEnabled@MainBarGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+44*8]
?setExtendInfoPanelEnabled@MainBarGUI@@QEAAX_N@Z endp

; MainBarGUI::extendInfoPanel(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?extendInfoPanel@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+45*8]
?extendInfoPanel@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; MainBarGUI::toggleInventory(class MyGUI::Widget *);
?toggleInventory@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+46*8]
?toggleInventory@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleStatsWindow(class MyGUI::Widget *);
?toggleStatsWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+47*8]
?toggleStatsWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::toggleHelpWindow(class MyGUI::Widget *);
?toggleHelpWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+48*8]
?toggleHelpWindow@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::changeSpeed(class MyGUI::Widget *);
?changeSpeed@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+49*8]
?changeSpeed@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::buildButton(class MyGUI::Widget *);
?buildButton@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+50*8]
?buildButton@MainBarGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; MainBarGUI::_getWidget(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?_getWidget@MainBarGUI@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_MainBarGUI_base+51*8]
?_getWidget@MainBarGUI@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
