
?_CONSTRUCTOR@MainTabPortraitPlatoon@@QEAAPEAV1@PEAVActivePlatoon@@PEAVMainBarGUI@@@Z proc EXPORT
?_CONSTRUCTOR@MainTabPortraitPlatoon@@QEAAPEAV1@PEAVActivePlatoon@@PEAVMainBarGUI@@@Z endp

; MainTabPortraitPlatoon::MainTabPortraitPlatoon(class ActivePlatoon *, class MainBarGUI *);
??0MainTabPortraitPlatoon@@QEAA@PEAVActivePlatoon@@PEAVMainBarGUI@@@Z proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+0*8]
??0MainTabPortraitPlatoon@@QEAA@PEAVActivePlatoon@@PEAVMainBarGUI@@@Z endp

?_CONSTRUCTOR@MainTabPortraitPlatoon@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@MainTabPortraitPlatoon@@QEAAPEAV1@XZ endp

; MainTabPortraitPlatoon::MainTabPortraitPlatoon();
??0MainTabPortraitPlatoon@@QEAA@XZ proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+1*8]
??0MainTabPortraitPlatoon@@QEAA@XZ endp

; MainTabPortraitPlatoon::addTab(class MyGUI::TabControl *, bool);
?addTab@MainTabPortraitPlatoon@@QEAAXPEAVTabControl@MyGUI@@_N@Z proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+2*8]
?addTab@MainTabPortraitPlatoon@@QEAAXPEAVTabControl@MyGUI@@_N@Z endp

; MainTabPortraitPlatoon::detach();
?detach@MainTabPortraitPlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+3*8]
?detach@MainTabPortraitPlatoon@@QEAAXXZ endp

; MainTabPortraitPlatoon::setFlash(bool);
?setFlash@MainTabPortraitPlatoon@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+4*8]
?setFlash@MainTabPortraitPlatoon@@QEAAX_N@Z endp

; MainTabPortraitPlatoon::update();
?update@MainTabPortraitPlatoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+5*8]
?update@MainTabPortraitPlatoon@@QEAAXXZ endp

?_DESTRUCTOR@MainTabPortraitPlatoon@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MainTabPortraitPlatoon@@QEAAXXZ endp

; MainTabPortraitPlatoon::~MainTabPortraitPlatoon();
??1MainTabPortraitPlatoon@@QEAA@XZ proc EXPORT
jmp function_pointers[_MainTabPortraitPlatoon_base+6*8]
??1MainTabPortraitPlatoon@@QEAA@XZ endp
