
; ManagementScreen::TechItemViewData::getName();
?getName@TechItemViewData@ManagementScreen@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+0*8]
?getName@TechItemViewData@ManagementScreen@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; ManagementScreen::TechItemViewData::getValue();
?getValue@TechItemViewData@ManagementScreen@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+1*8]
?getValue@TechItemViewData@ManagementScreen@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; ManagementScreen::TechItemViewData::getProgress();
?getProgress@TechItemViewData@ManagementScreen@@QEBAMXZ proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+2*8]
?getProgress@TechItemViewData@ManagementScreen@@QEBAMXZ endp

; ManagementScreen::TechItemViewData::setItem(class ResearchItem &);
?setItem@TechItemViewData@ManagementScreen@@QEAAXAEAVResearchItem@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+3*8]
?setItem@TechItemViewData@ManagementScreen@@QEAAXAEAVResearchItem@@@Z endp

?_CONSTRUCTOR@TechItemViewData@ManagementScreen@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@TechItemViewData@ManagementScreen@@QEAAPEAV12@AEBU12@@Z endp

; ManagementScreen::TechItemViewData::TechItemViewData(const struct ManagementScreen::TechItemViewData &);
??0TechItemViewData@ManagementScreen@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+4*8]
??0TechItemViewData@ManagementScreen@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@TechItemViewData@ManagementScreen@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TechItemViewData@ManagementScreen@@QEAAPEAV12@XZ endp

; ManagementScreen::TechItemViewData::TechItemViewData();
??0TechItemViewData@ManagementScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+5*8]
??0TechItemViewData@ManagementScreen@@QEAA@XZ endp

?_DESTRUCTOR@TechItemViewData@ManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TechItemViewData@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::TechItemViewData::~TechItemViewData();
??1TechItemViewData@ManagementScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_TechItemViewData_base+6*8]
??1TechItemViewData@ManagementScreen@@QEAA@XZ endp
