
; ManagementScreen::getSingleton();
?getSingleton@ManagementScreen@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+0*8]
?getSingleton@ManagementScreen@@SAPEAV1@XZ endp

?_DESTRUCTOR@ManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::~ManagementScreen();
??1ManagementScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+1*8]
??1ManagementScreen@@UEAA@XZ endp

; ManagementScreen::update();
?update@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+2*8]
?update@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::clear();
?clear@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+3*8]
?clear@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::getVisible();
?getVisible@ManagementScreen@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+4*8]
?getVisible@ManagementScreen@@QEAA_NXZ endp

; ManagementScreen::setVisible(bool, int);
?setVisible@ManagementScreen@@QEAAX_NH@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+5*8]
?setVisible@ManagementScreen@@QEAAX_NH@Z endp

; ManagementScreen::closeEverythingButton(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeEverythingButton@ManagementScreen@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+6*8]
?closeEverythingButton@ManagementScreen@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ManagementScreen::tabCallback(class MyGUI::TabControl *, unsigned __int64);
?tabCallback@ManagementScreen@@QEAAXPEAVTabControl@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+7*8]
?tabCallback@ManagementScreen@@QEAAXPEAVTabControl@MyGUI@@_K@Z endp

; ManagementScreen::getCurrentTab();
?getCurrentTab@ManagementScreen@@QEAAHXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+8*8]
?getCurrentTab@ManagementScreen@@QEAAHXZ endp

; ManagementScreen::getTab(int);
?getTab@ManagementScreen@@QEBAPEAVTabItem@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+9*8]
?getTab@ManagementScreen@@QEBAPEAVTabItem@MyGUI@@H@Z endp

; ManagementScreen::getWidget(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getWidget@ManagementScreen@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+10*8]
?getWidget@ManagementScreen@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ManagementScreen::refresh(class GameData *, float);
?refresh@ManagementScreen@@QEAAXPEAVGameData@@M@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+11*8]
?refresh@ManagementScreen@@QEAAXPEAVGameData@@M@Z endp

; ManagementScreen::refreshResearchList();
?refreshResearchList@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+12*8]
?refreshResearchList@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshResearchRate();
?refreshResearchRate@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+13*8]
?refreshResearchRate@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshDiplomacy();
?refreshDiplomacy@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+14*8]
?refreshDiplomacy@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshSquads();
?refreshSquads@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+15*8]
?refreshSquads@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshMap(bool);
?refreshMap@ManagementScreen@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+16*8]
?refreshMap@ManagementScreen@@QEAAX_N@Z endp

; ManagementScreen::showRoads(bool);
?showRoads@ManagementScreen@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+17*8]
?showRoads@ManagementScreen@@QEAAX_N@Z endp

; ManagementScreen::addSquadToMap(class Platoon *);
?addSquadToMap@ManagementScreen@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+18*8]
?addSquadToMap@ManagementScreen@@QEAAXPEAVPlatoon@@@Z endp

; ManagementScreen::removeSquadFromMap(class Platoon *);
?removeSquadFromMap@ManagementScreen@@QEAAXPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+19*8]
?removeSquadFromMap@ManagementScreen@@QEAAXPEAVPlatoon@@@Z endp

; ManagementScreen::addMessage(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum MessageLogColor);
?addMessage@ManagementScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0W4MessageLogColor@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+20*8]
?addMessage@ManagementScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0W4MessageLogColor@@@Z endp

; ManagementScreen::resetSquads();
?resetSquads@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+21*8]
?resetSquads@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshMessages();
?refreshMessages@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+22*8]
?refreshMessages@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshAI();
?refreshAI@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+23*8]
?refreshAI@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::setCraftingBench(const class hand &);
?setCraftingBench@ManagementScreen@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+24*8]
?setCraftingBench@ManagementScreen@@QEAAXAEBVhand@@@Z endp

; ManagementScreen::printResearch(class DatapanelGUI *, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?printResearch@ManagementScreen@@SAXPEAVDatapanelGUI@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2H@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+25*8]
?printResearch@ManagementScreen@@SAXPEAVDatapanelGUI@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2H@Z endp

; ManagementScreen::showDebugMarker(const class Ogre::Vector3 &);
?showDebugMarker@ManagementScreen@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+26*8]
?showDebugMarker@ManagementScreen@@QEAAXAEBVVector3@Ogre@@@Z endp

?_CONSTRUCTOR@ManagementScreen@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ManagementScreen@@QEAAPEAV1@XZ endp

; ManagementScreen::ManagementScreen();
??0ManagementScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+27*8]
??0ManagementScreen@@QEAA@XZ endp

; ManagementScreen::updateResearchListRate();
?updateResearchListRate@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+28*8]
?updateResearchListRate@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::refreshResearchListDescription();
?refreshResearchListDescription@ManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_ManagementScreen_base+29*8]
?refreshResearchListDescription@ManagementScreen@@QEAAXXZ endp

; ManagementScreen::researchTypeSelect(class MyGUI::ListBox *, unsigned __int64);
?researchTypeSelect@ManagementScreen@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+30*8]
?researchTypeSelect@ManagementScreen@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; ManagementScreen::addButtonPress(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?addButtonPress@ManagementScreen@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+31*8]
?addButtonPress@ManagementScreen@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; ManagementScreen::removeButtonPress(class MyGUI::Widget *, int, int, struct MyGUI::MouseButton);
?removeButtonPress@ManagementScreen@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+32*8]
?removeButtonPress@ManagementScreen@@QEAAXPEAVWidget@MyGUI@@HHUMouseButton@3@@Z endp

; ManagementScreen::mouseOverCallback(class MyGUI::Widget *, int, int);
?mouseOverCallback@ManagementScreen@@QEAAXPEAVWidget@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+33*8]
?mouseOverCallback@ManagementScreen@@QEAAXPEAVWidget@MyGUI@@HH@Z endp

; ManagementScreen::researchQueueTooltip(class wraps::BaseLayout *, const struct MyGUI::ToolTipInfo &, struct ManagementScreen::TechItemViewData);
?researchQueueTooltip@ManagementScreen@@QEAAXPEAVBaseLayout@wraps@@AEBUToolTipInfo@MyGUI@@UTechItemViewData@1@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+34*8]
?researchQueueTooltip@ManagementScreen@@QEAAXPEAVBaseLayout@wraps@@AEBUToolTipInfo@MyGUI@@UTechItemViewData@1@@Z endp

; ManagementScreen::researchRemoved(int, const struct ManagementScreen::TechItemViewData &);
?researchRemoved@ManagementScreen@@QEAAXHAEBUTechItemViewData@1@@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+35*8]
?researchRemoved@ManagementScreen@@QEAAXHAEBUTechItemViewData@1@@Z endp

; ManagementScreen::researchValidateOrder(int, int, bool &);
?researchValidateOrder@ManagementScreen@@QEAAXHHAEA_N@Z proc EXPORT
jmp function_pointers[_ManagementScreen_base+36*8]
?researchValidateOrder@ManagementScreen@@QEAAXHHAEA_N@Z endp
