
?_CONSTRUCTOR@MapMarkerTown@MapScreen@@QEAAPEAV12@PEAVTownBase@@PEAV2@@Z proc EXPORT
?_CONSTRUCTOR@MapMarkerTown@MapScreen@@QEAAPEAV12@PEAVTownBase@@PEAV2@@Z endp

; MapScreen::MapMarkerTown::MapMarkerTown(class TownBase *, class MapScreen *);
??0MapMarkerTown@MapScreen@@QEAA@PEAVTownBase@@PEAV1@@Z proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerTown_base+0*8]
??0MapMarkerTown@MapScreen@@QEAA@PEAVTownBase@@PEAV1@@Z endp

?_DESTRUCTOR@MapMarkerTown@MapScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MapMarkerTown@MapScreen@@QEAAXXZ endp

; MapScreen::MapMarkerTown::~MapMarkerTown();
??1MapMarkerTown@MapScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerTown_base+1*8]
??1MapMarkerTown@MapScreen@@QEAA@XZ endp

; MapScreen::MapMarkerTown::update(const struct MyGUI::types::TPoint<int> &, enum MapZoomLevel);
?update@MapMarkerTown@MapScreen@@QEAAXAEBU?$TPoint@H@types@MyGUI@@W4MapZoomLevel@@@Z proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerTown_base+2*8]
?update@MapMarkerTown@MapScreen@@QEAAXAEBU?$TPoint@H@types@MyGUI@@W4MapZoomLevel@@@Z endp

; MapScreen::MapMarkerTown::setVisible(bool);
?setVisible@MapMarkerTown@MapScreen@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerTown_base+3*8]
?setVisible@MapMarkerTown@MapScreen@@QEAAX_N@Z endp

; MapScreen::MapMarkerTown::getVisible();
?getVisible@MapMarkerTown@MapScreen@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerTown_base+4*8]
?getVisible@MapMarkerTown@MapScreen@@QEBA_NXZ endp
