
?_CONSTRUCTOR@MapMarkerCharacter@MapScreen@@QEAAPEAV12@PEAVRootObjectBase@@PEAV2@@Z proc EXPORT
?_CONSTRUCTOR@MapMarkerCharacter@MapScreen@@QEAAPEAV12@PEAVRootObjectBase@@PEAV2@@Z endp

; MapScreen::MapMarkerCharacter::MapMarkerCharacter(class RootObjectBase *, class MapScreen *);
??0MapMarkerCharacter@MapScreen@@QEAA@PEAVRootObjectBase@@PEAV1@@Z proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerCharacter_base+0*8]
??0MapMarkerCharacter@MapScreen@@QEAA@PEAVRootObjectBase@@PEAV1@@Z endp

?_DESTRUCTOR@MapMarkerCharacter@MapScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MapMarkerCharacter@MapScreen@@QEAAXXZ endp

; MapScreen::MapMarkerCharacter::~MapMarkerCharacter();
??1MapMarkerCharacter@MapScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerCharacter_base+1*8]
??1MapMarkerCharacter@MapScreen@@QEAA@XZ endp

; MapScreen::MapMarkerCharacter::update(const struct MyGUI::types::TPoint<int> &);
?update@MapMarkerCharacter@MapScreen@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerCharacter_base+2*8]
?update@MapMarkerCharacter@MapScreen@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; MapScreen::MapMarkerCharacter::setVisible(bool);
?setVisible@MapMarkerCharacter@MapScreen@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerCharacter_base+3*8]
?setVisible@MapMarkerCharacter@MapScreen@@QEAAX_N@Z endp

; MapScreen::MapMarkerCharacter::getVisible();
?getVisible@MapMarkerCharacter@MapScreen@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MapScreen_MapMarkerCharacter_base+4*8]
?getVisible@MapMarkerCharacter@MapScreen@@QEBA_NXZ endp
