
?_CONSTRUCTOR@MedianFilter2DVector@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@MedianFilter2DVector@@QEAAPEAV1@XZ endp

; MedianFilter2DVector::MedianFilter2DVector();
??0MedianFilter2DVector@@QEAA@XZ proc EXPORT
jmp function_pointers[_MedianFilter2DVector_base+0*8]
??0MedianFilter2DVector@@QEAA@XZ endp

; MedianFilter2DVector::setup(int, int, bool);
?setup@MedianFilter2DVector@@QEAAXHH_N@Z proc EXPORT
jmp function_pointers[_MedianFilter2DVector_base+1*8]
?setup@MedianFilter2DVector@@QEAAXHH_N@Z endp

; MedianFilter2DVector::reset();
?reset@MedianFilter2DVector@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedianFilter2DVector_base+2*8]
?reset@MedianFilter2DVector@@QEAAXXZ endp

?_DESTRUCTOR@MedianFilter2DVector@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MedianFilter2DVector@@QEAAXXZ endp

; MedianFilter2DVector::~MedianFilter2DVector();
??1MedianFilter2DVector@@QEAA@XZ proc EXPORT
jmp function_pointers[_MedianFilter2DVector_base+3*8]
??1MedianFilter2DVector@@QEAA@XZ endp
