
; MedicalSystem::HealthPartStatus::serialise(class GameData *, int);
?serialise@HealthPartStatus@MedicalSystem@@QEAAXPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+0*8]
?serialise@HealthPartStatus@MedicalSystem@@QEAAXPEAVGameData@@H@Z endp

; MedicalSystem::HealthPartStatus::load(class GameData *, int);
?load@HealthPartStatus@MedicalSystem@@QEAAXPEAVGameData@@H@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+1*8]
?load@HealthPartStatus@MedicalSystem@@QEAAXPEAVGameData@@H@Z endp

; MedicalSystem::HealthPartStatus::isRobotic();
?isRobotic@HealthPartStatus@MedicalSystem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+2*8]
?isRobotic@HealthPartStatus@MedicalSystem@@QEAA_NXZ endp

; MedicalSystem::HealthPartStatus::getData();
?getData@HealthPartStatus@MedicalSystem@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+3*8]
?getData@HealthPartStatus@MedicalSystem@@QEAAPEAVGameData@@XZ endp

; MedicalSystem::HealthPartStatus::getRobotLimbEnum();
?getRobotLimbEnum@HealthPartStatus@MedicalSystem@@QEBA?AW4Limb@RobotLimbs@@XZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+4*8]
?getRobotLimbEnum@HealthPartStatus@MedicalSystem@@QEBA?AW4Limb@RobotLimbs@@XZ endp

; MedicalSystem::HealthPartStatus::setup(class GameData *, float, float, float, class MedicalSystem *, bool, class Character *);
?setup@HealthPartStatus@MedicalSystem@@QEAAXPEAVGameData@@MMMPEAV2@_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+5*8]
?setup@HealthPartStatus@MedicalSystem@@QEAAXPEAVGameData@@MMMPEAV2@_NPEAVCharacter@@@Z endp

; MedicalSystem::HealthPartStatus::update(float, float, float, float, float, float);
?update@HealthPartStatus@MedicalSystem@@QEAA_NMMMMMM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+6*8]
?update@HealthPartStatus@MedicalSystem@@QEAA_NMMMMMM@Z endp

; MedicalSystem::HealthPartStatus::updateDerivedHealths();
?updateDerivedHealths@HealthPartStatus@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+7*8]
?updateDerivedHealths@HealthPartStatus@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::HealthPartStatus::applyDamage(const class Damages &);
?applyDamage@HealthPartStatus@MedicalSystem@@QEAAXAEBVDamages@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+8*8]
?applyDamage@HealthPartStatus@MedicalSystem@@QEAAXAEBVDamages@@@Z endp

; MedicalSystem::HealthPartStatus::applyWearDamage(const class Damages &);
?applyWearDamage@HealthPartStatus@MedicalSystem@@QEAAXAEBVDamages@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+9*8]
?applyWearDamage@HealthPartStatus@MedicalSystem@@QEAAXAEBVDamages@@@Z endp

; MedicalSystem::HealthPartStatus::getWorstDamage(float);
?getWorstDamage@HealthPartStatus@MedicalSystem@@QEBAMM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+10*8]
?getWorstDamage@HealthPartStatus@MedicalSystem@@QEBAMM@Z endp

; MedicalSystem::HealthPartStatus::getRobotLimbState();
?getRobotLimbState@HealthPartStatus@MedicalSystem@@QEAA?AW4LimbState@@XZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+11*8]
?getRobotLimbState@HealthPartStatus@MedicalSystem@@QEAA?AW4LimbState@@XZ endp

; MedicalSystem::HealthPartStatus::setRobotLimbItem(class RobotLimbItem *, bool);
?setRobotLimbItem@HealthPartStatus@MedicalSystem@@QEAAXPEAVRobotLimbItem@@_N@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+12*8]
?setRobotLimbItem@HealthPartStatus@MedicalSystem@@QEAAXPEAVRobotLimbItem@@_N@Z endp

; MedicalSystem::HealthPartStatus::getExtraBleedingAmount();
?getExtraBleedingAmount@HealthPartStatus@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+13*8]
?getExtraBleedingAmount@HealthPartStatus@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::HealthPartStatus::isDead();
?isDead@HealthPartStatus@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+14*8]
?isDead@HealthPartStatus@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::HealthPartStatus::getBloodynessMult();
?getBloodynessMult@HealthPartStatus@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+15*8]
?getBloodynessMult@HealthPartStatus@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::HealthPartStatus::maxHealth();
?maxHealth@HealthPartStatus@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+16*8]
?maxHealth@HealthPartStatus@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::HealthPartStatus::healthAsPercent(float);
?healthAsPercent@HealthPartStatus@MedicalSystem@@QEAAMM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_HealthPartStatus_base+17*8]
?healthAsPercent@HealthPartStatus@MedicalSystem@@QEAAMM@Z endp
