
; MedicalSystem::precalculateFirstAidNeedScore();
?precalculateFirstAidNeedScore@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+0*8]
?precalculateFirstAidNeedScore@MedicalSystem@@QEAAXXZ endp

?_CONSTRUCTOR@MedicalSystem@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@MedicalSystem@@QEAAPEAV1@XZ endp

; MedicalSystem::MedicalSystem();
??0MedicalSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+1*8]
??0MedicalSystem@@QEAA@XZ endp

?_DESTRUCTOR@MedicalSystem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::~MedicalSystem();
??1MedicalSystem@@UEAA@XZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+2*8]
??1MedicalSystem@@UEAA@XZ endp

; MedicalSystem::init(class AnimationClass *, class Character *, class GameData *, class CharStats *);
?init@MedicalSystem@@QEAAXPEAVAnimationClass@@PEAVCharacter@@PEAVGameData@@PEAVCharStats@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+3*8]
?init@MedicalSystem@@QEAAXPEAVAnimationClass@@PEAVCharacter@@PEAVGameData@@PEAVCharStats@@@Z endp

?_NV_updateStats@MedicalSystem@@QEAAXXZ proc EXPORT
?_NV_updateStats@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::updateStats();
?updateStats@MedicalSystem@@UEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+4*8]
?updateStats@MedicalSystem@@UEAAXXZ endp

; MedicalSystem::notifyRaceChange(class GameData *);
?notifyRaceChange@MedicalSystem@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+5*8]
?notifyRaceChange@MedicalSystem@@QEAAXPEAVGameData@@@Z endp

; MedicalSystem::medicalUpdate(float);
?medicalUpdate@MedicalSystem@@QEAAXM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+6*8]
?medicalUpdate@MedicalSystem@@QEAAXM@Z endp

?_NV_periodicUpdate@MedicalSystem@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::periodicUpdate();
?periodicUpdate@MedicalSystem@@UEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+7*8]
?periodicUpdate@MedicalSystem@@UEAAXXZ endp

; MedicalSystem::scoreFirstAidNeed(bool);
?scoreFirstAidNeed@MedicalSystem@@QEBAM_N@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+8*8]
?scoreFirstAidNeed@MedicalSystem@@QEBAM_N@Z endp

; MedicalSystem::scoreJuryRigNeed(float);
?scoreJuryRigNeed@MedicalSystem@@QEBAMM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+9*8]
?scoreJuryRigNeed@MedicalSystem@@QEBAMM@Z endp

; MedicalSystem::isFullyRested();
?isFullyRested@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+10*8]
?isFullyRested@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::_setHealth(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?_setHealth@MedicalSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+11*8]
?_setHealth@MedicalSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp

; MedicalSystem::validateHealthValues();
?validateHealthValues@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+12*8]
?validateHealthValues@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::getLimbState(enum RobotLimbs::Limb);
?getLimbState@MedicalSystem@@QEBA?AW4LimbState@@W4Limb@RobotLimbs@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+13*8]
?getLimbState@MedicalSystem@@QEBA?AW4LimbState@@W4Limb@RobotLimbs@@@Z endp

; MedicalSystem::amputate(enum RobotLimbs::Limb, bool, const class Ogre::Vector3 &);
?amputate@MedicalSystem@@QEAAXW4Limb@RobotLimbs@@_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+14*8]
?amputate@MedicalSystem@@QEAAXW4Limb@RobotLimbs@@_NAEBVVector3@Ogre@@@Z endp

; MedicalSystem::crushLimb(enum RobotLimbs::Limb);
?crushLimb@MedicalSystem@@QEAAXW4Limb@RobotLimbs@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+15*8]
?crushLimb@MedicalSystem@@QEAAXW4Limb@RobotLimbs@@@Z endp

; MedicalSystem::isUselessNoLimbGuy();
?isUselessNoLimbGuy@MedicalSystem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+16*8]
?isUselessNoLimbGuy@MedicalSystem@@QEAA_NXZ endp

; MedicalSystem::recalculateStealthHinderance();
?recalculateStealthHinderance@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+17*8]
?recalculateStealthHinderance@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::getPart(enum RobotLimbs::Limb);
?getPart@MedicalSystem@@QEAAPEAVHealthPartStatus@1@W4Limb@RobotLimbs@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+18*8]
?getPart@MedicalSystem@@QEAAPEAVHealthPartStatus@1@W4Limb@RobotLimbs@@@Z endp

; MedicalSystem::getPart(unsigned __int64);
?getPart@MedicalSystem@@QEAAPEAVHealthPartStatus@1@_K@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+19*8]
?getPart@MedicalSystem@@QEAAPEAVHealthPartStatus@1@_K@Z endp

; MedicalSystem::getPart(enum MedicalSystem::HealthPartStatus::PartType, enum LeftRight);
?getPart@MedicalSystem@@QEAAPEAVHealthPartStatus@1@W4PartType@21@W4LeftRight@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+20*8]
?getPart@MedicalSystem@@QEAAPEAVHealthPartStatus@1@W4PartType@21@W4LeftRight@@@Z endp

; MedicalSystem::getPartCount();
?getPartCount@MedicalSystem@@QEBAHXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+21*8]
?getPartCount@MedicalSystem@@QEBAHXZ endp

; MedicalSystem::setRobotLimbItem(enum RobotLimbs::Limb, class Item *, bool);
?setRobotLimbItem@MedicalSystem@@QEAAXW4Limb@RobotLimbs@@PEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+22*8]
?setRobotLimbItem@MedicalSystem@@QEAAXW4Limb@RobotLimbs@@PEAVItem@@_N@Z endp

; MedicalSystem::hasRobotics();
?hasRobotics@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+23*8]
?hasRobotics@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::addArmour(class Armour *);
?addArmour@MedicalSystem@@QEAAXPEAVArmour@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+24*8]
?addArmour@MedicalSystem@@QEAAXPEAVArmour@@@Z endp

; MedicalSystem::removeArmour(class Item *);
?removeArmour@MedicalSystem@@QEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+25*8]
?removeArmour@MedicalSystem@@QEAAXPEAVItem@@@Z endp

; MedicalSystem::wearingUniformOf(class Faction *);
?wearingUniformOf@MedicalSystem@@QEAA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+26*8]
?wearingUniformOf@MedicalSystem@@QEAA_NPEAVFaction@@@Z endp

; MedicalSystem::serialise(class GameData *);
?serialise@MedicalSystem@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+27*8]
?serialise@MedicalSystem@@QEAAXPEAVGameData@@@Z endp

; MedicalSystem::load(class GameData *);
?load@MedicalSystem@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+28*8]
?load@MedicalSystem@@QEAAXPEAVGameData@@@Z endp

; MedicalSystem::addWound(bool, enum CutDirection, class Damages &, int &, class RootObject *, enum AttackDirection::Enum &, class Harpoon *);
?addWound@MedicalSystem@@QEAAPEAVGameData@@_NW4CutDirection@@AEAVDamages@@AEAHPEAVRootObject@@AEAW4Enum@AttackDirection@@PEAVHarpoon@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+29*8]
?addWound@MedicalSystem@@QEAAPEAVGameData@@_NW4CutDirection@@AEAVDamages@@AEAHPEAVRootObject@@AEAW4Enum@AttackDirection@@PEAVHarpoon@@@Z endp

; MedicalSystem::punchSomething(enum HitMaterialType, class Character *, class CombatTechniqueData *, int);
?punchSomething@MedicalSystem@@QEAAMW4HitMaterialType@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+30*8]
?punchSomething@MedicalSystem@@QEAAMW4HitMaterialType@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

; MedicalSystem::getBoneNameForBodypart(class GameData *);
?getBoneNameForBodypart@MedicalSystem@@SAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+31*8]
?getBoneNameForBodypart@MedicalSystem@@SAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameData@@@Z endp

; MedicalSystem::isFed();
?isFed@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+32*8]
?isFed@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::getMaxBlood();
?getMaxBlood@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+33*8]
?getMaxBlood@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::startKnockoutTimer();
?startKnockoutTimer@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+34*8]
?startKnockoutTimer@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::knockout(float);
?knockout@MedicalSystem@@QEAAXM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+35*8]
?knockout@MedicalSystem@@QEAAXM@Z endp

; MedicalSystem::knockoutForceTimer(float);
?knockoutForceTimer@MedicalSystem@@QEAAXM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+36*8]
?knockoutForceTimer@MedicalSystem@@QEAAXM@Z endp

; MedicalSystem::pointOfCollapseBloodloss();
?pointOfCollapseBloodloss@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+37*8]
?pointOfCollapseBloodloss@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::pointOfNoReturn();
?pointOfNoReturn@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+38*8]
?pointOfNoReturn@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::pointOfNoReturn_Hunger01(float);
?pointOfNoReturn_Hunger01@MedicalSystem@@QEBAMM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+39*8]
?pointOfNoReturn_Hunger01@MedicalSystem@@QEBAMM@Z endp

; MedicalSystem::isHungerKO();
?isHungerKO@MedicalSystem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+40*8]
?isHungerKO@MedicalSystem@@QEAA_NXZ endp

; MedicalSystem::getToughnessXpBonus();
?getToughnessXpBonus@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+41*8]
?getToughnessXpBonus@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::getHungerSpeedModifier();
?getHungerSpeedModifier@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+42*8]
?getHungerSpeedModifier@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::getHealthStatModifier(enum StatsEnumerated, bool, bool, bool, bool, bool, bool);
?getHealthStatModifier@MedicalSystem@@QEBAMW4StatsEnumerated@@_N11111@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+43*8]
?getHealthStatModifier@MedicalSystem@@QEBAMW4StatsEnumerated@@_N11111@Z endp

; MedicalSystem::_getRoboticsStatMult(enum StatsEnumerated);
?_getRoboticsStatMult@MedicalSystem@@QEBAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+44*8]
?_getRoboticsStatMult@MedicalSystem@@QEBAMW4StatsEnumerated@@@Z endp

; MedicalSystem::getMissingArmPenaltyMult();
?getMissingArmPenaltyMult@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+45*8]
?getMissingArmPenaltyMult@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::getDerivedHeadHealth();
?getDerivedHeadHealth@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+46*8]
?getDerivedHeadHealth@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::isCollapse(class MedicalSystem::HealthPartStatus *, float);
?isCollapse@MedicalSystem@@QEAA_NPEAVHealthPartStatus@1@M@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+47*8]
?isCollapse@MedicalSystem@@QEAA_NPEAVHealthPartStatus@1@M@Z endp

; MedicalSystem::getCollapseStage(class MedicalSystem::HealthPartStatus *, float);
?getCollapseStage@MedicalSystem@@QEAA?AW4CollapseStage@1@PEAVHealthPartStatus@1@M@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+48*8]
?getCollapseStage@MedicalSystem@@QEAA?AW4CollapseStage@1@PEAVHealthPartStatus@1@M@Z endp

; MedicalSystem::calculateDesiredPainAnimations();
?calculateDesiredPainAnimations@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+49*8]
?calculateDesiredPainAnimations@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::getMovementSpeedInjuryMultiplier();
?getMovementSpeedInjuryMultiplier@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+50*8]
?getMovementSpeedInjuryMultiplier@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::getStatRoboticsMultiplier(enum StatsEnumerated);
?getStatRoboticsMultiplier@MedicalSystem@@QEAAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+51*8]
?getStatRoboticsMultiplier@MedicalSystem@@QEAAMW4StatsEnumerated@@@Z endp

; MedicalSystem::getMovementSwimSpeedInjuryMultiplier();
?getMovementSwimSpeedInjuryMultiplier@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+52*8]
?getMovementSwimSpeedInjuryMultiplier@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::gettingEaten(float, bool);
?gettingEaten@MedicalSystem@@QEAA_NM_N@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+53*8]
?gettingEaten@MedicalSystem@@QEAA_NM_N@Z endp

; MedicalSystem::gettingAcidRain(float);
?gettingAcidRain@MedicalSystem@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+54*8]
?gettingAcidRain@MedicalSystem@@QEAA_NM@Z endp

; MedicalSystem::gettingAcidWater(float);
?gettingAcidWater@MedicalSystem@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+55*8]
?gettingAcidWater@MedicalSystem@@QEAA_NM@Z endp

; MedicalSystem::gettingAcidFeet(float);
?gettingAcidFeet@MedicalSystem@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+56*8]
?gettingAcidFeet@MedicalSystem@@QEAA_NM@Z endp

; MedicalSystem::gettingGassed(float);
?gettingGassed@MedicalSystem@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+57*8]
?gettingGassed@MedicalSystem@@QEAA_NM@Z endp

; MedicalSystem::gettingWindyface(float);
?gettingWindyface@MedicalSystem@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+58*8]
?gettingWindyface@MedicalSystem@@QEAA_NM@Z endp

; MedicalSystem::gettingBurnt(float);
?gettingBurnt@MedicalSystem@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+59*8]
?gettingBurnt@MedicalSystem@@QEAA_NM@Z endp

; MedicalSystem::applyFirstAid(float, class Item *, float, class Character *);
?applyFirstAid@MedicalSystem@@QEAA_NMPEAVItem@@MPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+60*8]
?applyFirstAid@MedicalSystem@@QEAA_NMPEAVItem@@MPEAVCharacter@@@Z endp

; MedicalSystem::applyDoctoring(float, class Item *, float, class Character *);
?applyDoctoring@MedicalSystem@@QEAA_NMPEAVItem@@MPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+61*8]
?applyDoctoring@MedicalSystem@@QEAA_NMPEAVItem@@MPEAVCharacter@@@Z endp

; MedicalSystem::applyRigging(float, class Item *, float);
?applyRigging@MedicalSystem@@QEAA_NMPEAVItem@@M@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+62*8]
?applyRigging@MedicalSystem@@QEAA_NMPEAVItem@@M@Z endp

; MedicalSystem::reassessCollapseMode(bool, bool);
?reassessCollapseMode@MedicalSystem@@QEAAX_N0@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+63*8]
?reassessCollapseMode@MedicalSystem@@QEAAX_N0@Z endp

; MedicalSystem::isUnconcious();
?isUnconcious@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+64*8]
?isUnconcious@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::isCrippled();
?isCrippled@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+65*8]
?isCrippled@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::isDead();
?isDead@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+66*8]
?isDead@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::hasAnArmToFightWith();
?hasAnArmToFightWith@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+67*8]
?hasAnArmToFightWith@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::hasFreshlySeveredALimb();
?hasFreshlySeveredALimb@MedicalSystem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+68*8]
?hasFreshlySeveredALimb@MedicalSystem@@QEAA_NXZ endp

; MedicalSystem::isReallyHungry();
?isReallyHungry@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+69*8]
?isReallyHungry@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::scoreTechnique(class CombatTechniqueData *);
?scoreTechnique@MedicalSystem@@QEAAMPEAVCombatTechniqueData@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+70*8]
?scoreTechnique@MedicalSystem@@QEAAMPEAVCombatTechniqueData@@@Z endp

; MedicalSystem::getMedicalGUIData(class DatapanelGUI *);
?getMedicalGUIData@MedicalSystem@@QEAAXPEAVDatapanelGUI@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+71*8]
?getMedicalGUIData@MedicalSystem@@QEAAXPEAVDatapanelGUI@@@Z endp

; MedicalSystem::isProbablyDying();
?isProbablyDying@MedicalSystem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+72*8]
?isProbablyDying@MedicalSystem@@QEAA_NXZ endp

; MedicalSystem::getOverallHealthRating();
?getOverallHealthRating@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+73*8]
?getOverallHealthRating@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::canGetUpWakeUp();
?canGetUpWakeUp@MedicalSystem@@QEAA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+74*8]
?canGetUpWakeUp@MedicalSystem@@QEAA_NXZ endp

; MedicalSystem::_reassessRagdollPartsAssumingWeJustClearedTheEntireRagdoll();
?_reassessRagdollPartsAssumingWeJustClearedTheEntireRagdoll@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+75*8]
?_reassessRagdollPartsAssumingWeJustClearedTheEntireRagdoll@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::isRightArmOk();
?isRightArmOk@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+76*8]
?isRightArmOk@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::isLeftArmOk();
?isLeftArmOk@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+77*8]
?isLeftArmOk@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::canIkick();
?canIkick@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+78*8]
?canIkick@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::isInBloodlossTrauma();
?isInBloodlossTrauma@MedicalSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+79*8]
?isInBloodlossTrauma@MedicalSystem@@QEBA_NXZ endp

; MedicalSystem::splatBlood(const class Damages &, enum CutDirection, enum AttackDirection::Enum);
?splatBlood@MedicalSystem@@QEAAXAEBVDamages@@W4CutDirection@@W4Enum@AttackDirection@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+80*8]
?splatBlood@MedicalSystem@@QEAAXAEBVDamages@@W4CutDirection@@W4Enum@AttackDirection@@@Z endp

; MedicalSystem::clearWeatherEffects();
?clearWeatherEffects@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+81*8]
?clearWeatherEffects@MedicalSystem@@QEAAXXZ endp

; MedicalSystem::getWeatherStatPenaltyMult();
?getWeatherStatPenaltyMult@MedicalSystem@@QEBAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+82*8]
?getWeatherStatPenaltyMult@MedicalSystem@@QEBAMXZ endp

; MedicalSystem::getWeatherStatPenalty(float);
?getWeatherStatPenalty@MedicalSystem@@QEBAHM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+83*8]
?getWeatherStatPenalty@MedicalSystem@@QEBAHM@Z endp

; MedicalSystem::calculateBleedRateForFX();
?calculateBleedRateForFX@MedicalSystem@@QEAAMXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+84*8]
?calculateBleedRateForFX@MedicalSystem@@QEAAMXZ endp

; MedicalSystem::bloodlossUpdate(float);
?bloodlossUpdate@MedicalSystem@@QEAAXM@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+85*8]
?bloodlossUpdate@MedicalSystem@@QEAAXM@Z endp

; MedicalSystem::drainMedkit(float, class Item *, float);
?drainMedkit@MedicalSystem@@QEBAXMPEAVItem@@M@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+86*8]
?drainMedkit@MedicalSystem@@QEBAXMPEAVItem@@M@Z endp

; MedicalSystem::applyDamage(class MedicalSystem::HealthPartStatus *, const class Damages &, bool, bool, const class Ogre::Vector3 &);
?applyDamage@MedicalSystem@@QEAAXPEAVHealthPartStatus@1@AEBVDamages@@_N2AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+87*8]
?applyDamage@MedicalSystem@@QEAAXPEAVHealthPartStatus@1@AEBVDamages@@_N2AEBVVector3@Ogre@@@Z endp

; MedicalSystem::ragdollPartCollapse(class MedicalSystem::HealthPartStatus *);
?ragdollPartCollapse@MedicalSystem@@QEAAXPEAVHealthPartStatus@1@@Z proc EXPORT
jmp function_pointers[_MedicalSystem_base+88*8]
?ragdollPartCollapse@MedicalSystem@@QEAAXPEAVHealthPartStatus@1@@Z endp

; MedicalSystem::updateDamageState();
?updateDamageState@MedicalSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedicalSystem_base+89*8]
?updateDamageState@MedicalSystem@@QEAAXXZ endp
