
?_CONSTRUCTOR@MedianFilter@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@MedianFilter@@QEAAPEAV1@XZ endp

; MedianFilter::MedianFilter();
??0MedianFilter@@QEAA@XZ proc EXPORT
jmp function_pointers[_MedianFilter_base+0*8]
??0MedianFilter@@QEAA@XZ endp

; MedianFilter::setup(int, int, bool);
?setup@MedianFilter@@QEAAXHH_N@Z proc EXPORT
jmp function_pointers[_MedianFilter_base+1*8]
?setup@MedianFilter@@QEAAXHH_N@Z endp

; MedianFilter::reset();
?reset@MedianFilter@@QEAAXXZ proc EXPORT
jmp function_pointers[_MedianFilter_base+2*8]
?reset@MedianFilter@@QEAAXXZ endp

; MedianFilter::applySilent(float);
?applySilent@MedianFilter@@QEAAXM@Z proc EXPORT
jmp function_pointers[_MedianFilter_base+3*8]
?applySilent@MedianFilter@@QEAAXM@Z endp

; MedianFilter::apply(float &);
?apply@MedianFilter@@QEAAXAEAM@Z proc EXPORT
jmp function_pointers[_MedianFilter_base+4*8]
?apply@MedianFilter@@QEAAXAEAM@Z endp

?_DESTRUCTOR@MedianFilter@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MedianFilter@@QEAAXXZ endp

; MedianFilter::~MedianFilter();
??1MedianFilter@@QEAA@XZ proc EXPORT
jmp function_pointers[_MedianFilter_base+5*8]
??1MedianFilter@@QEAA@XZ endp
