
?_CONSTRUCTOR@MeshDataLookup@@QEAAPEAV1@PEBVEntity@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@MeshDataLookup@@QEAAPEAV1@PEBVEntity@Ogre@@@Z endp

; MeshDataLookup::MeshDataLookup(const class Ogre::Entity *);
??0MeshDataLookup@@QEAA@PEBVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_MeshDataLookup_base+0*8]
??0MeshDataLookup@@QEAA@PEBVEntity@Ogre@@@Z endp

?_DESTRUCTOR@MeshDataLookup@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MeshDataLookup@@QEAAXXZ endp

; MeshDataLookup::~MeshDataLookup();
??1MeshDataLookup@@QEAA@XZ proc EXPORT
jmp function_pointers[_MeshDataLookup_base+1*8]
??1MeshDataLookup@@QEAA@XZ endp

; MeshDataLookup::init(const class Ogre::Entity *);
?init@MeshDataLookup@@QEAAXPEBVEntity@Ogre@@@Z proc EXPORT
jmp function_pointers[_MeshDataLookup_base+2*8]
?init@MeshDataLookup@@QEAAXPEBVEntity@Ogre@@@Z endp
