
?_CONSTRUCTOR@Box@MessageBoxManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Box@MessageBoxManager@@QEAAPEAV12@XZ endp

; MessageBoxManager::Box::Box();
??0Box@MessageBoxManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_MessageBoxManager_Box_base+0*8]
??0Box@MessageBoxManager@@QEAA@XZ endp

?_DESTRUCTOR@Box@MessageBoxManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Box@MessageBoxManager@@QEAAXXZ endp

; MessageBoxManager::Box::~Box();
??1Box@MessageBoxManager@@UEAA@XZ proc EXPORT
jmp function_pointers[_MessageBoxManager_Box_base+1*8]
??1Box@MessageBoxManager@@UEAA@XZ endp

; MessageBoxManager::Box::buttonClick(class MyGUI::Widget *);
?buttonClick@Box@MessageBoxManager@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_MessageBoxManager_Box_base+2*8]
?buttonClick@Box@MessageBoxManager@@QEAAXPEAVWidget@MyGUI@@@Z endp
