
?_CONSTRUCTOR@ModInfo@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@ModInfo@@QEAAPEAV1@AEBV1@@Z endp

; ModInfo::ModInfo(const class ModInfo &);
??0ModInfo@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_ModInfo_base+0*8]
??0ModInfo@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@ModInfo@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ModInfo@@QEAAPEAV1@XZ endp

; ModInfo::ModInfo();
??0ModInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_ModInfo_base+1*8]
??0ModInfo@@QEAA@XZ endp

; ModInfo::getLocale(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getLocale@ModInfo@@QEBA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_ModInfo_base+2*8]
?getLocale@ModInfo@@QEBA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

?_DESTRUCTOR@ModInfo@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ModInfo@@QEAAXXZ endp

; ModInfo::~ModInfo();
??1ModInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_ModInfo_base+3*8]
??1ModInfo@@QEAA@XZ endp

; ModInfo::operator=(const class ModInfo &);
??4ModInfo@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_ModInfo_base+4*8]
??4ModInfo@@QEAAAEAV0@AEBV0@@Z endp
