
?_CONSTRUCTOR@MotionFilter@@QEAAPEAV1@HMM@Z proc EXPORT
?_CONSTRUCTOR@MotionFilter@@QEAAPEAV1@HMM@Z endp

; MotionFilter::MotionFilter(int, float, float);
??0MotionFilter@@QEAA@HMM@Z proc EXPORT
jmp function_pointers[_MotionFilter_base+0*8]
??0MotionFilter@@QEAA@HMM@Z endp

; MotionFilter::SetHistoryBufferLength(int, float);
?SetHistoryBufferLength@MotionFilter@@QEAA_NHM@Z proc EXPORT
jmp function_pointers[_MotionFilter_base+1*8]
?SetHistoryBufferLength@MotionFilter@@QEAA_NHM@Z endp

; MotionFilter::Apply(float &);
?Apply@MotionFilter@@QEAAXAEAM@Z proc EXPORT
jmp function_pointers[_MotionFilter_base+2*8]
?Apply@MotionFilter@@QEAAXAEAM@Z endp

?_DESTRUCTOR@MotionFilter@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MotionFilter@@QEAAXXZ endp

; MotionFilter::~MotionFilter();
??1MotionFilter@@QEAA@XZ proc EXPORT
jmp function_pointers[_MotionFilter_base+3*8]
??1MotionFilter@@QEAA@XZ endp
