
?_NV_isNavMeshSector@NavInstance@@QEBA_NXZ proc EXPORT
?_NV_isNavMeshSector@NavInstance@@QEBA_NXZ endp

; NavInstance::isNavMeshSector();
?isNavMeshSector@NavInstance@@UEBA_NXZ proc EXPORT
jmp function_pointers[_NavInstance_base+0*8]
?isNavMeshSector@NavInstance@@UEBA_NXZ endp

?_CONSTRUCTOR@NavInstance@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NavInstance@@QEAAPEAV1@XZ endp

; NavInstance::NavInstance();
??0NavInstance@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavInstance_base+1*8]
??0NavInstance@@QEAA@XZ endp
