
?_CONSTRUCTOR@NavMeshMessage@NavMesh@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@NavMeshMessage@NavMesh@@QEAAPEAV12@XZ endp

; NavMesh::NavMeshMessage::NavMeshMessage();
??0NavMeshMessage@NavMesh@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMesh_NavMeshMessage_base+0*8]
??0NavMeshMessage@NavMesh@@QEAA@XZ endp

?_DESTRUCTOR@NavMeshMessage@NavMesh@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NavMeshMessage@NavMesh@@QEAAXXZ endp

; NavMesh::NavMeshMessage::~NavMeshMessage();
??1NavMeshMessage@NavMesh@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMesh_NavMeshMessage_base+1*8]
??1NavMeshMessage@NavMesh@@QEAA@XZ endp
