
; NavMeshSeeds::load();
?load@NavMeshSeeds@@QEAAXXZ proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+0*8]
?load@NavMeshSeeds@@QEAAXXZ endp

; NavMeshSeeds::save();
?save@NavMeshSeeds@@QEAAXXZ proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+1*8]
?save@NavMeshSeeds@@QEAAXXZ endp

; NavMeshSeeds::addSeedPoint(const class Ogre::Vector3 &, bool);
?addSeedPoint@NavMeshSeeds@@QEAAXAEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+2*8]
?addSeedPoint@NavMeshSeeds@@QEAAXAEBVVector3@Ogre@@_N@Z endp

; NavMeshSeeds::removeSeedPoints(const class Ogre::Vector3 &, float);
?removeSeedPoints@NavMeshSeeds@@QEAAHAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+3*8]
?removeSeedPoints@NavMeshSeeds@@QEAAHAEBVVector3@Ogre@@M@Z endp

; NavMeshSeeds::clearSeedPoints(class ZoneMap *);
?clearSeedPoints@NavMeshSeeds@@QEAAHPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+4*8]
?clearSeedPoints@NavMeshSeeds@@QEAAHPEAVZoneMap@@@Z endp

; NavMeshSeeds::removeIsland(const class Ogre::Vector3 &, float);
?removeIsland@NavMeshSeeds@@QEAAHAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+5*8]
?removeIsland@NavMeshSeeds@@QEAAHAEBVVector3@Ogre@@M@Z endp

; NavMeshSeeds::projectToTerrain(class ZoneMap *);
?projectToTerrain@NavMeshSeeds@@QEAAXPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+6*8]
?projectToTerrain@NavMeshSeeds@@QEAAXPEAVZoneMap@@@Z endp

; NavMeshSeeds::getSeedPoints(class ZoneMap *);
?getSeedPoints@NavMeshSeeds@@QEBAPEBV?$lektor@VVector3@Ogre@@@@PEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+7*8]
?getSeedPoints@NavMeshSeeds@@QEBAPEBV?$lektor@VVector3@Ogre@@@@PEAVZoneMap@@@Z endp

?_CONSTRUCTOR@NavMeshSeeds@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NavMeshSeeds@@QEAAPEAV1@XZ endp

; NavMeshSeeds::NavMeshSeeds();
??0NavMeshSeeds@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+8*8]
??0NavMeshSeeds@@QEAA@XZ endp

?_DESTRUCTOR@NavMeshSeeds@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NavMeshSeeds@@QEAAXXZ endp

; NavMeshSeeds::~NavMeshSeeds();
??1NavMeshSeeds@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMeshSeeds_base+9*8]
??1NavMeshSeeds@@QEAA@XZ endp
