
?_CONSTRUCTOR@BuildingInfo@NavMesh@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@BuildingInfo@NavMesh@@QEAAPEAV12@AEBU12@@Z endp

; NavMesh::BuildingInfo::BuildingInfo(const struct NavMesh::BuildingInfo &);
??0BuildingInfo@NavMesh@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_NavMesh_BuildingInfo_base+0*8]
??0BuildingInfo@NavMesh@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@BuildingInfo@NavMesh@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@BuildingInfo@NavMesh@@QEAAPEAV12@XZ endp

; NavMesh::BuildingInfo::BuildingInfo();
??0BuildingInfo@NavMesh@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMesh_BuildingInfo_base+1*8]
??0BuildingInfo@NavMesh@@QEAA@XZ endp

?_DESTRUCTOR@BuildingInfo@NavMesh@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildingInfo@NavMesh@@QEAAXXZ endp

; NavMesh::BuildingInfo::~BuildingInfo();
??1BuildingInfo@NavMesh@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMesh_BuildingInfo_base+2*8]
??1BuildingInfo@NavMesh@@QEAA@XZ endp

; NavMesh::BuildingInfo::operator=(const struct NavMesh::BuildingInfo &);
??4BuildingInfo@NavMesh@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_NavMesh_BuildingInfo_base+3*8]
??4BuildingInfo@NavMesh@@QEAAAEAU01@AEBU01@@Z endp
