
?_CONSTRUCTOR@TaskQueue@NavMeshGenerator@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TaskQueue@NavMeshGenerator@@QEAAPEAV12@XZ endp

; NavMeshGenerator::TaskQueue::TaskQueue();
??0TaskQueue@NavMeshGenerator@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMeshGenerator_TaskQueue_base+0*8]
??0TaskQueue@NavMeshGenerator@@QEAA@XZ endp

; NavMeshGenerator::TaskQueue::push(struct NavMeshGenerator::Task *);
?push@TaskQueue@NavMeshGenerator@@QEAAXPEAUTask@2@@Z proc EXPORT
jmp function_pointers[_NavMeshGenerator_TaskQueue_base+1*8]
?push@TaskQueue@NavMeshGenerator@@QEAAXPEAUTask@2@@Z endp

; NavMeshGenerator::TaskQueue::pop();
?pop@TaskQueue@NavMeshGenerator@@QEAAPEAUTask@2@XZ proc EXPORT
jmp function_pointers[_NavMeshGenerator_TaskQueue_base+2*8]
?pop@TaskQueue@NavMeshGenerator@@QEAAPEAUTask@2@XZ endp

?_DESTRUCTOR@TaskQueue@NavMeshGenerator@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TaskQueue@NavMeshGenerator@@QEAAXXZ endp

; NavMeshGenerator::TaskQueue::~TaskQueue();
??1TaskQueue@NavMeshGenerator@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMeshGenerator_TaskQueue_base+3*8]
??1TaskQueue@NavMeshGenerator@@QEAA@XZ endp
