
?_CONSTRUCTOR@Task@NavMeshGenerator@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Task@NavMeshGenerator@@QEAAPEAV12@XZ endp

; NavMeshGenerator::Task::Task();
??0Task@NavMeshGenerator@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMeshGenerator_Task_base+0*8]
??0Task@NavMeshGenerator@@QEAA@XZ endp

?_DESTRUCTOR@Task@NavMeshGenerator@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Task@NavMeshGenerator@@QEAAXXZ endp

; NavMeshGenerator::Task::~Task();
??1Task@NavMeshGenerator@@QEAA@XZ proc EXPORT
jmp function_pointers[_NavMeshGenerator_Task_base+1*8]
??1Task@NavMeshGenerator@@QEAA@XZ endp
