
?_CONSTRUCTOR@NewGameWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NewGameWindow@@QEAAPEAV1@XZ endp

; NewGameWindow::NewGameWindow();
??0NewGameWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_NewGameWindow_base+0*8]
??0NewGameWindow@@QEAA@XZ endp

?_DESTRUCTOR@NewGameWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NewGameWindow@@QEAAXXZ endp

; NewGameWindow::~NewGameWindow();
??1NewGameWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_NewGameWindow_base+1*8]
??1NewGameWindow@@UEAA@XZ endp

; NewGameWindow::setVisible(bool);
?setVisible@NewGameWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+2*8]
?setVisible@NewGameWindow@@QEAAX_N@Z endp

; NewGameWindow::getVisible();
?getVisible@NewGameWindow@@QEAA_NXZ proc EXPORT
jmp function_pointers[_NewGameWindow_base+3*8]
?getVisible@NewGameWindow@@QEAA_NXZ endp

; NewGameWindow::setRealPosition(float, float);
?setRealPosition@NewGameWindow@@QEAAXMM@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+4*8]
?setRealPosition@NewGameWindow@@QEAAXMM@Z endp

?_NV_setPosition@NewGameWindow@@QEAAXHH@Z proc EXPORT
?_NV_setPosition@NewGameWindow@@QEAAXHH@Z endp

; NewGameWindow::setPosition(int, int);
?setPosition@NewGameWindow@@UEAAXHH@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+5*8]
?setPosition@NewGameWindow@@UEAAXHH@Z endp

; NewGameWindow::showWindow(class MyGUI::Widget *);
?showWindow@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+6*8]
?showWindow@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_show@NewGameWindow@@QEAAX_N@Z proc EXPORT
?_NV_show@NewGameWindow@@QEAAX_N@Z endp

; NewGameWindow::show(bool);
?show@NewGameWindow@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+7*8]
?show@NewGameWindow@@UEAAX_N@Z endp

?_NV_update@NewGameWindow@@QEAAXXZ proc EXPORT
?_NV_update@NewGameWindow@@QEAAXXZ endp

; NewGameWindow::update();
?update@NewGameWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_NewGameWindow_base+8*8]
?update@NewGameWindow@@UEAAXXZ endp

; NewGameWindow::loadData();
?loadData@NewGameWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_NewGameWindow_base+9*8]
?loadData@NewGameWindow@@QEAAXXZ endp

; NewGameWindow::updateCurrentData();
?updateCurrentData@NewGameWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_NewGameWindow_base+10*8]
?updateCurrentData@NewGameWindow@@QEAAXXZ endp

; NewGameWindow::close(class MyGUI::Widget *);
?close@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+11*8]
?close@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; NewGameWindow::prevStart(class MyGUI::Widget *);
?prevStart@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+12*8]
?prevStart@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; NewGameWindow::nextStart(class MyGUI::Widget *);
?nextStart@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+13*8]
?nextStart@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; NewGameWindow::newGameStart(class MyGUI::Widget *);
?newGameStart@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+14*8]
?newGameStart@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; NewGameWindow::toggleAdvancedOptions(class MyGUI::Widget *);
?toggleAdvancedOptions@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_NewGameWindow_base+15*8]
?toggleAdvancedOptions@NewGameWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp
