
?_CONSTRUCTOR@NewGameOptionsWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NewGameOptionsWindow@@QEAAPEAV1@XZ endp

; NewGameOptionsWindow::NewGameOptionsWindow();
??0NewGameOptionsWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+0*8]
??0NewGameOptionsWindow@@QEAA@XZ endp

?_DESTRUCTOR@NewGameOptionsWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NewGameOptionsWindow@@QEAAXXZ endp

; NewGameOptionsWindow::~NewGameOptionsWindow();
??1NewGameOptionsWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+1*8]
??1NewGameOptionsWindow@@UEAA@XZ endp

; NewGameOptionsWindow::setVisible(bool);
?setVisible@NewGameOptionsWindow@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+2*8]
?setVisible@NewGameOptionsWindow@@QEAAX_N@Z endp

; NewGameOptionsWindow::getVisible();
?getVisible@NewGameOptionsWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+3*8]
?getVisible@NewGameOptionsWindow@@QEBA_NXZ endp

; NewGameOptionsWindow::setPosition(int, int);
?setPosition@NewGameOptionsWindow@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+4*8]
?setPosition@NewGameOptionsWindow@@QEAAXHH@Z endp

; NewGameOptionsWindow::update();
?update@NewGameOptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+5*8]
?update@NewGameOptionsWindow@@QEAAXXZ endp

; NewGameOptionsWindow::setOptions(const class GameplayOptions &);
?setOptions@NewGameOptionsWindow@@QEAAXAEBVGameplayOptions@@@Z proc EXPORT
jmp function_pointers[_NewGameOptionsWindow_base+6*8]
?setOptions@NewGameOptionsWindow@@QEAAXAEBVGameplayOptions@@@Z endp
