
?_CONSTRUCTOR@NxBox@@QEAAPEAV1@AEBVNxVec3@@0AEBVNxMat33@@@Z proc EXPORT
?_CONSTRUCTOR@NxBox@@QEAAPEAV1@AEBVNxVec3@@0AEBVNxMat33@@@Z endp

; NxBox::NxBox(const class NxVec3 &, const class NxVec3 &, const class NxMat33 &);
??0NxBox@@QEAA@AEBVNxVec3@@0AEBVNxMat33@@@Z proc EXPORT
jmp function_pointers[_NxBox_base+0*8]
??0NxBox@@QEAA@AEBVNxVec3@@0AEBVNxMat33@@@Z endp

?_CONSTRUCTOR@NxBox@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NxBox@@QEAAPEAV1@XZ endp

; NxBox::NxBox();
??0NxBox@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxBox_base+1*8]
??0NxBox@@QEAA@XZ endp

?_DESTRUCTOR@NxBox@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NxBox@@QEAAXXZ endp

; NxBox::~NxBox();
??1NxBox@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxBox_base+2*8]
??1NxBox@@QEAA@XZ endp

; NxBox::operator=(const class NxBox &);
??4NxBox@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxBox_base+3*8]
??4NxBox@@QEAAAEAV0@AEBV0@@Z endp
