
?_CONSTRUCTOR@NxMat33@@QEAAPEAV1@AEBVNxQuat@@@Z proc EXPORT
?_CONSTRUCTOR@NxMat33@@QEAAPEAV1@AEBVNxQuat@@@Z endp

; NxMat33::NxMat33(const class NxQuat &);
??0NxMat33@@QEAA@AEBVNxQuat@@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+0*8]
??0NxMat33@@QEAA@AEBVNxQuat@@@Z endp

?_CONSTRUCTOR@NxMat33@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@NxMat33@@QEAAPEAV1@AEBV1@@Z endp

; NxMat33::NxMat33(const class NxMat33 &);
??0NxMat33@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+1*8]
??0NxMat33@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@NxMat33@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NxMat33@@QEAAPEAV1@XZ endp

; NxMat33::NxMat33();
??0NxMat33@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxMat33_base+2*8]
??0NxMat33@@QEAA@XZ endp

?_DESTRUCTOR@NxMat33@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NxMat33@@QEAAXXZ endp

; NxMat33::~NxMat33();
??1NxMat33@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxMat33_base+3*8]
??1NxMat33@@QEAA@XZ endp

; NxMat33::operator=(const class NxMat33 &);
??4NxMat33@@QEAAAEBV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+4*8]
??4NxMat33@@QEAAAEBV0@AEBV0@@Z endp

; NxMat33::setRowMajor(const float *);
?setRowMajor@NxMat33@@QEAAXPEBM@Z proc EXPORT
jmp function_pointers[_NxMat33_base+5*8]
?setRowMajor@NxMat33@@QEAAXPEBM@Z endp

; NxMat33::getRowMajor(float *);
?getRowMajor@NxMat33@@QEBAXPEAM@Z proc EXPORT
jmp function_pointers[_NxMat33_base+6*8]
?getRowMajor@NxMat33@@QEBAXPEAM@Z endp

; NxMat33::getColumnMajor(float *);
?getColumnMajor@NxMat33@@QEBAXPEAM@Z proc EXPORT
jmp function_pointers[_NxMat33_base+7*8]
?getColumnMajor@NxMat33@@QEBAXPEAM@Z endp

; NxMat33::setRowMajorStride4(const float *);
?setRowMajorStride4@NxMat33@@QEAAXPEBM@Z proc EXPORT
jmp function_pointers[_NxMat33_base+8*8]
?setRowMajorStride4@NxMat33@@QEAAXPEBM@Z endp

; NxMat33::getRowMajorStride4(float *);
?getRowMajorStride4@NxMat33@@QEBAXPEAM@Z proc EXPORT
jmp function_pointers[_NxMat33_base+9*8]
?getRowMajorStride4@NxMat33@@QEBAXPEAM@Z endp

; NxMat33::getColumnMajorStride4(float *);
?getColumnMajorStride4@NxMat33@@QEBAXPEAM@Z proc EXPORT
jmp function_pointers[_NxMat33_base+10*8]
?getColumnMajorStride4@NxMat33@@QEBAXPEAM@Z endp

; NxMat33::setColumn(int, const class NxVec3 &);
?setColumn@NxMat33@@QEAAXHAEBVNxVec3@@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+11*8]
?setColumn@NxMat33@@QEAAXHAEBVNxVec3@@@Z endp

; NxMat33::getRow(int);
?getRow@NxMat33@@QEBA?AVNxVec3@@H@Z proc EXPORT
jmp function_pointers[_NxMat33_base+12*8]
?getRow@NxMat33@@QEBA?AVNxVec3@@H@Z endp

; NxMat33::getColumn(int);
?getColumn@NxMat33@@QEBA?AVNxVec3@@H@Z proc EXPORT
jmp function_pointers[_NxMat33_base+13*8]
?getColumn@NxMat33@@QEBA?AVNxVec3@@H@Z endp

; NxMat33::getColumn(int, class NxVec3 &);
?getColumn@NxMat33@@QEBAXHAEAVNxVec3@@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+14*8]
?getColumn@NxMat33@@QEBAXHAEAVNxVec3@@@Z endp

; NxMat33::operator()(int, int);
??RNxMat33@@QEBAAEBMHH@Z proc EXPORT
jmp function_pointers[_NxMat33_base+15*8]
??RNxMat33@@QEBAAEBMHH@Z endp

; NxMat33::isFinite();
?isFinite@NxMat33@@QEBA_NXZ proc EXPORT
jmp function_pointers[_NxMat33_base+16*8]
?isFinite@NxMat33@@QEBA_NXZ endp

; NxMat33::zero();
?zero@NxMat33@@QEAAXXZ proc EXPORT
jmp function_pointers[_NxMat33_base+17*8]
?zero@NxMat33@@QEAAXXZ endp

; NxMat33::id();
?id@NxMat33@@QEAAXXZ proc EXPORT
jmp function_pointers[_NxMat33_base+18*8]
?id@NxMat33@@QEAAXXZ endp

; NxMat33::fromQuat(const class NxQuat &);
?fromQuat@NxMat33@@QEAAXAEBVNxQuat@@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+19*8]
?fromQuat@NxMat33@@QEAAXAEBVNxQuat@@@Z endp

; NxMat33::toQuat(class NxQuat &);
?toQuat@NxMat33@@QEBAXAEAVNxQuat@@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+20*8]
?toQuat@NxMat33@@QEBAXAEAVNxQuat@@@Z endp

; NxMat33::operator*=(const class NxMat33 &);
??XNxMat33@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+21*8]
??XNxMat33@@QEAAAEAV0@AEBV0@@Z endp

; NxMat33::multiply(const class NxMat33 &, const class NxMat33 &);
?multiply@NxMat33@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_NxMat33_base+22*8]
?multiply@NxMat33@@QEAAXAEBV1@0@Z endp

; NxMat33::multiply(const class NxVec3 &, class NxVec3 &);
?multiply@NxMat33@@QEBAXAEBVNxVec3@@AEAV2@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+23*8]
?multiply@NxMat33@@QEBAXAEBVNxVec3@@AEAV2@@Z endp

; NxMat33::operator*(const class NxVec3 &);
??DNxMat33@@QEBA?AVNxVec3@@AEBV1@@Z proc EXPORT
jmp function_pointers[_NxMat33_base+24*8]
??DNxMat33@@QEBA?AVNxVec3@@AEBV1@@Z endp
