
?_DESTRUCTOR@NxUserTriggerReport@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NxUserTriggerReport@@QEAAXXZ endp

; NxUserTriggerReport::~NxUserTriggerReport();
??1NxUserTriggerReport@@UEAA@XZ proc EXPORT
jmp function_pointers[_NxUserTriggerReport_base+0*8]
??1NxUserTriggerReport@@UEAA@XZ endp

?_CONSTRUCTOR@NxUserTriggerReport@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NxUserTriggerReport@@QEAAPEAV1@XZ endp

; NxUserTriggerReport::NxUserTriggerReport();
??0NxUserTriggerReport@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxUserTriggerReport_base+1*8]
??0NxUserTriggerReport@@QEAA@XZ endp
