
?_DESTRUCTOR@NxUserControllerHitReport@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@NxUserControllerHitReport@@QEAAXXZ endp

; NxUserControllerHitReport::~NxUserControllerHitReport();
??1NxUserControllerHitReport@@UEAA@XZ proc EXPORT
jmp function_pointers[_NxUserControllerHitReport_base+0*8]
??1NxUserControllerHitReport@@UEAA@XZ endp

?_CONSTRUCTOR@NxUserControllerHitReport@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NxUserControllerHitReport@@QEAAPEAV1@XZ endp

; NxUserControllerHitReport::NxUserControllerHitReport();
??0NxUserControllerHitReport@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxUserControllerHitReport_base+1*8]
??0NxUserControllerHitReport@@QEAA@XZ endp
