
?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@AEBV1@@Z endp

; NxVec3::NxVec3(const class NxVec3 &);
??0NxVec3@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+0*8]
??0NxVec3@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@QEBM@Z proc EXPORT
?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@QEBM@Z endp

; NxVec3::NxVec3(const float *);
??0NxVec3@@QEAA@QEBM@Z proc EXPORT
jmp function_pointers[_NxVec3_base+1*8]
??0NxVec3@@QEAA@QEBM@Z endp

?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@MMM@Z proc EXPORT
?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@MMM@Z endp

; NxVec3::NxVec3(float, float, float);
??0NxVec3@@QEAA@MMM@Z proc EXPORT
jmp function_pointers[_NxVec3_base+2*8]
??0NxVec3@@QEAA@MMM@Z endp

?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@M@Z proc EXPORT
?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@M@Z endp

; NxVec3::NxVec3(float);
??0NxVec3@@QEAA@M@Z proc EXPORT
jmp function_pointers[_NxVec3_base+3*8]
??0NxVec3@@QEAA@M@Z endp

?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@NxVec3@@QEAAPEAV1@XZ endp

; NxVec3::NxVec3();
??0NxVec3@@QEAA@XZ proc EXPORT
jmp function_pointers[_NxVec3_base+4*8]
??0NxVec3@@QEAA@XZ endp

; NxVec3::operator=(const class NxVec3 &);
??4NxVec3@@QEAAAEBV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+5*8]
??4NxVec3@@QEAAAEBV0@AEBV0@@Z endp

; NxVec3::operator[](int);
??ANxVec3@@QEAAAEAMH@Z proc EXPORT
jmp function_pointers[_NxVec3_base+6*8]
??ANxVec3@@QEAAAEAMH@Z endp

; NxVec3::operator==(const class NxVec3 &);
??8NxVec3@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+7*8]
??8NxVec3@@QEBA_NAEBV0@@Z endp

; NxVec3::operator!=(const class NxVec3 &);
??9NxVec3@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+8*8]
??9NxVec3@@QEBA_NAEBV0@@Z endp

; NxVec3::set(float, float, float);
?set@NxVec3@@QEAAXMMM@Z proc EXPORT
jmp function_pointers[_NxVec3_base+9*8]
?set@NxVec3@@QEAAXMMM@Z endp

; NxVec3::set(const float *);
?set@NxVec3@@QEAAXPEBM@Z proc EXPORT
jmp function_pointers[_NxVec3_base+10*8]
?set@NxVec3@@QEAAXPEBM@Z endp

; NxVec3::zero();
?zero@NxVec3@@QEAAXXZ proc EXPORT
jmp function_pointers[_NxVec3_base+11*8]
?zero@NxVec3@@QEAAXXZ endp

; NxVec3::isZero();
?isZero@NxVec3@@QEBAHXZ proc EXPORT
jmp function_pointers[_NxVec3_base+12*8]
?isZero@NxVec3@@QEBAHXZ endp

; NxVec3::add(const class NxVec3 &, const class NxVec3 &);
?add@NxVec3@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_NxVec3_base+13*8]
?add@NxVec3@@QEAAXAEBV1@0@Z endp

; NxVec3::subtract(const class NxVec3 &, const class NxVec3 &);
?subtract@NxVec3@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_NxVec3_base+14*8]
?subtract@NxVec3@@QEAAXAEBV1@0@Z endp

; NxVec3::multiplyAdd(float, const class NxVec3 &, const class NxVec3 &);
?multiplyAdd@NxVec3@@QEAAXMAEBV1@0@Z proc EXPORT
jmp function_pointers[_NxVec3_base+15*8]
?multiplyAdd@NxVec3@@QEAAXMAEBV1@0@Z endp

; NxVec3::normalize();
?normalize@NxVec3@@QEAAMXZ proc EXPORT
jmp function_pointers[_NxVec3_base+16*8]
?normalize@NxVec3@@QEAAMXZ endp

; NxVec3::setMagnitude(float);
?setMagnitude@NxVec3@@QEAAXM@Z proc EXPORT
jmp function_pointers[_NxVec3_base+17*8]
?setMagnitude@NxVec3@@QEAAXM@Z endp

; NxVec3::closestAxis();
?closestAxis@NxVec3@@QEBAIXZ proc EXPORT
jmp function_pointers[_NxVec3_base+18*8]
?closestAxis@NxVec3@@QEBAIXZ endp

; NxVec3::isFinite();
?isFinite@NxVec3@@QEBA_NXZ proc EXPORT
jmp function_pointers[_NxVec3_base+19*8]
?isFinite@NxVec3@@QEBA_NXZ endp

; NxVec3::dot(const class NxVec3 &);
?dot@NxVec3@@QEBAMAEBV1@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+20*8]
?dot@NxVec3@@QEBAMAEBV1@@Z endp

; NxVec3::magnitude();
?magnitude@NxVec3@@QEBAMXZ proc EXPORT
jmp function_pointers[_NxVec3_base+21*8]
?magnitude@NxVec3@@QEBAMXZ endp

; NxVec3::magnitudeSquared();
?magnitudeSquared@NxVec3@@QEBAMXZ proc EXPORT
jmp function_pointers[_NxVec3_base+22*8]
?magnitudeSquared@NxVec3@@QEBAMXZ endp

; NxVec3::cross(const class NxVec3 &, const class NxVec3 &);
?cross@NxVec3@@QEAAXAEBV1@0@Z proc EXPORT
jmp function_pointers[_NxVec3_base+23*8]
?cross@NxVec3@@QEAAXAEBV1@0@Z endp

; NxVec3::equals(const class NxVec3 &, float);
?equals@NxVec3@@QEBA_NAEBV1@M@Z proc EXPORT
jmp function_pointers[_NxVec3_base+24*8]
?equals@NxVec3@@QEBA_NAEBV1@M@Z endp

; NxVec3::operator-();
??GNxVec3@@QEBA?AV0@XZ proc EXPORT
jmp function_pointers[_NxVec3_base+25*8]
??GNxVec3@@QEBA?AV0@XZ endp

; NxVec3::operator+(const class NxVec3 &);
??HNxVec3@@QEBA?AV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+26*8]
??HNxVec3@@QEBA?AV0@AEBV0@@Z endp

; NxVec3::operator+=(const class NxVec3 &);
??YNxVec3@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+27*8]
??YNxVec3@@QEAAAEAV0@AEBV0@@Z endp

; NxVec3::operator-=(const class NxVec3 &);
??ZNxVec3@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+28*8]
??ZNxVec3@@QEAAAEAV0@AEBV0@@Z endp

; NxVec3::operator*=(float);
??XNxVec3@@QEAAAEAV0@M@Z proc EXPORT
jmp function_pointers[_NxVec3_base+29*8]
??XNxVec3@@QEAAAEAV0@M@Z endp

; NxVec3::operator^(const class NxVec3 &);
??TNxVec3@@QEBA?AV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_NxVec3_base+30*8]
??TNxVec3@@QEBA?AV0@AEBV0@@Z endp
