
?_CONSTRUCTOR@OpenSaveFileDialog@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@OpenSaveFileDialog@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z endp

; OpenSaveFileDialog::OpenSaveFileDialog(class MyGUI::Widget *);
??0OpenSaveFileDialog@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+0*8]
??0OpenSaveFileDialog@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@OpenSaveFileDialog@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OpenSaveFileDialog@@QEAAXXZ endp

; OpenSaveFileDialog::~OpenSaveFileDialog();
??1OpenSaveFileDialog@@UEAA@XZ proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+1*8]
??1OpenSaveFileDialog@@UEAA@XZ endp

; OpenSaveFileDialog::setVisible(bool);
?setVisible@OpenSaveFileDialog@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+2*8]
?setVisible@OpenSaveFileDialog@@QEAAX_N@Z endp

; OpenSaveFileDialog::getVisible();
?getVisible@OpenSaveFileDialog@@QEBA_NXZ proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+3*8]
?getVisible@OpenSaveFileDialog@@QEBA_NXZ endp

; OpenSaveFileDialog::setDialogInfo(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?setDialogInfo@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_N@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+4*8]
?setDialogInfo@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_N@Z endp

; OpenSaveFileDialog::setCurrentFolder(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCurrentFolder@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+5*8]
?setCurrentFolder@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; OpenSaveFileDialog::getCurrentFolder();
?getCurrentFolder@OpenSaveFileDialog@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+6*8]
?getCurrentFolder@OpenSaveFileDialog@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; OpenSaveFileDialog::setFileName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setFileName@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+7*8]
?setFileName@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; OpenSaveFileDialog::getFileName();
?getFileName@OpenSaveFileDialog@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+8*8]
?getFileName@OpenSaveFileDialog@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; symbol is too long
; ?setRecentFolders@OpenSaveFileDialog@@QEAAXAEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$STLAllocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z
; OpenSaveFileDialog::setRecentFolders(const class std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,Ogre::STLAllocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,Ogre::CategorisedAllocPolicy<0> > > &);
OpenSaveFileDialog_setRecentFolders_PLACEHOLDER proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+9*8]
OpenSaveFileDialog_setRecentFolders_PLACEHOLDER endp

; OpenSaveFileDialog::setFileMask(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setFileMask@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+10*8]
?setFileMask@OpenSaveFileDialog@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; OpenSaveFileDialog::getFileMask();
?getFileMask@OpenSaveFileDialog@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+11*8]
?getFileMask@OpenSaveFileDialog@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; OpenSaveFileDialog::notifyDirectoryComboAccept(class MyGUI::ComboBox *, unsigned __int64);
?notifyDirectoryComboAccept@OpenSaveFileDialog@@QEAAXPEAVComboBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+12*8]
?notifyDirectoryComboAccept@OpenSaveFileDialog@@QEAAXPEAVComboBox@MyGUI@@_K@Z endp

; OpenSaveFileDialog::notifyDirectoryComboChangePosition(class MyGUI::ComboBox *, unsigned __int64);
?notifyDirectoryComboChangePosition@OpenSaveFileDialog@@QEAAXPEAVComboBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+13*8]
?notifyDirectoryComboChangePosition@OpenSaveFileDialog@@QEAAXPEAVComboBox@MyGUI@@_K@Z endp

; OpenSaveFileDialog::notifyListChangePosition(class MyGUI::ListBox *, unsigned __int64);
?notifyListChangePosition@OpenSaveFileDialog@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+14*8]
?notifyListChangePosition@OpenSaveFileDialog@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; OpenSaveFileDialog::notifyListSelectAccept(class MyGUI::ListBox *, unsigned __int64);
?notifyListSelectAccept@OpenSaveFileDialog@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+15*8]
?notifyListSelectAccept@OpenSaveFileDialog@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; OpenSaveFileDialog::closeWindow(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeWindow@OpenSaveFileDialog@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+16*8]
?closeWindow@OpenSaveFileDialog@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; OpenSaveFileDialog::update();
?update@OpenSaveFileDialog@@QEAAXXZ proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+17*8]
?update@OpenSaveFileDialog@@QEAAXXZ endp

; OpenSaveFileDialog::accept(class MyGUI::Widget *);
?accept@OpenSaveFileDialog@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+18*8]
?accept@OpenSaveFileDialog@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OpenSaveFileDialog::cancel(class MyGUI::Widget *);
?cancel@OpenSaveFileDialog@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+19*8]
?cancel@OpenSaveFileDialog@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OpenSaveFileDialog::upFolder(class MyGUI::Widget *);
?upFolder@OpenSaveFileDialog@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OpenSaveFileDialog_base+20*8]
?upFolder@OpenSaveFileDialog@@QEAAXPEAVWidget@MyGUI@@@Z endp
