
; OptionsWindow::getSingleton();
?getSingleton@OptionsWindow@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+0*8]
?getSingleton@OptionsWindow@@SAPEAV1@XZ endp

?_NV_show@OptionsWindow@@QEAAX_N@Z proc EXPORT
?_NV_show@OptionsWindow@@QEAAX_N@Z endp

; OptionsWindow::show(bool);
?show@OptionsWindow@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+1*8]
?show@OptionsWindow@@UEAAX_N@Z endp

; OptionsWindow::show();
?show@OptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+2*8]
?show@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::hide();
?hide@OptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+3*8]
?hide@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::toggle();
?toggle@OptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+4*8]
?toggle@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::isVisible();
?isVisible@OptionsWindow@@QEAA_NXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+5*8]
?isVisible@OptionsWindow@@QEAA_NXZ endp

; OptionsWindow::waitingForKey();
?waitingForKey@OptionsWindow@@QEAA_NXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+6*8]
?waitingForKey@OptionsWindow@@QEAA_NXZ endp

; OptionsWindow::setKey(const enum OIS::KeyCode &);
?setKey@OptionsWindow@@QEAAXAEBW4KeyCode@OIS@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+7*8]
?setKey@OptionsWindow@@QEAAXAEBW4KeyCode@OIS@@@Z endp

?_NV_update@OptionsWindow@@QEAAXXZ proc EXPORT
?_NV_update@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::update();
?update@OptionsWindow@@UEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+8*8]
?update@OptionsWindow@@UEAAXXZ endp

?_CONSTRUCTOR@OptionsWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@OptionsWindow@@QEAAPEAV1@XZ endp

; OptionsWindow::OptionsWindow();
??0OptionsWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+9*8]
??0OptionsWindow@@QEAA@XZ endp

?_DESTRUCTOR@OptionsWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::~OptionsWindow();
??1OptionsWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+10*8]
??1OptionsWindow@@UEAA@XZ endp

; OptionsWindow::saveLocationChanged(class DataPanelLine *);
?saveLocationChanged@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+11*8]
?saveLocationChanged@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::changeFontSize(class DataPanelLine *);
?changeFontSize@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+12*8]
?changeFontSize@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::changeVolume(class DataPanelLine *);
?changeVolume@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+13*8]
?changeVolume@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::toggleNames(class DataPanelLine *);
?toggleNames@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+14*8]
?toggleNames@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::resetTutorials(class DataPanelLine *);
?resetTutorials@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+15*8]
?resetTutorials@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::toggleTutorials(class DataPanelLine *);
?toggleTutorials@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+16*8]
?toggleTutorials@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::changeDistances(class DataPanelLine *);
?changeDistances@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+17*8]
?changeDistances@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::toggleCompositor(class DataPanelLine *);
?toggleCompositor@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+18*8]
?toggleCompositor@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::resetAllKeys(class DataPanelLine *);
?resetAllKeys@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+19*8]
?resetAllKeys@OptionsWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; OptionsWindow::saveOptions();
?saveOptions@OptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+20*8]
?saveOptions@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::create();
?create@OptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+21*8]
?create@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::updateResolutions();
?updateResolutions@OptionsWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsWindow_base+22*8]
?updateResolutions@OptionsWindow@@QEAAXXZ endp

; OptionsWindow::closeButton(class MyGUI::Widget *);
?closeButton@OptionsWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OptionsWindow_base+23*8]
?closeButton@OptionsWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp
