
?_CONSTRUCTOR@OptionsHolder@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@OptionsHolder@@QEAAPEAV1@XZ endp

; OptionsHolder::OptionsHolder();
??0OptionsHolder@@QEAA@XZ proc EXPORT
jmp function_pointers[_OptionsHolder_base+0*8]
??0OptionsHolder@@QEAA@XZ endp

; OptionsHolder::enabledCivilians();
?enabledCivilians@OptionsHolder@@QEAA_NXZ proc EXPORT
jmp function_pointers[_OptionsHolder_base+1*8]
?enabledCivilians@OptionsHolder@@QEAA_NXZ endp

; OptionsHolder::characterMultithreadingEnabled();
?characterMultithreadingEnabled@OptionsHolder@@QEAA_NXZ proc EXPORT
jmp function_pointers[_OptionsHolder_base+2*8]
?characterMultithreadingEnabled@OptionsHolder@@QEAA_NXZ endp

; OptionsHolder::compositiorEnabled(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?compositiorEnabled@OptionsHolder@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_OptionsHolder_base+3*8]
?compositiorEnabled@OptionsHolder@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; OptionsHolder::loadCompositorSettings();
?loadCompositorSettings@OptionsHolder@@QEAAXXZ proc EXPORT
jmp function_pointers[_OptionsHolder_base+4*8]
?loadCompositorSettings@OptionsHolder@@QEAAXXZ endp

?_DESTRUCTOR@OptionsHolder@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OptionsHolder@@QEAAXXZ endp

; OptionsHolder::~OptionsHolder();
??1OptionsHolder@@QEAA@XZ proc EXPORT
jmp function_pointers[_OptionsHolder_base+5*8]
??1OptionsHolder@@QEAA@XZ endp
