
?_CONSTRUCTOR@OrderData@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@OrderData@@QEAAPEAV1@XZ endp

; OrderData::OrderData();
??0OrderData@@QEAA@XZ proc EXPORT
jmp function_pointers[_OrderData_base+0*8]
??0OrderData@@QEAA@XZ endp

; OrderData::set(const class Tasker *, int, bool);
?set@OrderData@@QEAAXPEBVTasker@@H_N@Z proc EXPORT
jmp function_pointers[_OrderData_base+1*8]
?set@OrderData@@QEAAXPEBVTasker@@H_N@Z endp

; OrderData::updateText();
?updateText@OrderData@@QEAAXXZ proc EXPORT
jmp function_pointers[_OrderData_base+2*8]
?updateText@OrderData@@QEAAXXZ endp

?_DESTRUCTOR@OrderData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OrderData@@QEAAXXZ endp

; OrderData::~OrderData();
??1OrderData@@QEAA@XZ proc EXPORT
jmp function_pointers[_OrderData_base+3*8]
??1OrderData@@QEAA@XZ endp

; OrderData::operator=(const class OrderData &);
??4OrderData@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_OrderData_base+4*8]
??4OrderData@@QEAAAEAV0@AEBV0@@Z endp
