
?_CONSTRUCTOR@OrdersPanel@@QEAAPEAV1@PEAVMainBarGUI@@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@OrdersPanel@@QEAAPEAV1@PEAVMainBarGUI@@PEAVWidget@MyGUI@@@Z endp

; OrdersPanel::OrdersPanel(class MainBarGUI *, class MyGUI::Widget *);
??0OrdersPanel@@QEAA@PEAVMainBarGUI@@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+0*8]
??0OrdersPanel@@QEAA@PEAVMainBarGUI@@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@OrdersPanel@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OrdersPanel@@QEAAXXZ endp

; OrdersPanel::~OrdersPanel();
??1OrdersPanel@@QEAA@XZ proc EXPORT
jmp function_pointers[_OrdersPanel_base+1*8]
??1OrdersPanel@@QEAA@XZ endp

; OrdersPanel::update(class Character *);
?update@OrdersPanel@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+2*8]
?update@OrdersPanel@@QEAAXPEAVCharacter@@@Z endp

; OrdersPanel::clear();
?clear@OrdersPanel@@QEAAXXZ proc EXPORT
jmp function_pointers[_OrdersPanel_base+3*8]
?clear@OrdersPanel@@QEAAXXZ endp

; OrdersPanel::command(int);
?command@OrdersPanel@@QEAAXH@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+4*8]
?command@OrdersPanel@@QEAAXH@Z endp

; OrdersPanel::refreshOrders();
?refreshOrders@OrdersPanel@@QEAAXXZ proc EXPORT
jmp function_pointers[_OrdersPanel_base+5*8]
?refreshOrders@OrdersPanel@@QEAAXXZ endp

; OrdersPanel::moveJob(int, int);
?moveJob@OrdersPanel@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+6*8]
?moveJob@OrdersPanel@@QEAAXHH@Z endp

; OrdersPanel::removeJob(class OrderData *);
?removeJob@OrdersPanel@@QEAAXPEAVOrderData@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+7*8]
?removeJob@OrdersPanel@@QEAAXPEAVOrderData@@@Z endp

; OrdersPanel::notifyStartDropOrder(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool &);
?notifyStartDropOrder@OrdersPanel@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+8*8]
?notifyStartDropOrder@OrdersPanel@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z endp

; OrdersPanel::notifyRequestDropOrder(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool &);
?notifyRequestDropOrder@OrdersPanel@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+9*8]
?notifyRequestDropOrder@OrdersPanel@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z endp

; OrdersPanel::notifyEndDropOrder(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool);
?notifyEndDropOrder@OrdersPanel@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@_N@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+10*8]
?notifyEndDropOrder@OrdersPanel@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@_N@Z endp

; OrdersPanel::toggleStealth(class MyGUI::Widget *);
?toggleStealth@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+11*8]
?toggleStealth@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::toggleRanged(class MyGUI::Widget *);
?toggleRanged@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+12*8]
?toggleRanged@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::setSpeed(enum MoveSpeed);
?setSpeed@OrdersPanel@@QEAAXW4MoveSpeed@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+13*8]
?setSpeed@OrdersPanel@@QEAAXW4MoveSpeed@@@Z endp

; OrdersPanel::setSpeedImage(enum MoveSpeed);
?setSpeedImage@OrdersPanel@@QEAAXW4MoveSpeed@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+14*8]
?setSpeedImage@OrdersPanel@@QEAAXW4MoveSpeed@@@Z endp

; OrdersPanel::speedPrevious(class MyGUI::Widget *);
?speedPrevious@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+15*8]
?speedPrevious@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::speedNext(class MyGUI::Widget *);
?speedNext@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+16*8]
?speedNext@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::blockmodeButton(class MyGUI::Widget *);
?blockmodeButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+17*8]
?blockmodeButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::holdButtonCallback(class MyGUI::Widget *);
?holdButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+18*8]
?holdButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::passiveButtonCallback(class MyGUI::Widget *);
?passiveButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+19*8]
?passiveButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::chaseButtonCallback(class MyGUI::Widget *);
?chaseButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+20*8]
?chaseButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::tauntButtonCallback(class MyGUI::Widget *);
?tauntButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+21*8]
?tauntButtonCallback@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::medicButton(class MyGUI::Widget *);
?medicButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+22*8]
?medicButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::liftButton(class MyGUI::Widget *);
?liftButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+23*8]
?liftButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrdersPanel::prospectingButton(class MyGUI::Widget *);
?prospectingButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersPanel_base+24*8]
?prospectingButton@OrdersPanel@@QEAAXPEAVWidget@MyGUI@@@Z endp
