
?_CONSTRUCTOR@OrdersItemBox@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@OrdersItemBox@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z endp

; OrdersItemBox::OrdersItemBox(class MyGUI::Widget *);
??0OrdersItemBox@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrdersItemBox_base+0*8]
??0OrdersItemBox@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@OrdersItemBox@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OrdersItemBox@@QEAAXXZ endp

; OrdersItemBox::~OrdersItemBox();
??1OrdersItemBox@@UEAA@XZ proc EXPORT
jmp function_pointers[_OrdersItemBox_base+1*8]
??1OrdersItemBox@@UEAA@XZ endp
