
?_CONSTRUCTOR@OrderCellView@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@OrderCellView@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z endp

; OrderCellView::OrderCellView(class MyGUI::Widget *);
??0OrderCellView@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrderCellView_base+0*8]
??0OrderCellView@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@OrderCellView@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@OrderCellView@@QEAAXXZ endp

; OrderCellView::~OrderCellView();
??1OrderCellView@@UEAA@XZ proc EXPORT
jmp function_pointers[_OrderCellView_base+1*8]
??1OrderCellView@@UEAA@XZ endp

; OrderCellView::update(const struct MyGUI::IBDrawItemInfo &, class OrderData *);
?update@OrderCellView@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVOrderData@@@Z proc EXPORT
jmp function_pointers[_OrderCellView_base+2*8]
?update@OrderCellView@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVOrderData@@@Z endp

; OrderCellView::getCellDimension(class MyGUI::Widget *, struct MyGUI::types::TCoord<int> &, bool);
?getCellDimension@OrderCellView@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@3@_N@Z proc EXPORT
jmp function_pointers[_OrderCellView_base+3*8]
?getCellDimension@OrderCellView@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@3@_N@Z endp

; OrderCellView::getWidget();
?getWidget@OrderCellView@@QEBAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_OrderCellView_base+4*8]
?getWidget@OrderCellView@@QEBAPEAVWidget@MyGUI@@XZ endp

; OrderCellView::onRemove(class MyGUI::Widget *);
?onRemove@OrderCellView@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_OrderCellView_base+5*8]
?onRemove@OrderCellView@@QEAAXPEAVWidget@MyGUI@@@Z endp

; OrderCellView::resize();
?resize@OrderCellView@@QEAAXXZ proc EXPORT
jmp function_pointers[_OrderCellView_base+6*8]
?resize@OrderCellView@@QEAAXXZ endp
