
?_CONSTRUCTOR@ParticlePool@@QEAAPEAV1@HM@Z proc EXPORT
?_CONSTRUCTOR@ParticlePool@@QEAAPEAV1@HM@Z endp

; ParticlePool::ParticlePool(int, float);
??0ParticlePool@@QEAA@HM@Z proc EXPORT
jmp function_pointers[_ParticlePool_base+0*8]
??0ParticlePool@@QEAA@HM@Z endp

?_DESTRUCTOR@ParticlePool@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ParticlePool@@QEAAXXZ endp

; ParticlePool::~ParticlePool();
??1ParticlePool@@QEAA@XZ proc EXPORT
jmp function_pointers[_ParticlePool_base+1*8]
??1ParticlePool@@QEAA@XZ endp

; ParticlePool::init();
?init@ParticlePool@@QEAAXXZ proc EXPORT
jmp function_pointers[_ParticlePool_base+2*8]
?init@ParticlePool@@QEAAXXZ endp

; ParticlePool::destroy();
?destroy@ParticlePool@@QEAAXXZ proc EXPORT
jmp function_pointers[_ParticlePool_base+3*8]
?destroy@ParticlePool@@QEAAXXZ endp

; ParticlePool::getSize();
?getSize@ParticlePool@@QEBAHXZ proc EXPORT
jmp function_pointers[_ParticlePool_base+4*8]
?getSize@ParticlePool@@QEBAHXZ endp

; ParticlePool::addParticle(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Ogre::SceneNode *);
?addParticle@ParticlePool@@QEAA_NPEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVSceneNode@4@@Z proc EXPORT
jmp function_pointers[_ParticlePool_base+5*8]
?addParticle@ParticlePool@@QEAA_NPEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVSceneNode@4@@Z endp

; ParticlePool::update();
?update@ParticlePool@@QEAAXXZ proc EXPORT
jmp function_pointers[_ParticlePool_base+6*8]
?update@ParticlePool@@QEAAXXZ endp

; ParticlePool::shiftParticles(const class Ogre::Vector3 &);
?shiftParticles@ParticlePool@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ParticlePool_base+7*8]
?shiftParticles@ParticlePool@@QEAAXAEBVVector3@Ogre@@@Z endp
