
?_CONSTRUCTOR@physHit@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@physHit@@QEAAPEAV1@AEBV1@@Z endp

; physHit::physHit(const class physHit &);
??0physHit@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_physHit_base+0*8]
??0physHit@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@physHit@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@physHit@@QEAAPEAV1@H@Z endp

; physHit::physHit(int);
??0physHit@@QEAA@H@Z proc EXPORT
jmp function_pointers[_physHit_base+1*8]
??0physHit@@QEAA@H@Z endp

?_CONSTRUCTOR@physHit@@QEAAPEAV1@_N0M@Z proc EXPORT
?_CONSTRUCTOR@physHit@@QEAAPEAV1@_N0M@Z endp

; physHit::physHit(bool, bool, float);
??0physHit@@QEAA@_N0M@Z proc EXPORT
jmp function_pointers[_physHit_base+2*8]
??0physHit@@QEAA@_N0M@Z endp

; physHit::operator=(const class physHit &);
??4physHit@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_physHit_base+3*8]
??4physHit@@QEAAAEAV0@AEBV0@@Z endp

; physHit::traceWasAborted();
?traceWasAborted@physHit@@QEBA_NXZ proc EXPORT
jmp function_pointers[_physHit_base+4*8]
?traceWasAborted@physHit@@QEBA_NXZ endp

; physHit::operator bool();
??BphysHit@@QEBA_NXZ proc EXPORT
jmp function_pointers[_physHit_base+5*8]
??BphysHit@@QEBA_NXZ endp

; physHit::reset();
?reset@physHit@@QEAAXXZ proc EXPORT
jmp function_pointers[_physHit_base+6*8]
?reset@physHit@@QEAAXXZ endp

; physHit::hitObjectUnsafePtr();
?hitObjectUnsafePtr@physHit@@QEAAPEAVRootObject@@XZ proc EXPORT
jmp function_pointers[_physHit_base+7*8]
?hitObjectUnsafePtr@physHit@@QEAAPEAVRootObject@@XZ endp

; physHit::getBuilding();
?getBuilding@physHit@@QEAAPEAVBuilding@@XZ proc EXPORT
jmp function_pointers[_physHit_base+8*8]
?getBuilding@physHit@@QEAAPEAVBuilding@@XZ endp

; physHit::group();
?group@physHit@@QEBAGXZ proc EXPORT
jmp function_pointers[_physHit_base+9*8]
?group@physHit@@QEBAGXZ endp
