
?_CONSTRUCTOR@PhysicalEntity@@QEAAPEAV1@PEAVMovableObject@Ogre@@DPEAVGameData@@1_N@Z proc EXPORT
?_CONSTRUCTOR@PhysicalEntity@@QEAAPEAV1@PEAVMovableObject@Ogre@@DPEAVGameData@@1_N@Z endp

; PhysicalEntity::PhysicalEntity(class Ogre::MovableObject *, char, class GameData *, class GameData *, bool);
??0PhysicalEntity@@QEAA@PEAVMovableObject@Ogre@@DPEAVGameData@@1_N@Z proc EXPORT
jmp function_pointers[_PhysicalEntity_base+0*8]
??0PhysicalEntity@@QEAA@PEAVMovableObject@Ogre@@DPEAVGameData@@1_N@Z endp

?_DESTRUCTOR@PhysicalEntity@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PhysicalEntity@@QEAAXXZ endp

; PhysicalEntity::~PhysicalEntity();
??1PhysicalEntity@@UEAA@XZ proc EXPORT
jmp function_pointers[_PhysicalEntity_base+1*8]
??1PhysicalEntity@@UEAA@XZ endp
