
?_CONSTRUCTOR@RotatingEnt@PhysicsCollection@@QEAAPEAV12@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z proc EXPORT
?_CONSTRUCTOR@RotatingEnt@PhysicsCollection@@QEAAPEAV12@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z endp

; PhysicsCollection::RotatingEnt::RotatingEnt(class Ogre::MovableObject *, int, class GameData *, class GameData *);
??0RotatingEnt@PhysicsCollection@@QEAA@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+0*8]
??0RotatingEnt@PhysicsCollection@@QEAA@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z endp

?_DESTRUCTOR@RotatingEnt@PhysicsCollection@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RotatingEnt@PhysicsCollection@@QEAAXXZ endp

; PhysicsCollection::RotatingEnt::~RotatingEnt();
??1RotatingEnt@PhysicsCollection@@UEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+1*8]
??1RotatingEnt@PhysicsCollection@@UEAA@XZ endp

?_NV_update@RotatingEnt@PhysicsCollection@@QEAAXM@Z proc EXPORT
?_NV_update@RotatingEnt@PhysicsCollection@@QEAAXM@Z endp

; PhysicsCollection::RotatingEnt::update(float);
?update@RotatingEnt@PhysicsCollection@@UEAAXM@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+2*8]
?update@RotatingEnt@PhysicsCollection@@UEAAXM@Z endp

?_NV_updateAim@RotatingEnt@PhysicsCollection@@QEAAMMAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_updateAim@RotatingEnt@PhysicsCollection@@QEAAMMAEBVVector3@Ogre@@@Z endp

; PhysicsCollection::RotatingEnt::updateAim(float, const class Ogre::Vector3 &);
?updateAim@RotatingEnt@PhysicsCollection@@UEAAMMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+3*8]
?updateAim@RotatingEnt@PhysicsCollection@@UEAAMMAEBVVector3@Ogre@@@Z endp

?_NV_isRotatingEnt@RotatingEnt@PhysicsCollection@@QEBA_NXZ proc EXPORT
?_NV_isRotatingEnt@RotatingEnt@PhysicsCollection@@QEBA_NXZ endp

; PhysicsCollection::RotatingEnt::isRotatingEnt();
?isRotatingEnt@RotatingEnt@PhysicsCollection@@UEBA_NXZ proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+4*8]
?isRotatingEnt@RotatingEnt@PhysicsCollection@@UEBA_NXZ endp

; PhysicsCollection::RotatingEnt::getRotationPower();
?getRotationPower@RotatingEnt@PhysicsCollection@@QEBAMXZ proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+5*8]
?getRotationPower@RotatingEnt@PhysicsCollection@@QEBAMXZ endp

?_NV_weatherUpdated@RotatingEnt@PhysicsCollection@@QEAAXPEAVWeatherInstance@@_N@Z proc EXPORT
?_NV_weatherUpdated@RotatingEnt@PhysicsCollection@@QEAAXPEAVWeatherInstance@@_N@Z endp

; PhysicsCollection::RotatingEnt::weatherUpdated(class WeatherInstance *, bool);
?weatherUpdated@RotatingEnt@PhysicsCollection@@UEAAXPEAVWeatherInstance@@_N@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_RotatingEnt_base+6*8]
?weatherUpdated@RotatingEnt@PhysicsCollection@@UEAAXPEAVWeatherInstance@@_N@Z endp
