
?_CONSTRUCTOR@LightEnt@PhysicsCollection@@QEAAPEAV12@PEAVGameData@@_NPEAVSceneNode@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@LightEnt@PhysicsCollection@@QEAAPEAV12@PEAVGameData@@_NPEAVSceneNode@Ogre@@@Z endp

; PhysicsCollection::LightEnt::LightEnt(class GameData *, bool, class Ogre::SceneNode *);
??0LightEnt@PhysicsCollection@@QEAA@PEAVGameData@@_NPEAVSceneNode@Ogre@@@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_LightEnt_base+0*8]
??0LightEnt@PhysicsCollection@@QEAA@PEAVGameData@@_NPEAVSceneNode@Ogre@@@Z endp

?_DESTRUCTOR@LightEnt@PhysicsCollection@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@LightEnt@PhysicsCollection@@QEAAXXZ endp

; PhysicsCollection::LightEnt::~LightEnt();
??1LightEnt@PhysicsCollection@@QEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsCollection_LightEnt_base+1*8]
??1LightEnt@PhysicsCollection@@QEAA@XZ endp

; PhysicsCollection::LightEnt::setEnergyLevel(float);
?setEnergyLevel@LightEnt@PhysicsCollection@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_LightEnt_base+2*8]
?setEnergyLevel@LightEnt@PhysicsCollection@@QEAAXM@Z endp

; PhysicsCollection::LightEnt::setFloor(int);
?setFloor@LightEnt@PhysicsCollection@@QEAAXH@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_LightEnt_base+3*8]
?setFloor@LightEnt@PhysicsCollection@@QEAAXH@Z endp
