
?_NV_onTrigger@TriggerCallback@PhysicsActual@@QEAAXAEAVNxShape@@0W4NxShapeFlag@@@Z proc EXPORT
?_NV_onTrigger@TriggerCallback@PhysicsActual@@QEAAXAEAVNxShape@@0W4NxShapeFlag@@@Z endp

; PhysicsActual::TriggerCallback::onTrigger(class NxShape &, class NxShape &, enum NxShapeFlag);
?onTrigger@TriggerCallback@PhysicsActual@@UEAAXAEAVNxShape@@0W4NxShapeFlag@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_TriggerCallback_base+0*8]
?onTrigger@TriggerCallback@PhysicsActual@@UEAAXAEAVNxShape@@0W4NxShapeFlag@@@Z endp

; PhysicsActual::TriggerCallback::updateFrameEndMT();
?updateFrameEndMT@TriggerCallback@PhysicsActual@@QEAAXXZ proc EXPORT
jmp function_pointers[_PhysicsActual_TriggerCallback_base+1*8]
?updateFrameEndMT@TriggerCallback@PhysicsActual@@QEAAXXZ endp

?_CONSTRUCTOR@TriggerCallback@PhysicsActual@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TriggerCallback@PhysicsActual@@QEAAPEAV12@XZ endp

; PhysicsActual::TriggerCallback::TriggerCallback();
??0TriggerCallback@PhysicsActual@@QEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsActual_TriggerCallback_base+2*8]
??0TriggerCallback@PhysicsActual@@QEAA@XZ endp

?_DESTRUCTOR@TriggerCallback@PhysicsActual@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TriggerCallback@PhysicsActual@@QEAAXXZ endp

; PhysicsActual::TriggerCallback::~TriggerCallback();
??1TriggerCallback@PhysicsActual@@UEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsActual_TriggerCallback_base+3*8]
??1TriggerCallback@PhysicsActual@@UEAA@XZ endp
