
?_CONSTRUCTOR@PhysicsActual@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@PhysicsActual@@QEAAPEAV1@XZ endp

; PhysicsActual::PhysicsActual();
??0PhysicsActual@@QEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsActual_base+0*8]
??0PhysicsActual@@QEAA@XZ endp

?_DESTRUCTOR@PhysicsActual@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PhysicsActual@@QEAAXXZ endp

; PhysicsActual::~PhysicsActual();
??1PhysicsActual@@UEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsActual_base+1*8]
??1PhysicsActual@@UEAA@XZ endp

?_NV_updateUT@PhysicsActual@@QEAAXXZ proc EXPORT
?_NV_updateUT@PhysicsActual@@QEAAXXZ endp

; PhysicsActual::updateUT();
?updateUT@PhysicsActual@@UEAAXXZ proc EXPORT
jmp function_pointers[_PhysicsActual_base+2*8]
?updateUT@PhysicsActual@@UEAAXXZ endp

?_NV_backThreadUpdate@PhysicsActual@@QEAAXM_N@Z proc EXPORT
?_NV_backThreadUpdate@PhysicsActual@@QEAAXM_N@Z endp

; PhysicsActual::backThreadUpdate(float, bool);
?backThreadUpdate@PhysicsActual@@UEAAXM_N@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+3*8]
?backThreadUpdate@PhysicsActual@@UEAAXM_N@Z endp

; PhysicsActual::threadJunkPreBT();
?threadJunkPreBT@PhysicsActual@@QEAAXXZ proc EXPORT
jmp function_pointers[_PhysicsActual_base+4*8]
?threadJunkPreBT@PhysicsActual@@QEAAXXZ endp

; PhysicsActual::threadJunkPostBT();
?threadJunkPostBT@PhysicsActual@@QEAAXXZ proc EXPORT
jmp function_pointers[_PhysicsActual_base+5*8]
?threadJunkPostBT@PhysicsActual@@QEAAXXZ endp

; PhysicsActual::setup();
?setup@PhysicsActual@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PhysicsActual_base+6*8]
?setup@PhysicsActual@@QEAA_NXZ endp

; PhysicsActual::scytheGetFirstModelName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?scytheGetFirstModelName@PhysicsActual@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+7*8]
?scytheGetFirstModelName@PhysicsActual@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; PhysicsActual::scytheInsert(class _ScytheRootObjectInterfaceT *);
?scytheInsert@PhysicsActual@@QEAA_NPEAV_ScytheRootObjectInterfaceT@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+8*8]
?scytheInsert@PhysicsActual@@QEAA_NPEAV_ScytheRootObjectInterfaceT@@@Z endp

; PhysicsActual::convertXMLToBin(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class Ogre::Vector3 &);
?convertXMLToBin@PhysicsActual@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+9*8]
?convertXMLToBin@PhysicsActual@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVVector3@Ogre@@@Z endp

; PhysicsActual::loadPhysXFile(class PhysFileParams &, class lektor<NxActor *> *);
?loadPhysXFile@PhysicsActual@@QEAAPEAVNxActor@@AEAVPhysFileParams@@PEAV?$lektor@PEAVNxActor@@@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+10*8]
?loadPhysXFile@PhysicsActual@@QEAAPEAVNxActor@@AEAVPhysFileParams@@PEAV?$lektor@PEAVNxActor@@@@@Z endp

; PhysicsActual::loadPhysXFileAsATrigger(class PhysFileParams &, class lektor<NxActor *> *);
?loadPhysXFileAsATrigger@PhysicsActual@@QEAAPEAVNxActor@@AEAVPhysFileParams@@PEAV?$lektor@PEAVNxActor@@@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+11*8]
?loadPhysXFileAsATrigger@PhysicsActual@@QEAAPEAVNxActor@@AEAVPhysFileParams@@PEAV?$lektor@PEAVNxActor@@@@@Z endp

; PhysicsActual::_createTriggerHull(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?_createTriggerHull@PhysicsActual@@QEAAPEAVNxActor@@AEBVVector3@Ogre@@0@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+12*8]
?_createTriggerHull@PhysicsActual@@QEAAPEAVNxActor@@AEBVVector3@Ogre@@0@Z endp

; PhysicsActual::_createStaticCapsule(const class Ogre::Vector3 &, float, float);
?_createStaticCapsule@PhysicsActual@@QEAAPEAVNxActor@@AEBVVector3@Ogre@@MM@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+13*8]
?_createStaticCapsule@PhysicsActual@@QEAAPEAVNxActor@@AEBVVector3@Ogre@@MM@Z endp

; PhysicsActual::_createStaticBox(const class Ogre::Vector3 &, const class Ogre::Vector3 &, const class Ogre::Quaternion &, int);
?_createStaticBox@PhysicsActual@@QEAAPEAVNxActor@@AEBVVector3@Ogre@@0AEBVQuaternion@4@H@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+14*8]
?_createStaticBox@PhysicsActual@@QEAAPEAVNxActor@@AEBVVector3@Ogre@@0AEBVQuaternion@4@H@Z endp

; PhysicsActual::_destroy(class NxActor *);
?_destroy@PhysicsActual@@QEAAXPEAVNxActor@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+15*8]
?_destroy@PhysicsActual@@QEAAXPEAVNxActor@@@Z endp

; PhysicsActual::setActorCollisionGroup(class NxActor *, unsigned short);
?setActorCollisionGroup@PhysicsActual@@SAXPEAVNxActor@@G@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+16*8]
?setActorCollisionGroup@PhysicsActual@@SAXPEAVNxActor@@G@Z endp

; PhysicsActual::getActorCollisionGroup(class NxActor *);
?getActorCollisionGroup@PhysicsActual@@SAGPEAVNxActor@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+17*8]
?getActorCollisionGroup@PhysicsActual@@SAGPEAVNxActor@@@Z endp

; PhysicsActual::setActorMaterial(class NxActor *, int);
?setActorMaterial@PhysicsActual@@SAXPEAVNxActor@@H@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+18*8]
?setActorMaterial@PhysicsActual@@SAXPEAVNxActor@@H@Z endp

; PhysicsActual::scaleCollection(class NXU::NxuPhysicsCollection * &, const class NxVec3 &);
?scaleCollection@PhysicsActual@@QEAAXAEAPEAVNxuPhysicsCollection@NXU@@AEBVNxVec3@@@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+19*8]
?scaleCollection@PhysicsActual@@QEAAXAEAPEAVNxuPhysicsCollection@NXU@@AEBVNxVec3@@@Z endp

; PhysicsActual::uncookMesh(class NXU::NxTriangleMeshDesc *, const char *);
?uncookMesh@PhysicsActual@@QEBA_NPEAVNxTriangleMeshDesc@NXU@@PEBD@Z proc EXPORT
jmp function_pointers[_PhysicsActual_base+20*8]
?uncookMesh@PhysicsActual@@QEBA_NPEAVNxTriangleMeshDesc@NXU@@PEBD@Z endp
