
?_CONSTRUCTOR@StaticEnt@PhysicsCollection@@QEAAPEAV12@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z proc EXPORT
?_CONSTRUCTOR@StaticEnt@PhysicsCollection@@QEAAPEAV12@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z endp

; PhysicsCollection::StaticEnt::StaticEnt(class Ogre::MovableObject *, int, class GameData *, class GameData *);
??0StaticEnt@PhysicsCollection@@QEAA@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_StaticEnt_base+0*8]
??0StaticEnt@PhysicsCollection@@QEAA@PEAVMovableObject@Ogre@@HPEAVGameData@@1@Z endp

?_NV_update@StaticEnt@PhysicsCollection@@QEAAXM@Z proc EXPORT
?_NV_update@StaticEnt@PhysicsCollection@@QEAAXM@Z endp

; PhysicsCollection::StaticEnt::update(float);
?update@StaticEnt@PhysicsCollection@@UEAAXM@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_StaticEnt_base+1*8]
?update@StaticEnt@PhysicsCollection@@UEAAXM@Z endp

?_NV_updateAim@StaticEnt@PhysicsCollection@@QEAAMMAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_updateAim@StaticEnt@PhysicsCollection@@QEAAMMAEBVVector3@Ogre@@@Z endp

; PhysicsCollection::StaticEnt::updateAim(float, const class Ogre::Vector3 &);
?updateAim@StaticEnt@PhysicsCollection@@UEAAMMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_StaticEnt_base+2*8]
?updateAim@StaticEnt@PhysicsCollection@@UEAAMMAEBVVector3@Ogre@@@Z endp

?_NV_isRotatingEnt@StaticEnt@PhysicsCollection@@QEBA_NXZ proc EXPORT
?_NV_isRotatingEnt@StaticEnt@PhysicsCollection@@QEBA_NXZ endp

; PhysicsCollection::StaticEnt::isRotatingEnt();
?isRotatingEnt@StaticEnt@PhysicsCollection@@UEBA_NXZ proc EXPORT
jmp function_pointers[_PhysicsCollection_StaticEnt_base+3*8]
?isRotatingEnt@StaticEnt@PhysicsCollection@@UEBA_NXZ endp

?_DESTRUCTOR@StaticEnt@PhysicsCollection@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@StaticEnt@PhysicsCollection@@QEAAXXZ endp

; PhysicsCollection::StaticEnt::~StaticEnt();
??1StaticEnt@PhysicsCollection@@UEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsCollection_StaticEnt_base+4*8]
??1StaticEnt@PhysicsCollection@@UEAA@XZ endp
