
?_DESTRUCTOR@PhysicsCollection@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PhysicsCollection@@QEAAXXZ endp

; PhysicsCollection::~PhysicsCollection();
??1PhysicsCollection@@QEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsCollection_base+0*8]
??1PhysicsCollection@@QEAA@XZ endp

; PhysicsCollection::findRotatingEnt(class GameData *);
?findRotatingEnt@PhysicsCollection@@QEBAPEAVRotatingEnt@1@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_base+1*8]
?findRotatingEnt@PhysicsCollection@@QEBAPEAVRotatingEnt@1@PEAVGameData@@@Z endp

; PhysicsCollection::getWindRotationPower();
?getWindRotationPower@PhysicsCollection@@QEBAMXZ proc EXPORT
jmp function_pointers[_PhysicsCollection_base+2*8]
?getWindRotationPower@PhysicsCollection@@QEBAMXZ endp

; PhysicsCollection::getWindMillPart();
?getWindMillPart@PhysicsCollection@@QEBAPEAVRotatingEnt@1@XZ proc EXPORT
jmp function_pointers[_PhysicsCollection_base+3*8]
?getWindMillPart@PhysicsCollection@@QEBAPEAVRotatingEnt@1@XZ endp

; PhysicsCollection::isLoaded();
?isLoaded@PhysicsCollection@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PhysicsCollection_base+4*8]
?isLoaded@PhysicsCollection@@QEAA_NXZ endp

; PhysicsCollection::setVisible(bool);
?setVisible@PhysicsCollection@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_base+5*8]
?setVisible@PhysicsCollection@@QEAAX_N@Z endp

; PhysicsCollection::handleChanged(const class hand &);
?handleChanged@PhysicsCollection@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_base+6*8]
?handleChanged@PhysicsCollection@@QEAAXAEBVhand@@@Z endp

; PhysicsCollection::update(float);
?update@PhysicsCollection@@QEAAXM@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_base+7*8]
?update@PhysicsCollection@@QEAAXM@Z endp

; PhysicsCollection::updateAimingType(float, const class Ogre::Vector3 &);
?updateAimingType@PhysicsCollection@@QEAAMMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PhysicsCollection_base+8*8]
?updateAimingType@PhysicsCollection@@QEAAMMAEBVVector3@Ogre@@@Z endp

?_CONSTRUCTOR@PhysicsCollection@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@PhysicsCollection@@QEAAPEAV1@XZ endp

; PhysicsCollection::PhysicsCollection();
??0PhysicsCollection@@QEAA@XZ proc EXPORT
jmp function_pointers[_PhysicsCollection_base+9*8]
??0PhysicsCollection@@QEAA@XZ endp
