
?_CONSTRUCTOR@Platoon@@QEAAPEAV1@PEAVFaction@@PEAVGameData@@1AEBVVector3@Ogre@@_N@Z proc EXPORT
?_CONSTRUCTOR@Platoon@@QEAAPEAV1@PEAVFaction@@PEAVGameData@@1AEBVVector3@Ogre@@_N@Z endp

; Platoon::Platoon(class Faction *, class GameData *, class GameData *, const class Ogre::Vector3 &, bool);
??0Platoon@@QEAA@PEAVFaction@@PEAVGameData@@1AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_Platoon_base+0*8]
??0Platoon@@QEAA@PEAVFaction@@PEAVGameData@@1AEBVVector3@Ogre@@_N@Z endp

?_DESTRUCTOR@Platoon@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Platoon@@QEAAXXZ endp

; Platoon::~Platoon();
??1Platoon@@UEAA@XZ proc EXPORT
jmp function_pointers[_Platoon_base+1*8]
??1Platoon@@UEAA@XZ endp

; Platoon::setCharacterCount(int);
?setCharacterCount@Platoon@@QEAAXH@Z proc EXPORT
jmp function_pointers[_Platoon_base+2*8]
?setCharacterCount@Platoon@@QEAAXH@Z endp

; Platoon::chooseNewHome();
?chooseNewHome@Platoon@@QEAA?AVhand@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+3*8]
?chooseNewHome@Platoon@@QEAA?AVhand@@XZ endp

?_NV_isUnconcious@Platoon@@QEBA_NXZ proc EXPORT
?_NV_isUnconcious@Platoon@@QEBA_NXZ endp

; Platoon::isUnconcious();
?isUnconcious@Platoon@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Platoon_base+4*8]
?isUnconcious@Platoon@@UEBA_NXZ endp

; Platoon::getSquadType();
?getSquadType@Platoon@@QEBA?AW4SquadType@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+5*8]
?getSquadType@Platoon@@QEBA?AW4SquadType@@XZ endp

; Platoon::setSquadType(enum SquadType);
?setSquadType@Platoon@@QEAAXW4SquadType@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+6*8]
?setSquadType@Platoon@@QEAAXW4SquadType@@@Z endp

?_NV_getCurrentTownLocation@Platoon@@QEAAPEAVTownBase@@XZ proc EXPORT
?_NV_getCurrentTownLocation@Platoon@@QEAAPEAVTownBase@@XZ endp

; Platoon::getCurrentTownLocation();
?getCurrentTownLocation@Platoon@@UEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+7*8]
?getCurrentTownLocation@Platoon@@UEAAPEAVTownBase@@XZ endp

; Platoon::hasCampaign();
?hasCampaign@Platoon@@QEAAPEAVCampaignInstance@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+8*8]
?hasCampaign@Platoon@@QEAAPEAVCampaignInstance@@XZ endp

; Platoon::iBuyStolenGoods(class Item *);
?iBuyStolenGoods@Platoon@@QEAA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+9*8]
?iBuyStolenGoods@Platoon@@QEAA_NPEAVItem@@@Z endp

; Platoon::iBuyIllegalGoods();
?iBuyIllegalGoods@Platoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Platoon_base+10*8]
?iBuyIllegalGoods@Platoon@@QEAA_NXZ endp

?_NV_setFaction@Platoon@@QEAAXPEAVFaction@@@Z proc EXPORT
?_NV_setFaction@Platoon@@QEAAXPEAVFaction@@@Z endp

; Platoon::setFaction(class Faction *);
?setFaction@Platoon@@UEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+11*8]
?setFaction@Platoon@@UEAAXPEAVFaction@@@Z endp

; Platoon::canTakeRefugees(class Platoon *);
?canTakeRefugees@Platoon@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_Platoon_base+12*8]
?canTakeRefugees@Platoon@@QEAA_NPEAV1@@Z endp

?_NV_isUnique@Platoon@@QEAAPEAVUniquePlatoon@@XZ proc EXPORT
?_NV_isUnique@Platoon@@QEAAPEAVUniquePlatoon@@XZ endp

; Platoon::isUnique();
?isUnique@Platoon@@UEAAPEAVUniquePlatoon@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+13*8]
?isUnique@Platoon@@UEAAPEAVUniquePlatoon@@XZ endp

; Platoon::getPlatoonStringID();
?getPlatoonStringID@Platoon@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+14*8]
?getPlatoonStringID@Platoon@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Platoon::getBlackboard();
?getBlackboard@Platoon@@QEAAPEAVBlackboard@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+15*8]
?getBlackboard@Platoon@@QEAAPEAVBlackboard@@XZ endp

?_NV_getDataType@Platoon@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@Platoon@@QEBA?AW4itemType@@XZ endp

; Platoon::getDataType();
?getDataType@Platoon@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+16*8]
?getDataType@Platoon@@UEBA?AW4itemType@@XZ endp

; Platoon::erasePlatoonFile();
?erasePlatoonFile@Platoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+17*8]
?erasePlatoonFile@Platoon@@QEAAXXZ endp

; Platoon::showDebugMarker(bool);
?showDebugMarker@Platoon@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Platoon_base+18*8]
?showDebugMarker@Platoon@@QEAAX_N@Z endp

?_NV_getStateBroadcast@Platoon@@QEAAPEAVStateBroadcastData@@XZ proc EXPORT
?_NV_getStateBroadcast@Platoon@@QEAAPEAVStateBroadcastData@@XZ endp

; Platoon::getStateBroadcast();
?getStateBroadcast@Platoon@@UEAAPEAVStateBroadcastData@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+19*8]
?getStateBroadcast@Platoon@@UEAAPEAVStateBroadcastData@@XZ endp

?_NV_serialiseEverything@Platoon@@QEAAPEAVGameData@@PEAVGameDataContainer@@_N@Z proc EXPORT
?_NV_serialiseEverything@Platoon@@QEAAPEAVGameData@@PEAVGameDataContainer@@_N@Z endp

; Platoon::serialiseEverything(class GameDataContainer *, bool);
?serialiseEverything@Platoon@@UEAAPEAVGameData@@PEAVGameDataContainer@@_N@Z proc EXPORT
jmp function_pointers[_Platoon_base+20*8]
?serialiseEverything@Platoon@@UEAAPEAVGameData@@PEAVGameDataContainer@@_N@Z endp

?_NV_loadStateData@Platoon@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_loadStateData@Platoon@@QEAAXPEAVGameData@@@Z endp

; Platoon::loadStateData(class GameData *);
?loadStateData@Platoon@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+21*8]
?loadStateData@Platoon@@UEAAXPEAVGameData@@@Z endp

?_NV_serialise@Platoon@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@Platoon@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; Platoon::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@Platoon@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+22*8]
?serialise@Platoon@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@Platoon@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@Platoon@@QEAAXPEAVGameSaveState@@@Z endp

; Platoon::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@Platoon@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+23*8]
?loadFromSerialise@Platoon@@UEAAXPEAVGameSaveState@@@Z endp

; Platoon::reprocessTask(class Tasker *);
?reprocessTask@Platoon@@QEAAXPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+24*8]
?reprocessTask@Platoon@@QEAAXPEAVTasker@@@Z endp

; Platoon::taskIsComplete(class Tasker *);
?taskIsComplete@Platoon@@QEAAXPEAVTasker@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+25*8]
?taskIsComplete@Platoon@@QEAAXPEAVTasker@@@Z endp

; Platoon::setDataFilename(class std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
?setDataFilename@Platoon@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+26*8]
?setDataFilename@Platoon@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Platoon::isIntact();
?isIntact@Platoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Platoon_base+27*8]
?isIntact@Platoon@@QEAA_NXZ endp

?_NV_notifyMissionEnded@Platoon@@QEAAXXZ proc EXPORT
?_NV_notifyMissionEnded@Platoon@@QEAAXXZ endp

; Platoon::notifyMissionEnded();
?notifyMissionEnded@Platoon@@UEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+28*8]
?notifyMissionEnded@Platoon@@UEAAXXZ endp

; Platoon::activate();
?activate@Platoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+29*8]
?activate@Platoon@@QEAAXXZ endp

; Platoon::deactivate(class GameDataContainer *);
?deactivate@Platoon@@QEAAXPEAVGameDataContainer@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+30*8]
?deactivate@Platoon@@QEAAXPEAVGameDataContainer@@@Z endp

; Platoon::declareDead();
?declareDead@Platoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+31*8]
?declareDead@Platoon@@QEAAXXZ endp

; Platoon::undeclareDead();
?undeclareDead@Platoon@@QEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+32*8]
?undeclareDead@Platoon@@QEAAXXZ endp

; Platoon::isFullyLoaded();
?isFullyLoaded@Platoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Platoon_base+33*8]
?isFullyLoaded@Platoon@@QEAA_NXZ endp

; Platoon::getActivePlatoon();
?getActivePlatoon@Platoon@@QEAAPEAVActivePlatoon@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+34*8]
?getActivePlatoon@Platoon@@QEAAPEAVActivePlatoon@@XZ endp

; Platoon::getUnloadedPlatoon();
?getUnloadedPlatoon@Platoon@@QEAAPEAVUnloadedPlatoon@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+35*8]
?getUnloadedPlatoon@Platoon@@QEAAPEAVUnloadedPlatoon@@XZ endp

?_NV_update@Platoon@@QEAA_NXZ proc EXPORT
?_NV_update@Platoon@@QEAA_NXZ endp

; Platoon::update();
?update@Platoon@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Platoon_base+36*8]
?update@Platoon@@UEAA_NXZ endp

?_NV_periodicUpdate_active@Platoon@@QEAAXM@Z proc EXPORT
?_NV_periodicUpdate_active@Platoon@@QEAAXM@Z endp

; Platoon::periodicUpdate_active(float);
?periodicUpdate_active@Platoon@@UEAAXM@Z proc EXPORT
jmp function_pointers[_Platoon_base+37*8]
?periodicUpdate_active@Platoon@@UEAAXM@Z endp

?_NV_periodicUpdate_unloaded@Platoon@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate_unloaded@Platoon@@QEAAXXZ endp

; Platoon::periodicUpdate_unloaded();
?periodicUpdate_unloaded@Platoon@@UEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+38*8]
?periodicUpdate_unloaded@Platoon@@UEAAXXZ endp

; Platoon::setupPatrolSettings(int, int);
?setupPatrolSettings@Platoon@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_Platoon_base+39*8]
?setupPatrolSettings@Platoon@@QEAAXHH@Z endp

; Platoon::getPatrolInfo();
?getPatrolInfo@Platoon@@QEAAPEAVPatrolInfo@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+40*8]
?getPatrolInfo@Platoon@@QEAAPEAVPatrolInfo@@XZ endp

; Platoon::getRoamingMapArea();
?getRoamingMapArea@Platoon@@QEAAPEAVAreaBiomeGroup@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+41*8]
?getRoamingMapArea@Platoon@@QEAAPEAVAreaBiomeGroup@@XZ endp

; Platoon::setRoamingMapArea(class AreaBiomeGroup *);
?setRoamingMapArea@Platoon@@QEAAXPEAVAreaBiomeGroup@@@Z proc EXPORT
jmp function_pointers[_Platoon_base+42*8]
?setRoamingMapArea@Platoon@@QEAAXPEAVAreaBiomeGroup@@@Z endp

; Platoon::isPersistentSquad();
?isPersistentSquad@Platoon@@QEAA_NXZ proc EXPORT
jmp function_pointers[_Platoon_base+43*8]
?isPersistentSquad@Platoon@@QEAA_NXZ endp

; Platoon::setPersistentSquad(bool);
?setPersistentSquad@Platoon@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Platoon_base+44*8]
?setPersistentSquad@Platoon@@QEAAX_N@Z endp

?_NV_getOwnerships@Platoon@@QEAAPEAVOwnerships@@XZ proc EXPORT
?_NV_getOwnerships@Platoon@@QEAAPEAVOwnerships@@XZ endp

; Platoon::getOwnerships();
?getOwnerships@Platoon@@UEAAPEAVOwnerships@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+45*8]
?getOwnerships@Platoon@@UEAAPEAVOwnerships@@XZ endp

; Platoon::getNearestActiveCharacter(const class Ogre::Vector3 &, int);
?getNearestActiveCharacter@Platoon@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_Platoon_base+46*8]
?getNearestActiveCharacter@Platoon@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@H@Z endp

; Platoon::getSquadLeader();
?getSquadLeader@Platoon@@QEAAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+47*8]
?getSquadLeader@Platoon@@QEAAPEAVCharacter@@XZ endp

; Platoon::getSquadLeader_theRealOne();
?getSquadLeader_theRealOne@Platoon@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_Platoon_base+48*8]
?getSquadLeader_theRealOne@Platoon@@QEBAAEBVhand@@XZ endp

; Platoon::getCharacterCount();
?getCharacterCount@Platoon@@QEAAHXZ proc EXPORT
jmp function_pointers[_Platoon_base+49*8]
?getCharacterCount@Platoon@@QEAAHXZ endp

; Platoon::getCharacterCount_Original();
?getCharacterCount_Original@Platoon@@QEBAHXZ proc EXPORT
jmp function_pointers[_Platoon_base+50*8]
?getCharacterCount_Original@Platoon@@QEBAHXZ endp

; Platoon::needsNewCharacters();
?needsNewCharacters@Platoon@@QEAAHXZ proc EXPORT
jmp function_pointers[_Platoon_base+51*8]
?needsNewCharacters@Platoon@@QEAAHXZ endp

?_NV_reCheckPersistenceOnUnload@Platoon@@QEAAXXZ proc EXPORT
?_NV_reCheckPersistenceOnUnload@Platoon@@QEAAXXZ endp

; Platoon::reCheckPersistenceOnUnload();
?reCheckPersistenceOnUnload@Platoon@@UEAAXXZ proc EXPORT
jmp function_pointers[_Platoon_base+52*8]
?reCheckPersistenceOnUnload@Platoon@@UEAAXXZ endp
