
?_CONSTRUCTOR@PlayerInterface@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@PlayerInterface@@QEAAPEAV1@XZ endp

; PlayerInterface::PlayerInterface();
??0PlayerInterface@@QEAA@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+0*8]
??0PlayerInterface@@QEAA@XZ endp

?_DESTRUCTOR@PlayerInterface@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::~PlayerInterface();
??1PlayerInterface@@QEAA@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+1*8]
??1PlayerInterface@@QEAA@XZ endp

; PlayerInterface::getCamera();
?getCamera@PlayerInterface@@QEAAPEAVCameraClass@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+2*8]
?getCamera@PlayerInterface@@QEAAPEAVCameraClass@@XZ endp

; PlayerInterface::playerSetup(class CameraClass *);
?playerSetup@PlayerInterface@@QEAAXPEAVCameraClass@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+3*8]
?playerSetup@PlayerInterface@@QEAAXPEAVCameraClass@@@Z endp

; PlayerInterface::clearAndReset();
?clearAndReset@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+4*8]
?clearAndReset@PlayerInterface@@QEAAXXZ endp

?_NV_factoryObjectCreatedCallback@PlayerInterface@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_factoryObjectCreatedCallback@PlayerInterface@@QEAAXPEAVRootObject@@@Z endp

; PlayerInterface::factoryObjectCreatedCallback(class RootObject *);
?factoryObjectCreatedCallback@PlayerInterface@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+5*8]
?factoryObjectCreatedCallback@PlayerInterface@@UEAAXPEAVRootObject@@@Z endp

; PlayerInterface::setFaction(class Faction *);
?setFaction@PlayerInterface@@QEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+6*8]
?setFaction@PlayerInterface@@QEAAXPEAVFaction@@@Z endp

; PlayerInterface::getFaction();
?getFaction@PlayerInterface@@QEBAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+7*8]
?getFaction@PlayerInterface@@QEBAPEAVFaction@@XZ endp

; PlayerInterface::setCurrentPlatoon(class Platoon *);
?setCurrentPlatoon@PlayerInterface@@QEAA_NPEAVPlatoon@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+8*8]
?setCurrentPlatoon@PlayerInterface@@QEAA_NPEAVPlatoon@@@Z endp

; PlayerInterface::getCurrentPlatoon();
?getCurrentPlatoon@PlayerInterface@@QEAAPEAVPlatoon@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+9*8]
?getCurrentPlatoon@PlayerInterface@@QEAAPEAVPlatoon@@XZ endp

; PlayerInterface::getCurrentActivePlatoon();
?getCurrentActivePlatoon@PlayerInterface@@QEAAPEAVRootObjectContainer@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+10*8]
?getCurrentActivePlatoon@PlayerInterface@@QEAAPEAVRootObjectContainer@@XZ endp

; PlayerInterface::recruit(const class lektor<Character *> &, bool);
?recruit@PlayerInterface@@QEAA_NAEBV?$lektor@PEAVCharacter@@@@_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+11*8]
?recruit@PlayerInterface@@QEAA_NAEBV?$lektor@PEAVCharacter@@@@_N@Z endp

; PlayerInterface::recruit(class Character *, bool);
?recruit@PlayerInterface@@QEAA_NPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+12*8]
?recruit@PlayerInterface@@QEAA_NPEAVCharacter@@_N@Z endp

; PlayerInterface::createSquad();
?createSquad@PlayerInterface@@QEAAPEAVActivePlatoon@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+13*8]
?createSquad@PlayerInterface@@QEAAPEAVActivePlatoon@@XZ endp

; PlayerInterface::getDeadSquad();
?getDeadSquad@PlayerInterface@@QEAAPEAVActivePlatoon@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+14*8]
?getDeadSquad@PlayerInterface@@QEAAPEAVActivePlatoon@@XZ endp

; PlayerInterface::getDeadSquadHandle();
?getDeadSquadHandle@PlayerInterface@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+15*8]
?getDeadSquadHandle@PlayerInterface@@QEBAAEBVhand@@XZ endp

; PlayerInterface::update();
?update@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+16*8]
?update@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::updateUT();
?updateUT@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+17*8]
?updateUT@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::isBuildMode();
?isBuildMode@PlayerInterface@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+18*8]
?isBuildMode@PlayerInterface@@QEBA_NXZ endp

; PlayerInterface::activateObjectPlacementMode(class GameData *);
?activateObjectPlacementMode@PlayerInterface@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+19*8]
?activateObjectPlacementMode@PlayerInterface@@QEAAXPEAVGameData@@@Z endp

; PlayerInterface::activateCharacterEditMode(class Character *);
?activateCharacterEditMode@PlayerInterface@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+20*8]
?activateCharacterEditMode@PlayerInterface@@QEAAXPEAVCharacter@@@Z endp

; PlayerInterface::triggerAreaArrivalDialogue(class GameData *);
?triggerAreaArrivalDialogue@PlayerInterface@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+21*8]
?triggerAreaArrivalDialogue@PlayerInterface@@QEAA_NPEAVGameData@@@Z endp

; PlayerInterface::setCharacterEditMode(bool);
?setCharacterEditMode@PlayerInterface@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+22*8]
?setCharacterEditMode@PlayerInterface@@QEAAX_N@Z endp

; PlayerInterface::getCharacterEditMode();
?getCharacterEditMode@PlayerInterface@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+23*8]
?getCharacterEditMode@PlayerInterface@@QEBA_NXZ endp

; PlayerInterface::unselectAll();
?unselectAll@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+24*8]
?unselectAll@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::selectAll();
?selectAll@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+25*8]
?selectAll@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::selectObject(class RootObject *, bool);
?selectObject@PlayerInterface@@QEAAXPEAVRootObject@@_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+26*8]
?selectObject@PlayerInterface@@QEAAXPEAVRootObject@@_N@Z endp

; PlayerInterface::selectPlayerCharacter(int, bool, bool);
?selectPlayerCharacter@PlayerInterface@@QEAAXH_N0@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+27*8]
?selectPlayerCharacter@PlayerInterface@@QEAAXH_N0@Z endp

; PlayerInterface::_selectPlayerCharacter(class RootObject *, bool, bool);
?_selectPlayerCharacter@PlayerInterface@@QEAAXPEAVRootObject@@_N1@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+28*8]
?_selectPlayerCharacter@PlayerInterface@@QEAAXPEAVRootObject@@_N1@Z endp

; PlayerInterface::activateSelection(class RootObject *);
?activateSelection@PlayerInterface@@QEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+29*8]
?activateSelection@PlayerInterface@@QEAAXPEAVRootObject@@@Z endp

; PlayerInterface::getCameraCenter();
?getCameraCenter@PlayerInterface@@QEBA?BVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+30*8]
?getCameraCenter@PlayerInterface@@QEBA?BVVector3@Ogre@@XZ endp

; PlayerInterface::getDistanceFromCamera(const class Ogre::Vector3 &);
?getDistanceFromCamera@PlayerInterface@@QEBAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+31*8]
?getDistanceFromCamera@PlayerInterface@@QEBAMAEBVVector3@Ogre@@@Z endp

; PlayerInterface::getSquaredDistanceFromCamera(const class Ogre::Vector3 &);
?getSquaredDistanceFromCamera@PlayerInterface@@QEBAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+32*8]
?getSquaredDistanceFromCamera@PlayerInterface@@QEBAMAEBVVector3@Ogre@@@Z endp

; PlayerInterface::startTrackCharacter(class RootObject *);
?startTrackCharacter@PlayerInterface@@QEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+33*8]
?startTrackCharacter@PlayerInterface@@QEAAXPEAVRootObject@@@Z endp

; PlayerInterface::stopTrackCharacter();
?stopTrackCharacter@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+34*8]
?stopTrackCharacter@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::isTrackingCharacter();
?isTrackingCharacter@PlayerInterface@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+35*8]
?isTrackingCharacter@PlayerInterface@@QEBA_NXZ endp

; PlayerInterface::focusCamera(const class Ogre::Vector3 &);
?focusCamera@PlayerInterface@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+36*8]
?focusCamera@PlayerInterface@@QEAAXAEBVVector3@Ogre@@@Z endp

; PlayerInterface::manuallyOrientCamera(const class Ogre::Quaternion &, float);
?manuallyOrientCamera@PlayerInterface@@QEAAXAEBVQuaternion@Ogre@@M@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+37*8]
?manuallyOrientCamera@PlayerInterface@@QEAAXAEBVQuaternion@Ogre@@M@Z endp

; PlayerInterface::focusCameraSelectedCharacter();
?focusCameraSelectedCharacter@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+38*8]
?focusCameraSelectedCharacter@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::toggleLevelEditorOnSelectedTown();
?toggleLevelEditorOnSelectedTown@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+39*8]
?toggleLevelEditorOnSelectedTown@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::isLevelEditMode();
?isLevelEditMode@PlayerInterface@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+40*8]
?isLevelEditMode@PlayerInterface@@QEBA_NXZ endp

; PlayerInterface::isObjectPlacementMode();
?isObjectPlacementMode@PlayerInterface@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+41*8]
?isObjectPlacementMode@PlayerInterface@@QEBA_NXZ endp

; PlayerInterface::setOrderSelectedCharacters(enum MessageForB::StandingOrder);
?setOrderSelectedCharacters@PlayerInterface@@QEAAXW4StandingOrder@MessageForB@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+42*8]
?setOrderSelectedCharacters@PlayerInterface@@QEAAXW4StandingOrder@MessageForB@@@Z endp

; PlayerInterface::getLevelEditor();
?getLevelEditor@PlayerInterface@@QEAAPEAVLevelEditor@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+43*8]
?getLevelEditor@PlayerInterface@@QEAAPEAVLevelEditor@@XZ endp

; PlayerInterface::objectSelected(class RootObject *, bool);
?objectSelected@PlayerInterface@@QEAAXPEAVRootObject@@_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+44*8]
?objectSelected@PlayerInterface@@QEAAXPEAVRootObject@@_N@Z endp

; PlayerInterface::toggleObjectSelected(class RootObject *);
?toggleObjectSelected@PlayerInterface@@QEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+45*8]
?toggleObjectSelected@PlayerInterface@@QEAAXPEAVRootObject@@@Z endp

; PlayerInterface::isObjectSelected(class RootObject *);
?isObjectSelected@PlayerInterface@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+46*8]
?isObjectSelected@PlayerInterface@@QEAA_NPEAVRootObject@@@Z endp

; PlayerInterface::unselectPlayerCharacter(class RootObject *);
?unselectPlayerCharacter@PlayerInterface@@QEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+47*8]
?unselectPlayerCharacter@PlayerInterface@@QEAAXPEAVRootObject@@@Z endp

; PlayerInterface::updatePlayerSelection(const class hand &, const class hand &);
?updatePlayerSelection@PlayerInterface@@QEAAXAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+48*8]
?updatePlayerSelection@PlayerInterface@@QEAAXAEBVhand@@0@Z endp

; PlayerInterface::getCurrentFloor();
?getCurrentFloor@PlayerInterface@@QEBAHXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+49*8]
?getCurrentFloor@PlayerInterface@@QEBAHXZ endp

; PlayerInterface::setCurrentFloor(int);
?setCurrentFloor@PlayerInterface@@QEAAXH@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+50*8]
?setCurrentFloor@PlayerInterface@@QEAAXH@Z endp

; PlayerInterface::getAllSelectedObjects(class lektor<RootObject *> &, enum itemType);
?getAllSelectedObjects@PlayerInterface@@QEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+51*8]
?getAllSelectedObjects@PlayerInterface@@QEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@@Z endp

; PlayerInterface::getNearestSelectedCharacterTo(const class Ogre::Vector3 &);
?getNearestSelectedCharacterTo@PlayerInterface@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+52*8]
?getNearestSelectedCharacterTo@PlayerInterface@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@@Z endp

; PlayerInterface::getNearestCharacterTo(const class Ogre::Vector3 &);
?getNearestCharacterTo@PlayerInterface@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+53*8]
?getNearestCharacterTo@PlayerInterface@@QEAAPEAVCharacter@@AEBVVector3@Ogre@@@Z endp

; PlayerInterface::newPlayerTaskSelectedCharacters(enum TaskType, const class hand &, class Building *, const class Ogre::Vector3 &, bool);
?newPlayerTaskSelectedCharacters@PlayerInterface@@QEAAXW4TaskType@@AEBVhand@@PEAVBuilding@@AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+54*8]
?newPlayerTaskSelectedCharacters@PlayerInterface@@QEAAXW4TaskType@@AEBVhand@@PEAVBuilding@@AEBVVector3@Ogre@@_N@Z endp

; PlayerInterface::getPlayerTaskProbability(enum TaskType, class RootObject *, float &);
?getPlayerTaskProbability@PlayerInterface@@QEAA_NW4TaskType@@PEAVRootObject@@AEAM@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+55*8]
?getPlayerTaskProbability@PlayerInterface@@QEAA_NW4TaskType@@PEAVRootObject@@AEAM@Z endp

; PlayerInterface::addOrderSelectedCharacters(class Building *, enum TaskType, class RootObject *, bool, bool, const class Ogre::Vector3 &);
?addOrderSelectedCharacters@PlayerInterface@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@_N3AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+56*8]
?addOrderSelectedCharacters@PlayerInterface@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@_N3AEBVVector3@Ogre@@@Z endp

; PlayerInterface::addJobSelectedCharacters(enum TaskType, class RootObject *, bool, bool, const class Ogre::Vector3 &);
?addJobSelectedCharacters@PlayerInterface@@QEAAXW4TaskType@@PEAVRootObject@@_N2AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+57*8]
?addJobSelectedCharacters@PlayerInterface@@QEAAXW4TaskType@@PEAVRootObject@@_N2AEBVVector3@Ogre@@@Z endp

; PlayerInterface::removeJobSelectedCharacters(enum TaskType);
?removeJobSelectedCharacters@PlayerInterface@@QEAAXW4TaskType@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+58*8]
?removeJobSelectedCharacters@PlayerInterface@@QEAAXW4TaskType@@@Z endp

; PlayerInterface::removePermaJobSelectedCharacters(int);
?removePermaJobSelectedCharacters@PlayerInterface@@QEAAXH@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+59*8]
?removePermaJobSelectedCharacters@PlayerInterface@@QEAAXH@Z endp

; PlayerInterface::selectedCharactersUnconcious(bool);
?selectedCharactersUnconcious@PlayerInterface@@QEAA_N_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+60*8]
?selectedCharactersUnconcious@PlayerInterface@@QEAA_N_N@Z endp

; PlayerInterface::selectedCharactersLayingLow();
?selectedCharactersLayingLow@PlayerInterface@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+61*8]
?selectedCharactersLayingLow@PlayerInterface@@QEAA_NXZ endp

; PlayerInterface::useSpeedGroup(bool);
?useSpeedGroup@PlayerInterface@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+62*8]
?useSpeedGroup@PlayerInterface@@QEAAX_N@Z endp

; PlayerInterface::assignSpeedGroup(bool);
?assignSpeedGroup@PlayerInterface@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+63*8]
?assignSpeedGroup@PlayerInterface@@QEAAX_N@Z endp

; PlayerInterface::isEnemy(class Character *);
?isEnemy@PlayerInterface@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+64*8]
?isEnemy@PlayerInterface@@QEAA_NPEAVCharacter@@@Z endp

; PlayerInterface::isFactionKnown(class Faction *);
?isFactionKnown@PlayerInterface@@QEBA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+65*8]
?isFactionKnown@PlayerInterface@@QEBA_NPEAVFaction@@@Z endp

; PlayerInterface::encounterFaction(class Faction *);
?encounterFaction@PlayerInterface@@QEAAXPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+66*8]
?encounterFaction@PlayerInterface@@QEAAXPEAVFaction@@@Z endp

; PlayerInterface::pickupItem(class Item *);
?pickupItem@PlayerInterface@@QEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+67*8]
?pickupItem@PlayerInterface@@QEAAXPEAVItem@@@Z endp

; PlayerInterface::cycleSquad();
?cycleSquad@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+68*8]
?cycleSquad@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::cycleCharacter(int);
?cycleCharacter@PlayerInterface@@QEAAXH@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+69*8]
?cycleCharacter@PlayerInterface@@QEAAXH@Z endp

; PlayerInterface::stopCharactersMovement();
?stopCharactersMovement@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+70*8]
?stopCharactersMovement@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::getAnyPlayerCharacter();
?getAnyPlayerCharacter@PlayerInterface@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+71*8]
?getAnyPlayerCharacter@PlayerInterface@@QEBAPEAVCharacter@@XZ endp

; PlayerInterface::getAllPlayerCharacters(class lektor<RootObject *> &);
?getAllPlayerCharacters@PlayerInterface@@QEAAXAEAV?$lektor@PEAVRootObject@@@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+72*8]
?getAllPlayerCharacters@PlayerInterface@@QEAAXAEAV?$lektor@PEAVRootObject@@@@@Z endp

; PlayerInterface::getAllPlayerCharacters();
?getAllPlayerCharacters@PlayerInterface@@QEBAAEBV?$lektor@PEAVCharacter@@@@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+73*8]
?getAllPlayerCharacters@PlayerInterface@@QEBAAEBV?$lektor@PEAVCharacter@@@@XZ endp

; PlayerInterface::isOrderValidForSelection(enum TaskType);
?isOrderValidForSelection@PlayerInterface@@QEBA_NW4TaskType@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+74*8]
?isOrderValidForSelection@PlayerInterface@@QEBA_NW4TaskType@@@Z endp

; PlayerInterface::serialise(class GameData *);
?serialise@PlayerInterface@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+75*8]
?serialise@PlayerInterface@@QEAAXPEAVGameData@@@Z endp

; PlayerInterface::loadFromSerialise(class GameData *);
?loadFromSerialise@PlayerInterface@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+76*8]
?loadFromSerialise@PlayerInterface@@QEAAXPEAVGameData@@@Z endp

; PlayerInterface::getInteriorsVisible(class Building *);
?getInteriorsVisible@PlayerInterface@@QEAA_NPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+77*8]
?getInteriorsVisible@PlayerInterface@@QEAA_NPEAVBuilding@@@Z endp

; PlayerInterface::setVisibilityForReflections(bool);
?setVisibilityForReflections@PlayerInterface@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+78*8]
?setVisibilityForReflections@PlayerInterface@@QEAAX_N@Z endp

; PlayerInterface::updateFloorVisibility(const class lektor<Character *> &);
?updateFloorVisibility@PlayerInterface@@QEAAXAEBV?$lektor@PEAVCharacter@@@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+79*8]
?updateFloorVisibility@PlayerInterface@@QEAAXAEBV?$lektor@PEAVCharacter@@@@@Z endp

; PlayerInterface::resetFloorsVisibility();
?resetFloorsVisibility@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+80*8]
?resetFloorsVisibility@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::setFloorsVisibility(int);
?setFloorsVisibility@PlayerInterface@@QEAAXH@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+81*8]
?setFloorsVisibility@PlayerInterface@@QEAAXH@Z endp

; PlayerInterface::addTaskNearestSelectedCharacter(class Building *, enum TaskType, class RootObject *, bool, const class Ogre::Vector3 &, bool);
?addTaskNearestSelectedCharacter@PlayerInterface@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@_NAEBVVector3@Ogre@@3@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+82*8]
?addTaskNearestSelectedCharacter@PlayerInterface@@QEAAXPEAVBuilding@@W4TaskType@@PEAVRootObject@@_NAEBVVector3@Ogre@@3@Z endp

; PlayerInterface::updateLastMoveWaypointSelectedCharacters(const class Ogre::Vector3 &, class Building *);
?updateLastMoveWaypointSelectedCharacters@PlayerInterface@@QEAAXAEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+83*8]
?updateLastMoveWaypointSelectedCharacters@PlayerInterface@@QEAAXAEBVVector3@Ogre@@PEAVBuilding@@@Z endp

; PlayerInterface::clearSelection();
?clearSelection@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+84*8]
?clearSelection@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::playerControl(class InputHandler &);
?playerControl@PlayerInterface@@QEAAXAEAVInputHandler@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+85*8]
?playerControl@PlayerInterface@@QEAAXAEAVInputHandler@@@Z endp

; PlayerInterface::mouseScan();
?mouseScan@PlayerInterface@@QEAAXXZ proc EXPORT
jmp function_pointers[_PlayerInterface_base+86*8]
?mouseScan@PlayerInterface@@QEAAXXZ endp

; PlayerInterface::characterSelected(class Character *);
?characterSelected@PlayerInterface@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+87*8]
?characterSelected@PlayerInterface@@QEAAXPEAVCharacter@@@Z endp

; PlayerInterface::itemSelected(class Item *);
?itemSelected@PlayerInterface@@QEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+88*8]
?itemSelected@PlayerInterface@@QEAAXPEAVItem@@@Z endp

; PlayerInterface::buildingSelected(class Building *, const class Ogre::Vector3 &, bool);
?buildingSelected@PlayerInterface@@QEAA_NPEAVBuilding@@AEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+89*8]
?buildingSelected@PlayerInterface@@QEAA_NPEAVBuilding@@AEBVVector3@Ogre@@_N@Z endp

; PlayerInterface::playerMove(const class Ogre::Vector3 &, class Building *);
?playerMove@PlayerInterface@@QEAAXAEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+90*8]
?playerMove@PlayerInterface@@QEAAXAEBVVector3@Ogre@@PEAVBuilding@@@Z endp

; PlayerInterface::_isPlayerCharacter(class RootObject *);
?_isPlayerCharacter@PlayerInterface@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_base+91*8]
?_isPlayerCharacter@PlayerInterface@@QEAA_NPEAVRootObject@@@Z endp
