
?_CONSTRUCTOR@AIOptions@PlayerInterface@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@AIOptions@PlayerInterface@@QEAAPEAV12@XZ endp

; PlayerInterface::AIOptions::AIOptions();
??0AIOptions@PlayerInterface@@QEAA@XZ proc EXPORT
jmp function_pointers[_PlayerInterface_AIOptions_base+0*8]
??0AIOptions@PlayerInterface@@QEAA@XZ endp

; PlayerInterface::AIOptions::load(class GameData *);
?load@AIOptions@PlayerInterface@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_AIOptions_base+1*8]
?load@AIOptions@PlayerInterface@@QEAAXPEAVGameData@@@Z endp

; PlayerInterface::AIOptions::save(class GameData *);
?save@AIOptions@PlayerInterface@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_PlayerInterface_AIOptions_base+2*8]
?save@AIOptions@PlayerInterface@@QEAAXPEAVGameData@@@Z endp
