
; PortraitManager::getInstance();
?getInstance@PortraitManager@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_PortraitManager_base+0*8]
?getInstance@PortraitManager@@SAPEAV1@XZ endp

; PortraitManager::init();
?init@PortraitManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_PortraitManager_base+1*8]
?init@PortraitManager@@QEAAXXZ endp

; PortraitManager::destroy();
?destroy@PortraitManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_PortraitManager_base+2*8]
?destroy@PortraitManager@@QEAAXXZ endp

; PortraitManager::setUpdateEnabled(bool);
?setUpdateEnabled@PortraitManager@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+3*8]
?setUpdateEnabled@PortraitManager@@QEAAX_N@Z endp

; PortraitManager::reloadPortraits();
?reloadPortraits@PortraitManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_PortraitManager_base+4*8]
?reloadPortraits@PortraitManager@@QEAAXXZ endp

; PortraitManager::reloadTexture();
?reloadTexture@PortraitManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_PortraitManager_base+5*8]
?reloadTexture@PortraitManager@@QEAAXXZ endp

; PortraitManager::saveTexture();
?saveTexture@PortraitManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_PortraitManager_base+6*8]
?saveTexture@PortraitManager@@QEAAXXZ endp

; PortraitManager::getPortrait(const class hand &);
?getPortrait@PortraitManager@@QEAAPEAVPortraitData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+7*8]
?getPortrait@PortraitManager@@QEAAPEAVPortraitData@@AEBVhand@@@Z endp

; PortraitManager::updatePortrait(const class hand &, const class hand &);
?updatePortrait@PortraitManager@@QEAAXAEBVhand@@0@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+8*8]
?updatePortrait@PortraitManager@@QEAAXAEBVhand@@0@Z endp

; PortraitManager::updatePortraitImage(const class hand &);
?updatePortraitImage@PortraitManager@@QEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+9*8]
?updatePortraitImage@PortraitManager@@QEAA_NAEBVhand@@@Z endp

; PortraitManager::clearPortraits(bool);
?clearPortraits@PortraitManager@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+10*8]
?clearPortraits@PortraitManager@@QEAAX_N@Z endp

; PortraitManager::setImageWidget(const class hand &, class MyGUI::ImageBox *, bool);
?setImageWidget@PortraitManager@@QEAAXAEBVhand@@PEAVImageBox@MyGUI@@_N@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+11*8]
?setImageWidget@PortraitManager@@QEAAXAEBVhand@@PEAVImageBox@MyGUI@@_N@Z endp

; PortraitManager::getCharacterFlashing(class Character *);
?getCharacterFlashing@PortraitManager@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+12*8]
?getCharacterFlashing@PortraitManager@@QEAA_NPEAVCharacter@@@Z endp

; PortraitManager::getCharacterInCombat(class Character *);
?getCharacterInCombat@PortraitManager@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+13*8]
?getCharacterInCombat@PortraitManager@@QEAA_NPEAVCharacter@@@Z endp

; PortraitManager::getCharacterDown(class Character *);
?getCharacterDown@PortraitManager@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+14*8]
?getCharacterDown@PortraitManager@@QEAA_NPEAVCharacter@@@Z endp

; PortraitManager::getSquadFlashing(class ActivePlatoon *);
?getSquadFlashing@PortraitManager@@QEAA_NPEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+15*8]
?getSquadFlashing@PortraitManager@@QEAA_NPEAVActivePlatoon@@@Z endp

?_CONSTRUCTOR@PortraitManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@PortraitManager@@QEAAPEAV1@XZ endp

; PortraitManager::PortraitManager();
??0PortraitManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_PortraitManager_base+16*8]
??0PortraitManager@@QEAA@XZ endp

?_DESTRUCTOR@PortraitManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PortraitManager@@QEAAXXZ endp

; PortraitManager::~PortraitManager();
??1PortraitManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_PortraitManager_base+17*8]
??1PortraitManager@@QEAA@XZ endp

; PortraitManager::createPortraitImage(class PortraitImage * &, class Character *);
?createPortraitImage@PortraitManager@@QEAA_NAEAPEAVPortraitImage@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+18*8]
?createPortraitImage@PortraitManager@@QEAA_NAEAPEAVPortraitImage@@PEAVCharacter@@@Z endp

; PortraitManager::getNextIndices(unsigned char &, unsigned char &);
?getNextIndices@PortraitManager@@QEAAXAEAE0@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+19*8]
?getNextIndices@PortraitManager@@QEAAXAEAE0@Z endp

; PortraitManager::setImageWidgetNPC(class Character *, class MyGUI::ImageBox *);
?setImageWidgetNPC@PortraitManager@@QEAAXPEAVCharacter@@PEAVImageBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_PortraitManager_base+20*8]
?setImageWidgetNPC@PortraitManager@@QEAAXPEAVCharacter@@PEAVImageBox@MyGUI@@@Z endp
