
; PortraitData::getCharacter();
?getCharacter@PortraitData@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_PortraitData_base+0*8]
?getCharacter@PortraitData@@QEBAPEAVCharacter@@XZ endp

; PortraitData::getHandle();
?getHandle@PortraitData@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_PortraitData_base+1*8]
?getHandle@PortraitData@@QEBAAEBVhand@@XZ endp

; PortraitData::update();
?update@PortraitData@@QEAA_NXZ proc EXPORT
jmp function_pointers[_PortraitData_base+2*8]
?update@PortraitData@@QEAA_NXZ endp

; PortraitData::forceUpdate();
?forceUpdate@PortraitData@@QEAAXXZ proc EXPORT
jmp function_pointers[_PortraitData_base+3*8]
?forceUpdate@PortraitData@@QEAAXXZ endp

; PortraitData::isSelected();
?isSelected@PortraitData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PortraitData_base+4*8]
?isSelected@PortraitData@@QEBA_NXZ endp

; PortraitData::isDown();
?isDown@PortraitData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_PortraitData_base+5*8]
?isDown@PortraitData@@QEBA_NXZ endp

; PortraitData::getBackgroundImageName();
?getBackgroundImageName@PortraitData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_PortraitData_base+6*8]
?getBackgroundImageName@PortraitData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; PortraitData::getBackOverlayImageName();
?getBackOverlayImageName@PortraitData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_PortraitData_base+7*8]
?getBackOverlayImageName@PortraitData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; PortraitData::getFrontOverlayImageName();
?getFrontOverlayImageName@PortraitData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_PortraitData_base+8*8]
?getFrontOverlayImageName@PortraitData@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_CONSTRUCTOR@PortraitData@@QEAAPEAV1@AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@PortraitData@@QEAAPEAV1@AEBVhand@@@Z endp

; PortraitData::PortraitData(const class hand &);
??0PortraitData@@QEAA@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_PortraitData_base+9*8]
??0PortraitData@@QEAA@AEBVhand@@@Z endp

?_DESTRUCTOR@PortraitData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PortraitData@@QEAAXXZ endp

; PortraitData::~PortraitData();
??1PortraitData@@QEAA@XZ proc EXPORT
jmp function_pointers[_PortraitData_base+10*8]
??1PortraitData@@QEAA@XZ endp
