
?_CONSTRUCTOR@PortraitImage@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GAEBU?$TCoord@H@types@MyGUI@@AEBU?$TRect@M@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@PortraitImage@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GAEBU?$TCoord@H@types@MyGUI@@AEBU?$TRect@M@Ogre@@@Z endp

; PortraitImage::PortraitImage(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, unsigned short, const struct MyGUI::types::TCoord<int> &, const struct Ogre::TRect<float> &);
??0PortraitImage@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GAEBU?$TCoord@H@types@MyGUI@@AEBU?$TRect@M@Ogre@@@Z proc EXPORT
jmp function_pointers[_PortraitImage_base+0*8]
??0PortraitImage@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GAEBU?$TCoord@H@types@MyGUI@@AEBU?$TRect@M@Ogre@@@Z endp

; PortraitImage::updateImageWidget(class MyGUI::ImageBox *, bool);
?updateImageWidget@PortraitImage@@QEAAXPEAVImageBox@MyGUI@@_N@Z proc EXPORT
jmp function_pointers[_PortraitImage_base+1*8]
?updateImageWidget@PortraitImage@@QEAAXPEAVImageBox@MyGUI@@_N@Z endp

?_DESTRUCTOR@PortraitImage@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PortraitImage@@QEAAXXZ endp

; PortraitImage::~PortraitImage();
??1PortraitImage@@QEAA@XZ proc EXPORT
jmp function_pointers[_PortraitImage_base+2*8]
??1PortraitImage@@QEAA@XZ endp
