
?_CONSTRUCTOR@PortraitMainCellView@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@PortraitMainCellView@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z endp

; PortraitMainCellView::PortraitMainCellView(class MyGUI::Widget *);
??0PortraitMainCellView@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_PortraitMainCellView_base+0*8]
??0PortraitMainCellView@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@PortraitMainCellView@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PortraitMainCellView@@QEAAXXZ endp

; PortraitMainCellView::~PortraitMainCellView();
??1PortraitMainCellView@@UEAA@XZ proc EXPORT
jmp function_pointers[_PortraitMainCellView_base+1*8]
??1PortraitMainCellView@@UEAA@XZ endp

; PortraitMainCellView::update(const struct MyGUI::IBDrawItemInfo &, class PortraitData *);
?update@PortraitMainCellView@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVPortraitData@@@Z proc EXPORT
jmp function_pointers[_PortraitMainCellView_base+2*8]
?update@PortraitMainCellView@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVPortraitData@@@Z endp

; PortraitMainCellView::getCellDimension(class MyGUI::Widget *, struct MyGUI::types::TCoord<int> &, bool);
?getCellDimension@PortraitMainCellView@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@3@_N@Z proc EXPORT
jmp function_pointers[_PortraitMainCellView_base+3*8]
?getCellDimension@PortraitMainCellView@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@3@_N@Z endp

; PortraitMainCellView::resize(int);
?resize@PortraitMainCellView@@QEAAXH@Z proc EXPORT
jmp function_pointers[_PortraitMainCellView_base+4*8]
?resize@PortraitMainCellView@@QEAAXH@Z endp

; PortraitMainCellView::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@PortraitMainCellView@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_PortraitMainCellView_base+5*8]
?setName@PortraitMainCellView@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
