
?_CONSTRUCTOR@ProductionBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@ProductionBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; ProductionBuilding::ProductionBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0ProductionBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+0*8]
??0ProductionBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@ProductionBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ProductionBuilding@@QEAAXXZ endp

; ProductionBuilding::~ProductionBuilding();
??1ProductionBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+1*8]
??1ProductionBuilding@@UEAA@XZ endp

?_NV_getProductionBuilding@ProductionBuilding@@QEAAPEAV1@XZ proc EXPORT
?_NV_getProductionBuilding@ProductionBuilding@@QEAAPEAV1@XZ endp

; ProductionBuilding::getProductionBuilding();
?getProductionBuilding@ProductionBuilding@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+2*8]
?getProductionBuilding@ProductionBuilding@@UEAAPEAV1@XZ endp

?_NV_createInventoryLayout@ProductionBuilding@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@ProductionBuilding@@QEAAPEAVInventoryLayout@@XZ endp

; ProductionBuilding::createInventoryLayout();
?createInventoryLayout@ProductionBuilding@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+3*8]
?createInventoryLayout@ProductionBuilding@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_update@ProductionBuilding@@QEAAXXZ proc EXPORT
?_NV_update@ProductionBuilding@@QEAAXXZ endp

; ProductionBuilding::update();
?update@ProductionBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+4*8]
?update@ProductionBuilding@@UEAAXXZ endp

?_NV_needsUpdate@ProductionBuilding@@QEAA_NXZ proc EXPORT
?_NV_needsUpdate@ProductionBuilding@@QEAA_NXZ endp

; ProductionBuilding::needsUpdate();
?needsUpdate@ProductionBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+5*8]
?needsUpdate@ProductionBuilding@@UEAA_NXZ endp

?_NV_operate@ProductionBuilding@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@ProductionBuilding@@QEAAXPEAVCharacter@@M@Z endp

; ProductionBuilding::operate(class Character *, float);
?operate@ProductionBuilding@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+6*8]
?operate@ProductionBuilding@@UEAAXPEAVCharacter@@M@Z endp

?_NV_getGUIData@ProductionBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@ProductionBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; ProductionBuilding::getGUIData(class DatapanelGUI *, int);
?getGUIData@ProductionBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+7*8]
?getGUIData@ProductionBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIToolTipForGroundResourceEfficiency@ProductionBuilding@@QEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
?_NV_getGUIToolTipForGroundResourceEfficiency@ProductionBuilding@@QEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; ProductionBuilding::getGUIToolTipForGroundResourceEfficiency(class lektor<StringPair> &);
?getGUIToolTipForGroundResourceEfficiency@ProductionBuilding@@UEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+8*8]
?getGUIToolTipForGroundResourceEfficiency@ProductionBuilding@@UEAAXAEAV?$lektor@VStringPair@@@@@Z endp

?_NV_serialise@ProductionBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@ProductionBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; ProductionBuilding::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@ProductionBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+9*8]
?serialise@ProductionBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@ProductionBuilding@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@ProductionBuilding@@QEAAXPEAVGameSaveState@@@Z endp

; ProductionBuilding::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@ProductionBuilding@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+10*8]
?loadFromSerialise@ProductionBuilding@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_getProductionMult@ProductionBuilding@@QEAAMXZ proc EXPORT
?_NV_getProductionMult@ProductionBuilding@@QEAAMXZ endp

; ProductionBuilding::getProductionMult();
?getProductionMult@ProductionBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+11*8]
?getProductionMult@ProductionBuilding@@UEAAMXZ endp

?_NV_getProductionMultForGUI@ProductionBuilding@@QEAAMXZ proc EXPORT
?_NV_getProductionMultForGUI@ProductionBuilding@@QEAAMXZ endp

; ProductionBuilding::getProductionMultForGUI();
?getProductionMultForGUI@ProductionBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+12*8]
?getProductionMultForGUI@ProductionBuilding@@UEAAMXZ endp

?_NV_setupMiningResourceLevel@ProductionBuilding@@QEAAXXZ proc EXPORT
?_NV_setupMiningResourceLevel@ProductionBuilding@@QEAAXXZ endp

; ProductionBuilding::setupMiningResourceLevel();
?setupMiningResourceLevel@ProductionBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+13*8]
?setupMiningResourceLevel@ProductionBuilding@@UEAAXXZ endp

?_NV_getMiningResourceLevel@ProductionBuilding@@QEBAMXZ proc EXPORT
?_NV_getMiningResourceLevel@ProductionBuilding@@QEBAMXZ endp

; ProductionBuilding::getMiningResourceLevel();
?getMiningResourceLevel@ProductionBuilding@@UEBAMXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+14*8]
?getMiningResourceLevel@ProductionBuilding@@UEBAMXZ endp

?_NV_getMouseCursor@ProductionBuilding@@QEAA?AW4CursorType@@XZ proc EXPORT
?_NV_getMouseCursor@ProductionBuilding@@QEAA?AW4CursorType@@XZ endp

; ProductionBuilding::getMouseCursor();
?getMouseCursor@ProductionBuilding@@UEAA?AW4CursorType@@XZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+15*8]
?getMouseCursor@ProductionBuilding@@UEAA?AW4CursorType@@XZ endp

?_NV_getDefaultTask@ProductionBuilding@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@ProductionBuilding@@QEAA?AW4TaskType@@XZ endp

; ProductionBuilding::getDefaultTask();
?getDefaultTask@ProductionBuilding@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+16*8]
?getDefaultTask@ProductionBuilding@@UEAA?AW4TaskType@@XZ endp

?_NV_getInputValue@ProductionBuilding@@QEAAMPEAVItem@@@Z proc EXPORT
?_NV_getInputValue@ProductionBuilding@@QEAAMPEAVItem@@@Z endp

; ProductionBuilding::getInputValue(class Item *);
?getInputValue@ProductionBuilding@@UEAAMPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+17*8]
?getInputValue@ProductionBuilding@@UEAAMPEAVItem@@@Z endp

?_NV_getResourcesNeededBecauseEmpty@ProductionBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
?_NV_getResourcesNeededBecauseEmpty@ProductionBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; ProductionBuilding::getResourcesNeededBecauseEmpty(class lektor<GameData *> &);
?getResourcesNeededBecauseEmpty@ProductionBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+18*8]
?getResourcesNeededBecauseEmpty@ProductionBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

?_NV_getResourcesNeededBecauseNotFull@ProductionBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
?_NV_getResourcesNeededBecauseNotFull@ProductionBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; ProductionBuilding::getResourcesNeededBecauseNotFull(class lektor<GameData *> &);
?getResourcesNeededBecauseNotFull@ProductionBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+19*8]
?getResourcesNeededBecauseNotFull@ProductionBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

?_NV_isAnyInputsEmpty@ProductionBuilding@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsEmpty@ProductionBuilding@@QEBA_NXZ endp

; ProductionBuilding::isAnyInputsEmpty();
?isAnyInputsEmpty@ProductionBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+20*8]
?isAnyInputsEmpty@ProductionBuilding@@UEBA_NXZ endp

?_NV_isAnyInputsInvalidType@ProductionBuilding@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsInvalidType@ProductionBuilding@@QEBA_NXZ endp

; ProductionBuilding::isAnyInputsInvalidType();
?isAnyInputsInvalidType@ProductionBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+21*8]
?isAnyInputsInvalidType@ProductionBuilding@@UEBA_NXZ endp

?_NV_isAnyInputsFull@ProductionBuilding@@QEAA_NXZ proc EXPORT
?_NV_isAnyInputsFull@ProductionBuilding@@QEAA_NXZ endp

; ProductionBuilding::isAnyInputsFull();
?isAnyInputsFull@ProductionBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+22*8]
?isAnyInputsFull@ProductionBuilding@@UEAA_NXZ endp

?_NV_isProductionFull@ProductionBuilding@@QEAA_NXZ proc EXPORT
?_NV_isProductionFull@ProductionBuilding@@QEAA_NXZ endp

; ProductionBuilding::isProductionFull();
?isProductionFull@ProductionBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+23*8]
?isProductionFull@ProductionBuilding@@UEAA_NXZ endp

?_NV_isProductionEmpty@ProductionBuilding@@QEAA_NXZ proc EXPORT
?_NV_isProductionEmpty@ProductionBuilding@@QEAA_NXZ endp

; ProductionBuilding::isProductionEmpty();
?isProductionEmpty@ProductionBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+24*8]
?isProductionEmpty@ProductionBuilding@@UEAA_NXZ endp

?_NV_canHaveSomeOfThese@ProductionBuilding@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_canHaveSomeOfThese@ProductionBuilding@@QEAA_NPEAVGameData@@@Z endp

; ProductionBuilding::canHaveSomeOfThese(class GameData *);
?canHaveSomeOfThese@ProductionBuilding@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+25*8]
?canHaveSomeOfThese@ProductionBuilding@@UEAA_NPEAVGameData@@@Z endp

?_NV_getOutputBasedRotationSpeedMult@ProductionBuilding@@QEAAMXZ proc EXPORT
?_NV_getOutputBasedRotationSpeedMult@ProductionBuilding@@QEAAMXZ endp

; ProductionBuilding::getOutputBasedRotationSpeedMult();
?getOutputBasedRotationSpeedMult@ProductionBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+26*8]
?getOutputBasedRotationSpeedMult@ProductionBuilding@@UEAAMXZ endp

?_NV_getItemsWeWantRidOf@ProductionBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z proc EXPORT
?_NV_getItemsWeWantRidOf@ProductionBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z endp

; ProductionBuilding::getItemsWeWantRidOf(class lektor<GameData *> &, bool);
?getItemsWeWantRidOf@ProductionBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+27*8]
?getItemsWeWantRidOf@ProductionBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z endp

; ProductionBuilding::getOutput();
?getOutput@ProductionBuilding@@QEBAMXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+28*8]
?getOutput@ProductionBuilding@@QEBAMXZ endp

?_NV_getNumConsumtionItems@ProductionBuilding@@QEBAHXZ proc EXPORT
?_NV_getNumConsumtionItems@ProductionBuilding@@QEBAHXZ endp

; ProductionBuilding::getNumConsumtionItems();
?getNumConsumtionItems@ProductionBuilding@@UEBAHXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+29*8]
?getNumConsumtionItems@ProductionBuilding@@UEBAHXZ endp

?_NV_getConsumtionItems@ProductionBuilding@@QEAAPEAVConsumptionItem@StorageBuilding@@H@Z proc EXPORT
?_NV_getConsumtionItems@ProductionBuilding@@QEAAPEAVConsumptionItem@StorageBuilding@@H@Z endp

; ProductionBuilding::getConsumtionItems(int);
?getConsumtionItems@ProductionBuilding@@UEAAPEAVConsumptionItem@StorageBuilding@@H@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+30*8]
?getConsumtionItems@ProductionBuilding@@UEAAPEAVConsumptionItem@StorageBuilding@@H@Z endp

?_NV_setProductionItem@ProductionBuilding@@QEAAXPEAVGameData@@HM@Z proc EXPORT
?_NV_setProductionItem@ProductionBuilding@@QEAAXPEAVGameData@@HM@Z endp

; ProductionBuilding::setProductionItem(class GameData *, int, float);
?setProductionItem@ProductionBuilding@@UEAAXPEAVGameData@@HM@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+31*8]
?setProductionItem@ProductionBuilding@@UEAAXPEAVGameData@@HM@Z endp

?_NV_setupFromData@ProductionBuilding@@QEAAXXZ proc EXPORT
?_NV_setupFromData@ProductionBuilding@@QEAAXXZ endp

; ProductionBuilding::setupFromData();
?setupFromData@ProductionBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+32*8]
?setupFromData@ProductionBuilding@@UEAAXXZ endp

?_NV_updateInventoryWindow@ProductionBuilding@@QEAAXXZ proc EXPORT
?_NV_updateInventoryWindow@ProductionBuilding@@QEAAXXZ endp

; ProductionBuilding::updateInventoryWindow();
?updateInventoryWindow@ProductionBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_ProductionBuilding_base+33*8]
?updateInventoryWindow@ProductionBuilding@@UEAAXXZ endp

?_NV_updateInputs@ProductionBuilding@@QEAAXM@Z proc EXPORT
?_NV_updateInputs@ProductionBuilding@@QEAAXM@Z endp

; ProductionBuilding::updateInputs(float);
?updateInputs@ProductionBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+34*8]
?updateInputs@ProductionBuilding@@UEAAXM@Z endp

?_NV_updateOutput@ProductionBuilding@@QEAAXM@Z proc EXPORT
?_NV_updateOutput@ProductionBuilding@@QEAAXM@Z endp

; ProductionBuilding::updateOutput(float);
?updateOutput@ProductionBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+35*8]
?updateOutput@ProductionBuilding@@UEAAXM@Z endp

?_NV_limitInputsOutputRate@ProductionBuilding@@QEAA_NAEAM@Z proc EXPORT
?_NV_limitInputsOutputRate@ProductionBuilding@@QEAA_NAEAM@Z endp

; ProductionBuilding::limitInputsOutputRate(float &);
?limitInputsOutputRate@ProductionBuilding@@UEAA_NAEAM@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+36*8]
?limitInputsOutputRate@ProductionBuilding@@UEAA_NAEAM@Z endp

?_NV_getGUIFertility@ProductionBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIFertility@ProductionBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; ProductionBuilding::getGUIFertility(class DatapanelGUI *, int);
?getGUIFertility@ProductionBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+37*8]
?getGUIFertility@ProductionBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIState@ProductionBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@ProductionBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; ProductionBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@ProductionBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_ProductionBuilding_base+38*8]
?getGUIState@ProductionBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp
