
?_CONSTRUCTOR@ProsperityManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ProsperityManager@@QEAAPEAV1@XZ endp

; ProsperityManager::ProsperityManager();
??0ProsperityManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_ProsperityManager_base+0*8]
??0ProsperityManager@@QEAA@XZ endp

; ProsperityManager::setup(class GameData *);
?setup@ProsperityManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+1*8]
?setup@ProsperityManager@@QEAAXPEAVGameData@@@Z endp

; ProsperityManager::load(class GameData *);
?load@ProsperityManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+2*8]
?load@ProsperityManager@@QEAAXPEAVGameData@@@Z endp

; ProsperityManager::save(class GameData *);
?save@ProsperityManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+3*8]
?save@ProsperityManager@@QEAAXPEAVGameData@@@Z endp

; ProsperityManager::getProsperityMultiplier();
?getProsperityMultiplier@ProsperityManager@@QEBAMXZ proc EXPORT
jmp function_pointers[_ProsperityManager_base+4*8]
?getProsperityMultiplier@ProsperityManager@@QEBAMXZ endp

; ProsperityManager::getGUIData(class DatapanelGUI *, int);
?getGUIData@ProsperityManager@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+5*8]
?getGUIData@ProsperityManager@@QEAAXPEAVDatapanelGUI@@H@Z endp

; ProsperityManager::update(float);
?update@ProsperityManager@@QEAAXM@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+6*8]
?update@ProsperityManager@@QEAAXM@Z endp

; ProsperityManager::notifySquadDefeated(class GameData *);
?notifySquadDefeated@ProsperityManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+7*8]
?notifySquadDefeated@ProsperityManager@@QEAAXPEAVGameData@@@Z endp

; ProsperityManager::notifySpecialNPCDead(class GameData *);
?notifySpecialNPCDead@ProsperityManager@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ProsperityManager_base+8*8]
?notifySpecialNPCDead@ProsperityManager@@QEAAXPEAVGameData@@@Z endp
