
?_CONSTRUCTOR@ProspectingWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ProspectingWindow@@QEAAPEAV1@XZ endp

; ProspectingWindow::ProspectingWindow();
??0ProspectingWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+0*8]
??0ProspectingWindow@@QEAA@XZ endp

?_DESTRUCTOR@ProspectingWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ProspectingWindow@@QEAAXXZ endp

; ProspectingWindow::~ProspectingWindow();
??1ProspectingWindow@@UEAA@XZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+1*8]
??1ProspectingWindow@@UEAA@XZ endp

; ProspectingWindow::getSingleton();
?getSingleton@ProspectingWindow@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+2*8]
?getSingleton@ProspectingWindow@@SAPEAV1@XZ endp

; ProspectingWindow::showT(const class Ogre::Vector3 &, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?showT@ProspectingWindow@@QEAAXAEBVVector3@Ogre@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ProspectingWindow_base+3*8]
?showT@ProspectingWindow@@QEAAXAEBVVector3@Ogre@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ProspectingWindow::_show();
?_show@ProspectingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+4*8]
?_show@ProspectingWindow@@QEAAXXZ endp

; ProspectingWindow::hide();
?hide@ProspectingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+5*8]
?hide@ProspectingWindow@@QEAAXXZ endp

; ProspectingWindow::getVisible();
?getVisible@ProspectingWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+6*8]
?getVisible@ProspectingWindow@@QEBA_NXZ endp

; ProspectingWindow::closeButton(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?closeButton@ProspectingWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ProspectingWindow_base+7*8]
?closeButton@ProspectingWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ProspectingWindow::updateCameraMarker();
?updateCameraMarker@ProspectingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+8*8]
?updateCameraMarker@ProspectingWindow@@QEAAXXZ endp

; ProspectingWindow::resourceSelected(class MyGUI::Widget *);
?resourceSelected@ProspectingWindow@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ProspectingWindow_base+9*8]
?resourceSelected@ProspectingWindow@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ProspectingWindow::worldToMapCoords(const class Ogre::Vector3 &);
?worldToMapCoords@ProspectingWindow@@QEBA?AU?$TPoint@H@types@MyGUI@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ProspectingWindow_base+10*8]
?worldToMapCoords@ProspectingWindow@@QEBA?AU?$TPoint@H@types@MyGUI@@AEBVVector3@Ogre@@@Z endp

; ProspectingWindow::updateMap(enum MiningResource);
?updateMap@ProspectingWindow@@QEAAXW4MiningResource@@@Z proc EXPORT
jmp function_pointers[_ProspectingWindow_base+11*8]
?updateMap@ProspectingWindow@@QEAAXW4MiningResource@@@Z endp

; ProspectingWindow::refresh();
?refresh@ProspectingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+12*8]
?refresh@ProspectingWindow@@QEAAXXZ endp

; ProspectingWindow::clear();
?clear@ProspectingWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_ProspectingWindow_base+13*8]
?clear@ProspectingWindow@@QEAAXXZ endp
