
; RaceLimiter::getSingleton();
?getSingleton@RaceLimiter@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_RaceLimiter_base+0*8]
?getSingleton@RaceLimiter@@SAPEAV1@XZ endp

; RaceLimiter::addLimit(class GameData *);
?addLimit@RaceLimiter@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RaceLimiter_base+1*8]
?addLimit@RaceLimiter@@QEAAXPEAVGameData@@@Z endp

?_NV_canEquip@RaceLimiter@@QEAA_NPEAVGameData@@PEAVRootObject@@@Z proc EXPORT
?_NV_canEquip@RaceLimiter@@QEAA_NPEAVGameData@@PEAVRootObject@@@Z endp

; RaceLimiter::canEquip(class GameData *, class RootObject *);
?canEquip@RaceLimiter@@UEAA_NPEAVGameData@@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_RaceLimiter_base+2*8]
?canEquip@RaceLimiter@@UEAA_NPEAVGameData@@PEAVRootObject@@@Z endp

?_NV_canEquip@RaceLimiter@@QEAA_NPEAVGameData@@PEAVRaceData@@_N@Z proc EXPORT
?_NV_canEquip@RaceLimiter@@QEAA_NPEAVGameData@@PEAVRaceData@@_N@Z endp

; RaceLimiter::canEquip(class GameData *, class RaceData *, bool);
?canEquip@RaceLimiter@@UEAA_NPEAVGameData@@PEAVRaceData@@_N@Z proc EXPORT
jmp function_pointers[_RaceLimiter_base+3*8]
?canEquip@RaceLimiter@@UEAA_NPEAVGameData@@PEAVRaceData@@_N@Z endp

?_CONSTRUCTOR@RaceLimiter@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@RaceLimiter@@QEAAPEAV1@XZ endp

; RaceLimiter::RaceLimiter();
??0RaceLimiter@@QEAA@XZ proc EXPORT
jmp function_pointers[_RaceLimiter_base+4*8]
??0RaceLimiter@@QEAA@XZ endp

?_DESTRUCTOR@RaceLimiter@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RaceLimiter@@QEAAXXZ endp

; RaceLimiter::~RaceLimiter();
??1RaceLimiter@@QEAA@XZ proc EXPORT
jmp function_pointers[_RaceLimiter_base+5*8]
??1RaceLimiter@@QEAA@XZ endp
