
; RaceData::getRaceData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getRaceData@RaceData@@SAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+0*8]
?getRaceData@RaceData@@SAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RaceData::getRaceData(class GameData *);
?getRaceData@RaceData@@SAPEAV1@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+1*8]
?getRaceData@RaceData@@SAPEAV1@PEAVGameData@@@Z endp

?_CONSTRUCTOR@RaceData@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@RaceData@@QEAAPEAV1@PEAVGameData@@@Z endp

; RaceData::RaceData(class GameData *);
??0RaceData@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+2*8]
??0RaceData@@QEAA@PEAVGameData@@@Z endp

; RaceData::isRelatedRace(class RaceData *);
?isRelatedRace@RaceData@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_RaceData_base+3*8]
?isRelatedRace@RaceData@@QEAA_NPEAV1@@Z endp

; RaceData::isRelatedRace(class GameData *);
?isRelatedRace@RaceData@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+4*8]
?isRelatedRace@RaceData@@QEAA_NPEAVGameData@@@Z endp

; RaceData::isSpecificRace(class GameData *);
?isSpecificRace@RaceData@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+5*8]
?isSpecificRace@RaceData@@QEAA_NPEAVGameData@@@Z endp

; RaceData::getStatMod(enum StatsEnumerated);
?getStatMod@RaceData@@QEAAMW4StatsEnumerated@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+6*8]
?getStatMod@RaceData@@QEAAMW4StatsEnumerated@@@Z endp

; RaceData::canEat(class GameData *, bool);
?canEat@RaceData@@QEBA_NPEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_RaceData_base+7*8]
?canEat@RaceData@@QEBA_NPEAVGameData@@_N@Z endp

; RaceData::canEat(class Item *, bool);
?canEat@RaceData@@QEBA_NPEAVItem@@_N@Z proc EXPORT
jmp function_pointers[_RaceData_base+8*8]
?canEat@RaceData@@QEBA_NPEAVItem@@_N@Z endp

; RaceData::isImmune(enum WeatherAffecting);
?isImmune@RaceData@@QEBA_NW4WeatherAffecting@@@Z proc EXPORT
jmp function_pointers[_RaceData_base+9*8]
?isImmune@RaceData@@QEBA_NW4WeatherAffecting@@@Z endp
