
?_NV_canEquip@Limiter@RaceLimiter@@QEAA_NPEAVRaceData@@_N@Z proc EXPORT
?_NV_canEquip@Limiter@RaceLimiter@@QEAA_NPEAVRaceData@@_N@Z endp

; RaceLimiter::Limiter::canEquip(class RaceData *, bool);
?canEquip@Limiter@RaceLimiter@@UEAA_NPEAVRaceData@@_N@Z proc EXPORT
jmp function_pointers[_RaceLimiter_Limiter_base+0*8]
?canEquip@Limiter@RaceLimiter@@UEAA_NPEAVRaceData@@_N@Z endp

?_CONSTRUCTOR@Limiter@RaceLimiter@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@Limiter@RaceLimiter@@QEAAPEAV12@XZ endp

; RaceLimiter::Limiter::Limiter();
??0Limiter@RaceLimiter@@QEAA@XZ proc EXPORT
jmp function_pointers[_RaceLimiter_Limiter_base+1*8]
??0Limiter@RaceLimiter@@QEAA@XZ endp

?_DESTRUCTOR@Limiter@RaceLimiter@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Limiter@RaceLimiter@@QEAAXXZ endp

; RaceLimiter::Limiter::~Limiter();
??1Limiter@RaceLimiter@@QEAA@XZ proc EXPORT
jmp function_pointers[_RaceLimiter_Limiter_base+2*8]
??1Limiter@RaceLimiter@@QEAA@XZ endp
