
?_CONSTRUCTOR@RainCollectorBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@RainCollectorBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; RainCollectorBuilding::RainCollectorBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0RainCollectorBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_RainCollectorBuilding_base+0*8]
??0RainCollectorBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_NV_calculateEfficiencyMult@RainCollectorBuilding@@QEBAMXZ proc EXPORT
?_NV_calculateEfficiencyMult@RainCollectorBuilding@@QEBAMXZ endp

; RainCollectorBuilding::calculateEfficiencyMult();
?calculateEfficiencyMult@RainCollectorBuilding@@UEBAMXZ proc EXPORT
jmp function_pointers[_RainCollectorBuilding_base+1*8]
?calculateEfficiencyMult@RainCollectorBuilding@@UEBAMXZ endp

?_NV_getGUIState@RainCollectorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@RainCollectorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; RainCollectorBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@RainCollectorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_RainCollectorBuilding_base+2*8]
?getGUIState@RainCollectorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIToolTipForGroundResourceEfficiency@RainCollectorBuilding@@QEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
?_NV_getGUIToolTipForGroundResourceEfficiency@RainCollectorBuilding@@QEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; RainCollectorBuilding::getGUIToolTipForGroundResourceEfficiency(class lektor<StringPair> &);
?getGUIToolTipForGroundResourceEfficiency@RainCollectorBuilding@@UEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_RainCollectorBuilding_base+3*8]
?getGUIToolTipForGroundResourceEfficiency@RainCollectorBuilding@@UEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; RainCollectorBuilding::getRainAmount();
?getRainAmount@RainCollectorBuilding@@QEBAMXZ proc EXPORT
jmp function_pointers[_RainCollectorBuilding_base+4*8]
?getRainAmount@RainCollectorBuilding@@QEBAMXZ endp

?_DESTRUCTOR@RainCollectorBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RainCollectorBuilding@@QEAAXXZ endp

; RainCollectorBuilding::~RainCollectorBuilding();
??1RainCollectorBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_RainCollectorBuilding_base+5*8]
??1RainCollectorBuilding@@UEAA@XZ endp
