
?_CONSTRUCTOR@ResearchBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@ResearchBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; ResearchBuilding::ResearchBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0ResearchBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_ResearchBuilding_base+0*8]
??0ResearchBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@ResearchBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ResearchBuilding@@QEAAXXZ endp

; ResearchBuilding::~ResearchBuilding();
??1ResearchBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+1*8]
??1ResearchBuilding@@UEAA@XZ endp

?_NV_dontNeedWorkRightNow@ResearchBuilding@@QEBA_NXZ proc EXPORT
?_NV_dontNeedWorkRightNow@ResearchBuilding@@QEBA_NXZ endp

; ResearchBuilding::dontNeedWorkRightNow();
?dontNeedWorkRightNow@ResearchBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+2*8]
?dontNeedWorkRightNow@ResearchBuilding@@UEBA_NXZ endp

?_NV_getDefaultTask@ResearchBuilding@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@ResearchBuilding@@QEAA?AW4TaskType@@XZ endp

; ResearchBuilding::getDefaultTask();
?getDefaultTask@ResearchBuilding@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+3*8]
?getDefaultTask@ResearchBuilding@@UEAA?AW4TaskType@@XZ endp

?_NV_update@ResearchBuilding@@QEAAXXZ proc EXPORT
?_NV_update@ResearchBuilding@@QEAAXXZ endp

; ResearchBuilding::update();
?update@ResearchBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+4*8]
?update@ResearchBuilding@@UEAAXXZ endp

?_NV_operate@ResearchBuilding@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@ResearchBuilding@@QEAAXPEAVCharacter@@M@Z endp

; ResearchBuilding::operate(class Character *, float);
?operate@ResearchBuilding@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_ResearchBuilding_base+5*8]
?operate@ResearchBuilding@@UEAAXPEAVCharacter@@M@Z endp

?_NV_notifyConstructionComplete@ResearchBuilding@@QEAAXXZ proc EXPORT
?_NV_notifyConstructionComplete@ResearchBuilding@@QEAAXXZ endp

; ResearchBuilding::notifyConstructionComplete();
?notifyConstructionComplete@ResearchBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+6*8]
?notifyConstructionComplete@ResearchBuilding@@UEAAXXZ endp

?_NV_getGUIData@ResearchBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@ResearchBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; ResearchBuilding::getGUIData(class DatapanelGUI *, int);
?getGUIData@ResearchBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_ResearchBuilding_base+7*8]
?getGUIData@ResearchBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getTechLevel@ResearchBuilding@@QEAAHXZ proc EXPORT
?_NV_getTechLevel@ResearchBuilding@@QEAAHXZ endp

; ResearchBuilding::getTechLevel();
?getTechLevel@ResearchBuilding@@UEAAHXZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+8*8]
?getTechLevel@ResearchBuilding@@UEAAHXZ endp

?_NV_createInventoryLayout@ResearchBuilding@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@ResearchBuilding@@QEAAPEAVInventoryLayout@@XZ endp

; ResearchBuilding::createInventoryLayout();
?createInventoryLayout@ResearchBuilding@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_ResearchBuilding_base+9*8]
?createInventoryLayout@ResearchBuilding@@UEAAPEAVInventoryLayout@@XZ endp

; ResearchBuilding::showResearchWindow(class MyGUI::Widget *);
?showResearchWindow@ResearchBuilding@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ResearchBuilding_base+10*8]
?showResearchWindow@ResearchBuilding@@QEAAXPEAVWidget@MyGUI@@@Z endp
