
?_CONSTRUCTOR@ResearchBuildingInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ResearchBuildingInventoryLayout@@QEAAPEAV1@XZ endp

; ResearchBuildingInventoryLayout::ResearchBuildingInventoryLayout();
??0ResearchBuildingInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_ResearchBuildingInventoryLayout_base+0*8]
??0ResearchBuildingInventoryLayout@@QEAA@XZ endp

; symbol is too long
; ?setupSections@ResearchBuildingInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; ResearchBuildingInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
ResearchBuildingInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_ResearchBuildingInventoryLayout_base+1*8]
ResearchBuildingInventoryLayout_setupSections_PLACEHOLDER endp

; ResearchBuildingInventoryLayout::getResearchButton();
?getResearchButton@ResearchBuildingInventoryLayout@@QEBAPEAVWidget@MyGUI@@XZ proc EXPORT
jmp function_pointers[_ResearchBuildingInventoryLayout_base+2*8]
?getResearchButton@ResearchBuildingInventoryLayout@@QEBAPEAVWidget@MyGUI@@XZ endp

?_DESTRUCTOR@ResearchBuildingInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ResearchBuildingInventoryLayout@@QEAAXXZ endp

; ResearchBuildingInventoryLayout::~ResearchBuildingInventoryLayout();
??1ResearchBuildingInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_ResearchBuildingInventoryLayout_base+3*8]
??1ResearchBuildingInventoryLayout@@UEAA@XZ endp
