
?_CONSTRUCTOR@TextureLoadData@ResourceLoader@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
?_CONSTRUCTOR@TextureLoadData@ResourceLoader@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; ResourceLoader::TextureLoadData::TextureLoadData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0TextureLoadData@ResourceLoader@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_ResourceLoader_TextureLoadData_base+0*8]
??0TextureLoadData@ResourceLoader@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

?_DESTRUCTOR@TextureLoadData@ResourceLoader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TextureLoadData@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::TextureLoadData::~TextureLoadData();
??1TextureLoadData@ResourceLoader@@UEAA@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_TextureLoadData_base+1*8]
??1TextureLoadData@ResourceLoader@@UEAA@XZ endp

?_NV_loadImage@TextureLoadData@ResourceLoader@@QEAAXXZ proc EXPORT
?_NV_loadImage@TextureLoadData@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::TextureLoadData::loadImage();
?loadImage@TextureLoadData@ResourceLoader@@UEAAXXZ proc EXPORT
jmp function_pointers[_ResourceLoader_TextureLoadData_base+2*8]
?loadImage@TextureLoadData@ResourceLoader@@UEAAXXZ endp

?_NV_getTexture@TextureLoadData@ResourceLoader@@QEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ proc EXPORT
?_NV_getTexture@TextureLoadData@ResourceLoader@@QEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ endp

; ResourceLoader::TextureLoadData::getTexture();
?getTexture@TextureLoadData@ResourceLoader@@UEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_TextureLoadData_base+3*8]
?getTexture@TextureLoadData@ResourceLoader@@UEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ endp
