
?_CONSTRUCTOR@ResourceLoadRequestMesh@ResourceLoader@@QEAAPEAV12@_KAEBV?$function@$$A6AXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z@boost@@PEAVEntity@Ogre@@AEBVMeshLoadData@2@@Z proc EXPORT
?_CONSTRUCTOR@ResourceLoadRequestMesh@ResourceLoader@@QEAAPEAV12@_KAEBV?$function@$$A6AXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z@boost@@PEAVEntity@Ogre@@AEBVMeshLoadData@2@@Z endp

; ResourceLoader::ResourceLoadRequestMesh::ResourceLoadRequestMesh(unsigned __int64, const class boost::function<void __cdecl(Ogre::SharedPtr<Ogre::Resource>,void *)> &, class Ogre::Entity *, const class ResourceLoader::MeshLoadData &);
??0ResourceLoadRequestMesh@ResourceLoader@@QEAA@_KAEBV?$function@$$A6AXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z@boost@@PEAVEntity@Ogre@@AEBVMeshLoadData@1@@Z proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestMesh_base+0*8]
??0ResourceLoadRequestMesh@ResourceLoader@@QEAA@_KAEBV?$function@$$A6AXV?$SharedPtr@VResource@Ogre@@@Ogre@@PEAX@Z@boost@@PEAVEntity@Ogre@@AEBVMeshLoadData@1@@Z endp

?_DESTRUCTOR@ResourceLoadRequestMesh@ResourceLoader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ResourceLoadRequestMesh@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::ResourceLoadRequestMesh::~ResourceLoadRequestMesh();
??1ResourceLoadRequestMesh@ResourceLoader@@QEAA@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestMesh_base+1*8]
??1ResourceLoadRequestMesh@ResourceLoader@@QEAA@XZ endp

; ResourceLoader::ResourceLoadRequestMesh::finish();
?finish@ResourceLoadRequestMesh@ResourceLoader@@QEAAXXZ proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestMesh_base+2*8]
?finish@ResourceLoadRequestMesh@ResourceLoader@@QEAAXXZ endp
