
?_CONSTRUCTOR@MeshLoadData@ResourceLoader@@QEAAPEAV12@AEBV12@@Z proc EXPORT
?_CONSTRUCTOR@MeshLoadData@ResourceLoader@@QEAAPEAV12@AEBV12@@Z endp

; ResourceLoader::MeshLoadData::MeshLoadData(const class ResourceLoader::MeshLoadData &);
??0MeshLoadData@ResourceLoader@@QEAA@AEBV01@@Z proc EXPORT
jmp function_pointers[_ResourceLoader_MeshLoadData_base+0*8]
??0MeshLoadData@ResourceLoader@@QEAA@AEBV01@@Z endp

?_CONSTRUCTOR@MeshLoadData@ResourceLoader@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@MeshLoadData@ResourceLoader@@QEAAPEAV12@XZ endp

; ResourceLoader::MeshLoadData::MeshLoadData();
??0MeshLoadData@ResourceLoader@@QEAA@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_MeshLoadData_base+1*8]
??0MeshLoadData@ResourceLoader@@QEAA@XZ endp

?_DESTRUCTOR@MeshLoadData@ResourceLoader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@MeshLoadData@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::MeshLoadData::~MeshLoadData();
??1MeshLoadData@ResourceLoader@@QEAA@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_MeshLoadData_base+2*8]
??1MeshLoadData@ResourceLoader@@QEAA@XZ endp
