
?_CONSTRUCTOR@ResourceLoadRequestTexture@ResourceLoader@@QEAAPEAV12@AEBV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVTextureUnitState@4@@Z proc EXPORT
?_CONSTRUCTOR@ResourceLoadRequestTexture@ResourceLoader@@QEAAPEAV12@AEBV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVTextureUnitState@4@@Z endp

; ResourceLoader::ResourceLoadRequestTexture::ResourceLoadRequestTexture(const class Ogre::SharedPtr<Ogre::Material> &, class Ogre::TextureUnitState *);
??0ResourceLoadRequestTexture@ResourceLoader@@QEAA@AEBV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVTextureUnitState@3@@Z proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestTexture_base+0*8]
??0ResourceLoadRequestTexture@ResourceLoader@@QEAA@AEBV?$SharedPtr@VMaterial@Ogre@@@Ogre@@PEAVTextureUnitState@3@@Z endp

?_DESTRUCTOR@ResourceLoadRequestTexture@ResourceLoader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ResourceLoadRequestTexture@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::ResourceLoadRequestTexture::~ResourceLoadRequestTexture();
??1ResourceLoadRequestTexture@ResourceLoader@@QEAA@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestTexture_base+1*8]
??1ResourceLoadRequestTexture@ResourceLoader@@QEAA@XZ endp

; ResourceLoader::ResourceLoadRequestTexture::isMaterialValid();
?isMaterialValid@ResourceLoadRequestTexture@ResourceLoader@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestTexture_base+2*8]
?isMaterialValid@ResourceLoadRequestTexture@ResourceLoader@@QEBA_NXZ endp

; ResourceLoader::ResourceLoadRequestTexture::setTexture(const class Ogre::SharedPtr<Ogre::Texture> &);
?setTexture@ResourceLoadRequestTexture@ResourceLoader@@QEAAXAEBV?$SharedPtr@VTexture@Ogre@@@Ogre@@@Z proc EXPORT
jmp function_pointers[_ResourceLoader_ResourceLoadRequestTexture_base+3*8]
?setTexture@ResourceLoadRequestTexture@ResourceLoader@@QEAAXAEBV?$SharedPtr@VTexture@Ogre@@@Ogre@@@Z endp
