
; symbol is too long
; ??0TextureArrayLoadData@ResourceLoader@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$STLAllocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@3@0@Z
; ResourceLoader::TextureArrayLoadData::TextureArrayLoadData(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,Ogre::STLAllocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,Ogre::CategorisedAllocPolicy<0> > > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
ResourceLoader_TextureArrayLoadData_TextureArrayLoadData_PLACEHOLDER proc EXPORT
jmp function_pointers[_ResourceLoader_TextureArrayLoadData_base+0*8]
ResourceLoader_TextureArrayLoadData_TextureArrayLoadData_PLACEHOLDER endp

?_DESTRUCTOR@TextureArrayLoadData@ResourceLoader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TextureArrayLoadData@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::TextureArrayLoadData::~TextureArrayLoadData();
??1TextureArrayLoadData@ResourceLoader@@UEAA@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_TextureArrayLoadData_base+1*8]
??1TextureArrayLoadData@ResourceLoader@@UEAA@XZ endp

?_NV_loadImage@TextureArrayLoadData@ResourceLoader@@QEAAXXZ proc EXPORT
?_NV_loadImage@TextureArrayLoadData@ResourceLoader@@QEAAXXZ endp

; ResourceLoader::TextureArrayLoadData::loadImage();
?loadImage@TextureArrayLoadData@ResourceLoader@@UEAAXXZ proc EXPORT
jmp function_pointers[_ResourceLoader_TextureArrayLoadData_base+2*8]
?loadImage@TextureArrayLoadData@ResourceLoader@@UEAAXXZ endp

?_NV_getTexture@TextureArrayLoadData@ResourceLoader@@QEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ proc EXPORT
?_NV_getTexture@TextureArrayLoadData@ResourceLoader@@QEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ endp

; ResourceLoader::TextureArrayLoadData::getTexture();
?getTexture@TextureArrayLoadData@ResourceLoader@@UEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ proc EXPORT
jmp function_pointers[_ResourceLoader_TextureArrayLoadData_base+3*8]
?getTexture@TextureArrayLoadData@ResourceLoader@@UEAA?AV?$SharedPtr@VTexture@Ogre@@@Ogre@@XZ endp
