
?_CONSTRUCTOR@RobotLimbs@@QEAAPEAV1@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@RobotLimbs@@QEAAPEAV1@PEAVCharacter@@@Z endp

; RobotLimbs::RobotLimbs(class Character *);
??0RobotLimbs@@QEAA@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+0*8]
??0RobotLimbs@@QEAA@PEAVCharacter@@@Z endp

?_DESTRUCTOR@RobotLimbs@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RobotLimbs@@QEAAXXZ endp

; RobotLimbs::~RobotLimbs();
??1RobotLimbs@@QEAA@XZ proc EXPORT
jmp function_pointers[_RobotLimbs_base+1*8]
??1RobotLimbs@@QEAA@XZ endp

; RobotLimbs::load(class GameData *);
?load@RobotLimbs@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+2*8]
?load@RobotLimbs@@QEAAXPEAVGameData@@@Z endp

; RobotLimbs::save(class GameData *);
?save@RobotLimbs@@QEBAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+3*8]
?save@RobotLimbs@@QEBAXPEAVGameData@@@Z endp

; RobotLimbs::getState(enum RobotLimbs::Limb);
?getState@RobotLimbs@@QEBA?AW4LimbState@@W4Limb@1@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+4*8]
?getState@RobotLimbs@@QEBA?AW4LimbState@@W4Limb@1@@Z endp

; RobotLimbs::getLimb(enum RobotLimbs::Limb);
?getLimb@RobotLimbs@@QEBAPEAVItem@@W4Limb@1@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+5*8]
?getLimb@RobotLimbs@@QEBAPEAVItem@@W4Limb@1@@Z endp

; RobotLimbs::getMask();
?getMask@RobotLimbs@@QEBAHXZ proc EXPORT
jmp function_pointers[_RobotLimbs_base+6*8]
?getMask@RobotLimbs@@QEBAHXZ endp

; RobotLimbs::setLimb(enum RobotLimbs::Limb, enum LimbState, class Item *);
?setLimb@RobotLimbs@@QEAAXW4Limb@1@W4LimbState@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+7*8]
?setLimb@RobotLimbs@@QEAAXW4Limb@1@W4LimbState@@PEAVItem@@@Z endp

; RobotLimbs::getInventoryInterface(bool);
?getInventoryInterface@RobotLimbs@@QEAAPEAVRootObject@@_N@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+8*8]
?getInventoryInterface@RobotLimbs@@QEAAPEAVRootObject@@_N@Z endp

; RobotLimbs::destroyInventoryInterface();
?destroyInventoryInterface@RobotLimbs@@QEAAXXZ proc EXPORT
jmp function_pointers[_RobotLimbs_base+9*8]
?destroyInventoryInterface@RobotLimbs@@QEAAXXZ endp

; RobotLimbs::getLimbItem(enum RobotLimbs::Limb);
?getLimbItem@RobotLimbs@@QEAAPEAVItem@@W4Limb@1@@Z proc EXPORT
jmp function_pointers[_RobotLimbs_base+10*8]
?getLimbItem@RobotLimbs@@QEAAPEAVItem@@W4Limb@1@@Z endp
