
?_CONSTRUCTOR@SpecificItemLoadFirst@RootObjectContainer@@QEAAPEAV12@W4itemType@@0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
?_CONSTRUCTOR@SpecificItemLoadFirst@RootObjectContainer@@QEAAPEAV12@W4itemType@@0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; RootObjectContainer::SpecificItemLoadFirst::SpecificItemLoadFirst(enum itemType, enum itemType, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
??0SpecificItemLoadFirst@RootObjectContainer@@QEAA@W4itemType@@0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_SpecificItemLoadFirst_base+0*8]
??0SpecificItemLoadFirst@RootObjectContainer@@QEAA@W4itemType@@0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

?_NV_shouldSkip@SpecificItemLoadFirst@RootObjectContainer@@QEAA_NPEAVGameSaveState@@@Z proc EXPORT
?_NV_shouldSkip@SpecificItemLoadFirst@RootObjectContainer@@QEAA_NPEAVGameSaveState@@@Z endp

; RootObjectContainer::SpecificItemLoadFirst::shouldSkip(class GameSaveState *);
?shouldSkip@SpecificItemLoadFirst@RootObjectContainer@@UEAA_NPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_SpecificItemLoadFirst_base+1*8]
?shouldSkip@SpecificItemLoadFirst@RootObjectContainer@@UEAA_NPEAVGameSaveState@@@Z endp

; RootObjectContainer::SpecificItemLoadFirst::flip();
?flip@SpecificItemLoadFirst@RootObjectContainer@@QEAAXXZ proc EXPORT
jmp function_pointers[_RootObjectContainer_SpecificItemLoadFirst_base+2*8]
?flip@SpecificItemLoadFirst@RootObjectContainer@@QEAAXXZ endp

?_DESTRUCTOR@SpecificItemLoadFirst@RootObjectContainer@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SpecificItemLoadFirst@RootObjectContainer@@QEAAXXZ endp

; RootObjectContainer::SpecificItemLoadFirst::~SpecificItemLoadFirst();
??1SpecificItemLoadFirst@RootObjectContainer@@QEAA@XZ proc EXPORT
jmp function_pointers[_RootObjectContainer_SpecificItemLoadFirst_base+3*8]
??1SpecificItemLoadFirst@RootObjectContainer@@QEAA@XZ endp
