
?_CONSTRUCTOR@CreatelistItem@RootObjectFactory@@QEAAPEAV12@PEAVGameData@@VVector3@Ogre@@_NPEAVFaction@@VQuaternion@5@PEAVFactoryCallbackInterface@@PEAVGameSaveState@@PEAVRootObjectContainer@@PEAVBuilding@@M@Z proc EXPORT
?_CONSTRUCTOR@CreatelistItem@RootObjectFactory@@QEAAPEAV12@PEAVGameData@@VVector3@Ogre@@_NPEAVFaction@@VQuaternion@5@PEAVFactoryCallbackInterface@@PEAVGameSaveState@@PEAVRootObjectContainer@@PEAVBuilding@@M@Z endp

; RootObjectFactory::CreatelistItem::CreatelistItem(class GameData *, class Ogre::Vector3, bool, class Faction *, class Ogre::Quaternion, class FactoryCallbackInterface *, class GameSaveState *, class RootObjectContainer *, class Building *, float);
??0CreatelistItem@RootObjectFactory@@QEAA@PEAVGameData@@VVector3@Ogre@@_NPEAVFaction@@VQuaternion@4@PEAVFactoryCallbackInterface@@PEAVGameSaveState@@PEAVRootObjectContainer@@PEAVBuilding@@M@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_CreatelistItem_base+0*8]
??0CreatelistItem@RootObjectFactory@@QEAA@PEAVGameData@@VVector3@Ogre@@_NPEAVFaction@@VQuaternion@4@PEAVFactoryCallbackInterface@@PEAVGameSaveState@@PEAVRootObjectContainer@@PEAVBuilding@@M@Z endp
