
?_CONSTRUCTOR@RootObject@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@RootObject@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@Vhand@@@Z endp

; RootObject::RootObject(class GameData *, class Faction *, class hand);
??0RootObject@@QEAA@PEAVGameData@@PEAVFaction@@Vhand@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+0*8]
??0RootObject@@QEAA@PEAVGameData@@PEAVFaction@@Vhand@@@Z endp

?_DESTRUCTOR@RootObject@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RootObject@@QEAAXXZ endp

; RootObject::~RootObject();
??1RootObject@@UEAA@XZ proc EXPORT
jmp function_pointers[_RootObject_base+1*8]
??1RootObject@@UEAA@XZ endp

?_NV_needsSaving@RootObject@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_needsSaving@RootObject@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RootObject::needsSaving(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?needsSaving@RootObject@@UEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+2*8]
?needsSaving@RootObject@@UEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getInstanceID@RootObject@@QEAAPEAVInstanceID@@XZ proc EXPORT
?_NV_getInstanceID@RootObject@@QEAAPEAVInstanceID@@XZ endp

; RootObject::getInstanceID();
?getInstanceID@RootObject@@UEAAPEAVInstanceID@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+3*8]
?getInstanceID@RootObject@@UEAAPEAVInstanceID@@XZ endp

?_NV_getLayoutInstanceID@RootObject@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getLayoutInstanceID@RootObject@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; RootObject::getLayoutInstanceID();
?getLayoutInstanceID@RootObject@@UEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+4*8]
?getLayoutInstanceID@RootObject@@UEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getOrientation@RootObject@@QEBA?AVQuaternion@Ogre@@XZ proc EXPORT
?_NV_getOrientation@RootObject@@QEBA?AVQuaternion@Ogre@@XZ endp

; RootObject::getOrientation();
?getOrientation@RootObject@@UEBA?AVQuaternion@Ogre@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+5*8]
?getOrientation@RootObject@@UEBA?AVQuaternion@Ogre@@XZ endp

?_NV_getZoneMapLocation@RootObject@@QEAAPEAVZoneMap@@XZ proc EXPORT
?_NV_getZoneMapLocation@RootObject@@QEAAPEAVZoneMap@@XZ endp

; RootObject::getZoneMapLocation();
?getZoneMapLocation@RootObject@@UEAAPEAVZoneMap@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+6*8]
?getZoneMapLocation@RootObject@@UEAAPEAVZoneMap@@XZ endp

?_NV_getRace@RootObject@@QEBAPEAVRaceData@@XZ proc EXPORT
?_NV_getRace@RootObject@@QEBAPEAVRaceData@@XZ endp

; RootObject::getRace();
?getRace@RootObject@@UEBAPEAVRaceData@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+7*8]
?getRace@RootObject@@UEBAPEAVRaceData@@XZ endp

?_NV_threadedUpdate@RootObject@@QEAAXXZ proc EXPORT
?_NV_threadedUpdate@RootObject@@QEAAXXZ endp

; RootObject::threadedUpdate();
?threadedUpdate@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+8*8]
?threadedUpdate@RootObject@@UEAAXXZ endp

?_NV_update@RootObject@@QEAAXXZ proc EXPORT
?_NV_update@RootObject@@QEAAXXZ endp

; RootObject::update();
?update@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+9*8]
?update@RootObject@@UEAAXXZ endp

?_NV_periodicUpdate@RootObject@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@RootObject@@QEAAXXZ endp

; RootObject::periodicUpdate();
?periodicUpdate@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+10*8]
?periodicUpdate@RootObject@@UEAAXXZ endp

?_NV_getAABB@RootObject@@QEBAAEBUAabb@Ogre@@XZ proc EXPORT
?_NV_getAABB@RootObject@@QEBAAEBUAabb@Ogre@@XZ endp

; RootObject::getAABB();
?getAABB@RootObject@@UEBAAEBUAabb@Ogre@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+11*8]
?getAABB@RootObject@@UEBAAEBUAabb@Ogre@@XZ endp

?_NV_getVisible@RootObject@@QEBA_NXZ proc EXPORT
?_NV_getVisible@RootObject@@QEBA_NXZ endp

; RootObject::getVisible();
?getVisible@RootObject@@UEBA_NXZ proc EXPORT
jmp function_pointers[_RootObject_base+12*8]
?getVisible@RootObject@@UEBA_NXZ endp

?_NV_isDisabled@RootObject@@QEAA_NXZ proc EXPORT
?_NV_isDisabled@RootObject@@QEAA_NXZ endp

; RootObject::isDisabled();
?isDisabled@RootObject@@UEAA_NXZ proc EXPORT
jmp function_pointers[_RootObject_base+13*8]
?isDisabled@RootObject@@UEAA_NXZ endp

?_NV_setFaction@RootObject@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
?_NV_setFaction@RootObject@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

; RootObject::setFaction(class Faction *, class ActivePlatoon *);
?setFaction@RootObject@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+14*8]
?setFaction@RootObject@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

?_NV_amInsideTownWalls@RootObject@@QEAAHXZ proc EXPORT
?_NV_amInsideTownWalls@RootObject@@QEAAHXZ endp

; RootObject::amInsideTownWalls();
?amInsideTownWalls@RootObject@@UEAAHXZ proc EXPORT
jmp function_pointers[_RootObject_base+15*8]
?amInsideTownWalls@RootObject@@UEAAHXZ endp

?_NV_setInsideTownWalls@RootObject@@QEAAXH@Z proc EXPORT
?_NV_setInsideTownWalls@RootObject@@QEAAXH@Z endp

; RootObject::setInsideTownWalls(int);
?setInsideTownWalls@RootObject@@UEAAXH@Z proc EXPORT
jmp function_pointers[_RootObject_base+16*8]
?setInsideTownWalls@RootObject@@UEAAXH@Z endp

?_NV_getFloor@RootObject@@QEBAHXZ proc EXPORT
?_NV_getFloor@RootObject@@QEBAHXZ endp

; RootObject::getFloor();
?getFloor@RootObject@@UEBAHXZ proc EXPORT
jmp function_pointers[_RootObject_base+17*8]
?getFloor@RootObject@@UEBAHXZ endp

?_NV_setFloor@RootObject@@QEAAXH@Z proc EXPORT
?_NV_setFloor@RootObject@@QEAAXH@Z endp

; RootObject::setFloor(int);
?setFloor@RootObject@@UEAAXH@Z proc EXPORT
jmp function_pointers[_RootObject_base+18*8]
?setFloor@RootObject@@UEAAXH@Z endp

?_NV_select@RootObject@@QEAAXXZ proc EXPORT
?_NV_select@RootObject@@QEAAXXZ endp

; RootObject::select();
?select@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+19*8]
?select@RootObject@@UEAAXXZ endp

?_NV_unselect@RootObject@@QEAAXXZ proc EXPORT
?_NV_unselect@RootObject@@QEAAXXZ endp

; RootObject::unselect();
?unselect@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+20*8]
?unselect@RootObject@@UEAAXXZ endp

?_NV_getGUIData@RootObject@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@RootObject@@QEAAXPEAVDatapanelGUI@@H@Z endp

; RootObject::getGUIData(class DatapanelGUI *, int);
?getGUIData@RootObject@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_RootObject_base+21*8]
?getGUIData@RootObject@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIDataCategories@RootObject@@QEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
?_NV_getGUIDataCategories@RootObject@@QEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; RootObject::getGUIDataCategories(class lektor<StringPair> &);
?getGUIDataCategories@RootObject@@UEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+22*8]
?getGUIDataCategories@RootObject@@UEAAXAEAV?$lektor@VStringPair@@@@@Z endp

?_NV_setStandingOrder@RootObject@@QEAAXW4StandingOrder@MessageForB@@@Z proc EXPORT
?_NV_setStandingOrder@RootObject@@QEAAXW4StandingOrder@MessageForB@@@Z endp

; RootObject::setStandingOrder(enum MessageForB::StandingOrder);
?setStandingOrder@RootObject@@UEAAXW4StandingOrder@MessageForB@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+23*8]
?setStandingOrder@RootObject@@UEAAXW4StandingOrder@MessageForB@@@Z endp

?_NV_getOrders@RootObject@@QEAAXAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@@Z proc EXPORT
?_NV_getOrders@RootObject@@QEAAXAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@@Z endp

; RootObject::getOrders(class lektor<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > &);
?getOrders@RootObject@@UEAAXAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+24*8]
?getOrders@RootObject@@UEAAXAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@@Z endp

?_NV_getInventory@RootObject@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@RootObject@@QEBAPEAVInventory@@XZ endp

; RootObject::getInventory();
?getInventory@RootObject@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+25*8]
?getInventory@RootObject@@UEBAPEAVInventory@@XZ endp

?_NV_giveItem@RootObject@@QEAA_NPEAVItem@@_N1@Z proc EXPORT
?_NV_giveItem@RootObject@@QEAA_NPEAVItem@@_N1@Z endp

; RootObject::giveItem(class Item *, bool, bool);
?giveItem@RootObject@@UEAA_NPEAVItem@@_N1@Z proc EXPORT
jmp function_pointers[_RootObject_base+26*8]
?giveItem@RootObject@@UEAA_NPEAVItem@@_N1@Z endp

?_NV_hasRoomForItem@RootObject@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_hasRoomForItem@RootObject@@QEAA_NPEAVGameData@@@Z endp

; RootObject::hasRoomForItem(class GameData *);
?hasRoomForItem@RootObject@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+27*8]
?hasRoomForItem@RootObject@@UEAA_NPEAVGameData@@@Z endp

?_NV_hasItem@RootObject@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_hasItem@RootObject@@QEAA_NPEAVGameData@@@Z endp

; RootObject::hasItem(class GameData *);
?hasItem@RootObject@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+28*8]
?hasItem@RootObject@@UEAA_NPEAVGameData@@@Z endp

?_NV_createInventoryLayout@RootObject@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@RootObject@@QEAAPEAVInventoryLayout@@XZ endp

; RootObject::createInventoryLayout();
?createInventoryLayout@RootObject@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+29*8]
?createInventoryLayout@RootObject@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_ImStealingDoYouNotice@RootObject@@QEAA_NPEAV1@@Z proc EXPORT
?_NV_ImStealingDoYouNotice@RootObject@@QEAA_NPEAV1@@Z endp

; RootObject::ImStealingDoYouNotice(class RootObject *);
?ImStealingDoYouNotice@RootObject@@UEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_RootObject_base+30*8]
?ImStealingDoYouNotice@RootObject@@UEAA_NPEAV1@@Z endp

?_NV_stolenGoodsDetectionCheck@RootObject@@QEAA_NPEAVItem@@PEAV1@@Z proc EXPORT
?_NV_stolenGoodsDetectionCheck@RootObject@@QEAA_NPEAVItem@@PEAV1@@Z endp

; RootObject::stolenGoodsDetectionCheck(class Item *, class RootObject *);
?stolenGoodsDetectionCheck@RootObject@@UEAA_NPEAVItem@@PEAV1@@Z proc EXPORT
jmp function_pointers[_RootObject_base+31*8]
?stolenGoodsDetectionCheck@RootObject@@UEAA_NPEAVItem@@PEAV1@@Z endp

?_NV_equipItem@RootObject@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_equipItem@RootObject@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; RootObject::equipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?equipItem@RootObject@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+32*8]
?equipItem@RootObject@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_unequipItem@RootObject@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_unequipItem@RootObject@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; RootObject::unequipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?unequipItem@RootObject@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+33*8]
?unequipItem@RootObject@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_dropItem@RootObject@@QEAAXPEAV1@@Z proc EXPORT
?_NV_dropItem@RootObject@@QEAAXPEAV1@@Z endp

; RootObject::dropItem(class RootObject *);
?dropItem@RootObject@@UEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_RootObject_base+34*8]
?dropItem@RootObject@@UEAAXPEAV1@@Z endp

?_NV_takeMoney@RootObject@@QEAA_NH@Z proc EXPORT
?_NV_takeMoney@RootObject@@QEAA_NH@Z endp

; RootObject::takeMoney(int);
?takeMoney@RootObject@@UEAA_NH@Z proc EXPORT
jmp function_pointers[_RootObject_base+35*8]
?takeMoney@RootObject@@UEAA_NH@Z endp

?_NV_getMoney@RootObject@@QEBAHXZ proc EXPORT
?_NV_getMoney@RootObject@@QEBAHXZ endp

; RootObject::getMoney();
?getMoney@RootObject@@UEBAHXZ proc EXPORT
jmp function_pointers[_RootObject_base+36*8]
?getMoney@RootObject@@UEBAHXZ endp

?_NV_say@RootObject@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_say@RootObject@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RootObject::say(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?say@RootObject@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+37*8]
?say@RootObject@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_notifyIndoors@RootObject@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_notifyIndoors@RootObject@@QEAAXAEBVhand@@@Z endp

; RootObject::notifyIndoors(const class hand &);
?notifyIndoors@RootObject@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+38*8]
?notifyIndoors@RootObject@@UEAAXAEBVhand@@@Z endp

?_NV_notifyOutdoors@RootObject@@QEAAXXZ proc EXPORT
?_NV_notifyOutdoors@RootObject@@QEAAXXZ endp

; RootObject::notifyOutdoors();
?notifyOutdoors@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+39*8]
?notifyOutdoors@RootObject@@UEAAXXZ endp

?_NV_isIndoors@RootObject@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_isIndoors@RootObject@@QEBAAEBVhand@@XZ endp

; RootObject::isIndoors();
?isIndoors@RootObject@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+40*8]
?isIndoors@RootObject@@UEBAAEBVhand@@XZ endp

?_NV_isOnARoof@RootObject@@QEAA_NXZ proc EXPORT
?_NV_isOnARoof@RootObject@@QEAA_NXZ endp

; RootObject::isOnARoof();
?isOnARoof@RootObject@@UEAA_NXZ proc EXPORT
jmp function_pointers[_RootObject_base+41*8]
?isOnARoof@RootObject@@UEAA_NXZ endp

?_NV_getIntendedAggression@RootObject@@QEAAMXZ proc EXPORT
?_NV_getIntendedAggression@RootObject@@QEAAMXZ endp

; RootObject::getIntendedAggression();
?getIntendedAggression@RootObject@@UEAAMXZ proc EXPORT
jmp function_pointers[_RootObject_base+42*8]
?getIntendedAggression@RootObject@@UEAAMXZ endp

?_NV_hitByMeleeAttack@RootObject@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
?_NV_hitByMeleeAttack@RootObject@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

; RootObject::hitByMeleeAttack(enum CutDirection, class Damages &, class Character *, class CombatTechniqueData *, int);
?hitByMeleeAttack@RootObject@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
jmp function_pointers[_RootObject_base+43*8]
?hitByMeleeAttack@RootObject@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

?_NV_getPlatoonAI@RootObject@@QEAAPEAVPlatoonAI@@XZ proc EXPORT
?_NV_getPlatoonAI@RootObject@@QEAAPEAVPlatoonAI@@XZ endp

; RootObject::getPlatoonAI();
?getPlatoonAI@RootObject@@UEAAPEAVPlatoonAI@@XZ proc EXPORT
jmp function_pointers[_RootObject_base+44*8]
?getPlatoonAI@RootObject@@UEAAPEAVPlatoonAI@@XZ endp

?_NV_setIsInsideBuilding@RootObject@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setIsInsideBuilding@RootObject@@QEAAXAEBVhand@@@Z endp

; RootObject::setIsInsideBuilding(const class hand &);
?setIsInsideBuilding@RootObject@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_RootObject_base+45*8]
?setIsInsideBuilding@RootObject@@UEAAXAEBVhand@@@Z endp

?_NV_notifyEffect@RootObject@@QEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z proc EXPORT
?_NV_notifyEffect@RootObject@@QEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z endp

; RootObject::notifyEffect(enum EffectType::Enum, enum WeatherAffecting, float);
?notifyEffect@RootObject@@UEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z proc EXPORT
jmp function_pointers[_RootObject_base+46*8]
?notifyEffect@RootObject@@UEAAXW4Enum@EffectType@@W4WeatherAffecting@@M@Z endp

?_NV_loadUnloadCheck@RootObject@@QEAAXXZ proc EXPORT
?_NV_loadUnloadCheck@RootObject@@QEAAXXZ endp

; RootObject::loadUnloadCheck();
?loadUnloadCheck@RootObject@@UEAAXXZ proc EXPORT
jmp function_pointers[_RootObject_base+47*8]
?loadUnloadCheck@RootObject@@UEAAXXZ endp
