
; RootObjectFactory::create(class GameData *, class Ogre::Vector3, bool, class Faction *, class Ogre::Quaternion, class FactoryCallbackInterface *, class RootObjectContainer *, class GameSaveState *, bool, class Building *, float);
?create@RootObjectFactory@@QEAAPEAVRootObjectBase@@PEAVGameData@@VVector3@Ogre@@_NPEAVFaction@@VQuaternion@5@PEAVFactoryCallbackInterface@@PEAVRootObjectContainer@@PEAVGameSaveState@@2PEAVBuilding@@M@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+0*8]
?create@RootObjectFactory@@QEAAPEAVRootObjectBase@@PEAVGameData@@VVector3@Ogre@@_NPEAVFaction@@VQuaternion@5@PEAVFactoryCallbackInterface@@PEAVRootObjectContainer@@PEAVGameSaveState@@2PEAVBuilding@@M@Z endp

; RootObjectFactory::createBuilding(class GameData *, class Ogre::Vector3, class TownBase *, class Faction *, class Ogre::Quaternion, class FactoryCallbackInterface *, class Layout *, class Building *, class GameSaveState *, class Building *, bool, bool, bool, int, bool);
?createBuilding@RootObjectFactory@@QEAAPEAVBuilding@@PEAVGameData@@VVector3@Ogre@@PEAVTownBase@@PEAVFaction@@VQuaternion@5@PEAVFactoryCallbackInterface@@PEAVLayout@@PEAV2@PEAVGameSaveState@@7_N99H9@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+1*8]
?createBuilding@RootObjectFactory@@QEAAPEAVBuilding@@PEAVGameData@@VVector3@Ogre@@PEAVTownBase@@PEAVFaction@@VQuaternion@5@PEAVFactoryCallbackInterface@@PEAVLayout@@PEAV2@PEAVGameSaveState@@7_N99H9@Z endp

; RootObjectFactory::createLocationNode(bool, class GameData *, class Ogre::Vector3, class Building *, class Faction *, class Ogre::Quaternion, class GameSaveState *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createLocationNode@RootObjectFactory@@QEAAPEAVLocationNode@@_NPEAVGameData@@VVector3@Ogre@@PEAVBuilding@@PEAVFaction@@VQuaternion@5@PEAVGameSaveState@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+2*8]
?createLocationNode@RootObjectFactory@@QEAAPEAVLocationNode@@_NPEAVGameData@@VVector3@Ogre@@PEAVBuilding@@PEAVFaction@@VQuaternion@5@PEAVGameSaveState@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RootObjectFactory::createItem(class GameData *, const class hand &, class GameData *, class GameData *, int, class Faction *);
?createItem@RootObjectFactory@@QEAAPEAVItem@@PEAVGameData@@AEBVhand@@00HPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+3*8]
?createItem@RootObjectFactory@@QEAAPEAVItem@@PEAVGameData@@AEBVhand@@00HPEAVFaction@@@Z endp

; RootObjectFactory::createItem(class GameData *);
?createItem@RootObjectFactory@@QEAAPEAVItem@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+4*8]
?createItem@RootObjectFactory@@QEAAPEAVItem@@PEAVGameData@@@Z endp

; RootObjectFactory::copyItem(class Item *);
?copyItem@RootObjectFactory@@QEAAPEAVItem@@PEAV2@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+5*8]
?copyItem@RootObjectFactory@@QEAAPEAVItem@@PEAV2@@Z endp

; RootObjectFactory::chooseDataFromList(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum itemType, int);
?chooseDataFromList@RootObjectFactory@@QEAAPEAVGameData@@PEAV2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@H@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+6*8]
?chooseDataFromList@RootObjectFactory@@QEAAPEAVGameData@@PEAV2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@H@Z endp

; RootObjectFactory::chooseDataFromListWithVals(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum itemType, int);
?chooseDataFromListWithVals@RootObjectFactory@@QEAAPEBVGameDataReference@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@H@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+7*8]
?chooseDataFromListWithVals@RootObjectFactory@@QEAAPEBVGameDataReference@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4itemType@@H@Z endp

; RootObjectFactory::getValsFromDataInList(class GameData *, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getValsFromDataInList@RootObjectFactory@@QEAA?AVTripleInt@@PEAVGameData@@0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+8*8]
?getValsFromDataInList@RootObjectFactory@@QEAA?AVTripleInt@@PEAVGameData@@0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RootObjectFactory::createCharacterForBuilding(class Building *);
?createCharacterForBuilding@RootObjectFactory@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+9*8]
?createCharacterForBuilding@RootObjectFactory@@QEAAXPEAVBuilding@@@Z endp

; RootObjectFactory::createRandomCharacter(class Faction *, class Ogre::Vector3, class RootObjectContainer *, class GameData *, class Building *, float);
?createRandomCharacter@RootObjectFactory@@QEAAPEAVRootObject@@PEAVFaction@@VVector3@Ogre@@PEAVRootObjectContainer@@PEAVGameData@@PEAVBuilding@@M@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+10*8]
?createRandomCharacter@RootObjectFactory@@QEAAPEAVRootObject@@PEAVFaction@@VVector3@Ogre@@PEAVRootObjectContainer@@PEAVGameData@@PEAVBuilding@@M@Z endp

; RootObjectFactory::createRandomUnloadedCharacter(class Faction *, class UnloadedPlatoon *, class Ogre::Vector3, class GameData *, class Ownerships *);
?createRandomUnloadedCharacter@RootObjectFactory@@QEAA?AVGameSaveState@@PEAVFaction@@PEAVUnloadedPlatoon@@VVector3@Ogre@@PEAVGameData@@PEAVOwnerships@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+11*8]
?createRandomUnloadedCharacter@RootObjectFactory@@QEAA?AVGameSaveState@@PEAVFaction@@PEAVUnloadedPlatoon@@VVector3@Ogre@@PEAVGameData@@PEAVOwnerships@@@Z endp

; RootObjectFactory::createRandomSquad(class Faction *, class Ogre::Vector3, class TownBase *, int, class Building *, class GameData *, class RootObjectContainer *, class AreaBiomeGroup *, class Platoon *, bool, const class hand &, class TownBase *, float, enum SquadType, bool);
?createRandomSquad@RootObjectFactory@@QEAAPEAVPlatoon@@PEAVFaction@@VVector3@Ogre@@PEAVTownBase@@HPEAVBuilding@@PEAVGameData@@PEAVRootObjectContainer@@PEAVAreaBiomeGroup@@PEAV2@_NAEBVhand@@2MW4SquadType@@8@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+12*8]
?createRandomSquad@RootObjectFactory@@QEAAPEAVPlatoon@@PEAVFaction@@VVector3@Ogre@@PEAVTownBase@@HPEAVBuilding@@PEAVGameData@@PEAVRootObjectContainer@@PEAVAreaBiomeGroup@@PEAV2@_NAEBVhand@@2MW4SquadType@@8@Z endp

; RootObjectFactory::createRandomUnloadedSquad(class Faction *, class Ogre::Vector3, class TownBase *, int, class Building *, class GameData *, class RootObjectContainer *, class AreaBiomeGroup *, bool, const class hand &, class TownBase *, enum SquadType);
?createRandomUnloadedSquad@RootObjectFactory@@QEAAPEAVPlatoon@@PEAVFaction@@VVector3@Ogre@@PEAVTownBase@@HPEAVBuilding@@PEAVGameData@@PEAVRootObjectContainer@@PEAVAreaBiomeGroup@@_NAEBVhand@@2W4SquadType@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+13*8]
?createRandomUnloadedSquad@RootObjectFactory@@QEAAPEAVPlatoon@@PEAVFaction@@VVector3@Ogre@@PEAVTownBase@@HPEAVBuilding@@PEAVGameData@@PEAVRootObjectContainer@@PEAVAreaBiomeGroup@@_NAEBVhand@@2W4SquadType@@@Z endp

; RootObjectFactory::mainThreadUpdate();
?mainThreadUpdate@RootObjectFactory@@QEAAXXZ proc EXPORT
jmp function_pointers[_RootObjectFactory_base+14*8]
?mainThreadUpdate@RootObjectFactory@@QEAAXXZ endp

; RootObjectFactory::populateBuilding(class Building *);
?populateBuilding@RootObjectFactory@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+15*8]
?populateBuilding@RootObjectFactory@@QEAAXPEAVBuilding@@@Z endp

; RootObjectFactory::chooseMyClothing(class lektor<GameData *> &, class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class RaceData *, bool);
?chooseMyClothing@RootObjectFactory@@SAXAEAV?$lektor@PEAVGameData@@@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVRaceData@@_N@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+16*8]
?chooseMyClothing@RootObjectFactory@@SAXAEAV?$lektor@PEAVGameData@@@@PEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVRaceData@@_N@Z endp

; RootObjectFactory::_chooseClothingItemFromList(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum AttachSlot, class RaceData *);
?_chooseClothingItemFromList@RootObjectFactory@@SAPEAVGameData@@PEAV2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4AttachSlot@@PEAVRaceData@@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+17*8]
?_chooseClothingItemFromList@RootObjectFactory@@SAPEAVGameData@@PEAV2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4AttachSlot@@PEAVRaceData@@@Z endp

; RootObjectFactory::process(class RootObjectFactory::CreatelistItem *);
?process@RootObjectFactory@@QEAAPEAVRootObjectBase@@PEAVCreatelistItem@1@@Z proc EXPORT
jmp function_pointers[_RootObjectFactory_base+18*8]
?process@RootObjectFactory@@QEAAPEAVRootObjectBase@@PEAVCreatelistItem@1@@Z endp

?_CONSTRUCTOR@RootObjectFactory@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@RootObjectFactory@@QEAAPEAV1@XZ endp

; RootObjectFactory::RootObjectFactory();
??0RootObjectFactory@@QEAA@XZ proc EXPORT
jmp function_pointers[_RootObjectFactory_base+19*8]
??0RootObjectFactory@@QEAA@XZ endp

?_DESTRUCTOR@RootObjectFactory@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RootObjectFactory@@QEAAXXZ endp

; RootObjectFactory::~RootObjectFactory();
??1RootObjectFactory@@QEAA@XZ proc EXPORT
jmp function_pointers[_RootObjectFactory_base+20*8]
??1RootObjectFactory@@QEAA@XZ endp
