
?_CONSTRUCTOR@RootObjectContainer@@QEAAPEAV1@PEAVDataObjectContainer@@@Z proc EXPORT
?_CONSTRUCTOR@RootObjectContainer@@QEAAPEAV1@PEAVDataObjectContainer@@@Z endp

; RootObjectContainer::RootObjectContainer(class DataObjectContainer *);
??0RootObjectContainer@@QEAA@PEAVDataObjectContainer@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+0*8]
??0RootObjectContainer@@QEAA@PEAVDataObjectContainer@@@Z endp

?_CONSTRUCTOR@RootObjectContainer@@QEAAPEAV1@W4GroupType@DataObjectContainer@@@Z proc EXPORT
?_CONSTRUCTOR@RootObjectContainer@@QEAAPEAV1@W4GroupType@DataObjectContainer@@@Z endp

; RootObjectContainer::RootObjectContainer(enum DataObjectContainer::GroupType);
??0RootObjectContainer@@QEAA@W4GroupType@DataObjectContainer@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+1*8]
??0RootObjectContainer@@QEAA@W4GroupType@DataObjectContainer@@@Z endp

?_DESTRUCTOR@RootObjectContainer@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RootObjectContainer@@QEAAXXZ endp

; RootObjectContainer::~RootObjectContainer();
??1RootObjectContainer@@UEAA@XZ proc EXPORT
jmp function_pointers[_RootObjectContainer_base+2*8]
??1RootObjectContainer@@UEAA@XZ endp

?_NV_addActiveObject@RootObjectContainer@@QEAA_NPEAVRootObject@@@Z proc EXPORT
?_NV_addActiveObject@RootObjectContainer@@QEAA_NPEAVRootObject@@@Z endp

; RootObjectContainer::addActiveObject(class RootObject *);
?addActiveObject@RootObjectContainer@@UEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+3*8]
?addActiveObject@RootObjectContainer@@UEAA_NPEAVRootObject@@@Z endp

?_NV_removeObject@RootObjectContainer@@QEAA_NPEAVRootObject@@@Z proc EXPORT
?_NV_removeObject@RootObjectContainer@@QEAA_NPEAVRootObject@@@Z endp

; RootObjectContainer::removeObject(class RootObject *);
?removeObject@RootObjectContainer@@UEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+4*8]
?removeObject@RootObjectContainer@@UEAA_NPEAVRootObject@@@Z endp

?_NV_update@RootObjectContainer@@QEAA_NXZ proc EXPORT
?_NV_update@RootObjectContainer@@QEAA_NXZ endp

; RootObjectContainer::update();
?update@RootObjectContainer@@UEAA_NXZ proc EXPORT
jmp function_pointers[_RootObjectContainer_base+5*8]
?update@RootObjectContainer@@UEAA_NXZ endp

; RootObjectContainer::getThing(int);
?getThing@RootObjectContainer@@QEAAPEAVRootObject@@H@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+6*8]
?getThing@RootObjectContainer@@QEAAPEAVRootObject@@H@Z endp

; RootObjectContainer::getNumThings();
?getNumThings@RootObjectContainer@@QEBAHXZ proc EXPORT
jmp function_pointers[_RootObjectContainer_base+7*8]
?getNumThings@RootObjectContainer@@QEBAHXZ endp

; RootObjectContainer::getThings();
?getThings@RootObjectContainer@@QEAAPEAV?$lektor@PEAVRootObject@@@@XZ proc EXPORT
jmp function_pointers[_RootObjectContainer_base+8*8]
?getThings@RootObjectContainer@@QEAAPEAV?$lektor@PEAVRootObject@@@@XZ endp

?_NV_getSelectedObjects@RootObjectContainer@@QEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z proc EXPORT
?_NV_getSelectedObjects@RootObjectContainer@@QEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z endp

; RootObjectContainer::getSelectedObjects(class lektor<RootObject *> &, enum itemType, bool);
?getSelectedObjects@RootObjectContainer@@UEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+9*8]
?getSelectedObjects@RootObjectContainer@@UEAAXAEAV?$lektor@PEAVRootObject@@@@W4itemType@@_N@Z endp

; RootObjectContainer::serialiseThings(const class lektor<RootObject *> &, class GameData *, class GameDataContainer *, class PosRotPair *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?serialiseThings@RootObjectContainer@@QEAAXAEBV?$lektor@PEAVRootObject@@@@PEAVGameData@@PEAVGameDataContainer@@PEAVPosRotPair@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+10*8]
?serialiseThings@RootObjectContainer@@QEAAXAEBV?$lektor@PEAVRootObject@@@@PEAVGameData@@PEAVGameDataContainer@@PEAVPosRotPair@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RootObjectContainer::serialiseThings(class GameData *, class GameDataContainer *, class PosRotPair *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?serialiseThings@RootObjectContainer@@QEAAXPEAVGameData@@PEAVGameDataContainer@@PEAVPosRotPair@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+11*8]
?serialiseThings@RootObjectContainer@@QEAAXPEAVGameData@@PEAVGameDataContainer@@PEAVPosRotPair@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_loadToReality@RootObjectContainer@@QEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFactoryCallbackInterface@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameDataContainer@@PEAVSpecificItemLoadFirst@1@@Z proc EXPORT
?_NV_loadToReality@RootObjectContainer@@QEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFactoryCallbackInterface@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameDataContainer@@PEAVSpecificItemLoadFirst@1@@Z endp

; RootObjectContainer::loadToReality(bool, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class FactoryCallbackInterface *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class GameDataContainer *, class RootObjectContainer::SpecificItemLoadFirst *);
?loadToReality@RootObjectContainer@@UEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFactoryCallbackInterface@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameDataContainer@@PEAVSpecificItemLoadFirst@1@@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+12*8]
?loadToReality@RootObjectContainer@@UEAAX_NAEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFactoryCallbackInterface@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVGameDataContainer@@PEAVSpecificItemLoadFirst@1@@Z endp

?_NV_loadInstance@RootObjectContainer@@QEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z proc EXPORT
?_NV_loadInstance@RootObjectContainer@@QEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z endp

; RootObjectContainer::loadInstance(class GameSaveState &, bool, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class FactoryCallbackInterface *, const class Ogre::Vector3 &);
?loadInstance@RootObjectContainer@@UEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z proc EXPORT
jmp function_pointers[_RootObjectContainer_base+13*8]
?loadInstance@RootObjectContainer@@UEAAXAEAVGameSaveState@@_NAEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFactoryCallbackInterface@@2@Z endp
