
?_CONSTRUCTOR@RootObjectBase@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@Vhand@@@Z proc EXPORT
?_CONSTRUCTOR@RootObjectBase@@QEAAPEAV1@PEAVGameData@@PEAVFaction@@Vhand@@@Z endp

; RootObjectBase::RootObjectBase(class GameData *, class Faction *, class hand);
??0RootObjectBase@@QEAA@PEAVGameData@@PEAVFaction@@Vhand@@@Z proc EXPORT
jmp function_pointers[_RootObjectBase_base+0*8]
??0RootObjectBase@@QEAA@PEAVGameData@@PEAVFaction@@Vhand@@@Z endp

?_DESTRUCTOR@RootObjectBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@RootObjectBase@@QEAAXXZ endp

; RootObjectBase::~RootObjectBase();
??1RootObjectBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+1*8]
??1RootObjectBase@@UEAA@XZ endp

; RootObjectBase::isValid();
?isValid@RootObjectBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+2*8]
?isValid@RootObjectBase@@QEBA_NXZ endp

?_NV_getName@RootObjectBase@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getName@RootObjectBase@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; RootObjectBase::getName();
?getName@RootObjectBase@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+3*8]
?getName@RootObjectBase@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_setName@RootObjectBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setName@RootObjectBase@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; RootObjectBase::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@RootObjectBase@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_RootObjectBase_base+4*8]
?setName@RootObjectBase@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_getGameData@RootObjectBase@@QEBAPEAVGameData@@XZ proc EXPORT
?_NV_getGameData@RootObjectBase@@QEBAPEAVGameData@@XZ endp

; RootObjectBase::getGameData();
?getGameData@RootObjectBase@@UEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+5*8]
?getGameData@RootObjectBase@@UEBAPEAVGameData@@XZ endp

?_NV_getDataType@RootObjectBase@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@RootObjectBase@@QEBA?AW4itemType@@XZ endp

; RootObjectBase::getDataType();
?getDataType@RootObjectBase@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+6*8]
?getDataType@RootObjectBase@@UEBA?AW4itemType@@XZ endp

?_NV_typeIsAnItem@RootObjectBase@@QEBA_NXZ proc EXPORT
?_NV_typeIsAnItem@RootObjectBase@@QEBA_NXZ endp

; RootObjectBase::typeIsAnItem();
?typeIsAnItem@RootObjectBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+7*8]
?typeIsAnItem@RootObjectBase@@UEBA_NXZ endp

?_NV_isUnconcious@RootObjectBase@@QEBA_NXZ proc EXPORT
?_NV_isUnconcious@RootObjectBase@@QEBA_NXZ endp

; RootObjectBase::isUnconcious();
?isUnconcious@RootObjectBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+8*8]
?isUnconcious@RootObjectBase@@UEBA_NXZ endp

?_NV_getPositionForWaypoint@RootObjectBase@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getPositionForWaypoint@RootObjectBase@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; RootObjectBase::getPositionForWaypoint(const class Ogre::Vector3 &);
?getPositionForWaypoint@RootObjectBase@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_RootObjectBase_base+9*8]
?getPositionForWaypoint@RootObjectBase@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_getPosition@RootObjectBase@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@RootObjectBase@@QEAA?AVVector3@Ogre@@XZ endp

; RootObjectBase::getPosition();
?getPosition@RootObjectBase@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+10*8]
?getPosition@RootObjectBase@@UEAA?AVVector3@Ogre@@XZ endp

?_NV_getMovementSpeed@RootObjectBase@@QEBAMXZ proc EXPORT
?_NV_getMovementSpeed@RootObjectBase@@QEBAMXZ endp

; RootObjectBase::getMovementSpeed();
?getMovementSpeed@RootObjectBase@@UEBAMXZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+11*8]
?getMovementSpeed@RootObjectBase@@UEBAMXZ endp

?_NV_getMovementDirection@RootObjectBase@@QEBA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getMovementDirection@RootObjectBase@@QEBA?AVVector3@Ogre@@XZ endp

; RootObjectBase::getMovementDirection();
?getMovementDirection@RootObjectBase@@UEBA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+12*8]
?getMovementDirection@RootObjectBase@@UEBA?AVVector3@Ogre@@XZ endp

?_NV_getFaction@RootObjectBase@@QEBAPEAVFaction@@XZ proc EXPORT
?_NV_getFaction@RootObjectBase@@QEBAPEAVFaction@@XZ endp

; RootObjectBase::getFaction();
?getFaction@RootObjectBase@@UEBAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+13*8]
?getFaction@RootObjectBase@@UEBAPEAVFaction@@XZ endp

; RootObjectBase::hasFaction();
?hasFaction@RootObjectBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+14*8]
?hasFaction@RootObjectBase@@QEBA_NXZ endp

?_NV_getFloor@RootObjectBase@@QEBAHXZ proc EXPORT
?_NV_getFloor@RootObjectBase@@QEBAHXZ endp

; RootObjectBase::getFloor();
?getFloor@RootObjectBase@@UEBAHXZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+15*8]
?getFloor@RootObjectBase@@UEBAHXZ endp

?_NV_getSensoryData@RootObjectBase@@QEAAPEAVSensoryData@@XZ proc EXPORT
?_NV_getSensoryData@RootObjectBase@@QEAAPEAVSensoryData@@XZ endp

; RootObjectBase::getSensoryData();
?getSensoryData@RootObjectBase@@UEAAPEAVSensoryData@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+16*8]
?getSensoryData@RootObjectBase@@UEAAPEAVSensoryData@@XZ endp

?_NV_getStateBroadcast@RootObjectBase@@QEAAPEAVStateBroadcastData@@XZ proc EXPORT
?_NV_getStateBroadcast@RootObjectBase@@QEAAPEAVStateBroadcastData@@XZ endp

; RootObjectBase::getStateBroadcast();
?getStateBroadcast@RootObjectBase@@UEAAPEAVStateBroadcastData@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+17*8]
?getStateBroadcast@RootObjectBase@@UEAAPEAVStateBroadcastData@@XZ endp

?_NV_getCurrentTownLocation@RootObjectBase@@QEAAPEAVTownBase@@XZ proc EXPORT
?_NV_getCurrentTownLocation@RootObjectBase@@QEAAPEAVTownBase@@XZ endp

; RootObjectBase::getCurrentTownLocation();
?getCurrentTownLocation@RootObjectBase@@UEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+18*8]
?getCurrentTownLocation@RootObjectBase@@UEAAPEAVTownBase@@XZ endp

; RootObjectBase::getHandle();
?getHandle@RootObjectBase@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+19*8]
?getHandle@RootObjectBase@@QEBAAEBVhand@@XZ endp

?_NV_setHandle@RootObjectBase@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@RootObjectBase@@QEAAXAEBVhand@@@Z endp

; RootObjectBase::setHandle(const class hand &);
?setHandle@RootObjectBase@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_RootObjectBase_base+20*8]
?setHandle@RootObjectBase@@UEAAXAEBVhand@@@Z endp

?_NV_getOwnerships@RootObjectBase@@QEAAPEAVOwnerships@@XZ proc EXPORT
?_NV_getOwnerships@RootObjectBase@@QEAAPEAVOwnerships@@XZ endp

; RootObjectBase::getOwnerships();
?getOwnerships@RootObjectBase@@UEAAPEAVOwnerships@@XZ proc EXPORT
jmp function_pointers[_RootObjectBase_base+21*8]
?getOwnerships@RootObjectBase@@UEAAPEAVOwnerships@@XZ endp

?_NV_setFaction@RootObjectBase@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
?_NV_setFaction@RootObjectBase@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

; RootObjectBase::setFaction(class Faction *, class ActivePlatoon *);
?setFaction@RootObjectBase@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_RootObjectBase_base+22*8]
?setFaction@RootObjectBase@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp
