
; SaveManager::getSingleton();
?getSingleton@SaveManager@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_SaveManager_base+0*8]
?getSingleton@SaveManager@@SAPEAV1@XZ endp

; SaveManager::isVisible();
?isVisible@SaveManager@@QEAAHXZ proc EXPORT
jmp function_pointers[_SaveManager_base+1*8]
?isVisible@SaveManager@@QEAAHXZ endp

; SaveManager::showSave();
?showSave@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+2*8]
?showSave@SaveManager@@QEAAXXZ endp

; SaveManager::showLoad();
?showLoad@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+3*8]
?showLoad@SaveManager@@QEAAXXZ endp

; SaveManager::showImport();
?showImport@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+4*8]
?showImport@SaveManager@@QEAAXXZ endp

; SaveManager::hide();
?hide@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+5*8]
?hide@SaveManager@@QEAAXXZ endp

; SaveManager::newGame(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?newGame@SaveManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveManager_base+6*8]
?newGame@SaveManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveManager::save(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?save@SaveManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_SaveManager_base+7*8]
?save@SaveManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; SaveManager::load(const struct SaveInfo &, bool);
?load@SaveManager@@QEAAXAEBUSaveInfo@@_N@Z proc EXPORT
jmp function_pointers[_SaveManager_base+8*8]
?load@SaveManager@@QEAAXAEBUSaveInfo@@_N@Z endp

; SaveManager::load(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?load@SaveManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveManager_base+9*8]
?load@SaveManager@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveManager::import(const struct SaveInfo &, int);
?import@SaveManager@@QEAAXAEBUSaveInfo@@H@Z proc EXPORT
jmp function_pointers[_SaveManager_base+10*8]
?import@SaveManager@@QEAAXAEBUSaveInfo@@H@Z endp

; SaveManager::savesExist();
?savesExist@SaveManager@@QEAA_NXZ proc EXPORT
jmp function_pointers[_SaveManager_base+11*8]
?savesExist@SaveManager@@QEAA_NXZ endp

; SaveManager::saveExists(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveExists@SaveManager@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_SaveManager_base+12*8]
?saveExists@SaveManager@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; SaveManager::scanGames(class lektor<SaveInfo> &, bool);
?scanGames@SaveManager@@QEAAHAEAV?$lektor@USaveInfo@@@@_N@Z proc EXPORT
jmp function_pointers[_SaveManager_base+13*8]
?scanGames@SaveManager@@QEAAHAEAV?$lektor@USaveInfo@@@@_N@Z endp

; SaveManager::scanGames(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class lektor<SaveInfo> &, bool);
?scanGames@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$lektor@USaveInfo@@@@_N@Z proc EXPORT
jmp function_pointers[_SaveManager_base+14*8]
?scanGames@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$lektor@USaveInfo@@@@_N@Z endp

; SaveManager::loadInfo(struct SaveInfo &);
?loadInfo@SaveManager@@QEAA_NAEAUSaveInfo@@@Z proc EXPORT
jmp function_pointers[_SaveManager_base+15*8]
?loadInfo@SaveManager@@QEAA_NAEAUSaveInfo@@@Z endp

; SaveManager::checkVersion(const struct SaveInfo &);
?checkVersion@SaveManager@@QEAA_NAEBUSaveInfo@@@Z proc EXPORT
jmp function_pointers[_SaveManager_base+16*8]
?checkVersion@SaveManager@@QEAA_NAEBUSaveInfo@@@Z endp

; SaveManager::execute();
?execute@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+17*8]
?execute@SaveManager@@QEAAXXZ endp

; SaveManager::getCurrentGame();
?getCurrentGame@SaveManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_SaveManager_base+18*8]
?getCurrentGame@SaveManager@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; SaveManager::versionCode(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?versionCode@SaveManager@@QEAAIAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveManager_base+19*8]
?versionCode@SaveManager@@QEAAIAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveManager::updateAutoSave();
?updateAutoSave@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+20*8]
?updateAutoSave@SaveManager@@QEAAXXZ endp

; SaveManager::getSavePath();
?getSavePath@SaveManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_SaveManager_base+21*8]
?getSavePath@SaveManager@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; SaveManager::initialisePaths();
?initialisePaths@SaveManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveManager_base+22*8]
?initialisePaths@SaveManager@@QEAAXXZ endp

?_CONSTRUCTOR@SaveManager@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SaveManager@@QEAAPEAV1@XZ endp

; SaveManager::SaveManager();
??0SaveManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveManager_base+23*8]
??0SaveManager@@QEAA@XZ endp

?_DESTRUCTOR@SaveManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SaveManager@@QEAAXXZ endp

; SaveManager::~SaveManager();
??1SaveManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveManager_base+24*8]
??1SaveManager@@QEAA@XZ endp

; SaveManager::saveGame(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveGame@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_SaveManager_base+25*8]
?saveGame@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; SaveManager::loadGame(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?loadGame@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_SaveManager_base+26*8]
?loadGame@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; SaveManager::importGame(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?importGame@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z proc EXPORT
jmp function_pointers[_SaveManager_base+27*8]
?importGame@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0H@Z endp

; SaveManager::importPlayerBuildings(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?importPlayerBuildings@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_SaveManager_base+28*8]
?importPlayerBuildings@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; SaveManager::importOldPlayerBuildings(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?importOldPlayerBuildings@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_SaveManager_base+29*8]
?importOldPlayerBuildings@SaveManager@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp
