
; SaveFileSystem::getSingleton();
?getSingleton@SaveFileSystem@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+0*8]
?getSingleton@SaveFileSystem@@SAPEAV1@XZ endp

?_CONSTRUCTOR@SaveFileSystem@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SaveFileSystem@@QEAAPEAV1@XZ endp

; SaveFileSystem::SaveFileSystem();
??0SaveFileSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+1*8]
??0SaveFileSystem@@QEAA@XZ endp

?_DESTRUCTOR@SaveFileSystem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SaveFileSystem@@QEAAXXZ endp

; SaveFileSystem::~SaveFileSystem();
??1SaveFileSystem@@UEAA@XZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+2*8]
??1SaveFileSystem@@UEAA@XZ endp

; SaveFileSystem::log(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, enum Logger::Severity);
?log@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Severity@Logger@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+3*8]
?log@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Severity@Logger@@@Z endp

; SaveFileSystem::setTemporaryPath(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setTemporaryPath@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+4*8]
?setTemporaryPath@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveFileSystem::fileExists(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?fileExists@SaveFileSystem@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+5*8]
?fileExists@SaveFileSystem@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveFileSystem::readFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?readFile@SaveFileSystem@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+6*8]
?readFile@SaveFileSystem@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; SaveFileSystem::writeFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?writeFile@SaveFileSystem@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+7*8]
?writeFile@SaveFileSystem@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; SaveFileSystem::deleteFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?deleteFile@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+8*8]
?deleteFile@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveFileSystem::newGame();
?newGame@SaveFileSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+9*8]
?newGame@SaveFileSystem@@QEAAXXZ endp

; SaveFileSystem::loadGame(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?loadGame@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+10*8]
?loadGame@SaveFileSystem@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveFileSystem::saveGame(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?saveGame@SaveFileSystem@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+11*8]
?saveGame@SaveFileSystem@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveFileSystem::sync();
?sync@SaveFileSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+12*8]
?sync@SaveFileSystem@@QEAAXXZ endp

; SaveFileSystem::analyse();
?analyse@SaveFileSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+13*8]
?analyse@SaveFileSystem@@QEAAXXZ endp

; SaveFileSystem::cleanup(bool);
?cleanup@SaveFileSystem@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+14*8]
?cleanup@SaveFileSystem@@QEAAX_N@Z endp

; SaveFileSystem::scanForResidualTempFolders();
?scanForResidualTempFolders@SaveFileSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+15*8]
?scanForResidualTempFolders@SaveFileSystem@@QEAAXXZ endp

; SaveFileSystem::isTempFolder(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isTempFolder@SaveFileSystem@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+16*8]
?isTempFolder@SaveFileSystem@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SaveFileSystem::getActiveSave();
?getActiveSave@SaveFileSystem@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+17*8]
?getActiveSave@SaveFileSystem@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; SaveFileSystem::busy();
?busy@SaveFileSystem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+18*8]
?busy@SaveFileSystem@@QEBA_NXZ endp

; SaveFileSystem::createCurrent();
?createCurrent@SaveFileSystem@@QEAAXXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+19*8]
?createCurrent@SaveFileSystem@@QEAAXXZ endp

?_NV_threadProc@SaveFileSystem@@QEAAKXZ proc EXPORT
?_NV_threadProc@SaveFileSystem@@QEAAKXZ endp

; SaveFileSystem::threadProc();
?threadProc@SaveFileSystem@@UEAAKXZ proc EXPORT
jmp function_pointers[_SaveFileSystem_base+20*8]
?threadProc@SaveFileSystem@@UEAAKXZ endp

; SaveFileSystem::addMessage(enum SaveFileSystem::MessageType, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addMessage@SaveFileSystem@@QEAAXW4MessageType@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_base+21*8]
?addMessage@SaveFileSystem@@QEAAXW4MessageType@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp
