
?_CONSTRUCTOR@SaveInfo@@QEAAPEAV1@AEBU1@@Z proc EXPORT
?_CONSTRUCTOR@SaveInfo@@QEAAPEAV1@AEBU1@@Z endp

; SaveInfo::SaveInfo(const struct SaveInfo &);
??0SaveInfo@@QEAA@AEBU0@@Z proc EXPORT
jmp function_pointers[_SaveInfo_base+0*8]
??0SaveInfo@@QEAA@AEBU0@@Z endp

?_CONSTRUCTOR@SaveInfo@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SaveInfo@@QEAAPEAV1@XZ endp

; SaveInfo::SaveInfo();
??0SaveInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveInfo_base+1*8]
??0SaveInfo@@QEAA@XZ endp

?_DESTRUCTOR@SaveInfo@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SaveInfo@@QEAAXXZ endp

; SaveInfo::~SaveInfo();
??1SaveInfo@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveInfo_base+2*8]
??1SaveInfo@@QEAA@XZ endp

; SaveInfo::operator=(const struct SaveInfo &);
??4SaveInfo@@QEAAAEAU0@AEBU0@@Z proc EXPORT
jmp function_pointers[_SaveInfo_base+3*8]
??4SaveInfo@@QEAAAEAU0@AEBU0@@Z endp
