
?_CONSTRUCTOR@FileMessage@SaveFileSystem@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@FileMessage@SaveFileSystem@@QEAAPEAV12@XZ endp

; SaveFileSystem::FileMessage::FileMessage();
??0FileMessage@SaveFileSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveFileSystem_FileMessage_base+0*8]
??0FileMessage@SaveFileSystem@@QEAA@XZ endp

?_DESTRUCTOR@FileMessage@SaveFileSystem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@FileMessage@SaveFileSystem@@QEAAXXZ endp

; SaveFileSystem::FileMessage::~FileMessage();
??1FileMessage@SaveFileSystem@@QEAA@XZ proc EXPORT
jmp function_pointers[_SaveFileSystem_FileMessage_base+1*8]
??1FileMessage@SaveFileSystem@@QEAA@XZ endp

; SaveFileSystem::FileMessage::operator=(const struct SaveFileSystem::FileMessage &);
??4FileMessage@SaveFileSystem@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_SaveFileSystem_FileMessage_base+2*8]
??4FileMessage@SaveFileSystem@@QEAAAEAU01@AEBU01@@Z endp
