
?_NV_update@ScreenLabelDebug@@QEAAXXZ proc EXPORT
?_NV_update@ScreenLabelDebug@@QEAAXXZ endp

; ScreenLabelDebug::update();
?update@ScreenLabelDebug@@UEAAXXZ proc EXPORT
jmp function_pointers[_ScreenLabelDebug_base+0*8]
?update@ScreenLabelDebug@@UEAAXXZ endp

; ScreenLabelDebug::getCaption();
?getCaption@ScreenLabelDebug@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_ScreenLabelDebug_base+1*8]
?getCaption@ScreenLabelDebug@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_CONSTRUCTOR@ScreenLabelDebug@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
?_CONSTRUCTOR@ScreenLabelDebug@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp

; ScreenLabelDebug::ScreenLabelDebug(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
??0ScreenLabelDebug@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_ScreenLabelDebug_base+2*8]
??0ScreenLabelDebug@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp

?_DESTRUCTOR@ScreenLabelDebug@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ScreenLabelDebug@@QEAAXXZ endp

; ScreenLabelDebug::~ScreenLabelDebug();
??1ScreenLabelDebug@@UEAA@XZ proc EXPORT
jmp function_pointers[_ScreenLabelDebug_base+3*8]
??1ScreenLabelDebug@@UEAA@XZ endp
