
?_CONSTRUCTOR@ScreenLabelInterface@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ScreenLabelInterface@@QEAAPEAV1@XZ endp

; ScreenLabelInterface::ScreenLabelInterface();
??0ScreenLabelInterface@@QEAA@XZ proc EXPORT
jmp function_pointers[_ScreenLabelInterface_base+0*8]
??0ScreenLabelInterface@@QEAA@XZ endp

?_DESTRUCTOR@ScreenLabelInterface@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ScreenLabelInterface@@QEAAXXZ endp

; ScreenLabelInterface::~ScreenLabelInterface();
??1ScreenLabelInterface@@UEAA@XZ proc EXPORT
jmp function_pointers[_ScreenLabelInterface_base+1*8]
??1ScreenLabelInterface@@UEAA@XZ endp

?_NV_setVisible@ScreenLabelInterface@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@ScreenLabelInterface@@QEAAX_N@Z endp

; ScreenLabelInterface::setVisible(bool);
?setVisible@ScreenLabelInterface@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_ScreenLabelInterface_base+2*8]
?setVisible@ScreenLabelInterface@@UEAAX_N@Z endp

?_NV_setPosition@ScreenLabelInterface@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_setPosition@ScreenLabelInterface@@QEAAXAEBVVector3@Ogre@@@Z endp

; ScreenLabelInterface::setPosition(const class Ogre::Vector3 &);
?setPosition@ScreenLabelInterface@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ScreenLabelInterface_base+3*8]
?setPosition@ScreenLabelInterface@@UEAAXAEBVVector3@Ogre@@@Z endp
