
?_NV_setTracking@ScreenLabel@@QEAAXAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_setTracking@ScreenLabel@@QEAAXAEBVhand@@AEBVVector3@Ogre@@@Z endp

; ScreenLabel::setTracking(const class hand &, const class Ogre::Vector3 &);
?setTracking@ScreenLabel@@UEAAXAEBVhand@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ScreenLabel_base+0*8]
?setTracking@ScreenLabel@@UEAAXAEBVhand@@AEBVVector3@Ogre@@@Z endp

?_NV_setCaption@ScreenLabel@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_setCaption@ScreenLabel@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ScreenLabel::setCaption(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCaption@ScreenLabel@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ScreenLabel_base+1*8]
?setCaption@ScreenLabel@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_setRisingSpeed@ScreenLabel@@QEAAXW4RisingSpeed@1@@Z proc EXPORT
?_NV_setRisingSpeed@ScreenLabel@@QEAAXW4RisingSpeed@1@@Z endp

; ScreenLabel::setRisingSpeed(enum ScreenLabel::RisingSpeed);
?setRisingSpeed@ScreenLabel@@UEAAXW4RisingSpeed@1@@Z proc EXPORT
jmp function_pointers[_ScreenLabel_base+2*8]
?setRisingSpeed@ScreenLabel@@UEAAXW4RisingSpeed@1@@Z endp

?_NV_setColor@ScreenLabel@@QEAAXAEBUColour@MyGUI@@@Z proc EXPORT
?_NV_setColor@ScreenLabel@@QEAAXAEBUColour@MyGUI@@@Z endp

; ScreenLabel::setColor(const struct MyGUI::Colour &);
?setColor@ScreenLabel@@UEAAXAEBUColour@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ScreenLabel_base+3*8]
?setColor@ScreenLabel@@UEAAXAEBUColour@MyGUI@@@Z endp

?_NV_setPosition@ScreenLabel@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
?_NV_setPosition@ScreenLabel@@QEAAXAEBVVector3@Ogre@@@Z endp

; ScreenLabel::setPosition(const class Ogre::Vector3 &);
?setPosition@ScreenLabel@@UEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ScreenLabel_base+4*8]
?setPosition@ScreenLabel@@UEAAXAEBVVector3@Ogre@@@Z endp

?_NV_update@ScreenLabel@@QEAAXXZ proc EXPORT
?_NV_update@ScreenLabel@@QEAAXXZ endp

; ScreenLabel::update();
?update@ScreenLabel@@UEAAXXZ proc EXPORT
jmp function_pointers[_ScreenLabel_base+5*8]
?update@ScreenLabel@@UEAAXXZ endp

?_CONSTRUCTOR@ScreenLabel@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUColour@MyGUI@@W4LabelSize@1@W4RisingSpeed@1@@Z proc EXPORT
?_CONSTRUCTOR@ScreenLabel@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUColour@MyGUI@@W4LabelSize@1@W4RisingSpeed@1@@Z endp

; ScreenLabel::ScreenLabel(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const struct MyGUI::Colour &, enum ScreenLabel::LabelSize, enum ScreenLabel::RisingSpeed);
??0ScreenLabel@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUColour@MyGUI@@W4LabelSize@0@W4RisingSpeed@0@@Z proc EXPORT
jmp function_pointers[_ScreenLabel_base+6*8]
??0ScreenLabel@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUColour@MyGUI@@W4LabelSize@0@W4RisingSpeed@0@@Z endp

?_DESTRUCTOR@ScreenLabel@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ScreenLabel@@QEAAXXZ endp

; ScreenLabel::~ScreenLabel();
??1ScreenLabel@@UEAA@XZ proc EXPORT
jmp function_pointers[_ScreenLabel_base+7*8]
??1ScreenLabel@@UEAA@XZ endp

; ScreenLabel::destroy();
?destroy@ScreenLabel@@QEAAXXZ proc EXPORT
jmp function_pointers[_ScreenLabel_base+8*8]
?destroy@ScreenLabel@@QEAAXXZ endp
