
; Scythe::PhysicsClass::insert(class PhysFileParams *, class _ScytheRootObjectInterfaceT *, class NxScene * const, const class Scythe::ScythePhysicsEntityData *, const class Scythe::Vector3 &, const class Scythe::Matrix &);
?insert@PhysicsClass@Scythe@@QEAA_NPEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@QEAVNxScene@@PEBVScythePhysicsEntityData@2@AEBVVector3@2@AEBVMatrix@2@@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+0*8]
?insert@PhysicsClass@Scythe@@QEAA_NPEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@QEAVNxScene@@PEBVScythePhysicsEntityData@2@AEBVVector3@2@AEBVMatrix@2@@Z endp

; Scythe::PhysicsClass::insert(class PhysFileParams *, class _ScytheRootObjectInterfaceT *, class NxScene * const, const class Scythe::ScythePhysicsEntityData *, const class Scythe::Vector3 &, const class Scythe::Quat &);
?insert@PhysicsClass@Scythe@@QEAA_NPEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@QEAVNxScene@@PEBVScythePhysicsEntityData@2@AEBVVector3@2@AEBVQuat@2@@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+1*8]
?insert@PhysicsClass@Scythe@@QEAA_NPEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@QEAVNxScene@@PEBVScythePhysicsEntityData@2@AEBVVector3@2@AEBVQuat@2@@Z endp

; Scythe::PhysicsClass::insert(class PhysFileParams *, class _ScytheRootObjectInterfaceT *, class NxScene * const, const class Scythe::ScythePhysicsEntityData *, const class Scythe::Vector3 &);
?insert@PhysicsClass@Scythe@@QEAA_NPEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@QEAVNxScene@@PEBVScythePhysicsEntityData@2@AEBVVector3@2@@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+2*8]
?insert@PhysicsClass@Scythe@@QEAA_NPEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@QEAVNxScene@@PEBVScythePhysicsEntityData@2@AEBVVector3@2@@Z endp

; Scythe::PhysicsClass::createNewActor1(const class Scythe::PhysicsActorData *, class PhysFileParams *, class _ScytheRootObjectInterfaceT *, const class Scythe::Vector3 &, class NxScene * const, const class Scythe::Matrix &, class Scythe::SkeletonData *);
?createNewActor1@PhysicsClass@Scythe@@QEAAPEAVScytheActor@2@PEBVPhysicsActorData@2@PEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@AEBVVector3@2@QEAVNxScene@@AEBVMatrix@2@PEAVSkeletonData@2@@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+3*8]
?createNewActor1@PhysicsClass@Scythe@@QEAAPEAVScytheActor@2@PEBVPhysicsActorData@2@PEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@AEBVVector3@2@QEAVNxScene@@AEBVMatrix@2@PEAVSkeletonData@2@@Z endp

; Scythe::PhysicsClass::createNewActor(class PhysFileParams *, const class Scythe::PhysicsActorData *, const class Scythe::Vector3 &, class NxScene * const, const class Scythe::Matrix &, class Scythe::SkeletonData *);
?createNewActor@PhysicsClass@Scythe@@QEAAPEAVScytheActor@2@PEAVPhysFileParams@@PEBVPhysicsActorData@2@AEBVVector3@2@QEAVNxScene@@AEBVMatrix@2@PEAVSkeletonData@2@@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+4*8]
?createNewActor@PhysicsClass@Scythe@@QEAAPEAVScytheActor@2@PEAVPhysFileParams@@PEBVPhysicsActorData@2@AEBVVector3@2@QEAVNxScene@@AEBVMatrix@2@PEAVSkeletonData@2@@Z endp

; Scythe::PhysicsClass::createJoint1(const class Scythe::PhysicsJointData *, class NxActor * const, class NxActor * const, class NxScene * const, const class Scythe::Vector3 &, const class Scythe::Matrix &, const class Scythe::Vector3 &, int);
?createJoint1@PhysicsClass@Scythe@@QEAAPEAVNxJoint@@PEBVPhysicsJointData@2@QEAVNxActor@@1QEAVNxScene@@AEBVVector3@2@AEBVMatrix@2@3H@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+5*8]
?createJoint1@PhysicsClass@Scythe@@QEAAPEAVNxJoint@@PEBVPhysicsJointData@2@QEAVNxActor@@1QEAVNxScene@@AEBVVector3@2@AEBVMatrix@2@3H@Z endp

; Scythe::PhysicsClass::createJoint(const class Scythe::PhysicsJointData *, class NxActor * const, class NxActor * const, class NxScene * const, const class Scythe::Vector3 &, const class Scythe::Matrix &, const class Scythe::Vector3 &, int);
?createJoint@PhysicsClass@Scythe@@QEAAPEAVNxJoint@@PEBVPhysicsJointData@2@QEAVNxActor@@1QEAVNxScene@@AEBVVector3@2@AEBVMatrix@2@3H@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+6*8]
?createJoint@PhysicsClass@Scythe@@QEAAPEAVNxJoint@@PEBVPhysicsJointData@2@QEAVNxActor@@1QEAVNxScene@@AEBVVector3@2@AEBVMatrix@2@3H@Z endp

; Scythe::PhysicsClass::createSkeletalModel(class PhysFileParams *, class _ScytheRootObjectInterfaceT *, const class Scythe::PhysicsModelData *, const class Scythe::Vector3 &, const class Scythe::Matrix &);
?createSkeletalModel@PhysicsClass@Scythe@@QEAAPEAVSkeletonData@2@PEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@PEBVPhysicsModelData@2@AEBVVector3@2@AEBVMatrix@2@@Z proc EXPORT
jmp function_pointers[_Scythe_PhysicsClass_base+7*8]
?createSkeletalModel@PhysicsClass@Scythe@@QEAAPEAVSkeletonData@2@PEAVPhysFileParams@@PEAV_ScytheRootObjectInterfaceT@@PEBVPhysicsModelData@2@AEBVVector3@2@AEBVMatrix@2@@Z endp
