
?_CONSTRUCTOR@SeenSomeone@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SeenSomeone@@QEAAPEAV1@XZ endp

; SeenSomeone::SeenSomeone();
??0SeenSomeone@@QEAA@XZ proc EXPORT
jmp function_pointers[_SeenSomeone_base+0*8]
??0SeenSomeone@@QEAA@XZ endp

; SeenSomeone::lastSeenInSeconds();
?lastSeenInSeconds@SeenSomeone@@QEAAMXZ proc EXPORT
jmp function_pointers[_SeenSomeone_base+1*8]
?lastSeenInSeconds@SeenSomeone@@QEAAMXZ endp

; SeenSomeone::getPosition();
?getPosition@SeenSomeone@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_SeenSomeone_base+2*8]
?getPosition@SeenSomeone@@QEAA?AVVector3@Ogre@@XZ endp

; SeenSomeone::getFaction();
?getFaction@SeenSomeone@@QEAAPEAVFaction@@XZ proc EXPORT
jmp function_pointers[_SeenSomeone_base+3*8]
?getFaction@SeenSomeone@@QEAAPEAVFaction@@XZ endp
