
; SelectionBox::start(const class Ogre::Vector2 &);
?start@SelectionBox@@QEAAXAEBVVector2@Ogre@@@Z proc EXPORT
jmp function_pointers[_SelectionBox_base+0*8]
?start@SelectionBox@@QEAAXAEBVVector2@Ogre@@@Z endp

; SelectionBox::update(const class Ogre::Vector2 &);
?update@SelectionBox@@QEAAXAEBVVector2@Ogre@@@Z proc EXPORT
jmp function_pointers[_SelectionBox_base+1*8]
?update@SelectionBox@@QEAAXAEBVVector2@Ogre@@@Z endp

; SelectionBox::cancel();
?cancel@SelectionBox@@QEAAXXZ proc EXPORT
jmp function_pointers[_SelectionBox_base+2*8]
?cancel@SelectionBox@@QEAAXXZ endp

; SelectionBox::isActive();
?isActive@SelectionBox@@QEBA_NXZ proc EXPORT
jmp function_pointers[_SelectionBox_base+3*8]
?isActive@SelectionBox@@QEBA_NXZ endp

; SelectionBox::contains(const class Ogre::Vector3 &, const class Ogre::Vector3 &, float);
?contains@SelectionBox@@QEAA_NAEBVVector3@Ogre@@0M@Z proc EXPORT
jmp function_pointers[_SelectionBox_base+4*8]
?contains@SelectionBox@@QEAA_NAEBVVector3@Ogre@@0M@Z endp

; SelectionBox::contains(const class Ogre::AxisAlignedBox &);
?contains@SelectionBox@@QEBA_NAEBVAxisAlignedBox@Ogre@@@Z proc EXPORT
jmp function_pointers[_SelectionBox_base+5*8]
?contains@SelectionBox@@QEBA_NAEBVAxisAlignedBox@Ogre@@@Z endp

; SelectionBox::contains(const class Ogre::Vector3 &, float);
?contains@SelectionBox@@QEBA_NAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_SelectionBox_base+6*8]
?contains@SelectionBox@@QEBA_NAEBVVector3@Ogre@@M@Z endp

?_CONSTRUCTOR@SelectionBox@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SelectionBox@@QEAAPEAV1@XZ endp

; SelectionBox::SelectionBox();
??0SelectionBox@@QEAA@XZ proc EXPORT
jmp function_pointers[_SelectionBox_base+7*8]
??0SelectionBox@@QEAA@XZ endp

?_DESTRUCTOR@SelectionBox@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SelectionBox@@QEAAXXZ endp

; SelectionBox::~SelectionBox();
??1SelectionBox@@QEAA@XZ proc EXPORT
jmp function_pointers[_SelectionBox_base+8*8]
??1SelectionBox@@QEAA@XZ endp
