
?_CONSTRUCTOR@SensoryData@@QEAAPEAV1@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@SensoryData@@QEAAPEAV1@PEAVCharacter@@@Z endp

; SensoryData::SensoryData(class Character *);
??0SensoryData@@QEAA@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+0*8]
??0SensoryData@@QEAA@PEAVCharacter@@@Z endp

?_DESTRUCTOR@SensoryData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SensoryData@@QEAAXXZ endp

; SensoryData::~SensoryData();
??1SensoryData@@QEAA@XZ proc EXPORT
jmp function_pointers[_SensoryData_base+1*8]
??1SensoryData@@QEAA@XZ endp

; SensoryData::periodicUpdate(float);
?periodicUpdate@SensoryData@@QEAAXM@Z proc EXPORT
jmp function_pointers[_SensoryData_base+2*8]
?periodicUpdate@SensoryData@@QEAAXM@Z endp

; SensoryData::periodicUpdate_KOed();
?periodicUpdate_KOed@SensoryData@@QEAAXXZ proc EXPORT
jmp function_pointers[_SensoryData_base+3*8]
?periodicUpdate_KOed@SensoryData@@QEAAXXZ endp

; SensoryData::getVisionRange(bool);
?getVisionRange@SensoryData@@QEAAM_N@Z proc EXPORT
jmp function_pointers[_SensoryData_base+4*8]
?getVisionRange@SensoryData@@QEAAM_N@Z endp

; SensoryData::update(float);
?update@SensoryData@@QEAAXM@Z proc EXPORT
jmp function_pointers[_SensoryData_base+5*8]
?update@SensoryData@@QEAAXM@Z endp

; SensoryData::notifyKO();
?notifyKO@SensoryData@@QEAAXXZ proc EXPORT
jmp function_pointers[_SensoryData_base+6*8]
?notifyKO@SensoryData@@QEAAXXZ endp

; SensoryData::getIterator(unsigned int, unsigned int);
?getIterator@SensoryData@@QEAA?AVSenseItr@@II@Z proc EXPORT
jmp function_pointers[_SensoryData_base+7*8]
?getIterator@SensoryData@@QEAA?AVSenseItr@@II@Z endp

; SensoryData::getNearestEnemyDistanceSq();
?getNearestEnemyDistanceSq@SensoryData@@QEBAMXZ proc EXPORT
jmp function_pointers[_SensoryData_base+8*8]
?getNearestEnemyDistanceSq@SensoryData@@QEBAMXZ endp

; SensoryData::canISeeThisGuy(class Character *);
?canISeeThisGuy@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+9*8]
?canISeeThisGuy@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::canIHearThisGuy(class Character *);
?canIHearThisGuy@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+10*8]
?canIHearThisGuy@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::amIAwareOfThisGuy(class Character *, bool);
?amIAwareOfThisGuy@SensoryData@@QEAA_NPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_SensoryData_base+11*8]
?amIAwareOfThisGuy@SensoryData@@QEAA_NPEAVCharacter@@_N@Z endp

; SensoryData::getLastKnownPositionOf(class Character *);
?getLastKnownPositionOf@SensoryData@@QEAA?AVVector3@Ogre@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+12*8]
?getLastKnownPositionOf@SensoryData@@QEAA?AVVector3@Ogre@@PEAVCharacter@@@Z endp

; SensoryData::getDataFor(class Character *);
?getDataFor@SensoryData@@QEAAPEAVSeenSomeone@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+13*8]
?getDataFor@SensoryData@@QEAAPEAVSeenSomeone@@PEAVCharacter@@@Z endp

; SensoryData::notifyCriminalThreat(const class hand &);
?notifyCriminalThreat@SensoryData@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+14*8]
?notifyCriminalThreat@SensoryData@@QEAAXAEBVhand@@@Z endp

; SensoryData::getFactionRelation(class RootObjectBase *);
?getFactionRelation@SensoryData@@QEAAMPEAVRootObjectBase@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+15*8]
?getFactionRelation@SensoryData@@QEAAMPEAVRootObjectBase@@@Z endp

; SensoryData::getStateBroadcast();
?getStateBroadcast@SensoryData@@QEBAPEAVStateBroadcastData@@XZ proc EXPORT
jmp function_pointers[_SensoryData_base+16*8]
?getStateBroadcast@SensoryData@@QEBAPEAVStateBroadcastData@@XZ endp

; SensoryData::getStateBroadcastOf(const class hand &);
?getStateBroadcastOf@SensoryData@@QEAAPEAVStateBroadcastData@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+17*8]
?getStateBroadcastOf@SensoryData@@QEAAPEAVStateBroadcastData@@AEBVhand@@@Z endp

; SensoryData::_shareSensesCheck(class Character *, class lektor<RootObject *> &, float);
?_shareSensesCheck@SensoryData@@QEAA_NPEAVCharacter@@AEAV?$lektor@PEAVRootObject@@@@M@Z proc EXPORT
jmp function_pointers[_SensoryData_base+18*8]
?_shareSensesCheck@SensoryData@@QEAA_NPEAVCharacter@@AEAV?$lektor@PEAVRootObject@@@@M@Z endp

; SensoryData::getGUIData(class DatapanelGUI *, int);
?getGUIData@SensoryData@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_SensoryData_base+19*8]
?getGUIData@SensoryData@@QEAAXPEAVDatapanelGUI@@H@Z endp

; SensoryData::_calculateFOVScore(class Character *);
?_calculateFOVScore@SensoryData@@QEAAMPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+20*8]
?_calculateFOVScore@SensoryData@@QEAAMPEAVCharacter@@@Z endp

; SensoryData::_traceLineOfSightCheck(class Character *);
?_traceLineOfSightCheck@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+21*8]
?_traceLineOfSightCheck@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::getCharacter();
?getCharacter@SensoryData@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_SensoryData_base+22*8]
?getCharacter@SensoryData@@QEBAPEAVCharacter@@XZ endp

; SensoryData::dialogAssessmentUpdate(float, bool);
?dialogAssessmentUpdate@SensoryData@@QEAAXM_N@Z proc EXPORT
jmp function_pointers[_SensoryData_base+23*8]
?dialogAssessmentUpdate@SensoryData@@QEAAXM_N@Z endp

; SensoryData::noticeThisPerson(class Character *, bool);
?noticeThisPerson@SensoryData@@QEAAXPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_SensoryData_base+24*8]
?noticeThisPerson@SensoryData@@QEAAXPEAVCharacter@@_N@Z endp

; SensoryData::add(class Character *, bool, bool);
?add@SensoryData@@QEAAPEAVSeenSomeone@@PEAVCharacter@@_N1@Z proc EXPORT
jmp function_pointers[_SensoryData_base+25*8]
?add@SensoryData@@QEAAPEAVSeenSomeone@@PEAVCharacter@@_N1@Z endp

; SensoryData::remove(class Character *);
?remove@SensoryData@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+26*8]
?remove@SensoryData@@QEAAXPEAVCharacter@@@Z endp

; SensoryData::decay(class Character *);
?decay@SensoryData@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+27*8]
?decay@SensoryData@@QEAAXPEAVCharacter@@@Z endp

; SensoryData::canSee(class Character *, class SeenSomeone *);
?canSee@SensoryData@@QEAA_NPEAVCharacter@@PEAVSeenSomeone@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+28*8]
?canSee@SensoryData@@QEAA_NPEAVCharacter@@PEAVSeenSomeone@@@Z endp

; SensoryData::canHear(class Character *, class SeenSomeone *);
?canHear@SensoryData@@QEAA_NPEAVCharacter@@PEAVSeenSomeone@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+29*8]
?canHear@SensoryData@@QEAA_NPEAVCharacter@@PEAVSeenSomeone@@@Z endp

; SensoryData::disguiseMods(class Character *, float);
?disguiseMods@SensoryData@@QEAA_NPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_SensoryData_base+30*8]
?disguiseMods@SensoryData@@QEAA_NPEAVCharacter@@M@Z endp

; SensoryData::assessCrimes(class Character *);
?assessCrimes@SensoryData@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+31*8]
?assessCrimes@SensoryData@@QEAAXPEAVCharacter@@@Z endp

; SensoryData::assessKidnapping(class Character *);
?assessKidnapping@SensoryData@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+32*8]
?assessKidnapping@SensoryData@@QEAAXPEAVCharacter@@@Z endp

; SensoryData::processKillList();
?processKillList@SensoryData@@QEAAXXZ proc EXPORT
jmp function_pointers[_SensoryData_base+33*8]
?processKillList@SensoryData@@QEAAXXZ endp

; SensoryData::assessNeutral(class Character *, bool);
?assessNeutral@SensoryData@@QEAAXPEAVCharacter@@_N@Z proc EXPORT
jmp function_pointers[_SensoryData_base+34*8]
?assessNeutral@SensoryData@@QEAAXPEAVCharacter@@_N@Z endp

; SensoryData::setupMyProgressBar(const class hand &);
?setupMyProgressBar@SensoryData@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+35*8]
?setupMyProgressBar@SensoryData@@QEAAXAEBVhand@@@Z endp

; SensoryData::updateMyProgressBar(float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?updateMyProgressBar@SensoryData@@QEAAXMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+36*8]
?updateMyProgressBar@SensoryData@@QEAAXMAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SensoryData::canISeeThisGuyDoinSneakingOrSomething(class Character *, float, class SensoryData::SpottingPeopleMgr *, float, float);
?canISeeThisGuyDoinSneakingOrSomething@SensoryData@@QEAA?AVYesNoMaybe@@PEAVCharacter@@MPEAVSpottingPeopleMgr@1@MM@Z proc EXPORT
jmp function_pointers[_SensoryData_base+37*8]
?canISeeThisGuyDoinSneakingOrSomething@SensoryData@@QEAA?AVYesNoMaybe@@PEAVCharacter@@MPEAVSpottingPeopleMgr@1@MM@Z endp

; SensoryData::isIntruder_Base(class Character *);
?isIntruder_Base@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+38*8]
?isIntruder_Base@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::isIntruder_Building(class Character *);
?isIntruder_Building@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+39*8]
?isIntruder_Building@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::isInMyPrivate_Building(class Character *);
?isInMyPrivate_Building@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+40*8]
?isInMyPrivate_Building@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::isEscapee(class Character *);
?isEscapee@SensoryData@@QEAA_NPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+41*8]
?isEscapee@SensoryData@@QEAA_NPEAVCharacter@@@Z endp

; SensoryData::reassessAll(class lektor<RootObject *> &, float);
?reassessAll@SensoryData@@QEAAXAEAV?$lektor@PEAVRootObject@@@@M@Z proc EXPORT
jmp function_pointers[_SensoryData_base+42*8]
?reassessAll@SensoryData@@QEAAXAEAV?$lektor@PEAVRootObject@@@@M@Z endp

; SensoryData::reassess(class Character *, class SeenSomeone *, float);
?reassess@SensoryData@@QEAAPEAVSeenSomeone@@PEAVCharacter@@PEAV2@M@Z proc EXPORT
jmp function_pointers[_SensoryData_base+43*8]
?reassess@SensoryData@@QEAAPEAVSeenSomeone@@PEAVCharacter@@PEAV2@M@Z endp

; SensoryData::addToThreatsAndFlockingList(class Character *);
?addToThreatsAndFlockingList@SensoryData@@QEAAXPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SensoryData_base+44*8]
?addToThreatsAndFlockingList@SensoryData@@QEAAXPEAVCharacter@@@Z endp

; SensoryData::buildingSpotterUpdate();
?buildingSpotterUpdate@SensoryData@@QEAAXXZ proc EXPORT
jmp function_pointers[_SensoryData_base+45*8]
?buildingSpotterUpdate@SensoryData@@QEAAXXZ endp
