
; SensoryData::SpottingPeopleMgr::spot(const class hand &, float);
?spot@SpottingPeopleMgr@SensoryData@@QEAAXAEBVhand@@M@Z proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+0*8]
?spot@SpottingPeopleMgr@SensoryData@@QEAAXAEBVhand@@M@Z endp

; SensoryData::SpottingPeopleMgr::getTime(const class hand &);
?getTime@SpottingPeopleMgr@SensoryData@@QEAAMAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+1*8]
?getTime@SpottingPeopleMgr@SensoryData@@QEAAMAEBVhand@@@Z endp

; SensoryData::SpottingPeopleMgr::update(float);
?update@SpottingPeopleMgr@SensoryData@@QEAAXM@Z proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+2*8]
?update@SpottingPeopleMgr@SensoryData@@QEAAXM@Z endp

; SensoryData::SpottingPeopleMgr::cantSeeAnymore(const class hand &);
?cantSeeAnymore@SpottingPeopleMgr@SensoryData@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+3*8]
?cantSeeAnymore@SpottingPeopleMgr@SensoryData@@QEAAXAEBVhand@@@Z endp

; SensoryData::SpottingPeopleMgr::has(const class hand &);
?has@SpottingPeopleMgr@SensoryData@@QEBA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+4*8]
?has@SpottingPeopleMgr@SensoryData@@QEBA_NAEBVhand@@@Z endp

; SensoryData::SpottingPeopleMgr::resetSeenFlags();
?resetSeenFlags@SpottingPeopleMgr@SensoryData@@QEAAXXZ proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+5*8]
?resetSeenFlags@SpottingPeopleMgr@SensoryData@@QEAAXXZ endp

?_CONSTRUCTOR@SpottingPeopleMgr@SensoryData@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@SpottingPeopleMgr@SensoryData@@QEAAPEAV12@XZ endp

; SensoryData::SpottingPeopleMgr::SpottingPeopleMgr();
??0SpottingPeopleMgr@SensoryData@@QEAA@XZ proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+6*8]
??0SpottingPeopleMgr@SensoryData@@QEAA@XZ endp

?_DESTRUCTOR@SpottingPeopleMgr@SensoryData@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SpottingPeopleMgr@SensoryData@@QEAAXXZ endp

; SensoryData::SpottingPeopleMgr::~SpottingPeopleMgr();
??1SpottingPeopleMgr@SensoryData@@QEAA@XZ proc EXPORT
jmp function_pointers[_SensoryData_SpottingPeopleMgr_base+7*8]
??1SpottingPeopleMgr@SensoryData@@QEAA@XZ endp
