
?_CONSTRUCTOR@ShopTraderInventorySection@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAVInventory@@@Z proc EXPORT
?_CONSTRUCTOR@ShopTraderInventorySection@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAVInventory@@@Z endp

; ShopTraderInventorySection::ShopTraderInventorySection(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, class Inventory *);
??0ShopTraderInventorySection@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAVInventory@@@Z proc EXPORT
jmp function_pointers[_ShopTraderInventorySection_base+0*8]
??0ShopTraderInventorySection@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAVInventory@@@Z endp

?_NV_addItem@ShopTraderInventorySection@@QEAA_NPEAVItem@@H@Z proc EXPORT
?_NV_addItem@ShopTraderInventorySection@@QEAA_NPEAVItem@@H@Z endp

; ShopTraderInventorySection::addItem(class Item *, int);
?addItem@ShopTraderInventorySection@@UEAA_NPEAVItem@@H@Z proc EXPORT
jmp function_pointers[_ShopTraderInventorySection_base+1*8]
?addItem@ShopTraderInventorySection@@UEAA_NPEAVItem@@H@Z endp

?_NV_autoArrange@ShopTraderInventorySection@@QEAAXXZ proc EXPORT
?_NV_autoArrange@ShopTraderInventorySection@@QEAAXXZ endp

; ShopTraderInventorySection::autoArrange();
?autoArrange@ShopTraderInventorySection@@UEAAXXZ proc EXPORT
jmp function_pointers[_ShopTraderInventorySection_base+2*8]
?autoArrange@ShopTraderInventorySection@@UEAAXXZ endp

?_DESTRUCTOR@ShopTraderInventorySection@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ShopTraderInventorySection@@QEAAXXZ endp

; ShopTraderInventorySection::~ShopTraderInventorySection();
??1ShopTraderInventorySection@@UEAA@XZ proc EXPORT
jmp function_pointers[_ShopTraderInventorySection_base+3*8]
??1ShopTraderInventorySection@@UEAA@XZ endp
