
?_CONSTRUCTOR@ShopTrader@@QEAAPEAV1@PEAVCharacter@@@Z proc EXPORT
?_CONSTRUCTOR@ShopTrader@@QEAAPEAV1@PEAVCharacter@@@Z endp

; ShopTrader::ShopTrader(class Character *);
??0ShopTrader@@QEAA@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+0*8]
??0ShopTrader@@QEAA@PEAVCharacter@@@Z endp

?_DESTRUCTOR@ShopTrader@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ShopTrader@@QEAAXXZ endp

; ShopTrader::~ShopTrader();
??1ShopTrader@@UEAA@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+1*8]
??1ShopTrader@@UEAA@XZ endp

?_NV_getGUIData@ShopTrader@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@ShopTrader@@QEAAXPEAVDatapanelGUI@@H@Z endp

; ShopTrader::getGUIData(class DatapanelGUI *, int);
?getGUIData@ShopTrader@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+2*8]
?getGUIData@ShopTrader@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_equipItem@ShopTrader@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_equipItem@ShopTrader@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; ShopTrader::equipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?equipItem@ShopTrader@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+3*8]
?equipItem@ShopTrader@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_unequipItem@ShopTrader@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_unequipItem@ShopTrader@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; ShopTrader::unequipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?unequipItem@ShopTrader@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+4*8]
?unequipItem@ShopTrader@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_getInventory@ShopTrader@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@ShopTrader@@QEBAPEAVInventory@@XZ endp

; ShopTrader::getInventory();
?getInventory@ShopTrader@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+5*8]
?getInventory@ShopTrader@@UEBAPEAVInventory@@XZ endp

?_NV_takeMoney@ShopTrader@@QEAA_NH@Z proc EXPORT
?_NV_takeMoney@ShopTrader@@QEAA_NH@Z endp

; ShopTrader::takeMoney(int);
?takeMoney@ShopTrader@@UEAA_NH@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+6*8]
?takeMoney@ShopTrader@@UEAA_NH@Z endp

?_NV_getMoney@ShopTrader@@QEBAHXZ proc EXPORT
?_NV_getMoney@ShopTrader@@QEBAHXZ endp

; ShopTrader::getMoney();
?getMoney@ShopTrader@@UEBAHXZ proc EXPORT
jmp function_pointers[_ShopTrader_base+7*8]
?getMoney@ShopTrader@@UEBAHXZ endp

?_NV_getOrientation@ShopTrader@@QEBA?AVQuaternion@Ogre@@XZ proc EXPORT
?_NV_getOrientation@ShopTrader@@QEBA?AVQuaternion@Ogre@@XZ endp

; ShopTrader::getOrientation();
?getOrientation@ShopTrader@@UEBA?AVQuaternion@Ogre@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+8*8]
?getOrientation@ShopTrader@@UEBA?AVQuaternion@Ogre@@XZ endp

?_NV_getPosition@ShopTrader@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@ShopTrader@@QEAA?AVVector3@Ogre@@XZ endp

; ShopTrader::getPosition();
?getPosition@ShopTrader@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+9*8]
?getPosition@ShopTrader@@UEAA?AVVector3@Ogre@@XZ endp

?_NV_isIndoors@ShopTrader@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_isIndoors@ShopTrader@@QEBAAEBVhand@@XZ endp

; ShopTrader::isIndoors();
?isIndoors@ShopTrader@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+10*8]
?isIndoors@ShopTrader@@UEBAAEBVhand@@XZ endp

?_NV_getFloor@ShopTrader@@QEBAHXZ proc EXPORT
?_NV_getFloor@ShopTrader@@QEBAHXZ endp

; ShopTrader::getFloor();
?getFloor@ShopTrader@@UEBAHXZ proc EXPORT
jmp function_pointers[_ShopTrader_base+11*8]
?getFloor@ShopTrader@@UEBAHXZ endp

?_NV_getCurrentTownLocation@ShopTrader@@QEAAPEAVTownBase@@XZ proc EXPORT
?_NV_getCurrentTownLocation@ShopTrader@@QEAAPEAVTownBase@@XZ endp

; ShopTrader::getCurrentTownLocation();
?getCurrentTownLocation@ShopTrader@@UEAAPEAVTownBase@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+12*8]
?getCurrentTownLocation@ShopTrader@@UEAAPEAVTownBase@@XZ endp

?_NV_getDataType@ShopTrader@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@ShopTrader@@QEBA?AW4itemType@@XZ endp

; ShopTrader::getDataType();
?getDataType@ShopTrader@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+13*8]
?getDataType@ShopTrader@@UEBA?AW4itemType@@XZ endp

?_NV_serialise@ShopTrader@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@ShopTrader@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; ShopTrader::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@ShopTrader@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+14*8]
?serialise@ShopTrader@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@ShopTrader@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@ShopTrader@@QEAAXPEAVGameSaveState@@@Z endp

; ShopTrader::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@ShopTrader@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+15*8]
?loadFromSerialise@ShopTrader@@UEAAXPEAVGameSaveState@@@Z endp

; ShopTrader::getTrader();
?getTrader@ShopTrader@@QEBAPEAVCharacter@@XZ proc EXPORT
jmp function_pointers[_ShopTrader_base+16*8]
?getTrader@ShopTrader@@QEBAPEAVCharacter@@XZ endp

?_NV_isPhysical@ShopTrader@@QEBA_NXZ proc EXPORT
?_NV_isPhysical@ShopTrader@@QEBA_NXZ endp

; ShopTrader::isPhysical();
?isPhysical@ShopTrader@@UEBA_NXZ proc EXPORT
jmp function_pointers[_ShopTrader_base+17*8]
?isPhysical@ShopTrader@@UEBA_NXZ endp

?_NV_setVisible@ShopTrader@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@ShopTrader@@QEAAX_N@Z endp

; ShopTrader::setVisible(bool);
?setVisible@ShopTrader@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_ShopTrader_base+18*8]
?setVisible@ShopTrader@@UEAAX_N@Z endp

?_NV_createPhysical@ShopTrader@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@ShopTrader@@QEAA_NXZ endp

; ShopTrader::createPhysical();
?createPhysical@ShopTrader@@UEAA_NXZ proc EXPORT
jmp function_pointers[_ShopTrader_base+19*8]
?createPhysical@ShopTrader@@UEAA_NXZ endp

?_NV_destroyPhysical@ShopTrader@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@ShopTrader@@QEAAXXZ endp

; ShopTrader::destroyPhysical();
?destroyPhysical@ShopTrader@@UEAAXXZ proc EXPORT
jmp function_pointers[_ShopTrader_base+20*8]
?destroyPhysical@ShopTrader@@UEAAXXZ endp

; ShopTrader::updateInventory();
?updateInventory@ShopTrader@@QEAAXXZ proc EXPORT
jmp function_pointers[_ShopTrader_base+21*8]
?updateInventory@ShopTrader@@QEAAXXZ endp
