
?_CONSTRUCTOR@ShopTraderInventory@@QEAAPEAV1@PEAVRootObject@@AEAV?$vector@PEAVInventorySection@@V?$STLAllocator@PEAVInventorySection@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_CONSTRUCTOR@ShopTraderInventory@@QEAAPEAV1@PEAVRootObject@@AEAV?$vector@PEAVInventorySection@@V?$STLAllocator@PEAVInventorySection@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; ShopTraderInventory::ShopTraderInventory(class RootObject *, class std::vector<InventorySection *,Ogre::STLAllocator<InventorySection *,Ogre::CategorisedAllocPolicy<0> > > &);
??0ShopTraderInventory@@QEAA@PEAVRootObject@@AEAV?$vector@PEAVInventorySection@@V?$STLAllocator@PEAVInventorySection@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+0*8]
??0ShopTraderInventory@@QEAA@PEAVRootObject@@AEAV?$vector@PEAVInventorySection@@V?$STLAllocator@PEAVInventorySection@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_DESTRUCTOR@ShopTraderInventory@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ShopTraderInventory@@QEAAXXZ endp

; ShopTraderInventory::~ShopTraderInventory();
??1ShopTraderInventory@@UEAA@XZ proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+1*8]
??1ShopTraderInventory@@UEAA@XZ endp

?_NV_updateInventory@ShopTraderInventory@@QEAAXXZ proc EXPORT
?_NV_updateInventory@ShopTraderInventory@@QEAAXXZ endp

; ShopTraderInventory::updateInventory();
?updateInventory@ShopTraderInventory@@UEAAXXZ proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+2*8]
?updateInventory@ShopTraderInventory@@UEAAXXZ endp

?_NV_dropItem@ShopTraderInventory@@QEAAXPEAVItem@@@Z proc EXPORT
?_NV_dropItem@ShopTraderInventory@@QEAAXPEAVItem@@@Z endp

; ShopTraderInventory::dropItem(class Item *);
?dropItem@ShopTraderInventory@@UEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+3*8]
?dropItem@ShopTraderInventory@@UEAAXPEAVItem@@@Z endp

?_NV_refreshGui@ShopTraderInventory@@QEAAXXZ proc EXPORT
?_NV_refreshGui@ShopTraderInventory@@QEAAXXZ endp

; ShopTraderInventory::refreshGui();
?refreshGui@ShopTraderInventory@@UEAAXXZ proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+4*8]
?refreshGui@ShopTraderInventory@@UEAAXXZ endp

?_NV_initialiseNewSection@ShopTraderInventory@@QEAAPEAVInventorySection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHW4AttachSlot@@_N22H@Z proc EXPORT
?_NV_initialiseNewSection@ShopTraderInventory@@QEAAPEAVInventorySection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHW4AttachSlot@@_N22H@Z endp

; ShopTraderInventory::initialiseNewSection(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int, int, enum AttachSlot, bool, bool, bool, int);
?initialiseNewSection@ShopTraderInventory@@UEAAPEAVInventorySection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHW4AttachSlot@@_N22H@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+5*8]
?initialiseNewSection@ShopTraderInventory@@UEAAPEAVInventorySection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHW4AttachSlot@@_N22H@Z endp

?_NV__addItem@ShopTraderInventory@@QEAA_NPEAVItem@@H@Z proc EXPORT
?_NV__addItem@ShopTraderInventory@@QEAA_NPEAVItem@@H@Z endp

; ShopTraderInventory::_addItem(class Item *, int);
?_addItem@ShopTraderInventory@@UEAA_NPEAVItem@@H@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+6*8]
?_addItem@ShopTraderInventory@@UEAA_NPEAVItem@@H@Z endp

; ShopTraderInventory::_addItemToInventories(class Item *);
?_addItemToInventories@ShopTraderInventory@@QEAA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+7*8]
?_addItemToInventories@ShopTraderInventory@@QEAA_NPEAVItem@@@Z endp

; ShopTraderInventory::_removeItemFromInventories(class Item *, int);
?_removeItemFromInventories@ShopTraderInventory@@QEAAXPEAVItem@@H@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+8*8]
?_removeItemFromInventories@ShopTraderInventory@@QEAAXPEAVItem@@H@Z endp

?_NV__sectionAddItemCallback@ShopTraderInventory@@QEAAXPEAVItem@@@Z proc EXPORT
?_NV__sectionAddItemCallback@ShopTraderInventory@@QEAAXPEAVItem@@@Z endp

; ShopTraderInventory::_sectionAddItemCallback(class Item *);
?_sectionAddItemCallback@ShopTraderInventory@@UEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+9*8]
?_sectionAddItemCallback@ShopTraderInventory@@UEAAXPEAVItem@@@Z endp

?_NV__sectionUpdateItemCallback@ShopTraderInventory@@QEAAXPEAVItem@@H@Z proc EXPORT
?_NV__sectionUpdateItemCallback@ShopTraderInventory@@QEAAXPEAVItem@@H@Z endp

; ShopTraderInventory::_sectionUpdateItemCallback(class Item *, int);
?_sectionUpdateItemCallback@ShopTraderInventory@@UEAAXPEAVItem@@H@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+10*8]
?_sectionUpdateItemCallback@ShopTraderInventory@@UEAAXPEAVItem@@H@Z endp

?_NV__sectionRemoveItemCallback@ShopTraderInventory@@QEAAXPEAVItem@@@Z proc EXPORT
?_NV__sectionRemoveItemCallback@ShopTraderInventory@@QEAAXPEAVItem@@@Z endp

; ShopTraderInventory::_sectionRemoveItemCallback(class Item *);
?_sectionRemoveItemCallback@ShopTraderInventory@@UEAAXPEAVItem@@@Z proc EXPORT
jmp function_pointers[_ShopTraderInventory_base+11*8]
?_sectionRemoveItemCallback@ShopTraderInventory@@UEAAXPEAVItem@@@Z endp
