
?_CONSTRUCTOR@SimpleTimeStamper@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SimpleTimeStamper@@QEAAPEAV1@XZ endp

; SimpleTimeStamper::SimpleTimeStamper();
??0SimpleTimeStamper@@QEAA@XZ proc EXPORT
jmp function_pointers[_SimpleTimeStamper_base+0*8]
??0SimpleTimeStamper@@QEAA@XZ endp

; SimpleTimeStamper::getTime(double);
?getTime@SimpleTimeStamper@@QEAANN@Z proc EXPORT
jmp function_pointers[_SimpleTimeStamper_base+1*8]
?getTime@SimpleTimeStamper@@QEAANN@Z endp

; SimpleTimeStamper::stampTime();
?stampTime@SimpleTimeStamper@@QEAANXZ proc EXPORT
jmp function_pointers[_SimpleTimeStamper_base+2*8]
?stampTime@SimpleTimeStamper@@QEAANXZ endp

?_DESTRUCTOR@SimpleTimeStamper@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SimpleTimeStamper@@QEAAXXZ endp

; SimpleTimeStamper::~SimpleTimeStamper();
??1SimpleTimeStamper@@QEAA@XZ proc EXPORT
jmp function_pointers[_SimpleTimeStamper_base+3*8]
??1SimpleTimeStamper@@QEAA@XZ endp
