
?_CONSTRUCTOR@SpeedGroup@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SpeedGroup@@QEAAPEAV1@XZ endp

; SpeedGroup::SpeedGroup();
??0SpeedGroup@@QEAA@XZ proc EXPORT
jmp function_pointers[_SpeedGroup_base+0*8]
??0SpeedGroup@@QEAA@XZ endp

; SpeedGroup::insert(const class hand &);
?insert@SpeedGroup@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SpeedGroup_base+1*8]
?insert@SpeedGroup@@QEAAXAEBVhand@@@Z endp

; SpeedGroup::erase(const class hand &);
?erase@SpeedGroup@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_SpeedGroup_base+2*8]
?erase@SpeedGroup@@QEAAXAEBVhand@@@Z endp

; SpeedGroup::getSpeed(class Character *);
?getSpeed@SpeedGroup@@QEAAMPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_SpeedGroup_base+3*8]
?getSpeed@SpeedGroup@@QEAAMPEAVCharacter@@@Z endp

?_DESTRUCTOR@SpeedGroup@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SpeedGroup@@QEAAXXZ endp

; SpeedGroup::~SpeedGroup();
??1SpeedGroup@@QEAA@XZ proc EXPORT
jmp function_pointers[_SpeedGroup_base+4*8]
??1SpeedGroup@@QEAA@XZ endp
