
?_CONSTRUCTOR@SplashScreen@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@SplashScreen@@QEAAPEAV1@XZ endp

; SplashScreen::SplashScreen();
??0SplashScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_SplashScreen_base+0*8]
??0SplashScreen@@QEAA@XZ endp

?_DESTRUCTOR@SplashScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SplashScreen@@QEAAXXZ endp

; SplashScreen::~SplashScreen();
??1SplashScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_SplashScreen_base+1*8]
??1SplashScreen@@QEAA@XZ endp

; SplashScreen::update();
?update@SplashScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SplashScreen_base+2*8]
?update@SplashScreen@@QEAAXXZ endp

; SplashScreen::getState();
?getState@SplashScreen@@QEBADXZ proc EXPORT
jmp function_pointers[_SplashScreen_base+3*8]
?getState@SplashScreen@@QEBADXZ endp

; SplashScreen::getEnded();
?getEnded@SplashScreen@@QEBA_NXZ proc EXPORT
jmp function_pointers[_SplashScreen_base+4*8]
?getEnded@SplashScreen@@QEBA_NXZ endp

; SplashScreen::skip();
?skip@SplashScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SplashScreen_base+5*8]
?skip@SplashScreen@@QEAAXXZ endp

; SplashScreen::addLogo(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, float);
?addLogo@SplashScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z proc EXPORT
jmp function_pointers[_SplashScreen_base+6*8]
?addLogo@SplashScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M@Z endp
