
?_CONSTRUCTOR@SquadManagementScreen@@QEAAPEAV1@PEAVManagementScreen@@@Z proc EXPORT
?_CONSTRUCTOR@SquadManagementScreen@@QEAAPEAV1@PEAVManagementScreen@@@Z endp

; SquadManagementScreen::SquadManagementScreen(class ManagementScreen *);
??0SquadManagementScreen@@QEAA@PEAVManagementScreen@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+0*8]
??0SquadManagementScreen@@QEAA@PEAVManagementScreen@@@Z endp

?_DESTRUCTOR@SquadManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::~SquadManagementScreen();
??1SquadManagementScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+1*8]
??1SquadManagementScreen@@QEAA@XZ endp

; SquadManagementScreen::getVisible();
?getVisible@SquadManagementScreen@@QEBA_NXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+2*8]
?getVisible@SquadManagementScreen@@QEBA_NXZ endp

; SquadManagementScreen::update();
?update@SquadManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+3*8]
?update@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::reset();
?reset@SquadManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+4*8]
?reset@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::refreshSquads();
?refreshSquads@SquadManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+5*8]
?refreshSquads@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::notifyStartDropSquad(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool &);
?notifyStartDropSquad@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+6*8]
?notifyStartDropSquad@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z endp

; SquadManagementScreen::notifyRequestDropSquad(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool &);
?notifyRequestDropSquad@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+7*8]
?notifyRequestDropSquad@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z endp

; SquadManagementScreen::notifyEndDropSquad(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool);
?notifyEndDropSquad@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+8*8]
?notifyEndDropSquad@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@_N@Z endp

; SquadManagementScreen::notifyStartDropPortrait(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool &);
?notifyStartDropPortrait@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+9*8]
?notifyStartDropPortrait@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z endp

; SquadManagementScreen::notifyRequestDropPortrait(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool &);
?notifyRequestDropPortrait@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+10*8]
?notifyRequestDropPortrait@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@AEA_N@Z endp

; SquadManagementScreen::notifyEndDropPortrait(class wraps::BaseLayout *, struct wraps::DDItemInfo, bool);
?notifyEndDropPortrait@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+11*8]
?notifyEndDropPortrait@SquadManagementScreen@@QEAAXPEAVBaseLayout@wraps@@UDDItemInfo@3@_N@Z endp

; SquadManagementScreen::onAddSquad(class MyGUI::Widget *);
?onAddSquad@SquadManagementScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+12*8]
?onAddSquad@SquadManagementScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; SquadManagementScreen::removeSquad(class SquadManagementScreen::SquadData *);
?removeSquad@SquadManagementScreen@@QEAAXPEAVSquadData@1@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+13*8]
?removeSquad@SquadManagementScreen@@QEAAXPEAVSquadData@1@@Z endp

; SquadManagementScreen::getSquad(class ActivePlatoon *);
?getSquad@SquadManagementScreen@@QEAAPEAVSquadData@1@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+14*8]
?getSquad@SquadManagementScreen@@QEAAPEAVSquadData@1@PEAVActivePlatoon@@@Z endp

; SquadManagementScreen::dismissCharacter(int);
?dismissCharacter@SquadManagementScreen@@QEAAXH@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_base+15*8]
?dismissCharacter@SquadManagementScreen@@QEAAXH@Z endp
