
?_CONSTRUCTOR@PortraitSquadItemBox@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@PortraitSquadItemBox@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z endp

; SquadManagementScreen::PortraitSquadItemBox::PortraitSquadItemBox(class MyGUI::Widget *);
??0PortraitSquadItemBox@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadItemBox_base+0*8]
??0PortraitSquadItemBox@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@PortraitSquadItemBox@SquadManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PortraitSquadItemBox@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::PortraitSquadItemBox::~PortraitSquadItemBox();
??1PortraitSquadItemBox@SquadManagementScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadItemBox_base+1*8]
??1PortraitSquadItemBox@SquadManagementScreen@@UEAA@XZ endp

; SquadManagementScreen::PortraitSquadItemBox::getItemCount();
?getItemCount@PortraitSquadItemBox@SquadManagementScreen@@QEBAHXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadItemBox_base+2*8]
?getItemCount@PortraitSquadItemBox@SquadManagementScreen@@QEBAHXZ endp

; SquadManagementScreen::PortraitSquadItemBox::update();
?update@PortraitSquadItemBox@SquadManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadItemBox_base+3*8]
?update@PortraitSquadItemBox@SquadManagementScreen@@QEAAXXZ endp
