
?_CONSTRUCTOR@PortraitSquadCellView@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@PortraitSquadCellView@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z endp

; SquadManagementScreen::PortraitSquadCellView::PortraitSquadCellView(class MyGUI::Widget *);
??0PortraitSquadCellView@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadCellView_base+0*8]
??0PortraitSquadCellView@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@PortraitSquadCellView@SquadManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@PortraitSquadCellView@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::PortraitSquadCellView::~PortraitSquadCellView();
??1PortraitSquadCellView@SquadManagementScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadCellView_base+1*8]
??1PortraitSquadCellView@SquadManagementScreen@@UEAA@XZ endp

; SquadManagementScreen::PortraitSquadCellView::update(const struct MyGUI::IBDrawItemInfo &, class PortraitData *);
?update@PortraitSquadCellView@SquadManagementScreen@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVPortraitData@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadCellView_base+2*8]
?update@PortraitSquadCellView@SquadManagementScreen@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVPortraitData@@@Z endp

; SquadManagementScreen::PortraitSquadCellView::getCellDimension(class MyGUI::Widget *, struct MyGUI::types::TCoord<int> &, bool);
?getCellDimension@PortraitSquadCellView@SquadManagementScreen@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@4@_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadCellView_base+3*8]
?getCellDimension@PortraitSquadCellView@SquadManagementScreen@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@4@_N@Z endp

; SquadManagementScreen::PortraitSquadCellView::resize();
?resize@PortraitSquadCellView@SquadManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadCellView_base+4*8]
?resize@PortraitSquadCellView@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::PortraitSquadCellView::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@PortraitSquadCellView@SquadManagementScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_PortraitSquadCellView_base+5*8]
?setName@PortraitSquadCellView@SquadManagementScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
