
?_CONSTRUCTOR@SquadItemBox@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@SquadItemBox@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z endp

; SquadManagementScreen::SquadItemBox::SquadItemBox(class MyGUI::Widget *);
??0SquadItemBox@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadItemBox_base+0*8]
??0SquadItemBox@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@SquadItemBox@SquadManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SquadItemBox@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::SquadItemBox::~SquadItemBox();
??1SquadItemBox@SquadManagementScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadItemBox_base+1*8]
??1SquadItemBox@SquadManagementScreen@@UEAA@XZ endp

; SquadManagementScreen::SquadItemBox::setCellSize(int, int);
?setCellSize@SquadItemBox@SquadManagementScreen@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadItemBox_base+2*8]
?setCellSize@SquadItemBox@SquadManagementScreen@@QEAAXHH@Z endp

; SquadManagementScreen::SquadItemBox::getItemCount();
?getItemCount@SquadItemBox@SquadManagementScreen@@QEBAHXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadItemBox_base+3*8]
?getItemCount@SquadItemBox@SquadManagementScreen@@QEBAHXZ endp
