
?_CONSTRUCTOR@SquadData@SquadManagementScreen@@QEAAPEAV12@PEAVActivePlatoon@@@Z proc EXPORT
?_CONSTRUCTOR@SquadData@SquadManagementScreen@@QEAAPEAV12@PEAVActivePlatoon@@@Z endp

; SquadManagementScreen::SquadData::SquadData(class ActivePlatoon *);
??0SquadData@SquadManagementScreen@@QEAA@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadData_base+0*8]
??0SquadData@SquadManagementScreen@@QEAA@PEAVActivePlatoon@@@Z endp

?_DESTRUCTOR@SquadData@SquadManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SquadData@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::SquadData::~SquadData();
??1SquadData@SquadManagementScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadData_base+1*8]
??1SquadData@SquadManagementScreen@@QEAA@XZ endp

; SquadManagementScreen::SquadData::setName(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setName@SquadData@SquadManagementScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadData_base+2*8]
?setName@SquadData@SquadManagementScreen@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; SquadManagementScreen::SquadData::getName();
?getName@SquadData@SquadManagementScreen@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadData_base+3*8]
?getName@SquadData@SquadManagementScreen@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp
