
?_CONSTRUCTOR@SquadCellView@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@SquadCellView@SquadManagementScreen@@QEAAPEAV12@PEAVWidget@MyGUI@@@Z endp

; SquadManagementScreen::SquadCellView::SquadCellView(class MyGUI::Widget *);
??0SquadCellView@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+0*8]
??0SquadCellView@SquadManagementScreen@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@SquadCellView@SquadManagementScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@SquadCellView@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::SquadCellView::~SquadCellView();
??1SquadCellView@SquadManagementScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+1*8]
??1SquadCellView@SquadManagementScreen@@UEAA@XZ endp

; SquadManagementScreen::SquadCellView::update(const struct MyGUI::IBDrawItemInfo &, class SquadManagementScreen::SquadData *);
?update@SquadCellView@SquadManagementScreen@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVSquadData@2@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+2*8]
?update@SquadCellView@SquadManagementScreen@@QEAAXAEBUIBDrawItemInfo@MyGUI@@PEAVSquadData@2@@Z endp

; SquadManagementScreen::SquadCellView::updateSquadSize();
?updateSquadSize@SquadCellView@SquadManagementScreen@@QEAAXXZ proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+3*8]
?updateSquadSize@SquadCellView@SquadManagementScreen@@QEAAXXZ endp

; SquadManagementScreen::SquadCellView::getCellDimension(class MyGUI::Widget *, struct MyGUI::types::TCoord<int> &, bool);
?getCellDimension@SquadCellView@SquadManagementScreen@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@4@_N@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+4*8]
?getCellDimension@SquadCellView@SquadManagementScreen@@SAXPEAVWidget@MyGUI@@AEAU?$TCoord@H@types@4@_N@Z endp

; SquadManagementScreen::SquadCellView::onNameChanged(class MyGUI::EditBox *);
?onNameChanged@SquadCellView@SquadManagementScreen@@QEAAXPEAVEditBox@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+5*8]
?onNameChanged@SquadCellView@SquadManagementScreen@@QEAAXPEAVEditBox@MyGUI@@@Z endp

; SquadManagementScreen::SquadCellView::onRemove(class MyGUI::Widget *);
?onRemove@SquadCellView@SquadManagementScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_SquadManagementScreen_SquadCellView_base+6*8]
?onRemove@SquadCellView@SquadManagementScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp
