
; static_functions::showErrorMessage();
?showErrorMessage@@YAXXZ proc EXPORT
jmp function_pointers[_static_functions_base+0*8]
?showErrorMessage@@YAXXZ endp

; static_functions::modMedicalSkill(float, class Item *, float);
?modMedicalSkill@@YAMMPEAVItem@@M@Z proc EXPORT
jmp function_pointers[_static_functions_base+1*8]
?modMedicalSkill@@YAMMPEAVItem@@M@Z endp

; static_functions::loadPhysXResource(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, int);
?loadPhysXResource@@YAPEAVNxuPhysicsCollection@NXU@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z proc EXPORT
jmp function_pointers[_static_functions_base+2*8]
?loadPhysXResource@@YAPEAVNxuPhysicsCollection@NXU@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z endp

; static_functions::NXU::scaleCopyCollection(const class NXU::NxuPhysicsCollection *, const char *, const class NxVec3 &, class NxPhysicsSDK *);
?scaleCopyCollection@NXU@@YAPEAVNxuPhysicsCollection@1@PEBV21@PEBDAEBVNxVec3@@PEAVNxPhysicsSDK@@@Z proc EXPORT
jmp function_pointers[_static_functions_base+3*8]
?scaleCopyCollection@NXU@@YAPEAVNxuPhysicsCollection@1@PEBV21@PEBDAEBVNxVec3@@PEAVNxPhysicsSDK@@@Z endp

; static_functions::getFoliageRotation(class FoliageSystem::EntData *, float, float, class Ogre::Quaternion &);
?getFoliageRotation@@YAXPEAVEntData@FoliageSystem@@MMAEAVQuaternion@Ogre@@@Z proc EXPORT
jmp function_pointers[_static_functions_base+4*8]
?getFoliageRotation@@YAXPEAVEntData@FoliageSystem@@MMAEAVQuaternion@Ogre@@@Z endp
