
?_CONSTRUCTOR@StorageBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@StorageBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; StorageBuilding::StorageBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0StorageBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+0*8]
??0StorageBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@StorageBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@StorageBuilding@@QEAAXXZ endp

; StorageBuilding::~StorageBuilding();
??1StorageBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+1*8]
??1StorageBuilding@@UEAA@XZ endp

?_NV_getFunctionStuff@StorageBuilding@@QEAAPEAV1@XZ proc EXPORT
?_NV_getFunctionStuff@StorageBuilding@@QEAAPEAV1@XZ endp

; StorageBuilding::getFunctionStuff();
?getFunctionStuff@StorageBuilding@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+2*8]
?getFunctionStuff@StorageBuilding@@UEAAPEAV1@XZ endp

?_NV_getUseableStuff@StorageBuilding@@QEAAPEAVUseableStuff@@XZ proc EXPORT
?_NV_getUseableStuff@StorageBuilding@@QEAAPEAVUseableStuff@@XZ endp

; StorageBuilding::getUseableStuff();
?getUseableStuff@StorageBuilding@@UEAAPEAVUseableStuff@@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+3*8]
?getUseableStuff@StorageBuilding@@UEAAPEAVUseableStuff@@XZ endp

?_NV_update@StorageBuilding@@QEAAXXZ proc EXPORT
?_NV_update@StorageBuilding@@QEAAXXZ endp

; StorageBuilding::update();
?update@StorageBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+4*8]
?update@StorageBuilding@@UEAAXXZ endp

?_NV_getDefaultTask@StorageBuilding@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@StorageBuilding@@QEAA?AW4TaskType@@XZ endp

; StorageBuilding::getDefaultTask();
?getDefaultTask@StorageBuilding@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+5*8]
?getDefaultTask@StorageBuilding@@UEAA?AW4TaskType@@XZ endp

?_NV_getItemsWeWantRidOf@StorageBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z proc EXPORT
?_NV_getItemsWeWantRidOf@StorageBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z endp

; StorageBuilding::getItemsWeWantRidOf(class lektor<GameData *> &, bool);
?getItemsWeWantRidOf@StorageBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+6*8]
?getItemsWeWantRidOf@StorageBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@_N@Z endp

?_NV_getProductionItemData@StorageBuilding@@QEAAPEAVGameData@@XZ proc EXPORT
?_NV_getProductionItemData@StorageBuilding@@QEAAPEAVGameData@@XZ endp

; StorageBuilding::getProductionItemData();
?getProductionItemData@StorageBuilding@@UEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+7*8]
?getProductionItemData@StorageBuilding@@UEAAPEAVGameData@@XZ endp

; StorageBuilding::getProductionItem();
?getProductionItem@StorageBuilding@@QEBAPEAVConsumptionItem@1@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+8*8]
?getProductionItem@StorageBuilding@@QEBAPEAVConsumptionItem@1@XZ endp

?_NV_getCurrentProductionQuantity@StorageBuilding@@QEAAHXZ proc EXPORT
?_NV_getCurrentProductionQuantity@StorageBuilding@@QEAAHXZ endp

; StorageBuilding::getCurrentProductionQuantity();
?getCurrentProductionQuantity@StorageBuilding@@UEAAHXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+9*8]
?getCurrentProductionQuantity@StorageBuilding@@UEAAHXZ endp

?_NV_canHaveSomeOfThese@StorageBuilding@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_canHaveSomeOfThese@StorageBuilding@@QEAA_NPEAVGameData@@@Z endp

; StorageBuilding::canHaveSomeOfThese(class GameData *);
?canHaveSomeOfThese@StorageBuilding@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+10*8]
?canHaveSomeOfThese@StorageBuilding@@UEAA_NPEAVGameData@@@Z endp

?_NV_getResourcesNeededBecauseEmpty@StorageBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
?_NV_getResourcesNeededBecauseEmpty@StorageBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; StorageBuilding::getResourcesNeededBecauseEmpty(class lektor<GameData *> &);
?getResourcesNeededBecauseEmpty@StorageBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+11*8]
?getResourcesNeededBecauseEmpty@StorageBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

?_NV_getResourcesNeededBecauseNotFull@StorageBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
?_NV_getResourcesNeededBecauseNotFull@StorageBuilding@@QEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

; StorageBuilding::getResourcesNeededBecauseNotFull(class lektor<GameData *> &);
?getResourcesNeededBecauseNotFull@StorageBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+12*8]
?getResourcesNeededBecauseNotFull@StorageBuilding@@UEAAXAEAV?$lektor@PEAVGameData@@@@@Z endp

?_NV_isAnyInputsEmpty@StorageBuilding@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsEmpty@StorageBuilding@@QEBA_NXZ endp

; StorageBuilding::isAnyInputsEmpty();
?isAnyInputsEmpty@StorageBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+13*8]
?isAnyInputsEmpty@StorageBuilding@@UEBA_NXZ endp

?_NV_isAnyInputsFull@StorageBuilding@@QEAA_NXZ proc EXPORT
?_NV_isAnyInputsFull@StorageBuilding@@QEAA_NXZ endp

; StorageBuilding::isAnyInputsFull();
?isAnyInputsFull@StorageBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+14*8]
?isAnyInputsFull@StorageBuilding@@UEAA_NXZ endp

?_NV_isProductionFull@StorageBuilding@@QEAA_NXZ proc EXPORT
?_NV_isProductionFull@StorageBuilding@@QEAA_NXZ endp

; StorageBuilding::isProductionFull();
?isProductionFull@StorageBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+15*8]
?isProductionFull@StorageBuilding@@UEAA_NXZ endp

?_NV_isProductionEmpty@StorageBuilding@@QEAA_NXZ proc EXPORT
?_NV_isProductionEmpty@StorageBuilding@@QEAA_NXZ endp

; StorageBuilding::isProductionEmpty();
?isProductionEmpty@StorageBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+16*8]
?isProductionEmpty@StorageBuilding@@UEAA_NXZ endp

?_NV_getNumConsumtionItems@StorageBuilding@@QEBAHXZ proc EXPORT
?_NV_getNumConsumtionItems@StorageBuilding@@QEBAHXZ endp

; StorageBuilding::getNumConsumtionItems();
?getNumConsumtionItems@StorageBuilding@@UEBAHXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+17*8]
?getNumConsumtionItems@StorageBuilding@@UEBAHXZ endp

?_NV_getConsumtionItems@StorageBuilding@@QEAAPEAVConsumptionItem@1@H@Z proc EXPORT
?_NV_getConsumtionItems@StorageBuilding@@QEAAPEAVConsumptionItem@1@H@Z endp

; StorageBuilding::getConsumtionItems(int);
?getConsumtionItems@StorageBuilding@@UEAAPEAVConsumptionItem@1@H@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+18*8]
?getConsumtionItems@StorageBuilding@@UEAAPEAVConsumptionItem@1@H@Z endp

; StorageBuilding::getConsumtionItems_inStock(class lektor<StorageBuilding::ConsumptionItem *> &);
?getConsumtionItems_inStock@StorageBuilding@@QEAAXAEAV?$lektor@PEAVConsumptionItem@StorageBuilding@@@@@Z proc EXPORT
jmp function_pointers[_StorageBuilding_base+19*8]
?getConsumtionItems_inStock@StorageBuilding@@QEAAXAEAV?$lektor@PEAVConsumptionItem@StorageBuilding@@@@@Z endp

; StorageBuilding::limitedByType();
?limitedByType@StorageBuilding@@QEBA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+20*8]
?limitedByType@StorageBuilding@@QEBA_NXZ endp

?_NV_updateInventoryWindow@StorageBuilding@@QEAAXXZ proc EXPORT
?_NV_updateInventoryWindow@StorageBuilding@@QEAAXXZ endp

; StorageBuilding::updateInventoryWindow();
?updateInventoryWindow@StorageBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_StorageBuilding_base+21*8]
?updateInventoryWindow@StorageBuilding@@UEAAXXZ endp
