
?_CONSTRUCTOR@ConsumptionItem@StorageBuilding@@QEAAPEAV12@MPEAVGameData@@PEAVInventorySection@@H@Z proc EXPORT
?_CONSTRUCTOR@ConsumptionItem@StorageBuilding@@QEAAPEAV12@MPEAVGameData@@PEAVInventorySection@@H@Z endp

; StorageBuilding::ConsumptionItem::ConsumptionItem(float, class GameData *, class InventorySection *, int);
??0ConsumptionItem@StorageBuilding@@QEAA@MPEAVGameData@@PEAVInventorySection@@H@Z proc EXPORT
jmp function_pointers[_StorageBuilding_ConsumptionItem_base+0*8]
??0ConsumptionItem@StorageBuilding@@QEAA@MPEAVGameData@@PEAVInventorySection@@H@Z endp

?_CONSTRUCTOR@ConsumptionItem@StorageBuilding@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ConsumptionItem@StorageBuilding@@QEAAPEAV12@XZ endp

; StorageBuilding::ConsumptionItem::ConsumptionItem();
??0ConsumptionItem@StorageBuilding@@QEAA@XZ proc EXPORT
jmp function_pointers[_StorageBuilding_ConsumptionItem_base+1*8]
??0ConsumptionItem@StorageBuilding@@QEAA@XZ endp

; StorageBuilding::ConsumptionItem::isFull();
?isFull@ConsumptionItem@StorageBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_ConsumptionItem_base+2*8]
?isFull@ConsumptionItem@StorageBuilding@@QEAA_NXZ endp

; StorageBuilding::ConsumptionItem::isEmpty();
?isEmpty@ConsumptionItem@StorageBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_StorageBuilding_ConsumptionItem_base+3*8]
?isEmpty@ConsumptionItem@StorageBuilding@@QEAA_NXZ endp
