
?_CONSTRUCTOR@StringPair@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
?_CONSTRUCTOR@StringPair@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; StringPair::StringPair(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0StringPair@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_StringPair_base+0*8]
??0StringPair@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

?_CONSTRUCTOR@StringPair@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@StringPair@@QEAAPEAV1@AEBV1@@Z endp

; StringPair::StringPair(const class StringPair &);
??0StringPair@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_StringPair_base+1*8]
??0StringPair@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@StringPair@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@StringPair@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; StringPair::StringPair(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0StringPair@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_StringPair_base+2*8]
??0StringPair@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_CONSTRUCTOR@StringPair@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@StringPair@@QEAAPEAV1@XZ endp

; StringPair::StringPair();
??0StringPair@@QEAA@XZ proc EXPORT
jmp function_pointers[_StringPair_base+3*8]
??0StringPair@@QEAA@XZ endp

?_DESTRUCTOR@StringPair@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@StringPair@@QEAAXXZ endp

; StringPair::~StringPair();
??1StringPair@@UEAA@XZ proc EXPORT
jmp function_pointers[_StringPair_base+4*8]
??1StringPair@@UEAA@XZ endp

?_NV_operator_assign@StringPair@@QEAAAEBV1@AEBV1@@Z proc EXPORT
?_NV_operator_assign@StringPair@@QEAAAEBV1@AEBV1@@Z endp

; StringPair::operator=(const class StringPair &);
??4StringPair@@UEAAAEBV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_StringPair_base+5*8]
??4StringPair@@UEAAAEBV0@AEBV0@@Z endp
