
?_CONSTRUCTOR@Sword@@QEAAPEAV1@PEAVGameData@@00Vhand@@H@Z proc EXPORT
?_CONSTRUCTOR@Sword@@QEAAPEAV1@PEAVGameData@@00Vhand@@H@Z endp

; Sword::Sword(class GameData *, class GameData *, class GameData *, class hand, int);
??0Sword@@QEAA@PEAVGameData@@00Vhand@@H@Z proc EXPORT
jmp function_pointers[_Sword_base+0*8]
??0Sword@@QEAA@PEAVGameData@@00Vhand@@H@Z endp

?_NV_getClassType@Sword@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getClassType@Sword@@QEBA?AW4itemType@@XZ endp

; Sword::getClassType();
?getClassType@Sword@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Sword_base+1*8]
?getClassType@Sword@@UEBA?AW4itemType@@XZ endp

?_NV_isSword@Sword@@QEAAPEAV1@XZ proc EXPORT
?_NV_isSword@Sword@@QEAAPEAV1@XZ endp

; Sword::isSword();
?isSword@Sword@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Sword_base+2*8]
?isSword@Sword@@UEAAPEAV1@XZ endp

; Sword::setupStats(int, class GameData *, class GameData *, class GameData *);
?setupStats@Sword@@QEAAXHPEAVGameData@@00@Z proc EXPORT
jmp function_pointers[_Sword_base+3*8]
?setupStats@Sword@@QEAAXHPEAVGameData@@00@Z endp

?_NV_getTooltipData1@Sword@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData1@Sword@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Sword::getTooltipData1(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData1@Sword@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Sword_base+4*8]
?getTooltipData1@Sword@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getTooltipData2@Sword@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
?_NV_getTooltipData2@Sword@@QEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

; Sword::getTooltipData2(class std::vector<StringPair,Ogre::STLAllocator<StringPair,Ogre::CategorisedAllocPolicy<0> > > &);
?getTooltipData2@Sword@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z proc EXPORT
jmp function_pointers[_Sword_base+5*8]
?getTooltipData2@Sword@@UEAAXAEAV?$vector@VStringPair@@V?$STLAllocator@VStringPair@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@@Z endp

?_NV_getSkillModIndoors@Sword@@QEBAHXZ proc EXPORT
?_NV_getSkillModIndoors@Sword@@QEBAHXZ endp

; Sword::getSkillModIndoors();
?getSkillModIndoors@Sword@@UEBAHXZ proc EXPORT
jmp function_pointers[_Sword_base+6*8]
?getSkillModIndoors@Sword@@UEBAHXZ endp

?_DESTRUCTOR@Sword@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Sword@@QEAAXXZ endp

; Sword::~Sword();
??1Sword@@UEAA@XZ proc EXPORT
jmp function_pointers[_Sword_base+7*8]
??1Sword@@UEAA@XZ endp
