
?_CONSTRUCTOR@TaskData@@QEAAPEAV1@W4TaskType@@P8AI@@EAAMAEBVhand@@AEBVVector3@Ogre@@@Z_N4@Z proc EXPORT
?_CONSTRUCTOR@TaskData@@QEAAPEAV1@W4TaskType@@P8AI@@EAAMAEBVhand@@AEBVVector3@Ogre@@@Z_N4@Z endp

; TaskData::TaskData(enum TaskType, function  *, bool, bool);
??0TaskData@@QEAA@W4TaskType@@P8AI@@EAAMAEBVhand@@AEBVVector3@Ogre@@@Z_N4@Z proc EXPORT
jmp function_pointers[_TaskData_base+0*8]
??0TaskData@@QEAA@W4TaskType@@P8AI@@EAAMAEBVhand@@AEBVVector3@Ogre@@@Z_N4@Z endp

; TaskData::addResult(enum StateType, bool, bool);
?addResult@TaskData@@QEAAXW4StateType@@_N1@Z proc EXPORT
jmp function_pointers[_TaskData_base+1*8]
?addResult@TaskData@@QEAAXW4StateType@@_N1@Z endp

; TaskData::addRequirement(enum StateType, bool, bool);
?addRequirement@TaskData@@QEAAXW4StateType@@_N1@Z proc EXPORT
jmp function_pointers[_TaskData_base+2*8]
?addRequirement@TaskData@@QEAAXW4StateType@@_N1@Z endp

; TaskData::setCharacteristics(float, float, float, bool);
?setCharacteristics@TaskData@@QEAAXMMM_N@Z proc EXPORT
jmp function_pointers[_TaskData_base+3*8]
?setCharacteristics@TaskData@@QEAAXMMM_N@Z endp

; TaskData::setInfrequentGoalChecks();
?setInfrequentGoalChecks@TaskData@@QEAAXXZ proc EXPORT
jmp function_pointers[_TaskData_base+4*8]
?setInfrequentGoalChecks@TaskData@@QEAAXXZ endp

; TaskData::setAlertnessMult(float);
?setAlertnessMult@TaskData@@QEAAXM@Z proc EXPORT
jmp function_pointers[_TaskData_base+5*8]
?setAlertnessMult@TaskData@@QEAAXM@Z endp

; TaskData::setRequirementsCantEndActionPrematurely(bool);
?setRequirementsCantEndActionPrematurely@TaskData@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_TaskData_base+6*8]
?setRequirementsCantEndActionPrematurely@TaskData@@QEAAX_N@Z endp

; TaskData::setCopyMeInfluence(float);
?setCopyMeInfluence@TaskData@@QEAAXM@Z proc EXPORT
jmp function_pointers[_TaskData_base+7*8]
?setCopyMeInfluence@TaskData@@QEAAXM@Z endp

; TaskData::setFollowMeWeight(float);
?setFollowMeWeight@TaskData@@QEAAXM@Z proc EXPORT
jmp function_pointers[_TaskData_base+8*8]
?setFollowMeWeight@TaskData@@QEAAXM@Z endp

; TaskData::setSelfRegulation(bool, bool);
?setSelfRegulation@TaskData@@QEAAX_N0@Z proc EXPORT
jmp function_pointers[_TaskData_base+9*8]
?setSelfRegulation@TaskData@@QEAAX_N0@Z endp

; TaskData::setDurationBased(float, float, bool);
?setDurationBased@TaskData@@QEAAXMM_N@Z proc EXPORT
jmp function_pointers[_TaskData_base+10*8]
?setDurationBased@TaskData@@QEAAXMM_N@Z endp

; TaskData::hasInfrequentGoalChecks();
?hasInfrequentGoalChecks@TaskData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TaskData_base+11*8]
?hasInfrequentGoalChecks@TaskData@@QEBA_NXZ endp

; TaskData::getRequirementsCantEndActionPrematurely();
?getRequirementsCantEndActionPrematurely@TaskData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TaskData_base+12*8]
?getRequirementsCantEndActionPrematurely@TaskData@@QEBA_NXZ endp

; TaskData::setPermaJob(enum PermajobType, bool, enum TaskType, enum TaskType);
?setPermaJob@TaskData@@QEAAXW4PermajobType@@_NW4TaskType@@2@Z proc EXPORT
jmp function_pointers[_TaskData_base+13*8]
?setPermaJob@TaskData@@QEAAXW4PermajobType@@_NW4TaskType@@2@Z endp

; TaskData::getPermaJobType();
?getPermaJobType@TaskData@@QEBA?AW4PermajobType@@XZ proc EXPORT
jmp function_pointers[_TaskData_base+14*8]
?getPermaJobType@TaskData@@QEBA?AW4PermajobType@@XZ endp

; TaskData::isPermaJob();
?isPermaJob@TaskData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TaskData_base+15*8]
?isPermaJob@TaskData@@QEBA_NXZ endp

; TaskData::isPermaJobFixedTarget();
?isPermaJobFixedTarget@TaskData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TaskData_base+16*8]
?isPermaJobFixedTarget@TaskData@@QEBA_NXZ endp

; TaskData::getPermaJobAssociation();
?getPermaJobAssociation@TaskData@@QEBA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_TaskData_base+17*8]
?getPermaJobAssociation@TaskData@@QEBA?AW4TaskType@@XZ endp

; TaskData::getPermaJobAssociation_secondary();
?getPermaJobAssociation_secondary@TaskData@@QEBA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_TaskData_base+18*8]
?getPermaJobAssociation_secondary@TaskData@@QEBA?AW4TaskType@@XZ endp

; TaskData::isResultsComplete(class AI *, const class hand &, const class hand &, const class Ogre::Vector3 &);
?isResultsComplete@TaskData@@QEAA_NPEAVAI@@AEBVhand@@1AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TaskData_base+19*8]
?isResultsComplete@TaskData@@QEAA_NPEAVAI@@AEBVhand@@1AEBVVector3@Ogre@@@Z endp

; TaskData::isResultsComplete_ignoreSubtasker(class AI *, const class hand &, const class hand &, const class Ogre::Vector3 &);
?isResultsComplete_ignoreSubtasker@TaskData@@QEAA_NPEAVAI@@AEBVhand@@1AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TaskData_base+20*8]
?isResultsComplete_ignoreSubtasker@TaskData@@QEAA_NPEAVAI@@AEBVhand@@1AEBVVector3@Ogre@@@Z endp

; TaskData::getRequirementComplaint(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class AI *, const class hand &, const class Ogre::Vector3 &, const class hand &, bool);
?getRequirementComplaint@TaskData@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAI@@AEBVhand@@AEBVVector3@Ogre@@2_N@Z proc EXPORT
jmp function_pointers[_TaskData_base+21*8]
?getRequirementComplaint@TaskData@@QEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVAI@@AEBVhand@@AEBVVector3@Ogre@@2_N@Z endp

; TaskData::_isRequirementsComplete(class AI *, const class hand &, const class Ogre::Vector3 &, class hand &, bool, enum StateType &);
?_isRequirementsComplete@TaskData@@QEAA_NPEAVAI@@AEBVhand@@AEBVVector3@Ogre@@AEAV3@_NAEAW4StateType@@@Z proc EXPORT
jmp function_pointers[_TaskData_base+22*8]
?_isRequirementsComplete@TaskData@@QEAA_NPEAVAI@@AEBVhand@@AEBVVector3@Ogre@@AEAV3@_NAEAW4StateType@@@Z endp

; TaskData::isRequirementComplete(class AI *, const class hand &, int, const class Ogre::Vector3 &);
?isRequirementComplete@TaskData@@QEAA_NPEAVAI@@AEBVhand@@HAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TaskData_base+23*8]
?isRequirementComplete@TaskData@@QEAA_NPEAVAI@@AEBVhand@@HAEBVVector3@Ogre@@@Z endp

; TaskData::setTargetingFunction(function  *, bool);
?setTargetingFunction@TaskData@@QEAAXP8AI@@EAAMAEBVhand@@AEAV3@_N@Z2@Z proc EXPORT
jmp function_pointers[_TaskData_base+24*8]
?setTargetingFunction@TaskData@@QEAAXP8AI@@EAAMAEBVhand@@AEAV3@_N@Z2@Z endp

; TaskData::isTargetFinder();
?isTargetFinder@TaskData@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TaskData_base+25*8]
?isTargetFinder@TaskData@@QEBA_NXZ endp

; TaskData::setSubTask(enum StateType, bool);
?setSubTask@TaskData@@QEAAXW4StateType@@_N@Z proc EXPORT
jmp function_pointers[_TaskData_base+26*8]
?setSubTask@TaskData@@QEAAXW4StateType@@_N@Z endp

; TaskData::setDialogueDeliveryTag(enum EventTriggerEnum);
?setDialogueDeliveryTag@TaskData@@QEAAXW4EventTriggerEnum@@@Z proc EXPORT
jmp function_pointers[_TaskData_base+27*8]
?setDialogueDeliveryTag@TaskData@@QEAAXW4EventTriggerEnum@@@Z endp

; TaskData::runTargetFind(class AI *, const class hand &, class hand &, bool);
?runTargetFind@TaskData@@QEAAMPEAVAI@@AEBVhand@@AEAV3@_N@Z proc EXPORT
jmp function_pointers[_TaskData_base+28*8]
?runTargetFind@TaskData@@QEAAMPEAVAI@@AEBVhand@@AEAV3@_N@Z endp

; TaskData::_targetsRemaining(class AI *, const class hand &);
?_targetsRemaining@TaskData@@QEAA_NPEAVAI@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_TaskData_base+29*8]
?_targetsRemaining@TaskData@@QEAA_NPEAVAI@@AEBVhand@@@Z endp
