
?_CONSTRUCTOR@TaskStateData@@QEAAPEAV1@W4StateType@@_N1@Z proc EXPORT
?_CONSTRUCTOR@TaskStateData@@QEAAPEAV1@W4StateType@@_N1@Z endp

; TaskStateData::TaskStateData(enum StateType, bool, bool);
??0TaskStateData@@QEAA@W4StateType@@_N1@Z proc EXPORT
jmp function_pointers[_TaskStateData_base+0*8]
??0TaskStateData@@QEAA@W4StateType@@_N1@Z endp

?_CONSTRUCTOR@TaskStateData@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TaskStateData@@QEAAPEAV1@XZ endp

; TaskStateData::TaskStateData();
??0TaskStateData@@QEAA@XZ proc EXPORT
jmp function_pointers[_TaskStateData_base+1*8]
??0TaskStateData@@QEAA@XZ endp
