
?_CONSTRUCTOR@ThreadWannabe@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@ThreadWannabe@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ThreadWannabe::ThreadWannabe(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0ThreadWannabe@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ThreadWannabe_base+0*8]
??0ThreadWannabe@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ThreadWannabe::isPaused();
?isPaused@ThreadWannabe@@QEAA_NXZ proc EXPORT
jmp function_pointers[_ThreadWannabe_base+1*8]
?isPaused@ThreadWannabe@@QEAA_NXZ endp

; ThreadWannabe::setPaused(bool, float);
?setPaused@ThreadWannabe@@QEAAX_NM@Z proc EXPORT
jmp function_pointers[_ThreadWannabe_base+2*8]
?setPaused@ThreadWannabe@@QEAAX_NM@Z endp

?_NV_threadProc@ThreadWannabe@@QEAAKXZ proc EXPORT
?_NV_threadProc@ThreadWannabe@@QEAAKXZ endp

; ThreadWannabe::threadProc();
?threadProc@ThreadWannabe@@UEAAKXZ proc EXPORT
jmp function_pointers[_ThreadWannabe_base+3*8]
?threadProc@ThreadWannabe@@UEAAKXZ endp

?_NV_forceLoopMT@ThreadWannabe@@QEAAXXZ proc EXPORT
?_NV_forceLoopMT@ThreadWannabe@@QEAAXXZ endp

; ThreadWannabe::forceLoopMT();
?forceLoopMT@ThreadWannabe@@UEAAXXZ proc EXPORT
jmp function_pointers[_ThreadWannabe_base+4*8]
?forceLoopMT@ThreadWannabe@@UEAAXXZ endp

?_DESTRUCTOR@ThreadWannabe@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ThreadWannabe@@QEAAXXZ endp

; ThreadWannabe::~ThreadWannabe();
??1ThreadWannabe@@UEAA@XZ proc EXPORT
jmp function_pointers[_ThreadWannabe_base+5*8]
??1ThreadWannabe@@UEAA@XZ endp
