
?_CONSTRUCTOR@TimeOfDay@@QEAAPEAV1@N@Z proc EXPORT
?_CONSTRUCTOR@TimeOfDay@@QEAAPEAV1@N@Z endp

; TimeOfDay::TimeOfDay(double);
??0TimeOfDay@@QEAA@N@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+0*8]
??0TimeOfDay@@QEAA@N@Z endp

?_CONSTRUCTOR@TimeOfDay@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TimeOfDay@@QEAAPEAV1@XZ endp

; TimeOfDay::TimeOfDay();
??0TimeOfDay@@QEAA@XZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+1*8]
??0TimeOfDay@@QEAA@XZ endp

; TimeOfDay::setNull();
?setNull@TimeOfDay@@QEAAXXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+2*8]
?setNull@TimeOfDay@@QEAAXXZ endp

; TimeOfDay::isUnset();
?isUnset@TimeOfDay@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+3*8]
?isUnset@TimeOfDay@@QEBA_NXZ endp

; TimeOfDay::setTime(double);
?setTime@TimeOfDay@@QEAAXN@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+4*8]
?setTime@TimeOfDay@@QEAAXN@Z endp

; TimeOfDay::addHours(double);
?addHours@TimeOfDay@@QEAAXN@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+5*8]
?addHours@TimeOfDay@@QEAAXN@Z endp

; TimeOfDay::addMinutes(double);
?addMinutes@TimeOfDay@@QEAAXN@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+6*8]
?addMinutes@TimeOfDay@@QEAAXN@Z endp

; TimeOfDay::operator>(const class TimeOfDay &);
??OTimeOfDay@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+7*8]
??OTimeOfDay@@QEBA_NAEBV0@@Z endp

; TimeOfDay::operator>=(const class TimeOfDay &);
??PTimeOfDay@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+8*8]
??PTimeOfDay@@QEBA_NAEBV0@@Z endp

; TimeOfDay::operator<(const class TimeOfDay &);
??MTimeOfDay@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+9*8]
??MTimeOfDay@@QEBA_NAEBV0@@Z endp

; TimeOfDay::operator<=(const class TimeOfDay &);
??NTimeOfDay@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+10*8]
??NTimeOfDay@@QEBA_NAEBV0@@Z endp

; TimeOfDay::operator==(const class TimeOfDay &);
??8TimeOfDay@@QEBA_NAEBV0@@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+11*8]
??8TimeOfDay@@QEBA_NAEBV0@@Z endp

; TimeOfDay::operator=(const class TimeOfDay &);
??4TimeOfDay@@QEAAAEBV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+12*8]
??4TimeOfDay@@QEAAAEBV0@AEBV0@@Z endp

; TimeOfDay::getTotalHours();
?getTotalHours@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+13*8]
?getTotalHours@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getTotalMinutes();
?getTotalMinutes@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+14*8]
?getTotalMinutes@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getTotalSeconds();
?getTotalSeconds@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+15*8]
?getTotalSeconds@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getRealLifeSeconds();
?getRealLifeSeconds@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+16*8]
?getRealLifeSeconds@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getRealLifeSecondsPassed();
?getRealLifeSecondsPassed@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+17*8]
?getRealLifeSecondsPassed@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getTotalDays();
?getTotalDays@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+18*8]
?getTotalDays@TimeOfDay@@QEBANXZ endp

; TimeOfDay::stampTime();
?stampTime@TimeOfDay@@QEAAXXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+19*8]
?stampTime@TimeOfDay@@QEAAXXZ endp

; TimeOfDay::getHoursPassed();
?getHoursPassed@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+20*8]
?getHoursPassed@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getMinutesPassed();
?getMinutesPassed@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+21*8]
?getMinutesPassed@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getSecondsPassed();
?getSecondsPassed@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+22*8]
?getSecondsPassed@TimeOfDay@@QEBANXZ endp

; TimeOfDay::timeOfDayHasPassed(double);
?timeOfDayHasPassed@TimeOfDay@@QEBA_NN@Z proc EXPORT
jmp function_pointers[_TimeOfDay_base+23*8]
?timeOfDayHasPassed@TimeOfDay@@QEBA_NN@Z endp

; TimeOfDay::timePassed();
?timePassed@TimeOfDay@@QEBANXZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+24*8]
?timePassed@TimeOfDay@@QEBANXZ endp

; TimeOfDay::getTimePassedString();
?getTimePassedString@TimeOfDay@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+25*8]
?getTimePassedString@TimeOfDay@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; TimeOfDay::getTimeRemainingString();
?getTimeRemainingString@TimeOfDay@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+26*8]
?getTimeRemainingString@TimeOfDay@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; TimeOfDay::getTotalTimeString();
?getTotalTimeString@TimeOfDay@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TimeOfDay_base+27*8]
?getTotalTimeString@TimeOfDay@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp
