
; TitleScreen::getSingleton();
?getSingleton@TitleScreen@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_TitleScreen_base+0*8]
?getSingleton@TitleScreen@@SAPEAV1@XZ endp

?_CONSTRUCTOR@TitleScreen@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TitleScreen@@QEAAPEAV1@XZ endp

; TitleScreen::TitleScreen();
??0TitleScreen@@QEAA@XZ proc EXPORT
jmp function_pointers[_TitleScreen_base+1*8]
??0TitleScreen@@QEAA@XZ endp

?_DESTRUCTOR@TitleScreen@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TitleScreen@@QEAAXXZ endp

; TitleScreen::~TitleScreen();
??1TitleScreen@@UEAA@XZ proc EXPORT
jmp function_pointers[_TitleScreen_base+2*8]
??1TitleScreen@@UEAA@XZ endp

?_NV_clear@TitleScreen@@QEAAXXZ proc EXPORT
?_NV_clear@TitleScreen@@QEAAXXZ endp

; TitleScreen::clear();
?clear@TitleScreen@@UEAAXXZ proc EXPORT
jmp function_pointers[_TitleScreen_base+3*8]
?clear@TitleScreen@@UEAAXXZ endp

?_NV_show@TitleScreen@@QEAAX_N@Z proc EXPORT
?_NV_show@TitleScreen@@QEAAX_N@Z endp

; TitleScreen::show(bool);
?show@TitleScreen@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+4*8]
?show@TitleScreen@@UEAAX_N@Z endp

?_NV_update@TitleScreen@@QEAAXXZ proc EXPORT
?_NV_update@TitleScreen@@QEAAXXZ endp

; TitleScreen::update();
?update@TitleScreen@@UEAAXXZ proc EXPORT
jmp function_pointers[_TitleScreen_base+5*8]
?update@TitleScreen@@UEAAXXZ endp

; TitleScreen::closeTheOtherBits();
?closeTheOtherBits@TitleScreen@@QEAA_NXZ proc EXPORT
jmp function_pointers[_TitleScreen_base+6*8]
?closeTheOtherBits@TitleScreen@@QEAA_NXZ endp

; TitleScreen::loadGame(class MyGUI::Widget *);
?loadGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+7*8]
?loadGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TitleScreen::importGame(class MyGUI::Widget *);
?importGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+8*8]
?importGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TitleScreen::showOptions(class MyGUI::Widget *);
?showOptions@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+9*8]
?showOptions@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TitleScreen::credits(class MyGUI::Widget *);
?credits@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+10*8]
?credits@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TitleScreen::exitGame(class MyGUI::Widget *);
?exitGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+11*8]
?exitGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TitleScreen::continueGame(class MyGUI::Widget *);
?continueGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+12*8]
?continueGame@TitleScreen@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TitleScreen::hover(class MyGUI::Widget *, class MyGUI::Widget *);
?hover@TitleScreen@@QEAAXPEAVWidget@MyGUI@@0@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+13*8]
?hover@TitleScreen@@QEAAXPEAVWidget@MyGUI@@0@Z endp

; TitleScreen::setCreditsVisible(bool);
?setCreditsVisible@TitleScreen@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_TitleScreen_base+14*8]
?setCreditsVisible@TitleScreen@@QEAAX_N@Z endp
