
?_CONSTRUCTOR@ToolTipStatic@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@ToolTipStatic@@QEAAPEAV1@PEAVWidget@MyGUI@@@Z endp

; ToolTipStatic::ToolTipStatic(class MyGUI::Widget *);
??0ToolTipStatic@@QEAA@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipStatic_base+0*8]
??0ToolTipStatic@@QEAA@PEAVWidget@MyGUI@@@Z endp

?_DESTRUCTOR@ToolTipStatic@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ToolTipStatic@@QEAAXXZ endp

; ToolTipStatic::~ToolTipStatic();
??1ToolTipStatic@@UEAA@XZ proc EXPORT
jmp function_pointers[_ToolTipStatic_base+1*8]
??1ToolTipStatic@@UEAA@XZ endp

?_NV_update@ToolTipStatic@@QEAAXXZ proc EXPORT
?_NV_update@ToolTipStatic@@QEAAXXZ endp

; ToolTipStatic::update();
?update@ToolTipStatic@@UEAAXXZ proc EXPORT
jmp function_pointers[_ToolTipStatic_base+2*8]
?update@ToolTipStatic@@UEAAXXZ endp

?_NV_clear@ToolTipStatic@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_clear@ToolTipStatic@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipStatic::clear(class MyGUI::Widget *);
?clear@ToolTipStatic@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipStatic_base+3*8]
?clear@ToolTipStatic@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV__setup@ToolTipStatic@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV__setup@ToolTipStatic@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipStatic::_setup(class MyGUI::Widget *);
?_setup@ToolTipStatic@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipStatic_base+4*8]
?_setup@ToolTipStatic@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_setVisible@ToolTipStatic@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@ToolTipStatic@@QEAAX_N@Z endp

; ToolTipStatic::setVisible(bool);
?setVisible@ToolTipStatic@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_ToolTipStatic_base+5*8]
?setVisible@ToolTipStatic@@UEAAX_N@Z endp

?_NV_setPosition@ToolTipStatic@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
?_NV_setPosition@ToolTipStatic@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTipStatic::setPosition(const struct MyGUI::types::TPoint<int> &);
?setPosition@ToolTipStatic@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipStatic_base+6*8]
?setPosition@ToolTipStatic@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTipStatic::mouseMoved(class MyGUI::Widget *, int, int);
?mouseMoved@ToolTipStatic@@QEAAXPEAVWidget@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_ToolTipStatic_base+7*8]
?mouseMoved@ToolTipStatic@@QEAAXPEAVWidget@MyGUI@@HH@Z endp
