
?_CONSTRUCTOR@ToolTipFixed@@QEAAPEAV1@PEAVWidget@MyGUI@@0@Z proc EXPORT
?_CONSTRUCTOR@ToolTipFixed@@QEAAPEAV1@PEAVWidget@MyGUI@@0@Z endp

; ToolTipFixed::ToolTipFixed(class MyGUI::Widget *, class MyGUI::Widget *);
??0ToolTipFixed@@QEAA@PEAVWidget@MyGUI@@0@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+0*8]
??0ToolTipFixed@@QEAA@PEAVWidget@MyGUI@@0@Z endp

?_DESTRUCTOR@ToolTipFixed@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ToolTipFixed@@QEAAXXZ endp

; ToolTipFixed::~ToolTipFixed();
??1ToolTipFixed@@UEAA@XZ proc EXPORT
jmp function_pointers[_ToolTipFixed_base+1*8]
??1ToolTipFixed@@UEAA@XZ endp

?_NV_clear@ToolTipFixed@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_clear@ToolTipFixed@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipFixed::clear(class MyGUI::Widget *);
?clear@ToolTipFixed@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+2*8]
?clear@ToolTipFixed@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_update@ToolTipFixed@@QEAAXXZ proc EXPORT
?_NV_update@ToolTipFixed@@QEAAXXZ endp

; ToolTipFixed::update();
?update@ToolTipFixed@@UEAAXXZ proc EXPORT
jmp function_pointers[_ToolTipFixed_base+3*8]
?update@ToolTipFixed@@UEAAXXZ endp

; ToolTipFixed::setBottomPosition(const struct MyGUI::types::TPoint<int> &);
?setBottomPosition@ToolTipFixed@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+4*8]
?setBottomPosition@ToolTipFixed@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

?_NV_setVisible@ToolTipFixed@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@ToolTipFixed@@QEAAX_N@Z endp

; ToolTipFixed::setVisible(bool);
?setVisible@ToolTipFixed@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+5*8]
?setVisible@ToolTipFixed@@UEAAX_N@Z endp

?_NV_setPosition@ToolTipFixed@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
?_NV_setPosition@ToolTipFixed@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTipFixed::setPosition(const struct MyGUI::types::TPoint<int> &);
?setPosition@ToolTipFixed@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+6*8]
?setPosition@ToolTipFixed@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

?_NV__setup@ToolTipFixed@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV__setup@ToolTipFixed@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipFixed::_setup(class MyGUI::Widget *);
?_setup@ToolTipFixed@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+7*8]
?_setup@ToolTipFixed@@UEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipFixed::mouseMoved(class MyGUI::Widget *, int, int);
?mouseMoved@ToolTipFixed@@QEAAXPEAVWidget@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_ToolTipFixed_base+8*8]
?mouseMoved@ToolTipFixed@@QEAAXPEAVWidget@MyGUI@@HH@Z endp
