
?_CONSTRUCTOR@ToolTipInventory@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ToolTipInventory@@QEAAPEAV1@XZ endp

; ToolTipInventory::ToolTipInventory();
??0ToolTipInventory@@QEAA@XZ proc EXPORT
jmp function_pointers[_ToolTipInventory_base+0*8]
??0ToolTipInventory@@QEAA@XZ endp

?_DESTRUCTOR@ToolTipInventory@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ToolTipInventory@@QEAAXXZ endp

; ToolTipInventory::~ToolTipInventory();
??1ToolTipInventory@@UEAA@XZ proc EXPORT
jmp function_pointers[_ToolTipInventory_base+1*8]
??1ToolTipInventory@@UEAA@XZ endp

?_NV__setup@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV__setup@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipInventory::_setup(class MyGUI::Widget *);
?_setup@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+2*8]
?_setup@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_setup@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_setup@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipInventory::setup(class MyGUI::Widget *);
?setup@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+3*8]
?setup@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_show@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z proc EXPORT
?_NV_show@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z endp

; ToolTipInventory::show(class MyGUI::Widget *, const struct MyGUI::types::TPoint<int> &);
?show@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+4*8]
?show@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z endp

?_NV_update@ToolTipInventory@@QEAAXXZ proc EXPORT
?_NV_update@ToolTipInventory@@QEAAXXZ endp

; ToolTipInventory::update();
?update@ToolTipInventory@@UEAAXXZ proc EXPORT
jmp function_pointers[_ToolTipInventory_base+5*8]
?update@ToolTipInventory@@UEAAXXZ endp

?_NV_setContent@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_setContent@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipInventory::setContent(class MyGUI::Widget *);
?setContent@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+6*8]
?setContent@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_clearData@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_clearData@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipInventory::clearData(class MyGUI::Widget *);
?clearData@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+7*8]
?clearData@ToolTipInventory@@UEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTipInventory::mouseMoved(class MyGUI::Widget *, int, int);
?mouseMoved@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@HH@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+8*8]
?mouseMoved@ToolTipInventory@@QEAAXPEAVWidget@MyGUI@@HH@Z endp

?_NV_setPosition@ToolTipInventory@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
?_NV_setPosition@ToolTipInventory@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTipInventory::setPosition(const struct MyGUI::types::TPoint<int> &);
?setPosition@ToolTipInventory@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipInventory_base+9*8]
?setPosition@ToolTipInventory@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp
