
?_CONSTRUCTOR@ToolTipLine@ToolTip@@QEAAPEAV12@PEAVWidget@MyGUI@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
?_CONSTRUCTOR@ToolTipLine@ToolTip@@QEAAPEAV12@PEAVWidget@MyGUI@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; ToolTip::ToolTipLine::ToolTipLine(class MyGUI::Widget *, float, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0ToolTipLine@ToolTip@@QEAA@PEAVWidget@MyGUI@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_ToolTip_ToolTipLine_base+0*8]
??0ToolTipLine@ToolTip@@QEAA@PEAVWidget@MyGUI@@MAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

?_DESTRUCTOR@ToolTipLine@ToolTip@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ToolTipLine@ToolTip@@QEAAXXZ endp

; ToolTip::ToolTipLine::~ToolTipLine();
??1ToolTipLine@ToolTip@@QEAA@XZ proc EXPORT
jmp function_pointers[_ToolTip_ToolTipLine_base+1*8]
??1ToolTipLine@ToolTip@@QEAA@XZ endp
