
?_CONSTRUCTOR@ToolTip@@QEAAPEAV1@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_CONSTRUCTOR@ToolTip@@QEAAPEAV1@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; ToolTip::ToolTip(class MyGUI::Widget *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
??0ToolTip@@QEAA@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+0*8]
??0ToolTip@@QEAA@PEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_DESTRUCTOR@ToolTip@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ToolTip@@QEAAXXZ endp

; ToolTip::~ToolTip();
??1ToolTip@@UEAA@XZ proc EXPORT
jmp function_pointers[_ToolTip_base+1*8]
??1ToolTip@@UEAA@XZ endp

; ToolTip::setup(class MyGUI::Widget *, const class hand &);
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+2*8]
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBVhand@@@Z endp

; ToolTip::setup(class MyGUI::Widget *, class GameData *);
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+3*8]
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@PEAVGameData@@@Z endp

; ToolTip::setup(class MyGUI::Widget *, const class lektor<StringPair> &);
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+4*8]
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBV?$lektor@VStringPair@@@@@Z endp

; ToolTip::setup(class MyGUI::Widget *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+5*8]
?setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

?_NV_clear@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_clear@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::clear(class MyGUI::Widget *);
?clear@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+6*8]
?clear@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_update@ToolTip@@QEAAXXZ proc EXPORT
?_NV_update@ToolTip@@QEAAXXZ endp

; ToolTip::update();
?update@ToolTip@@UEAAXXZ proc EXPORT
jmp function_pointers[_ToolTip_base+7*8]
?update@ToolTip@@UEAAXXZ endp

?_NV_hide@ToolTip@@QEAAXXZ proc EXPORT
?_NV_hide@ToolTip@@QEAAXXZ endp

; ToolTip::hide();
?hide@ToolTip@@UEAAXXZ proc EXPORT
jmp function_pointers[_ToolTip_base+8*8]
?hide@ToolTip@@UEAAXXZ endp

; ToolTip::getVisible();
?getVisible@ToolTip@@QEBA_NXZ proc EXPORT
jmp function_pointers[_ToolTip_base+9*8]
?getVisible@ToolTip@@QEBA_NXZ endp

?_NV__setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV__setup@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::_setup(class MyGUI::Widget *);
?_setup@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+10*8]
?_setup@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_clearData@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_clearData@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::clearData(class MyGUI::Widget *);
?clearData@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+11*8]
?clearData@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_show@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z proc EXPORT
?_NV_show@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z endp

; ToolTip::show(class MyGUI::Widget *, const struct MyGUI::types::TPoint<int> &);
?show@ToolTip@@UEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+12*8]
?show@ToolTip@@UEAAXPEAVWidget@MyGUI@@AEBU?$TPoint@H@types@3@@Z endp

?_NV_setContent@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
?_NV_setContent@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::setContent(class MyGUI::Widget *);
?setContent@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+13*8]
?setContent@ToolTip@@UEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::showText(class MyGUI::Widget *);
?showText@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+14*8]
?showText@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::showMultiLine(class MyGUI::Widget *);
?showMultiLine@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+15*8]
?showMultiLine@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

; ToolTip::showGameData(const class hand &);
?showGameData@ToolTip@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+16*8]
?showGameData@ToolTip@@QEAAXAEBVhand@@@Z endp

; ToolTip::showGameData(class MyGUI::Widget *);
?showGameData@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+17*8]
?showGameData@ToolTip@@QEAAXPEAVWidget@MyGUI@@@Z endp

?_NV_setVisible@ToolTip@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@ToolTip@@QEAAX_N@Z endp

; ToolTip::setVisible(bool);
?setVisible@ToolTip@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_ToolTip_base+18*8]
?setVisible@ToolTip@@UEAAX_N@Z endp

?_NV_setPosition@ToolTip@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
?_NV_setPosition@ToolTip@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTip::setPosition(const struct MyGUI::types::TPoint<int> &);
?setPosition@ToolTip@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+19*8]
?setPosition@ToolTip@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTip::addLine(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?addLine@ToolTip@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_ToolTip_base+20*8]
?addLine@ToolTip@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; ToolTip::clearLines();
?clearLines@ToolTip@@QEAAXXZ proc EXPORT
jmp function_pointers[_ToolTip_base+21*8]
?clearLines@ToolTip@@QEAAXXZ endp

; ToolTip::notifyToolTip(class MyGUI::Widget *, const struct MyGUI::ToolTipInfo &);
?notifyToolTip@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBUToolTipInfo@3@@Z proc EXPORT
jmp function_pointers[_ToolTip_base+22*8]
?notifyToolTip@ToolTip@@QEAAXPEAVWidget@MyGUI@@AEBUToolTipInfo@3@@Z endp
