
?_CONSTRUCTOR@ToolTipDynamic@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ToolTipDynamic@@QEAAPEAV1@XZ endp

; ToolTipDynamic::ToolTipDynamic();
??0ToolTipDynamic@@QEAA@XZ proc EXPORT
jmp function_pointers[_ToolTipDynamic_base+0*8]
??0ToolTipDynamic@@QEAA@XZ endp

?_DESTRUCTOR@ToolTipDynamic@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ToolTipDynamic@@QEAAXXZ endp

; ToolTipDynamic::~ToolTipDynamic();
??1ToolTipDynamic@@UEAA@XZ proc EXPORT
jmp function_pointers[_ToolTipDynamic_base+1*8]
??1ToolTipDynamic@@UEAA@XZ endp

?_NV_setVisible@ToolTipDynamic@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@ToolTipDynamic@@QEAAX_N@Z endp

; ToolTipDynamic::setVisible(bool);
?setVisible@ToolTipDynamic@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_ToolTipDynamic_base+2*8]
?setVisible@ToolTipDynamic@@UEAAX_N@Z endp

?_NV_setPosition@ToolTipDynamic@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
?_NV_setPosition@ToolTipDynamic@@QEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp

; ToolTipDynamic::setPosition(const struct MyGUI::types::TPoint<int> &);
?setPosition@ToolTipDynamic@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z proc EXPORT
jmp function_pointers[_ToolTipDynamic_base+3*8]
?setPosition@ToolTipDynamic@@UEAAXAEBU?$TPoint@H@types@MyGUI@@@Z endp
