
?_CONSTRUCTOR@TortureBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@TortureBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; TortureBuilding::TortureBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0TortureBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TortureBuilding_base+0*8]
??0TortureBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_NV_getFunctionStuff@TortureBuilding@@QEAAPEAVStorageBuilding@@XZ proc EXPORT
?_NV_getFunctionStuff@TortureBuilding@@QEAAPEAVStorageBuilding@@XZ endp

; TortureBuilding::getFunctionStuff();
?getFunctionStuff@TortureBuilding@@UEAAPEAVStorageBuilding@@XZ proc EXPORT
jmp function_pointers[_TortureBuilding_base+1*8]
?getFunctionStuff@TortureBuilding@@UEAAPEAVStorageBuilding@@XZ endp

?_NV_update@TortureBuilding@@QEAAXXZ proc EXPORT
?_NV_update@TortureBuilding@@QEAAXXZ endp

; TortureBuilding::update();
?update@TortureBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TortureBuilding_base+2*8]
?update@TortureBuilding@@UEAAXXZ endp

?_DESTRUCTOR@TortureBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TortureBuilding@@QEAAXXZ endp

; TortureBuilding::~TortureBuilding();
??1TortureBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_TortureBuilding_base+3*8]
??1TortureBuilding@@UEAA@XZ endp
