
?_CONSTRUCTOR@NestSpot@Town@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@NestSpot@Town@@QEAAPEAV12@AEBU12@@Z endp

; Town::NestSpot::NestSpot(const struct Town::NestSpot &);
??0NestSpot@Town@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_Town_NestSpot_base+0*8]
??0NestSpot@Town@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@NestSpot@Town@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@NestSpot@Town@@QEAAPEAV12@XZ endp

; Town::NestSpot::NestSpot();
??0NestSpot@Town@@QEAA@XZ proc EXPORT
jmp function_pointers[_Town_NestSpot_base+1*8]
??0NestSpot@Town@@QEAA@XZ endp

; Town::NestSpot::operator=(const struct Town::NestSpot &);
??4NestSpot@Town@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_Town_NestSpot_base+2*8]
??4NestSpot@Town@@QEAAAEAU01@AEBU01@@Z endp
