
?_CONSTRUCTOR@TownPositionCacher@TownBase@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@TownPositionCacher@TownBase@@QEAAPEAV12@XZ endp

; TownBase::TownPositionCacher::TownPositionCacher();
??0TownPositionCacher@TownBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_TownBase_TownPositionCacher_base+0*8]
??0TownPositionCacher@TownBase@@QEAA@XZ endp

; TownBase::TownPositionCacher::stampUpdate();
?stampUpdate@TownPositionCacher@TownBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_TownPositionCacher_base+1*8]
?stampUpdate@TownPositionCacher@TownBase@@QEAAXXZ endp

; TownBase::TownPositionCacher::needsUpdate();
?needsUpdate@TownPositionCacher@TownBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_TownPositionCacher_base+2*8]
?needsUpdate@TownPositionCacher@TownBase@@QEAA_NXZ endp
