
?_CONSTRUCTOR@ResidentData@TownBase@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@ResidentData@TownBase@@QEAAPEAV12@AEBU12@@Z endp

; TownBase::ResidentData::ResidentData(const struct TownBase::ResidentData &);
??0ResidentData@TownBase@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_TownBase_ResidentData_base+0*8]
??0ResidentData@TownBase@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@ResidentData@TownBase@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@ResidentData@TownBase@@QEAAPEAV12@XZ endp

; TownBase::ResidentData::ResidentData();
??0ResidentData@TownBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_TownBase_ResidentData_base+1*8]
??0ResidentData@TownBase@@QEAA@XZ endp

?_DESTRUCTOR@ResidentData@TownBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ResidentData@TownBase@@QEAAXXZ endp

; TownBase::ResidentData::~ResidentData();
??1ResidentData@TownBase@@QEAA@XZ proc EXPORT
jmp function_pointers[_TownBase_ResidentData_base+2*8]
??1ResidentData@TownBase@@QEAA@XZ endp

; TownBase::ResidentData::operator=(const struct TownBase::ResidentData &);
??4ResidentData@TownBase@@QEAAAEAU01@AEBU01@@Z proc EXPORT
jmp function_pointers[_TownBase_ResidentData_base+3*8]
??4ResidentData@TownBase@@QEAAAEAU01@AEBU01@@Z endp
