
?_CONSTRUCTOR@Town@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@Town@@QEAAPEAV1@PEAVGameData@@@Z endp

; Town::Town(class GameData *);
??0Town@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+0*8]
??0Town@@QEAA@PEAVGameData@@@Z endp

?_DESTRUCTOR@Town@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Town@@QEAAXXZ endp

; Town::~Town();
??1Town@@UEAA@XZ proc EXPORT
jmp function_pointers[_Town_base+1*8]
??1Town@@UEAA@XZ endp

; Town::initialiseResidentData();
?initialiseResidentData@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+2*8]
?initialiseResidentData@Town@@QEAAXXZ endp

?_NV_getGameData@Town@@QEBAPEAVGameData@@XZ proc EXPORT
?_NV_getGameData@Town@@QEBAPEAVGameData@@XZ endp

; Town::getGameData();
?getGameData@Town@@UEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Town_base+3*8]
?getGameData@Town@@UEBAPEAVGameData@@XZ endp

; Town::getOriginalGameData();
?getOriginalGameData@Town@@QEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Town_base+4*8]
?getOriginalGameData@Town@@QEBAPEAVGameData@@XZ endp

; Town::notifyRepopulation(class GameData *);
?notifyRepopulation@Town@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+5*8]
?notifyRepopulation@Town@@QEAAXPEAVGameData@@@Z endp

; Town::isMyOldHomeTownStillValid(class GameData *);
?isMyOldHomeTownStillValid@Town@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+6*8]
?isMyOldHomeTownStillValid@Town@@QEAA_NPEAVGameData@@@Z endp

?_NV_setup@Town@@QEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z proc EXPORT
?_NV_setup@Town@@QEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z endp

; Town::setup(class GameData *, class Ogre::Vector3, class hand);
?setup@Town@@UEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z proc EXPORT
jmp function_pointers[_Town_base+7*8]
?setup@Town@@UEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z endp

?_NV__reset@Town@@QEAAXXZ proc EXPORT
?_NV__reset@Town@@QEAAXXZ endp

; Town::_reset();
?_reset@Town@@UEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+8*8]
?_reset@Town@@UEAAXXZ endp

?_NV_getDataType@Town@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@Town@@QEBA?AW4itemType@@XZ endp

; Town::getDataType();
?getDataType@Town@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_Town_base+9*8]
?getDataType@Town@@UEBA?AW4itemType@@XZ endp

?_NV_reassessTownPosition@Town@@QEAAXXZ proc EXPORT
?_NV_reassessTownPosition@Town@@QEAAXXZ endp

; Town::reassessTownPosition();
?reassessTownPosition@Town@@UEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+10*8]
?reassessTownPosition@Town@@UEAAXXZ endp

; Town::showDistantTown(bool);
?showDistantTown@Town@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Town_base+11*8]
?showDistantTown@Town@@QEAAX_N@Z endp

?_NV_getAlarmMgr@Town@@QEAAPEAVAlarmManager@@XZ proc EXPORT
?_NV_getAlarmMgr@Town@@QEAAPEAVAlarmManager@@XZ endp

; Town::getAlarmMgr();
?getAlarmMgr@Town@@UEAAPEAVAlarmManager@@XZ proc EXPORT
jmp function_pointers[_Town_base+12*8]
?getAlarmMgr@Town@@UEAAPEAVAlarmManager@@XZ endp

; Town::isOutpost();
?isOutpost@Town@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Town_base+13*8]
?isOutpost@Town@@QEBA_NXZ endp

; Town::_setMainResident(class Building *, class GameData *, bool);
?_setMainResident@Town@@QEAA_NPEAVBuilding@@PEAVGameData@@_N@Z proc EXPORT
jmp function_pointers[_Town_base+14*8]
?_setMainResident@Town@@QEAA_NPEAVBuilding@@PEAVGameData@@_N@Z endp

; Town::chooseResidents(const class lektor<Building *> &);
?chooseResidents@Town@@QEAAXAEBV?$lektor@PEAVBuilding@@@@@Z proc EXPORT
jmp function_pointers[_Town_base+15*8]
?chooseResidents@Town@@QEAAXAEBV?$lektor@PEAVBuilding@@@@@Z endp

; Town::spawnTheBarFlies();
?spawnTheBarFlies@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+16*8]
?spawnTheBarFlies@Town@@QEAAXXZ endp

; Town::chooseBuildingForResident(const class lektor<Building *> &, struct TownBase::ResidentData *);
?chooseBuildingForResident@Town@@QEAAPEAVBuilding@@AEBV?$lektor@PEAVBuilding@@@@PEAUResidentData@TownBase@@@Z proc EXPORT
jmp function_pointers[_Town_base+17*8]
?chooseBuildingForResident@Town@@QEAAPEAVBuilding@@AEBV?$lektor@PEAVBuilding@@@@PEAUResidentData@TownBase@@@Z endp

; Town::townLoadedEvent(bool);
?townLoadedEvent@Town@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Town_base+18*8]
?townLoadedEvent@Town@@QEAAX_N@Z endp

; Town::notifyUnloading();
?notifyUnloading@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+19*8]
?notifyUnloading@Town@@QEAAXXZ endp

?_NV_setHandle@Town@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@Town@@QEAAXAEBVhand@@@Z endp

; Town::setHandle(const class hand &);
?setHandle@Town@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Town_base+20*8]
?setHandle@Town@@UEAAXAEBVhand@@@Z endp

; Town::getBuildingMaterial();
?getBuildingMaterial@Town@@QEBAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_Town_base+21*8]
?getBuildingMaterial@Town@@QEBAPEAVGameData@@XZ endp

; Town::getLocalTradePriceMult(class GameData *);
?getLocalTradePriceMult@Town@@QEAAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+22*8]
?getLocalTradePriceMult@Town@@QEAAMPEAVGameData@@@Z endp

; Town::getFactionTradeCultureMult(class GameData *);
?getFactionTradeCultureMult@Town@@QEAAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+23*8]
?getFactionTradeCultureMult@Town@@QEAAMPEAVGameData@@@Z endp

?_NV_isTown@Town@@QEAAPEAV1@XZ proc EXPORT
?_NV_isTown@Town@@QEAAPEAV1@XZ endp

; Town::isTown();
?isTown@Town@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Town_base+24*8]
?isTown@Town@@UEAAPEAV1@XZ endp

?_NV_isNest@Town@@QEAAPEAVNest@@XZ proc EXPORT
?_NV_isNest@Town@@QEAAPEAVNest@@XZ endp

; Town::isNest();
?isNest@Town@@UEAAPEAVNest@@XZ proc EXPORT
jmp function_pointers[_Town_base+25*8]
?isNest@Town@@UEAAPEAVNest@@XZ endp

?_NV_isPublic@Town@@QEBA_NXZ proc EXPORT
?_NV_isPublic@Town@@QEBA_NXZ endp

; Town::isPublic();
?isPublic@Town@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Town_base+26*8]
?isPublic@Town@@UEBA_NXZ endp

?_NV_getGUIData@Town@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@Town@@QEAAXPEAVDatapanelGUI@@H@Z endp

; Town::getGUIData(class DatapanelGUI *, int);
?getGUIData@Town@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_Town_base+27*8]
?getGUIData@Town@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_saveState@Town@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_saveState@Town@@QEAAXPEAVGameData@@@Z endp

; Town::saveState(class GameData *);
?saveState@Town@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+28*8]
?saveState@Town@@UEAAXPEAVGameData@@@Z endp

?_NV_loadState@Town@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_loadState@Town@@QEAAXPEAVGameData@@@Z endp

; Town::loadState(class GameData *);
?loadState@Town@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+29*8]
?loadState@Town@@UEAAXPEAVGameData@@@Z endp

?_NV_serialise@Town@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@Town@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; Town::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@Town@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_Town_base+30*8]
?serialise@Town@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@Town@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@Town@@QEAAXPEAVGameSaveState@@@Z endp

; Town::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@Town@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_Town_base+31*8]
?loadFromSerialise@Town@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_needsSaving@Town@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
?_NV_needsSaving@Town@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Town::needsSaving(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?needsSaving@Town@@UEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_Town_base+32*8]
?needsSaving@Town@@UEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; Town::setPosition(const class Ogre::Vector3 &);
?setPosition@Town@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Town_base+33*8]
?setPosition@Town@@QEAAXAEBVVector3@Ogre@@@Z endp

?_NV_saveStateEditor@Town@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_saveStateEditor@Town@@QEAAXPEAVGameData@@@Z endp

; Town::saveStateEditor(class GameData *);
?saveStateEditor@Town@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+34*8]
?saveStateEditor@Town@@UEAAXPEAVGameData@@@Z endp

?_NV_loadStateEditor@Town@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_loadStateEditor@Town@@QEAAXPEAVGameData@@@Z endp

; Town::loadStateEditor(class GameData *);
?loadStateEditor@Town@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+35*8]
?loadStateEditor@Town@@UEAAXPEAVGameData@@@Z endp

?_NV_getRadius@Town@@QEBAMXZ proc EXPORT
?_NV_getRadius@Town@@QEBAMXZ endp

; Town::getRadius();
?getRadius@Town@@UEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+36*8]
?getRadius@Town@@UEBAMXZ endp

?_NV_isActive@Town@@QEBA_NXZ proc EXPORT
?_NV_isActive@Town@@QEBA_NXZ endp

; Town::isActive();
?isActive@Town@@UEBA_NXZ proc EXPORT
jmp function_pointers[_Town_base+37*8]
?isActive@Town@@UEBA_NXZ endp

?_NV_update@Town@@QEAAXXZ proc EXPORT
?_NV_update@Town@@QEAAXXZ endp

; Town::update();
?update@Town@@UEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+38*8]
?update@Town@@UEAAXXZ endp

?_NV_periodicUpdate@Town@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@Town@@QEAAXXZ endp

; Town::periodicUpdate();
?periodicUpdate@Town@@UEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+39*8]
?periodicUpdate@Town@@UEAAXXZ endp

?_NV_updatePowerGrid@Town@@QEAAXXZ proc EXPORT
?_NV_updatePowerGrid@Town@@QEAAXXZ endp

; Town::updatePowerGrid();
?updatePowerGrid@Town@@UEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+40*8]
?updatePowerGrid@Town@@UEAAXXZ endp

?_NV_hasResidentHQ@Town@@QEBA_NPEAVFaction@@@Z proc EXPORT
?_NV_hasResidentHQ@Town@@QEBA_NPEAVFaction@@@Z endp

; Town::hasResidentHQ(class Faction *);
?hasResidentHQ@Town@@UEBA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_Town_base+41*8]
?hasResidentHQ@Town@@UEBA_NPEAVFaction@@@Z endp

?_NV_addGate@Town@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_addGate@Town@@QEAAXAEBVhand@@@Z endp

; Town::addGate(const class hand &);
?addGate@Town@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_Town_base+42*8]
?addGate@Town@@UEAAXAEBVhand@@@Z endp

?_NV_gatesAllClosed@Town@@QEAA_NXZ proc EXPORT
?_NV_gatesAllClosed@Town@@QEAA_NXZ endp

; Town::gatesAllClosed();
?gatesAllClosed@Town@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Town_base+43*8]
?gatesAllClosed@Town@@UEAA_NXZ endp

?_NV_hasGates@Town@@QEAA_NXZ proc EXPORT
?_NV_hasGates@Town@@QEAA_NXZ endp

; Town::hasGates();
?hasGates@Town@@UEAA_NXZ proc EXPORT
jmp function_pointers[_Town_base+44*8]
?hasGates@Town@@UEAA_NXZ endp

; Town::notifyAccesibility(bool);
?notifyAccesibility@Town@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_Town_base+45*8]
?notifyAccesibility@Town@@QEAAX_N@Z endp

?_NV_getNearestGate@Town@@QEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_getNearestGate@Town@@QEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z endp

; Town::getNearestGate(const class Ogre::Vector3 &);
?getNearestGate@Town@@UEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_Town_base+46*8]
?getNearestGate@Town@@UEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z endp

?_NV_getPositionOutsideTownGates@Town@@QEAA?AVVector3@Ogre@@M@Z proc EXPORT
?_NV_getPositionOutsideTownGates@Town@@QEAA?AVVector3@Ogre@@M@Z endp

; Town::getPositionOutsideTownGates(float);
?getPositionOutsideTownGates@Town@@UEAA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_Town_base+47*8]
?getPositionOutsideTownGates@Town@@UEAA?AVVector3@Ogre@@M@Z endp

; Town::addBuilding(class UseableStuff *, bool, bool, bool);
?addBuilding@Town@@QEAAXPEAVUseableStuff@@_N11@Z proc EXPORT
jmp function_pointers[_Town_base+48*8]
?addBuilding@Town@@QEAAXPEAVUseableStuff@@_N11@Z endp

; Town::removeBuilding(class UseableStuff *);
?removeBuilding@Town@@QEAAXPEAVUseableStuff@@@Z proc EXPORT
jmp function_pointers[_Town_base+49*8]
?removeBuilding@Town@@QEAAXPEAVUseableStuff@@@Z endp

; Town::isPlayerBuildingsInThisTown();
?isPlayerBuildingsInThisTown@Town@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Town_base+50*8]
?isPlayerBuildingsInThisTown@Town@@QEBA_NXZ endp

; Town::setPlayerBuildingsInThisTown();
?setPlayerBuildingsInThisTown@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+51*8]
?setPlayerBuildingsInThisTown@Town@@QEAAXXZ endp

; Town::getRequiredPower();
?getRequiredPower@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+52*8]
?getRequiredPower@Town@@QEBAMXZ endp

; Town::getTotalPower();
?getTotalPower@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+53*8]
?getTotalPower@Town@@QEBAMXZ endp

; Town::hasSparePower();
?hasSparePower@Town@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Town_base+54*8]
?hasSparePower@Town@@QEBA_NXZ endp

; Town::getBatteryDrain();
?getBatteryDrain@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+55*8]
?getBatteryDrain@Town@@QEBAMXZ endp

; Town::getBatteryChargeMax();
?getBatteryChargeMax@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+56*8]
?getBatteryChargeMax@Town@@QEBAMXZ endp

; Town::getBatteryCharge();
?getBatteryCharge@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+57*8]
?getBatteryCharge@Town@@QEBAMXZ endp

; Town::getBatteryCharge01();
?getBatteryCharge01@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+58*8]
?getBatteryCharge01@Town@@QEBAMXZ endp

; Town::getBatteryChargingUpAmount();
?getBatteryChargingUpAmount@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+59*8]
?getBatteryChargingUpAmount@Town@@QEBAMXZ endp

; Town::getBatteryPowerTotal();
?getBatteryPowerTotal@Town@@QEBAMXZ proc EXPORT
jmp function_pointers[_Town_base+60*8]
?getBatteryPowerTotal@Town@@QEBAMXZ endp

; Town::isBatteryMode();
?isBatteryMode@Town@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Town_base+61*8]
?isBatteryMode@Town@@QEBA_NXZ endp

; Town::addNest(class GameData *, const class Ogre::Vector3 &, class Building *);
?addNest@Town@@QEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_Town_base+62*8]
?addNest@Town@@QEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z endp

; Town::removeNest(class Building *);
?removeNest@Town@@QEAA_NPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_Town_base+63*8]
?removeNest@Town@@QEAA_NPEAVBuilding@@@Z endp

; Town::clearNests();
?clearNests@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+64*8]
?clearNests@Town@@QEAAXXZ endp

?_NV_getMapMarker@Town@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getMapMarker@Town@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; Town::getMapMarker();
?getMapMarker@Town@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_Town_base+65*8]
?getMapMarker@Town@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getMapMarkerZoomLevel@Town@@QEAA?AW4MapZoomLevel@@XZ proc EXPORT
?_NV_getMapMarkerZoomLevel@Town@@QEAA?AW4MapZoomLevel@@XZ endp

; Town::getMapMarkerZoomLevel();
?getMapMarkerZoomLevel@Town@@UEAA?AW4MapZoomLevel@@XZ proc EXPORT
jmp function_pointers[_Town_base+66*8]
?getMapMarkerZoomLevel@Town@@UEAA?AW4MapZoomLevel@@XZ endp

; Town::recalculatePlayerTownLevel();
?recalculatePlayerTownLevel@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+67*8]
?recalculatePlayerTownLevel@Town@@QEAAXXZ endp

; Town::getPlayerTownTypeEnum();
?getPlayerTownTypeEnum@Town@@QEAA?AW4TownType@@XZ proc EXPORT
jmp function_pointers[_Town_base+68*8]
?getPlayerTownTypeEnum@Town@@QEAA?AW4TownType@@XZ endp

; Town::facilitesWeHaveHere();
?facilitesWeHaveHere@Town@@QEBA?AV?$TagsClass@W4BuildingDesignation@@@@XZ proc EXPORT
jmp function_pointers[_Town_base+69*8]
?facilitesWeHaveHere@Town@@QEBA?AV?$TagsClass@W4BuildingDesignation@@@@XZ endp

; Town::deActivationCheck();
?deActivationCheck@Town@@QEAAXXZ proc EXPORT
jmp function_pointers[_Town_base+70*8]
?deActivationCheck@Town@@QEAAXXZ endp

; Town::powerBuilding(class UseableStuff *, int, float &, bool);
?powerBuilding@Town@@QEAA_NPEAVUseableStuff@@HAEAM_N@Z proc EXPORT
jmp function_pointers[_Town_base+71*8]
?powerBuilding@Town@@QEAA_NPEAVUseableStuff@@HAEAM_N@Z endp

; Town::drainBattery(class UseableStuff *, int, float &);
?drainBattery@Town@@QEAA_NPEAVUseableStuff@@HAEAM@Z proc EXPORT
jmp function_pointers[_Town_base+72*8]
?drainBattery@Town@@QEAA_NPEAVUseableStuff@@HAEAM@Z endp

; Town::_initialiseResidentData(class GameData *);
?_initialiseResidentData@Town@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_Town_base+73*8]
?_initialiseResidentData@Town@@QEAAXPEAVGameData@@@Z endp
