
?_CONSTRUCTOR@DelayedSpawnMsg@TownBase@@QEAAPEAV12@PEAV2@PEAVGameData@@AEBVVector3@Ogre@@AEBVhand@@@Z proc EXPORT
?_CONSTRUCTOR@DelayedSpawnMsg@TownBase@@QEAAPEAV12@PEAV2@PEAVGameData@@AEBVVector3@Ogre@@AEBVhand@@@Z endp

; TownBase::DelayedSpawnMsg::DelayedSpawnMsg(class TownBase *, class GameData *, const class Ogre::Vector3 &, const class hand &);
??0DelayedSpawnMsg@TownBase@@QEAA@PEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVhand@@@Z proc EXPORT
jmp function_pointers[_TownBase_DelayedSpawnMsg_base+0*8]
??0DelayedSpawnMsg@TownBase@@QEAA@PEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVhand@@@Z endp

?_CONSTRUCTOR@DelayedSpawnMsg@TownBase@@QEAAPEAV12@PEAVItem@@AEBVVector3@Ogre@@@Z proc EXPORT
?_CONSTRUCTOR@DelayedSpawnMsg@TownBase@@QEAAPEAV12@PEAVItem@@AEBVVector3@Ogre@@@Z endp

; TownBase::DelayedSpawnMsg::DelayedSpawnMsg(class Item *, const class Ogre::Vector3 &);
??0DelayedSpawnMsg@TownBase@@QEAA@PEAVItem@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBase_DelayedSpawnMsg_base+1*8]
??0DelayedSpawnMsg@TownBase@@QEAA@PEAVItem@@AEBVVector3@Ogre@@@Z endp
