
?_CONSTRUCTOR@TownBase@@QEAAPEAV1@PEAVGameData@@@Z proc EXPORT
?_CONSTRUCTOR@TownBase@@QEAAPEAV1@PEAVGameData@@@Z endp

; TownBase::TownBase(class GameData *);
??0TownBase@@QEAA@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+0*8]
??0TownBase@@QEAA@PEAVGameData@@@Z endp

?_DESTRUCTOR@TownBase@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TownBase@@QEAAXXZ endp

; TownBase::~TownBase();
??1TownBase@@UEAA@XZ proc EXPORT
jmp function_pointers[_TownBase_base+1*8]
??1TownBase@@UEAA@XZ endp

?_NV_activate@TownBase@@QEAAXPEAVZoneMap@@@Z proc EXPORT
?_NV_activate@TownBase@@QEAAXPEAVZoneMap@@@Z endp

; TownBase::activate(class ZoneMap *);
?activate@TownBase@@UEAAXPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+2*8]
?activate@TownBase@@UEAAXPEAVZoneMap@@@Z endp

?_NV_isActive@TownBase@@QEBA_NXZ proc EXPORT
?_NV_isActive@TownBase@@QEBA_NXZ endp

; TownBase::isActive();
?isActive@TownBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+3*8]
?isActive@TownBase@@UEBA_NXZ endp

?_NV_setup@TownBase@@QEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z proc EXPORT
?_NV_setup@TownBase@@QEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z endp

; TownBase::setup(class GameData *, class Ogre::Vector3, class hand);
?setup@TownBase@@UEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+4*8]
?setup@TownBase@@UEAAXPEAVGameData@@VVector3@Ogre@@Vhand@@@Z endp

?_NV__reset@TownBase@@QEAAXXZ proc EXPORT
?_NV__reset@TownBase@@QEAAXXZ endp

; TownBase::_reset();
?_reset@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+5*8]
?_reset@TownBase@@UEAAXXZ endp

; TownBase::getKnownName();
?getKnownName@TownBase@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+6*8]
?getKnownName@TownBase@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getAlarmState@TownBase@@QEBA?AW4TownAlarmState@@XZ proc EXPORT
?_NV_getAlarmState@TownBase@@QEBA?AW4TownAlarmState@@XZ endp

; TownBase::getAlarmState();
?getAlarmState@TownBase@@UEBA?AW4TownAlarmState@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+7*8]
?getAlarmState@TownBase@@UEBA?AW4TownAlarmState@@XZ endp

?_NV_setAlarmState@TownBase@@QEAAXW4TownAlarmState@@@Z proc EXPORT
?_NV_setAlarmState@TownBase@@QEAAXW4TownAlarmState@@@Z endp

; TownBase::setAlarmState(enum TownAlarmState);
?setAlarmState@TownBase@@UEAAXW4TownAlarmState@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+8*8]
?setAlarmState@TownBase@@UEAAXW4TownAlarmState@@@Z endp

?_NV_reassessTownPosition@TownBase@@QEAAXXZ proc EXPORT
?_NV_reassessTownPosition@TownBase@@QEAAXXZ endp

; TownBase::reassessTownPosition();
?reassessTownPosition@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+9*8]
?reassessTownPosition@TownBase@@UEAAXXZ endp

?_NV_isNotFriendly@TownBase@@QEAA_NXZ proc EXPORT
?_NV_isNotFriendly@TownBase@@QEAA_NXZ endp

; TownBase::isNotFriendly();
?isNotFriendly@TownBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+10*8]
?isNotFriendly@TownBase@@UEAA_NXZ endp

?_NV_isPhysical@TownBase@@QEBA_NXZ proc EXPORT
?_NV_isPhysical@TownBase@@QEBA_NXZ endp

; TownBase::isPhysical();
?isPhysical@TownBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+11*8]
?isPhysical@TownBase@@UEBA_NXZ endp

?_NV_setVisible@TownBase@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@TownBase@@QEAAX_N@Z endp

; TownBase::setVisible(bool);
?setVisible@TownBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+12*8]
?setVisible@TownBase@@UEAAX_N@Z endp

?_NV_setHandle@TownBase@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_setHandle@TownBase@@QEAAXAEBVhand@@@Z endp

; TownBase::setHandle(const class hand &);
?setHandle@TownBase@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+13*8]
?setHandle@TownBase@@UEAAXAEBVhand@@@Z endp

?_NV_getDataType@TownBase@@QEBA?AW4itemType@@XZ proc EXPORT
?_NV_getDataType@TownBase@@QEBA?AW4itemType@@XZ endp

; TownBase::getDataType();
?getDataType@TownBase@@UEBA?AW4itemType@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+14*8]
?getDataType@TownBase@@UEBA?AW4itemType@@XZ endp

?_NV_isTown@TownBase@@QEAAPEAVTown@@XZ proc EXPORT
?_NV_isTown@TownBase@@QEAAPEAVTown@@XZ endp

; TownBase::isTown();
?isTown@TownBase@@UEAAPEAVTown@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+15*8]
?isTown@TownBase@@UEAAPEAVTown@@XZ endp

?_NV_nestUpThisSpot@TownBase@@QEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
?_NV_nestUpThisSpot@TownBase@@QEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z endp

; TownBase::nestUpThisSpot(class GameData *, const class Ogre::Vector3 &, class Building *);
?nestUpThisSpot@TownBase@@UEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+16*8]
?nestUpThisSpot@TownBase@@UEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z endp

?_NV_serialise@TownBase@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@TownBase@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; TownBase::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@TownBase@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+17*8]
?serialise@TownBase@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@TownBase@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@TownBase@@QEAAXPEAVGameSaveState@@@Z endp

; TownBase::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@TownBase@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+18*8]
?loadFromSerialise@TownBase@@UEAAXPEAVGameSaveState@@@Z endp

; TownBase::isOutpost();
?isOutpost@TownBase@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+19*8]
?isOutpost@TownBase@@QEBA_NXZ endp

; TownBase::withinBordersRange(const class Ogre::Vector3 &, float);
?withinBordersRange@TownBase@@QEBA_NAEBVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_TownBase_base+20*8]
?withinBordersRange@TownBase@@QEBA_NAEBVVector3@Ogre@@M@Z endp

; TownBase::withinDiscoveryRange(const class Ogre::Vector3 &, bool);
?withinDiscoveryRange@TownBase@@QEBA_NAEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+21*8]
?withinDiscoveryRange@TownBase@@QEBA_NAEBVVector3@Ogre@@_N@Z endp

?_NV_isIllegal@TownBase@@QEAA_NPEAVItem@@@Z proc EXPORT
?_NV_isIllegal@TownBase@@QEAA_NPEAVItem@@@Z endp

; TownBase::isIllegal(class Item *);
?isIllegal@TownBase@@UEAA_NPEAVItem@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+22*8]
?isIllegal@TownBase@@UEAA_NPEAVItem@@@Z endp

; TownBase::distanceTo(const class Ogre::Vector3 &);
?distanceTo@TownBase@@QEBAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+23*8]
?distanceTo@TownBase@@QEBAMAEBVVector3@Ogre@@@Z endp

; TownBase::squaredDistanceTo(const class Ogre::Vector3 &);
?squaredDistanceTo@TownBase@@QEBAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+24*8]
?squaredDistanceTo@TownBase@@QEBAMAEBVVector3@Ogre@@@Z endp

?_NV_isDead@TownBase@@QEAA_NXZ proc EXPORT
?_NV_isDead@TownBase@@QEAA_NXZ endp

; TownBase::isDead();
?isDead@TownBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+25*8]
?isDead@TownBase@@UEAA_NXZ endp

?_NV_getPositionOutsideTownGates@TownBase@@QEAA?AVVector3@Ogre@@M@Z proc EXPORT
?_NV_getPositionOutsideTownGates@TownBase@@QEAA?AVVector3@Ogre@@M@Z endp

; TownBase::getPositionOutsideTownGates(float);
?getPositionOutsideTownGates@TownBase@@UEAA?AVVector3@Ogre@@M@Z proc EXPORT
jmp function_pointers[_TownBase_base+26*8]
?getPositionOutsideTownGates@TownBase@@UEAA?AVVector3@Ogre@@M@Z endp

?_NV_setFaction@TownBase@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
?_NV_setFaction@TownBase@@QEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

; TownBase::setFaction(class Faction *, class ActivePlatoon *);
?setFaction@TownBase@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+27*8]
?setFaction@TownBase@@UEAAXPEAVFaction@@PEAVActivePlatoon@@@Z endp

?_NV_isPublic@TownBase@@QEBA_NXZ proc EXPORT
?_NV_isPublic@TownBase@@QEBA_NXZ endp

; TownBase::isPublic();
?isPublic@TownBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+28*8]
?isPublic@TownBase@@UEBA_NXZ endp

?_NV_getRadius@TownBase@@QEBAMXZ proc EXPORT
?_NV_getRadius@TownBase@@QEBAMXZ endp

; TownBase::getRadius();
?getRadius@TownBase@@UEBAMXZ proc EXPORT
jmp function_pointers[_TownBase_base+29*8]
?getRadius@TownBase@@UEBAMXZ endp

?_NV_getGUIData@TownBase@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@TownBase@@QEAAXPEAVDatapanelGUI@@H@Z endp

; TownBase::getGUIData(class DatapanelGUI *, int);
?getGUIData@TownBase@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_TownBase_base+30*8]
?getGUIData@TownBase@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_saveState@TownBase@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_saveState@TownBase@@QEAAXPEAVGameData@@@Z endp

; TownBase::saveState(class GameData *);
?saveState@TownBase@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+31*8]
?saveState@TownBase@@UEAAXPEAVGameData@@@Z endp

?_NV_loadState@TownBase@@QEAAXPEAVGameData@@@Z proc EXPORT
?_NV_loadState@TownBase@@QEAAXPEAVGameData@@@Z endp

; TownBase::loadState(class GameData *);
?loadState@TownBase@@UEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+32*8]
?loadState@TownBase@@UEAAXPEAVGameData@@@Z endp

?_NV_update@TownBase@@QEAAXXZ proc EXPORT
?_NV_update@TownBase@@QEAAXXZ endp

; TownBase::update();
?update@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+33*8]
?update@TownBase@@UEAAXXZ endp

?_NV_periodicUpdate@TownBase@@QEAAXXZ proc EXPORT
?_NV_periodicUpdate@TownBase@@QEAAXXZ endp

; TownBase::periodicUpdate();
?periodicUpdate@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+34*8]
?periodicUpdate@TownBase@@UEAAXXZ endp

?_NV_updatePowerGrid@TownBase@@QEAAXXZ proc EXPORT
?_NV_updatePowerGrid@TownBase@@QEAAXXZ endp

; TownBase::updatePowerGrid();
?updatePowerGrid@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+35*8]
?updatePowerGrid@TownBase@@UEAAXXZ endp

?_NV_hasResidentHQ@TownBase@@QEBA_NPEAVFaction@@@Z proc EXPORT
?_NV_hasResidentHQ@TownBase@@QEBA_NPEAVFaction@@@Z endp

; TownBase::hasResidentHQ(class Faction *);
?hasResidentHQ@TownBase@@UEBA_NPEAVFaction@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+36*8]
?hasResidentHQ@TownBase@@UEBA_NPEAVFaction@@@Z endp

?_NV_findAllBuildings@TownBase@@QEAAXPEAVBuildingFinderClass@@@Z proc EXPORT
?_NV_findAllBuildings@TownBase@@QEAAXPEAVBuildingFinderClass@@@Z endp

; TownBase::findAllBuildings(class BuildingFinderClass *);
?findAllBuildings@TownBase@@UEAAXPEAVBuildingFinderClass@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+37*8]
?findAllBuildings@TownBase@@UEAAXPEAVBuildingFinderClass@@@Z endp

?_NV_findAllBuildingsOfType@TownBase@@QEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingDesignation@@PEAVCharacter@@@Z proc EXPORT
?_NV_findAllBuildingsOfType@TownBase@@QEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingDesignation@@PEAVCharacter@@@Z endp

; TownBase::findAllBuildingsOfType(enum BuildingDesignation, class Character *);
?findAllBuildingsOfType@TownBase@@UEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingDesignation@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+38*8]
?findAllBuildingsOfType@TownBase@@UEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingDesignation@@PEAVCharacter@@@Z endp

?_NV_findAllBuildingsWithFunction@TownBase@@QEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingFunction@@PEAVCharacter@@@Z proc EXPORT
?_NV_findAllBuildingsWithFunction@TownBase@@QEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingFunction@@PEAVCharacter@@@Z endp

; TownBase::findAllBuildingsWithFunction(enum BuildingFunction, class Character *);
?findAllBuildingsWithFunction@TownBase@@UEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingFunction@@PEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+39*8]
?findAllBuildingsWithFunction@TownBase@@UEAAPEAV?$lektor@PEAVBuilding@@@@W4BuildingFunction@@PEAVCharacter@@@Z endp

?_NV_allBuildingsDoorsOpen@TownBase@@QEAA_NXZ proc EXPORT
?_NV_allBuildingsDoorsOpen@TownBase@@QEAA_NXZ endp

; TownBase::allBuildingsDoorsOpen();
?allBuildingsDoorsOpen@TownBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+40*8]
?allBuildingsDoorsOpen@TownBase@@UEAA_NXZ endp

?_NV_destroyPhysical@TownBase@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@TownBase@@QEAAXXZ endp

; TownBase::destroyPhysical();
?destroyPhysical@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+41*8]
?destroyPhysical@TownBase@@UEAAXXZ endp

?_NV_getPosition@TownBase@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
?_NV_getPosition@TownBase@@QEAA?AVVector3@Ogre@@XZ endp

; TownBase::getPosition();
?getPosition@TownBase@@UEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+42*8]
?getPosition@TownBase@@UEAA?AVVector3@Ogre@@XZ endp

?_NV_getPositionForWaypoint@TownBase@@QEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
?_NV_getPositionForWaypoint@TownBase@@QEAA?AVVector3@Ogre@@AEBV23@@Z endp

; TownBase::getPositionForWaypoint(const class Ogre::Vector3 &);
?getPositionForWaypoint@TownBase@@UEAA?AVVector3@Ogre@@AEBV23@@Z proc EXPORT
jmp function_pointers[_TownBase_base+43*8]
?getPositionForWaypoint@TownBase@@UEAA?AVVector3@Ogre@@AEBV23@@Z endp

?_NV_createPhysical@TownBase@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@TownBase@@QEAA_NXZ endp

; TownBase::createPhysical();
?createPhysical@TownBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+44*8]
?createPhysical@TownBase@@UEAA_NXZ endp

?_NV_getAlarmMgr@TownBase@@QEAAPEAVAlarmManager@@XZ proc EXPORT
?_NV_getAlarmMgr@TownBase@@QEAAPEAVAlarmManager@@XZ endp

; TownBase::getAlarmMgr();
?getAlarmMgr@TownBase@@UEAAPEAVAlarmManager@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+45*8]
?getAlarmMgr@TownBase@@UEAAPEAVAlarmManager@@XZ endp

?_NV_hasGates@TownBase@@QEAA_NXZ proc EXPORT
?_NV_hasGates@TownBase@@QEAA_NXZ endp

; TownBase::hasGates();
?hasGates@TownBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+46*8]
?hasGates@TownBase@@UEAA_NXZ endp

?_NV_addGate@TownBase@@QEAAXAEBVhand@@@Z proc EXPORT
?_NV_addGate@TownBase@@QEAAXAEBVhand@@@Z endp

; TownBase::addGate(const class hand &);
?addGate@TownBase@@UEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+47*8]
?addGate@TownBase@@UEAAXAEBVhand@@@Z endp

?_NV_gatesAllClosed@TownBase@@QEAA_NXZ proc EXPORT
?_NV_gatesAllClosed@TownBase@@QEAA_NXZ endp

; TownBase::gatesAllClosed();
?gatesAllClosed@TownBase@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+48*8]
?gatesAllClosed@TownBase@@UEAA_NXZ endp

?_NV_getNearestGate@TownBase@@QEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z proc EXPORT
?_NV_getNearestGate@TownBase@@QEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z endp

; TownBase::getNearestGate(const class Ogre::Vector3 &);
?getNearestGate@TownBase@@UEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+49*8]
?getNearestGate@TownBase@@UEAAPEAVGatewayBuilding@@AEBVVector3@Ogre@@@Z endp

?_NV_getBiome@TownBase@@QEAAPEAVAreaBiomeGroup@@XZ proc EXPORT
?_NV_getBiome@TownBase@@QEAAPEAVAreaBiomeGroup@@XZ endp

; TownBase::getBiome();
?getBiome@TownBase@@UEAAPEAVAreaBiomeGroup@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+50*8]
?getBiome@TownBase@@UEAAPEAVAreaBiomeGroup@@XZ endp

?_NV_isRecentlyDiscovered@TownBase@@QEBA_NXZ proc EXPORT
?_NV_isRecentlyDiscovered@TownBase@@QEBA_NXZ endp

; TownBase::isRecentlyDiscovered();
?isRecentlyDiscovered@TownBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+51*8]
?isRecentlyDiscovered@TownBase@@UEBA_NXZ endp

?_NV_setRecentlyDiscovered@TownBase@@QEAAX_N@Z proc EXPORT
?_NV_setRecentlyDiscovered@TownBase@@QEAAX_N@Z endp

; TownBase::setRecentlyDiscovered(bool);
?setRecentlyDiscovered@TownBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+52*8]
?setRecentlyDiscovered@TownBase@@UEAAX_N@Z endp

?_NV_isDiscovered@TownBase@@QEBA_NXZ proc EXPORT
?_NV_isDiscovered@TownBase@@QEBA_NXZ endp

; TownBase::isDiscovered();
?isDiscovered@TownBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+53*8]
?isDiscovered@TownBase@@UEBA_NXZ endp

?_NV_setDiscovered@TownBase@@QEAAX_N@Z proc EXPORT
?_NV_setDiscovered@TownBase@@QEAAX_N@Z endp

; TownBase::setDiscovered(bool);
?setDiscovered@TownBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+54*8]
?setDiscovered@TownBase@@UEAAX_N@Z endp

?_NV_setDead@TownBase@@QEAAXXZ proc EXPORT
?_NV_setDead@TownBase@@QEAAXXZ endp

; TownBase::setDead();
?setDead@TownBase@@UEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+55*8]
?setDead@TownBase@@UEAAXXZ endp

?_NV_isExplored@TownBase@@QEBA_NXZ proc EXPORT
?_NV_isExplored@TownBase@@QEBA_NXZ endp

; TownBase::isExplored();
?isExplored@TownBase@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+56*8]
?isExplored@TownBase@@UEBA_NXZ endp

?_NV_setExplored@TownBase@@QEAAX_N@Z proc EXPORT
?_NV_setExplored@TownBase@@QEAAX_N@Z endp

; TownBase::setExplored(bool);
?setExplored@TownBase@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+57*8]
?setExplored@TownBase@@UEAAX_N@Z endp

?_NV_getUnexploredName@TownBase@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getUnexploredName@TownBase@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; TownBase::getUnexploredName();
?getUnexploredName@TownBase@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+58*8]
?getUnexploredName@TownBase@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getItemArtifactsMinValue@TownBase@@QEBAIXZ proc EXPORT
?_NV_getItemArtifactsMinValue@TownBase@@QEBAIXZ endp

; TownBase::getItemArtifactsMinValue();
?getItemArtifactsMinValue@TownBase@@UEBAIXZ proc EXPORT
jmp function_pointers[_TownBase_base+59*8]
?getItemArtifactsMinValue@TownBase@@UEBAIXZ endp

?_NV_getItemArtifactsMaxValue@TownBase@@QEBAIXZ proc EXPORT
?_NV_getItemArtifactsMaxValue@TownBase@@QEBAIXZ endp

; TownBase::getItemArtifactsMaxValue();
?getItemArtifactsMaxValue@TownBase@@UEBAIXZ proc EXPORT
jmp function_pointers[_TownBase_base+60*8]
?getItemArtifactsMaxValue@TownBase@@UEBAIXZ endp

?_NV_getGearArtifactsMinValue@TownBase@@QEBAIXZ proc EXPORT
?_NV_getGearArtifactsMinValue@TownBase@@QEBAIXZ endp

; TownBase::getGearArtifactsMinValue();
?getGearArtifactsMinValue@TownBase@@UEBAIXZ proc EXPORT
jmp function_pointers[_TownBase_base+61*8]
?getGearArtifactsMinValue@TownBase@@UEBAIXZ endp

?_NV_getGearArtifactsMaxValue@TownBase@@QEBAIXZ proc EXPORT
?_NV_getGearArtifactsMaxValue@TownBase@@QEBAIXZ endp

; TownBase::getGearArtifactsMaxValue();
?getGearArtifactsMaxValue@TownBase@@UEBAIXZ proc EXPORT
jmp function_pointers[_TownBase_base+62*8]
?getGearArtifactsMaxValue@TownBase@@UEBAIXZ endp

; TownBase::addArtifactItem(const class ArtifactItemData &);
?addArtifactItem@TownBase@@QEAAXAEBVArtifactItemData@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+63*8]
?addArtifactItem@TownBase@@QEAAXAEBVArtifactItemData@@@Z endp

; TownBase::setZonePopulated(class ZoneMap *);
?setZonePopulated@TownBase@@QEAAXPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+64*8]
?setZonePopulated@TownBase@@QEAAXPEAVZoneMap@@@Z endp

; TownBase::getBuildingsManager();
?getBuildingsManager@TownBase@@QEAAPEAVTownBuildingsManager@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+65*8]
?getBuildingsManager@TownBase@@QEAAPEAVTownBuildingsManager@@XZ endp

; TownBase::getBuildingFloorVisibility(class Building *);
?getBuildingFloorVisibility@TownBase@@QEBAHPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+66*8]
?getBuildingFloorVisibility@TownBase@@QEBAHPEAVBuilding@@@Z endp

; TownBase::setBuildingsFloorVisibility(class Building *, int);
?setBuildingsFloorVisibility@TownBase@@QEAAXPEAVBuilding@@H@Z proc EXPORT
jmp function_pointers[_TownBase_base+67*8]
?setBuildingsFloorVisibility@TownBase@@QEAAXPEAVBuilding@@H@Z endp

; TownBase::resetBuildingsFloorVisibility();
?resetBuildingsFloorVisibility@TownBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+68*8]
?resetBuildingsFloorVisibility@TownBase@@QEAAXXZ endp

; TownBase::getTownFloorVisiblity();
?getTownFloorVisiblity@TownBase@@QEBAHXZ proc EXPORT
jmp function_pointers[_TownBase_base+69*8]
?getTownFloorVisiblity@TownBase@@QEBAHXZ endp

; TownBase::setTownFloorVisiblity(int, bool);
?setTownFloorVisiblity@TownBase@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+70*8]
?setTownFloorVisiblity@TownBase@@QEAAXH_N@Z endp

; TownBase::resetTownFloorVisibility();
?resetTownFloorVisibility@TownBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+71*8]
?resetTownFloorVisibility@TownBase@@QEAAXXZ endp

?_NV_getCurrentTownLocation@TownBase@@QEAAPEAV1@XZ proc EXPORT
?_NV_getCurrentTownLocation@TownBase@@QEAAPEAV1@XZ endp

; TownBase::getCurrentTownLocation();
?getCurrentTownLocation@TownBase@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_TownBase_base+72*8]
?getCurrentTownLocation@TownBase@@UEAAPEAV1@XZ endp

; TownBase::delayedSpawningChecks();
?delayedSpawningChecks@TownBase@@SAHXZ proc EXPORT
jmp function_pointers[_TownBase_base+73*8]
?delayedSpawningChecks@TownBase@@SAHXZ endp

; TownBase::getZonesCoverage();
?getZonesCoverage@TownBase@@QEBAAEBV?$unordered_set@PEAVZoneMap@@U?$hash@PEAVZoneMap@@@boost@@U?$equal_to@PEAVZoneMap@@@std@@V?$STLAllocator@PEAVZoneMap@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+74*8]
?getZonesCoverage@TownBase@@QEBAAEBV?$unordered_set@PEAVZoneMap@@U?$hash@PEAVZoneMap@@@boost@@U?$equal_to@PEAVZoneMap@@@std@@V?$STLAllocator@PEAVZoneMap@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@unordered@boost@@XZ endp

; TownBase::clearDelayedItemLoadingMessages();
?clearDelayedItemLoadingMessages@TownBase@@SAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+75*8]
?clearDelayedItemLoadingMessages@TownBase@@SAXXZ endp

?_NV_getMapMarker@TownBase@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getMapMarker@TownBase@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; TownBase::getMapMarker();
?getMapMarker@TownBase@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+76*8]
?getMapMarker@TownBase@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getMapMarkerZoomLevel@TownBase@@QEAA?AW4MapZoomLevel@@XZ proc EXPORT
?_NV_getMapMarkerZoomLevel@TownBase@@QEAA?AW4MapZoomLevel@@XZ endp

; TownBase::getMapMarkerZoomLevel();
?getMapMarkerZoomLevel@TownBase@@UEAA?AW4MapZoomLevel@@XZ proc EXPORT
jmp function_pointers[_TownBase_base+77*8]
?getMapMarkerZoomLevel@TownBase@@UEAA?AW4MapZoomLevel@@XZ endp

; TownBase::addOccupier(const class hand &);
?addOccupier@TownBase@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+78*8]
?addOccupier@TownBase@@QEAAXAEBVhand@@@Z endp

; TownBase::removeOccupier(const class hand &);
?removeOccupier@TownBase@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+79*8]
?removeOccupier@TownBase@@QEAAXAEBVhand@@@Z endp

; TownBase::isOccupied();
?isOccupied@TownBase@@QEAA_NXZ proc EXPORT
jmp function_pointers[_TownBase_base+80*8]
?isOccupied@TownBase@@QEAA_NXZ endp

?_NV__nestUpThisSpot@TownBase@@QEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
?_NV__nestUpThisSpot@TownBase@@QEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z endp

; TownBase::_nestUpThisSpot(class GameData *, const class Ogre::Vector3 &, class Building *);
?_nestUpThisSpot@TownBase@@UEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TownBase_base+81*8]
?_nestUpThisSpot@TownBase@@UEAAXPEAVGameData@@AEBVVector3@Ogre@@PEAVBuilding@@@Z endp

; TownBase::spawnDebris(class NestBatcher *, class GameData *, class GameData *, class Ogre::Vector3, float, int, float, class Building *, bool);
?spawnDebris@TownBase@@QEAAXPEAVNestBatcher@@PEAVGameData@@1VVector3@Ogre@@MHMPEAVBuilding@@_N@Z proc EXPORT
jmp function_pointers[_TownBase_base+82*8]
?spawnDebris@TownBase@@QEAAXPEAVNestBatcher@@PEAVGameData@@1VVector3@Ogre@@MHMPEAVBuilding@@_N@Z endp

; TownBase::distributeArtifacts();
?distributeArtifacts@TownBase@@QEAAXXZ proc EXPORT
jmp function_pointers[_TownBase_base+83*8]
?distributeArtifacts@TownBase@@QEAAXXZ endp
