
?_CONSTRUCTOR@TownBuildingsManager@@QEAAPEAV1@PEAVTownBase@@@Z proc EXPORT
?_CONSTRUCTOR@TownBuildingsManager@@QEAAPEAV1@PEAVTownBase@@@Z endp

; TownBuildingsManager::TownBuildingsManager(class TownBase *);
??0TownBuildingsManager@@QEAA@PEAVTownBase@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+0*8]
??0TownBuildingsManager@@QEAA@PEAVTownBase@@@Z endp

?_DESTRUCTOR@TownBuildingsManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TownBuildingsManager@@QEAAXXZ endp

; TownBuildingsManager::~TownBuildingsManager();
??1TownBuildingsManager@@UEAA@XZ proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+1*8]
??1TownBuildingsManager@@UEAA@XZ endp

; TownBuildingsManager::clear();
?clear@TownBuildingsManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+2*8]
?clear@TownBuildingsManager@@QEAAXXZ endp

; TownBuildingsManager::moveBuildingsTo(class TownBuildingsManager *);
?moveBuildingsTo@TownBuildingsManager@@QEAAXPEAV1@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+3*8]
?moveBuildingsTo@TownBuildingsManager@@QEAAXPEAV1@@Z endp

; TownBuildingsManager::addEntity(class Building *, class Ogre::MovableObject *, int, bool, bool);
?addEntity@TownBuildingsManager@@QEAAPEAVMovableObject@Ogre@@PEAVBuilding@@PEAV23@H_N2@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+4*8]
?addEntity@TownBuildingsManager@@QEAAPEAVMovableObject@Ogre@@PEAVBuilding@@PEAV23@H_N2@Z endp

; TownBuildingsManager::removeEntity(class Ogre::FastArray<Ogre::MovableObject *> &, class Ogre::MovableObject *);
?removeEntity@TownBuildingsManager@@SA_NAEAV?$FastArray@PEAVMovableObject@Ogre@@@Ogre@@PEAVMovableObject@3@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+5*8]
?removeEntity@TownBuildingsManager@@SA_NAEAV?$FastArray@PEAVMovableObject@Ogre@@@Ogre@@PEAVMovableObject@3@@Z endp

; TownBuildingsManager::removeEntity(class Building *, class Ogre::MovableObject *);
?removeEntity@TownBuildingsManager@@QEAAXPEAVBuilding@@PEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+6*8]
?removeEntity@TownBuildingsManager@@QEAAXPEAVBuilding@@PEAVMovableObject@Ogre@@@Z endp

; TownBuildingsManager::removeBuilding(class Building *);
?removeBuilding@TownBuildingsManager@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+7*8]
?removeBuilding@TownBuildingsManager@@QEAAXPEAVBuilding@@@Z endp

; TownBuildingsManager::switchInstancing(class Building *, class Ogre::MovableObject * &, int, bool);
?switchInstancing@TownBuildingsManager@@QEAA_NPEAVBuilding@@AEAPEAVMovableObject@Ogre@@H_N@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+8*8]
?switchInstancing@TownBuildingsManager@@QEAA_NPEAVBuilding@@AEAPEAVMovableObject@Ogre@@H_N@Z endp

; TownBuildingsManager::addInteriorShell(class Building *, class Ogre::MovableObject *, int);
?addInteriorShell@TownBuildingsManager@@QEAAXPEAVBuilding@@PEAVMovableObject@Ogre@@H@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+9*8]
?addInteriorShell@TownBuildingsManager@@QEAAXPEAVBuilding@@PEAVMovableObject@Ogre@@H@Z endp

; TownBuildingsManager::removeInteriorShell(class Building *, class Ogre::MovableObject *, int);
?removeInteriorShell@TownBuildingsManager@@QEAAXPEAVBuilding@@PEAVMovableObject@Ogre@@H@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+10*8]
?removeInteriorShell@TownBuildingsManager@@QEAAXPEAVBuilding@@PEAVMovableObject@Ogre@@H@Z endp

; TownBuildingsManager::setFloorVisible(class Building *, int);
?setFloorVisible@TownBuildingsManager@@QEAAXPEAVBuilding@@H@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+11*8]
?setFloorVisible@TownBuildingsManager@@QEAAXPEAVBuilding@@H@Z endp

; TownBuildingsManager::getFloorVisible(class Building *);
?getFloorVisible@TownBuildingsManager@@QEBAHPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+12*8]
?getFloorVisible@TownBuildingsManager@@QEBAHPEAVBuilding@@@Z endp

; TownBuildingsManager::getFloorVisible(class Building *, int);
?getFloorVisible@TownBuildingsManager@@QEBA_NPEAVBuilding@@H@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+13*8]
?getFloorVisible@TownBuildingsManager@@QEBA_NPEAVBuilding@@H@Z endp

; TownBuildingsManager::setAllVisible(int, bool);
?setAllVisible@TownBuildingsManager@@QEAAXH_N@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+14*8]
?setAllVisible@TownBuildingsManager@@QEAAXH_N@Z endp

; TownBuildingsManager::resetAllVisible();
?resetAllVisible@TownBuildingsManager@@QEAAXXZ proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+15*8]
?resetAllVisible@TownBuildingsManager@@QEAAXXZ endp

; TownBuildingsManager::setSignsVisible(bool);
?setSignsVisible@TownBuildingsManager@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+16*8]
?setSignsVisible@TownBuildingsManager@@QEAAX_N@Z endp

?_NV_factoryObjectCreatedCallback@TownBuildingsManager@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_factoryObjectCreatedCallback@TownBuildingsManager@@QEAAXPEAVRootObject@@@Z endp

; TownBuildingsManager::factoryObjectCreatedCallback(class RootObject *);
?factoryObjectCreatedCallback@TownBuildingsManager@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+17*8]
?factoryObjectCreatedCallback@TownBuildingsManager@@UEAAXPEAVRootObject@@@Z endp

; TownBuildingsManager::isInstanced(class Ogre::MovableObject *);
?isInstanced@TownBuildingsManager@@SA_NPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+18*8]
?isInstanced@TownBuildingsManager@@SA_NPEAVMovableObject@Ogre@@@Z endp

; TownBuildingsManager::isEntity(class Ogre::MovableObject *);
?isEntity@TownBuildingsManager@@SA_NPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+19*8]
?isEntity@TownBuildingsManager@@SA_NPEAVMovableObject@Ogre@@@Z endp

; TownBuildingsManager::makeInstance(class Ogre::MovableObject * &);
?makeInstance@TownBuildingsManager@@QEAA_NAEAPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+20*8]
?makeInstance@TownBuildingsManager@@QEAA_NAEAPEAVMovableObject@Ogre@@@Z endp

; TownBuildingsManager::makeEntity(class Ogre::MovableObject * &);
?makeEntity@TownBuildingsManager@@QEAA_NAEAPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_base+21*8]
?makeEntity@TownBuildingsManager@@QEAA_NAEAPEAVMovableObject@Ogre@@@Z endp
