
?_CONSTRUCTOR@BuildingInfo@TownBuildingsManager@@QEAAPEAV12@AEBU12@@Z proc EXPORT
?_CONSTRUCTOR@BuildingInfo@TownBuildingsManager@@QEAAPEAV12@AEBU12@@Z endp

; TownBuildingsManager::BuildingInfo::BuildingInfo(const struct TownBuildingsManager::BuildingInfo &);
??0BuildingInfo@TownBuildingsManager@@QEAA@AEBU01@@Z proc EXPORT
jmp function_pointers[_TownBuildingsManager_BuildingInfo_base+0*8]
??0BuildingInfo@TownBuildingsManager@@QEAA@AEBU01@@Z endp

?_CONSTRUCTOR@BuildingInfo@TownBuildingsManager@@QEAAPEAV12@XZ proc EXPORT
?_CONSTRUCTOR@BuildingInfo@TownBuildingsManager@@QEAAPEAV12@XZ endp

; TownBuildingsManager::BuildingInfo::BuildingInfo();
??0BuildingInfo@TownBuildingsManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_TownBuildingsManager_BuildingInfo_base+1*8]
??0BuildingInfo@TownBuildingsManager@@QEAA@XZ endp

?_DESTRUCTOR@BuildingInfo@TownBuildingsManager@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BuildingInfo@TownBuildingsManager@@QEAAXXZ endp

; TownBuildingsManager::BuildingInfo::~BuildingInfo();
??1BuildingInfo@TownBuildingsManager@@QEAA@XZ proc EXPORT
jmp function_pointers[_TownBuildingsManager_BuildingInfo_base+2*8]
??1BuildingInfo@TownBuildingsManager@@QEAA@XZ endp
