
; TradeCulture::reset();
?reset@TradeCulture@@QEAAXXZ proc EXPORT
jmp function_pointers[_TradeCulture_base+0*8]
?reset@TradeCulture@@QEAAXXZ endp

; TradeCulture::setupTradeCulture(class GameData *);
?setupTradeCulture@TradeCulture@@QEAAXPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TradeCulture_base+1*8]
?setupTradeCulture@TradeCulture@@QEAAXPEAVGameData@@@Z endp

; TradeCulture::getForbiddenItemsList();
?getForbiddenItemsList@TradeCulture@@QEBAAEBV?$lektor@PEAVGameData@@@@XZ proc EXPORT
jmp function_pointers[_TradeCulture_base+2*8]
?getForbiddenItemsList@TradeCulture@@QEBAAEBV?$lektor@PEAVGameData@@@@XZ endp

; TradeCulture::isItemIllegal(class GameData *);
?isItemIllegal@TradeCulture@@QEBA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TradeCulture_base+3*8]
?isItemIllegal@TradeCulture@@QEBA_NPEAVGameData@@@Z endp

; TradeCulture::getAllIllegalItems();
?getAllIllegalItems@TradeCulture@@QEBAPEBV?$set@PEAVGameData@@U?$less@PEAVGameData@@@std@@V?$STLAllocator@PEAVGameData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@XZ proc EXPORT
jmp function_pointers[_TradeCulture_base+4*8]
?getAllIllegalItems@TradeCulture@@QEBAPEBV?$set@PEAVGameData@@U?$less@PEAVGameData@@@std@@V?$STLAllocator@PEAVGameData@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@XZ endp

; TradeCulture::getTradePriceMultiplier(class GameData *);
?getTradePriceMultiplier@TradeCulture@@QEAAMPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TradeCulture_base+5*8]
?getTradePriceMultiplier@TradeCulture@@QEAAMPEAVGameData@@@Z endp

; TradeCulture::hasTradePriceMultiplier(class GameData *);
?hasTradePriceMultiplier@TradeCulture@@QEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_TradeCulture_base+6*8]
?hasTradePriceMultiplier@TradeCulture@@QEAA_NPEAVGameData@@@Z endp

?_CONSTRUCTOR@TradeCulture@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TradeCulture@@QEAAPEAV1@XZ endp

; TradeCulture::TradeCulture();
??0TradeCulture@@QEAA@XZ proc EXPORT
jmp function_pointers[_TradeCulture_base+7*8]
??0TradeCulture@@QEAA@XZ endp

?_DESTRUCTOR@TradeCulture@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TradeCulture@@QEAAXXZ endp

; TradeCulture::~TradeCulture();
??1TradeCulture@@QEAA@XZ proc EXPORT
jmp function_pointers[_TradeCulture_base+8*8]
??1TradeCulture@@QEAA@XZ endp
