
?_CONSTRUCTOR@TraderInventoryLayout@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TraderInventoryLayout@@QEAAPEAV1@XZ endp

; TraderInventoryLayout::TraderInventoryLayout();
??0TraderInventoryLayout@@QEAA@XZ proc EXPORT
jmp function_pointers[_TraderInventoryLayout_base+0*8]
??0TraderInventoryLayout@@QEAA@XZ endp

; symbol is too long
; ?setupSections@TraderInventoryLayout@@UEAAXPEAVInventoryGUI@@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; TraderInventoryLayout::setupSections(class InventoryGUI *, class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
TraderInventoryLayout_setupSections_PLACEHOLDER proc EXPORT
jmp function_pointers[_TraderInventoryLayout_base+1*8]
TraderInventoryLayout_setupSections_PLACEHOLDER endp

; symbol is too long
; ?resize@TraderInventoryLayout@@QEAAXAEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$STLAllocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVInventorySectionGUI@@@std@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@PEAVInventory@@@Z
; TraderInventoryLayout::resize(class std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,InventorySectionGUI *,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,Ogre::STLAllocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,InventorySectionGUI *>,Ogre::CategorisedAllocPolicy<0> > > &, class Inventory *);
TraderInventoryLayout_resize_PLACEHOLDER proc EXPORT
jmp function_pointers[_TraderInventoryLayout_base+2*8]
TraderInventoryLayout_resize_PLACEHOLDER endp

; TraderInventoryLayout::notifyMouseWheel(class MyGUI::Widget *, int);
?notifyMouseWheel@TraderInventoryLayout@@QEAAXPEAVWidget@MyGUI@@H@Z proc EXPORT
jmp function_pointers[_TraderInventoryLayout_base+3*8]
?notifyMouseWheel@TraderInventoryLayout@@QEAAXPEAVWidget@MyGUI@@H@Z endp

?_DESTRUCTOR@TraderInventoryLayout@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TraderInventoryLayout@@QEAAXXZ endp

; TraderInventoryLayout::~TraderInventoryLayout();
??1TraderInventoryLayout@@UEAA@XZ proc EXPORT
jmp function_pointers[_TraderInventoryLayout_base+4*8]
??1TraderInventoryLayout@@UEAA@XZ endp
