
; TransformWindow::getSingleton();
?getSingleton@TransformWindow@@SAPEAV1@XZ proc EXPORT
jmp function_pointers[_TransformWindow_base+0*8]
?getSingleton@TransformWindow@@SAPEAV1@XZ endp

?_CONSTRUCTOR@TransformWindow@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TransformWindow@@QEAAPEAV1@XZ endp

; TransformWindow::TransformWindow();
??0TransformWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_TransformWindow_base+1*8]
??0TransformWindow@@QEAA@XZ endp

?_DESTRUCTOR@TransformWindow@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TransformWindow@@QEAAXXZ endp

; TransformWindow::~TransformWindow();
??1TransformWindow@@QEAA@XZ proc EXPORT
jmp function_pointers[_TransformWindow_base+2*8]
??1TransformWindow@@QEAA@XZ endp

; TransformWindow::show(class Ogre::SceneNode *, class Ogre::Vector3 *, class Ogre::Quaternion *, class Ogre::Vector3 *, class Ogre::SceneNode *);
?show@TransformWindow@@QEAAXPEAVSceneNode@Ogre@@PEAVVector3@3@PEAVQuaternion@3@10@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+3*8]
?show@TransformWindow@@QEAAXPEAVSceneNode@Ogre@@PEAVVector3@3@PEAVQuaternion@3@10@Z endp

; TransformWindow::setCaption(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setCaption@TransformWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+4*8]
?setCaption@TransformWindow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; TransformWindow::updateState(const class InstanceID *);
?updateState@TransformWindow@@QEAAXPEBVInstanceID@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+5*8]
?updateState@TransformWindow@@QEAAXPEBVInstanceID@@@Z endp

; TransformWindow::close();
?close@TransformWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+6*8]
?close@TransformWindow@@QEAAXXZ endp

; TransformWindow::refresh();
?refresh@TransformWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+7*8]
?refresh@TransformWindow@@QEAAXXZ endp

; TransformWindow::updateGizmo();
?updateGizmo@TransformWindow@@QEAA_NXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+8*8]
?updateGizmo@TransformWindow@@QEAA_NXZ endp

; TransformWindow::isActive();
?isActive@TransformWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+9*8]
?isActive@TransformWindow@@QEBA_NXZ endp

; TransformWindow::isVisible();
?isVisible@TransformWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+10*8]
?isVisible@TransformWindow@@QEBA_NXZ endp

; TransformWindow::hasChanged();
?hasChanged@TransformWindow@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+11*8]
?hasChanged@TransformWindow@@QEBA_NXZ endp

; TransformWindow::clearChangedFlag();
?clearChangedFlag@TransformWindow@@QEAAXXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+12*8]
?clearChangedFlag@TransformWindow@@QEAAXXZ endp

; TransformWindow::getMode();
?getMode@TransformWindow@@QEBAHXZ proc EXPORT
jmp function_pointers[_TransformWindow_base+13*8]
?getMode@TransformWindow@@QEBAHXZ endp

; TransformWindow::setMode(int);
?setMode@TransformWindow@@QEAA_NH@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+14*8]
?setMode@TransformWindow@@QEAA_NH@Z endp

; TransformWindow::getLastZone();
?getLastZone@TransformWindow@@QEBAPEAVZoneMap@@XZ proc EXPORT
jmp function_pointers[_TransformWindow_base+15*8]
?getLastZone@TransformWindow@@QEBAPEAVZoneMap@@XZ endp

; TransformWindow::getZone();
?getZone@TransformWindow@@QEBAPEAVZoneMap@@XZ proc EXPORT
jmp function_pointers[_TransformWindow_base+16*8]
?getZone@TransformWindow@@QEBAPEAVZoneMap@@XZ endp

; TransformWindow::changeMode(class DataPanelLine *);
?changeMode@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+17*8]
?changeMode@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; TransformWindow::changeCoord(class DataPanelLine *);
?changeCoord@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+18*8]
?changeCoord@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; TransformWindow::changeValue(class DataPanelLine *);
?changeValue@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+19*8]
?changeValue@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; TransformWindow::confirmValue(class MyGUI::Widget *, class MyGUI::Widget *);
?confirmValue@TransformWindow@@QEAAXPEAVWidget@MyGUI@@0@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+20*8]
?confirmValue@TransformWindow@@QEAAXPEAVWidget@MyGUI@@0@Z endp

; TransformWindow::reset(class DataPanelLine *);
?reset@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+21*8]
?reset@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; TransformWindow::revert(class DataPanelLine *);
?revert@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+22*8]
?revert@TransformWindow@@QEAAXPEAVDataPanelLine@@@Z endp

; TransformWindow::hide(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?hide@TransformWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_TransformWindow_base+23*8]
?hide@TransformWindow@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
