
?_CONSTRUCTOR@TripleInt@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@TripleInt@@QEAAPEAV1@AEBV1@@Z endp

; TripleInt::TripleInt(const class TripleInt &);
??0TripleInt@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_TripleInt_base+0*8]
??0TripleInt@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@TripleInt@@QEAAPEAV1@HHH@Z proc EXPORT
?_CONSTRUCTOR@TripleInt@@QEAAPEAV1@HHH@Z endp

; TripleInt::TripleInt(int, int, int);
??0TripleInt@@QEAA@HHH@Z proc EXPORT
jmp function_pointers[_TripleInt_base+1*8]
??0TripleInt@@QEAA@HHH@Z endp

?_CONSTRUCTOR@TripleInt@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TripleInt@@QEAAPEAV1@XZ endp

; TripleInt::TripleInt();
??0TripleInt@@QEAA@XZ proc EXPORT
jmp function_pointers[_TripleInt_base+2*8]
??0TripleInt@@QEAA@XZ endp

; TripleInt::operator=(const class TripleInt &);
??4TripleInt@@QEAAAEBV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_TripleInt_base+3*8]
??4TripleInt@@QEAAAEBV0@AEBV0@@Z endp

; TripleInt::operator[](int);
??ATripleInt@@QEBAHH@Z proc EXPORT
jmp function_pointers[_TripleInt_base+4*8]
??ATripleInt@@QEBAHH@Z endp

; TripleInt::operator[](int);
??ATripleInt@@QEAAAEAHH@Z proc EXPORT
jmp function_pointers[_TripleInt_base+5*8]
??ATripleInt@@QEAAAEAHH@Z endp
