
?_CONSTRUCTOR@TurretBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@TurretBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; TurretBuilding::TurretBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0TurretBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+0*8]
??0TurretBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@TurretBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::~TurretBuilding();
??1TurretBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+1*8]
??1TurretBuilding@@UEAA@XZ endp

?_NV_getDefaultTask@TurretBuilding@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@TurretBuilding@@QEAA?AW4TaskType@@XZ endp

; TurretBuilding::getDefaultTask();
?getDefaultTask@TurretBuilding@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+2*8]
?getDefaultTask@TurretBuilding@@UEAA?AW4TaskType@@XZ endp

?_NV_setup@TurretBuilding@@QEAAXXZ proc EXPORT
?_NV_setup@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::setup();
?setup@TurretBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+3*8]
?setup@TurretBuilding@@UEAAXXZ endp

?_NV_update@TurretBuilding@@QEAAXXZ proc EXPORT
?_NV_update@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::update();
?update@TurretBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+4*8]
?update@TurretBuilding@@UEAAXXZ endp

?_NV_needsUpdate@TurretBuilding@@QEAA_NXZ proc EXPORT
?_NV_needsUpdate@TurretBuilding@@QEAA_NXZ endp

; TurretBuilding::needsUpdate();
?needsUpdate@TurretBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+5*8]
?needsUpdate@TurretBuilding@@UEAA_NXZ endp

?_NV_operate@TurretBuilding@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@TurretBuilding@@QEAAXPEAVCharacter@@M@Z endp

; TurretBuilding::operate(class Character *, float);
?operate@TurretBuilding@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+6*8]
?operate@TurretBuilding@@UEAAXPEAVCharacter@@M@Z endp

; TurretBuilding::getStatUsed();
?getStatUsed@TurretBuilding@@QEBA?AW4StatsEnumerated@@XZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+7*8]
?getStatUsed@TurretBuilding@@QEBA?AW4StatsEnumerated@@XZ endp

?_NV_getProductionMultForGUI@TurretBuilding@@QEAAMXZ proc EXPORT
?_NV_getProductionMultForGUI@TurretBuilding@@QEAAMXZ endp

; TurretBuilding::getProductionMultForGUI();
?getProductionMultForGUI@TurretBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+8*8]
?getProductionMultForGUI@TurretBuilding@@UEAAMXZ endp

?_NV_getGUIToolTipForGroundResourceEfficiency@TurretBuilding@@QEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
?_NV_getGUIToolTipForGroundResourceEfficiency@TurretBuilding@@QEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; TurretBuilding::getGUIToolTipForGroundResourceEfficiency(class lektor<StringPair> &);
?getGUIToolTipForGroundResourceEfficiency@TurretBuilding@@UEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+9*8]
?getGUIToolTipForGroundResourceEfficiency@TurretBuilding@@UEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; TurretBuilding::aimAt(const class Ogre::Vector3 &);
?aimAt@TurretBuilding@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+10*8]
?aimAt@TurretBuilding@@QEAAXAEBVVector3@Ogre@@@Z endp

?_NV_setVisible@TurretBuilding@@QEAAX_N@Z proc EXPORT
?_NV_setVisible@TurretBuilding@@QEAAX_N@Z endp

; TurretBuilding::setVisible(bool);
?setVisible@TurretBuilding@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+11*8]
?setVisible@TurretBuilding@@UEAAX_N@Z endp

; TurretBuilding::setMountedBuilding(class Building *);
?setMountedBuilding@TurretBuilding@@QEAAXPEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+12*8]
?setMountedBuilding@TurretBuilding@@QEAAXPEAVBuilding@@@Z endp

?_NV_getMountedBuilding@TurretBuilding@@QEBAAEBVhand@@XZ proc EXPORT
?_NV_getMountedBuilding@TurretBuilding@@QEBAAEBVhand@@XZ endp

; TurretBuilding::getMountedBuilding();
?getMountedBuilding@TurretBuilding@@UEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+13*8]
?getMountedBuilding@TurretBuilding@@UEBAAEBVhand@@XZ endp

?_NV_amInsideTownWalls@TurretBuilding@@QEAAHXZ proc EXPORT
?_NV_amInsideTownWalls@TurretBuilding@@QEAAHXZ endp

; TurretBuilding::amInsideTownWalls();
?amInsideTownWalls@TurretBuilding@@UEAAHXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+14*8]
?amInsideTownWalls@TurretBuilding@@UEAAHXZ endp

?_NV_notifyConstructionComplete@TurretBuilding@@QEAAXXZ proc EXPORT
?_NV_notifyConstructionComplete@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::notifyConstructionComplete();
?notifyConstructionComplete@TurretBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+15*8]
?notifyConstructionComplete@TurretBuilding@@UEAAXXZ endp

?_NV_createPhysical@TurretBuilding@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@TurretBuilding@@QEAA_NXZ endp

; TurretBuilding::createPhysical();
?createPhysical@TurretBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+16*8]
?createPhysical@TurretBuilding@@UEAA_NXZ endp

?_NV_destroyPhysical@TurretBuilding@@QEAAXXZ proc EXPORT
?_NV_destroyPhysical@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::destroyPhysical();
?destroyPhysical@TurretBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+17*8]
?destroyPhysical@TurretBuilding@@UEAAXXZ endp

?_NV_onBuildingLoaded@TurretBuilding@@QEAAXXZ proc EXPORT
?_NV_onBuildingLoaded@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::onBuildingLoaded();
?onBuildingLoaded@TurretBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+18*8]
?onBuildingLoaded@TurretBuilding@@UEAAXXZ endp

; TurretBuilding::addToBuildingsMananger(class Ogre::MovableObject * &);
?addToBuildingsMananger@TurretBuilding@@QEAAXAEAPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+19*8]
?addToBuildingsMananger@TurretBuilding@@QEAAXAEAPEAVMovableObject@Ogre@@@Z endp

; TurretBuilding::removeFromBuildingsMananger(class Ogre::MovableObject * &);
?removeFromBuildingsMananger@TurretBuilding@@QEAAXAEAPEAVMovableObject@Ogre@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+20*8]
?removeFromBuildingsMananger@TurretBuilding@@QEAAXAEAPEAVMovableObject@Ogre@@@Z endp

?_NV_getGUIState@TurretBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@TurretBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; TurretBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@TurretBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+21*8]
?getGUIState@TurretBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIData@TurretBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@TurretBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; TurretBuilding::getGUIData(class DatapanelGUI *, int);
?getGUIData@TurretBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+22*8]
?getGUIData@TurretBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_serialise@TurretBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@TurretBuilding@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; TurretBuilding::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@TurretBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+23*8]
?serialise@TurretBuilding@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@TurretBuilding@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@TurretBuilding@@QEAAXPEAVGameSaveState@@@Z endp

; TurretBuilding::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@TurretBuilding@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+24*8]
?loadFromSerialise@TurretBuilding@@UEAAXPEAVGameSaveState@@@Z endp

; TurretBuilding::calculatePowerMult();
?calculatePowerMult@TurretBuilding@@QEAAMXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+25*8]
?calculatePowerMult@TurretBuilding@@QEAAMXZ endp

; TurretBuilding::_teleport(const class Ogre::Vector3 &);
?_teleport@TurretBuilding@@QEAAXAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+26*8]
?_teleport@TurretBuilding@@QEAAXAEBVVector3@Ogre@@@Z endp

?_NV_clearTownBuildingsManagerPtr@TurretBuilding@@QEAAXXZ proc EXPORT
?_NV_clearTownBuildingsManagerPtr@TurretBuilding@@QEAAXXZ endp

; TurretBuilding::clearTownBuildingsManagerPtr();
?clearTownBuildingsManagerPtr@TurretBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_TurretBuilding_base+27*8]
?clearTownBuildingsManagerPtr@TurretBuilding@@UEAAXXZ endp

?_NV_setPartVisible@TurretBuilding@@QEAAXPEAVPhysicalEntity@@_N@Z proc EXPORT
?_NV_setPartVisible@TurretBuilding@@QEAAXPEAVPhysicalEntity@@_N@Z endp

; TurretBuilding::setPartVisible(class PhysicalEntity *, bool);
?setPartVisible@TurretBuilding@@UEAAXPEAVPhysicalEntity@@_N@Z proc EXPORT
jmp function_pointers[_TurretBuilding_base+28*8]
?setPartVisible@TurretBuilding@@UEAAXPEAVPhysicalEntity@@_N@Z endp
