
?_CONSTRUCTOR@TutorialItem@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TutorialItem@@QEAAPEAV1@XZ endp

; TutorialItem::TutorialItem();
??0TutorialItem@@QEAA@XZ proc EXPORT
jmp function_pointers[_TutorialItem_base+0*8]
??0TutorialItem@@QEAA@XZ endp

?_DESTRUCTOR@TutorialItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TutorialItem@@QEAAXXZ endp

; TutorialItem::~TutorialItem();
??1TutorialItem@@UEAA@XZ proc EXPORT
jmp function_pointers[_TutorialItem_base+1*8]
??1TutorialItem@@UEAA@XZ endp

; TutorialItem::getId();
?getId@TutorialItem@@QEBAIXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+2*8]
?getId@TutorialItem@@QEBAIXZ endp

; TutorialItem::getTitle();
?getTitle@TutorialItem@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_TutorialItem_base+3*8]
?getTitle@TutorialItem@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; TutorialItem::isLastSubItem();
?isLastSubItem@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+4*8]
?isLastSubItem@TutorialItem@@QEBA_NXZ endp

; TutorialItem::isSkippable();
?isSkippable@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+5*8]
?isSkippable@TutorialItem@@QEBA_NXZ endp

; TutorialItem::isActive();
?isActive@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+6*8]
?isActive@TutorialItem@@QEBA_NXZ endp

; TutorialItem::hasEnded();
?hasEnded@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+7*8]
?hasEnded@TutorialItem@@QEBA_NXZ endp

; TutorialItem::getCurrentSubItem();
?getCurrentSubItem@TutorialItem@@QEBAPEAVTutorialSubItem@@XZ proc EXPORT
jmp function_pointers[_TutorialItem_base+8*8]
?getCurrentSubItem@TutorialItem@@QEBAPEAVTutorialSubItem@@XZ endp

; TutorialItem::getSubItemAt(int);
?getSubItemAt@TutorialItem@@QEBAPEAVTutorialSubItem@@H@Z proc EXPORT
jmp function_pointers[_TutorialItem_base+9*8]
?getSubItemAt@TutorialItem@@QEBAPEAVTutorialSubItem@@H@Z endp

; TutorialItem::getCurrentSubItemIndex();
?getCurrentSubItemIndex@TutorialItem@@QEBAHXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+10*8]
?getCurrentSubItemIndex@TutorialItem@@QEBAHXZ endp

; TutorialItem::getNumSubItems();
?getNumSubItems@TutorialItem@@QEBAHXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+11*8]
?getNumSubItems@TutorialItem@@QEBAHXZ endp

; TutorialItem::hasNextSubItem();
?hasNextSubItem@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+12*8]
?hasNextSubItem@TutorialItem@@QEBA_NXZ endp

; TutorialItem::hasPrevSubItem();
?hasPrevSubItem@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+13*8]
?hasPrevSubItem@TutorialItem@@QEBA_NXZ endp

; TutorialItem::nextSubItem();
?nextSubItem@TutorialItem@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+14*8]
?nextSubItem@TutorialItem@@QEAAXXZ endp

; TutorialItem::prevSubItem();
?prevSubItem@TutorialItem@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+15*8]
?prevSubItem@TutorialItem@@QEAAXXZ endp

; TutorialItem::getStarted();
?getStarted@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+16*8]
?getStarted@TutorialItem@@QEBA_NXZ endp

; TutorialItem::getEnded();
?getEnded@TutorialItem@@QEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+17*8]
?getEnded@TutorialItem@@QEBA_NXZ endp

?_NV_reset@TutorialItem@@QEAAXXZ proc EXPORT
?_NV_reset@TutorialItem@@QEAAXXZ endp

; TutorialItem::reset();
?reset@TutorialItem@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+18*8]
?reset@TutorialItem@@UEAAXXZ endp

?_NV_start@TutorialItem@@QEAAXXZ proc EXPORT
?_NV_start@TutorialItem@@QEAAXXZ endp

; TutorialItem::start();
?start@TutorialItem@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+19*8]
?start@TutorialItem@@UEAAXXZ endp

?_NV_run@TutorialItem@@QEAA_NXZ proc EXPORT
?_NV_run@TutorialItem@@QEAA_NXZ endp

; TutorialItem::run();
?run@TutorialItem@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+20*8]
?run@TutorialItem@@UEAA_NXZ endp

?_NV_end@TutorialItem@@QEAAXXZ proc EXPORT
?_NV_end@TutorialItem@@QEAAXXZ endp

; TutorialItem::end();
?end@TutorialItem@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialItem_base+21*8]
?end@TutorialItem@@UEAAXXZ endp
