
?_CONSTRUCTOR@TutorialGUILine@TutorialGUI@@QEAAPEAV12@PEAVWidget@MyGUI@@PEAVTutorialItem@@_N@Z proc EXPORT
?_CONSTRUCTOR@TutorialGUILine@TutorialGUI@@QEAAPEAV12@PEAVWidget@MyGUI@@PEAVTutorialItem@@_N@Z endp

; TutorialGUI::TutorialGUILine::TutorialGUILine(class MyGUI::Widget *, class TutorialItem *, bool);
??0TutorialGUILine@TutorialGUI@@QEAA@PEAVWidget@MyGUI@@PEAVTutorialItem@@_N@Z proc EXPORT
jmp function_pointers[_TutorialGUI_TutorialGUILine_base+0*8]
??0TutorialGUILine@TutorialGUI@@QEAA@PEAVWidget@MyGUI@@PEAVTutorialItem@@_N@Z endp

; TutorialGUI::TutorialGUILine::updateHighlight(float);
?updateHighlight@TutorialGUILine@TutorialGUI@@QEAA_NM@Z proc EXPORT
jmp function_pointers[_TutorialGUI_TutorialGUILine_base+1*8]
?updateHighlight@TutorialGUILine@TutorialGUI@@QEAA_NM@Z endp

?_DESTRUCTOR@TutorialGUILine@TutorialGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TutorialGUILine@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::TutorialGUILine::~TutorialGUILine();
??1TutorialGUILine@TutorialGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_TutorialGUI_TutorialGUILine_base+2*8]
??1TutorialGUILine@TutorialGUI@@UEAA@XZ endp
