
?_NV_show@TutorialpediaGUI@@QEAAX_N@Z proc EXPORT
?_NV_show@TutorialpediaGUI@@QEAAX_N@Z endp

; TutorialpediaGUI::show(bool);
?show@TutorialpediaGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+0*8]
?show@TutorialpediaGUI@@UEAAX_N@Z endp

?_NV_clear@TutorialpediaGUI@@QEAAXXZ proc EXPORT
?_NV_clear@TutorialpediaGUI@@QEAAXXZ endp

; TutorialpediaGUI::clear();
?clear@TutorialpediaGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+1*8]
?clear@TutorialpediaGUI@@UEAAXXZ endp

?_NV_isVisible@TutorialpediaGUI@@QEBA_NXZ proc EXPORT
?_NV_isVisible@TutorialpediaGUI@@QEBA_NXZ endp

; TutorialpediaGUI::isVisible();
?isVisible@TutorialpediaGUI@@UEBA_NXZ proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+2*8]
?isVisible@TutorialpediaGUI@@UEBA_NXZ endp

?_CONSTRUCTOR@TutorialpediaGUI@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TutorialpediaGUI@@QEAAPEAV1@XZ endp

; TutorialpediaGUI::TutorialpediaGUI();
??0TutorialpediaGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+3*8]
??0TutorialpediaGUI@@QEAA@XZ endp

?_DESTRUCTOR@TutorialpediaGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TutorialpediaGUI@@QEAAXXZ endp

; TutorialpediaGUI::~TutorialpediaGUI();
??1TutorialpediaGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+4*8]
??1TutorialpediaGUI@@UEAA@XZ endp

; TutorialpediaGUI::setup();
?setup@TutorialpediaGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+5*8]
?setup@TutorialpediaGUI@@QEAAXXZ endp

; TutorialpediaGUI::updateCurrentItem();
?updateCurrentItem@TutorialpediaGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+6*8]
?updateCurrentItem@TutorialpediaGUI@@QEAAXXZ endp

; TutorialpediaGUI::tutorialSelectedEvent(class MyGUI::ListBox *, unsigned __int64);
?tutorialSelectedEvent@TutorialpediaGUI@@QEAAXPEAVListBox@MyGUI@@_K@Z proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+7*8]
?tutorialSelectedEvent@TutorialpediaGUI@@QEAAXPEAVListBox@MyGUI@@_K@Z endp

; TutorialpediaGUI::tutorialPrevEvent(class MyGUI::Widget *);
?tutorialPrevEvent@TutorialpediaGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+8*8]
?tutorialPrevEvent@TutorialpediaGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialpediaGUI::tutorialNextEvent(class MyGUI::Widget *);
?tutorialNextEvent@TutorialpediaGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+9*8]
?tutorialNextEvent@TutorialpediaGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialpediaGUI::tutorialActivateButtonEvent(class MyGUI::Widget *);
?tutorialActivateButtonEvent@TutorialpediaGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+10*8]
?tutorialActivateButtonEvent@TutorialpediaGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialpediaGUI::tutorialWindowButton(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?tutorialWindowButton@TutorialpediaGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_TutorialpediaGUI_base+11*8]
?tutorialWindowButton@TutorialpediaGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
