
?_CONSTRUCTOR@TutorialGUI@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@TutorialGUI@@QEAAPEAV1@XZ endp

; TutorialGUI::TutorialGUI();
??0TutorialGUI@@QEAA@XZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+0*8]
??0TutorialGUI@@QEAA@XZ endp

?_DESTRUCTOR@TutorialGUI@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::~TutorialGUI();
??1TutorialGUI@@UEAA@XZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+1*8]
??1TutorialGUI@@UEAA@XZ endp

?_NV_clear@TutorialGUI@@QEAAXXZ proc EXPORT
?_NV_clear@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::clear();
?clear@TutorialGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+2*8]
?clear@TutorialGUI@@UEAAXXZ endp

; TutorialGUI::startHighlight(enum TutorialGUI::HighlightItem);
?startHighlight@TutorialGUI@@QEAAXW4HighlightItem@1@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+3*8]
?startHighlight@TutorialGUI@@QEAAXW4HighlightItem@1@@Z endp

; TutorialGUI::endHighlight();
?endHighlight@TutorialGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+4*8]
?endHighlight@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::_setHightlightCoords();
?_setHightlightCoords@TutorialGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+5*8]
?_setHightlightCoords@TutorialGUI@@QEAAXXZ endp

?_NV_update@TutorialGUI@@QEAAXXZ proc EXPORT
?_NV_update@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::update();
?update@TutorialGUI@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+6*8]
?update@TutorialGUI@@UEAAXXZ endp

; TutorialGUI::setEnabled(bool);
?setEnabled@TutorialGUI@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+7*8]
?setEnabled@TutorialGUI@@QEAAX_N@Z endp

?_NV_show@TutorialGUI@@QEAAX_N@Z proc EXPORT
?_NV_show@TutorialGUI@@QEAAX_N@Z endp

; TutorialGUI::show(bool);
?show@TutorialGUI@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+8*8]
?show@TutorialGUI@@UEAAX_N@Z endp

; TutorialGUI::addTutorialsToList(const class std::vector<TutorialItem *,Ogre::STLAllocator<TutorialItem *,Ogre::CategorisedAllocPolicy<0> > > &, bool);
?addTutorialsToList@TutorialGUI@@QEAAXAEBV?$vector@PEAVTutorialItem@@V?$STLAllocator@PEAVTutorialItem@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@_N@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+9*8]
?addTutorialsToList@TutorialGUI@@QEAAXAEBV?$vector@PEAVTutorialItem@@V?$STLAllocator@PEAVTutorialItem@@V?$CategorisedAllocPolicy@$0A@@Ogre@@@Ogre@@@std@@_N@Z endp

; TutorialGUI::removeTutorialFromList(class TutorialItem *);
?removeTutorialFromList@TutorialGUI@@QEAAXPEAVTutorialItem@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+10*8]
?removeTutorialFromList@TutorialGUI@@QEAAXPEAVTutorialItem@@@Z endp

; TutorialGUI::arrangeList();
?arrangeList@TutorialGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+11*8]
?arrangeList@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::refreshUI();
?refreshUI@TutorialGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+12*8]
?refreshUI@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::windowButtonEvent(class MyGUI::Window *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?windowButtonEvent@TutorialGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+13*8]
?windowButtonEvent@TutorialGUI@@QEAAXPEAVWindow@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; TutorialGUI::windowPrevEvent(class MyGUI::Widget *);
?windowPrevEvent@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+14*8]
?windowPrevEvent@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialGUI::windowNextEvent(class MyGUI::Widget *);
?windowNextEvent@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+15*8]
?windowNextEvent@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialGUI::dismissButtonEvent(class MyGUI::Widget *);
?dismissButtonEvent@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+16*8]
?dismissButtonEvent@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialGUI::tooltipOpen(class MyGUI::Widget *);
?tooltipOpen@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+17*8]
?tooltipOpen@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialGUI::tooltipClose(class MyGUI::Widget *);
?tooltipClose@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+18*8]
?tooltipClose@TutorialGUI@@QEAAXPEAVWidget@MyGUI@@@Z endp

; TutorialGUI::showTutorialWindow(class TutorialItem *);
?showTutorialWindow@TutorialGUI@@QEAAXPEAVTutorialItem@@@Z proc EXPORT
jmp function_pointers[_TutorialGUI_base+19*8]
?showTutorialWindow@TutorialGUI@@QEAAXPEAVTutorialItem@@@Z endp

; TutorialGUI::closeTutorialWindow();
?closeTutorialWindow@TutorialGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+20*8]
?closeTutorialWindow@TutorialGUI@@QEAAXXZ endp

; TutorialGUI::updateCurrentItem();
?updateCurrentItem@TutorialGUI@@QEAAXXZ proc EXPORT
jmp function_pointers[_TutorialGUI_base+21*8]
?updateCurrentItem@TutorialGUI@@QEAAXXZ endp
