
?_CONSTRUCTOR@TutorialSubItem@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
?_CONSTRUCTOR@TutorialSubItem@@QEAAPEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

; TutorialSubItem::TutorialSubItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
??0TutorialSubItem@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z proc EXPORT
jmp function_pointers[_TutorialSubItem_base+0*8]
??0TutorialSubItem@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z endp

?_CONSTRUCTOR@TutorialSubItem@@QEAAPEAV1@_N@Z proc EXPORT
?_CONSTRUCTOR@TutorialSubItem@@QEAAPEAV1@_N@Z endp

; TutorialSubItem::TutorialSubItem(bool);
??0TutorialSubItem@@QEAA@_N@Z proc EXPORT
jmp function_pointers[_TutorialSubItem_base+1*8]
??0TutorialSubItem@@QEAA@_N@Z endp

?_NV_start@TutorialSubItem@@QEAAXXZ proc EXPORT
?_NV_start@TutorialSubItem@@QEAAXXZ endp

; TutorialSubItem::start();
?start@TutorialSubItem@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialSubItem_base+2*8]
?start@TutorialSubItem@@UEAAXXZ endp

?_NV_run@TutorialSubItem@@QEAA_NXZ proc EXPORT
?_NV_run@TutorialSubItem@@QEAA_NXZ endp

; TutorialSubItem::run();
?run@TutorialSubItem@@UEAA_NXZ proc EXPORT
jmp function_pointers[_TutorialSubItem_base+3*8]
?run@TutorialSubItem@@UEAA_NXZ endp

?_NV_end@TutorialSubItem@@QEAAXXZ proc EXPORT
?_NV_end@TutorialSubItem@@QEAAXXZ endp

; TutorialSubItem::end();
?end@TutorialSubItem@@UEAAXXZ proc EXPORT
jmp function_pointers[_TutorialSubItem_base+4*8]
?end@TutorialSubItem@@UEAAXXZ endp

?_DESTRUCTOR@TutorialSubItem@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@TutorialSubItem@@QEAAXXZ endp

; TutorialSubItem::~TutorialSubItem();
??1TutorialSubItem@@QEAA@XZ proc EXPORT
jmp function_pointers[_TutorialSubItem_base+5*8]
??1TutorialSubItem@@QEAA@XZ endp
