
?_CONSTRUCTOR@UseableStuff@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@UseableStuff@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; UseableStuff::UseableStuff(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0UseableStuff@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+0*8]
??0UseableStuff@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_DESTRUCTOR@UseableStuff@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@UseableStuff@@QEAAXXZ endp

; UseableStuff::~UseableStuff();
??1UseableStuff@@UEAA@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+1*8]
??1UseableStuff@@UEAA@XZ endp

?_NV_getUseableStuff@UseableStuff@@QEAAPEAV1@XZ proc EXPORT
?_NV_getUseableStuff@UseableStuff@@QEAAPEAV1@XZ endp

; UseableStuff::getUseableStuff();
?getUseableStuff@UseableStuff@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+2*8]
?getUseableStuff@UseableStuff@@UEAAPEAV1@XZ endp

?_NV_createInventoryLayout@UseableStuff@@QEAAPEAVInventoryLayout@@XZ proc EXPORT
?_NV_createInventoryLayout@UseableStuff@@QEAAPEAVInventoryLayout@@XZ endp

; UseableStuff::createInventoryLayout();
?createInventoryLayout@UseableStuff@@UEAAPEAVInventoryLayout@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+3*8]
?createInventoryLayout@UseableStuff@@UEAAPEAVInventoryLayout@@XZ endp

?_NV_equipItem@UseableStuff@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_equipItem@UseableStuff@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; UseableStuff::equipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?equipItem@UseableStuff@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+4*8]
?equipItem@UseableStuff@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_unequipItem@UseableStuff@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
?_NV_unequipItem@UseableStuff@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

; UseableStuff::unequipItem(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class Item *);
?unequipItem@UseableStuff@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+5*8]
?unequipItem@UseableStuff@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVItem@@@Z endp

?_NV_dropItem@UseableStuff@@QEAAXPEAVRootObject@@@Z proc EXPORT
?_NV_dropItem@UseableStuff@@QEAAXPEAVRootObject@@@Z endp

; UseableStuff::dropItem(class RootObject *);
?dropItem@UseableStuff@@UEAAXPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+6*8]
?dropItem@UseableStuff@@UEAAXPEAVRootObject@@@Z endp

?_NV_takeMoney@UseableStuff@@QEAA_NH@Z proc EXPORT
?_NV_takeMoney@UseableStuff@@QEAA_NH@Z endp

; UseableStuff::takeMoney(int);
?takeMoney@UseableStuff@@UEAA_NH@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+7*8]
?takeMoney@UseableStuff@@UEAA_NH@Z endp

?_NV_getMoney@UseableStuff@@QEBAHXZ proc EXPORT
?_NV_getMoney@UseableStuff@@QEBAHXZ endp

; UseableStuff::getMoney();
?getMoney@UseableStuff@@UEBAHXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+8*8]
?getMoney@UseableStuff@@UEBAHXZ endp

?_NV_getInventory@UseableStuff@@QEBAPEAVInventory@@XZ proc EXPORT
?_NV_getInventory@UseableStuff@@QEBAPEAVInventory@@XZ endp

; UseableStuff::getInventory();
?getInventory@UseableStuff@@UEBAPEAVInventory@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+9*8]
?getInventory@UseableStuff@@UEBAPEAVInventory@@XZ endp

?_NV_canHaveSomeOfThese@UseableStuff@@QEAA_NPEAVGameData@@@Z proc EXPORT
?_NV_canHaveSomeOfThese@UseableStuff@@QEAA_NPEAVGameData@@@Z endp

; UseableStuff::canHaveSomeOfThese(class GameData *);
?canHaveSomeOfThese@UseableStuff@@UEAA_NPEAVGameData@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+10*8]
?canHaveSomeOfThese@UseableStuff@@UEAA_NPEAVGameData@@@Z endp

?_NV_isAnyInputsEmpty@UseableStuff@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsEmpty@UseableStuff@@QEBA_NXZ endp

; UseableStuff::isAnyInputsEmpty();
?isAnyInputsEmpty@UseableStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+11*8]
?isAnyInputsEmpty@UseableStuff@@UEBA_NXZ endp

?_NV_needsUpdate@UseableStuff@@QEAA_NXZ proc EXPORT
?_NV_needsUpdate@UseableStuff@@QEAA_NXZ endp

; UseableStuff::needsUpdate();
?needsUpdate@UseableStuff@@UEAA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+12*8]
?needsUpdate@UseableStuff@@UEAA_NXZ endp

?_NV_threadedUpdate@UseableStuff@@QEAAXXZ proc EXPORT
?_NV_threadedUpdate@UseableStuff@@QEAAXXZ endp

; UseableStuff::threadedUpdate();
?threadedUpdate@UseableStuff@@UEAAXXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+13*8]
?threadedUpdate@UseableStuff@@UEAAXXZ endp

?_NV_operate@UseableStuff@@QEAAXPEAVCharacter@@M@Z proc EXPORT
?_NV_operate@UseableStuff@@QEAAXPEAVCharacter@@M@Z endp

; UseableStuff::operate(class Character *, float);
?operate@UseableStuff@@UEAAXPEAVCharacter@@M@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+14*8]
?operate@UseableStuff@@UEAAXPEAVCharacter@@M@Z endp

?_NV_calculateEfficiencyMult@UseableStuff@@QEBAMXZ proc EXPORT
?_NV_calculateEfficiencyMult@UseableStuff@@QEBAMXZ endp

; UseableStuff::calculateEfficiencyMult();
?calculateEfficiencyMult@UseableStuff@@UEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+15*8]
?calculateEfficiencyMult@UseableStuff@@UEBAMXZ endp

?_NV_isOutOfPower@UseableStuff@@QEBAMXZ proc EXPORT
?_NV_isOutOfPower@UseableStuff@@QEBAMXZ endp

; UseableStuff::isOutOfPower();
?isOutOfPower@UseableStuff@@UEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+16*8]
?isOutOfPower@UseableStuff@@UEBAMXZ endp

?_NV_getCostToUse@UseableStuff@@QEAAHPEAVCharacter@@@Z proc EXPORT
?_NV_getCostToUse@UseableStuff@@QEAAHPEAVCharacter@@@Z endp

; UseableStuff::getCostToUse(class Character *);
?getCostToUse@UseableStuff@@UEAAHPEAVCharacter@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+17*8]
?getCostToUse@UseableStuff@@UEAAHPEAVCharacter@@@Z endp

?_NV_getGUIData@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIData@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z endp

; UseableStuff::getGUIData(class DatapanelGUI *, int);
?getGUIData@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+18*8]
?getGUIData@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIPower@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIPower@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z endp

; UseableStuff::getGUIPower(class DatapanelGUI *, int);
?getGUIPower@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+19*8]
?getGUIPower@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIEfficiency@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIEfficiency@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z endp

; UseableStuff::getGUIEfficiency(class DatapanelGUI *, int);
?getGUIEfficiency@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+20*8]
?getGUIEfficiency@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIWorkers@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIWorkers@UseableStuff@@QEAAXPEAVDatapanelGUI@@H@Z endp

; UseableStuff::getGUIWorkers(class DatapanelGUI *, int);
?getGUIWorkers@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+21*8]
?getGUIWorkers@UseableStuff@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIToolTipForGroundResourceEfficiency@UseableStuff@@QEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
?_NV_getGUIToolTipForGroundResourceEfficiency@UseableStuff@@QEAAXAEAV?$lektor@VStringPair@@@@@Z endp

; UseableStuff::getGUIToolTipForGroundResourceEfficiency(class lektor<StringPair> &);
?getGUIToolTipForGroundResourceEfficiency@UseableStuff@@UEAAXAEAV?$lektor@VStringPair@@@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+22*8]
?getGUIToolTipForGroundResourceEfficiency@UseableStuff@@UEAAXAEAV?$lektor@VStringPair@@@@@Z endp

?_NV_serialise@UseableStuff@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
?_NV_serialise@UseableStuff@@QEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

; UseableStuff::serialise(class GameDataContainer *, class GameData *, class PosRotPair *);
?serialise@UseableStuff@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+23*8]
?serialise@UseableStuff@@UEAA?AVGameSaveState@@PEAVGameDataContainer@@PEAVGameData@@PEAVPosRotPair@@@Z endp

?_NV_loadFromSerialise@UseableStuff@@QEAAXPEAVGameSaveState@@@Z proc EXPORT
?_NV_loadFromSerialise@UseableStuff@@QEAAXPEAVGameSaveState@@@Z endp

; UseableStuff::loadFromSerialise(class GameSaveState *);
?loadFromSerialise@UseableStuff@@UEAAXPEAVGameSaveState@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+24*8]
?loadFromSerialise@UseableStuff@@UEAAXPEAVGameSaveState@@@Z endp

?_NV_hitByMeleeAttack@UseableStuff@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
?_NV_hitByMeleeAttack@UseableStuff@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

; UseableStuff::hitByMeleeAttack(enum CutDirection, class Damages &, class Character *, class CombatTechniqueData *, int);
?hitByMeleeAttack@UseableStuff@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+25*8]
?hitByMeleeAttack@UseableStuff@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

?_NV_isBroken@UseableStuff@@QEBA_NXZ proc EXPORT
?_NV_isBroken@UseableStuff@@QEBA_NXZ endp

; UseableStuff::isBroken();
?isBroken@UseableStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+26*8]
?isBroken@UseableStuff@@UEBA_NXZ endp

?_NV_setBroken@UseableStuff@@QEAAX_N@Z proc EXPORT
?_NV_setBroken@UseableStuff@@QEAAX_N@Z endp

; UseableStuff::setBroken(bool);
?setBroken@UseableStuff@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+27*8]
?setBroken@UseableStuff@@UEAAX_N@Z endp

?_NV_isDisabled@UseableStuff@@QEAA_NXZ proc EXPORT
?_NV_isDisabled@UseableStuff@@QEAA_NXZ endp

; UseableStuff::isDisabled();
?isDisabled@UseableStuff@@UEAA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+28*8]
?isDisabled@UseableStuff@@UEAA_NXZ endp

?_NV_getMouseCursor@UseableStuff@@QEAA?AW4CursorType@@XZ proc EXPORT
?_NV_getMouseCursor@UseableStuff@@QEAA?AW4CursorType@@XZ endp

; UseableStuff::getMouseCursor();
?getMouseCursor@UseableStuff@@UEAA?AW4CursorType@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+29*8]
?getMouseCursor@UseableStuff@@UEAA?AW4CursorType@@XZ endp

?_NV_getDefaultTask@UseableStuff@@QEAA?AW4TaskType@@XZ proc EXPORT
?_NV_getDefaultTask@UseableStuff@@QEAA?AW4TaskType@@XZ endp

; UseableStuff::getDefaultTask();
?getDefaultTask@UseableStuff@@UEAA?AW4TaskType@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+30*8]
?getDefaultTask@UseableStuff@@UEAA?AW4TaskType@@XZ endp

; UseableStuff::getAnimation();
?getAnimation@UseableStuff@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+31*8]
?getAnimation@UseableStuff@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; UseableStuff::getAnimationKO();
?getAnimationKO@UseableStuff@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+32*8]
?getAnimationKO@UseableStuff@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; UseableStuff::getAnimationDazed();
?getAnimationDazed@UseableStuff@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+33*8]
?getAnimationDazed@UseableStuff@@QEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

?_NV_getReachRange@UseableStuff@@QEBAMXZ proc EXPORT
?_NV_getReachRange@UseableStuff@@QEBAMXZ endp

; UseableStuff::getReachRange();
?getReachRange@UseableStuff@@UEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+34*8]
?getReachRange@UseableStuff@@UEBAMXZ endp

?_NV_dontNeedWorkRightNow@UseableStuff@@QEBA_NXZ proc EXPORT
?_NV_dontNeedWorkRightNow@UseableStuff@@QEBA_NXZ endp

; UseableStuff::dontNeedWorkRightNow();
?dontNeedWorkRightNow@UseableStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+35*8]
?dontNeedWorkRightNow@UseableStuff@@UEBA_NXZ endp

?_NV_isFreeSlot@UseableStuff@@QEBA_NAEBVhand@@@Z proc EXPORT
?_NV_isFreeSlot@UseableStuff@@QEBA_NAEBVhand@@@Z endp

; UseableStuff::isFreeSlot(const class hand &);
?isFreeSlot@UseableStuff@@UEBA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+36*8]
?isFreeSlot@UseableStuff@@UEBA_NAEBVhand@@@Z endp

?_NV_tryOperate@UseableStuff@@QEAA_NAEBVhand@@@Z proc EXPORT
?_NV_tryOperate@UseableStuff@@QEAA_NAEBVhand@@@Z endp

; UseableStuff::tryOperate(const class hand &);
?tryOperate@UseableStuff@@UEAA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+37*8]
?tryOperate@UseableStuff@@UEAA_NAEBVhand@@@Z endp

?_NV_couldIOperate@UseableStuff@@QEBA_NAEBVhand@@@Z proc EXPORT
?_NV_couldIOperate@UseableStuff@@QEBA_NAEBVhand@@@Z endp

; UseableStuff::couldIOperate(const class hand &);
?couldIOperate@UseableStuff@@UEBA_NAEBVhand@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+38*8]
?couldIOperate@UseableStuff@@UEBA_NAEBVhand@@@Z endp

; UseableStuff::stopOperating(const class hand &);
?stopOperating@UseableStuff@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+39*8]
?stopOperating@UseableStuff@@QEAAXAEBVhand@@@Z endp

; UseableStuff::getOccupant();
?getOccupant@UseableStuff@@QEBAAEBVhand@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+40*8]
?getOccupant@UseableStuff@@QEBAAEBVhand@@XZ endp

; UseableStuff::occupantHandleChangedEvent(const class hand &);
?occupantHandleChangedEvent@UseableStuff@@QEAAXAEBVhand@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+41*8]
?occupantHandleChangedEvent@UseableStuff@@QEAAXAEBVhand@@@Z endp

?_NV_togglePowerButton@UseableStuff@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_togglePowerButton@UseableStuff@@QEAAXPEAVDataPanelLine@@@Z endp

; UseableStuff::togglePowerButton(class DataPanelLine *);
?togglePowerButton@UseableStuff@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+42*8]
?togglePowerButton@UseableStuff@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_toggleBattButton@UseableStuff@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_toggleBattButton@UseableStuff@@QEAAXPEAVDataPanelLine@@@Z endp

; UseableStuff::toggleBattButton(class DataPanelLine *);
?toggleBattButton@UseableStuff@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+43*8]
?toggleBattButton@UseableStuff@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_isForSale@UseableStuff@@QEAA_NXZ proc EXPORT
?_NV_isForSale@UseableStuff@@QEAA_NXZ endp

; UseableStuff::isForSale();
?isForSale@UseableStuff@@UEAA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+44*8]
?isForSale@UseableStuff@@UEAA_NXZ endp

; UseableStuff::takePowerFrom(float, float);
?takePowerFrom@UseableStuff@@QEAAMMM@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+45*8]
?takePowerFrom@UseableStuff@@QEAAMMM@Z endp

; UseableStuff::howMuchPowerDoYouWantMax();
?howMuchPowerDoYouWantMax@UseableStuff@@QEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+46*8]
?howMuchPowerDoYouWantMax@UseableStuff@@QEBAMXZ endp

?_NV_howMuchPowerDoYouWantForSortingFunction@UseableStuff@@QEBAMXZ proc EXPORT
?_NV_howMuchPowerDoYouWantForSortingFunction@UseableStuff@@QEBAMXZ endp

; UseableStuff::howMuchPowerDoYouWantForSortingFunction();
?howMuchPowerDoYouWantForSortingFunction@UseableStuff@@UEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+47*8]
?howMuchPowerDoYouWantForSortingFunction@UseableStuff@@UEBAMXZ endp

; UseableStuff::howMuchPowerDoYouWantNow();
?howMuchPowerDoYouWantNow@UseableStuff@@QEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+48*8]
?howMuchPowerDoYouWantNow@UseableStuff@@QEBAMXZ endp

?_NV_needPowerRightNow@UseableStuff@@QEBA_NXZ proc EXPORT
?_NV_needPowerRightNow@UseableStuff@@QEBA_NXZ endp

; UseableStuff::needPowerRightNow();
?needPowerRightNow@UseableStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+49*8]
?needPowerRightNow@UseableStuff@@UEBA_NXZ endp

?_NV_givePower@UseableStuff@@QEAAXM@Z proc EXPORT
?_NV_givePower@UseableStuff@@QEAAXM@Z endp

; UseableStuff::givePower(float);
?givePower@UseableStuff@@UEAAXM@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+50*8]
?givePower@UseableStuff@@UEAAXM@Z endp

; UseableStuff::resetPower();
?resetPower@UseableStuff@@QEAAXXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+51*8]
?resetPower@UseableStuff@@QEAAXXZ endp

; UseableStuff::getMaxPower();
?getMaxPower@UseableStuff@@QEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+52*8]
?getMaxPower@UseableStuff@@QEBAMXZ endp

?_NV_getPowerOutput@UseableStuff@@QEBAMXZ proc EXPORT
?_NV_getPowerOutput@UseableStuff@@QEBAMXZ endp

; UseableStuff::getPowerOutput();
?getPowerOutput@UseableStuff@@UEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+53*8]
?getPowerOutput@UseableStuff@@UEBAMXZ endp

?_NV_getFuelConsumptionRate@UseableStuff@@QEAAMXZ proc EXPORT
?_NV_getFuelConsumptionRate@UseableStuff@@QEAAMXZ endp

; UseableStuff::getFuelConsumptionRate();
?getFuelConsumptionRate@UseableStuff@@UEAAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+54*8]
?getFuelConsumptionRate@UseableStuff@@UEAAMXZ endp

; UseableStuff::isBattery();
?isBattery@UseableStuff@@QEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+55*8]
?isBattery@UseableStuff@@QEBA_NXZ endp

; UseableStuff::isGenerator();
?isGenerator@UseableStuff@@QEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+56*8]
?isGenerator@UseableStuff@@QEBA_NXZ endp

; UseableStuff::getBatteryCharge();
?getBatteryCharge@UseableStuff@@QEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+57*8]
?getBatteryCharge@UseableStuff@@QEBAMXZ endp

; UseableStuff::getBatteryChargeMax();
?getBatteryChargeMax@UseableStuff@@QEBAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+58*8]
?getBatteryChargeMax@UseableStuff@@QEBAMXZ endp

?_NV_setupFromData@UseableStuff@@QEAAXXZ proc EXPORT
?_NV_setupFromData@UseableStuff@@QEAAXXZ endp

; UseableStuff::setupFromData();
?setupFromData@UseableStuff@@UEAAXXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+59*8]
?setupFromData@UseableStuff@@UEAAXXZ endp

?_NV_switchPowerOn@UseableStuff@@QEAAX_N@Z proc EXPORT
?_NV_switchPowerOn@UseableStuff@@QEAAX_N@Z endp

; UseableStuff::switchPowerOn(bool);
?switchPowerOn@UseableStuff@@UEAAX_N@Z proc EXPORT
jmp function_pointers[_UseableStuff_base+60*8]
?switchPowerOn@UseableStuff@@UEAAX_N@Z endp

; UseableStuff::hasPower();
?hasPower@UseableStuff@@QEAA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+61*8]
?hasPower@UseableStuff@@QEAA_NXZ endp

?_NV_isPowerOn@UseableStuff@@QEBA_NXZ proc EXPORT
?_NV_isPowerOn@UseableStuff@@QEBA_NXZ endp

; UseableStuff::isPowerOn();
?isPowerOn@UseableStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+62*8]
?isPowerOn@UseableStuff@@UEBA_NXZ endp

; UseableStuff::isRecievesBatteryPower();
?isRecievesBatteryPower@UseableStuff@@QEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+63*8]
?isRecievesBatteryPower@UseableStuff@@QEBA_NXZ endp

; UseableStuff::getStatUsed();
?getStatUsed@UseableStuff@@QEBA?AW4StatsEnumerated@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+64*8]
?getStatUsed@UseableStuff@@QEBA?AW4StatsEnumerated@@XZ endp

?_NV_getDoorLock@UseableStuff@@QEAAPEAVDoorLock@@XZ proc EXPORT
?_NV_getDoorLock@UseableStuff@@QEAAPEAVDoorLock@@XZ endp

; UseableStuff::getDoorLock();
?getDoorLock@UseableStuff@@UEAAPEAVDoorLock@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+65*8]
?getDoorLock@UseableStuff@@UEAAPEAVDoorLock@@XZ endp

?_NV_hasDoorLock@UseableStuff@@QEBA_NXZ proc EXPORT
?_NV_hasDoorLock@UseableStuff@@QEBA_NXZ endp

; UseableStuff::hasDoorLock();
?hasDoorLock@UseableStuff@@UEBA_NXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+66*8]
?hasDoorLock@UseableStuff@@UEBA_NXZ endp

; UseableStuff::getFunctionalityData();
?getFunctionalityData@UseableStuff@@QEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+67*8]
?getFunctionalityData@UseableStuff@@QEAAPEAVGameData@@XZ endp

?_NV_setup@UseableStuff@@QEAAXXZ proc EXPORT
?_NV_setup@UseableStuff@@QEAAXXZ endp

; UseableStuff::setup();
?setup@UseableStuff@@UEAAXXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+68*8]
?setup@UseableStuff@@UEAAXXZ endp

?_NV_getOutputBasedRotationSpeedMult@UseableStuff@@QEAAMXZ proc EXPORT
?_NV_getOutputBasedRotationSpeedMult@UseableStuff@@QEAAMXZ endp

; UseableStuff::getOutputBasedRotationSpeedMult();
?getOutputBasedRotationSpeedMult@UseableStuff@@UEAAMXZ proc EXPORT
jmp function_pointers[_UseableStuff_base+69*8]
?getOutputBasedRotationSpeedMult@UseableStuff@@UEAAMXZ endp

?_NV_getGUIPowerEfficiencyToolTipString@UseableStuff@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
?_NV_getGUIPowerEfficiencyToolTipString@UseableStuff@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp

; UseableStuff::getGUIPowerEfficiencyToolTipString();
?getGUIPowerEfficiencyToolTipString@UseableStuff@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ proc EXPORT
jmp function_pointers[_UseableStuff_base+70*8]
?getGUIPowerEfficiencyToolTipString@UseableStuff@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ endp
