
?_CONSTRUCTOR@UtilityT@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@UtilityT@@QEAAPEAV1@XZ endp

; UtilityT::UtilityT();
??0UtilityT@@QEAA@XZ proc EXPORT
jmp function_pointers[_UtilityT_base+0*8]
??0UtilityT@@QEAA@XZ endp

; UtilityT::getMouseRay();
?getMouseRay@UtilityT@@SA?AVRay@Ogre@@XZ proc EXPORT
jmp function_pointers[_UtilityT_base+1*8]
?getMouseRay@UtilityT@@SA?AVRay@Ogre@@XZ endp

; UtilityT::mouseTrace(class physHit &, const class Ogre::Vector2 &, unsigned int);
?mouseTrace@UtilityT@@SAXAEAVphysHit@@AEBVVector2@Ogre@@I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+2*8]
?mouseTrace@UtilityT@@SAXAEAVphysHit@@AEBVVector2@Ogre@@I@Z endp

; UtilityT::rayTrace(class physHit &, const class Ogre::Ray &, unsigned int);
?rayTrace@UtilityT@@SAXAEAVphysHit@@AEBVRay@Ogre@@I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+3*8]
?rayTrace@UtilityT@@SAXAEAVphysHit@@AEBVRay@Ogre@@I@Z endp

; UtilityT::ceilingTrace(const class Ogre::Vector3 &, unsigned int, bool);
?ceilingTrace@UtilityT@@SA_NAEBVVector3@Ogre@@I_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+4*8]
?ceilingTrace@UtilityT@@SA_NAEBVVector3@Ogre@@I_N@Z endp

; UtilityT::traceNoActors(class physHit &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, unsigned int);
?traceNoActors@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+5*8]
?traceNoActors@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1I@Z endp

; UtilityT::trace(class physHit &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, unsigned int);
?trace@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+6*8]
?trace@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1I@Z endp

; UtilityT::traceFloorHeight(class physHit &, const class Ogre::Vector3 &, int);
?traceFloorHeight@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_UtilityT_base+7*8]
?traceFloorHeight@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@H@Z endp

; UtilityT::_trace_TEST(class physHit &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, unsigned int);
?_trace_TEST@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+8*8]
?_trace_TEST@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1I@Z endp

; UtilityT::tracePosOnly(const class Ogre::Vector3 &, const class Ogre::Vector3 &, unsigned int);
?tracePosOnly@UtilityT@@SA?AVVector3@Ogre@@AEBV23@0I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+9*8]
?tracePosOnly@UtilityT@@SA?AVVector3@Ogre@@AEBV23@0I@Z endp

; UtilityT::sphereTrace(class physHit &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, const float, unsigned int, bool);
?sphereTrace@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1MI_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+10*8]
?sphereTrace@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@1MI_N@Z endp

; UtilityT::boxTrace(class physHit &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, unsigned int, bool);
?boxTrace@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@11I_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+11*8]
?boxTrace@UtilityT@@SAXAEAVphysHit@@AEBVVector3@Ogre@@11I_N@Z endp

; UtilityT::mouseTraceAll(class lektor<PhysHitItem> &, unsigned int);
?mouseTraceAll@UtilityT@@SAXAEAV?$lektor@UPhysHitItem@@@@I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+12*8]
?mouseTraceAll@UtilityT@@SAXAEAV?$lektor@UPhysHitItem@@@@I@Z endp

; UtilityT::traceAll(class lektor<PhysHitItem> &, const class Ogre::Vector3 &, const class Ogre::Vector3 &, unsigned int);
?traceAll@UtilityT@@SAXAEAV?$lektor@UPhysHitItem@@@@AEBVVector3@Ogre@@1I@Z proc EXPORT
jmp function_pointers[_UtilityT_base+13*8]
?traceAll@UtilityT@@SAXAEAV?$lektor@UPhysHitItem@@@@AEBVVector3@Ogre@@1I@Z endp

; UtilityT::getTerrainHeight(float, float);
?getTerrainHeight@UtilityT@@SAMMM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+14*8]
?getTerrainHeight@UtilityT@@SAMMM@Z endp

; UtilityT::getTerrainWithWaterHeight(float, float);
?getTerrainWithWaterHeight@UtilityT@@SAMMM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+15*8]
?getTerrainWithWaterHeight@UtilityT@@SAMMM@Z endp

; UtilityT::getTerrainWithWaterHeightFromRenderer(const class Ogre::Vector3 &);
?getTerrainWithWaterHeightFromRenderer@UtilityT@@SAMAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+16*8]
?getTerrainWithWaterHeightFromRenderer@UtilityT@@SAMAEBVVector3@Ogre@@@Z endp

; UtilityT::getPositionInWater(float, float);
?getPositionInWater@UtilityT@@SA_NMM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+17*8]
?getPositionInWater@UtilityT@@SA_NMM@Z endp

; UtilityT::getFloorHeight(const class Ogre::Vector3 &, int, bool, bool);
?getFloorHeight@UtilityT@@SAMAEBVVector3@Ogre@@H_N1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+18*8]
?getFloorHeight@UtilityT@@SAMAEBVVector3@Ogre@@H_N1@Z endp

; UtilityT::getFloorHeight(const class Ogre::Vector3 &, bool, bool);
?getFloorHeight@UtilityT@@SAMAEBVVector3@Ogre@@_N1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+19*8]
?getFloorHeight@UtilityT@@SAMAEBVVector3@Ogre@@_N1@Z endp

; UtilityT::getBuildingGroundFloorHeight(const class Ogre::Vector3 &, bool);
?getBuildingGroundFloorHeight@UtilityT@@SAMAEBVVector3@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+20*8]
?getBuildingGroundFloorHeight@UtilityT@@SAMAEBVVector3@Ogre@@_N@Z endp

; UtilityT::isIndoors(const class Ogre::Vector3 &);
?isIndoors@UtilityT@@SAPEAVBuilding@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+21*8]
?isIndoors@UtilityT@@SAPEAVBuilding@@AEBVVector3@Ogre@@@Z endp

; UtilityT::isIndoorsFast(const class Ogre::Vector3 &);
?isIndoorsFast@UtilityT@@SA_NAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+22*8]
?isIndoorsFast@UtilityT@@SA_NAEBVVector3@Ogre@@@Z endp

; UtilityT::isIndoors_forWaypoint(const class Ogre::Vector3 &);
?isIndoors_forWaypoint@UtilityT@@SAPEAVBuilding@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+23*8]
?isIndoors_forWaypoint@UtilityT@@SAPEAVBuilding@@AEBVVector3@Ogre@@@Z endp

; UtilityT::cascadeSetStatic(class Ogre::SceneNode *, bool);
?cascadeSetStatic@UtilityT@@SAXPEAVSceneNode@Ogre@@_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+24*8]
?cascadeSetStatic@UtilityT@@SAXPEAVSceneNode@Ogre@@_N@Z endp

; UtilityT::perlinNoise_2D(double, double, double, float);
?perlinNoise_2D@UtilityT@@QEAAMNNNM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+25*8]
?perlinNoise_2D@UtilityT@@QEAAMNNNM@Z endp

; UtilityT::getFloorNumber(int);
?getFloorNumber@UtilityT@@SAHH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+26*8]
?getFloorNumber@UtilityT@@SAHH@Z endp

; UtilityT::getFloorNumber(const class Ogre::Vector3 &, class hand *);
?getFloorNumber@UtilityT@@SAHAEBVVector3@Ogre@@PEAVhand@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+27*8]
?getFloorNumber@UtilityT@@SAHAEBVVector3@Ogre@@PEAVhand@@@Z endp

; UtilityT::getTerrainHeightFastWithNormal(float, float, class Ogre::Vector3 &, class ZoneMap *);
?getTerrainHeightFastWithNormal@UtilityT@@QEAAMMMAEAVVector3@Ogre@@PEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+28*8]
?getTerrainHeightFastWithNormal@UtilityT@@QEAAMMMAEAVVector3@Ogre@@PEAVZoneMap@@@Z endp

; UtilityT::getTerrainHeightFast(float, float, class ZoneMap *);
?getTerrainHeightFast@UtilityT@@SAMMMPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+29*8]
?getTerrainHeightFast@UtilityT@@SAMMMPEAVZoneMap@@@Z endp

; UtilityT::getTerrainSlopeFast(float, float, class ZoneMap *);
?getTerrainSlopeFast@UtilityT@@QEAAMMMPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+30*8]
?getTerrainSlopeFast@UtilityT@@QEAAMMMPEAVZoneMap@@@Z endp

; UtilityT::random(float, float);
?random@UtilityT@@SAMMM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+31*8]
?random@UtilityT@@SAMMM@Z endp

; UtilityT::random();
?random@UtilityT@@SAMXZ proc EXPORT
jmp function_pointers[_UtilityT_base+32*8]
?random@UtilityT@@SAMXZ endp

; UtilityT::randomBool();
?randomBool@UtilityT@@SA_NXZ proc EXPORT
jmp function_pointers[_UtilityT_base+33*8]
?randomBool@UtilityT@@SA_NXZ endp

; UtilityT::randomInt(int, int);
?randomInt@UtilityT@@SAHHH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+34*8]
?randomInt@UtilityT@@SAHHH@Z endp

; UtilityT::seed(unsigned int);
?seed@UtilityT@@SAXI@Z proc EXPORT
jmp function_pointers[_UtilityT_base+35*8]
?seed@UtilityT@@SAXI@Z endp

; UtilityT::seed();
?seed@UtilityT@@SAXXZ proc EXPORT
jmp function_pointers[_UtilityT_base+36*8]
?seed@UtilityT@@SAXXZ endp

; UtilityT::round(float);
?round@UtilityT@@SAHM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+37*8]
?round@UtilityT@@SAHM@Z endp

; UtilityT::nlerp(const float &, const float &, const float &);
?nlerp@UtilityT@@SAMAEBM00@Z proc EXPORT
jmp function_pointers[_UtilityT_base+38*8]
?nlerp@UtilityT@@SAMAEBM00@Z endp

; UtilityT::getNextPow2(int);
?getNextPow2@UtilityT@@SAHH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+39*8]
?getNextPow2@UtilityT@@SAHH@Z endp

; UtilityT::quatSetDirection(class Ogre::Quaternion &, const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?quatSetDirection@UtilityT@@SAXAEAVQuaternion@Ogre@@AEBVVector3@3@1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+40*8]
?quatSetDirection@UtilityT@@SAXAEAVQuaternion@Ogre@@AEBVVector3@3@1@Z endp

; UtilityT::getSubMapSector(float, float);
?getSubMapSector@UtilityT@@SA?AViVector2@@MM@Z proc EXPORT
jmp function_pointers[_UtilityT_base+41*8]
?getSubMapSector@UtilityT@@SA?AViVector2@@MM@Z endp

; UtilityT::getSubMapSectorBounds(const class iVector2);
?getSubMapSectorBounds@UtilityT@@SA?AVVector4@Ogre@@ViVector2@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+42*8]
?getSubMapSectorBounds@UtilityT@@SA?AVVector4@Ogre@@ViVector2@@@Z endp

; UtilityT::getResourceFilePath(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getResourceFilePath@UtilityT@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+43*8]
?getResourceFilePath@UtilityT@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV23@@Z endp

; UtilityT::removePathFromString(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?removePathFromString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+44*8]
?removePathFromString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; UtilityT::removeFilenameFromPath(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?removeFilenameFromPath@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+45*8]
?removeFilenameFromPath@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; UtilityT::removeFileExtensionFromString(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?removeFileExtensionFromString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+46*8]
?removeFileExtensionFromString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; UtilityT::getFileExtensionFromString(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getFileExtensionFromString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+47*8]
?getFileExtensionFromString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; UtilityT::removeInvalidFileNameChars(class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?removeInvalidFileNameChars@UtilityT@@SAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+48*8]
?removeInvalidFileNameChars@UtilityT@@SAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::compareStringsCaseInsenstive(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?compareStringsCaseInsenstive@UtilityT@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_UtilityT_base+49*8]
?compareStringsCaseInsenstive@UtilityT@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; UtilityT::profilesClear();
?profilesClear@UtilityT@@QEAAXXZ proc EXPORT
jmp function_pointers[_UtilityT_base+50*8]
?profilesClear@UtilityT@@QEAAXXZ endp

; UtilityT::profilesPrint();
?profilesPrint@UtilityT@@QEAAXXZ proc EXPORT
jmp function_pointers[_UtilityT_base+51*8]
?profilesPrint@UtilityT@@QEAAXXZ endp

; UtilityT::profileGet(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?profileGet@UtilityT@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+52*8]
?profileGet@UtilityT@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::getTerrainHeightFromRenderer(const class Ogre::Vector3 &, bool, int);
?getTerrainHeightFromRenderer@UtilityT@@SAMAEBVVector3@Ogre@@_NH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+53*8]
?getTerrainHeightFromRenderer@UtilityT@@SAMAEBVVector3@Ogre@@_NH@Z endp

; UtilityT::getApproxTerrainHeightFromRenderer(const class Ogre::Vector3 &, class Ogre::Vector3 &);
?getApproxTerrainHeightFromRenderer@UtilityT@@SAMAEBVVector3@Ogre@@AEAV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+54*8]
?getApproxTerrainHeightFromRenderer@UtilityT@@SAMAEBVVector3@Ogre@@AEAV23@@Z endp

; UtilityT::worldToScreenRel(const class Ogre::Vector3 &, float &, float &);
?worldToScreenRel@UtilityT@@QEAA_NAEBVVector3@Ogre@@AEAM1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+55*8]
?worldToScreenRel@UtilityT@@QEAA_NAEBVVector3@Ogre@@AEAM1@Z endp

; UtilityT::worldToScreenPX(const class Ogre::Vector3 &, float &, float &);
?worldToScreenPX@UtilityT@@QEAA_NAEBVVector3@Ogre@@AEAM1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+56*8]
?worldToScreenPX@UtilityT@@QEAA_NAEBVVector3@Ogre@@AEAM1@Z endp

; UtilityT::worldToScreenWithRadius(const class Ogre::Vector3 &, const float, float &, float &, float &, float &);
?worldToScreenWithRadius@UtilityT@@QEAA_NAEBVVector3@Ogre@@MAEAM111@Z proc EXPORT
jmp function_pointers[_UtilityT_base+57*8]
?worldToScreenWithRadius@UtilityT@@QEAA_NAEBVVector3@Ogre@@MAEAM111@Z endp

; UtilityT::placeOrientedMarker(const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Ogre::SceneNode *);
?placeOrientedMarker@UtilityT@@QEAAPEAVEntity@Ogre@@AEBVVector3@3@AEBVQuaternion@3@PEAVSceneNode@3@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+58*8]
?placeOrientedMarker@UtilityT@@QEAAPEAVEntity@Ogre@@AEBVVector3@3@AEBVQuaternion@3@PEAVSceneNode@3@@Z endp

; UtilityT::placeMarker(const class Ogre::Vector3 &, const void *, int);
?placeMarker@UtilityT@@QEAAXAEBVVector3@Ogre@@PEBXH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+59*8]
?placeMarker@UtilityT@@QEAAXAEBVVector3@Ogre@@PEBXH@Z endp

; UtilityT::placeMarker(const class Ogre::Vector3 &, int);
?placeMarker@UtilityT@@QEAAXAEBVVector3@Ogre@@H@Z proc EXPORT
jmp function_pointers[_UtilityT_base+60*8]
?placeMarker@UtilityT@@QEAAXAEBVVector3@Ogre@@H@Z endp

; UtilityT::debugBox(class NxShape *);
?debugBox@UtilityT@@QEAAXPEAVNxShape@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+61*8]
?debugBox@UtilityT@@QEAAXPEAVNxShape@@@Z endp

; UtilityT::placeBox(class Ogre::Vector3, class Ogre::SceneNode *);
?placeBox@UtilityT@@QEAAXVVector3@Ogre@@PEAVSceneNode@3@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+62*8]
?placeBox@UtilityT@@QEAAXVVector3@Ogre@@PEAVSceneNode@3@@Z endp

; UtilityT::placeArrow(const class Ogre::Vector3 &, const class Ogre::Vector3 &, const void *, float, float, int);
?placeArrow@UtilityT@@QEAAXAEBVVector3@Ogre@@0PEBXMMH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+63*8]
?placeArrow@UtilityT@@QEAAXAEBVVector3@Ogre@@0PEBXMMH@Z endp

; UtilityT::placeArrowTo(const class Ogre::Vector3 &, const class Ogre::Vector3 &, const void *, float, int);
?placeArrowTo@UtilityT@@QEAAXAEBVVector3@Ogre@@0PEBXMH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+64*8]
?placeArrowTo@UtilityT@@QEAAXAEBVVector3@Ogre@@0PEBXMH@Z endp

; UtilityT::placeArrowBT(const class Ogre::Vector3 &, const class Ogre::Vector3 &, const void *, float, float, int);
?placeArrowBT@UtilityT@@QEAAXAEBVVector3@Ogre@@0PEBXMMH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+65*8]
?placeArrowBT@UtilityT@@QEAAXAEBVVector3@Ogre@@0PEBXMMH@Z endp

; UtilityT::removeArrow(const void *);
?removeArrow@UtilityT@@QEAAXPEBX@Z proc EXPORT
jmp function_pointers[_UtilityT_base+66*8]
?removeArrow@UtilityT@@QEAAXPEBX@Z endp

; UtilityT::placeSphere(const class Ogre::Vector3 &, const void *, float, int);
?placeSphere@UtilityT@@QEAAXAEBVVector3@Ogre@@PEBXMH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+67*8]
?placeSphere@UtilityT@@QEAAXAEBVVector3@Ogre@@PEBXMH@Z endp

; UtilityT::placeAxis(const class Ogre::Vector3 &, const class Ogre::Quaternion &);
?placeAxis@UtilityT@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+68*8]
?placeAxis@UtilityT@@QEAAXAEBVVector3@Ogre@@AEBVQuaternion@3@@Z endp

; UtilityT::placeAxis(const class Ogre::Vector3 &, const class NxMat33 &);
?placeAxis@UtilityT@@QEAAXAEBVVector3@Ogre@@AEBVNxMat33@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+69*8]
?placeAxis@UtilityT@@QEAAXAEBVVector3@Ogre@@AEBVNxMat33@@@Z endp

; UtilityT::ogreTrace(const class Ogre::Vector3 &, const class Ogre::Vector3 &, int);
?ogreTrace@UtilityT@@QEAA?AVrendHit@@AEBVVector3@Ogre@@0H@Z proc EXPORT
jmp function_pointers[_UtilityT_base+70*8]
?ogreTrace@UtilityT@@QEAA?AVrendHit@@AEBVVector3@Ogre@@0H@Z endp

; UtilityT::getDebugMaterial(int, bool);
?getDebugMaterial@UtilityT@@QEAA?AV?$SharedPtr@VMaterial@Ogre@@@Ogre@@H_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+71*8]
?getDebugMaterial@UtilityT@@QEAA?AV?$SharedPtr@VMaterial@Ogre@@@Ogre@@H_N@Z endp

; UtilityT::flushMarkerQueue();
?flushMarkerQueue@UtilityT@@QEAAXXZ proc EXPORT
jmp function_pointers[_UtilityT_base+72*8]
?flushMarkerQueue@UtilityT@@QEAAXXZ endp

; UtilityT::removeMarkers();
?removeMarkers@UtilityT@@QEAAXXZ proc EXPORT
jmp function_pointers[_UtilityT_base+73*8]
?removeMarkers@UtilityT@@QEAAXXZ endp

; UtilityT::folderExists(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?folderExists@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+74*8]
?folderExists@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::fileExists(const class std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > &);
?fileExists@UtilityT@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+75*8]
?fileExists@UtilityT@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z endp

; UtilityT::fileExistsASCII(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?fileExistsASCII@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+76*8]
?fileExistsASCII@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::createFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?createFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_UtilityT_base+77*8]
?createFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; UtilityT::writeFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?writeFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+78*8]
?writeFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_N@Z endp

; UtilityT::readFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?readFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+79*8]
?readFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV23@@Z endp

; UtilityT::isFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+80*8]
?isFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::isDirectory(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?isDirectory@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+81*8]
?isDirectory@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::makeSureGameFolderExists(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?makeSureGameFolderExists@UtilityT@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+82*8]
?makeSureGameFolderExists@UtilityT@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::makeSureFolderExists(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?makeSureFolderExists@UtilityT@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+83*8]
?makeSureFolderExists@UtilityT@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::getFullPath(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getFullPath@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+84*8]
?getFullPath@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z endp

; UtilityT::getRelativePath(const class boost::filesystem::path &, const class boost::filesystem::path &, class boost::filesystem::path &);
?getRelativePath@UtilityT@@SA_NAEBVpath@filesystem@boost@@0AEAV234@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+85*8]
?getRelativePath@UtilityT@@SA_NAEBVpath@filesystem@boost@@0AEAV234@@Z endp

; UtilityT::getFilesInDir(class lektor<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getFilesInDir@UtilityT@@QEAA_NAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+86*8]
?getFilesInDir@UtilityT@@QEAA_NAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; UtilityT::getFilesInGameDir(class lektor<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getFilesInGameDir@UtilityT@@QEAA_NAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z proc EXPORT
jmp function_pointers[_UtilityT_base+87*8]
?getFilesInGameDir@UtilityT@@QEAA_NAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z endp

; UtilityT::getDirsInDir(class lektor<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?getDirsInDir@UtilityT@@QEAAXAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+88*8]
?getDirsInDir@UtilityT@@QEAAXAEAV?$lektor@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::getCurrentDir();
?getCurrentDir@UtilityT@@QEAA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ proc EXPORT
jmp function_pointers[_UtilityT_base+89*8]
?getCurrentDir@UtilityT@@QEAA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ endp

; UtilityT::setCurrentDir(const class std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > &);
?setCurrentDir@UtilityT@@QEAAXAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+90*8]
?setCurrentDir@UtilityT@@QEAAXAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z endp

; UtilityT::deleteFilesInFolder(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, bool);
?deleteFilesInFolder@UtilityT@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_N@Z proc EXPORT
jmp function_pointers[_UtilityT_base+91*8]
?deleteFilesInFolder@UtilityT@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_N@Z endp

; UtilityT::deleteFolder(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?deleteFolder@UtilityT@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+92*8]
?deleteFolder@UtilityT@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::deleteFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?deleteFile@UtilityT@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+93*8]
?deleteFile@UtilityT@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; UtilityT::moveFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?moveFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_UtilityT_base+94*8]
?moveFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; UtilityT::copyFile(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?copyFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z proc EXPORT
jmp function_pointers[_UtilityT_base+95*8]
?copyFile@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z endp

; UtilityT::copyFilesInFolder(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?copyFilesInFolder@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z proc EXPORT
jmp function_pointers[_UtilityT_base+96*8]
?copyFilesInFolder@UtilityT@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z endp

; UtilityT::positionIsInFrontOfMe(const class Ogre::Vector3 &, const class Ogre::Vector3 &);
?positionIsInFrontOfMe@UtilityT@@SA_NAEBVVector3@Ogre@@0@Z proc EXPORT
jmp function_pointers[_UtilityT_base+97*8]
?positionIsInFrontOfMe@UtilityT@@SA_NAEBVVector3@Ogre@@0@Z endp

; UtilityT::pointInPlane(class Ogre::Vector3, class Ogre::Vector3, class Ogre::Vector3);
?pointInPlane@UtilityT@@SA_NVVector3@Ogre@@00@Z proc EXPORT
jmp function_pointers[_UtilityT_base+98*8]
?pointInPlane@UtilityT@@SA_NVVector3@Ogre@@00@Z endp

; UtilityT::OBBCollision(class NxBox &, class NxBox &);
?OBBCollision@UtilityT@@SA_NAEAVNxBox@@0@Z proc EXPORT
jmp function_pointers[_UtilityT_base+99*8]
?OBBCollision@UtilityT@@SA_NAEAVNxBox@@0@Z endp

; UtilityT::colorToGUIString(const class Ogre::ColourValue &);
?colorToGUIString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVColourValue@Ogre@@@Z proc EXPORT
jmp function_pointers[_UtilityT_base+100*8]
?colorToGUIString@UtilityT@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVColourValue@Ogre@@@Z endp

; UtilityT::roundToNearest(float &, int);
?roundToNearest@UtilityT@@QEAAXAEAMH@Z proc EXPORT
jmp function_pointers[_UtilityT_base+101*8]
?roundToNearest@UtilityT@@QEAAXAEAMH@Z endp
