
?_CONSTRUCTOR@VisibleObjectInfo@@QEAAPEAV1@AEBV1@@Z proc EXPORT
?_CONSTRUCTOR@VisibleObjectInfo@@QEAAPEAV1@AEBV1@@Z endp

; VisibleObjectInfo::VisibleObjectInfo(const class VisibleObjectInfo &);
??0VisibleObjectInfo@@QEAA@AEBV0@@Z proc EXPORT
jmp function_pointers[_VisibleObjectInfo_base+0*8]
??0VisibleObjectInfo@@QEAA@AEBV0@@Z endp

?_CONSTRUCTOR@VisibleObjectInfo@@QEAAPEAV1@AEBVhand@@M_N@Z proc EXPORT
?_CONSTRUCTOR@VisibleObjectInfo@@QEAAPEAV1@AEBVhand@@M_N@Z endp

; VisibleObjectInfo::VisibleObjectInfo(const class hand &, float, bool);
??0VisibleObjectInfo@@QEAA@AEBVhand@@M_N@Z proc EXPORT
jmp function_pointers[_VisibleObjectInfo_base+1*8]
??0VisibleObjectInfo@@QEAA@AEBVhand@@M_N@Z endp

; VisibleObjectInfo::operator=(const class VisibleObjectInfo &);
??4VisibleObjectInfo@@QEAAAEAV0@AEBV0@@Z proc EXPORT
jmp function_pointers[_VisibleObjectInfo_base+2*8]
??4VisibleObjectInfo@@QEAAAEAV0@AEBV0@@Z endp
