
?_DESTRUCTOR@WallBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@WallBuilding@@QEAAXXZ endp

; WallBuilding::~WallBuilding();
??1WallBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_WallBuilding_base+0*8]
??1WallBuilding@@UEAA@XZ endp

?_CONSTRUCTOR@WallBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@PEAVLayout@@AEBVhand@@5@Z proc EXPORT
?_CONSTRUCTOR@WallBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@PEAVLayout@@AEBVhand@@5@Z endp

; WallBuilding::WallBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, class Layout *, const class hand &, const class hand &);
??0WallBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@PEAVLayout@@AEBVhand@@5@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+1*8]
??0WallBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@PEAVLayout@@AEBVhand@@5@Z endp

?_NV_getUseableStuff@WallBuilding@@QEAAPEAVUseableStuff@@XZ proc EXPORT
?_NV_getUseableStuff@WallBuilding@@QEAAPEAVUseableStuff@@XZ endp

; WallBuilding::getUseableStuff();
?getUseableStuff@WallBuilding@@UEAAPEAVUseableStuff@@XZ proc EXPORT
jmp function_pointers[_WallBuilding_base+2*8]
?getUseableStuff@WallBuilding@@UEAAPEAVUseableStuff@@XZ endp

?_NV_getReachRange@WallBuilding@@QEBAMXZ proc EXPORT
?_NV_getReachRange@WallBuilding@@QEBAMXZ endp

; WallBuilding::getReachRange();
?getReachRange@WallBuilding@@UEBAMXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+3*8]
?getReachRange@WallBuilding@@UEBAMXZ endp

?_NV_isForSale@WallBuilding@@QEAA_NXZ proc EXPORT
?_NV_isForSale@WallBuilding@@QEAA_NXZ endp

; WallBuilding::isForSale();
?isForSale@WallBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+4*8]
?isForSale@WallBuilding@@UEAA_NXZ endp

?_NV_createPhysical@WallBuilding@@QEAA_NXZ proc EXPORT
?_NV_createPhysical@WallBuilding@@QEAA_NXZ endp

; WallBuilding::createPhysical();
?createPhysical@WallBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+5*8]
?createPhysical@WallBuilding@@UEAA_NXZ endp

?_NV_isDamaged@WallBuilding@@QEAA_NXZ proc EXPORT
?_NV_isDamaged@WallBuilding@@QEAA_NXZ endp

; WallBuilding::isDamaged();
?isDamaged@WallBuilding@@UEAA_NXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+6*8]
?isDamaged@WallBuilding@@UEAA_NXZ endp

; WallBuilding::getPositionForWaypoint_outside();
?getPositionForWaypoint_outside@WallBuilding@@QEAA?AVVector3@Ogre@@XZ proc EXPORT
jmp function_pointers[_WallBuilding_base+7*8]
?getPositionForWaypoint_outside@WallBuilding@@QEAA?AVVector3@Ogre@@XZ endp

; WallBuilding::getOutsideGateCode();
?getOutsideGateCode@WallBuilding@@QEAAHXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+8*8]
?getOutsideGateCode@WallBuilding@@QEAAHXZ endp

?_NV_isAWall@WallBuilding@@QEAAPEAV1@XZ proc EXPORT
?_NV_isAWall@WallBuilding@@QEAAPEAV1@XZ endp

; WallBuilding::isAWall();
?isAWall@WallBuilding@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_WallBuilding_base+9*8]
?isAWall@WallBuilding@@UEAAPEAV1@XZ endp

?_NV_upgrade@WallBuilding@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_upgrade@WallBuilding@@QEAAXPEAVDataPanelLine@@@Z endp

; WallBuilding::upgrade(class DataPanelLine *);
?upgrade@WallBuilding@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+10*8]
?upgrade@WallBuilding@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_getGUIUpgrade@WallBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIUpgrade@WallBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; WallBuilding::getGUIUpgrade(class DatapanelGUI *, int);
?getGUIUpgrade@WallBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+11*8]
?getGUIUpgrade@WallBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIDestroyButton@WallBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIDestroyButton@WallBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; WallBuilding::getGUIDestroyButton(class DatapanelGUI *, int);
?getGUIDestroyButton@WallBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+12*8]
?getGUIDestroyButton@WallBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_canUpgrade@WallBuilding@@QEAAPEAVGameData@@XZ proc EXPORT
?_NV_canUpgrade@WallBuilding@@QEAAPEAVGameData@@XZ endp

; WallBuilding::canUpgrade();
?canUpgrade@WallBuilding@@UEAAPEAVGameData@@XZ proc EXPORT
jmp function_pointers[_WallBuilding_base+13*8]
?canUpgrade@WallBuilding@@UEAAPEAVGameData@@XZ endp

?_NV_dismantleButton_all@WallBuilding@@QEAAXPEAVDataPanelLine@@@Z proc EXPORT
?_NV_dismantleButton_all@WallBuilding@@QEAAXPEAVDataPanelLine@@@Z endp

; WallBuilding::dismantleButton_all(class DataPanelLine *);
?dismantleButton_all@WallBuilding@@UEAAXPEAVDataPanelLine@@@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+14*8]
?dismantleButton_all@WallBuilding@@UEAAXPEAVDataPanelLine@@@Z endp

?_NV_addConstructionProgress@WallBuilding@@QEAAXM@Z proc EXPORT
?_NV_addConstructionProgress@WallBuilding@@QEAAXM@Z endp

; WallBuilding::addConstructionProgress(float);
?addConstructionProgress@WallBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+15*8]
?addConstructionProgress@WallBuilding@@UEAAXM@Z endp

?_NV_setConstructionProgress@WallBuilding@@QEAAXM@Z proc EXPORT
?_NV_setConstructionProgress@WallBuilding@@QEAAXM@Z endp

; WallBuilding::setConstructionProgress(float);
?setConstructionProgress@WallBuilding@@UEAAXM@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+16*8]
?setConstructionProgress@WallBuilding@@UEAAXM@Z endp

?_NV_notifyConstructionComplete@WallBuilding@@QEAAXXZ proc EXPORT
?_NV_notifyConstructionComplete@WallBuilding@@QEAAXXZ endp

; WallBuilding::notifyConstructionComplete();
?notifyConstructionComplete@WallBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+17*8]
?notifyConstructionComplete@WallBuilding@@UEAAXXZ endp

?_NV_addDismantleProgress@WallBuilding@@QEAA_NM@Z proc EXPORT
?_NV_addDismantleProgress@WallBuilding@@QEAA_NM@Z endp

; WallBuilding::addDismantleProgress(float);
?addDismantleProgress@WallBuilding@@UEAA_NM@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+18*8]
?addDismantleProgress@WallBuilding@@UEAA_NM@Z endp

?_NV_notifyConstructionDismantling@WallBuilding@@QEAAXXZ proc EXPORT
?_NV_notifyConstructionDismantling@WallBuilding@@QEAAXXZ endp

; WallBuilding::notifyConstructionDismantling();
?notifyConstructionDismantling@WallBuilding@@UEAAXXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+19*8]
?notifyConstructionDismantling@WallBuilding@@UEAAXXZ endp

?_NV_hitByMeleeAttack@WallBuilding@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
?_NV_hitByMeleeAttack@WallBuilding@@QEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

; WallBuilding::hitByMeleeAttack(enum CutDirection, class Damages &, class Character *, class CombatTechniqueData *, int);
?hitByMeleeAttack@WallBuilding@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+20*8]
?hitByMeleeAttack@WallBuilding@@UEAA?AW4HitMaterialType@@W4CutDirection@@AEAVDamages@@PEAVCharacter@@PEAVCombatTechniqueData@@H@Z endp

?_NV_getBuildState@WallBuilding@@QEAAPEAVConstructionState@Building@@XZ proc EXPORT
?_NV_getBuildState@WallBuilding@@QEAAPEAVConstructionState@Building@@XZ endp

; WallBuilding::getBuildState();
?getBuildState@WallBuilding@@UEAAPEAVConstructionState@Building@@XZ proc EXPORT
jmp function_pointers[_WallBuilding_base+21*8]
?getBuildState@WallBuilding@@UEAAPEAVConstructionState@Building@@XZ endp

; WallBuilding::runLinkingCheck(class ZoneMapContent *);
?runLinkingCheck@WallBuilding@@QEAAXPEAVZoneMapContent@@@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+22*8]
?runLinkingCheck@WallBuilding@@QEAAXPEAVZoneMapContent@@@Z endp

; WallBuilding::isALittleWallPartLikeACornerOrSomething();
?isALittleWallPartLikeACornerOrSomething@WallBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+23*8]
?isALittleWallPartLikeACornerOrSomething@WallBuilding@@QEAA_NXZ endp

; WallBuilding::isAShortWallPart();
?isAShortWallPart@WallBuilding@@QEAA_NXZ proc EXPORT
jmp function_pointers[_WallBuilding_base+24*8]
?isAShortWallPart@WallBuilding@@QEAA_NXZ endp

; WallBuilding::letsShare(class WallBuilding *);
?letsShare@WallBuilding@@QEAA_NPEAV1@@Z proc EXPORT
jmp function_pointers[_WallBuilding_base+25*8]
?letsShare@WallBuilding@@QEAA_NPEAV1@@Z endp
