
?_NV_getItemWeight@Weapon@@QEBAMXZ proc EXPORT
?_NV_getItemWeight@Weapon@@QEBAMXZ endp

; Weapon::getItemWeight();
?getItemWeight@Weapon@@UEBAMXZ proc EXPORT
jmp function_pointers[_Weapon_base+0*8]
?getItemWeight@Weapon@@UEBAMXZ endp

?_NV_getValueSingle@Weapon@@QEBAH_N@Z proc EXPORT
?_NV_getValueSingle@Weapon@@QEBAH_N@Z endp

; Weapon::getValueSingle(bool);
?getValueSingle@Weapon@@UEBAH_N@Z proc EXPORT
jmp function_pointers[_Weapon_base+1*8]
?getValueSingle@Weapon@@UEBAH_N@Z endp

; Weapon::getCategory();
?getCategory@Weapon@@QEBA?AW4WeaponCategory@@XZ proc EXPORT
jmp function_pointers[_Weapon_base+2*8]
?getCategory@Weapon@@QEBA?AW4WeaponCategory@@XZ endp

; Weapon::getCategory_animationOverride();
?getCategory_animationOverride@Weapon@@QEBA?AW4WeaponCategory@@XZ proc EXPORT
jmp function_pointers[_Weapon_base+3*8]
?getCategory_animationOverride@Weapon@@QEBA?AW4WeaponCategory@@XZ endp

; Weapon::is2HandedOnly();
?is2HandedOnly@Weapon@@QEBA_NXZ proc EXPORT
jmp function_pointers[_Weapon_base+4*8]
?is2HandedOnly@Weapon@@QEBA_NXZ endp

; Weapon::getCombatWeight();
?getCombatWeight@Weapon@@QEBAMXZ proc EXPORT
jmp function_pointers[_Weapon_base+5*8]
?getCombatWeight@Weapon@@QEBAMXZ endp

?_NV_getCraftTime@Weapon@@QEAAMXZ proc EXPORT
?_NV_getCraftTime@Weapon@@QEAAMXZ endp

; Weapon::getCraftTime();
?getCraftTime@Weapon@@UEAAMXZ proc EXPORT
jmp function_pointers[_Weapon_base+6*8]
?getCraftTime@Weapon@@UEAAMXZ endp

?_NV_getCraftMaterialMult@Weapon@@QEAAMXZ proc EXPORT
?_NV_getCraftMaterialMult@Weapon@@QEAAMXZ endp

; Weapon::getCraftMaterialMult();
?getCraftMaterialMult@Weapon@@UEAAMXZ proc EXPORT
jmp function_pointers[_Weapon_base+7*8]
?getCraftMaterialMult@Weapon@@UEAAMXZ endp

?_NV_isWeapon@Weapon@@QEAAPEAV1@XZ proc EXPORT
?_NV_isWeapon@Weapon@@QEAAPEAV1@XZ endp

; Weapon::isWeapon();
?isWeapon@Weapon@@UEAAPEAV1@XZ proc EXPORT
jmp function_pointers[_Weapon_base+8*8]
?isWeapon@Weapon@@UEAAPEAV1@XZ endp

?_NV_isSword@Weapon@@QEAAPEAVSword@@XZ proc EXPORT
?_NV_isSword@Weapon@@QEAAPEAVSword@@XZ endp

; Weapon::isSword();
?isSword@Weapon@@UEAAPEAVSword@@XZ proc EXPORT
jmp function_pointers[_Weapon_base+9*8]
?isSword@Weapon@@UEAAPEAVSword@@XZ endp

?_NV_isCrossbow@Weapon@@QEAAPEAVCrossbow@@XZ proc EXPORT
?_NV_isCrossbow@Weapon@@QEAAPEAVCrossbow@@XZ endp

; Weapon::isCrossbow();
?isCrossbow@Weapon@@UEAAPEAVCrossbow@@XZ proc EXPORT
jmp function_pointers[_Weapon_base+10*8]
?isCrossbow@Weapon@@UEAAPEAVCrossbow@@XZ endp

?_NV_getSkillModIndoors@Weapon@@QEBAHXZ proc EXPORT
?_NV_getSkillModIndoors@Weapon@@QEBAHXZ endp

; Weapon::getSkillModIndoors();
?getSkillModIndoors@Weapon@@UEBAHXZ proc EXPORT
jmp function_pointers[_Weapon_base+11*8]
?getSkillModIndoors@Weapon@@UEBAHXZ endp

?_CONSTRUCTOR@Weapon@@QEAAPEAV1@PEAVGameData@@00Vhand@@H@Z proc EXPORT
?_CONSTRUCTOR@Weapon@@QEAAPEAV1@PEAVGameData@@00Vhand@@H@Z endp

; Weapon::Weapon(class GameData *, class GameData *, class GameData *, class hand, int);
??0Weapon@@QEAA@PEAVGameData@@00Vhand@@H@Z proc EXPORT
jmp function_pointers[_Weapon_base+12*8]
??0Weapon@@QEAA@PEAVGameData@@00Vhand@@H@Z endp

?_DESTRUCTOR@Weapon@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@Weapon@@QEAAXXZ endp

; Weapon::~Weapon();
??1Weapon@@UEAA@XZ proc EXPORT
jmp function_pointers[_Weapon_base+13*8]
??1Weapon@@UEAA@XZ endp
