
?_CONSTRUCTOR@WeatherRegion@@QEAAPEAV1@PEAVAreaBiomeGroup@@@Z proc EXPORT
?_CONSTRUCTOR@WeatherRegion@@QEAAPEAV1@PEAVAreaBiomeGroup@@@Z endp

; WeatherRegion::WeatherRegion(class AreaBiomeGroup *);
??0WeatherRegion@@QEAA@PEAVAreaBiomeGroup@@@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+0*8]
??0WeatherRegion@@QEAA@PEAVAreaBiomeGroup@@@Z endp

?_DESTRUCTOR@WeatherRegion@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@WeatherRegion@@QEAAXXZ endp

; WeatherRegion::~WeatherRegion();
??1WeatherRegion@@QEAA@XZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+1*8]
??1WeatherRegion@@QEAA@XZ endp

; WeatherRegion::reset();
?reset@WeatherRegion@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+2*8]
?reset@WeatherRegion@@QEAAXXZ endp

; WeatherRegion::getWeatherInstance();
?getWeatherInstance@WeatherRegion@@QEBAPEAVWeatherInstance@@XZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+3*8]
?getWeatherInstance@WeatherRegion@@QEBAPEAVWeatherInstance@@XZ endp

; WeatherRegion::setCurrentSeason(int, int);
?setCurrentSeason@WeatherRegion@@QEAAXHH@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+4*8]
?setCurrentSeason@WeatherRegion@@QEAAXHH@Z endp

; WeatherRegion::getNewWeatherStrength();
?getNewWeatherStrength@WeatherRegion@@QEBAMXZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+5*8]
?getNewWeatherStrength@WeatherRegion@@QEBAMXZ endp

; WeatherRegion::update();
?update@WeatherRegion@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+6*8]
?update@WeatherRegion@@QEAAXXZ endp

; WeatherRegion::updateBT();
?updateBT@WeatherRegion@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+7*8]
?updateBT@WeatherRegion@@QEAAXXZ endp

; WeatherRegion::addListener(class WeatherRegion::Listener *);
?addListener@WeatherRegion@@QEAAXPEAVListener@1@@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+8*8]
?addListener@WeatherRegion@@QEAAXPEAVListener@1@@Z endp

; WeatherRegion::removeListener(class WeatherRegion::Listener *);
?removeListener@WeatherRegion@@QEAAXPEAVListener@1@@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+9*8]
?removeListener@WeatherRegion@@QEAAXPEAVListener@1@@Z endp

; WeatherRegion::addGlobalEffect(enum EffectType::Enum);
?addGlobalEffect@WeatherRegion@@QEAAXW4Enum@EffectType@@@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+10*8]
?addGlobalEffect@WeatherRegion@@QEAAXW4Enum@EffectType@@@Z endp

; WeatherRegion::getNewSeason();
?getNewSeason@WeatherRegion@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+11*8]
?getNewSeason@WeatherRegion@@QEAAXXZ endp

; WeatherRegion::weatherChanged(bool);
?weatherChanged@WeatherRegion@@QEAAX_N@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+12*8]
?weatherChanged@WeatherRegion@@QEAAX_N@Z endp

; WeatherRegion::updateWeatherEffects();
?updateWeatherEffects@WeatherRegion@@QEAAXXZ proc EXPORT
jmp function_pointers[_WeatherRegion_base+13*8]
?updateWeatherEffects@WeatherRegion@@QEAAXXZ endp

; WeatherRegion::save(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?save@WeatherRegion@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+14*8]
?save@WeatherRegion@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; WeatherRegion::load(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?load@WeatherRegion@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_WeatherRegion_base+15*8]
?load@WeatherRegion@@QEAAXPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp
