
?_CONSTRUCTOR@WindGeneratorBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
?_CONSTRUCTOR@WindGeneratorBuilding@@QEAAPEAV1@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@4@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

; WindGeneratorBuilding::WindGeneratorBuilding(class GameData *, const class Ogre::Vector3 &, const class Ogre::Quaternion &, class Faction *, const class hand &, const class hand &, class Layout *, class Building *);
??0WindGeneratorBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+0*8]
??0WindGeneratorBuilding@@QEAA@PEAVGameData@@AEBVVector3@Ogre@@AEBVQuaternion@3@PEAVFaction@@AEBVhand@@4PEAVLayout@@PEAVBuilding@@@Z endp

?_NV_getPowerOutput@WindGeneratorBuilding@@QEBAMXZ proc EXPORT
?_NV_getPowerOutput@WindGeneratorBuilding@@QEBAMXZ endp

; WindGeneratorBuilding::getPowerOutput();
?getPowerOutput@WindGeneratorBuilding@@UEBAMXZ proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+1*8]
?getPowerOutput@WindGeneratorBuilding@@UEBAMXZ endp

?_NV_getGUIState@WindGeneratorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIState@WindGeneratorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; WindGeneratorBuilding::getGUIState(class DatapanelGUI *, int);
?getGUIState@WindGeneratorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+2*8]
?getGUIState@WindGeneratorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getGUIPower@WindGeneratorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
?_NV_getGUIPower@WindGeneratorBuilding@@QEAAXPEAVDatapanelGUI@@H@Z endp

; WindGeneratorBuilding::getGUIPower(class DatapanelGUI *, int);
?getGUIPower@WindGeneratorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+3*8]
?getGUIPower@WindGeneratorBuilding@@UEAAXPEAVDatapanelGUI@@H@Z endp

?_NV_getSoundIntensity@WindGeneratorBuilding@@QEAAMXZ proc EXPORT
?_NV_getSoundIntensity@WindGeneratorBuilding@@QEAAMXZ endp

; WindGeneratorBuilding::getSoundIntensity();
?getSoundIntensity@WindGeneratorBuilding@@UEAAMXZ proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+4*8]
?getSoundIntensity@WindGeneratorBuilding@@UEAAMXZ endp

?_NV_isAnyInputsEmpty@WindGeneratorBuilding@@QEBA_NXZ proc EXPORT
?_NV_isAnyInputsEmpty@WindGeneratorBuilding@@QEBA_NXZ endp

; WindGeneratorBuilding::isAnyInputsEmpty();
?isAnyInputsEmpty@WindGeneratorBuilding@@UEBA_NXZ proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+5*8]
?isAnyInputsEmpty@WindGeneratorBuilding@@UEBA_NXZ endp

?_DESTRUCTOR@WindGeneratorBuilding@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@WindGeneratorBuilding@@QEAAXXZ endp

; WindGeneratorBuilding::~WindGeneratorBuilding();
??1WindGeneratorBuilding@@UEAA@XZ proc EXPORT
jmp function_pointers[_WindGeneratorBuilding_base+6*8]
??1WindGeneratorBuilding@@UEAA@XZ endp
