
; WorldEventStateQueryList::setupFrom(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?setupFrom@WorldEventStateQueryList@@QEAA_NPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_WorldEventStateQueryList_base+0*8]
?setupFrom@WorldEventStateQueryList@@QEAA_NPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; WorldEventStateQueryList::reset();
?reset@WorldEventStateQueryList@@QEAAXXZ proc EXPORT
jmp function_pointers[_WorldEventStateQueryList_base+1*8]
?reset@WorldEventStateQueryList@@QEAAXXZ endp

; WorldEventStateQueryList::isTrue();
?isTrue@WorldEventStateQueryList@@QEBA_NXZ proc EXPORT
jmp function_pointers[_WorldEventStateQueryList_base+2*8]
?isTrue@WorldEventStateQueryList@@QEBA_NXZ endp

?_CONSTRUCTOR@WorldEventStateQueryList@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@WorldEventStateQueryList@@QEAAPEAV1@XZ endp

; WorldEventStateQueryList::WorldEventStateQueryList();
??0WorldEventStateQueryList@@QEAA@XZ proc EXPORT
jmp function_pointers[_WorldEventStateQueryList_base+3*8]
??0WorldEventStateQueryList@@QEAA@XZ endp

?_DESTRUCTOR@WorldEventStateQueryList@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@WorldEventStateQueryList@@QEAAXXZ endp

; WorldEventStateQueryList::~WorldEventStateQueryList();
??1WorldEventStateQueryList@@QEAA@XZ proc EXPORT
jmp function_pointers[_WorldEventStateQueryList_base+4*8]
??1WorldEventStateQueryList@@QEAA@XZ endp
