
?_CONSTRUCTOR@WorldEventStateQuery@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@WorldEventStateQuery@@QEAAPEAV1@XZ endp

; WorldEventStateQuery::WorldEventStateQuery();
??0WorldEventStateQuery@@QEAA@XZ proc EXPORT
jmp function_pointers[_WorldEventStateQuery_base+0*8]
??0WorldEventStateQuery@@QEAA@XZ endp

; WorldEventStateQuery::getFromData(class GameData *);
?getFromData@WorldEventStateQuery@@SAPEAV1@PEAVGameData@@@Z proc EXPORT
jmp function_pointers[_WorldEventStateQuery_base+1*8]
?getFromData@WorldEventStateQuery@@SAPEAV1@PEAVGameData@@@Z endp

; WorldEventStateQuery::checkAllStatesInObject(class GameData *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &);
?checkAllStatesInObject@WorldEventStateQuery@@SA_NPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z proc EXPORT
jmp function_pointers[_WorldEventStateQuery_base+2*8]
?checkAllStatesInObject@WorldEventStateQuery@@SA_NPEAVGameData@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z endp

; WorldEventStateQuery::isTrue();
?isTrue@WorldEventStateQuery@@QEBA_NXZ proc EXPORT
jmp function_pointers[_WorldEventStateQuery_base+3*8]
?isTrue@WorldEventStateQuery@@QEBA_NXZ endp
