
?_CONSTRUCTOR@BaseLayout@wraps@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@@Z proc EXPORT
?_CONSTRUCTOR@BaseLayout@wraps@@QEAAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@@Z endp

; wraps::BaseLayout::BaseLayout(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class MyGUI::Widget *);
??0BaseLayout@wraps@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+0*8]
??0BaseLayout@wraps@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@@Z endp

; wraps::BaseLayout::initialise(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class MyGUI::Widget *, bool, bool);
?initialise@BaseLayout@wraps@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N2@Z proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+1*8]
?initialise@BaseLayout@wraps@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@_N2@Z endp

; wraps::BaseLayout::shutdown();
?shutdown@BaseLayout@wraps@@QEAAXXZ proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+2*8]
?shutdown@BaseLayout@wraps@@QEAAXXZ endp

; wraps::BaseLayout::FindParentPrefix(class MyGUI::Widget *);
?FindParentPrefix@BaseLayout@wraps@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+3*8]
?FindParentPrefix@BaseLayout@wraps@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVWidget@MyGUI@@@Z endp

; wraps::BaseLayout::snapToParent(class MyGUI::Widget *);
?snapToParent@BaseLayout@wraps@@QEAAXPEAVWidget@MyGUI@@@Z proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+4*8]
?snapToParent@BaseLayout@wraps@@QEAAXPEAVWidget@MyGUI@@@Z endp

; wraps::BaseLayout::_createFakeWidgetT(const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, class MyGUI::Widget *);
?_createFakeWidgetT@BaseLayout@wraps@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV34@@Z proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+5*8]
?_createFakeWidgetT@BaseLayout@wraps@@QEAAPEAVWidget@MyGUI@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV34@@Z endp

?_DESTRUCTOR@BaseLayout@wraps@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@BaseLayout@wraps@@QEAAXXZ endp

; wraps::BaseLayout::~BaseLayout();
??1BaseLayout@wraps@@UEAA@XZ proc EXPORT
jmp function_pointers[_wraps_BaseLayout_base+6*8]
??1BaseLayout@wraps@@UEAA@XZ endp
