
?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@H@Z proc EXPORT
?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@H@Z endp

; YesNoMaybe::YesNoMaybe(int);
??0YesNoMaybe@@QEAA@H@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+0*8]
??0YesNoMaybe@@QEAA@H@Z endp

?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@AEAV1@@Z proc EXPORT
?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@AEAV1@@Z endp

; YesNoMaybe::YesNoMaybe(class YesNoMaybe &);
??0YesNoMaybe@@QEAA@AEAV0@@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+1*8]
??0YesNoMaybe@@QEAA@AEAV0@@Z endp

?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@W4ynm@1@@Z proc EXPORT
?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@W4ynm@1@@Z endp

; YesNoMaybe::YesNoMaybe(enum YesNoMaybe::ynm);
??0YesNoMaybe@@QEAA@W4ynm@0@@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+2*8]
??0YesNoMaybe@@QEAA@W4ynm@0@@Z endp

?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@YesNoMaybe@@QEAAPEAV1@XZ endp

; YesNoMaybe::YesNoMaybe();
??0YesNoMaybe@@QEAA@XZ proc EXPORT
jmp function_pointers[_YesNoMaybe_base+3*8]
??0YesNoMaybe@@QEAA@XZ endp

; YesNoMaybe::operator bool();
??BYesNoMaybe@@QEBA_NXZ proc EXPORT
jmp function_pointers[_YesNoMaybe_base+4*8]
??BYesNoMaybe@@QEBA_NXZ endp

; YesNoMaybe::operator enum YesNoMaybe::ynm();
??BYesNoMaybe@@QEBA?AW4ynm@0@XZ proc EXPORT
jmp function_pointers[_YesNoMaybe_base+5*8]
??BYesNoMaybe@@QEBA?AW4ynm@0@XZ endp

; YesNoMaybe::operator==(enum YesNoMaybe::ynm);
??8YesNoMaybe@@QEBA_NW4ynm@0@@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+6*8]
??8YesNoMaybe@@QEBA_NW4ynm@0@@Z endp

; YesNoMaybe::operator!=(class YesNoMaybe);
??9YesNoMaybe@@QEBA_NV0@@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+7*8]
??9YesNoMaybe@@QEBA_NV0@@Z endp

; YesNoMaybe::operator!=(enum YesNoMaybe::ynm);
??9YesNoMaybe@@QEBA_NW4ynm@0@@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+8*8]
??9YesNoMaybe@@QEBA_NW4ynm@0@@Z endp

; YesNoMaybe::operator!=(bool);
??9YesNoMaybe@@QEBA_N_N@Z proc EXPORT
jmp function_pointers[_YesNoMaybe_base+9*8]
??9YesNoMaybe@@QEBA_N_N@Z endp

; YesNoMaybe::toInt();
?toInt@YesNoMaybe@@QEAAHXZ proc EXPORT
jmp function_pointers[_YesNoMaybe_base+10*8]
?toInt@YesNoMaybe@@QEAAHXZ endp
