
?_CONSTRUCTOR@ZoneSpacialGrid@@QEAAPEAV1@XZ proc EXPORT
?_CONSTRUCTOR@ZoneSpacialGrid@@QEAAPEAV1@XZ endp

; ZoneSpacialGrid::ZoneSpacialGrid();
??0ZoneSpacialGrid@@QEAA@XZ proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+0*8]
??0ZoneSpacialGrid@@QEAA@XZ endp

?_DESTRUCTOR@ZoneSpacialGrid@@QEAAXXZ proc EXPORT
?_DESTRUCTOR@ZoneSpacialGrid@@QEAAXXZ endp

; ZoneSpacialGrid::~ZoneSpacialGrid();
??1ZoneSpacialGrid@@QEAA@XZ proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+1*8]
??1ZoneSpacialGrid@@QEAA@XZ endp

; ZoneSpacialGrid::add(class RootObject *);
?add@ZoneSpacialGrid@@QEAAIPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+2*8]
?add@ZoneSpacialGrid@@QEAAIPEAVRootObject@@@Z endp

; ZoneSpacialGrid::remove(class RootObject *);
?remove@ZoneSpacialGrid@@QEAA_NPEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+3*8]
?remove@ZoneSpacialGrid@@QEAA_NPEAVRootObject@@@Z endp

; ZoneSpacialGrid::update(class RootObject *);
?update@ZoneSpacialGrid@@QEAA?AW4Result@1@PEAVRootObject@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+4*8]
?update@ZoneSpacialGrid@@QEAA?AW4Result@1@PEAVRootObject@@@Z endp

; ZoneSpacialGrid::getObjects(const class Ogre::Vector3 &, float, class lektor<RootObject *> &, int);
?getObjects@ZoneSpacialGrid@@QEBAHAEBVVector3@Ogre@@MAEAV?$lektor@PEAVRootObject@@@@H@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+5*8]
?getObjects@ZoneSpacialGrid@@QEBAHAEBVVector3@Ogre@@MAEAV?$lektor@PEAVRootObject@@@@H@Z endp

; ZoneSpacialGrid::getObjects(const class Ogre::Vector3 &, float, int, class lektor<RootObject *> &, int);
?getObjects@ZoneSpacialGrid@@QEBAHAEBVVector3@Ogre@@MHAEAV?$lektor@PEAVRootObject@@@@H@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+6*8]
?getObjects@ZoneSpacialGrid@@QEBAHAEBVVector3@Ogre@@MHAEAV?$lektor@PEAVRootObject@@@@H@Z endp

; ZoneSpacialGrid::addZone(class ZoneMap *);
?addZone@ZoneSpacialGrid@@QEAAXPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+7*8]
?addZone@ZoneSpacialGrid@@QEAAXPEAVZoneMap@@@Z endp

; ZoneSpacialGrid::removeZone(class ZoneMap *);
?removeZone@ZoneSpacialGrid@@QEAAXPEAVZoneMap@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+8*8]
?removeZone@ZoneSpacialGrid@@QEAAXPEAVZoneMap@@@Z endp

; ZoneSpacialGrid::getZoneKey(const class Ogre::Vector3 &);
?getZoneKey@ZoneSpacialGrid@@QEBAIAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+9*8]
?getZoneKey@ZoneSpacialGrid@@QEBAIAEBVVector3@Ogre@@@Z endp

; ZoneSpacialGrid::getCellKey(class ZoneMap *, const class Ogre::Vector3 &);
?getCellKey@ZoneSpacialGrid@@QEBAIPEAVZoneMap@@AEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+10*8]
?getCellKey@ZoneSpacialGrid@@QEBAIPEAVZoneMap@@AEBVVector3@Ogre@@@Z endp

; ZoneSpacialGrid::getFullKey(const class Ogre::Vector3 &);
?getFullKey@ZoneSpacialGrid@@QEBAIAEBVVector3@Ogre@@@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+11*8]
?getFullKey@ZoneSpacialGrid@@QEBAIAEBVVector3@Ogre@@@Z endp

; ZoneSpacialGrid::initialiseGrid(float);
?initialiseGrid@ZoneSpacialGrid@@QEAAXM@Z proc EXPORT
jmp function_pointers[_ZoneSpacialGrid_base+12*8]
?initialiseGrid@ZoneSpacialGrid@@QEAAXM@Z endp
